### ISSUE TITLE
documentation: list pyprojectx as alternative to install PDM

### ISSUE THREAD

**Issue by houbie** [pdm-project/pdm#1004]
[Pyprojectx](https://pyprojectx.github.io/) provides a wrapper script that bootstraps the installation of all the development tools used in a project. As such it has the ability to install PDM on demand.

The benefits:
- you can clone and build a project without having to install PDM first
- you can lock the PDM version: this makes your project immune for breaking changes in PDM; as developer you don't need to install/select the required version
- projects become beginner-friendly as nothing needs to be set up

Pyprojectx has a [PDM initializer](https://pyprojectx.github.io/usage/#pdm-project): it installs PDM locally inside the project and starts `pdm init`

The [px-demo](https://github.com/pyprojectx/px-demo) project shows how you can build a PDM project in a minute:
```
git clone https://github.com/pyprojectx/px-demo.git
cd px-demo
./pw build
```

IMO it makes sense to add this to the documentation.

**Comment by frostming** [comment]
Sure, it is a nice tool! Would you like to make the PR?

**Comment by houbie** [comment]
Will do that
