### ISSUE TITLE
Potential checksum mismatch on Windows

### ISSUE THREAD

**Issue by Philogicatician** [pdm-project/pdm#1005]
After following the instructions on [this page](https://pdm.fming.dev/), and learning that Windows PowerShell can give checksum values with
```powershell
Get-FileHash -Path c:\path\to\pdm.exe -Algorithm SHA256
```
I'm wondering if there's a typo in the checksum listed in the documentation on pdm.fming.dev?  On the website, it lists 
```
70ac95c53830ff41d700051c9caebd83b2b85b5d6066e8f853006f9f07293ff0
```

But the sha256 hash given by PowerShell is 
```
FF247DBA44F20D327C7665550CB4323A80155196D474D9671EBC833F2850E8F2
```

There's another way to get sha256 hashes via the command prompt in Windows by using
```console
certutil -hashfile C:\path\to\pdm.exe SHA256
```
but it yields the same thing as PowerShell.  I scanned the file with Bitdefender antivirus software and even did a system wide scan, but everything looks fine.  

Is it possible the sha256 checksum listed on the website is outdated?

**Comment by frostming** [comment]
Sorry I failed to mention it is the checksum of https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py.

**Comment by Philogicatician** [comment]
@frostming Oh, that makes sense.  Do you happen to know how ones runs the checksum for an online file?
