### ISSUE TITLE
Scipy cannot be installed (without virtual env)

### ISSUE THREAD

**Issue by Philogicatician** [pdm-project/pdm#1007]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. Create a new, empty directory.
2. Run `pdm init`.
3. Use default settings.
4. Run `pdm add scipy`

## Actual behavior

PDM successfully installs numpy 1.22.3 (a dependency for scipy) but fails to install scypi 1.6.1.

## Expected behavior

PDM to install scypi 1.6.1 successfully without needing a virtual environment.

## Environment Information
```powershell
# Output of `pdm info `:
PDM version:        1.13.6
Python Interpreter: C:\Python310\python.EXE (3.10)
Project Root:       C:/Users/kevin/Desktop/Python Programming Projects/PDM_Testing
Project Packages:   C:\Users\kevin\Desktop\Python Programming Projects\PDM_Testing\__pypackages__\3.10

#Output of `pdm info --env`:
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.2",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19044",
  "python_full_version": "3.10.2",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "win32"
}
```

**Comment by Philogicatician** [comment]
Okay, here's the detailed debug log:

[pdm-install-p462x025.log](https://github.com/pdm-project/pdm/files/8384804/pdm-install-p462x025.log)

**Comment by frostming** [comment]
It seems missing some requirements for building. Can you install successfully with pip?

**Comment by Philogicatician** [comment]
Huh, apparently not, it gives me the following in PowerShell:

```powershell
PS C:\Users\kevin> pip install scipy
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
Collecting scipy
  Downloading scipy-1.8.0-cp310-cp310-win_amd64.whl (37.0 MB)
     ---------------------------------------- 37.0/37.0 MB 10.6 MB/s eta 0:00:00
Collecting numpy<1.25.0,>=1.17.3
  Using cached numpy-1.22.3-cp310-cp310-win_amd64.whl (14.7 MB)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
Installing collected packages: numpy, scipy
  WARNING: Failed to write executable - trying to use .deleteme logic
ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python310\\Scripts\\f2py.exe' -> 'C:\\Python310\\Scripts\\f2py.exe.deleteme'

WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)

```

**Comment by Philogicatician** [comment]
Ah, but it did work when going to root:
```powershell
PS C:\Windows\system32> pip install scipy
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
Collecting scipy
  Using cached scipy-1.8.0-cp310-cp310-win_amd64.whl (37.0 MB)
Requirement already satisfied: numpy<1.25.0,>=1.17.3 in c:\python310\lib\site-packages (from scipy) (1.22.3)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
Installing collected packages: scipy
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
Successfully installed scipy-1.8.0
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
```

**Comment by Philogicatician** [comment]
But going back to my PDM_Testing directory, deleting everything, and trying to use `pdm init` followed by `pdm add scipy` still gave a build error.  Below is the detailed log for that attempt:
[pdm-install-625h9dvj.log](https://github.com/pdm-project/pdm/files/8385388/pdm-install-625h9dvj.log)

**Comment by frostming** [comment]
Scipy 1.6.1 [doesn't provide a pre-built wheel](https://pypi.org/project/scipy/1.6.1/#files) for `3.10-win_amd64` so you have to compile from source, but the build requirements are not met. You should see the exact same error if you install with `pip install scipy==1.6.1`

Scipy 1.8.0 has pre-built wheels but it is excluded by the resolve since it supports a maximum python version of `<3.11` but your project doesn't have the same constraints.

**Comment by pikeas** [comment]
Just ran into this on MacOS. 

A Python constraint of `requires-python = ">=3.10"` causes the solver to choose scipy 1.6, which fails to install. Changing this to `requires-python = ">=3.10,<3.11"` picks up scipy 1.9, which installs successfully.
