### ISSUE TITLE
Keep toml file indent while executing pdm command

### ISSUE THREAD

**Issue by RollingSnack** [pdm-project/pdm#1009]
Before I ran `pdm add -d xxx`, it looks like this:

![a1](https://user-images.githubusercontent.com/22791898/161061248-c6ccd055-0bfd-451e-a91d-ee9d23ac4be6.png)

And after:

![a2](https://user-images.githubusercontent.com/22791898/161061338-d405b1d7-74aa-4694-8bc7-63b094b89d56.png)

Is it possible to keep the brackets aligned?

**Comment by frostming** [comment]
This was fixed upstream and released, you need to upgrade the `tomlkit` to `0.10.2` depended by PDM. Or simply reinstall PDM.

**Comment by frostming** [comment]
> I'm still seeing a similar issue with pdm 2.1.5 and tomlkit 0.11.5, 2 space indent gets changed to 4 on `pdm add`.

It is not the same as described in this issue. PDM doesn't keep the indentation length on `add` but rather *normalizes* it to 4 spaces, we are not changing this.

**Comment by frostming** [comment]
> But I don't think it makes sense to force it on a configuration file just because it's the standard for Python source files. PEP 8 doesn't say pyproject.toml should be indented using 4 spaces, and PDM is supposed to be a package manager, not an opinionated linter. 🤷‍♀️

Please don't take things for granted, `tomlkit` is THE ONLY Python toml writer that keeps the styles and formats. People have their own tastes in TOML styles, no one can make them all happy. Some would want the dependencies array in a single line and others want each in a line. Some may want the dependencies *sorted* and others would like to keep what they input.

IMO a small normalization for the dependencies array(yeah, not for other fields) from the PDM side can make it more consistent and less noise in the commit diff. I just brings more benefit than problems.
