### ISSUE TITLE
Automatically add type packages

### ISSUE THREAD

**Issue by lyz-code** [pdm-project/pdm#1015]
## Is your feature request related to a problem? Please describe.

Some packages don't ship their typing information (`requests`, `click`, `tabulate`) so whenever I want to add them I need to run two pdm commands

```bash
pdm add requests
pdm add -G typing types-requests
```

## Describe the solution you'd like

It would be awesome if `pdm` had a configuration option to download the `types-*` of packages that don't ship their typings. So whenever you do `pdm add requests` it would add the `types-requests` into the `typing` group. 

I understand that this can easily be seen as a super specific corner case and that running two commands is not that bad. If it's the case I don't have any problem closing the issue.

Thanks!

**Comment by pawamoy** [comment]
> I understand that this can easily be seen as a super specific corner case and that running two commands is not that bad. If it's the case I don't have any problem closing the issue.

That would be my opinion indeed, even though I *do* use mypy and types- packages! 😄 
Seems like a lot of difficult, unpredictable things to handle for few benefits.
Maybe that could be experimented on with a plugin though!

**Comment by lyz-code** [comment]
makes total sense, If I gather the forces to make the plugin I'll advertise it here
