### ISSUE TITLE
Removing Dependencies Fail with Global Interpreter

### ISSUE THREAD

**Issue by robml** [pdm-project/pdm#1021]
- [ X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Installed a series of packages like `numpy` and `pandas` on my global interpreter running `pdm` version `1.13.4`, and when trying to remove them it failed to remove any of the dependencies (due to a permission error with a "METADATA" file). The main issue is running `pdm list -g` shows all the dependencies, which I checked in the `/usr/bin/` folder ARE indeed there, however are removed from the `pyproject.toml` file from the associated global project and so `pdm remove -g` does not work.

## Actual behavior

Running something like `pdm remove -g jupyterlab` returns
```
Removing packages from default dependencies: jupyterlab
[ProjectError]: jupyterlab does not exist in default dependencies.
```
Although it appears in `pdm list -g`

## Expected behavior

Expected for the packages and their respective dependencies to be removed, or if not, to leave the `pyproject.toml` file unaltered.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:


PDM version:        1.13.4
Python Interpreter: /usr/bin/python3.8 (3.8)
Project Root:       /home/robmel/.pdm/global-project
Project Packages:   None
```

**Comment by frostming** [comment]
`pdm remove` can only remove dependencies listed in `pyproject.toml`, all child dependencies will be removed as a side effect, but you cannot pass intermediate dependencies to `pdm remove`.
