### ISSUE TITLE
[FR] Generate an arm64 based docker image

### ISSUE THREAD

**Issue by stephengolub** [pdm-project/pdm#1025]
## Is your feature request related to a problem? Please describe.

I was trying to build a project that was using the pdm docker image to build a project on my M1 Mac and it wouldn't work due to the arm architecture and the pdm image only being build with amd64 as a target.

## Describe the solution you'd like

It'd be nice if the official docker image to be built using the multiarch capabilities to support amd64 and arm64.

**Comment by frostming** [comment]
We no longer maintain a official docker image and it was removed from the documentation. You can build your own image from a source image like `python:3` following the [guide](https://pdm.fming.dev/usage/advanced/#use-pdm-in-a-multi-stage-dockerfile)

**Comment by stephengolub** [comment]
Good to know. thanks!
