### ISSUE TITLE
Publish Dockerfile

### ISSUE THREAD

**Issue by dylanraithel** [pdm-project/pdm#1026]
## Dockerfile question

Hi Frostming, PDM is amazing so far and I'd like to use your dockerhub image. I noticed it's not documented in this repo though so I wanted to ask if it's still going to be pushed to Dockerhub and listed as an artifact in the source repo here. It hasn't been updated in 9 months. What would you propose using instead if the pdm image is no longer needed? Just a generic python image with pdm installed as a pip package?

**Comment by frostming** [comment]
https://github.com/pdm-project/pdm/issues/1025#issuecomment-1092931816

> We no longer maintain an official docker image and it was removed from the documentation. You can build your own image from a source image like `python:3` following the [guide](https://pdm.fming.dev/usage/advanced/#use-pdm-in-a-multi-stage-dockerfile)

**Comment by acalvino4** [comment]
Above link to guide is broken. New location is here: https://pdm.fming.dev/latest/usage/advanced/#use-pdm-in-a-multi-stage-dockerfile
