### ISSUE TITLE
Documentation for enabling PEP582 globally could be more clear

### ISSUE THREAD

**Issue by ZenPylon** [pdm-project/pdm#1033]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Run 

```bash
pdm --pep582
```

## Actual behavior

The docs say to run `pdm --pep582` to [enable PEP582 globally,](https://pdm.fming.dev/#for-mac-and-linux-users) but running this only prints the script:

```bash
if [ -n "$PYTHONPATH" ]; then
    export PYTHONPATH='/usr/local/Cellar/pdm/1.13.6/libexec/lib/python3.10/site-packages/pdm/pep582':$PYTHONPATH
else
    export PYTHONPATH='/usr/local/Cellar/pdm/1.13.6/libexec/lib/python3.10/site-packages/pdm/pep582'
fi
```

## Expected behavior

I'm guessing this is just a documentation issue. The README file in this GitHub mentions `eval "$(pdm --pep582)`, and this does indeed function as expected. When I `echo $PYTHONPATH` after running that, the expected path to pep582 is printed.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

PDM version:        1.13.6
Python Interpreter: /usr/local/Cellar/pdm/1.13.6/libexec/bin/python3.10 (3.10)
Project Root:       /Users/<my-user>/<my-dir>
Project Packages:   /Users/<my-user>/<my-dir>/__pypackages__/3.10

{
  "implementation_name": "cpython",
  "implementation_version": "3.10.2",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "20.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 20.6.0: Wed Jan 12 22:22:42 PST 2022; root:xnu-7195.141.19~2/RELEASE_X86_64",
  "python_full_version": "3.10.2",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}

```

**Comment by cye18** [comment]
I think the document is quite clear about enabling PEP582. It seems you followed the instruction for Windows machine on a Linux one. If you run `pdm --pep582 >> ~/.bash_profile` as instructed, it should be working. Reference: https://pdm.fming.dev/#for-mac-and-linux-users
