### ISSUE TITLE
How to debug django in pycharm

### ISSUE THREAD

**Issue by lightlogic5** [pdm-project/pdm#1035]
![image](https://user-images.githubusercontent.com/12095814/162975358-f118ff93-95fd-4ba1-89f5-8ec29f6152f6.png)
![image](https://user-images.githubusercontent.com/12095814/162975665-a8aa0a7e-e601-4600-b3f4-eeb19122d2ef.png)

**Comment by frostming** [comment]
Did you mark the lib folder as sources root?
> Mark `__pypackages__/<major.minor>/lib` as [Sources Root](https://www.jetbrains.com/help/pycharm/configuring-project-structure.html#mark-dir-project-view). Then, select as [Python interpreter](https://www.jetbrains.com/help/pycharm/configuring-python-interpreter.html#interpreter) a Python installation with the same <major.minor> version.

**Comment by lightlogic5** [comment]
> 您是否将 lib 文件夹标记为源根目录？
> 
> > 标记`__pypackages__/<major.minor>/lib`为[Sources Root](https://www.jetbrains.com/help/pycharm/configuring-project-structure.html#mark-dir-project-view)。然后，选择具有相同 <major.minor> 版本的 Python 安装作为[Python 解释器。](https://www.jetbrains.com/help/pycharm/configuring-python-interpreter.html#interpreter)

![image](https://user-images.githubusercontent.com/12095814/163363915-6c1a4be5-70d1-40cc-ae55-a7c85da18bed.png)
thank you:
yes,i mark  `__pypackages__/3.10/lib` as sources root ,and select the python interpreter
![image](https://user-images.githubusercontent.com/12095814/163364523-ee8133cc-7488-41fd-8592-c873a5aed9d7.png)

**Comment by pawamoy** [comment]
You probably shouldn't use the interpreter of the PDM venv though, no? Don't you have a global interpreter installed?

**Comment by lightlogic5** [comment]
> You probably shouldn't use the interpreter of the PDM venv though, no? Don't you have a global interpreter installed?

I modified it to global interpreter
![image](https://user-images.githubusercontent.com/12095814/163670610-8dd5ee23-add0-4b38-9f42-2d6f1f7505d8.png)
![image](https://user-images.githubusercontent.com/12095814/163670660-01eb92b7-b4dc-48f5-adc8-ae50fef6d48e.png)
But it still reports an error

**Comment by frostming** [comment]
`import django` is run before the sys.path manipulation.
