### ISSUE TITLE
Running xonsh with pdm causes issues

### ISSUE THREAD

**Issue by DUOLabs333** [pdm-project/pdm#1040]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
1. Install xonsh with PDM.
2. Run it with `pdm run xonsh`.
3. In the shell, type `$(ls)`.
4. See that it immediately crashes
## Actual behavior
Running `$()` syntax lines causes xonsh to fork.

## Expected behavior
It will not fork, but continue normally.

## Environment Information

```
PDM version:        1.14.0
Python Interpreter: /usr/bin/python (3.10)
Project Root:       /home/system/PDM/xonsh
Project Packages:   /home/system/PDM/xonsh/__pypackages__/3.10

```

**Comment by DUOLabs333** [comment]
This seems to be due to the fact that PDM starts acting weird with subprocesses.

**Comment by DUOLabs333** [comment]
After some more digging, it seems that pdm just put the process in the background: `fg` brings them back with the output.

**Comment by DUOLabs333** [comment]
Running `PYTHONPATH=/home/system/.local/lib/python3.10/site-packages/pdm/pep582 /home/system/PDM/xonsh/__pypackages__/3.10/bin/xonsh` works fine.

**Comment by DUOLabs333** [comment]
This seems to be a python issue: doing `subprocess.run("YTHONPATH=/home/system/.local/lib/python3.10/site-packages/pdm/pep582 /home/system/PDM/xonsh/__pypackages__/3.10/bin/xonsh")` replicates the issue.

**Comment by frostming** [comment]
I have never played with a shell tool in PDM and I will regard this as a corner case. If there is anyone who encounters this issue and is interested in improving, I am open to PRs.

**Comment by agoose77** [comment]
@DUOLabs333 as an aside (and as a xonsh user), xonsh does some pretttty crazy things that I wouldn't be surprised if this is a bug on the xonsh side of things.

**Comment by DUOLabs333** [comment]
Yeah, I just gave up trying to get it to work (as an aside, I got it to work by manually setting the PYTHONPATH and PATH), and just went with ipython instead.
