### ISSUE TITLE
Add option to pdm Sync to fails if lock is outdated

### ISSUE THREAD

**Issue by SirMartin** [pdm-project/pdm#1048]
## Is your feature request related to a problem? Please describe.

I think it could be awesome if it is possible to have a _strict_ option added to **sync** that fails if the lock file is outdated, so always can ensure you force to make a lock before, and never install outdated versions.

## Describe the solution you'd like

Add an option to the sync command (something like **strict** for example) that if the lock file is outdated, instead of continuing with the synchronization, just stops the process. Failing with an exit code so if runs in a docker, for example, stop the build process.

**Comment by frostming** [comment]
`pdm install --check` is what you want.

Basically `pdm install` is a wrapper around `pdm sync`, the latter is more like an atomic action.
