### ISSUE TITLE
Replacing editable package with pypi version does not remove editable entry from pyproject.toml

### ISSUE THREAD

**Issue by jeverling** [pdm-project/pdm#1050]
Hi, thanks for the great project!

I'm not sure whether this is a bug or expected behavior.
When I _add_ a package as editable, and then later _add_ the pypi version of the same package, both remain in `pyproject.toml -> [project] -> dependencies`.

`pdm remove <package>` removes both instances from `pyproject.toml`.

I would expect the "editable" entry to be removed once the pypi version is added, but maybe that does not happen purpose.

**Comment by frostming** [comment]
you may need `--no-editable`

`pdm add --no-editable package` will override the given package and `pdm sync --no-editable` will replace all with non-editable ones
