### ISSUE TITLE
Python 2 compatibility

### ISSUE THREAD

**Issue by pawamoy** [pdm-project/pdm#1056]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

Unless I'm missing something, this [commit](https://github.com/pdm-project/pdm/commit/4bb1c7cc9895f2c860a6b4df559ca03e2a2b828f#diff-31ec4f7f379360a03c27efc73a970a3187c5ebb6e2b0275932687324e18de915) added functions with return annotations in `pdm/models/in_process/sysconfig_get_paths.py`, which are not Python 2 compatible.

```console
$ pdm lock
⠇ Resolving: new pin click 6.7
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/models/in_process/sysconfig_get_paths.py", line 7
    def _running_under_venv() -> bool:
                              ^
See /tmp/pdm-lock-ufx9xc2n.log for detailed debug log.
[CalledProcessError]: Command '['/usr/bin/python2.7', '-Es', '/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/models/in_process/sysconfig_get_paths.py', 'prefix']' returned non-zero exit status 1.
Add '-v' to see the detailed traceback
```

## Steps to reproduce

Setup a project with `requires-python = "<3"` and try to lock dependencies.

## Actual behavior

Syntax error on the `-> bool` part.

## Environment Information

```bash
PDM version:        1.14.1
Python Interpreter: /usr/bin/python2.7 (2.7)
Project Root:       /home/user/data/dev/project
Project Packages:   /home/user/data/dev/project/__pypackages__/2.7
```

**Comment by frostming** [comment]
Thanks
