### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by yalunren** [pdm-project/pdm#1060]
Hello, 

I just installed PDM and tried to run a test script.

It only has one line code.

`from web3 import Web3`

Then I run

`>>>pdm run python3 test.py`

The error shows it can't find the module pkg_resources.

```
Traceback (most recent call last):
  File "/Users/abc/code/eth/test.py", line 1, in <module>
    from web3 import Web3
  File "/Users/abc/code/eth/__pypackages__/3.10/lib/web3/__init__.py", line 4, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

When I run it directly from python3

`>>>python3 test.py`

```
Traceback (most recent call last):
  File "/Users/abc/code/eth/test.py", line 1, in <module>
    from web3 import Web3
ModuleNotFoundError: No module named 'web3'
```

pkg_resources is a default package in python and it imports fine when run directly using python command.
```
Python 3.10.4 (v3.10.4:9d38120e33, Mar 23 2022, 17:29:05) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkg_resources
>>> 
```

I guess it might be a path problem but not sure how to fix it.

Anyone can help?

Thanks!

**Comment by cye18** [comment]
If you search online, you'll find `pkg_resources` is part of `setuptools`.

When I see this error, typically `pdm add setuptools` fixes it.

Hope it helps 🙂

**Comment by pawamoy** [comment]
It's a common packaging mistake (forget to depend on setuptools), because until recently setuptools was used and installed almost all of the time. That's not the case anymore and these packages should fix their build dependencies :slightly_smiling_face:

**Comment by yalunren** [comment]
> If you search online, you'll find `pkg_resources` is part of `setuptools`.
> 
> When I see this error, typically `pdm add setuptools` fixes it.
> 
> Hope it helps 🙂
> 
> Not sure if it's something that PDM could improve to avoid, since it seems to be a kind of common issue when `setuptools` is involved 😉 Thanks!

Thanks! 

If I run a file direct by using `python test.py` the import is fine. So it seems pkg_resources is installed at system level.

I also tried the `PDM add setuptools` method. It did solve the pkg_resources problem. However, during runtime, another dependency issue shows up.

```
Traceback (most recent call last):
  File "/Users/abc/code/eth/test.py", line 2, in <module>
    w3 = Web3(EthereumTesterProvider())
  File "/Users/abc/code/eth/__pypackages__/3.10/lib/web3/providers/eth_tester/main.py", line 69, in __init__
    from eth_tester import EthereumTester  # noqa: F811
ModuleNotFoundError: No module named 'eth_tester'
```

It seems that the path configuration still has problem when the file trying to import it's own package 'eth_tester'. 

Pls advise how to fix it, thanks!

**Comment by pawamoy** [comment]
This dependency is part of the `tester` extra: https://github.com/ethereum/web3.py/blob/master/setup.py#L9 

In your pyproject.toml you can change your web3 dependency to include the extra: `web3[tester]`.

**Comment by yalunren** [comment]
> This dependency is part of the `tester` extra: https://github.com/ethereum/web3.py/blob/master/setup.py#L9
> 
> In your pyproject.toml you can change your web3 dependency to include the extra: `web3[tester]`.

It worked after I add the tester package. Thanks a lot!
