### ISSUE TITLE
pdm import -f setuppy

### ISSUE THREAD

**Issue by jnoortheen** [pdm-project/pdm#1062]
## Is your feature request related to a problem? Please describe.

As of `v1.14.1` this is not implemented. 

## Describe the solution you'd like

There is [a library](https://github.com/asottile/setup-py-upgrade) that implements similar functionality already . pdm can vendor this or use similar approach or can make this a plugin .

**Comment by frostming** [comment]
The AST parsing approach might be not robust enough and have lots of corner cases to deal with. The only reliable way to get project metadata from a `setup.py` is to run a `setup.py egg_info` command.

**Comment by frostming** [comment]
Closed by #1137, please test it on [`2.0.0a1`](https://github.com/pdm-project/pdm/releases/tag/2.0.0a1)
