### ISSUE TITLE
RFE: provide sphinx support

### ISSUE THREAD

**Issue by kloczek** [pdm-project/pdm#1068]
Curretnly looks like `pdm` has documentation magaged using `mkdoc`.
It would be really good to move to `sphix`. Rerason for such migration is that `mkdoc` has only possibility to generate only html documentation
On packaging pythion modules if module has sphinx based documentation I'm generating that doc as man pages because it is still basic documentation format on all unix platforms.

**Comment by pawamoy** [comment]
On Material for MkDocs sites:

- type "s"
- type your string

:smile: 

Ref: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#keyboard-shortcuts

Though you still have to go to the docs site, so yeah, typing `man 7 pdm-docs` is faster :slightly_smiling_face: 

Well, maybe someone can write a MkDocs plugin to generate man pages (and that someone might be me haha).

Anyway, switching to Sphinx just for this niche use case would be a huge regression IMO, so I'm voting against.

**Comment by kloczek** [comment]
> Though you still have to go to the docs site, so yeah, typing man 7 pdm-docs is faster 🙂

.. and mkdoc produces mutifile html documentation.
Issue is that I've already have man pages documentation in case of all python modules 
```console
[tkloczko@devel-g2v SPECS]$ grep %sphinx_build_man python-*.spec | wc -l; ls -1 python-*.spec| wc -l
520
918
```

**Comment by frostming** [comment]
Switching to sphinx is not planned.

**Comment by kloczek** [comment]
I've not been asking to swich to sphinx.
mkdoc and sphinx support can be provided without collision.
All what needs to be added is conf.py files.

**Comment by pawamoy** [comment]
For what benefit? API docs can be injected/autogenerated with MkDocs as well. In fact PDM already takes advantage of that, see for example https://pdm.fming.dev/latest/plugin/reference/

**Comment by kloczek** [comment]
mkdoc is not abble to provide anthing else than html and pdf.
sphisx can produce +15 formats and I'm producing all modules sphins generated docuementation as man page (which is still most commone documentation format on unix platforms).
mkdoc is not able to generate roff output.
```console
[tkloczko@devel-g2v SPECS]$ ls -1 python-*|wc -l; grep %sphinx_build_man python-*|wc -l
981
538
```
as you see more than half my packageed python modules uses that format.

**Comment by kloczek** [comment]
Just ins case. In the same population of python modules mkdoc is used by only SEVEN modules.

**Comment by pawamoy** [comment]
I don't know what your command is supposed to do or show. You did not provide an example Sphinx docs site that provides man pages. And yes of course more Python packages are using Sphinx, since Sphinx is a mature solution that has been around and wildely used for more than a decade. That does not mean it will always be better than alternatives such as MkDocs.

**Comment by kloczek** [comment]
You may not be aware of that but man command still beats opening web browset -> wntering URL where is documentation in html format -> predss ctrl-f to enter pharese which you want to find.
That is why html it is only ONLINE format of docuemnation.

Other thing is that as long as you are using html doc it does not mean that other people repper other formats.

**Comment by kloczek** [comment]
>You're still not providing the info I need to understand your use-case, and help you find a solution/workaround... Unless you can show me an example, I won't be able to help.

Please don't try to solve World Hunger issue using your module code.

I'm working on Linux/Solaris distribution in which all possible sphinx documentation of the python modules is build and packaged as man pages.
I'm not adking you to solve my problemns and I'm n ot asking for help.
If you don't care anbout better OOTB support on systems cut off from public network that is perfecly reasonable justitication.
