### ISSUE TITLE
Seemingly incorrect failure to install pandas 

### ISSUE THREAD

**Issue by jayvdb** [pdm-project/pdm#1071]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

I had a `Pipfile` like

```
[packages]
...
pandas = "~=1.2.4"
...

[requires]
python_version = "3.7"
```

And did an import, and all looked lovely in `pyproject.toml` except it was now `requires-python = ">=3.7"` which isnt the same.

Then `pdm install` failed with the output below.

As can be seen at https://github.com/pandas-dev/pandas/blob/v1.2.5/setup.py#L742 , pandas v1.2.5 does support Python v3.7.

I changed the `pyproject.toml` to `requires-python = "==3.7.13"` and the pandas problem disappeared.

## Actual behavior

```
Lock file does not exist
Updating the lock file...
Resolving: new pin python >=3.7
...
Resolving: new pin numpy 1.20.3
🔒 Lock failed
Unable to find a resolution because the following dependencies don't work on all Python versions defined by the project's `requires-python`: >=3.7
  python>=3.7.1 (from <Candidate pandas 1.2.4 from https://pypi.org/simple/pandas/>)
  python>=3.7.1 (from <Candidate pandas 1.2.5 from https://pypi.org/simple/pandas/>)
To fix this, you can change the value of `requires-python` in pyproject.toml.
See /tmp/pdm-lock-b42wp3tk.log for detailed debug log.
```

After guessing the workaround for this, I did have a successful install, then I tried to look at `/tmp/pdm-lock-b42wp3tk.log` from earlier, and it was gone.  The successful install appears to blow away old log files, which is neat I guess.

## Expected behavior

The import and install should have worked.  The `Pipfile` worked with pipenv, so one assumes `pdm` will be able to make it work in the new system.

If the version resolution needs a x.y.z version of Python, the import should try harder to create one.

## Environment Information

```bash
PDM version:        1.14.1
Python Interpreter: /usr/local/opt/python@3.7/bin/python3.7 (3.7)
Project Root:       /Users/jayvdb/projects/github/icetana/icetana-algorithm
Project Packages:   /Users/jayvdb/projects/github/icetana/icetana-algorithm/__pypackages__/3.7
{
  "implementation_name": "cpython",
  "implementation_version": "3.7.13",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "21.4.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64",
  "python_full_version": "3.7.13",
  "platform_python_implementation": "CPython",
  "python_version": "3.7",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
The `requires` from `Pipfile` is different from the `requires-python` metadata. Pipenv doesn't make any promise about whether the resulting Pipfiles are compatible with any python version you picked but PDM does.

Pandas explicitly excludes `3.7.0` from the supported version range and `requires-python = ">=3.7"` is wider than what pandas supports. As instructed, you have to change that value to `>=3.7.1` to make it work.

**Comment by frostming** [comment]
Closing it now for not being a bug
