### ISSUE TITLE
Path not being populated properly in WSL 2.0

### ISSUE THREAD

**Issue by dreinon** [pdm-project/pdm#1074]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
extract of pyproject.toml:
```toml
[tool.pdm.dev-dependencies]
dev = [
  "pre-commit~=2.15",
  "editables~=0.2",
  "mypy~=0.930",
  "pytest~=6.2",
  "pytest-asyncio~=0.16",
  "pytest-cov~=3.0",
  "pytest-mock~=3.6",
  "pylint~=2.11",
  "black>=22.3.0",
  "isort~=5.9",
]
```

zsh commands:
```zsh
❯ pdm run -vv black .
[PdmUsageError]: Command 'black' is not found on your PATH.

❯ pdm run python -c "import black; print('imported correctly')"
imported correctly
```

## Actual behavior
Black cannot be executed with `pdm run` (neither can pre-commit, isort, etc)

## Expected behavior
Be able to execute these commands.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.14.1
Python Interpreter: /home/dani/.local/share/pdm/venv/bin/python (3.10)
Project Root:       /home/dani/sjma/projects/sjma-backend
Project Packages:   /home/dani/sjma/projects/sjma-backend/__pypackages__/3.10
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.4",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.10.102.1-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Wed Mar 2 00:30:59 UTC 2022",
  "python_full_version": "3.10.4",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}

```

**Comment by dreinon** [comment]
If it helps, the issue gets solved by setting the following config:
```zsh
❯ pdm config python.use_pyenv False
❯ pdm config python.use_venv True
```

**Comment by frostming** [comment]
Did `black` get installed to `/home/dani/sjma/projects/sjma-backend/__pypackages__/3.10`? And what is the output of `pdm run python -c "import sys;print(sys.executable)"`?

**Comment by dreinon** [comment]
Surprisingly, I have set back the config for it to use pyenv and everything works.
(I even have deleted the recently created executables from .local/share/pdm/venv/bin so the only ones able to get executed were the ones into __pypackages/3.10/bin)

The output of the command you told me is:
/home/me/.local/share/pdm/venv/bin/python

**Comment by frostming** [comment]
Fine, I would like to close it now. Feel free to open a new one if you find stable reproducing steps in the future.
