### ISSUE TITLE
Global configuration file

### ISSUE THREAD

**Issue by menzenski** [pdm-project/pdm#1087]
## Is your feature request related to a problem? Please describe.

My team is in the middle of adopting PDM - we've created several new PDM projects and plan to move a bunch of existing python projects to PDM as well.

It's a pretty minor thing, but something that frustrates us is having to reenter the same information each time we run `pdm init`. Author name, author email, license, and requires-python have been constant for all of our projects thus far and it'd be great to have a mechanism to auto-populate these fields in a new project with values defined in a single place.

## Describe the solution you'd like

My ideal solution would be a `.pdmrc` file where default values could be defined. 

Other projects use something similar: for example, [cookiecutter](https://github.com/cookiecutter/cookiecutter) defines a [`.cookiecutterrc` file](https://cookiecutter.readthedocs.io/en/2.0.2/advanced/user_config.html) where default values can be defined.

**Comment by pawamoy** [comment]
What about creating your own Cookiecutter template then? You wouldn't even have to run `pdm init` anymore, as pyproject.toml would be generated by the template.

**Comment by frostming** [comment]
We are not going to implement this since it is well handled by boilerplate tools such as cookiecutter.
