### ISSUE TITLE
pdm init error,[CalledProcessError]

### ISSUE THREAD

**Issue by allenjol** [pdm-project/pdm#1089]
I use pipx to installed pdm tools，then,i use pdm init but get error.
```console
❯ mkdir pdm-demo
❯ cd pdm-demo
❯ pdm init
Creating a pyproject.toml for PDM...
[CalledProcessError]: Command '['/Users/allenjol/.pyenv/shims/python', '-c', 'import platform; print(platform.python_version())']' returned non-zero exit status 127.
Add '-v' to see the detailed traceback
```

I have installed pyenv before, and now my system python version is 3.10.2:
```console
❯ pyenv versions
* system (set by /Users/allenjol/.pyenv/version)
  3.10.4
❯ python3 -V
Python 3.10.2
```

Any one know how to resolve it?

**Comment by frostming** [comment]
Does the file `/Users/allenjol/.pyenv/shims/python` exists and the following command returns normally?

`/Users/allenjol/.pyenv/shims/python -c 'import platform; print(platform.python_version())'`

**Comment by allenjol** [comment]
Yes, the file `/Users/allenjol/.pyenv/shims/python` exists and the following command returns normally.
```
❯ /Users/allenjol/.pyenv/shims/python -c 'import platform; print(platform.python_version())'
3.10.4
```

**Comment by allenjol** [comment]
Oh, you remind me. 
Install pipx use python 3.10.4 version, but at present, I use a system version of python 3.10.2 performed on `pdm init`, I use pyenv global 3.10.4 switch the python version before you implement `pdm init` was no problem.

Thank you for you reply!
