### ISSUE TITLE
Error with pygments and `Ctrl+C`

### ISSUE THREAD

**Issue by DUOLabs333** [pdm-project/pdm#1095]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
1. Download and run [mathicsscript](https://github.com/Mathics3/mathicsscript) (though this is also reproducible with ipython, or any REPL that uses pygments). 

## Actual behavior
If a command takes a while to run, if you press Ctrl+C, the process will exit, though you can not see anyhting you type until you execute `reset` or `tset`.

## Expected behavior
Whatever the program is programmed to do.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.14.0
Python Interpreter: /usr/bin/python3.10 (3.10)
Project Root:       /home/system/PDM/ipython
Project Packages:   /home/system/PDM/ipython/__pypackages__/3.10
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.4",
  "os_name": "posix",
  "platform_machine": "aarch64",
  "platform_release": "5.17.1-1-aarch64-ARCH",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Mon Mar 28 23:54:20 UTC 2022",
  "python_full_version": "3.10.4",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}

```

**Comment by DUOLabs333** [comment]
Using `os.system` instead of `subsprocess` works much better.

**Comment by frostming** [comment]
Using `os.system` is less ideal and have security issues. `subprocess` is the recommended way to run processes in Python.

**Comment by DUOLabs333** [comment]
Ok, I found that this works:
```
s = signal.signal(signal.SIGINT, signal.SIG_IGN)
        process = subprocess.Popen(expanded_args, cwd=cwd, env=process_env, shell=shell)
        try:
            process.wait()
        except KeyboardInterrupt:
            pass
        s = signal.signal(signal.SIGINT, signal.SIG_IGN)
```

**Comment by DUOLabs333** [comment]
It also works on Windows.

**Comment by DUOLabs333** [comment]
Do you want me to start a PR?

**Comment by frafra** [comment]
I can confirm. This also happens when executing `pdm run` and exiting the Python interpreter. No pygments is involved.

**Comment by frostming** [comment]
> Ok, I found that this works:
> 
> ```
> s = signal.signal(signal.SIGINT, signal.SIG_IGN)
> process = subprocess.Popen(expanded_args, cwd=cwd, env=process_env, shell=shell)
> process.wait()
> s = signal.signal(signal.SIGINT, signal.SIG_IGN)
> ```

With this patch, then a long-running process won't respond to a `Ctrl-C`. Try `pdm run python -c "import time;time.sleep(10)"`

**Comment by DUOLabs333** [comment]
This should work:
```
def send_int(exitnum,handler):
            os.kill(process.pid,signal.SIGINT)
        s = signal.signal(signal.SIGINT, send_int)
        process = subprocess.Popen(expanded_args, cwd=cwd, env=process_env, shell=shell)
        process.wait()
        signal.signal(signal.SIGINT, s)
```

**Comment by frostming** [comment]
@DUOLabs333 A PR is welcomed
