### ISSUE TITLE
`pdm update --production` also updates dev requirements

### ISSUE THREAD

**Issue by lyz-code** [pdm-project/pdm#1104]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```bash
git clone https://github.com/lyz-code/repository-orm
cd repository-orm
make update-production
```

`update-production` runs behind the deck:

```bash
pdm update --production --no-sync
pdm sync --clean
```

## Actual behavior

Development dependencies are being updated too. Such as `mypy`.

## Expected behavior

Development dependencies are not updated

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.15.0
Python Interpreter: ~/.venvs/repository-orm/bin/python (3.9)
Project Root:       ~/projects/repository-orm
Project Packages:   None
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.10",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "4.19.0-5-amd64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Debian 4.19.37-5+deb10u1 (2019-07-19)",
  "python_full_version": "3.9.10",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by lyz-code** [comment]
Thanks for the quick fix. I can't wait for the next release to test it

**Comment by frostming** [comment]
Released https://github.com/pdm-project/pdm/releases/tag/1.15.1

Lyz ***@***.***> 于2022年6月1日周三 17:36写道：

**Comment by lyz-code** [comment]
Works perfectly, thanks!
