### ISSUE TITLE
Overrides only support exact versions

### ISSUE THREAD

**Issue by agoose77** [pdm-project/pdm#1122]
The documentation for overrides implies that version _constraints_ can be used. However, the logic that handles overrides actually constructs the version constraint, and therefore assumes a single version:
https://github.com/pdm-project/pdm/blob/111d00b9bb916d596901fdfe06cdf596d4eacd69/pdm/resolver/providers.py#L107-L114

I think it would be ideal if the user can provide new constraints that override those found during resolution, but if this is technically difficult, then updating the documentation to clarify the situation might be helpful, in addition to raising an error if the user tries to provide such a version.

**Comment by frostming** [comment]
I am a bit confusing, that is not the latest code:
https://github.com/pdm-project/pdm/blob/42fff5365afbbaf158bb1be9cd9c6ee023409149/pdm/resolver/providers.py#L114-L119

**Comment by agoose77** [comment]
Huh, that's odd. I think I knew what I was expecting to see, and picked out an old commit by accident.

I originally filed this report because I couldn't get version constraints to work in the first place :/

**Comment by frostming** [comment]
I am closing this issue now, when you encountered any issue, please file a new one with reproducible steps and descriptipns
