### ISSUE TITLE
scipy install fails on python 3.10

### ISSUE THREAD

**Issue by CucumberKing** [pdm-project/pdm#1136]
I hope I am right here, if not sorry for the report.
I have problems installing scipy with pdm.

First, pdm tries to install scipy 1.6.2, which does not seem to be suitable for 3.10. Then, when I manually request a version from 1.8, the installation still fails.

✖ 🔒 Lock failed
Unable to find a resolution because the following dependencies don't work on all Python versions defined by the project's `requires-python`: >=3.10
  python>=3.8,<3.11 (from <Candidate scipy 1.8.0 from https://pypi.org/simple/scipy/>)
  python>=3.8,<3.11 (from <Candidate scipy 1.8.1 from https://pypi.org/simple/scipy/>)
To fix this, you can change the value of `requires-python` in pyproject.toml.

This output does not make sense to me.

My pyproject.toml
```
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "", email = ""},
]
dependencies = [
    "scipy>=1.8.0",
]
requires-python = ">=3.10"
license = {text = "n"}

[tool.pdm]

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"
```

**Comment by Hnasar** [comment]
scipy doesn't claim to support Python 3.11, but your pyproject.toml requires that libraries support all versions >= 3.10 (which implies 3.11).

Try changing your pyproject.toml like so:

```
requires-python = ">=3.10, <3.11"
```

**Comment by CucumberKing** [comment]
Sorry if I'm stupid here but why does >=3.10 imply 3.11? I read that as greater than or equal to 3.10 and that would include 3.10..?

**Comment by Hnasar** [comment]
>=3.10 means everything newer than 3.10, even an alpha release of 3.11 and future versions of python. Its common for some python packages to put an upper bound on what they support.

**Comment by Hnasar** [comment]
Can you close the but if it's resolved?
