### ISSUE TITLE
PDM commands trying to resolve not production package

### ISSUE THREAD

**Issue by micaelmalta** [pdm-project/pdm#1139]
- [x]   I have searched the issue tracker and believe that this is not a duplicate.

### Steps to reproduce

`pyproject.toml`

```
[project]
name = "test"
version = "0.0.1"
description = ""
requires-python = ">= 3.7.2,<4.0"
dependencies = [
    "pydantic"
]

[project.optional-dependencies]
test = [
    "pylint"
]

[tool.pdm.dev-dependencies]
doc = [
    "mypy"
]
```

`pdm install --production -vvv`
or
`pdm update --production -vvv`

### Actual behavior

```
======== Start resolving requirements ========
  pylint
  mypy
  pydantic
  python>=3.7.2,<4.0
```

### Expected behavior

```
======== Start resolving requirements ========
  pydantic
  python>=3.7.2,<4.0
```

**Comment by Hnasar** [comment]
@micaelmalta This is intended. If PDM didn't check compatibility, it would mean that some dev dependencies could conflict with the production dependencies. 

If PDM allowed these conflicts what would be the right thing to do if the user requested to install both dev and prod dependencies? What use would the dev dependencies be without actually being able to run the code with the prod deps?

If for some reason a dev dependency is incompatible with your prod deps, that could be a good opportunity to instead install the dev dependency with pipx.

**Comment by frostming** [comment]
It is well explained by @Hnasar . No worry, PDM is just quickly scanning the other dependencies to see whether the locked versions satisfy the requirements and won't do anything if they do.

Close it for now.
