### ISSUE TITLE
using a local directory of wheel files as a source in addition to pypi

### ISSUE THREAD

**Issue by franzhaas** [pdm-project/pdm#1141]
Dear all,

Until now I used pipenv to manage my python projects, by setting.:

[global]
find-links = PATH_2_DIRECTORY_OF_MY_FAVORITE_WHEELS
wheel-dir = PATH_2_DIRECTORY_OF_MY_FAVORITE_WHEELS

in my pip.conf I was able to use a flat local directory of cached wheels, if a wheel was missing there it got downloaded from pypi only once.

How could i configure pdm to do the same? Unfortunately i didnt manage to transform the example at https://pdm.fming.dev/latest/pyproject/tool-pdm/ into a working solution using a file system path to a flat directory.

Thanks in advance,
franz

**Comment by frostming** [comment]
I've updated the doc to add an example: https://pdm.fming.dev/dev/pyproject/tool-pdm/#specify-other-sources-for-finding-packages

**Comment by franzhaas** [comment]
Thanks, the example works for me!
