### ISSUE TITLE
Enhance list by providing an option to specify which group of dependencies to list

### ISSUE THREAD

**Issue by TommyDuc** [pdm-project/pdm#1149]
As of now the `list` command can only list the packages currently installed in the working set.
Currently there is no way to target packages like the `sync` command  with the `--group` and `--production` parameters.
`sync --clean --production` doesn't always work either and so removing `__pypackages__` entirely seems to be the only solution.

I suggest to add these CLI parameters to the `list` command as well.

Of course, with a pretty please and a cherry on top 😀

**Comment by frostming** [comment]
What would you like to achieve by listing the packages in the *lock file*, rather than the *working set*? Any user scenario?

**Comment by TommyDuc** [comment]
Okay it outputs what I need:
```bash
pdm export --production --format requirements --without-hashes
```
Suggestion: mention it to the `list --freeze`'s `argparse` doc string
