### ISSUE TITLE
pdm 1.15.3 is incompatible with pdm-pep517 1.0.0

### ISSUE THREAD

**Issue by dvzrv** [pdm-project/pdm#1165]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Hi! I'm trying to package python-pdm for Arch Linux. For this to happen i had to also package pdm-pep517, which is now at version 1.0.0.
The latest version of pdm (1.15.3) is incompatible with it though.
What are the plans for compatibility? 

## Actual behavior

pdm 1.15.3 is not compatible with pdm-pep517 1.0.0.

## Expected behavior

The latest releases of pdm and pdm-pep517 are compatible.

## Environment Information

n/a

**Comment by frostming** [comment]
This request is not reasonable. PDM 1.15.3 explicitly specifies the dependency `pdm-pep517<1.0` and you shouldn't expect pdm-pep517 1.0.0 to work.

I don't know much about arch packaging but requiring the latest version to work does not make sense.

**Comment by dvzrv** [comment]
> This request is not reasonable. PDM 1.15.3 explicitly specifies the dependency pdm-pep517<1.0 and you shouldn't expect pdm-pep517 1.0.0 to work.

Why is it released then? What can pdm-pep517 1.0.0 be used for/with at this point in time?

> I don't know much about arch packaging but requiring the latest version to work does not make sense.

I'm trying to understand the rationale behind this, because it is *very hard* to keep up with a restrictive versioning system this way.
I need pdm to be able to package other packages that require it for installing via PEP517.

 If the conglomerate of pdm/pdm-pep517 introduces incompatibility, when using the respective latest versions, this conflicts with how packages are being updated (Arch Linux is rolling release) and it makes it very hard for downstream distributions to be able to package this project.

**Comment by dvzrv** [comment]
To be more specific: In a system's packaging context I will have to downgrade pdm-pep517 from 1.0.0 to 0.12.7 to be able to package pdm.
I will have to keep pdm-pep517 outdated until pdm supports pdm-pep517 >= 1.0.0 to be able to package the packages relying on pdm.

If any packages start to require pdm-pep517 >= 1.0.0 in the meantime I will not be able to package them or update them.

**Comment by frostming** [comment]
> Why is it released then? What can pdm-pep517 1.0.0 be used for/with at this point in time?

The semantics versioning is designed to allow breaking changes in major bumps, pdm 1.15.3 knows that and put a upper bound at the dependency version, I don't see why it is restricted.

`pdm-pep517`, apart from being a dependency of PDM, is also a build-time requirement for other packages that specify it as the build backend. For this usage, `pdm-pep517` has tried to be backward-compatible so that these packages are not broken. They can pull in the latest version of it and be built without any problem. But PDM 1.x wants it to be `<1.0`, so why not? Is it the case that there should be only one version of a specific package on the system, the latest version?

**Comment by dvzrv** [comment]
> But PDM 1.x wants it to be <1.0 because it calls the APIs of pdm-pep517, so why is it disallowed? Is it the case that there should be only one version of a specific package on the system, the latest version?

For system's packaging this is problematic, as pdm-pep517 needs to be held back until all consumers (in this case pdm) can use it in their current version.
