### ISSUE TITLE
v2: pip config is not used anymore?

### ISSUE THREAD

**Issue by pawamoy** [pdm-project/pdm#1176]
Is it possible that dropping pip in favor of unearth also dropped the feature that allowed PDM to read pip's configuration?

When I try to lock or install, PDM uses https://pypi.org/simple instead of my pip configured index.

```console
$ pdm install
All packages are synced to date, nothing to do.
Installing the project as an editable package...
  ✖ Install project 0.7.1.dev12+g699e72d.d20220629 failed

See /tmp/pdm-install-j7lda0bu.log for detailed debug log.
[BuildError]: Call command ['/home/user/.basher-packages/pyenv/pyenv/versions/3.8.11/bin/python3.8', '-Esm', 'pip', 'install', '--isolated', '--ignore-installed', '--prefix', 
'/tmp/pdm-build-env-kc7debg1-shared', '--index-url', 'https://pypi.org/simple', '-r', '/tmp/pdm-build-reqs-z280_ygx.txt'] return non-zero status(1).
Add '-v' to see the detailed traceback

$ pdm lock
See /tmp/pdm-lock-8n7m3ufh.log for detailed debug log.
[ProxyError]: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/mkdocs/ (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
Add '-v' to see the detailed traceback
```

**Comment by frostming** [comment]
> Is it possible that dropping pip in favor of unearth also dropped the feature that allowed PDM to read pip's configuration?

Exactly. Configurations should live in PDM's own config file.

**Comment by frostming** [comment]
I've updated the doc, thanks

**Comment by pawamoy** [comment]
Thank you!

**Comment by felixlu** [comment]
how can we use two pypi servers in PDM?

our company's private pypi server didn't proxy any upstream public pypi servers, so it's critical to have an extra pypi server.

**Comment by frostming** [comment]
> how can we use two pypi servers in PDM?
> 
> our company's private pypi server didn't proxy any upstream public pypi servers, so it's critical to have an extra pypi server.

Add it to the `[[tool.pdm.source]]` in `pyproject.toml`
