### ISSUE TITLE
setup-script only creates platform wheels

### ISSUE THREAD

**Issue by schiebel** [pdm-project/pdm#1215]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

I am trying to create a `pyproject.toml` file which will compile a [Kaitai](https://kaitai.io/) ksy file into a Python reader as the first step in the build process. The [documentation](https://pdm.fming.dev/latest/pyproject/build/) says:

> you may want to generate other files or download resources from the internet

so using `setup-script` seemed very convenient and exactly what I needed. However, specifying a `setup-script` causes a *platform wheel* (e.g. `testcase-0.1.0-cp38-cp38-macosx_10_15_x86_64.whl`) to be built instead of a *universal wheel* (e.g. `testcase-0.1.0-py3-none-any.whl`). Kaitai generates pure python files so a *platform wheel* is unnecessarily restrictive.

How do I create a *universal wheel* when using `setup-script`? Is there a better way to accomplish this?

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.15.4
Python Interpreter: /opt/local/bin/python (3.8)
Project Root:       /Users/drs/develop/kaitai/casatabstream
Project Packages:   /Users/drs/develop/kaitai/casatabstream/__pypackages__/3.8
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.12",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "19.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64",
  "python_full_version": "3.8.12",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
```toml
[tool.pdm.build]
is-purelib = true
```

**Comment by schiebel** [comment]
*excellent*, thanks very much
