### ISSUE TITLE
Write lockfile before calling the "post_lock" hook

### ISSUE THREAD

**Issue by lecardozo** [pdm-project/pdm#1224]
## Is your feature request related to a problem? Please describe.
First, thanks for the nice work with PDM. 😄 

I've been trying to come up with a way to `pdm export` a requirements.txt file every time an update to the lockfile happens. As some vulnerability scanning services and other CI tools do not yet support parsing/reading/interpreting pdm.lock files, this would allow us to adopt the PDM without compromising other parts of the workflow.

At first, we thought using PDM lifecycle hooks functionality would suffice. Something like
```toml
[tool.pdm.scripts]
post_lock = {shell = "pdm export -f requirements > requirements.txt"}
```
Unfortunately, that did not work, as the `post_lock` hook is called **before** the lockfile is written to the disk (snippet below)
https://github.com/pdm-project/pdm/blob/7d9c0f3d108c7418cd93e6a020b0f56333b8936b/pdm/cli/actions.py#L120-L125

## Describe the solution you'd like

Having the lockfile written to the disk before calling the `post_lock` hook would enable this functionality and make PDM's adoption easier for workflows that rely, at some point, on the standard requirements.txt file. 😃

**Comment by thiagoazeredo-quintoandar** [comment]
+1

**Comment by frostming** [comment]
I think this is a good issue for a new contributor 👍
