### ISSUE TITLE
pdm 2.0.0 "config cache_dir" in a non-root and proxy access env reaches out to pypi.org

### ISSUE THREAD

**Issue by awuersch** [pdm-project/pdm#1226]
- [ x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

This error is happening:

* on pdm 2.0.0 but not on pdm 1.15.4
* in an environment barring Internet access except through a proxy
* from a python 3.10 image
* running as a non-root user with no HOME dir

The above environment is common in a Kubernetes cluster.
A "pod" runs as non-root, so it is unable to create a home dir for its non-root user.

Assume there's an available VENV directory to put the pdm cache.
This could be, say, `VENV=/tmp/venv`.

The command
```
VENV=/tmp/venv
pdm config cache_dir "$VENV/.cache"
```
fails with an SSL error from attempting access to "pypi.org".

It would be nice if one could run first
```
pdm config --local pypi.url "PROXY_URL"
```

but the `config --local pypi.url` command cannot be run first,
because the default cache is at `$HOME/.cache`
and `$HOME/.cache` doesn't exist.

## Actual behavior

A `requests.exceptions.SSLError: HTTPSCOnnectionPool(host=='pypi.org', port=443)` exception is thrown.

## Expected behavior

The `pdm config cache_dir "$VENV/.cache"` should return normally.

## Environment Information

pdm is not yet initialized when this error occurs,
so `pdm info` returns an error.

**Comment by frostming** [comment]
Can you paste the full traceback(adding `-v`) for `requests.exceptions.SSLError: HTTPSCOnnectionPool(host=='pypi.org', port=443)`, it is not clear where it is raised.

**Comment by frostming** [comment]
Use the env var to workaround the first setup:

```
PDM_PYPI_URL=<PROXY_URL> pdm config cache_dir "venv/.cache"
```
