### ISSUE TITLE
2.0.x: problem with loop in depependencies (with `unearth` module)

### ISSUE THREAD

**Issue by kloczek** [pdm-project/pdm#1233]
With 2.0.x seems have been introduced install time dependency with `unearth`.
Issue is that `unearth` module needs `pdm` to build.
Any sughgestions how to resolve that loop in dependencies? 🤔 
Maybe it would be good to move `unearth` to use some other pep517 backend? 🤔

**Comment by frostming** [comment]
> Issue is that `unearth` module needs `pdm` to build.

Not correct, `unearth` needs `pdm-pep517`, which has no dependency. And you don't need `pdm` to build the package, any PEP-517 compliant build frontend can do that, such as [`build`](https://github.com/pypa/build)

**Comment by frostming** [comment]
`findpython` is also packaged in the same way, have a look at it on how to build it.

**Comment by kloczek** [comment]
OK. My falut.
Thank You 👍
