### ISSUE TITLE
After update to version 2, start to use venv in the project.

### ISSUE THREAD

**Issue by SirMartin** [pdm-project/pdm#1243]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

In my project PDM v. 1.15 didn´t use venv, but after the update to PDM v. 2 it start to create it.

Nothing was changed, just run it before or after the launch of version 2. To test it, I forced pip to install version 1.* or 2.*

![image](https://user-images.githubusercontent.com/854646/179734991-b50603fe-3ed8-423f-83d0-1da610efc98b.png)

**With PDM v. 1.15**
```bash
Step 9/15 : RUN pdm install --check --prod
 ---> Running in e64c32e22e30
Synchronizing working set with lock file: 54 to add, 0 to update, 0 to remove

Install setuptools 63.1.0 successful
...
Install typing-extensions 4.3.0 successful
Installing the project as an editable package...
Install Forrest Gump Launcher 0.0.1 successful

🎉 All complete!

PDM 1.15.4 is installed, while 2.0.1 is available.
Please run $ /usr/local/bin/python -m pip install -U pdm to upgrade.
Run $ pdm config check_update false to disable the check.
Removing intermediate container e64c32e22e30
 ---> e6b29e67d983
Step 10/15 : COPY README.md setup.cfg /opt/app/
 ---> c5ba5195fe35
Step 11/15 : FROM base AS development
 ---> c5ba5195fe35
Step 12/15 : ARG GITHUB_USER
 ---> Running in 244eea907ecd
Removing intermediate container 244eea907ecd
 ---> c8672b119107
Step 13/15 : ARG GITHUB_PIP_TOKEN
 ---> Running in aade0882e483
Removing intermediate container aade0882e483
 ---> 0b46e0fbcb15
Step 14/15 : COPY pdm.lock pyproject.toml /opt/app/
 ---> f14e53275466
Step 15/15 : RUN pdm sync
 ---> Running in 0d0d21972da7
Synchronizing working set with lock file: 14 to add, 0 to update, 0 to remove

Install freezegun 1.1.0 successful
Install pluggy 1.0.0 successful
Install mccabe 0.6.1 successful
Install exceptiongroup 1.0.0rc8 successful
Install flake8 3.9.2 successful
Install iniconfig 1.1.1 successful
Install pycodestyle 2.7.0 successful
Install pytest-spec 3.2.0 successful
Install pyflakes 2.3.1 successful
Install pyhamcrest 2.0.3 successful
Install hypothesis 6.49.1 successful
Install sortedcontainers 2.4.0 successful
Install pytest 7.1.2 successful
Install tomli 2.0.1 successful
Installing the project as an editable package...
  ✔ Install MyProject 0.0.1 successful

🎉 All complete!

PDM 1.15.4 is installed, while 2.0.1 is available.
Please run $ /usr/local/bin/python -m pip install -U pdm to upgrade.
Run $ pdm config check_update false to disable the check.

```

**With PDM v. 2.***

```bash
Step 9/15 : RUN pdm install --check --prod
 ---> Running in 08b05755632c
python.use_venv is on, creating a virtualenv for this project...
Virtualenv is created successfully at /opt/app/.venv
Synchronizing working set with lock file: 54 to add, 0 to update, 0 to remove

  ✔ Install setuptools 63.2.0 successful
  ✔ Install async-timeout 4.0.2 successful
 ...
  ✔ Install pyarrow 5.0.0 successful
Installing the project as an editable package...
  ✔ Install MyProject 0.0.1 successful

🎉 All complete!

Removing intermediate container 08b05755632c
 ---> 823616031f7f
Step 10/15 : COPY README.md setup.cfg /opt/app/
 ---> 4caee66e88a3
Step 11/15 : FROM base AS development
 ---> 4caee66e88a3
Step 12/15 : ARG GITHUB_USER
 ---> Running in f7ba3bced139
Removing intermediate container f7ba3bced139
 ---> 8518f61eee7c
Step 13/15 : ARG GITHUB_PIP_TOKEN
 ---> Running in ed624438498a
Removing intermediate container ed624438498a
 ---> d03d1cbfab2f
Step 14/15 : COPY pdm.lock pyproject.toml /opt/app/
 ---> d32225fb0633
Step 15/15 : RUN pdm sync
 ---> Running in 335907cb4f8e
Synchronizing working set with lock file: 14 to add, 0 to update, 0 to remove

  ✔ Install exceptiongroup 1.0.0rc8 successful
  ✔ Install freezegun 1.1.0 successful
  ✔ Install mccabe 0.6.1 successful
  ✔ Install iniconfig 1.1.1 successful
  ✔ Install pluggy 1.0.0 successful
  ✔ Install pycodestyle 2.7.0 successful
  ✔ Install flake8 3.9.2 successful
  ✔ Install hypothesis 6.52.3 successful
  ✔ Install pytest-spec 3.2.0 successful
  ✔ Install tomli 2.0.1 successful
  ✔ Install sortedcontainers 2.4.0 successful
  ✔ Install pyhamcrest 2.0.3 successful
  ✔ Install pyflakes 2.3.1 successful
  ✔ Install pytest 7.1.2 successful
Installing the project as an editable package...
  ✔ Update forrest-gump-launcher 0.0.1 -> 0.0.1 successful

🎉 All complete!

```

## Expected behavior

To continue with the same settings as before.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.0.1
Python Interpreter:
  /usr/bin/python3.10 (3.10)
Project Root:
  /home/edu/NextailGit/forrestgump-launcher
Project Packages:
  /home/edu/NextailGit/forrestgump-launcher/__pypackages__/3.10


{
  "implementation_name": "cpython",
  "implementation_version": "3.10.4",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.17.15-76051715-generic",
  "platform_system": "Linux",
  "platform_version": "#202206141358~1655919116~22.04~1db9e34 SMP PREEMPT Wed 
Jun 22 19",
  "python_full_version": "3.10.4",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}

```

**Comment by frostming** [comment]
Yeah, it is expected behavior change, to use PEP 582, upload an **empty** `__pypackages__` to your VCS

**Comment by SirMartin** [comment]
Ok, that works, but I found some issues with this fix.

If I change at a project level if use or not a venv, needs to be in the pdm.toml, the problem with this solution is if I use **pdm use** to specify which version to use locally, is also stored in the pdm.toml file.

So in that case there is specific user configurations (python path from pdm use) and project-specific configuration (the venv flag). 

Which is your suggestion? Because, of course, I can create an empty __pypackages__ folder in the VCS, but I need to create it also inside the container because I cannot move it from the local environment, because it could contain all the download dependencies, and make errors and conflicts.

It should not be this kind of global setting in another file? Or in the pyproject.toml, or maybe move the python path elsewhere?

Thanks for your great work

**Comment by alexclarence** [comment]
@SirMartin, wouldn't creating a __pypackages__ directory with a gitignore file inside of it solve the problem (assuming you're using git)?

`__pypackages__/.gitignore`
```
*
!.gitignore
```

This way the directory itself will be added to git but its contents will be ignored, and if you pull this into your container from git, it will create that directory automatically. I believe PEP582 mentioned this solution for projects using VSC

**Comment by SirMartin** [comment]
Kind of. The problem in that case is if I want to build the container locally, where __pypackages__ is not empty. I use it for example for launch some integration tests, in that case if I move into the container the __pypackages__ folder it come also all the content.

**Comment by SirMartin** [comment]
@frostming exists an option to configure it somehow that would be related to this project? Because as I said the .pdm.toml file can contain specific user information (like the python path from **pdm use**)

What do you think?

At the moment I created an empty **__pypackages__** in the VCS and in the docker file I added a line to disable the python venv using **pdm config**, so I have covered both local and docker usage, but I think could be done much better.

Thanks

**Comment by frostming** [comment]
> @frostming exists an option to configure it somehow that would be related to this project? Because as I said the .pdm.toml file can contain specific user information (like the python path from **pdm use**)
> 
> What do you think?
> 
> At the moment I created an empty ****pypackages**** in the VCS and in the docker file I added a line to disable the python venv using **pdm config**, so I have covered both local and docker usage, but I think could be done much better.
> 
> Thanks

Run `pdm use <python>` to choose a python path in the container will also fix the environment to using PEP 582

**Comment by SirMartin** [comment]
I don´t think is hard, I will continue using the pdm config, at least kind of explain itself what are you doing.

But I don´t fully understand why a configuration file like pdm.toml contains information that is user-specific (python path) and project specific, which makes it impossible to upload this file to a VCS to share the project settings for everyone. Maybe I am wrong, and the idea behind PEP-582 is that each person can decide whether to use it or not for each project, and pdm.toml was always thought of as a user-specific configuration file.

Thanks again.

**Comment by frostming** [comment]
`.pdm.toml` IS user-specific and is not designed to share.

In your case `python.use_venv` is also a user-specific config. You share the project with others and they can use venv or PEP 582 to bootstrap the environment.

**Comment by SirMartin** [comment]
100% understood now. Thanks again for your work!
