### ISSUE TITLE
Duplicate Global Environments

### ISSUE THREAD

**Issue by robml** [pdm-project/pdm#1246]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Prior to the update I had a base of packages I would keep track of using `pdm list -g`. Now it seems that my global project has been relocated (without me explicitly doing so) to `~/.config/pdm/global-project` whereas before it was in `~/.pdm/global-project`.

## Actual behavior

When I open a session it recognizes the modules in my old global directory `~/.pdm/global-project`, but when I try to add/remove/list new ones it automatically uses `~/.config/pdm/global-project`. I want to remove this latter one and link to the old one, however I am not entirely sure how.

Additionally here is my `pdm config output` with my user name stripped:
```
Site/default configuration (/etc/xdg/pdm/config.toml):
build_isolation = True
cache_dir = /home/USER/.cache/pdm
check_update = True
global_project.fallback = False
global_project.fallback_verbose = True
global_project.path = /home/USER/.config/pdm/global-project
global_project.user_site = False
install.cache = False
install.cache_method = symlink
install.parallel = True
project_max_depth = 5
pypi.json_api = False
pypi.url = https://pypi.org/simple
pypi.verify_ssl = True
python.use_pyenv = True
python.use_venv = True
strategy.resolve_max_rounds = 10000
strategy.save = minimum
strategy.update = reuse
venv.backend = virtualenv
venv.in_project = True
venv.location = /home/USER/.local/share/pdm/venvs
```

Despite `python.use_venv` being set to True, I have never encountered a new virtual environment creation and have recently uninstalled the `pdm-venv` plugin.

**Comment by frostming** [comment]
You can move or copy the contents under directory `~/.pdm/` to the new location `~/.config/pdm` and everything still works

>Despite `python.use_venv` being set to True, I have never encountered a new virtual environment creation and have recently uninstalled the `pdm-venv` plugin.

It will create on a brand new project and will PEP 582 if 1) a global python is stored in `.pdm.toml` or 2) `__pypackages__` exists

**Comment by robml** [comment]
Should I set it to False to prevent a new global project from being created or does it not affect global projects?
