### ISSUE TITLE
google pypi repositories

### ISSUE THREAD

**Issue by rmchale** [pdm-project/pdm#1248]
Is it possible to get pdm to work with google pypi repositories?  It uses a custom keyring https://cloud.google.com/artifact-registry/docs/python/authentication

it requires
`pip install keyrings.google-artifactregistry-auth`

**Comment by frostming** [comment]
If you used `pipx` to install pdm, you can add dependencies by:

```
pipx inject pdm keyring keyrings.google-artifactregistry-auth
```

Otherwise, it can be partially resolved by `pdm plugin add keyring keyrings.google-artifactregistry-auth`, but in this way you will not be able to uninstall it after that.

**Comment by frostming** [comment]
Upload and download are different config keys, read the docs please.
