### ISSUE TITLE
How to setup two PyPI indices ?

### ISSUE THREAD

**Issue by nlp4whp** [pdm-project/pdm#1250]
Does pdm support more than one pypi index url, like `pypi.url` and `pypi.extra.url` ?

Because at work, I have to submit own package to private pypiserver, so I need config two `pypi.url`: public and private

Thanks for anyone help 😭

**Comment by frostming** [comment]
See here: https://github.com/pdm-project/pdm/issues/1176#issuecomment-1189719393

**Comment by nlp4whp** [comment]
> See here: [#1176 (comment)](https://github.com/pdm-project/pdm/issues/1176#issuecomment-1189719393)

Thank you 🙏
