### ISSUE TITLE
Investigate relatively slow lock generation

### ISSUE THREAD

**Issue by SmileyChris** [pdm-project/pdm#1251]
A colleague put this [Python package manager shootout](https://lincolnloop.github.io/python-package-manager-shootout/) together very recently.

While there are "Lies, damned lies, and statistics", it is interesting that the relative lock generation speed is much slower than the other tools. Is pdm doing a more thorough job in creating the lock? Is it's dependency graph generation slower? Maybe the shootout is just doing something incorrectly?

An area of improvement to look into, in any case...

**Comment by frostming** [comment]
Did you see the latest test result: https://github.com/lincolnloop/python-package-manager-shootout/actions/runs/2708687120

And also notice the thorough run time, you will get a different solution.

**Comment by TiansuYu** [comment]
@frostming I have been seeing slow locking issues as well on `2.18.1`. May I ask what is the dependency resolution algorithm used by pdm? Is it [pubgrub](https://nex3.medium.com/pubgrub-2fb6470504f) or something else?
