### ISSUE TITLE
update: honor `!=` constraint with `--unconstrained`

### ISSUE THREAD

**Issue by blueyed** [pdm-project/pdm#1272]
I am using `pdm update --uncostrained --update-eager` to upgrade packages, and it would be nice if it honored something like `"django-extensions~=3.1,!=3.2.0"` (and similar) to exclude specific versions, and only upgrade it when version 3.2.1 (or anything later than the currently locked/matching 3.1.x version) is released.

docs: https://pdm.fming.dev/latest/usage/dependency/#update-packages-to-the-versions-that-break-the-version-specifiers

**Comment by frostming** [comment]
`--unconstrained`, as described, is to ignore the version specifiers, which contradict what you want. What you want is something like: I want to ignore those specifiers but keep some at the same time. This doesn't make sense to me.

Please provide a detailed solution for this. But basically, I don't want the options to be too complicated so the current state is enough. If you want to honor the specifiers, don't add `--unconstrained`, or you just rewrite the constraint as `"django-extensions>3.2.0"`
