### ISSUE TITLE
Managing projects with different pdm versions

### ISSUE THREAD

**Issue by alexclarence** [pdm-project/pdm#1273]
### Problem:
After upgrading to `pdm=2.0`, the lock files built with `pdm=1.15` don't work (they are incompatible since package name was replaced with url to avoid pip usage, as I understand)

This problem could be solved by re-locking the dependencies with `pdm lock` or `pdm install`, however this will potentially lock different (more recent) versions of the packages and break the code.

This becomes a problem if you are trying to revisit a project that has been worked on a while ago (and potentially by someone else). You want to be able to run the code without changing anything.

So to summarize, the situation I'm talking about is something like that:
1. Somebody used `pdm=1.15` on the project in the past (it's not a package - it's some kind of production code)
2. You have `pdm=2.0` installed and use it for all your new projects
3. You need to set up the environment and run the code from the past project without modifying it

### Possible half-solutions I could think of:
1. Re-create the lock file with `pdm lock` or `pdm install` and hope that code doesn't break when using more recent versions of the packages.
    => This is risky
2. Downgrade pdm every time you need to set up the environment and run the code, then upgrade pdm to run the code in another project. 
   => This is very inconvenient and requires you to know which version of pdm they used in the past projects.
3. Downgrade pdm once, `pip freeze` the environment, and then install all dependencies with pip.
   => Very awkward as you're not using pdm anymore

### Question:
What would be the best practice for managing those types of situations?
Is there a way to get the new version of pdm read old version of the lock?
Or is there a way to upgrade the lock file to a new version without changing locked package versions?

**Comment by frostming** [comment]
I would recommend:

4. Downgrade pdm once, `pdm export -o requirements.txt`, upgrade pdm, `pdm import requirements.txt`.
