### ISSUE TITLE
pdm completion breaks after upgrade to 2.0

### ISSUE THREAD

**Issue by shyn** [pdm-project/pdm#1283]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

run `pdm completion zsh` or `pdm completion powershell`. The output breaks coz of changed to rich.

## Actual behavior

`[word]` will be parsed as rich markup which is not expected. zsh and powershell completion scripts will be broken.

## Expected behavior

should work like pdm 1.x only `%{python_executable}` is replaced.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.0.2
Python Interpreter:
  D:\Programs\Python\Python38\python.exe (3.8)
Project Root:
  D:/Projects/ykdlweb
Project Packages:
  D:\Projects\ykdlweb\__pypackages__\3.8
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.10",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19044",
  "python_full_version": "3.8.10",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "win32"
}
```
---

I have digged into the source files. Didn't find an elegant solution for a pr. `print` maybe naive :)

Maybe add and `escape=False` parameter to `UI.echo`

**Comment by dexterlemmer** [comment]
It doesn't work for me either. And I'm on bash.

```
$ echo $SHELL
/bin/bash
$ which python
/home/dexter/.pyenv/shims/python
$ ls -al .venv/bin/python3.10
lrwxrwxrwx 1 dextre dexter 51 Jul 27 19:24 .venv/bin/python3.10 -> /home/dexter/.pyenv/versions/3.10.5/bin/python3.10
```
## Trying to enable bash completions

```
$ echo '. <(pdm completion)~' >> ~/.bashrc
$ exec $SHELL
```
PDM's completions still doesn't work after the above.

## Environment information

```
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.0.3
Python Interpreter:
  /home/dexter/Documents/2022/work-dir/SonnigLogger_0_7_0/.venv/bin/python (3.10)
Project Root:
  /home/dexter/Documents/2022/work-dir/SonnigLogger_0_7_0/
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.5",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.10.117-1-MANJARO",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT Wed May 18 09:22:50 UTC 2022",
  "python_full_version": "3.10.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}
```

## PS

I did manage to get `pyenv`s completions to work. So completions does work for me.

**Comment by shyn** [comment]
@dexterlemmer Yeah, i didn't tried bash. See cause: rich parsed the script files. 

`diff <(pdm completion bash) pdm-venv/lib/python3.8/site-packages/pdm/cli/completions/pdm.bash`
```bash
18c18
<     for word in ${words:1}; do
---
>     for word in ${words[@]:1}; do
139d138
<
```

`[@]` here removed by _termui.echo_ which use rich's _console.print_
