### ISSUE TITLE
Update docs to reflect `config use_venv` deprecation

### ISSUE THREAD

**Issue by dexterlemmer** [pdm-project/pdm#1289]
## Is your feature request related to a problem? Please describe.

I noticed that at https://pdm.fming.dev/2.1/usage/advanced/ the  [Use Nox as the runner](https://pdm.fming.dev/2.1/usage/advanced/#use-nox-as-the-runner) section contains the following sentence:

"Before running nox, you should also pdm config use_venv true to enable venv reusing."

However, in `bash` I get the following:

```bash
$ pdm config use_venv
DEPRECATED: the config has been renamed to python.use_venv
True
$ pdm config python.use_venv
True
```

## Describe the solution you'd like

Update the above mentioned sentence under  [Use Nox as the runner](https://pdm.fming.dev/2.1/usage/advanced/#use-nox-as-the-runner) as follows: 

```
- "Before running nox, you should also pdm config use_venv true to enable venv reusing."
+"Before running nox, you should also pdm config python.use_venv true to enable venv reusing."
```

I would be willing to make a PR if you ask me. But I may not be able to get around to it for a while.

---

Edit: I didn't check if the docs are outdated anywhere else.

**Comment by frostming** [comment]
> +"Before running nox, you should also pdm config python.use_venv true to enable venv reusing."

This sentence can be removed as the venv has been enabled by default. Welcome to PR.

**Comment by dexterlemmer** [comment]
> > +"Before running nox, you should also pdm config python.use_venv true to enable venv reusing."
> 
> This sentence can be removed as the venv has been enabled by default. Welcome to PR.

OK. I'll make a PR this weekend sometime.

**Comment by dexterlemmer** [comment]
Thinking about this. We can certainly remove the sentence. But may be we should still keep something like it but qualified to only be necessary if you're using PEP582.
