### ISSUE TITLE
编辑器支持

### ISSUE THREAD

**Issue by abersheeran** [pdm-project/pdm#129]
试验了一下 VSCode 没办法自动寻找到环境，这个 PEP 是不是太新了点……

**Comment by frostming** [comment]
https://pdm.fming.dev/#vscode

我也在想能不能做个扩展支持

**Comment by abersheeran** [comment]
这个配置我明白，不过太不友好了。

针对 pep 标准做一个插件我觉得更靠谱一点。或者直接提 PR 到现有的 Python 插件里

**Comment by felixlu** [comment]
放在项目目录里的 `__pypackages__` 也有个不便之处：全局查找的时候通常会找到大量第三方库里面的内容，PyCharm 和 VSCode 貌似都没有很好的办法来排除（如果有，请告诉我，谢谢）。

**Comment by frostming** [comment]
@felixlu 只能用排除目录设置，node_modules 和普通venv倒没有这问题，应该是在编辑器层面做了过滤

**Comment by thernstig** [comment]
It's hard for English speaking users to follow this 😛

**Comment by abersheeran** [comment]
> It's hard for English speaking users to follow this 😛

It is impossible for us to communicate in hundreds of languages at the same time, so there always be users who cannot understand the language we use to communicate. I don't think this is a problem in an era when translators(like [google translator](https://translate.google.com/)) are pretty good.

**Comment by thernstig** [comment]
@abersheeran imagine every user posting used their own language. Do you mean we should google translate every discussion in every thread in the entire Github? Or would it be simpler if everyone used the universal English language? (note: I am not a native English speaking user myself).

Using anything but English alienates users.

**Comment by pawamoy** [comment]
I agree that it's not difficult to use Google translate, but it makes this issue non-searchable for example.

**Comment by abersheeran** [comment]
> @abersheeran imagine every user posting used their own language. Do you mean we should google translate every discussion in every thread in the entire Github? Or would it be simpler if everyone used the universal English language? (note: I am not a native English speaking user myself).
> 
> Using anything but English alienates users.

Everyone has the right to communicate in their native language. But if you communicate with me in English, I will reply to you in English. Similarly, you can also use any other language, as long as I can understand (use translators), I will communicate with you in the same language.



> I agree that it's not difficult to use Google translate, but it makes this issue non-searchable for example.

I agree with you. This issue is really difficult to search in English. It can be converted into other languages through some automatic translation tools for easy searching. Like this https://github.com/marketplace/actions/issues-translator

**Comment by frostming** [comment]
No important stuff in this thread, you can open an English discussion and we can talk there

**Comment by pawamoy** [comment]
@abersheeran of course, feel free to write in your language of choice 🙂 
I guess what @thernstig and I tried to express is that, in the future, it would be easier for non-chinese-speakers to find information in issues if everybody uses english 🙂

**Comment by blueyed** [comment]
FWIW the topic/title appears to be "Editor support".. ;)
Let's close it maybe, or move it to a discussion at least?

**Comment by xareelee** [comment]
Я просто пытаюсь написать это сообщение на русском языке. Есть ли кто-нибудь желающий прочитать этот комментарий?
