### ISSUE TITLE
PDM Builds up a huge cache over time

### ISSUE THREAD

**Issue by jayceslesar** [pdm-project/pdm#1301]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

```sh
pi@raspberrypi:~$ sudo du -xh / | grep -P "G\t"
1.2G	/home/pi/.cache/pdm/http
1.2G	/home/pi/.cache/pdm
1.9G	/home/pi/.cache
3.6G	/home/pi
3.6G	/home
1.3G	/usr
5.1G	/
```
Not sure how I can better support but this is over the course of several months. Wondering why it doesnt clear itself out?

**Comment by jayceslesar** [comment]
Related to #683 ?

**Comment by pawamoy** [comment]
Why would it clear itself? Genuine question.

**Comment by jayceslesar** [comment]
> Why would it clear itself? Genuine question.

I dont know? Is it normal to build up insanely large caches like this?

**Comment by pawamoy** [comment]
With enough time, you end up installing multiple versions of many libraries, some of which being quite heavy (torch 900MB!, pydantic 30MB, etc). So I understand the size of the cached `packages` directory.

However I don't know how the `http` directory works :smile: I think that's just the HTTP response to packages downloads that are stored.

**Comment by frostming** [comment]
> I dont know? Is it normal to build up insanely large caches like this?

Why not? Care to look at the size of `pip`, or `yarn`, `npm` if you have installed

**Comment by jayceslesar** [comment]
> > I dont know? Is it normal to build up insanely large caches like this?
> 
> Why not? Care to look at the size of `pip`, or `yarn`, `npm` if you have installed

pip cache size shows about 1/4 the size there but I guess that is to be expected if most of my installations are happening through pdm?

**Comment by jayceslesar** [comment]
Regardless -- would probably need to collect some better usage stats to compare...
```sh
~/Library/Caches
❯ du -sh pip/
1.0G	pip/

~/Library/Caches
❯ du -sh pdm/
2.7G	pdm/
```

**Comment by jayceslesar** [comment]
Unrelated but making a venv from this command seems like a bug?

```sh
~/Library/Caches on
❯ pdm cache clear
5619 files are removed
python.use_venv is on, creating a virtualenv for this project...
Virtualenv is created successfully at /Users/jslesar/Library/Caches/.venv
```

**Comment by frostming** [comment]
> Unrelated but making a venv from this command seems like a bug?
> 
> ```shell
> ~/Library/Caches
> ❯ pdm cache clear
> 5619 files are removed
> python.use_venv is on, creating a virtualenv for this project...
> Virtualenv is created successfully at /Users/jslesar/Library/Caches/.venv
> ```

It may be just you, I can't reproduce, do you have any plugins installed?

**Comment by jayceslesar** [comment]
> It may be just you, I can't reproduce, do you have any plugins installed?

What plugins do you mean here? I run starship + iterm in zshell

```sh
❯ mkdir projects

❯ cd projects

~/projects
❯ ls

~/projects
❯ pdm cache clear
53 files are removed
python.use_venv is on, creating a virtualenv for this project...
Virtualenv is created successfully at /Users/jslesar/projects/.venv
```

**Comment by Hnasar** [comment]
Regarding the cache: I suppose https://github.com/pypa/pip/issues/3138 and https://github.com/pypa/pipenv/issues/3655 don't clear their cache either.

Regarding creating a virtualenv when it's unnecessary, I think this is a regression with PDM2. I also see on my install (with no plugins) that PDM creates a virtual env any time I clear the cache (I even tried `cd /; pdm cache clear`)
`pdm cache` probably doesn't need to create a venv.

**Comment by lsmith77** [comment]
we are using platform.sh for hosting and we keep going over the build cache size. would be nice if there would be a way to define the maximum space the cache is allowed to use up and then use an LRU algorithm to clear stuff from the cache.

note I think the situation is particularily problematic since we are downloading spaCy models as dependencies which are several GB in size.

**Comment by iacore** [comment]
Can pdm reuse pip's cache?

**Comment by lsmith77** [comment]
note in our case I suspect the issue is caused by downloading spacy model dependencies via download URL

```
    "en-core-web-lg @ https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.6.0/en_core_web_lg-3.6.0-py3-none-any.whl",
    "de-core-news-lg @ https://github.com/explosion/spacy-models/releases/download/de_core_news_lg-3.6.0/de_core_news_lg-3.6.0-py3-none-any.whl",
```
