### ISSUE TITLE
env file could not use PDM_PROJECT_ROOT

### ISSUE THREAD

**Issue by zhuoqiang** [pdm-project/pdm#1324]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

`.env` like following should put the project root into ptyhonpath variable 

```shell
PYTHONPATH=${PYTHONPATH}:${PDM_PROJECT_ROOT}
```

when we use it in `pyproject.toml`

```toml
[tool.pdm.scripts]
_.env_file.override = ".env"
```

## Actual behavior

the `PDM_PROJECT_ROOT` is empty

## Expected behavior

`PDM_PROJECT_ROOT` should be the absolute project root path when reading `.env` file

## Environment Information

```bash
PDM version:
  2.1.2
Python Interpreter:
  /opt/homebrew/Caskroom/mambaforge/base/envs/lc/bin/python (3.10)
Project Root:
  /project/root
Project Packages:
  None
Inside an active virtualenv /opt/homebrew/Caskroom/mambaforge/base/envs/lc, reuse it.
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.5",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "21.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000",
  "python_full_version": "3.10.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
You need to first state the necessity of this and why you think it should work in this way and not others.

**Comment by zhuoqiang** [comment]
I would like to add the project root into PYTHONPATH when execute command.
in the the following trick works in `.env` 

```shell
SCRIPT=$(readlink -f "$0")
THIS_DIRECTORY=$(dirname "$SCRIPT")
PYTHONPATH=${PYTHONPATH}:${THIS_DIRECTORY}
```

however, it did not work in pdm 2.1, when loading `.env` file, it assigns the literal instead the exapnding value.

anyway, is there any way that I could add the project root to PYTHONPATH automatically when using pdm?

**Comment by frostming** [comment]
Python will add the current working directory to the front of `sys.path`, why would you need that?

**Comment by zhuoqiang** [comment]
because '.' is always refering to current directory as the directory changes. 

I would like to append a fixed path relative the project root to PYTHONPATH env so that I could import the python package/module relative to project root no matter where I am (maybe deep down a nested sub directory tree)

```
- ROOT
- ROOT/mymodule.py
- ROOT/src/some_script.py
```

for example: I would like to `import mymodule` in `some_script.py`

**Comment by frostming** [comment]
This use case isn't supported by Python either. IMO this should not be solved on PDM side, you can anyway solve this by changing the `sys.path`. I wrote [an article](https://frostming.com/2019/03-13/where-do-your-packages-go/#%E8%84%9A%E6%9C%AC%E8%BF%90%E8%A1%8C%E6%96%B9%E5%BC%8F%E5%AF%B9%E6%90%9C%E7%B4%A2%E8%B7%AF%E5%BE%84%E7%9A%84%E5%BD%B1%E5%93%8D) about how the way of executing the script affects `sys.path`.
