### ISSUE TITLE
[CLI] highlight group which a package is added to/removed from

### ISSUE THREAD

**Issue by baggiponte** [pdm-project/pdm#1329]
## Is your feature request related to a problem? Please describe.

pdm prompts are already stellar; as a minor improvement, I would suggest to highlight (using rich, which I recall pdm is already using) to highlight the group name which a package is added to, or removed from. In this case, it would be easier to spot it in the echoed text.

![image](https://user-images.githubusercontent.com/57922983/185625424-15497f5a-9f90-4887-807f-31866f15d3be.png)

## Describe the solution you'd like

Slightly modify the echo statement here to add formatting e.g. [here](https://github.com/pdm-project/pdm/blob/2631ffacb8980f87d73add53cb2ff47d5aaa1d77/src/pdm/cli/actions.py#L437):

```python
    project.core.ui.echo(
        f"Removing packages from {group} {'dev-' if dev else ''}dependencies: "
        + ", ".join(f"[bold green]{name}[/]" for name in packages)
    )
```

From what I understand, it would be enough to:

1. agree on the formatting
2. changing from `{group}` to `[blue]{group}[/]`

As the `project.core.ui.echo` class already uses rich. I'd be glad to make the PR if needed!

**Comment by frostming** [comment]
SGTM, go ahead for it!
