### ISSUE TITLE
Any plans to do autoinstall of python versions as pipenv does that?

### ISSUE THREAD

**Issue by mgzenitech** [pdm-project/pdm#1338]
## Is your feature request related to a problem? Please describe.

Not per say.

## Describe the solution you'd like

pyproject.toml property with python version that the project requires to be automatically installed by pyenv or some other tool, not sure. Something very similar to pipenv solution...

**Comment by frostming** [comment]
No, PDM doesn't do too much but leaves it to dedicated tools, but you can implement it in a PDM plugin. Thanks.
