### ISSUE TITLE
Is PDM compatible with PyInstaller?

### ISSUE THREAD

**Issue by nickchomey** [pdm-project/pdm#1343]
Sorry for the probably dumb question, but I'm new to python development. I will be looking to create a single executable out of the project that I am developing, and it seems like PyInstaller is the right tool for this.

If I use PDM with the PEP582 mode, will it work with PyInstaller?

Thanks!

**Comment by frostming** [comment]
I am not sure, will you have a try? But you can always use virtualenv layout if PEP 582 doesn't work

**Comment by alexchandel** [comment]
What is the current procedure for driving the build of an `exe` with PyInstaller using PDM?
