### ISSUE TITLE
Please add `pdm publish --dry-run`

### ISSUE THREAD

**Issue by warsaw** [pdm-project/pdm#1346]
## Is your feature request related to a problem? Please describe.

I am working on adding automatic PyPI publishing to my CI pipeline on git pushing a tag, via `pdm publish`.   Because it's kind of tricky to debug CI pipelines (in GitLab in my case, but likely the same with GitHub), it would be nice if `pdm publish` included a `--dry-run` flag to simulate publishing.  Then I could debug all my `.gitlab-ci.yml` logic and remove the `--dry-run` flag when I have confidence it would work.

## Describe the solution you'd like

Please add `--dry-run` to `pdm publish`.  Thanks for your consideration!

**Comment by frostming** [comment]
What would you like to simulate? Showing the package metadata to be uploaded? If stability matters you can also try the combination of `build` and `twine`, which are well battle-tested.

**Comment by warsaw** [comment]
It would be great to test things like credentials and invoking the correct command.  However, AFAICT, the current legacy upload API doesn't really support dry run.  I haven't really followed the [detailed discussion](https://discuss.python.org/t/pep-694-upload-2-0-api-for-python-package-repositories/16879/35) about [PEP 649](https://peps.python.org/pep-0694/) (the upload 2.0 API), but maybe I will ask that on the thread.

> Showing the package metadata to be uploaded? Does test.pypi.org suffice for your case?

Great points!  Maybe `pdm publish -r https://test.pypi.org/simple` is good enough for developing the CI jobs.  I'll try that and follow up here.

`twine` and `build` certainly are options, but I'm exploring how far we can get with just a single tool (i.e. `pdm`).

Thanks!

**Comment by warsaw** [comment]
This worked great. Thanks @frostming .  Feel free to close this request unless you think there's more to be done.
