### ISSUE TITLE
Weird error during pdm lock (probably because no setup.py or req.txt info)

### ISSUE THREAD

**Issue by SirMartin** [pdm-project/pdm#1350]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

We have a library project that we use in some other projects, I converted this library to PDM from PIP, and I tried to just leave the pyproject.toml file as dependency information (removed requirements.txt and setup.py, I read somewhere that it could work, now I am not sure any longer :face_with_spiral_eyes: ) 

This library is imported in the other projects directly from git in PDM.

When I try to make the _pdm lock_ in another project that uses the library in the version without setup.py or requirements.txt, the lock crashes without giving any extra information.

When I try the pdm lock again, with another commit that the library contains the setup.py file, it doesn't crash.

## Actual behavior

If the library does not contain setup.py or requirements.txt pdm lock crashes without giving any information, just this stack trace.

Without the verbosity
``` 
❯ pdm lock
See /tmp/pdm-lock-k9dgkrtj.log for detailed debug log.
[KeyError]: 
Add '-v' to see the detailed traceback
``` 

```
pdm.termui: 	  <Candidate hypothesis 6.52.1 from https://pypi.org/simple/hypothesis/>
pdm.termui: 	  ... [60 more candidate(s)]
pdm.termui: 	Found matching candidates:
pdm.termui: 	  <Candidate pytest 7.1.2 from https://pypi.org/simple/pytest/>
pdm.termui: 	Found matching candidates:
pdm.termui: 	  <Candidate pytest-spec 3.2.0 from https://pypi.org/simple/pytest-spec/>
pdm.termui: 	Found matching candidates:
pdm.termui: 	  <Candidate pyhamcrest 2.0.4 from https://pypi.org/simple/pyhamcrest/>
pdm.termui: 	  <Candidate pyhamcrest 2.0.3 from https://pypi.org/simple/pyhamcrest/>
unearth: Running command git rev-parse HEAD
pdm.termui: Error occurs
Traceback (most recent call last):
  File "/home/edu/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/termui.py", line 234, in logging
    yield logger
  File "/home/edu/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/cli/actions.py", line 101, in do_lock
    mapping, dependencies = resolve(
  File "/home/edu/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/resolver/core.py", line 30, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/home/edu/.local/share/pdm/venv/lib/python3.10/site-packages/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/edu/.local/share/pdm/venv/lib/python3.10/site-packages/resolvelib/resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/home/edu/.local/share/pdm/venv/lib/python3.10/site-packages/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/home/edu/.local/share/pdm/venv/lib/python3.10/site-packages/resolvelib/resolvers.py", line 203, in _get_updated_criteria
    for requirement in self._p.get_dependencies(candidate=candidate):
  File "/home/edu/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/resolver/providers.py", line 180, in get_dependencies
    deps, requires_python, _ = self.repository.get_dependencies(candidate)
  File "/home/edu/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/models/repositories.py", line 70, in get_dependencies
    requirements, requires_python, summary = getter(candidate)
  File "/home/edu/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/models/repositories.py", line 38, in wrapper
    self._candidate_info_cache.set(candidate, result)
  File "/home/edu/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/models/caches.py", line 63, in set
    key = self._get_key(obj)
  File "/home/edu/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/models/caches.py", line 89, in _get_key
    raise KeyError
KeyError
```

## Expected behavior

It should work without them if it's possible or just at least show an error about why is failing.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.1.3
Python Interpreter:
  /usr/bin/python3.9 (3.9)
Project Root:
  /home/edu/NextailGit/replenishments-minions
Project Packages:
  /home/edu/NextailGit/replenishments-minions/__pypackages__/3.9

{
  "implementation_name": "cpython",
  "implementation_version": "3.9.13",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.18.10-76051810-generic",
  "platform_system": "Linux",
  "platform_version": "#202207071639~1659403207~22.04~cb5f582 SMP 
PREEMPT_DYNAMIC Tue A",
  "python_full_version": "3.9.13",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}


```

**Comment by SirMartin** [comment]
I even cannot understand why in the exception names all the time the python 3.10 when I specify in **pdm use** to use the 3.9

**Comment by frostming** [comment]
You failed to include a valid `name` or `version` in the `pyproject.toml` which is mandatory for an **installable** package



> I even cannot understand why in the exception names all the time the python 3.10 when I specify in **pdm use** to use the 3.9

Because you changed the python **your project uses**, not the one **pdm** uses.

**Comment by SirMartin** [comment]
If I understand correctly it doesn't matter if PDM works in 3.10 and my project in 3.9, it should not affect anything.

About the error, I need mandatory to include at least a setup.py or requirements.txt in order for to PDM consider it an installable library. Am I correct?

**Comment by frostming** [comment]
> If I understand correctly it doesn't matter if PDM works in 3.10 and my project in 3.9, it should not affect anything.
> 
> About the error, I need mandatory to include at least a setup.py or requirements.txt in order for to PDM consider it an installable library. Am I correct?

Read my reply carefully, I didn't mention `setup.py`, I said `pyproject.toml`

**Comment by SirMartin** [comment]
OH MY GOD, so stupid, thanks again.

Wow is a way to improve it, and instead of crashing just show a fancy error message for stupid people like me :astonished:

**Comment by frostming** [comment]
Added a meaningful error message, rather than empty, in 6e81113

**Comment by SirMartin** [comment]
Great work, it would be possible to include in the error from the **obj** some extra information, like package name or something?
