### ISSUE TITLE
`pdm run python ...` mangles spaces in args

### ISSUE THREAD

**Issue by drewp** [pdm-project/pdm#1360]
This looks like a pdm problem:

```
✨ dash(pts/26):/tmp/demo% pdm init -n
Creating a pyproject.toml for PDM...
Using Python interpreter: /usr/bin/python3.10 (3.10)
You are using the PEP 582 mode, no virtualenv is created.
For more info, please visit https://peps.python.org/pep-0582/
Changes are written to pyproject.toml.

PDM 2.1.2 is installed, while 2.1.3 is available.

✨ dash(pts/26):/tmp/demo% pdm run python -c 'import sys' 
  File "<string>", line 1
    import
          ^
SyntaxError: invalid syntax
```

**Comment by frostming** [comment]
The steps are quite simple, but I can't reproduce it, unfortunately. Can you provide a Dockerfile?

**Comment by drewp** [comment]
```
FROM docker.io/ubuntu:22.04

WORKDIR /tmp
RUN apt update
RUN apt install -y python3 curl python3.10-venv
RUN curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 -

RUN /root/.local/bin/pdm init -n
CMD ["/bin/bash", "-c", "/root/.local/bin/pdm run python -c 'import sys'"]
```
Indeed this does not repro. I tried to get the installer to pull pdm 2.1.2, but that went poorly:
* `install-pdm.py -v 2.1.2` tries an http get to ip 2.1.0.2 and stalls
* `install-pdm.py --version 2.1.2` has a weirder error
* `PDM_VERSION=2.1.2 curl ...` happily fetches 2.1.3

**Comment by frostming** [comment]
> * `install-pdm.py --version 2.1.2` has a weirder error

So what is the error?

> * `PDM_VERSION=2.1.2 curl ...` happily fetches 2.1.3

Wrong position of the env modifier, you should export `PDM_VERSION=2.1.2` and it should work

After all, use the **latest** version to reproduce a bug, it is a waste of time debugging a bug on old versions but works fine on the latest version.

**Comment by drewp** [comment]
--version flag is surprising
```
STEP 5/7: RUN curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py --version 2.1.2 | python3 -
  File "<stdin>", line 2
    Release-Date: 2022-01-05
                       ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
```

Anyway, I had forgotten that my `pdm` was running through a shell wrapper, so this was definitely not a pdm problem :) Sorry for the hassle. Maybe some fix comes from the version flag stuff.

**Comment by pawamoy** [comment]
```
curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py --version 2.1.2 | python3 -
```

You can't do that either. Here the `--version` flag is passed to cURL, that's not what you want. To pass the flag, you first need to download the `ìnstall-pdm.py` script locally, and then execute it with Python:

```
curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py --version 2.1.2
python3 install-pdm.py --version 2.1.2
```

**Comment by frostming** [comment]
Yes, to give options, pass them after `python3 -`:

```
curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 - --version 2.1.2
```
