### ISSUE TITLE
Documentation page on what to commit to version control

### ISSUE THREAD

**Issue by gjoseph92** [pdm-project/pdm#1364]
## Is your feature request related to a problem? Please describe.

For beginners, a clear section instructing them what to track (and not track) in version control might be helpful. For comparison, poetry has this: https://python-poetry.org/docs/basic-usage/#commit-your-poetrylock-file-to-version-control.

## Describe the solution you'd like

A "Working with version control" section under https://pdm.fming.dev/latest/usage/project/ recommending that you:
* Always commit `pyproject.toml`
* Almost always commit `pdm.lock` so other devs can contribute to the project in an identical environment, so you can re-use that environment in CI, etc.
* Add `.pdm.toml` to your `.gitignore` and don't commit it (I'm not actually sure about this—is it guaranteed to only contain machine-specific config?)

**Comment by Beartime234** [comment]
Suggested section in PR above. Umm'd and Ahh'd about the wording so feel free to critque/change.
#1373
