### ISSUE TITLE
pdm lock fails path cannot found if subdependency (via VCS or file system) is optional in the dependency.

### ISSUE THREAD

**Issue by SirMartin** [pdm-project/pdm#1375]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

I have 2 libraries, library **B** contains library **A**, and I am trying to add both in my project **C**.

I found 2 separate cases, one works and the other one is failing in the locking process.

The solution that is working, is that library **B** contains library **A** as a **required dependency** or even **dev dependency**.

The solution that not works, is when library **B** contains library **A** as an optional dependency. In that case, when I try to make the _pdm lock_ (in the final project **C**) I got an error that pdm cannot find the path of library **A** (I understand that something happens in the cloning process)

I tried the same in multiple final projects **C** and got the same error.

I also tried with different libraries as **A** in the **B** project. With and without VCS libraries as requirements.

It doesn't matter if in my project **C** I add both **A** and **B** as dependencies or just **B**, I got the same error.

To summarize:
* I got only the error for **VCS** or **local system** references, not if I add a PyPI library (pytest-spec for example)
* I got only the error if the library is defined as **optional**, works fine as mandatory or development.
* The library **B** also uses PDM, and I can make the _locking_ process on it without any issue, it is just when I try to make the lock for a project that uses **B**.

I added the libraries as optional in this way:
```toml
[project.optional-dependencies]
extra = [
    "common @ file:///home/me/work/common",
]
```

```toml
[project.optional-dependencies]
extra = [
"common @ git+https://${GITHUB_USER}:${GITHUB_PIP_TOKEN}@github.com/nextail/py-common.git@f059359d2411dc62e9eeaf7ce84a74baf2cf157e"
]
```

Instead of extra, I also tried with extra1, services, etc, and I got the same issue.

## Actual behavior

```
pdm.termui:   Adding requirement Flask==2.0.1
pdm.termui:   Adding requirement jsonschema==4.1.0
pdm.termui:   Adding requirement common @ git+https://${GITHUB_USER}:${GITHUB_PIP_TOKEN}@github.com/nextail/py-common.git@19b5aa2d6c08396cce0d444a8c30d8fb8dd285d4
unearth: Cloning https://***@github.com/nextail/py-common.git (revision: 19b5aa2d6c08396cce0d444a8c30d8fb8dd285d4) to /tmp/pdm-build-45p5t10k
unearth: Resolved https://***@github.com/nextail/py-common.git to commit 19b5aa2d6c08396cce0d444a8c30d8fb8dd285d4
pdm.termui:   Adding requirement db-tools @ git+https://${GITHUB_USER}:${GITHUB_PIP_TOKEN}@github.com/nextail/py-db-tools.git@405cce99e0cabec52ccd9535a36f298d5201f8f7
unearth: Cloning https://***@github.com/nextail/py-db-tools.git (revision: 405cce99e0cabec52ccd9535a36f298d5201f8f7) to /tmp/pdm-build-ccfz9cvw
unearth: Resolved https://***@github.com/nextail/py-db-tools.git to commit 405cce99e0cabec52ccd9535a36f298d5201f8f7
pdm.termui:   Adding requirement pyyaml==5.4.1
pdm.termui:   Adding requirement retry==0.9.2
pdm.termui:   Adding requirement intercept==0.1.2
pdm.termui:   Adding requirement setuptools>=63.3.0
pdm.termui:   Adding requirement pytest-spec>=3.2.0
pdm.termui:   Adding requirement flake8==3.9.2
pdm.termui:   Adding requirement pytest>=7.1.2
pdm.termui:   Adding requirement hypothesis>=6.46.3
pdm.termui:   Adding requirement python>=3.9
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui:   Adding requirement JSON-log-formatter==0.2.0(from common 0.1.1)
pdm.termui:   Adding requirement rollbar==0.15.1(from common 0.1.1)
pdm.termui:   Adding requirement proxy-tools==0.1.0(from common 0.1.1)
pdm.termui:   Adding requirement slackclient==2.9.3(from common 0.1.1)
pdm.termui:   Adding requirement certifi==2021.10.8(from common 0.1.1)
pdm.termui:   Adding requirement retry==0.9.2(from common 0.1.1)
pdm.termui:   Adding requirement redis==3.4.1(from common 0.1.1)
pdm.termui:   Adding requirement python-dateutil==2.8.1(from common 0.1.1)
pdm.termui:   Adding requirement psutil==5.8.0(from common 0.1.1)
pdm.termui:   Adding requirement pyyaml==5.4.1(from common 0.1.1)
pdm.termui:   Adding requirement protobuf==3.20.1(from common 0.1.1)
pdm.termui:   Adding requirement ddtrace[opentracing]==0.49.3(from common 0.1.1)
pdm.termui:   Adding requirement basictracer==3.1.0(from common 0.1.1)
pdm.termui:   Adding requirement confluent-kafka==1.6.1(from common 0.1.1)
pdm.termui:   Adding requirement setuptools>=62.1.0(from common 0.1.1)
pdm.termui: Pinning: common 0.1.1
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
[RequirementError]: The local path common does not exist.

```

## Expected behavior

The lock process should work well for VCS or local system libraries marked as optional.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.1.3
Python Interpreter:
  /usr/bin/python3.10 (3.10)
Project Root:
  /home/edu/NextailGit/forrestgump
Project Packages:
  /home/edu/NextailGit/forrestgump/__pypackages__/3.10


{
  "implementation_name": "cpython",
  "implementation_version": "3.10.4",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.18.10-76051810-generic",
  "platform_system": "Linux",
  "platform_version": "#202207071639~1659403207~22.04~cb5f582 SMP 
PREEMPT_DYNAMIC Tue A",
  "python_full_version": "3.10.4",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}

```

**Comment by SirMartin** [comment]
I added some extra information that I found while testing. Thanks again for your work.

**Comment by frostming** [comment]
So the dependency chain is `C -> B ->(optional VCS/local) A` right?
Does `C` depend on `B` by local path as well?

**Comment by SirMartin** [comment]
Yes, C depends on B via VCS/local path (I tried both)

Also tried with C depending directly on A, and same happened.



________________________________
De:Frost Ming ***@***.***>
Enviado:martes, 13 de septiembre de 2022 5:20
Para:pdm-project/pdm
Cc: Eduardo; Author 
Asunto: Re: [pdm-project/pdm] pdm lock fails path cannot found if subdependency (via VCS or file system) is optional in the dependency. (Issue #1375)

So the dependency chain is C -> B ->(optional VCS/local) A right?
Does C depend on B by local path as well?

**Comment by frostming** [comment]
Thanks, it has been already fixed in c6398209cabbda5eebba094e512d1661bbcf7c5c

**Comment by SirMartin** [comment]
When should be released?

**Comment by SirMartin** [comment]
Sorry for bothering you again @frostming , but in the commit, you referenced it says that the commit does not belong to the repository. 
![image](https://user-images.githubusercontent.com/854646/190087671-85eefc13-8047-4e55-97a2-dfd4c8b91b96.png)

It is not merged yet, but is this normal behaviour? Would be released soon? I just writing this because for me looks like is lost between branches.

Thanks again.

**Comment by frostming** [comment]
It should be 27a13326a1e172a69d56df3a201a1463e775ad78
