### ISSUE TITLE
PDM PYPI Source as an environment variable

### ISSUE THREAD

**Issue by FaizShah** [pdm-project/pdm#1380]
## Is your feature request related to a problem? Please describe.

Some reproducible build tools used by large companies create a local mirror or proxy of pypi. We would like to be able to pass the mirror as an environment variable when the build tool invokes PDM commands on behalf of the developer.

## Describe the solution you'd like

In NPM there is an environment variable “NPM_CONFIG_REGISTRY” that allows us to pass the local mirror/proxy of npm as an environment variable.

In the python community there is PIP_INDEX_URL for pip.

We would like a similar variable in PDM like “PDM_PYPI_SOURCE” which provides the same behavior as:

```
[[tool.pdm.source]]
url = "localhost:1234"
verify_ssl = true
name = "pypi"
```

From: https://pdm.fming.dev/latest/pyproject/tool-pdm/#specify-other-sources-for-finding-packages

**Comment by pawamoy** [comment]
It's already there ^^
https://pdm.fming.dev/latest/usage/configuration/
PDM_PYPI_URL

**Comment by FaizShah** [comment]
Perfect, thank you.
