### ISSUE TITLE
In project venv not being created

### ISSUE THREAD

**Issue by nickchomey** [pdm-project/pdm#1386]
- [ x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. Create new system user
2. install PDM via the curl command
3. create new folder in home directory, cd into it
4. `pdm init`, select interpreter in pdm folder (`/home/asdf/.local/share/pdm/venv/bin/python`)
5. `pdm add` any package

## Actual behavior

There isn't any `.venv` folder in the project root folder

Moreover, using `pdm config` says `venv.location = /home/asdf/.local/share/pdm/venvs` yet, the folder that is created is actually `venv` - without the `s`

If you create other projects and run `pdm list` you can see all packages installed across all projects. 

Also, in the interactive session of `pdm init`, I'm not getting prompted to create a venv. 

## Expected behavior

I would expect a .venv folder to be created within the project folder, as is described in the documentation. Moreover, I'd expect to only see/have access to packages that are installed within the current project.

## Environment Information

The problem might be related to me being in Ubuntu via WSL2?

```bash
# Paste the output of `pdm info && pdm info --env` below:

asdf@DESKTOP-DIFRTR1:~/testing$ pdm config
build_isolation = True
cache_dir = /home/asdf/.cache/pdm
check_update = True
global_project.fallback = False
global_project.fallback_verbose = True
global_project.path = /home/asdf/.config/pdm/global-project
global_project.user_site = False
install.cache = False
install.cache_method = symlink
install.parallel = True
project_max_depth = 5
pypi.json_api = False
pypi.url = https://pypi.org/simple
pypi.verify_ssl = True
python.use_pyenv = True
python.use_venv = True
strategy.resolve_max_rounds = 10000
strategy.save = minimum
strategy.update = reuse
venv.backend = virtualenv
venv.in_project = True
venv.location = /home/asdf/.local/share/pdm/venvs

Home configuration (/home/asdf/.config/pdm/config.toml):

Project configuration (/home/asdf/testing/.pdm.toml):

asdf@DESKTOP-DIFRTR1:~/testing$ pdm info --env
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.10",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.57.1-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Wed Jul 27 02:20:31 UTC 2022",
  "python_full_version": "3.8.10",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}

asdf@DESKTOP-DIFRTR1:~/testing$ pdm info
PDM version:
  2.1.3
Python Interpreter:
  /home/asdf/.local/share/pdm/venv/bin/python (3.8)
Project Root:
  /home/asdf/testing
Project Packages:
  None

```

**Comment by frostming** [comment]
You've chosen an interpreter inside a venv, making pdm think you are happy with the already created venv and install packages into it.

**Comment by pawamoy** [comment]
PDM has a cache feature that you can enable with `pdm config install.cache true`. With this, you can have as many venvs as you want without wasting disk space. You should definitely **not** use the same venv for multiple projects.

**Comment by frostming** [comment]
> I like the idea of using one shared venv so as to not duplicate package downloads etc..., but I was noticing some conflicts.

The feature is not for sharing packages, but allowing people to use venvs they manually created elsewhere. When you explicitly tell PDM to use the interpreter, you probably don't want it to make one more venv in the project.

**Comment by frostming** [comment]
Closing since it is not an issue with PDM

**Comment by pawamoy** [comment]
> Anyone see any improvements to this workflow?

Nope, that's perfect :smile: 
I myself prefer using PEP 582's `__pypackages__` (that PDM supports) rather than venvs, but that doesn't change the workflow :slightly_smiling_face:
