### ISSUE TITLE
pdm add etcd3 find wrong requirement grpcio>=1.27.1 instead of grpcio==1.27.1

### ISSUE THREAD

**Issue by toppk** [pdm-project/pdm#1389]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
pdm add etcd3

## Actual behavior

installs latest grpcio instead of the pinned version.  

i've tried this on python3.9 inside a virtualenv and it is the same issue.  

I expected it to install  the pinned version
## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.1.4
Python Interpreter:
  /usr/bin/python (3.11)
Project Root:
  /home/toppk/workspace/XXX
Project Packages:
  /home/toppk/workspace/XXX/__pypackages__/3.11
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.0c2",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.19.8-300.fc37.x86_64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Thu Sep 8 19:14:17 UTC 2022",
  "python_full_version": "3.11.0rc2",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}

```

**Comment by frostming** [comment]
Why do you think it is wrong? In the [`setup.py` it replaces `==` in the requirements.txt to `>=`](https://github.com/kragniz/python-etcd3/blob/833a7335150c08e864dd4a0cdda0034017ccd3b0/setup.py#L15-L20). So the requirement is actually `grpcio>=1.27.1`.

**Comment by toppk** [comment]
sorry, I missed that.  nothing is wrong.
