### ISSUE TITLE
Feature Request: Make publish repository CA bundle configurable

### ISSUE THREAD

**Issue by crbeckle** [pdm-project/pdm#1392]
## Problem Statement

In the [feature adding CA bundle configuration](https://github.com/pdm-project/pdm/pull/1267), the configuration was added for dependency resolution; however, when attempting to publish built packages to a custom PyPI repository (e.g. a local Artifactory PyPI repository), with a self-signed certificate, the upload fails with the following:

```bash
[SSLError]: HTTPSConnectionPool(host='custom-artifactory', port=443): Max retries exceeded with url: /artifactory/api/pypi/pypi-local (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate 
verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
```

This happens even when using:

`pdm config pypi.ca_certs /path/to/custom/ca.pem`

## There is a known workaround

Just as in the [feature request for making CA bundles configurable](https://github.com/pdm-project/pdm/issues/1240), the underlying [REQUESTS_CA_BUNDLE environment variable](https://requests.readthedocs.io/en/latest/user/advanced/#ssl-cert-verification) may be set to point to the correct bundle. For example, when using a Unix shell like bash:

```bash
export REQUESTS_CA_BUNDLE=/path/to/custom/ca.pem
```

## The solution I would prefer

- The primary problem with using `REQUESTS_CA_BUNDLE` (outside of needing to set it in new shell windows) is that it affects *both* dependency resolution as well as publishing.
   - Therefore, if using, for example, the standard PyPI for resolution, but a custom upload location, the CA bundle used must be the standard [certifi](https://github.com/certifi/python-certifi) bundle with the custom bundle tacked on.
- For publishing, it seems that the best option would be to:
   1. Add a `ca_bundle` configuration option for a publish repository in the global config (this matches the naming of `pypi.ca_bundle`)
   3. Add a `--ca-bundle` option to the `pdm publish` sub-command to allow overriding from the command line
   4. Allow the `--ca-bundle` override to also be provided via the `PDM_PUBLISH_CA_BUNDLE` environment variable

**Note**: if the proposed solution is acceptable, I would be happy to contribute the new feature.

**Comment by frostming** [comment]
SGTM, welcome to contribute

**Comment by crbeckle** [comment]
> SGTM, welcome to contribute

Great! I'm currently working on it. One update - I messed up in the naming. The current injection of a CA bundle for dependency resolution is `pypi.ca_certs` (rather than `pypi.ca_bundle`). To keep consistent with that naming, I am going to use `ca_certs`, `--ca-certs`, and `PDM_PUBLISH_CA_CERTS`.
