### ISSUE TITLE
Can pdm resolve problem of installing geopandas？

### ISSUE THREAD

**Issue by forestbat** [pdm-project/pdm#1393]
As we all know geopandas need [GDAL API](https://gdal.org/api/index.html)，and it's hard to setup even if I use conda to install it.
Today I knew pdm and I try to use it to install geopandas，however the installation still crashed like this：
https://paste.ubuntu.com/p/qMb8BzNF6M/
It seems same as installing with pip，so can pdm solve the problem？If can't，I will try to abandon geopandas.

**Comment by pawamoy** [comment]
There's nothing more PDM can do in this area compared to pip or any other package installer: you need to comply with geopandas requirements, that is to set a GDAL API, following the hints they output in the logs.

**Comment by forestbat** [comment]
> There's nothing more PDM can do in this area compared to pip or any other package installer: you need to comply with geopandas requirements, that is to set a GDAL API, following the hints they output in the logs.

Ok，I know.
