### ISSUE TITLE
No docs on how to opt into the 'centralized installation cache'

### ISSUE THREAD

**Issue by acalvino4** [pdm-project/pdm#1409]
## Is your feature request related to a problem? Please describe.

From the main readme:

<img width="406" alt="image" src="https://user-images.githubusercontent.com/43254861/192937055-5de8b2a8-c177-4c2b-bc8a-cec5e75b25c0.png">

but I don't see any instructions on how to opt in.

## Describe the solution you'd like

Could you add a note somewhere in the readme describing how to opt-in? Thanks!

**Comment by frostming** [comment]
https://pdm.fming.dev/latest/usage/project/#cache-the-installation-of-wheels
