### ISSUE TITLE
`pdm install` started failing on Python 3.7 after `importlib-metadata` released v5.0.0

### ISSUE THREAD

**Issue by FeodorFitsner** [pdm-project/pdm#1411]
A few hours ago `importlib-metadata` [released v5.0.0](https://pypi.org/project/importlib-metadata/5.0.0/) and `pdm install` started failing on Python 3.7.

Failing CI build: https://ci.appveyor.com/project/flet-dev/flet/builds/44943064/job/6j92ckkaol60n8q0#L98
Last good build: https://ci.appveyor.com/project/flet-dev/flet/builds/44942650/job/uxk5x5m152jrcl3r#L98

## Steps to reproduce

`pdm install`

## Actual behavior

```
Traceback (most recent call last):
  File "/home/appveyor/venv3.7.13/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/appveyor/venv3.7.13/lib/python3.7/site-packages/pdm/core.py", line 254, in main
    return Core().main(args)
  File "/home/appveyor/venv3.7.13/lib/python3.7/site-packages/pdm/core.py", line 55, in __init__
    self.load_plugins()
  File "/home/appveyor/venv3.7.13/lib/python3.7/site-packages/pdm/core.py", line 240, in load_plugins
    entry_points.get("pdm", []), entry_points.get("pdm.plugin", [])
AttributeError: 'EntryPoints' object has no attribute 'get'
```

## Expected behavior

The command works normally.

**Comment by analogrithems** [comment]
i've just started seeing the same in my circle builds started yesterday

**Comment by menzenski** [comment]
We are seeing this as well.

**Comment by lecardozo** [comment]
@frostming do you think updating the plugin loading snippet to the new `importlib-metadata==5.0.0` EntryPoints would be enough? It seems to me that this API has diverged between importlib.metadata and importlib_metadata. 🤔

I've tried a quick fix to support this new API on [this branch](https://github.com/lecardozo/pdm/tree/fix/importlib-metadata), but I'm not quite sure this will be enough to keep support for both 3.7 and >=3.8

**Comment by lecardozo** [comment]
I'm seeing a few options here:

- setting an upper bound for **importlib-metadata** (<5.0.0) for Python 3.7 (seems reasonable)
- keeping the code as is and dropping support for Python 3.7 (doesn't seem the best option, IMO)
- treating EntryPoints differently between different importlib-metadata major versions

Are there any other options that we should be considering?

**Comment by pawamoy** [comment]
I'd vote for the first solution: setting an upper bound for importlib-metadata (<5.0.0) for Python 3.7.
It's the most straight-forward fix, will not require more maintenance, and can easily be removed once Python 3.7 is EOL (which happens in middle of 2023 I think, so not far away). Users will just have to upgrade PDM, and done 🙂

**Comment by henryiii** [comment]
Ahh, `pdm install` bumps `importlib_metadata` up to 5, then nothing works anymore. So the current solution doesn't work even as a temporary one if a package you are using requires `importlib_metadata>=5`, which packages are starting to do. :(

**Comment by frostming** [comment]
Fixing in #1467
