### ISSUE TITLE
pdm sync fails with 401 when using pypi mirror with credentials from keyring 

### ISSUE THREAD

**Issue by hcoohb** [pdm-project/pdm#1420]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

1. Use a pypi mirror that require authentication.  (sorry I cannot share since this is a company internal mirror)
2. Set global pypi.url: `pdm config --global pypi.url https://pypiurlmirror.com/artifactory/api/pypi/internal-pypi/simple`
3. Inject keying for pdm in pipx: `pipx inject pdm keyring`
4. `pdm init` and leave project.name blank
5. `pdm add pyyaml -v`: it will prompt credentials and ability to save. (Amazing, I love it!!!). The install works great.
6. Now add a project name in pyproject.toml
7. try `pdm sync -v`

## Actual behavior

Following those steps, now that there is a package name, pdm will try to install it and doing so, it seems to try to collect package pdm-pep517 but without using the keyring auth resulting in error 401.  
it then hangs undefinitely.  
Here is the end of the log showing the error 401:

```bash
PS C:\Users\User.name\Devel\testp2> pdm sync -vv
All packages are synced to date, nothing to do.
Installing the project as an editable package...
pdm.termui: Preparing isolated env for PEP 517 build...
pdm.termui: Running PEP 517 backend to build a wheel for <Link file:///C:/Users/User.name/Devel/testp2 (from None)>
pdm.termui: Using pip 21.3.1 from C:\Users\User.name\.local\pipx\venvs\pdm\lib\site-packages\pip (python 3.7)
pdm.termui: Non-user install due to --prefix or --target option
pdm.termui: Created temporary directory: C:\Users\User.name\AppData\Local\Temp\pip-ephem-wheel-cache-vlt595wp
pdm.termui: Created temporary directory: C:\Users\User.name\AppData\Local\Temp\pip-req-tracker-a5bdzck8
pdm.termui: Initialized build tracking at C:\Users\User.name\AppData\Local\Temp\pip-req-tracker-a5bdzck8
pdm.termui: Created build tracker: C:\Users\User.name\AppData\Local\Temp\pip-req-tracker-a5bdzck8
pdm.termui: Entered build tracker: C:\Users\User.name\AppData\Local\Temp\pip-req-tracker-a5bdzck8
pdm.termui: Created temporary directory: C:\Users\User.name\AppData\Local\Temp\pip-install-_alo6ajd
pdm.termui: Looking in indexes: https://pypiurlmirror.com/artifactory/api/pypi/internal-pypi/simple
pdm.termui: 1 location(s) to search for versions of pdm-pep517:
pdm.termui: * https://pypiurlmirror.com/artifactory/api/pypi/internal-pypi/simple/pdm-pep517/
pdm.termui: Fetching project page and analyzing links: https://pypiurlmirror.com/artifactory/api/pypi/internal-pypi/simple/pdm-pep517/
pdm.termui: Getting page https://pypiurlmirror.com/artifactory/api/pypi/internal-pypi/simple/pdm-pep517/
pdm.termui: Found index url https://pypiurlmirror.com/artifactory/api/pypi/internal-pypi/simple
pdm.termui: Looking up "https://pypiurlmirror.com/artifactory/api/pypi/internal-pypi/simple/pdm-pep517/" in the cache
pdm.termui: Request header has "max_age" as 0, cache bypassed
pdm.termui: Starting new HTTPS connection (1): pypiurlmirror.com:443
pdm.termui: https://pypiurlmirror.com:443 "GET /artifactory/api/pypi/internal-pypi/simple/pdm-pep517/ HTTP/1.1" 401 91
pdm.termui: Found index url https://pypiurlmirror.com/artifactory/api/pypi/internal-pypi/simple
```

## Expected behavior

It would be great if we could use the keyring for all steps within pdm, that way no need to setup environment variables with credentials.  
Btw, if using the url "https://${INDEX_USER}:${INDEX_KEY}@pypiurlmirror.com/artifactory/api/pypi/internal-pypi/simple" with credentials in env var as describe in the doc, it works fine.

## Environment Information

```bash
PS C:\Users\User.nameDevel\test> pdm info
PDM version:
  2.1.5
Python Interpreter:
  C:\Users\User.name\AppData\Local\pdm\pdm\venvs\testp2-0VA1WQd9-3.7\Scripts\python.exe (3.7)
Project Root:
  C:/Users/User.Name/Devel/testp2
Project Packages:
  None
```

```bash
PS C:\Users\User.name\Devel\testp2> pdm info --env 
{
  "implementation_name": "cpython",
  "implementation_version": "3.7.5",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19041",
  "python_full_version": "3.7.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.7",
  "sys_platform": "win32"
}
```

**Comment by frostming** [comment]
Due to the special design of PDM, the `pip` invoked by PEP 517 builder(called the project environment) is not lying in the environment of PDM(called the host environment), by `pipx inject keyring` you injected `keyring` into the *host* environment. So the `pip` can't see it.

The reason behind it is we must build the package, and install build dependencies in the *project* environment(indeed it's an isolated clone of that environment, unless `--no-isolation` is passed).

To workaround it, `pdm add keyring` and add `--no-isolation` to the following commands.

**Comment by hcoohb** [comment]
Oh I see!
Thanks for the quick response and explanation. Now I understand why this is not the preferred option and the doc only mention the auth method using environment variables. Pity, that would have been very handy to just use keyring once and forget.
Thanks again
