### ISSUE TITLE
Search in github organization

### ISSUE THREAD

**Issue by thiagola92** [pdm-project/pdm#1423]
## Is your feature request related to a problem? Please describe.
I didn't want to host a Pypi server, so i was using VCS in all my packages. 

I saw in documentation that i could use a [directory as reference](https://pdm.fming.dev/latest/pyproject/tool-pdm/#find-links-source) but would still be very annoying if sharing with people was needed.  

## Describe the solution you'd like
I was wondering if is possible to have a Github organization as source. Anything like:  
```
url = "https://github.com/ORGANIZATION"
name = "organization"
```

**Comment by frostming** [comment]
The source must implement [PEP 503](https://peps.python.org/pep-0503/) as an index. We are not going to support non-standard index servers.
