### ISSUE TITLE
Configure username and password for source in config

### ISSUE THREAD

**Issue by thiagola92** [pdm-project/pdm#1424]
## Is your feature request related to a problem? Please describe.
I saw that there is a way to use [environment variables](https://pdm.fming.dev/latest/usage/project/#hide-the-credentials-from-pyprojecttoml) but would be bad to configure like the [`pdm publish`](https://pdm.fming.dev/latest/usage/project/#configure-the-repository-secrets-for-upload)?  

## Describe the solution you'd like
Configure a new source in config.toml file like `pdm publish` does.

**Comment by thiagola92** [comment]
PS: Using environment variables is not a problem, i can always adapt my installation script to add the variables in `.bashrc`

**Comment by frostming** [comment]
You can store them into the `keyring`.
