### ISSUE TITLE
need ignore some package

### ISSUE THREAD

**Issue by bingoct** [pdm-project/pdm#1435]
need ignore install package specifed, such as pip install --ignore-installed.

**Comment by frostming** [comment]
Do you mean `pdm sync --reinstall`? please give more information on what you desire.

**Comment by bingoct** [comment]
By the way , what is  the `--no-deps` option in PDM.
I have installed  `pytorch-directml=1.8.0a0.dev220506`. 
If i install `torchvision==0.9.1`,  how cloud i skip install `torch`.
Thanks.
@frostming

**Comment by frostming** [comment]
PDM doesn't and won't provide such option.
