### ISSUE TITLE
Build distributions with locked dependencies

### ISSUE THREAD

**Issue by lecardozo** [pdm-project/pdm#1437]
## Is your feature request related to a problem? Please describe.

We have a project that is internally distributed as a wheel (although not a library). Currently, we can't benefit from PDM's locking capabilities (beyond the development environment) because the locked dependencies (transitive and direct) are not included in the distribution. 

## Describe the solution you'd like

Was wondering if it would make sense to have something like (👇 ) which would generate a distribution with locked dependencies, not only those direct dependencies defined by the user on pyproject.toml

```shell
# Adds all locked dependencies from pdm.lock into dists pyproject.toml/METADATA
$ pdm build --locked
```

I feel that this could be achieved with the usage of a `post_build` hook, but that would require editing the already packaged distribution.

Any thoughts on that?

**Comment by lecardozo** [comment]
I was able to achieve this by using `pre_build` and `post_build` hooks. No need to edit wheels.

- `pre_build` hook creates a new **pyproject.toml** with locked dependencies (keeps the original pyproject.toml on a backup file).
- `post_build` just renames the backup file back to **pyproject.toml**.

Feels like a small hack, but it's doable. 🤔

**Comment by gazpachoking** [comment]
@lecardozo Do you have an example repo where I can look at how you are doing this?

**Comment by gazpachoking** [comment]
I had my own go at implementing this which turned out pretty well.

https://github.com/gazpachoking/pdm-buildlocked

Haven't published it on pypi yet though. Not sure if it should be a flag to the existing build command. The docs mention plugins can "Add additional options to existing PDM commands" but I couldn't figure out how to do that.

**Comment by lecardozo** [comment]
That's definitely a more elegant solution @gazpachoking! 😄 Regarding adding this to an existing command, this is indeed mentioned on the documentation. Not sure how to currently achieve this, though. 

Apparently plugins are loaded after PDM commands were already registered to the the argument subparser. Maybe we can access those directly from the `core` object and add a new argument to an existing command? Seems kinda hacky, so I'm not sure if this is the best path.

**Comment by frostming** [comment]
> Apparently plugins are loaded after PDM commands were already registered to the argument subparser. Maybe we can access those directly from the `core` object and add a new argument to an existing command? Seems kinda hacky, so I'm not sure if this is the best path.

No need to monkeypatch like that, you can subclass that command and register it with **the same name** in your plugin to override it.

**Comment by gazpachoking** [comment]
> No need to monkeypatch like that, you can subclass that command and register it with **the same name** in your plugin to override it.

Oh. That makes sense. It seems to work functionally, but doesn't fully override the old command in the help.
![image](https://user-images.githubusercontent.com/187133/196334291-50c39275-7b8d-433a-80c0-25706b6e2657.png)

**Comment by gazpachoking** [comment]
I switched to adding a flag to the `build` command, and released an alpha on pypi.

**Comment by lecardozo** [comment]
I've tested it locally and it seems to be working quite well. The `build` command is only appearing once, at the end of the list, and the wheel metadata is properly reflecting locked direct and transitive dependencies.

**Comment by gazpachoking** [comment]
> I've tested it locally and it seems to be working quite well. The `build` command is only appearing once, at the end of the list, and the wheel metadata is properly reflecting locked direct and transitive dependencies.

Glad to hear it! Maybe it's only in my dev environment that it shows up twice.

**Comment by lofidevops** [comment]
@gazpachoking @lecardozo Thanks for your hard work! I was just investigating this issue while considering pdm as an installation tool in a production environment, where you definitely want pinned dependencies. I will try out pdm-buildlocked and pip-resolved and leave any feedback there!

**Comment by gazpachoking** [comment]
Sounds good! @lofidevops If pdm-buildlocked works properly for you as well, I'll call it good to go and cut a non-alpha release.

**Comment by sigma67** [comment]
Hi all, I just built a plugin to do this: https://github.com/sigma67/pdm-build-locked
