### ISSUE TITLE
Unexpected "No candidate is found" when viable package exists.

### ISSUE THREAD

**Issue by tgolsson** [pdm-project/pdm#1438]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Using the PDM directory in this repository: https://github.com/tgolsson/python-repository-tools-comparison, I've done a `pdm lock`, followed by `pdm sync`. This is on WSL2, Ubuntu 20.04, Python 3.8.10 on the host. Rest of config should be in repo.

## Actual behavior

```bash
$ pdm -v sync
Synchronizing working set with lock file: 1 to add, 0 to update, 0 to remove

  ✖ Install box2d 2.3.10 failed
Retry failed jobs
  ✖ Install box2d 2.3.10 failed

ERRORS:
add box2d failed:
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ts/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 225, in install_candidate
    self.manager.install(can)
  File "/home/ts/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/installers/manager.py", line 39, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "/home/ts/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/models/candidates.py", line 366, in build
    self.obtain(allow_all=False)
  File "/home/ts/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/models/candidates.py", line 418, in obtain
    raise CandidateNotFound(
pdm.exceptions.CandidateNotFound: No candidate is found for `box2d` that matches the environment or hashes

See /tmp/pdm-install-tmv4_zqq.log for detailed debug log.
[InstallationError]: Some package operations are not complete yet
Add '-v' to see the detailed traceback
```

Log file:

<details>
   <summary>Log file</summary>

   <pre>
unearth: Skip link <Link https://files.pythonhosted.org/packages/10/30/c6a4b95df8f92e56efc4415f9331bf402c54899637b0c9f9de4c6badecc0/Box2D-2.3.10-cp36-cp36m-win_amd64.whl (from None)>: none of the wheel tags(cp36-cp36m-win_amd64) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/17/d4/d9748c9981791e5cfca3fc755e01078a496e0817e4196a6166c6a1a805d1/Box2D-2.3.10-cp37-cp37m-manylinux1_i686.whl (from None)>: none of the wheel tags(cp37-cp37m-manylinux1_i686) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/1c/9e/da67ddb43f29634ee05b85bff5a1bf5f418c72169331b1abdc307ddadbe6/Box2D-2.3.10-cp36-cp36m-manylinux1_i686.whl (from None)>: none of the wheel tags(cp36-cp36m-manylinux1_i686) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/22/1b/ce95bb5d1807d4d85af8d0c90050add1a77124459f8097791f0c39136d53/Box2D-2.3.10-cp37-cp37m-manylinux1_x86_64.whl (from None)>: none of the wheel tags(cp37-cp37m-manylinux1_x86_64) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/30/7b/91ebadf3d7ffaf934781141e3b0dcdd97c8e9edac3653727647a6d3c4291/Box2D-2.3.10-cp36-cp36m-win32.whl (from None)>: none of the wheel tags(cp36-cp36m-win32) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/4e/9d/7f79ba35454c7ad907d2ba0548caad05dffb32db82760f19edeb2ec75de2/Box2D-2.3.10-cp38-cp38-manylinux1_i686.whl (from None)>: none of the wheel tags(cp38-cp38-manylinux1_i686) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/52/4a/3e20a02957f48750efe0967c98908390ce911808925dd59218e75f7c0a28/Box2D-2.3.10-cp35-cp35m-macosx_10_6_intel.whl (from None)>: none of the wheel tags(cp35-cp35m-macosx_10_6_intel) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/5d/a6/825cdbc0de7edb637328d95b9ac2793714e15900ba4a055df73d6f2590b7/Box2D-2.3.10-cp36-cp36m-macosx_10_9_x86_64.whl (from None)>: none of the wheel tags(cp36-cp36m-macosx_10_9_x86_64) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/6c/90/34166d73babf9010c06cf890c48c1155aec4d69125267e9777040e058ccd/Box2D-2.3.10-cp38-cp38-win_amd64.whl (from None)>: none of the wheel tags(cp38-cp38-win_amd64) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/72/42/6a8e18a93f75c84fd065cc9b57a4117219fa3c5a002a80cab8f339883ec8/Box2D-2.3.10-cp38-cp38-manylinux1_x86_64.whl (from None)>: none of the wheel tags(cp38-cp38-manylinux1_x86_64) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/72/f6/5651732d411ab7786517e1ad1fda6c621306204c5e9d1b59355286e55e86/Box2D-2.3.10-cp27-cp27m-win32.whl (from None)>: none of the wheel tags(cp27-cp27m-win32) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/73/04/c9bc6ccbf9126ef52510d717e9be48124f7db3b910cd39fe5b7394c3a7f8/Box2D-2.3.10-cp38-cp38-macosx_10_9_x86_64.whl (from None)>: none of the wheel tags(cp38-cp38-macosx_10_9_x86_64) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/7f/69/83eff7e98ff9cc1248976a8602d1b7729d0cf2c55932be82277b47f29fdf/Box2D-2.3.10-cp37-cp37m-win32.whl (from None)>: none of the wheel tags(cp37-cp37m-win32) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/89/8e/524bac8b658db8a3a23bfa50df33123e3ab74eb98af1362ab279e1995879/Box2D-2.3.10-cp35-cp35m-manylinux1_x86_64.whl (from None)>: none of the wheel tags(cp35-cp35m-manylinux1_x86_64) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/a9/0b/d48d42dd9e19ce83a3fb4eee074e785b6c6ea612a2244dc2ef69427d338b/Box2D-2.3.10-cp36-cp36m-manylinux1_x86_64.whl (from None)>: none of the wheel tags(cp36-cp36m-manylinux1_x86_64) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/ac/b8/7016a3b1ef7e3f9d8ec6da5a5e2d9fc04f69f36afb307cc5c641a48d11b9/Box2D-2.3.10-cp38-cp38-win32.whl (from None)>: none of the wheel tags(cp38-cp38-win32) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/bd/dc/0ce0b594ef0b54591ab8d87a501ad59e638bad34d664a58fd7a6ec780015/Box2D-2.3.10-cp37-cp37m-macosx_10_9_x86_64.whl (from None)>: none of the wheel tags(cp37-cp37m-macosx_10_9_x86_64) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/cb/92/c145fe96e5c47dbb3ab70bcd7ff9cc536aa617e5d294c3f467a1a1f303a7/Box2D-2.3.10-cp35-cp35m-manylinux1_i686.whl (from None)>: none of the wheel tags(cp35-cp35m-manylinux1_i686) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/f0/fe/143cc8dcbee290eac1d7b89a6ce470de2f6569bc24a8de31c1b80a15957c/Box2D-2.3.10-cp37-cp37m-win_amd64.whl (from None)>: none of the wheel tags(cp37-cp37m-win_amd64) are compatible
pdm.termui: Error occurs:
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ts/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 225, in install_candidate
    self.manager.install(can)
  File "/home/ts/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/installers/manager.py", line 39, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "/home/ts/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/models/candidates.py", line 366, in build
    self.obtain(allow_all=False)
  File "/home/ts/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/models/candidates.py", line 418, in obtain
    raise CandidateNotFound(
pdm.exceptions.CandidateNotFound: No candidate is found for `box2d` that matches the environment or hashes
unearth: Skip link <Link https://files.pythonhosted.org/packages/10/30/c6a4b95df8f92e56efc4415f9331bf402c54899637b0c9f9de4c6badecc0/Box2D-2.3.10-cp36-cp36m-win_amd64.whl (from None)>: none of the wheel tags(cp36-cp36m-win_amd64) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/17/d4/d9748c9981791e5cfca3fc755e01078a496e0817e4196a6166c6a1a805d1/Box2D-2.3.10-cp37-cp37m-manylinux1_i686.whl (from None)>: none of the wheel tags(cp37-cp37m-manylinux1_i686) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/1c/9e/da67ddb43f29634ee05b85bff5a1bf5f418c72169331b1abdc307ddadbe6/Box2D-2.3.10-cp36-cp36m-manylinux1_i686.whl (from None)>: none of the wheel tags(cp36-cp36m-manylinux1_i686) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/22/1b/ce95bb5d1807d4d85af8d0c90050add1a77124459f8097791f0c39136d53/Box2D-2.3.10-cp37-cp37m-manylinux1_x86_64.whl (from None)>: none of the wheel tags(cp37-cp37m-manylinux1_x86_64) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/30/7b/91ebadf3d7ffaf934781141e3b0dcdd97c8e9edac3653727647a6d3c4291/Box2D-2.3.10-cp36-cp36m-win32.whl (from None)>: none of the wheel tags(cp36-cp36m-win32) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/4e/9d/7f79ba35454c7ad907d2ba0548caad05dffb32db82760f19edeb2ec75de2/Box2D-2.3.10-cp38-cp38-manylinux1_i686.whl (from None)>: none of the wheel tags(cp38-cp38-manylinux1_i686) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/52/4a/3e20a02957f48750efe0967c98908390ce911808925dd59218e75f7c0a28/Box2D-2.3.10-cp35-cp35m-macosx_10_6_intel.whl (from None)>: none of the wheel tags(cp35-cp35m-macosx_10_6_intel) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/5d/a6/825cdbc0de7edb637328d95b9ac2793714e15900ba4a055df73d6f2590b7/Box2D-2.3.10-cp36-cp36m-macosx_10_9_x86_64.whl (from None)>: none of the wheel tags(cp36-cp36m-macosx_10_9_x86_64) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/6c/90/34166d73babf9010c06cf890c48c1155aec4d69125267e9777040e058ccd/Box2D-2.3.10-cp38-cp38-win_amd64.whl (from None)>: none of the wheel tags(cp38-cp38-win_amd64) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/72/42/6a8e18a93f75c84fd065cc9b57a4117219fa3c5a002a80cab8f339883ec8/Box2D-2.3.10-cp38-cp38-manylinux1_x86_64.whl (from None)>: none of the wheel tags(cp38-cp38-manylinux1_x86_64) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/72/f6/5651732d411ab7786517e1ad1fda6c621306204c5e9d1b59355286e55e86/Box2D-2.3.10-cp27-cp27m-win32.whl (from None)>: none of the wheel tags(cp27-cp27m-win32) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/73/04/c9bc6ccbf9126ef52510d717e9be48124f7db3b910cd39fe5b7394c3a7f8/Box2D-2.3.10-cp38-cp38-macosx_10_9_x86_64.whl (from None)>: none of the wheel tags(cp38-cp38-macosx_10_9_x86_64) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/7f/69/83eff7e98ff9cc1248976a8602d1b7729d0cf2c55932be82277b47f29fdf/Box2D-2.3.10-cp37-cp37m-win32.whl (from None)>: none of the wheel tags(cp37-cp37m-win32) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/89/8e/524bac8b658db8a3a23bfa50df33123e3ab74eb98af1362ab279e1995879/Box2D-2.3.10-cp35-cp35m-manylinux1_x86_64.whl (from None)>: none of the wheel tags(cp35-cp35m-manylinux1_x86_64) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/a9/0b/d48d42dd9e19ce83a3fb4eee074e785b6c6ea612a2244dc2ef69427d338b/Box2D-2.3.10-cp36-cp36m-manylinux1_x86_64.whl (from None)>: none of the wheel tags(cp36-cp36m-manylinux1_x86_64) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/ac/b8/7016a3b1ef7e3f9d8ec6da5a5e2d9fc04f69f36afb307cc5c641a48d11b9/Box2D-2.3.10-cp38-cp38-win32.whl (from None)>: none of the wheel tags(cp38-cp38-win32) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/bd/dc/0ce0b594ef0b54591ab8d87a501ad59e638bad34d664a58fd7a6ec780015/Box2D-2.3.10-cp37-cp37m-macosx_10_9_x86_64.whl (from None)>: none of the wheel tags(cp37-cp37m-macosx_10_9_x86_64) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/cb/92/c145fe96e5c47dbb3ab70bcd7ff9cc536aa617e5d294c3f467a1a1f303a7/Box2D-2.3.10-cp35-cp35m-manylinux1_i686.whl (from None)>: none of the wheel tags(cp35-cp35m-manylinux1_i686) are compatible
unearth: Skip link <Link https://files.pythonhosted.org/packages/f0/fe/143cc8dcbee290eac1d7b89a6ce470de2f6569bc24a8de31c1b80a15957c/Box2D-2.3.10-cp37-cp37m-win_amd64.whl (from None)>: none of the wheel tags(cp37-cp37m-win_amd64) are compatible
pdm.termui: Error occurs:
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ts/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 225, in install_candidate
    self.manager.install(can)
  File "/home/ts/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/installers/manager.py", line 39, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "/home/ts/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/models/candidates.py", line 366, in build
    self.obtain(allow_all=False)
  File "/home/ts/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/models/candidates.py", line 418, in obtain
    raise CandidateNotFound(
pdm.exceptions.CandidateNotFound: No candidate is found for `box2d` that matches the environment or hashes
pdm.termui: Error occurs
Traceback (most recent call last):
  File "/home/ts/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/termui.py", line 234, in logging
    yield logger
  File "/home/ts/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 412, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet
    </pre>
</details>

## Expected behavior

The manylinux1 variant is compatible (to my knowledge) and should be installed. Downloading this and manually installing with `pdm run pip $WHEEL` works fine. The SHA256 sum matches what's in the lock file.

## Environment Information

```bash
PDM version:
  2.1.5
Python Interpreter:
  /home/ts/Repositories/python-tools-comparison/pdm/.venv/bin/python (3.9)
Project Root:
  /home/ts/Repositories/python-tools-comparison/pdm
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.5",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.57.1-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Wed Jul 27 02:20:31 UTC 2022",
  "python_full_version": "3.9.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by tgolsson** [comment]
OK; obviously I should've read the info output. I think I'd done something wrong during configuration and the Python had reset to 3.9, which is what it does say in the env output. My bad!

**Comment by tgolsson** [comment]
(It is quite confusing still that the pip is fine with installing the 3.8 wheel while the configured python is 3.9, but that's not a bug in PDM.)

**Comment by dev590t** [comment]
I have the same issue. 
```
dev_1@dev_1 /tmp/test$ pdm add kaleido
Adding packages to default dependencies: kaleido
🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 1 to add, 0 to update, 0 to remove

  ✖ Install kaleido 0.2.1.post1 failed
Retry failed jobs
  ✖ Install kaleido 0.2.1.post1 failed

ERRORS:
add kaleido failed:
Traceback (most recent call last):
  File "/gnu/store/abznl1yzi6isa57mh1mj3fsdylksqd7m-python-3.8.2/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/dev_1/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 225, in 
install_candidate
    self.manager.install(can)
  File "/home/dev_1/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/installers/manager.py", line 39, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "/home/dev_1/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/models/candidates.py", line 361, in build
    self.obtain(allow_all=False)
  File "/home/dev_1/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/models/candidates.py", line 413, in obtain
    raise CandidateNotFound(
pdm.exceptions.CandidateNotFound: No candidate is found for `kaleido` that matches the environment or hashes

dev_1@dev_1 /tmp/test$ pdm info
PDM version:
  2.2.1
Python Interpreter:
  /home/dev_1/.local/share/pdm/venv/bin/python (3.8)
Project Root:
  /tmp/test
Project Packages:
  None
```

How did you solve the problem?

**Comment by 00sapo** [comment]
> How did you solve the problem?

Same issue for me. The following solves the problems for me:

```
install_pip = "python -m ensurepip"
install_deps = "python -m pip install kaleido==0.2.1"
post_install = {composite = ["install_pip", "install_deps"]}
```

**Comment by frostming** [comment]
`kaleido 0.2.1.post1` is an incomplete release that doesn't have wheels for your system, fix it by excluding that version:

```
pdm add kaleido!=0.2.1.post1
```

**Comment by 00sapo** [comment]
> `kaleido 0.2.1.post1` is an incomplete release that doesn't have wheels for your system, fix it by excluding that version:
> 
> ```
> pdm add "kaleido!=0.2.1.post1"
> ```

In my case, it fails with 0.2.1 as well, this is why I relied on pure pip
