### ISSUE TITLE
Make enabling pep582 more robust

### ISSUE THREAD

**Issue by acalvino4** [pdm-project/pdm#1439]
## Is your feature request related to a problem? Please describe.

The docs say to add a line similar to
`pdm --pep582 >> ~/.bash_profile`
to enable pep582. This output contains a path which includes the current python version (currently 3.10). At some point pdm will presumably be updated to depend on another version of python and this will probably break / require tweaking.

## Describe the solution you'd like

I suspect or more robust setup would be similar to what is required in setting up `rbenv` or `pyenv` where they have you add something like `eval "$(rbenv init - zsh)"` to your `.bashrc`. In other words, just change the line in the docs to
`echo 'eval "$(pdm --pep582)"'>>.bashrc`
so that as pdm's dependencies change, user configurations still work.

**Comment by frostming** [comment]
> just change the line in the docs to
> `echo 'eval "$(pdm --pep582)"'>>.bashrc`

Yeah, you can do it, but it adds some overhead to the startup of the shell, so I would rather keep the recommendation in the docs.
