### ISSUE TITLE
Cached version of current project used when using `pdm lock`

### ISSUE THREAD

**Issue by tgolsson** [pdm-project/pdm#1441]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

I'm working on a package that that has a self-referential pattern for its own optional dependencies; as described for `foo[socks,jwt]` here: https://pdm.fming.dev/latest/usage/dependency/#add-dependencies. I ran `pdm lock` to generate a lockfile. I then changed the description and ran `pdm lock` again.

The exact config is:
```toml
[project.optional-dependencies]
a = ["some-pkg==1.2.3"]
b = [
    "another-package=1.2.3.4",
]
ci = ["gsutil>=4.66", "pkg[a,b]"]
```

## Actual behavior

After changing the description, the base case `foo` uses the old summary but the target `foo[socks,jwt]` uses the new summary.

Like this:

```toml

[[package]]
name = "pkg"
version = "0.1.0"
requires_python = "~=3.8"
summary = "old summary"
dependencies = [ "..." ]

[[package]]
name = "pkg"
version = "0.1.0"
extras = ["a", "b"]
requires_python = "~=3.8"
summary = "new summary"
dependencies = [ "..." ]
```

## Expected behavior

Both package references use the same summary. Deleting `~/.cache/pdm/metadata/package_meta_NNNNN.json` and running `pdm lock` again solves the issue, making both references use `new summary`.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.1.5
Python Interpreter:
  <REDACTED>/pkg/.venv/bin/python (3.8)
Project Root:
  <REDACTED>/pkg
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.10",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.68.1-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Mon Sep 19 19:14:52 UTC 2022",
  "python_full_version": "3.8.10",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
Is `pkg` a published package? then updating description should bump the version right?

**Comment by tgolsson** [comment]
No; and I think that may have been part of the problem. `pkg` is the local package described in the `pyproject.toml`. It unfortunately collides with a package on pypi, and when later working with `pdm update` it failed because of this - so it might have silently affected other packages too.

**Comment by tgolsson** [comment]
This might be related to the same issue as in #1470.
