### ISSUE TITLE
Vertically align config output

### ISSUE THREAD

**Issue by eugenesvk** [pdm-project/pdm#1447]
## Is your feature request related to a problem? Please describe.

Currently `pdm config` output is unpleasant to read since keys are not separated from value properly

```
build_isolation = True
cache_dir = /Users/u/Library/Caches/pdm
check_update = True
global_project.fallback = False
global_project.fallback_verbose = True
global_project.path = /Users/u/Library/Preferences/pdm/global-project
global_project.user_site = False
install.cache = False
install.cache_method = symlink
install.parallel = True
project_max_depth = 5
pypi.json_api = False
pypi.url = https://pypi.org/simple
pypi.verify_ssl = True
python.use_pyenv = True
python.use_venv = True
strategy.resolve_max_rounds = 10000
strategy.save = minimum
strategy.update = reuse
venv.backend = virtualenv
venv.in_project = True
venv.location = /Users/u/Library/Application Support/pdm/venvs
```

## Describe the solution you'd like

A vertical alignment of the `=` key/value separator
```
build_isolation                 = True
cache_dir                       = /Users/u/Library/Caches/pdm
check_update                    = True
global_project.fallback         = False
global_project.fallback_verbose = True
global_project.path             = /Users/u/Library/Preferences/pdm/global-project
global_project.user_site        = False
install.cache                   = False
install.cache_method            = symlink
install.parallel                = True
project_max_depth               = 5
pypi.json_api                   = False
pypi.url                        = https://pypi.org/simple
pypi.verify_ssl                 = True
python.use_pyenv                = True
python.use_venv                 = True
strategy.resolve_max_rounds     = 10000
strategy.save                   = minimum
strategy.update                 = reuse
venv.backend                    = virtualenv
venv.in_project                 = True
venv.location                   = /Users/u/Library/Application Support/pdm/venvs
```

**Comment by frostming** [comment]
> Currently `pdm config` output is unpleasant to read since keys are not separated from value properly

It seems not the case, they are in different colors
![image](https://user-images.githubusercontent.com/16336606/196575902-7cc435ce-f802-4967-9382-55400eb550e5.png)

The downside of aligning vertically is it make it harder to find the key at the same line, if the first column is too wide.

**Comment by eugenesvk** [comment]
> It seems not the case, they are in different colors

The colors actually make it worse since on my solarized theme they look too bleak (the lighter variant is especially trying to become invisible, and the colors are hard-coded :(), so black would've been much better.
<img width="229" alt="pdm" src="https://user-images.githubusercontent.com/12956286/196607093-520812d6-ac57-4180-adf2-023dfb795eb5.png">
But that's besides the point, the issue with all these walls of text is zigzagging, not lack of colors. It's the beauty of proper columns used for table formatting such as this that makes the text look better and easier to visually parse

> The downside of aligning vertically is it makes it harder to find the key at the same line, if the first column is too wide.

Is that a theoretical concern or is the current output too wide (how many chars is that)? But anyway that's a can be trivially fixed with a couple of options:



1. you can limit padding to whatever your threshold of visibility is

```
strategy.resolve_max_rounds = 10000
strategy.save        = minimum
strategy.update      = reuse
venv.backend         = virtualenv
venv.in_project      = True
```

2. you can add visual guides

like this
```
strategy.resolve_max_rounds .     . = 10000
strategy.save   .     .     .     . = minimum
strategy.update .     .     .     . = reuse
venv.backend    .     .     .     . = virtualenv
venv.in_project .     .     .     . = True
```
or like this
```
strategy.resolve_max_rounds............. = 10000
strategy.save........................... = minimum
strategy.update......................... = reuse
venv.backend............................ = virtualenv
venv.in_project......................... = True
```

**Comment by frostming** [comment]
> The colors actually make it worse since on my solarized theme they look too bleak (the lighter variant is especially trying to become invisible, and the colors are hard-coded :(), so black would've been much better.

yes, it is the same on the black theme, since those dimmed lines are config items overridden by higher levels, their values don't take effect.

I want to keep the current output because I investigated several products and they are doing the same:

- `git config -l`
- `pip config list`
- `poetry config --list`

Neither of them are doing a vertical alignment.

**Comment by pawamoy** [comment]
I find vertical alignment harder to read, it makes me do a lot more horizontal eye movement to read the values :confused:

**Comment by eugenesvk** [comment]
> yes, it is the same on the black theme, since those dimmed lines are config items overridden by higher levels, their values don't take effect.

- some explanation of that in the output would be nice
- but you still expect the user to read them to understand which keys are overridden, right, so it's then a poor choice of colors to make them less readable

> None of them is doing a vertical alignment

also many of them don't use colors, so? In general, good design practices are hard to find in cli tools, they mostly just do a data dump (`git config -l` is especially bad as it doesn't even add spaces before/after `=` in its wall of text!), so why conform to bad practices?

**Comment by eugenesvk** [comment]
> I find vertical alignment harder to read, it makes me do a lot more horizontal eye movement to read the values 😕

what about this example (remember that the max width is a configurable value)? Outside of rather long lines it's actually the opposite since due to proper alignment you can easier see the diffs in values (e.g. that `True` is the same for the next 5 lines, but then changes to `False` or `Some other long text value`) with your peripheral vision so you 
```
build_isolation   = True
cache_dir         = /Users/u/Library/Caches/pdm
check_update      = True
install.cache     = False
install.parallel  = True
project_max_depth = 5
pypi.json_api     = False
pypi.url          = https://pypi.org/simple
pypi.verify_ssl   = True
python.use_pyenv  = True
python.use_venv   = True
strategy.save     = minimum
strategy.update   = reuse
venv.backend      = virtualenv
venv.in_project   = True
venv.location     = /Users/u/Library/Application Support/pdm/venvs
```

**Comment by pawamoy** [comment]
I agree that it's pleasant to see. The thing, and it's my opinion only, when reading PDM's config, I'm scanning for the *keys* (which are already left-aligned), not *values*. Once I found the key(s) I'm interested in, I find it easier to read it's value of it's right next to it!
That's probably very subjective anyway.

I'd say PDM should definitely make the output more accessible if possible, though myself not being visually impaired I find it hard to know if vertical alignment would be an improvement or not 🤔

**Comment by eugenesvk** [comment]
> The colors are not really hardcoded: they actually are an ANSI sequence with a particular number, and this number is associated to a particular color by the terminal/theme

That's a distinction without a difference — the fact is I can't change the colors only for this app without changing the hardcoded ANSI sequence within the app, otherwise I'd be happy to change cyan to black in my theme

> The solarized background and the dimmed colors do not seem to play well together

It's not just the dimmed colors, the default also isn't great. And not just on a solarized bg: pure white background doesn't really help
It's more of an issue with `cyan` being used for something bigger than a symbol or two

> it's impossible to support themes of each and every user

Just testing with the 2 most common backgrounds (black and white) would be fine, no need for ∞
Also, using default foreground colors would avoid this mistake since they're properly set everywhere by the user choosing the theme
And allowing user config is always a good escape from having to design everything yourself!
Impossible Is Nothing™

**Comment by frostming** [comment]
Let's consider allowing color customization(#1450 ) if that would help, instead of vertical alignment. Thanks.

**Comment by eugenesvk** [comment]
That's not a replacement, though: poor colors make the text less visible, alignment makes the data structured
