### ISSUE TITLE
[macOS] user configs should not be stored in ~/Library/Preferences

### ISSUE THREAD

**Issue by eugenesvk** [pdm-project/pdm#1451]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

Install PDM on a Mac

## Actual behavior

Settings are stored in `~/Library/Preferences/pdm`

## Expected behavior

If the `$XDG_CONFIG_HOME` environment variable is set, store the settings in `$XDG_CONFIG_HOME/pdm/`
Otherwise fall back to the default macOS dir, which is `~/Library/Application Support/pdm`

[Apple docs](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html) that your doc link to say this about the current default `~/Libray/Preferences/`:

> You should not create files in this directory yourself

While the `~/Library/Application Support/` path has this description:

> Put app-created support files in the Library/Application support/ directory. In general, this directory includes files that the app uses to run but that should remain hidden from the user. This directory can also include data files, configuration files, templates and modified versions of resources loaded from the app bundle.

Though the best cli tools :) allow users to follow the cross-platform convention and put configs in `~/.config` for better portability and backup, while leaving `~/Library/Application Support/` to GUI apps, hence the above proposal to respect `XDG_CONFIG_HOME`

## Environment Information

not relevant

**Comment by frostming** [comment]
Because it would break the user setup, I have to ask what are the downsides of storing them in `Preferences`, except for violating the standards.

**Comment by eugenesvk** [comment]
I've mentioned a couple in the issue (portability and backup), + discoverability suffers (you wouldn't expect to look in this folder)
Otherwise not encountered many apps, so not sure what other downsides there are

**Comment by frostming** [comment]
`~/.config` isn't an option, we just switched from it to the current location(#1161).

**Comment by eugenesvk** [comment]
Ok, so you replaced one slightly incorrect decision of `~/.pdm` (not standard, but more convenient for backup/portability) with a strongly incorrect one of `/Preferences` (not standard, no portability/backup), why does it prevent an **option** to respect `XDG_CONFIG_HOME` (so`~/.config` is **not** the default like it was before)?

**Comment by frostming** [comment]
IIUC there is no big improvement from `~/Libray/Preferences/` to `~/Libray/Application Support` right? (We are not going the `~/.config/` routine.

And the result is given by the cross-platform location library `platformdirs`. Maybe you should report it there? I will close this issue.

**Comment by eugenesvk** [comment]
> We are not going the `~/.config/` routine.

:( why not? (again, as an option, **not** the default)

> And the result is given by the cross-platform location library `platformdirs`. Maybe you should report it there? I will close this issue.

There is already an issue for that https://github.com/platformdirs/platformdirs/issues/98 (though they also have `platformdirs.user_data_dir` that gives `Application Support` on macOS)

**Comment by eugenesvk** [comment]
The upstream library fixed this mistake, hopefully you can do the same how

**Comment by baggiponte** [comment]
> We are not going the `~/.config/` routine.

I would also like to add myself to the queue of people curious to hear your experience about why this. Having it as optional (e.g. as poetry does), perhaps just with a `PDM_CONFIG_DIR` env var to be set, feels like the most familiar way for me to configure these settings on macOS. It would be useful to put pdm configs under VC, for example.

**Comment by tshu-w** [comment]
I also vote for storing the configuration file in ~/.config on macOS via `XDG_CONFIG_HOME` or `PDM_CONFIG_DIR`.
