### ISSUE TITLE
Plugin overridden command duplicates help text

### ISSUE THREAD

**Issue by gazpachoking** [pdm-project/pdm#1454]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

When overriding built in pdm commands with a plugin, the help text for the original builtin remains visible. Discovered in #1437 Functionally, everything works fine with the overridden build command except for the help text.

## Steps to reproduce
```
pdm plugin add pdm-buildlocked
pdm --help
```

## Actual behavior
The 'build' command is printed twice in the help text.

![image](https://user-images.githubusercontent.com/187133/196983996-af8e593a-179f-48c6-802b-26190feaebb4.png)

## Expected behavior
The build command added by the pdm-buildlocked plugin overrides the built in build command in the help text.

## Environment Information

```json
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.5",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.22621",
  "python_full_version": "3.10.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "win32"
}
```

**Comment by frostming** [comment]
This was fixed on the main branch

**Comment by gazpachoking** [comment]
Oh, excellent. Thanks!
