### ISSUE TITLE
SHA256 Checksum on website docs does not match `install-pdm.py`

### ISSUE THREAD

**Issue by jtfidje** [pdm-project/pdm#1456]
Website gives the following checksum to match against:
`f09accb8a530315be312cf9ce7af987ccb608aa90d3972968d73e7ef7d8c547b`

Running `install-pdm.py` through `sha256sum` I get the following checksum:
`ed83f61b7ad3c3fcace57fda31175ad861c4283aeea02ba13b6351a66c2cca60`

**Comment by frostming** [comment]
Switch to the [dev version](https://pdm.fming.dev/dev/) and the checksum is updated.
