### ISSUE TITLE
[BUG] pdm failed to switch venv

### ISSUE THREAD

**Issue by Weilet** [pdm-project/pdm#1457]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. pdm init
2. pdm venv create
3. pdm venv activate -v 3.10

## Actual behavior

Only echo the command but not actually execute it.

## Expected behavior
Switch to another venv

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.1.5
Python Interpreter:
  C:\Users\Weile\Documents\github\test-pdm\.venv\Scripts\python.exe (3.10)
Project Root:
  C:/Users/Weile/Documents/github/test-pdm
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.4",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19044",
  "python_full_version": "3.10.4",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "win32"
}
```

**Comment by pawamoy** [comment]
That's the expected behavior, see https://pdm.fming.dev/latest/usage/venv/#activate-a-virtualenv.
The reason is: a subprocess cannot alter the environment of the current process.

**Comment by Weilet** [comment]
OK, I will close this issue.
