### ISSUE TITLE
Add a command for validating lockfile validity/freshness

### ISSUE THREAD

**Issue by tgolsson** [pdm-project/pdm#1459]
## Is your feature request related to a problem? Please describe.

I would like a cheap way of verifying that my lockfile is up to date, for example for CI usage.

## Describe the solution you'd like

While developing a plugin for version management of torch binaries I found this function:
https://github.com/pdm-project/pdm/blob/7877f73c47198518026b66ce7af173157d25c2eb/src/pdm/cli/actions.py#L155-L156

That seems like it would be very helpful if it was exposed either as a new command (`pdm validate-lockfile`?) or as `pdm lock --check`. 

I can contribute whichever variant you'd prefer - hence why I'm opening this to get a feeler for preferences.

**Comment by frostming** [comment]
I'd vote for `pdm lock --check`(in fact, there is `pdm install --check`), PR welcome
