### ISSUE TITLE
pdm check: check if the lockfile is up to date and related pre-commit hook

### ISSUE THREAD

**Issue by onerandomusername** [pdm-project/pdm#1471]
## Is your feature request related to a problem? Please describe.

I'd like to be able to guarentee that the lockfile is up to date when I update pyproject.toml. Because pdm stores a hash of specific keys found in pyproject.toml within pdm.lock, I want a command that simply exposes that information.

## Describe the solution you'd like
Simply put, `pdm check` which errors with a nonzero error code if the hash stored in pdm.lock doesn't match pyproject.toml or pdm.lock does not exist.

Furthermore, this could be exposed as a pre-commit hook which would check if the hash matches when pyproject.toml is edited.

**Comment by frostming** [comment]
This is already implemented by #1460, but are you interested in contributing the pre-commit hook?

**Comment by onerandomusername** [comment]
> This is already implemented by #1460, but are you interested in contributing the pre-commit hook?

added the hook in #1475
