### ISSUE TITLE
pdm run can freeze terminal

### ISSUE THREAD

**Issue by killjoy1221** [pdm-project/pdm#1474]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
1. Install fastapi and uvicorn
2. Create a file `app.py` with the following content
```py
from fastapi import FastAPI
app = FastAPI()
```
3. Start a dev server by running `pdm run uvicorn app:app --reload`
4. Wait a couple seconds, then stop the server by running Ctrl+C. 

## Actual behavior
Instead of exiting, it will hang on `Finished server process [PID]` and never return to the shell. To exit, you have to press ctrl+z (bash) to suspend the process then run `pkill pdm -9` to actually kill it.
```
➜ pdm run -v uvicorn app:app --reload
INFO:     Will watch for changes in these directories: ['/home/matthewm/pdm-script-zombies']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [287038] using StatReload
INFO:     Started server process [287040]
INFO:     Waiting for application startup.
INFO:     Application startup complete.

^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [287040]
^C^Z
[1]  + 287032 suspended  pdm run -v uvicorn app:app --reload
➜ ps
    PID TTY          TIME CMD
 283969 pts/4    00:00:00 zsh
 287032 pts/4    00:00:00 pdm
 287038 pts/4    00:00:00 uvicorn
 287039 pts/4    00:00:00 python
 287040 pts/4    00:00:00 python <defunct>
 287646 pts/4    00:00:00 ps
➜ pkill -9 pdm
[1]  + 287032 killed     pdm run -v uvicorn app:app --reload

```

## Expected behavior

pdm and uvicorn is expected to exit gracefully and not hang

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
➜ pdm info && pdm info --env
PDM version:
  2.1.5
Python Interpreter:
  /home/matthewm/pdm-script-zombies/.venv/bin/python (3.11)
Project Root:
  /home/matthewm/pdm-script-zombies
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.0",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.0.2-2-MANJARO",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Sat Oct 15 13:31:58 UTC 2022",
  "python_full_version": "3.11.0",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}
```

**Comment by pawamoy** [comment]
I've experienced this as well, though I couldn't say for sure if this is PDM's, uvicorn's, or something else's fault.

**Comment by killjoy1221** [comment]
I looked a bit more into it, and I've found that killing the pdm, uvicorn, or reloader process in a separate terminal instead of using Ctrl+C will actually stop the server. Killing the server process will cause it to lock up until the reloader, uvicorn, or pdm process is killed manually. I just think it's weird how Ctrl+C actually works when running uvicorn without pdm.

Related is encode/uvicorn#1579

**Comment by frostming** [comment]
@killjoy1221 can you test with the main branch? I removed a handler for SIGINT

**Comment by killjoy1221** [comment]
It seems to be working fine now with pdm 2.2.0

**Comment by DurandA** [comment]
I am still facing this issue on PDM version 2.12.3.

**Comment by Aeolun** [comment]
Or again? It seems like it's been a while since it happened last, but I have the issue too.

**Comment by sujh** [comment]
I met this problem with taskiq on MacOS. 
PDM version 2.24.1
