### ISSUE TITLE
Cross platform requirements.txt export (or closer to it)

### ISSUE THREAD

**Issue by gazpachoking** [pdm-project/pdm#1476]
## Is your feature request related to a problem? Please describe.
To help our users not using pdm, it would be nice to also provide a requirements.txt for easier installation of pinned dependencies that works on multiple platforms.

## Describe the solution you'd like
Environment markers are carried over from the lock file into requirements.txt created by the `export` command.

I see this was purposefully removed in https://github.com/pdm-project/pdm/commit/21ebacc60a27ff7175abf73d93e0d8d321c0a80c as a result of #843, but I was wondering the motivation behind that? Is it because we don't have the extra logic to combine environment markers if multiple dependencies declare the same transitive dependency with different environment markers? Not a showstopper if that logic complicated to implement, but wanted to bring up the question.

**Comment by frostming** [comment]
Environment marker merging was proved unsustainable and error-prone. I couldn't point to the exact issue right now but it was due to a package, each dependency of it and each dependency of its dependencies have a unique set of environment markers, with marker merging we ended up with a requirement string with more than 1000 characters long, and `packaging` refuses to parse them.

**Comment by gazpachoking** [comment]
Yeah, I suspected something like that might be the case. Thanks for the info!

**Comment by gazpachoking** [comment]
Hmm. I guess the locked requirements I'm outputting in the pdm-buildlocked plugin here will have the same flaw then? https://github.com/gazpachoking/pdm-buildlocked/blob/master/build_locked.py#L32-L47

**Comment by frostming** [comment]
> Hmm. I guess the locked requirements I'm outputting in the pdm-buildlocked plugin here will have the same flaw then? https://github.com/gazpachoking/pdm-buildlocked/blob/master/build_locked.py#L32-L47

Yes I think so, if your dependencies have environment markers.

**Comment by gazpachoking** [comment]
I took a peek at what poetry is doing, and... it seems pretty complicated. They seem to be combining and trying to simplify the combined marker constraints so that they don't keep growing. https://github.com/python-poetry/poetry-core/blob/3905d3e3baba4048ea3d4ed8d777f48bc87b8ca3/src/poetry/core/version/markers.py
