### ISSUE TITLE
Meta question: Use PDM to manage global applications?

### ISSUE THREAD

**Issue by hacker-DOM** [pdm-project/pdm#1500]
So I've been thinking, by any chance, would it be possible to somehow use Pdm/Pep 582 to manage global applications? I have everything from [visidata](https://github.com/saulpw/visidata) to [mackup](https://github.com/lra/mackup) currently installed _globally_ on Python - and I'm just waiting for something to break.

Basically it is simpler than the alternatives:

- have to source a virtualenv before every use (would also mean I can't use any other virtualenvs and apps, etc.)
- define an alias for each application/command that first sources it - again doesn't feel right

Why does Python require each package to be in `site-packages` just once, anyway? Why can't each package have it own `site-packages` (`__pypackages__`?) just like node/npm? I've been thinking about this for over a year, still don't have a good answer ❔

How do other people manage their top-level applications that they use frequently that just happen to be written in Python? What if `fd`, `sd`, `rg` were written in Python, then you would be sourcing and deactivating virtual environments after every use? :-)

Sorry for the rant, but I admire the author of this project, and if somebody can contribute some answers I am sure it will help others as well 🤘 🚀 👀

**Comment by pawamoy** [comment]
> Why does Python require each package to be in site-packages just once, anyway? Why can't each package have it own site-packages (__pypackages__?) just like node/npm? I've been thinking about this for over a year, still don't have a good answer ❔

That's just how it was designed, and that's why we "need" virtualenv or other hacks :confused:
Maybe that will change in the future though!

> How do other people manage their top-level applications that they use frequently that just happen to be written in Python? What if fd, sd, rg were written in Python, then you would be sourcing and deactivating virtual environments after every use? :-)

You seem to be exactly looking for [pipx](https://pypi.org/projects/pipx)!

**Comment by hacker-DOM** [comment]
I'll check it out, thanks!
