### ISSUE TITLE
Unsupported shell: sh, please specify another shell via `--pep582 <SHELL>`

### ISSUE THREAD

**Issue by cdleonard** [pdm-project/pdm#1502]
Running `eval "$(pdm582 --pep)"` fails containers which use non-bash shells by default, for example dash or busybox.

The generate shell code is very simple so "sh" should just be allowed.

**Comment by frostming** [comment]
SGTM, can you contribute the code for dash and busybox?

**Comment by cdleonard** [comment]
The code for bash works fine, there are no compat issues.
