### ISSUE TITLE
Remove the backend specific code from PDM

### ISSUE THREAD

**Issue by frostming** [pdm-project/pdm#1504]
## Describe the solution you'd like

As a further step to completely remove the lock-in with a particular build backend, there are following actions remaining

- Allow users to select from a list of supported backends(`setuptools`, `flit`, `hatchling`, `pdm-pep517`(default)) in `pdm init`
- Remove the support for exporting to `setup.py`, since the latest version of `setuptools` already supports PEP 621
- Support both `hatch` and `pdm` style variable substitution in the requirement strings.
- Read the dependencies from metadata to install the self package, because `editables` may be added dynamically.
- Remove `pdm-pep517` from the dependencies

**Comment by ofek** [comment]
> Support [...] `hatch` [...] variable substitution in the requirement strings

That'll be tough, I'd recommend not

**Comment by frostming** [comment]
@ofek we just need to support `{root:uri}` and `{env:*}` context formatting, because if we allow PDM to work with `hatchling`, we must produce metadata that can be recognized by the backend. But thanks, your reply makes me reread the [implementation of hatchling](https://github.com/pypa/hatch/blob/master/backend/src/hatchling/utils/context.py) and I think I can cover the basic usage.

BTW are you performing a full-text search for the related topics? :P

**Comment by ofek** [comment]
Ha yes every few days
