### ISSUE TITLE
Confusing message on first run with python.use_venv=false

### ISSUE THREAD

**Issue by blueyed** [pdm-project/pdm#1508]
Without `python.path` set in the config, but `python.use_venv = false` it will display "__pypackages__ is detected, using the PEP 582 mode" via https://github.com/pdm-project/pdm/blob/8d51c7ba3a6b6fa4b4df83695064ae96a902c989/src/pdm/project/core.py#L212-L216.

This confused me to look for an existing `__pypackages__` dir.

This happens within a Docker container, where Python is installed into `/venv`, but apparently not detected as a virtualenv.

The workaround is to configure it explicitly in the Dockerfile also: `RUN printf '[python]\nuse_venv = false\npath = "/venv/bin/python"' > /app/.pdm.toml`.

**Comment by pawamoy** [comment]
Witnessed this confusing message as well: no `__pypackages__` folder but `python.use_venv: false` and message saying `__pypackages__ detected`.
