### ISSUE TITLE
Question: permission bits of directories under __pypackages__

### ISSUE THREAD

**Issue by idnsunset** [pdm-project/pdm#1514]
I have a question about why all the directories under `__pypackages__` have permission bits of `777` but not a common `755`? Is it an intended design on purpose or just a case that only happens to me?

**Comment by frostming** [comment]
Are you working on Windows paths under WSL?

**Comment by idnsunset** [comment]
No, I am working on Ubuntu 20.04.

**Comment by frostming** [comment]
We are not setting permission bit explicitly https://github.com/pdm-project/pdm/blob/7894d18e8045d37579cc39348dd15c72e444c453/src/pdm/models/environment.py#L108

**Comment by idnsunset** [comment]
@frostming ,thank you for the quick reply! I did another test just now and no permission issue found. So it must have been something wrong by accident outside pdm itself.
