### ISSUE TITLE
Semantic versioning with urls

### ISSUE THREAD

**Issue by cesarob** [pdm-project/pdm#1515]
## Is your feature request related to a problem? Please describe.

We were wondering if we could use semantic versioning with url. I found this https://stackoverflow.com/questions/73984925/specify-dependency-version-for-git-repository-in-pyproject-toml.

The author got the answer that is not possible because it is not supported in [pep-0508](https://peps.python.org/pep-0508/)

## Describe the solution you'd like

wouldn't be pretty nice to be able to have semantic versioning with an url? It will avoid the usage of a private artifacts repository.

**Comment by frostming** [comment]
We are not going to invent something that isn't specified in the PEP standards. If you want to extend the standard, it may be a better choice to ask at https://discuss.python.org/c/packaging/ and draft a new PEP for that. Then PDM will follow the standard after it is accepted. Yeah, that is a long period though.

**Comment by cesarob** [comment]
Thanks for pointing to the proper location for discussion.
