### ISSUE TITLE
Feature request: make pdm aware of the environment

### ISSUE THREAD

**Issue by coccoinomane** [pdm-project/pdm#1520]
Hello!

There is a package called [`eth-brownie`](https://pypi.org/project/eth-brownie/) which determines its dependencies in `setup.py` by reading  an enviroment variable. From their README:

>If you want to install brownie inside your own project (rather than as a standalone cli tool):
>
>```bash
>export BROWNIE_LIB=1
>pip install eth-brownie
>```
>
>This loosens the pins on all dependencies. You'll want to make sure you have your own `requirements.txt` to make sure upgrades upstream don't surprise anyone.

The mechanism is implemented with a simple `if` block in `setup.py` ([link to relevant code here](https://github.com/eth-brownie/brownie/blob/master/setup.py#L10-L14)).

It seems `pdm` does not currently support this mechanism, because exporting the env variable has no effect on the installation process. For example, if I run the following:

```
export BROWNIE_LIB=1
pdm add eth-brownie
```

then `pdm` tries to install `eth-brownie` ignoring the env variable.

## Describe the solution you'd like

It would be great if `pdm` could read the environment variable while installing the package, so that packages can use them in their `setup.py`, just like brownie does.

Cheers,
Cocco

**Comment by frostming** [comment]
> If you want to install brownie inside your own project (rather than as a standalone cli tool):
> 
> ```shell
> export BROWNIE_LIB=1
> pip install eth-brownie
> ```
> 
> This loosens the pins on all dependencies. You'll want to make sure you have your own `requirements.txt` to make sure upgrades upstream don't surprise anyone.

I don't understand how it could work  and be documented like that. If the installer picks the built wheel(and it does have one on PyPI) for installation no `setup.py` will be executed and the dependencies are frozen. Unless you tell the installer to pick sdist explicitly. You can achieve this by `export PDM_NO_BINARY=eth-brownie`

**Comment by frostming** [comment]
When I restrict the version to `eth-browner==1.19.2` I got the following error:

```
pdm.termui: Candidate rejected: ipfshttpclient@0.8.0a2 because it introduces a new requirement python>=3.6.2,!=3.7.0,!=3.7.1 that conflicts with other requirements:
    python>=3.7,<4.0 (from project)
pdm.termui: Conflicts detected:
  python>=3.7,<4.0 (from project)
  python>=3.6.2,!=3.7.0,!=3.7.1 (from ipfshttpclient@0.8.0a2)
  python>=3.7,<4.0 (from project)
  python>=3.6.2,!=3.7.0,!=3.7.1 (from ipfshttpclient@0.8.0a2)
```

So it turns out `Python 3.7.0` and `3.7.1` is not eligible for this project. I changed to the `requires-python` to `>=3.7.2,<3.11` and  the locking succeeded.

**Comment by coccoinomane** [comment]
It works, thanks @frostming 😍

I would have never spotted this by myself, because I was trusting Brownie's [`setup.py`](https://github.com/eth-brownie/brownie/blob/master/setup.py) to be accurate... but it turns out it wasn't 🤦🏻‍♂️

For your information, this is the project where I'm using `pdm` > https://github.com/coccoinomane/web3cli
It is still in alpha state, but by all means feel free to have a look :-)
