### ISSUE TITLE
pdm publish .whl error on linux, unsupported platform tag 'linux_x86_64'

### ISSUE THREAD

**Issue by zombie110year** [pdm-project/pdm#1526]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**[PEP600](https://peps.python.org/pep-0600/) has instead [PEP425](https://peps.python.org/pep-0425/) on linux, so pdm should generate wheel name like `<project.name>-<version>-<py tag>-<abi tag>-manlylinux_<glibc major>_<glibc minor>_<arch>.whl`**

## Steps to reproduce

Build a binary wheel on linux and publish.

## Actual behavior

Meet a pypi 400 error:

```
[PublishError]: 400 Client Error: Binary wheel '****-linux_x86_64.whl' has an
unsupported platform tag 'linux_x86_64'. for url: https://upload.pypi.org/legacy/
```

## Expected behavior

After I manually rename whl as `****-manylinux_2_36_x86_64.whl`, publish successfully.

## Environment Information

```bash
PDM version:
  2.2.1
Python Interpreter:
  /home/zom/source/caj2pdf-restructured/.venv/bin/python (3.10)
Project Root:
  /home/zom/source/caj2pdf-restructured
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.8",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.10.16.3-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Fri Apr 2 22:23:49 UTC 2021",
  "python_full_version": "3.10.8",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
You can override the default platname by `pdm build -C--plat-name=manylinux_2_36_x86_64` and then publish the artifacts with `pdm publish --no-build`. However, it is more recommended to use `cibuildwheel` to make sure the wheel is abi compatible.

**Comment by zombie110year** [comment]
thanks for your help

**Comment by cavedon** [comment]
@frostming, would you consider defaulting to `next(packaging.tags.platform_tags())` for platform name in the tag for linux? That will give the most specific platform tag for the running interpreter. Of course it does not guarantee ABI compatibility, but that can be checked by the user with `auditwheel`.

**Comment by frostming** [comment]
No, it is also the default behavior of other build backends. You need to set them explicitly via `-C` option if you know what it means. Making it default would make people that are not familiar with packaging think it is ABI compatible.
