### ISSUE TITLE
`pdm run` is pretty slow

### ISSUE THREAD

**Issue by silverwind** [pdm-project/pdm#1527]
Comparing the startup performance of `pdm run` with `poetry run` in a fresh virtualenv for each, I find pdm to be consistently slower and both being miles away from bare `python`:

```bash
$ time pdm run python3 -V
Python 3.11.0
pdm run python3 -V  0.88s user 0.13s system 98% cpu 1.028 total

$ time poetry run python3 -V
Python 3.11.0
poetry run python3 -V  0.58s user 0.09s system 89% cpu 0.752 total

$ time python3 -V
Python 3.11.0
python3 -V  0.01s user 0.01s system 74% cpu 0.021 total
```

Can anything be done or is this slowness inherent to how pdm works?

**Comment by frostming** [comment]
That may depend, on my machine there is no big diff:
```
❯ time poetry run python3 -V
The currently activated Python version 3.8.10 is not supported by the project (^3.10).
Trying to find and use a compatible version.
Using python3 (3.10.5)
Python 3.8.10

real    0m0.526s
user    0m0.495s
sys     0m0.034s
```
```
❯ time pdm run python3 -V
Python 3.10.5

real    0m0.390s
user    0m0.329s
sys     0m0.069s
```

Both spawn a subprocess so they will be certainly slower than bare `python`

**Comment by silverwind** [comment]
I guess PEP 582 mode should then drastically reduce startup time when no suprocess is involved, I will test that as well.

**Comment by pawamoy** [comment]
Can confirm: with PEP582, you can run `python -m some_module`, which spares you the PDM machinery.

**Comment by abersheeran** [comment]
You can use `pdm shell` and then exec command without `pdm run`. 😆

**Comment by pawamoy** [comment]
@abersheeran is this a PDM plugin?

```console
% pdm shell
Usage: pdm [-h] [-V] [-c CONFIG] [-v] [-I] [--pep582 [SHELL]]
           {add,build,cache,completion,config,export,import,info,init,install,list,lock,publish,remove,run,search,self,plugin,show,sync,update,use,venv}
           ...
pdm: error: Command unknown: shell
```

**Comment by abersheeran** [comment]
> @abersheeran is this a PDM plugin?
> 
> ```
> % pdm shell
> Usage: pdm [-h] [-V] [-c CONFIG] [-v] [-I] [--pep582 [SHELL]]
>            {add,build,cache,completion,config,export,import,info,init,install,list,lock,publish,remove,run,search,self,plugin,show,sync,update,use,venv}
>            ...
> pdm: error: Command unknown: shell
> ```

Yes. https://pypi.org/project/pdm-shell/

**Comment by silverwind** [comment]
I think this is still a valid issue and PDM could improve startup time drastically by lazy-importing everything, so that `pdm run` loads only the minimal python code necessary to achieve execution inside the virtualenv.
