### ISSUE TITLE
Better docs & error messaging for vcs requirements

### ISSUE THREAD

**Issue by bszonye** [pdm-project/pdm#1569]
## Is your feature request related to a problem? Please describe.

I'm converting a project to pdm and ran into multiple problems converting my vcs-based requirements. I'm currently using mypy from VCS because of some unreleased features. The correct PEP 508 requirement string for that looks like this:
```
    "mypy @ git+https://github.com/python/mypy.git"
```
but my previous system didn't need the `mypy @` bit. Without that, pdm produces an indecipherable error message (similar to #1559). I wasn't sure whether this was even a supported feature, so I tried various workarounds, including pinning `packaging`, before discovering #1559 which pointed me to the correct syntax. I then made _another_ typo (forgetting the `@`) which produced the same kind of error message.

## Describe the solution you'd like

Please:
- [ ] include an example of a correct PEP 508 vcs requirement in the docs (for manual entry as well as CLI)
- [ ] produce error messages for this case that indicate the cause of the problem and how to fix it
- [ ] make pdm add, lock, and install behave consistently for this case

[edited to correct typo and to note that the three relevant commands are behaving differently here, which I find surprising]

**Comment by frostming** [comment]
> * include an example of a correct PEP 509 vcs requirement in the docs

Shouldn't [this](https://pdm.fming.dev/dev/usage/dependency/#vcs-dependencies) be sufficient? VCS requirements added from the *CLI* doesn't need name part, as it will be added by PDM when written to `pyproject.toml`.

And if you are writing it by hand, it should be covered by [PEP 621 Metadata section](https://pdm.fming.dev/dev/pyproject/pep621/), it refers to PEP 508(rather than PEP 509, but it should be typo).

**Comment by bszonye** [comment]
Hm. That's helpful if I'm using the CLI, but I already had the requirement in my pyproject.toml, as I'm converting from Poetry to PDM. That section should probably mention that you need the `name @` if you write it by hand. My experience with with pip, pip-tools, and poetry has been that they'll all infer the requirement name from the repo name, much like `pdm add` does.

It seems that there's already support for inferring the requirement name from the repo name in the `pdm add` CLI, and `pdm lock` accepted it too, so it would be nice if the `pdm install` CLI could also handle it gracefully. At the very least it would be helpful for the error message to indicate it's an invalid requirement syntax, and it'd be better if add+lock+install all handled the syntax consistently.

**Comment by frostming** [comment]
@bszonye please try the main branch, the name attribute will be populated correctly.

**Comment by bszonye** [comment]
Oh, this is already sorted out on main? Excellent, I'll switch from pypi install to vcs & report back if I have any further trouble. Thank you for your help!

**Comment by bszonye** [comment]
I'm still seeing the same error message on head:
```
$ pdm --version
PDM, version 2.3.3.dev5+g19f6c44

$ pdm lock
🔒 Lock successful
Changes are written to pdm.lock.

$ pdm install
See /tmp/pdm-install-resolve-2zfoq5g4.log for detailed debug log.
[ResolutionImpossible]:
[RequirementInformation(requirement=VcsRequirement(name=None, marker=None,
extras=None, specifier=None, editable=False, prerelease=False,
url='git+https://github.com/python/mypy.git', path=None, subdirectory=None,
vcs='git', ref=None, revision=None), parent=None)]
Add '-v' to see the detailed traceback
```
The lock succeeds but the install fails. I see that the `name=None` is the source of the error, now that I know what to look for.

This is with mypy in the dev dependencies like this:
```
[tool.pdm.dev-dependencies]
lint = [
    "git+https://github.com/python/mypy.git",
    ....
]
```
Of course this works correctly if I explicitly write the requirement in full as `mypy @ git+...` but figuring that out was difficult, and it's surprising that only the install command rejects the shorthand version.

**Comment by bszonye** [comment]
(For what it's worth, `pdm lock` produces nearly identical output regardless of whether I specify the requirement name. The only difference is `metadata.content_hash` which I presume is a checksum of the input requirements.)

**Comment by bszonye** [comment]
Thanks, by the way, for the quick response and the troubleshooting tips. I appreciate the help, I'm unblocked, and so far I'm having a good overall experience with pdm.
