### ISSUE TITLE
Pyproject.toml gives validation error because of missing project.name

### ISSUE THREAD

**Issue by johnbendi** [pdm-project/pdm#1573]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Leave project.name property empty and pyproject schema validation gives an error

## Actual behavior

Fails validation
## Expected behavior

Shouldn't fail validation

## Environment Information
VSCode on Ubuntu Linux using Even Better Toml extension

```bash
# Paste the output of `pdm info && pdm info --env` below:
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.8",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.0-56-generic",
  "platform_system": "Linux",
  "platform_version": "#62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022",
  "python_full_version": "3.10.8",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
What tool runs the validation?

**Comment by johnbendi** [comment]
It's a VSCode extension called [Even Better Toml](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml)

**Comment by johnbendi** [comment]
And I can't seem to figure out how to disable the check for that property

**Comment by frostming** [comment]
It is not our fault. obviously.

**Comment by johnbendi** [comment]
Sure. Thanks
