### ISSUE TITLE
Dummy dependency problem during install of ansible-lint

### ISSUE THREAD

**Issue by la-magra** [pdm-project/pdm#1575]
- [x] I have searched the issue tracker and this is definitely not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Context

This is a follow up to the following issues:

https://github.com/ansible/ansible-lint/pull/2712 the thing that started it all

But most recent release v6.10.0 https://github.com/ansible/ansible-lint/pull/2807 drops `setup.cfg` (finally...), but the problem remains.

https://github.com/ansible/ansible-lint/issues/2816 the "pip works, we don't care about anything else".

https://github.com/python-poetry/poetry/issues/7112#issuecomment-1329385572 the poetry workaround

In short, ansible-lint decided to use a dummy/fake package (`will-not-work-on-windows-try-from-wsl-instead; platform_system == "Windows"`) to stop installation on that unsupported platform.

edit. Feels related to https://github.com/pdm-project/pdm/issues/1535

## Steps to reproduce

```shell
$ pdm --version
PDM, version 2.3.3

$ pdm init
...

$ pdm add -d 'ansible-lint'
Adding packages to dev dev-dependencies: ansible-lint
See /tmp/pdm-lock-7z2owtju.log for detailed debug log.
[CandidateNotFound]: Unable to find candidates for will-not-work-on-windows-try-from-wsl-instead. There may exist some issues with the package name or network condition.
Add '-v' to see the detailed traceback
```

Also trying the poetry workaround by adding the `platform_system`
```toml
#pyproject.toml
...
[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "ansible-lint<7.0.0,>=6.0.0; platform_system != \"Windows\"",
]
...
```
then running `pdm install` yields the same results.

## Actual behavior

Package ansible-lint does not install.

## Expected behavior

It unfortunately should, even with their horrendous dependency...

## Environment Information

```shell
$ pdm info && pdm info --env
PDM version:
  2.3.3
Python Interpreter:
  /home/****/ansible-lint-test/.venv/bin/python (3.11)
Project Root:
  /home/****/ansible-lint-test
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.1",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.0.12-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Thu, 08 Dec 2022 11:03:38 +0000",
  "python_full_version": "3.11.1",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}
```

**Comment by la-magra** [comment]
Wonderful, thank you.

**Comment by mledoze** [comment]
Thanks for the fix.

Unfortunately this does not work with Python 3.9 although [`ansible-lint` requires Python >=3.8](https://github.com/ansible/ansible-lint/blob/dc42168472d0c32a23df8eef0f3c17583e3ce5ee/pyproject.toml#L11). It's because the dummy dependency `will-not-work-on-windows-try-from-wsl-instead` [requires Python >=3.11](https://github.com/orf/pypi-data/blob/22a38a4a703db01212c9e596e8c79d53fb1c45bb/release_data/w/i/will-not-work-on-windows-try-from-wsl-instead.json#LL32C8-L32C8). It does not make sense to me because this package has no code.

**Comment by la-magra** [comment]
Confirmed...

```shell
$ pdm update
�� Lock failed
Unable to find a resolution because the following dependencies don't work on all Python versions defined by the project's `requires-python`: >=3.9.
  python>=3.11,<4.0 (from <Candidate will-not-work-on-windows-try-from-wsl-instead@0.1.0 from https://pypi.org/simple/will-not-work-on-windows-try-from-wsl-instead/>)
To fix this, you can change the value of `requires-python` in pyproject.toml.
```

And for some damned reason https://pypi.org/project/will-not-work-on-windows-try-from-wsl-instead/ is a yanked release AND defined a `requires: Python >=3.11, <4.0`
