### ISSUE TITLE
PDM Website is invalid SSL Certificate

### ISSUE THREAD

**Issue by itonedev1990** [pdm-project/pdm#1576]
This website https://pdm.fming.dev is invalid ssl certificate.

**Comment by pawamoy** [comment]
:scream:

**Comment by aldrickdev** [comment]
I am getting the same issue

**Comment by frostming** [comment]
GitHub Pages is facing an issue provisioning SSL certificates for custom domains, now it has been redirected to `github.io` temporarily.
