### ISSUE TITLE
Impossible to chain script commands

### ISSUE THREAD

**Issue by ivarnakken** [pdm-project/pdm#1577]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

With this configuration:
```toml
[tool.pdm.scripts]
lint = "black <path> && isort <path>"
```

Run this:
```bash
$ pdm lint
```

The `black` and `isort` commands are arbitrarily chosen as an example, and the problem remains for all other types of commands.

## Actual behaviour

The result of running the script is an error raised by `black`, because `&&` is read as part of the first command (and not as a separator for the two commands).

## Expected behaviour

I'd expect both `black` and `isort` to run separately.

## Environment Information

```bash
PDM version:
  2.3.3
Python Interpreter:
  <path>/venv/bin/python (3.11)
Project Root:
  <path>
Project Packages:
  None
Inside an active virtualenv <path>/venv, reuse it.
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.0",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "22.1.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; 
root:xnu-8792.41.9~2/RELEASE_ARM64_T6000",
  "python_full_version": "3.11.0",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}
```

**Comment by ivarnakken** [comment]
Wrapping the command helped fix the issue!
```
lint = { shell = "black <path> && isort <path>" }
```
Would be nice if this was in the documentation though.

**Comment by pawamoy** [comment]
This is documented here: https://pdm.fming.dev/latest/usage/scripts/#shell.

**Comment by frostming** [comment]
`shell` can run arbitrary shell commands with operators and pipes, and `composite` script can compose multiple scripts and run one by one.
