### ISSUE TITLE
pack plugins into a zip app

### ISSUE THREAD

**Issue by franzhaas** [pdm-project/pdm#1586]
I tried to install the pdm-packer plugin into the PDM zip app.

I tried 2 methods (Before building the zip app).:

pdm add pdm-packer 
pdm run pdm self add pdm-packer

Both of them didn't immediately succeed, as this is a new feature I want to ask the question.:

Is this supposed to work?

Thanks in advance,
Franz

**Comment by frostming** [comment]
No it isn't going to work, the plugin loading relies on the entry point which is not available in zipapp.
