### ISSUE TITLE
pdm run don't exclude system site-packages if python has a different name 

### ISSUE THREAD

**Issue by vitidev** [pdm-project/pdm#1598]
- [x ] have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

I have installed `python 3.11` as `C:\Python\python.exe`. Also I made hardlink `C:\Python\python.exe -> C:\Python\p.exe`.

     > pdm init
     ...
     > pdm run -v python -c "import sys; print(sys.path)
    ['', 'z:\\test', 'C:\\Python\\python311.zip', 'C:\\Python\\Lib',
    'C:\\Python\\DLLs', 'z:\\test\\__pypackages__\\3.11\\lib']

    pdm run -v p -c "import sys; print(sys.path)"
    ['', 'z:\\test', 'C:\\Python\\python311.zip', 'C:\\Python\\Lib', 'C:\\Python\\DLLs', 
    'z:\\test\\__pypackages__\\3.11\\lib', 'C:\\Python', 'C:\\Python\\Lib\\site-packages']

## Actual behavior

When using a shortcut, there is no isolation form system packages

## Expected behavior

Expect the same result in both cases

## Environment Information

```bash
pdm info && pdm info --env
PDM version:
  2.3.4
Python Interpreter:
  C:\Python\python.EXE (3.11)
Project Root:
  z:/test
Project Packages:
  z:\test\__pypackages__\3.11
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.1",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19044",
  "python_full_version": "3.11.1",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "win32"
}
```
doc say:

     "The executable is from PATH but not inside the __pypackages__ folder."

But the executable file `p.exe` is located in the same place as `python.exe`

**Comment by vitidev** [comment]
@frostming 

PDM, version 2.4.0
the issue still present

    $ pdm info && pdm info --env
    PDM version:
      2.4.0
    Python Interpreter:
      C:\Python\python.EXE (3.11)
    Project Root:
      z:/test
    Project Packages:
      z:\test\__pypackages__\3.11
    {
      "implementation_name": "cpython",
      "implementation_version": "3.11.1",
      "os_name": "nt",
      "platform_machine": "AMD64",
      "platform_release": "10",
      "platform_system": "Windows",
      "platform_version": "10.0.19045",
      "python_full_version": "3.11.1",
      "platform_python_implementation": "CPython",
      "python_version": "3.11",
      "sys_platform": "win32"
    }

    $ pdm run -v python -c "import sys; print(sys.path)"
    ['', 'C:\\Python\\python311.zip', 'C:\\Python\\Lib', 'C:\\Python\\DLLs', 'z:\\test\\__pypackages__\\3.11\\lib']

    $ pdm run -v p -c "import sys; print(sys.path)"
    ['', 'C:\\Python\\python311.zip', 'C:\\Python\\Lib', 'C:\\Python\\DLLs', 'z:\\test\\__pypackages__\\3.11\\lib', 'C:\\Python', 'C:\\Python\\Lib\\site-packages']

**Comment by frostming** [comment]
Hard link doesn't work, it only works for symlinks

**Comment by vitidev** [comment]
@frostming 

I understand. PDM depends on the file name and does not use heuristic like

     Path(cmdfile).parent.joinpath('Lib/site-packages').is_dir()
     Path(commandfile).parent.joinpath('Lib/multiprocessing/pool.py').exists()
