### ISSUE TITLE
PDM exceeds MAX retries trying pull from local pypi-server repo 

### ISSUE THREAD

**Issue by sdiop** [pdm-project/pdm#1607]
- [ x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
1. Set the directives below in pyproject.toml

[[tool.pdm.source]]
url = "http://http://localhost:8080/simple"
verify_ssl = false
name = "local"

2. downloand a whl file (pyffmpeg-2.4.2.13-py3-none-macosx_11_0_arm64.whl) from PyPI and store in /Users/Shared/PythonPackages folder served by pypi-server
3. at the command line issue: pypi-server run -p 8080 /Users/Shared/PythonPackages
4. issue: pdm add pyffmpeg -v 

PDM still tries to connect to PyPI

➜ pdm add pyffmpeg -v                                                       
Adding packages to default dependencies: pyffmpeg
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   black>=22.12.0
pdm.termui:   requests>=2.28.1
pdm.termui:   fastapi>=0.89.0
pdm.termui:   pyffmpeg
pdm.termui:   pytest>=7.2.0
pdm.termui:   python>=3.11
pdm.termui:   Adding requirement black>=22.12.0
pdm.termui:   Adding requirement requests>=2.28.1
pdm.termui:   Adding requirement fastapi>=0.89.0
pdm.termui:   Adding requirement pyffmpeg
Traceback (most recent call last):
.......< deleted for brevity>
requests.exceptions.ConnectionError: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //localhost:8080/simple (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1101babc0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

PDM is expected to source from localhost:8080 instead of 

Pinging pypi-server yields the output below: 
time curl http://localhost:8080/simple/
    <html>
        <head>
            <title>Simple Index</title>
        </head>
        <body>
            <h1>Simple Index</h1>
                 <a href="dateutil/">dateutil</a><br>
                 <a href="numpy/">numpy</a><br>
                 <a href="pandas/">pandas</a><br>
                 <a href="pandasql/">pandasql</a><br>
                 <a href="pip/">pip</a><br>
                 <a href="pyffmpeg/">pyffmpeg</a><br>
                 <a href="python-dateutil/">python-dateutil</a><br>
                 <a href="pytz/">pytz</a><br>
                 <a href="rbenv/">rbenv</a><br>
                 <a href="ruby/">ruby</a><br>
                 <a href="setuptools/">setuptools</a><br>
                 <a href="six/">six</a><br>
                 <a href="sqlalchemy/">sqlalchemy</a><br>
                 <a href="wheel/">wheel</a><br>
        </body>
    </html>
    curl http://localhost:8080/simple/  0.00s user 0.00s system 0% cpu 0.903 total
so PDM errorring out after exceeding its MAX retries is quite baffling
I tried:
pip install pyffmpeg  --no-index --find-links /Users/Shared/PythonPackages
and it successfully installed the package as evidenced by:
➜ python  
Python 3.11.1 (main, Dec 29 2022, 19:01:22) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyffmpeg
>>> (no import errors)

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

```

PDM version:
  2.3.4
Python Interpreter:
  /Users/username/.pyenv/versions/3.11.1/bin/python3.11 (3.11)
Project Root:
  /Users/username/DV/pdmhow
Project Packages:
  /Users/username/DV/pdmhow/__pypackages__/3.11
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.1",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "22.2.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; 
root:xnu-8792.61.2~4/RELEASE_ARM64_T6000",
  "python_full_version": "3.11.1",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}

**Comment by frostming** [comment]
The `tool.pdm.source` is an addition, instead of a replacement. If you do want to omit the pypi source, assign the `name` to `pypi`.

**Comment by sdiop** [comment]
@frostming: I confirm that setting the `name` to `pypi` effectively replaces PyPI as a source to install packages from.
This was need as I work in settings where Internet connectivity is often unavailable so having frequently used packages locally is very useful.
Thank you very much for pointing me in the right direction. May I add a small paragraph in the docs to highlight that use case?

**Comment by frostming** [comment]
@sdiop There is a section in the docs: https://pdm.fming.dev/latest/pyproject/tool-pdm/#disable-the-pypi-repository
