### ISSUE TITLE
'pdm show' does not print more info with '--verbose' option

### ISSUE THREAD

**Issue by cmarqu** [pdm-project/pdm#1610]
## Is your feature request related to a problem? Please describe.

I am trying to debug why `pdm show --version` falls back to version "0.0.0" for me when I have `source = "scm"` set (`pdm build` also produces packages with this version).
Using `pdm show --version -vv` does not change the output, however.

## Describe the solution you'd like

It would be helpful if the `-v` (or `-vv`) option would print a log of the things it tries to find out the current version. (In my case, I have a full git checkout, so I'm stumped without more debug output.)

**Comment by frostming** [comment]
There is no log info to be displayed, the version is resolved by the backend and PDM calls the backend in a subprocess.

**Comment by cmarqu** [comment]
I see. Any suggestions on how to debug this though?
I have already tried the trace module and setting PYTHONWARNINGS to no avail.

**Comment by frostming** [comment]
check if your pyproject.toml is valid, especially build-system table setting
