### ISSUE TITLE
Locking any project with a dependency on Scipy and/or Matplotlib takes a long time

### ISSUE THREAD

**Issue by boschmic** [pdm-project/pdm#1613]
Locking any projects involving the matplotlib and/or scipy dependencies take a long time (several minutes for larger projects) and while locking, PDM is downloading a large amount of data.

- [x] I have searched the issue tracker and believe that this is not a duplicate.

Some other issues might be related: https://github.com/pdm-project/pdm/issues/1583 also had matplotlib and scipy in the list of dependencies.

## Steps to reproduce

1. `pdm clear cache`
2. `pdm lock` the following `pyproject.toml`:

```
[project]
dependencies = [
    "matplotlib>=3.6.3",
    "scipy>=1.9.3",
]
requires-python = ">=3.9"
```

## Actual behavior

The locking process stalls at "Resolving: new pin six 1.16.0" for around ~45 seconds. During that time PDM is downloading data at a rate of 40MB/sec, totaling at 1.9 GB.

## Expected behavior

I compared with Poetry. Poetry locks the same dependencies in 10 seconds and downloads less than only ~70MB of data. (I did clear the Poetry cache beforehand)

## Environment Information

```
PDM version:
  2.3.4
Python Interpreter:
  PROJECT_ROOT/.venv/bin/python (3.10)
Project Root:
  PROJECT_ROOT
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.6",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.0-56-generic",
  "platform_system": "Linux",
  "platform_version": "#62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022",
  "python_full_version": "3.10.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}
```

```

**Comment by frostming** [comment]
This is already fixed on the main branch and will be released shortly
