### ISSUE TITLE
[HELP] How to change `pdm init` default values?

### ISSUE THREAD

**Issue by spenpal** [pdm-project/pdm#1625]
I recently changed my Github username and also installed pdm too. However, the `pdm init` defaults is using my old Github username and my old email address (*not shown*), too. I have not been able to figure out where I can change these defaults in the PDM documentation. Any help would be appreciated!

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/tHMHX.png

**Comment by frostming** [comment]
PDM reads the info from `git config` command, so make sure you have updated the config with `git config`.

**Comment by spenpal** [comment]
> PDM reads the info from `git config` command, so make sure you have updated the config with `git config`.

Ahhh, this worked like a charm! Thanks so much! It's been bothering me for a really long time.
