### ISSUE TITLE
How to setup a proxy with PDM ?

### ISSUE THREAD

**Issue by cvgaviao** [pdm-project/pdm#1641]
I'm under a proxied network on my current company.
I have the following config on pip.ini that allowed me to install pdm using pip: 
```
[global]
trusted-host = pypi.org files.pythonhosted.org pypi.python.org
proxy = http://user:pwd@proxy.ourserver.com:8080
```
As soon as it was installed, I tried to do a `pdm self update` and I got this error:
```
C:\Users\cristiano>pdm self update
[SSLError]: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pdm/ (Caused by
SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local
issuer certificate (_ssl.c:992)')))
Add '-v' to see the detailed traceback
```
How can I setup a proxy to use PDM ?

**Comment by frostming** [comment]
env var `http_proxy` and `https_proxy` would just work.

**Comment by cvgaviao** [comment]
@frostming , thanks for the answer. But I think that this works only on Linux or Mac.

**Comment by frostming** [comment]
> @frostming , thanks for the answer. But I think that this works only on Linux or Mac. We don't have that possibility on Windows.

It works on windows, too.

**Comment by HuM4NoiD** [comment]
I tried with both upper case `HTTP_PROXY` and lower case `http_proxy` but both don't seem to work on windows. 
Also, If I may ask is `no_proxy` supported along with `http_proxy`?

**Comment by frostming** [comment]
> I tried with both upper case `HTTP_PROXY` and lower case `http_proxy` but both don't seem to work on windows. Also, If I may ask is `no_proxy` supported along with `http_proxy`?

Requests does read proxy settings from env var, which is used under the hood. Just note that it's `https_proxy` for https entry points. `no_proxy` is also supported.

**Comment by HuM4NoiD** [comment]
In the case where https proxies are not available, `http_proxy` should be used right? If i set `pdm config pypi.verify_ssl false` then it should resort to `http_proxy`.

I am in a scenario where there is no https proxy available but http proxy is.

My environment for linux:
```
❯ env | grep http
http_proxy=http://proxy-host:port
https_proxy=http://proxy-host:port
HTTP_PROXY=http://proxy-host:port
HTTPS_PROXY=http://proxy-host:port
```

My Environment for windows:
```
$ env | grep http
https_proxy=http://proxy-host:port
http_proxy=http://proxy-host:port
```

With this environment, a curl call like this succeeds for both windows and linux:
```
❯ curl https://pypi.org/simple/pdm/
```

My pdm config for linux:
```
❯ pdm config | grep pypi
pypi.ignore_stored_index = False
pypi.json_api = False
pypi.url = https://pypi.org/simple
pypi.verify_ssl = True
pypi.url = https://pypi.org/simple/
pypi.verify_ssl = False
```

My pdm config for windows:
```
$ pdm config | grep "pypi"
pypi.ignore_stored_index = False
pypi.json_api = False
pypi.url = https://pypi.org/simple
pypi.verify_ssl = True
pypi.verify_ssl = False
```

adding a package in linux is successful:
```
❯ pdm add pydantic
Adding packages to default dependencies: pydantic
🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 2 to add, 0 to update, 0 to remove

  ✔ Install typing-extensions 4.5.0 successful
  ✔ Install pydantic 1.10.5 successful

🎉 All complete!


PDM 2.4.5 is installed, while 2.4.6 is available.
Please run `pdm self update` to upgrade.
Run `pdm config check_update false` to disable the check.
```

But not in windows:
```
$ pdm add pydantic
Adding packages to default dependencies: pydantic
STATUS: Resolving dependencies
STATUS: Resolving: new pin python>=3.10
See <Redacted path>pdm-lock-hk933gmn.log for detailed debug log.
[SSLError]: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/52/2e/6df235627e54a46e0cb4eab44a848b53521516a4b6bb55b8a7093998afae/pydantic-1.10.5-cp310-cp310-win_amd64.whl (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))
Add '-v' to see the detailed traceback

```
