### ISSUE TITLE
`pdm build` may error out since the dist/ directory doesn't exist

### ISSUE THREAD

**Issue by eli-schwartz** [pdm-project/pdm#1647]
See e.g. https://github.com/mesonbuild/meson-python/discussions/273

Here's an example project: https://github.com/pyOpenSci/examplePy/tree/main/example6_pdm_meson

It uses pdm as a project manager, but meson-python as the pep517 compliant build backend. `mkdir dist/ && pdm build --no-clean` works. Remove the --no-clean flag and it fails.

[PEP 517](https://peps.python.org/pep-0517/) doesn't say whose responsibility it is to create the sdist_directory / wheel_directory. Some frontends, such as `build`, create it for you. PDM doesn't, apparently. Also, some backends do create it for you, I guess (I have not researched this, I assume pdm-backend does because it's presumably frequently used with PDM, and one of the two must create it).

IMHO the only viable solution here is for both backends and frontends to create that directory, because they cannot rely on the other doing it. So PDM should start to create that directory.

**Comment by lwasser** [comment]
hi 👋 @eli-schwartz @frostming !! Thank you for opening this issue. i plan to test a bit more later today given the fix now in the meson-python repo! i also am seeing here that i could use a flag `--no-clean` as well. i will experiment with that too later. 

@frostming i'm playing with packaging workflows that will be ideal for those newer to packaging as a part of an organization called pyOpenSci that supports and provides peer review of scientific python packages . We are now working on a packaging guide that overviews the ecosystem of tools and which tools might be best for which users. I did not realize that PDM had a default behavior of removing the dist dir! 

Many thanks for your work here on PDM. it seems to be a fantastic tool and I really appreciate the flexibility when selecting envt managers, etc!
