### ISSUE TITLE
Importing from `setup.py` without adds weird `dependencies`

### ISSUE THREAD

**Issue by FichteFoll** [pdm-project/pdm#1669]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. Start with a `setup.py` as follows:

```py
from setuptools import setup

setup(
    name='import_test',
    description='Tools for extracting text out of pdf documents',
    platforms=['any'],
    packages=['import_test'],
    entry_points={'console_scripts': ['import_test=import_test.__main__:main'], },
)
```

2. invoke `pdm import setup.py`

## Actual behavior

In the created `pyproject.toml`, the following is written:
```toml
dependencies = [
    "b''",
    "b''",
    "b''",
    "b''",
    "b''",
    "b''",
    "b''",
    "b''",
]
```

Nothing significant on the console:
```
$ pdm import setup.py -v
The project's requires-python has been set to >=3.10. You can change it later if necessary.
Changes are written to pyproject.toml.
```

## Expected behavior

`dependencies` is either an empty list or omitted.

## Environment Information

```bash
$ pdm info && pdm info --env
PDM version:
  2.4.2
Python Interpreter:
  /home/fichte/code/import_test/.venv/bin/python (3.10)
Project Root:
  /home/fichte/code/import_test
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.9",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.1.3-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Wed, 04 Jan 2023 16:28:15 +0000",
  "python_full_version": "3.10.9",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}
```

**Comment by FichteFoll** [comment]
Selecting setuppy during `pdm init` and with a dependency specified as follows:

```
install_requires="ass>=0.5.0",
```

pdm generates this:

```toml
dependencies = [".", ".", "0", "0", "5", "=", ">", "a", "s", "s"]
```

**Comment by pawamoy** [comment]
`install_requires` is supposed to be a list, not a string. The result you get when passing a string instead of a list is expected: PDM iterates on it and you get one item for each character.

**Comment by FichteFoll** [comment]
According to [the setuptools documentation](https://setuptools.pypa.io/en/latest/references/keywords.html), `install_requires` supports a string or a list of strings.

**Comment by pawamoy** [comment]
Ah, my bad, didn't know that! Thanks for the link :+1:

**Comment by frostming** [comment]
There has been a problem that wrong format is used to convert the file, you can workaround this by adding `--format setuppy` to make it explicit.



> According to [the setuptools documentation](https://setuptools.pypa.io/en/latest/references/keywords.html), `install_requires` supports a string or a list of strings.

At this point we don't handle such variants, please stick to a plain array instead.
