### ISSUE TITLE
Import `console_scripts` from `setup.py`

### ISSUE THREAD

**Issue by FichteFoll** [pdm-project/pdm#1670]
## Is your feature request related to a problem? Please describe.

When importing a project from `setup.py`, the `console_scripts` are currently not imported (pdm 2.4.2). I had to dig out the respective documentation manually which significantly increased the transition effort for me (since this is the first time I used this functionality and [PEP-621](https://peps.python.org/pep-0621/) in general).

The same probably also applies to the `gui_scripts` and other generic `entry_points`.

## Describe the solution you'd like

When importing a `setup.py` as follows:
```py
from setuptools import setup

setup(
    name='import_test',
    description='Tools for extracting text out of pdf documents',
    platforms=['any'],
    packages=['import_test'],
    entry_points={'console_scripts': ['import_test=import_test.__main__:main'], },
)
```

I'd expect the following section to be generated:

```toml
[project.scripts]
import_test = "import_test.__main__:main"
```

**Comment by FichteFoll** [comment]
I managed to get the expected script configuration via `pdm init` when selecting `setuppy` and answering yes to the question "Is the project a library that is installable?". I was unsuccessful with any other combination of responses to these two questions.

**Comment by frostming** [comment]
Fixed by https://github.com/pdm-project/pdm/commit/b0c6e31f7305df0fcae125ebfb2c75038ec08f3c

**Comment by FichteFoll** [comment]
The moment when I realized it was "setup-py" and not "set-uppy". 🤦
