### ISSUE TITLE
Dependency resolution downloads wheels that don't satisfy constraints

### ISSUE THREAD

**Issue by ralbertazzi** [pdm-project/pdm#1677]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

Running `pdm lock` on a platform downloads wheels for that platform even if excluded from marker constraints.

## Steps to reproduce

I ran everything on MacOS

pyproject.toml:
```toml
[tool.pdm]

[project]
authors = [{ name = "Riccardo Albertazzi", email = "ra@bendingspoons.com" }]
dependencies = ["tensorflow; sys_platform == 'linux'"]
description = ""
license = { text = "MIT" }
name = ""
requires-python = ">=3.10,<3.11"
version = ""
```

Clear cache
```
pdm cache clear
```

Lock dependencies (only interesting output is copied)
```
pdm lock -v

python.use_venv is on, creating a virtualenv for this project...
Run command: ['/opt/homebrew/Cellar/pdm/2.4.0/libexec/bin/python3.11', '-m', 'virtualenv', '/Users/ra/projects/pdm-test-platform/.venv', '-p',
'/opt/homebrew/opt/python@3.10/bin/python3.10', '--no-pip', '--no-setuptools', '--no-wheel', '--prompt=pdm-test-platform-3.10']
created virtual environment CPython3.10.8.final.0-64 in 19ms
  creator CPython3Posix(dest=/Users/ra/projects/pdm-test-platform/.venv, clear=False, no_vcs_ignore=False, global=False)
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
Virtualenv is created successfully at /Users/ra/projects/pdm-test-platform/.venv
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   tensorflow; sys_platform == "linux"
pdm.termui:   python>=3.10,<3.11
pdm.termui:   Adding requirement tensorflow; sys_platform == "linux"
pdm.termui:   Adding requirement python>=3.10,<3.11
pdm.termui: ======== Starting round 0 ========
STATUS: Resolving: new pin python>=3.10,<3.11
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
unearth.preparer: Downloading <Link https://files.pythonhosted.org/packages/ae/de/95531a6545c10c314ee8f54d87bf1937e1127bdbff0f7be88fa85e94ff01/tensorflow-2.11.0-cp310-cp310-macosx_10_14_x86_64.whl (from https://pypi.org/simple/tensorflow/)> (244.3 MB)
pdm.termui:   Adding requirement absl-py>=1.0.0(from tensorflow 2.11.0)
pdm.termui:   Adding requirement astunparse>=1.6.0(from tensorflow 2.11.0)
pdm.termui:   Adding requirement flatbuffers>=2.0(from tensorflow 2.11.0)
pdm.termui:   Adding requirement gast<=0.4.0,>=0.2.1(from tensorflow 2.11.0)
pdm.termui:   Adding requirement google-pasta>=0.1.1(from tensorflow 2.11.0)
pdm.termui:   Adding requirement h5py>=2.9.0(from tensorflow 2.11.0)
pdm.termui:   Adding requirement libclang>=13.0.0(from tensorflow 2.11.0)
pdm.termui:   Adding requirement numpy>=1.20(from tensorflow 2.11.0)
pdm.termui:   Adding requirement opt-einsum>=2.3.2(from tensorflow 2.11.0)
pdm.termui:   Adding requirement packaging(from tensorflow 2.11.0)
pdm.termui:   Adding requirement protobuf<3.20,>=3.9.2(from tensorflow 2.11.0)
pdm.termui:   Adding requirement setuptools(from tensorflow 2.11.0)
pdm.termui:   Adding requirement six>=1.12.0(from tensorflow 2.11.0)
pdm.termui:   Adding requirement termcolor>=1.1.0(from tensorflow 2.11.0)
pdm.termui:   Adding requirement typing-extensions>=3.6.6(from tensorflow 2.11.0)
pdm.termui:   Adding requirement wrapt>=1.11.0(from tensorflow 2.11.0)
pdm.termui:   Adding requirement grpcio<2.0,>=1.24.3(from tensorflow 2.11.0)
pdm.termui:   Adding requirement tensorboard<2.12,>=2.11(from tensorflow 2.11.0)
pdm.termui:   Adding requirement tensorflow-estimator<2.12,>=2.11.0(from tensorflow 2.11.0)
pdm.termui:   Adding requirement keras<2.12,>=2.11.0(from tensorflow 2.11.0)
pdm.termui:   Adding requirement tensorflow-io-gcs-filesystem>=0.23.1; platform_machine != "arm64" or platform_system != "Darwin"(from tensorflow 2.11.0)
STATUS: Resolving: new pin tensorflow 2.11.0
```

## Actual behavior

The MacOS wheel of `tensorflow` is downloaded (`tensorflow-2.11.0-cp310-cp310-macosx_10_14_x86_64.whl`).

## Expected behavior

I'm not sure what to expect, I'd like to discuss it with you. On one side, I would expect that the Linux wheel of `tensorflow` is downloaded for performing dependency resolution. On the other side I'd like to understand if `pdm` assumes that package dependencies will be equally specified in every different platform release of that package, for which it would make sense to download the MacOS wheel even if excluded.

Furthermore, I found weird to see that the `pdm.lock` contains hashes for `tensorflow` packages that do not match neither the Python specification neither the platform specification (e.g. windows wheels, Python 3.7 wheels, ..). Is this expected? If so, why? Isn't it just unnecessary information that we are dumping in there?

## Environment Information

```bash
PDM version:
  2.4.3
Python Interpreter:
  /Users/ra/projects/pdm-test-platform/.venv/bin/python (3.10)
Project Root:
  /Users/ra/projects/pdm-test-platform
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.8",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "21.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000",
  "python_full_version": "3.10.8",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}
```

Thank you so much for developing this amazing tool. I've been a happy `poetry` user for a couple years and I'm discovering `pdm` as it looks more correct and definitely faster (great caching mechanisms!).

**Comment by frostming** [comment]
> On one side, I would expect that the Linux wheel of `tensorflow` is downloaded for performing dependency resolution.

Why you are on MacOS arm64, Linux wheel and mac intel wheel are the same, despite the size.

> On the other side I'd like to understand if `pdm` assumes that package dependencies will be equally specified in every different platform release of that package, for which it would make sense to download the MacOS wheel even if excluded.

Exactly, though that is not accurate for python packaging(each wheel may have different metadata), that is a trade-off to make for the cross-platform lockfile, and poetry also does the same.


> Is this expected? If so, why? Isn't it just unnecessary information that we are dumping in there?

Yes, because we just don't want to bother with the compatibility of comparing the python range with the wheel tags(harder than you think). Some redundancy is acceptable for a trade-off.
