### ISSUE TITLE
Improve requires-python experience

### ISSUE THREAD

**Issue by ralbertazzi** [pdm-project/pdm#1678]
## Is your feature request related to a problem? Please describe.

I'm having a hard time specifying a custom correct `requires-python` through `pdm init`, often times ending with an exception `[InvalidSpecifier]: Invalid specifier`. At the same time, [the documentation](https://pdm.fming.dev/latest/usage/project/#how-requires-python-controls-the-project) provides zero examples. My experience has mostly been trial and error, which isn't great.

## Describe the solution you'd like

It would be great to:
- Improve the documentation providing some examples about the most common use cases (something similar to [this](https://python-poetry.org/docs/dependency-specification/#caret-requirements)).
	- `>=`
	- Specific minor (that I managed to achieve as `>= 3.10, < 3.11`, I don't know if there's a faster way)
	- Examples about other operands supported and the version range they are resolved to
- The exception should either:
	a. Provide a correction
	b. Link to the documentation
	c. Provide a few examples

While I understand that the `requires-python` may be part of PEP 621 and so not necessarily your responsibility, it would be great to provide some documentation where needed :)

**Comment by frostming** [comment]
Closed by https://github.com/pdm-project/pdm/commit/181bc7a9d0c7bd67f5d37a2f469140144702322b
