### ISSUE TITLE
Option to set minimum supported PDM version in pyproject.toml

### ISSUE THREAD

**Issue by Vinno97** [pdm-project/pdm#1679]
## Is your feature request related to a problem? Please describe.

Hi! I'm loving PDM and am introducing it into as many company projects as I can.
However, I had trouble with one project where I couldn't get the `tool.pdm.resolution.overrides` option to work, before finding out my version of PDM did not support this key yet.

As PDM should (I believe) be installed outside of your project's venv, this is a system dependency that can and will differ between systems. I can totally see this happening again in the future, where one project member uses some new feature of which another one doesn't even know that they don't have it.

## Describe the solution you'd like

I think it would be a great feature to be able to say "this pyproject.toml is built for PDM x.x.x and up". This way, in the future, everyone's installations either work exactly the same or give a clear error.

I can see several possible methods, like having a "schema version", but I think adding a key for PDM's version to `tool.pdm` in `pyprojec.toml` may be the most intuitive.

* Standard version specifier, used by PDM to compare its own version against (i.e. `>=2.4.3`)
* Can be written automatically, maybe one of these strategies. :
  * (Trivial, no auto-update) During init, manual update required when adding new keys
  * (Trivial, auto-update, may be too "spammy") Automatically updated when PDM's minor version is newer than the one specified
  * (Fanciest, auto-update) Automatically set to the lowest version that supports all detected config keys
    * This requires some sort of mapping or validation
* Maybe raise an error/warning when it detects a key that's newer than the specified version?
  * I.e. I've specified a minimum version of `v2.5.0`, am running `v2.6.0` and just added a key that's added in this version. PDM could then alert that the config is incompatible
    * Also relies on some sort of mapping or validation

**Comment by frostming** [comment]
IMO that is a bit overkill, workflow tool as such doesn't need to keep the older versions. Users can gain that knowledge by reading the docs for the specific release version(which is selectable at the navbar). And the docs can show the `New in version xxx` if possible. It also brings more effort for the maintainers to keep the version correct, if not automatically generated, which would be more complex.
