### ISSUE TITLE
Unable to find a resolution because the following dependencies don't work on all Python versions

### ISSUE THREAD

**Issue by T-baby** [pdm-project/pdm#1681]
Unable to find a resolution because the following dependencies don't work
on all Python versions defined by the project's `requires-python`: 
```
>=3.11.
  python>=3.7,<3.12 (from <Candidate pygls@1.0.0 from 
https://pypi.org/simple/pygls/>)
```

I don't think these two conditions are in conflict?

**Comment by frostming** [comment]
> I don't think these two conditions are in conflict?

They are conflicting. `pygls` says it doesn't work on Python 3.12, while 3.12 isn't excluded by your project, so this package just can't be locked in your project.

See also #1551, #1579. Your understanding of `requires-python` might be wrong.
