### ISSUE TITLE
`pdm` prints escape codes on Windows 10 / Powershell 7

### ISSUE THREAD

**Issue by m-legrand** [pdm-project/pdm#1685]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

- Install PDM with `pipx install pdm`
- Initialize a project using `pdm init`
- Try to start using PDM commands

## Actual behavior

PDM works fine but the output are full of escape codes making them close to unreadable. For instance

```
$ pdm --version
←[1mPDM←[0m, version ←[32m2.4.3←[0m
```

![image](https://user-images.githubusercontent.com/9072763/217284322-fa98b7f1-15f7-40af-bf1b-3e95cd6ef10c.png)

## Expected behavior

PDM working with coloured or uncoloured output, but without any escape code.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
$ pdm info && pdm info --env
PDM version:
  2.4.3
Python Interpreter:
  C:\Users\MLegrand\AppData\Local\Programs\Python\Python310\python.exe (3.10)
Project Root:
  D:/Git/MLegrand/crates
Project Packages:
  D:\Git\MLegrand\crates\__pypackages__\3.10
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.6",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19042",
  "python_full_version": "3.10.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "win32"
}
```

**Comment by frostming** [comment]
It's your console not configured properly, Windows 10 does support ANSI colors, but need to be enabled.

References:

- https://superuser.com/questions/413073/windows-console-with-ansi-colors-handling/1050078#1050078
- https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences?redirectedfrom=MSDN

It is not PDM's bug, closing it now

**Comment by m-legrand** [comment]
Thanks for the pointer to ANSI colors. The given links were targeted at the application developer (you), but looking around there are solutions to change the default behaviour for the user (me).

Here's what worked for me in case others run into the same issue ([source](https://stackoverflow.com/a/51681675/5213451)):

```pwsh
Set-ItemProperty HKCU:\Console VirtualTerminalLevel -Type DWORD 1
```

**Comment by chenyulue** [comment]
> It's your console not configured properly, Windows 10 does support ANSI colors, but need to be enabled.
> 
> References:
> 
>     * https://superuser.com/questions/413073/windows-console-with-ansi-colors-handling/1050078#1050078
> 
>     * https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences?redirectedfrom=MSDN
> 
> 
> It is not PDM's bug, closing it now

Are there any way to close the  ANSI sequence? Win7 doesn't support ANSI colors.

**Comment by frostming** [comment]
> @frostming Are there any way to close the ANSI sequence? Win7 doesn't support ANSI colors.

We rely on the good abstraction by `rich` and doesn't interactive with the console directly. You should seek for help there.

**Comment by pawamoy** [comment]
Try exporting `NO_COLOR=1`.

**Comment by zaruhev** [comment]
Hi @frostming, the ANSI colors are printed in Command Prompt without coloring on a default installation on the latest version of Windows 10. This is the default configuration for CMD, and I don't think the usage page should have ill-formatted output as a result. I feel like the colors should be omitted entirely if they are not supported. 

That being said, this doesn't hinder pdm's usability, and this can easily be fixed by either enabling it or using it in vscode. This is just a nag; however, I don't think the issue should be ignored.

Thanks for reading

**Comment by zaruhev** [comment]
P.S., the coloring system used is apparently inconsistent, as the coloring is done properly when initializing a package, but not when the usage is shown.
