### ISSUE TITLE
Dockerfile on dockerhub

### ISSUE THREAD

**Issue by mikedingjan** [pdm-project/pdm#1686]
The dockerfile on dockerhub (frostming/pdm) doesn;t support the publish command.

Since this file isn't updated in 2 years, maybe there is another one? or can someone push a newer version?

**Comment by frostming** [comment]
The reason why I don't maintain the docker image is that users may install pdm with different python versions into various base images. That will require many tags, it isn't easier than starting from a python image and install pdm into it manually.
