### ISSUE TITLE
PDM freezing when trying to install pyobjc-core, sub-dependency of rpaframework, on Windows

### ISSUE THREAD

**Issue by JoneSabino** [pdm-project/pdm#1695]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

On windows, run `pdm add rpaframework -v`, with other tools like pipenv it is installed normally.

## Actual behavior

The execution freezes when resolving `pyobjc-core` package

## Expected behavior

To finish the installation of rpaframework

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

PDM version:
  2.2.1
Python Interpreter:
  C:\prime\robot\teste-pdm\.venv\Scripts\python.exe (3.8)
Project Root:
  C:/prime/robot/teste-pdm
Project Packages:
  None

{
  "implementation_name": "cpython",
  "implementation_version": "3.8.10",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.22621",
  "python_full_version": "3.8.10",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "win32"
}

```

**Comment by frostming** [comment]
Can you reproduce with the latest PDM and show the output?

**Comment by JoneSabino** [comment]
Sure, here it is. It freezes at this point:

STATUS: Resolving: new pin pyobjc-core 9.0.1
pdm.termui: Pinning: pyobjc-core 9.0.1
pdm.termui: ======== Ending round 64 ========
pdm.termui: ======== Starting round 65 ========
unearth.preparer: Downloading <Link https://files.pythonhosted.org/packages/04/8d/7413bb658fae85ac99fc11ddc351678ab477edf4cdf1e13007e28e12c065/pyobjc-framework-ApplicationServices-9.0.1.tar.gz (from https://pypi.org/simple/pyobjc-framework-applicationservices/)> (177 kB)
pdm.termui: Running PEP 517 backend to get metadata for <Link https://files.pythonhosted.org/packages/04/8d/7413bb658fae85ac99fc11ddc351678ab477edf4cdf1e13007e28e12c065/pyobjc-framework-ApplicationServices-9.0.1.tar.gz (from https://pypi.org/simple/pyobjc-framework-applicationservices/)>
pdm.termui: Preparing isolated env for PEP 517 build...

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.4.3
Python Interpreter:
  C:\prime\robot\teste-pdm\.venv\Scripts\python.exe (3.8)
Project Root:
  C:/prime/robot/teste-pdm
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.10",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.22621",
  "python_full_version": "3.8.10",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "win32"
}
```

**Comment by frostming** [comment]
See [this comment](https://github.com/pdm-project/pdm/issues/1535#issuecomment-1336756231), closing as duplicating

**Comment by frostming** [comment]
@JoneSabino BTW, does the failure happen in installation stage or locking stage?
