### ISSUE TITLE
Module-invocation using -m in PDM scripts in PEP 582

### ISSUE THREAD

**Issue by hynek** [pdm-project/pdm#1699]
## Is your feature request related to a problem? Please describe.

I'm testing if I can move build-and-inspect-python-package to pdm and I've noticed there's no official way to run a module as I would with `python -m`.

I haven't noticed it before, because I use virtualenvs and it works there. But I wanted to give `__pypackages__` a shot and if I use `python -m` in a script there, I get the global one.

In this case I could solve it because `build` does have a CLI entry point (`pyproject-build`) that I didn't know about, but invoking modules indirectly via `python -m` has many upsides (e.g. https://snarky.ca/why-you-should-use-python-m-pip/ or https://hynek.me/articles/macos-dyld-env/).

I can't use `call` because the method names of the entry points are private implementation details.

## Describe the solution you'd like

I can think of two solutions and it would be nice to have both:

1. as with venv, ensure the `python` I get in a PDM command script is configured such that it finds the commands I need (N.B. I don't know if this is possible)
2. expand `call` to modules such that I can write `build = {call = "build"}` – this is what _I_ would use.

I think 1 not working the same way in venv and PEP 582 is actually a bug. 🤔

**Comment by frostming** [comment]
`pdm run python -m build` or `python -m build` with PEP 582 enabled globally should work

**Comment by hynek** [comment]
Uh OK this is very odd then.

It works now, but it 100% didn't before and I did double-check in `pdm list` that `build` was there. I kept getting "no module build" errors.

Closing for now – I'll reopen if I'll even run into it again and can gather more intel.
