### ISSUE TITLE
If name is not empty string in pyproject.toml file, docker build will stuck at last step of pam install

### ISSUE THREAD

**Issue by shaozi** [pdm-project/pdm#1717]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. In an empty folder, do `pdm init` to create a project
2. add a simple lib: `pdm add python-dotenv`
3. Edit `pyproject.toml` and fill a name

```toml
[project]
name = 'a'
```
4. add a Dockerfile

```dockerfile
FROM python:3.9-slim AS python-base
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONFAULTHANDLER 1
RUN apt-get update \
             && apt-get install -y --no-install-recommends curl \
             && apt-get purge -y --auto-remove \
             && rm -rf /var/lib/apt/lists/*
FROM python-base AS python-deps
# Install pdm
RUN curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 - -p /usr/local
# Install python dependencies in /.venv
COPY pyproject.toml .
COPY pdm.lock .
RUN pdm install
```

5. Run `docker build -t pdm-test .` to build a docker image
6. It will hang at the last step of pdm install at `Installing the project as an editable package... `

```sh
 => [internal] load build definition from Dockerfile                                                                                              0.0s
 => => transferring dockerfile: 576B                                                                                                              0.0s
 => [internal] load .dockerignore                                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                   0.0s
 => [internal] load metadata for docker.io/library/python:3.9-slim                                                                                0.4s
 => [python-base 1/2] FROM docker.io/library/python:3.9-slim@sha256:3bab254e90bb0986ead59a3d415e719439e629d0ff3acfdfc96021a75aab0621              0.0s
 => [internal] load build context                                                                                                                 0.0s
 => => transferring context: 533B                                                                                                                 0.0s
 => CACHED [python-base 2/2] RUN apt-get update     && apt-get install -y --no-install-recommends curl     && apt-get purge -y --auto-remove      0.0s
 => CACHED [python-deps 1/4] RUN curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 - -p /usr/local        0.0s
 => [python-deps 2/4] COPY pyproject.toml .                                                                                                       0.0s
 => [python-deps 3/4] COPY pdm.lock .                                                                                                             0.0s
 => [python-deps 4/4] RUN pdm install                                                                                                            18.0s
 => => # Changes are written to pdm.lock.                                                                                                             
 => => # STATUS: Resolving packages from lockfile...                                                                                                   
 => => # STATUS: Fetching hashes for resolved packages...                                                                                             
 => => # Synchronizing working set with lock file: 1 to add, 0 to update, 0 to remove                                                                 
 => => #   ✔ Install python-dotenv 0.21.1 successful                                                                                                  
 => => # Installing the project as an editable package...       
```

7. Now kill the process, and make the name to empty string:

```toml
    [project]
    name = ''
```

8. Rerun docker build command and it works.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
root@c27918e680fc:/# pdm info && pdm info --env
PDM version:
  2.4.5
Python Interpreter:
  /.venv/bin/python (3.9)
Project Root:
  /
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.16",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.82-0-virt",
  "platform_system": "Linux",
  "platform_version": "#1-Alpine SMP Mon, 12 Dec 2022 09:15:17 +0000",
  "python_full_version": "3.9.16",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
root@c27918e680fc:/# 
```

## pyproject.toml

```toml
[project]
# leave the name empty. otherwise pdm install hangs
name = 'a'
version = "1.0"
description = "description"
authors = [
    {name = "Jingshao Chen", email = "jingshaochen@gmail.com"},
]
dependencies = [
    "python-dotenv",
]
requires-python = ">=3.9"
license = {text = "MIT"}

[tool.pdm]
[[tool.pdm.source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"
```

**Comment by Drachenfels** [comment]
It's I guess related to: Application or library (referred: https://pdm.fming.dev/latest/usage/project/#choose-a-python-interpreter)

For me, it's a bit awkward that such strategic difference is inferred implicitly from the fact that the name is empty string or not, while pep 621 says this:

> The name of the project.
>
> Tools MUST require users to statically define this field.

I found this bug report because I have a different issue, I provided the name oblivious to the fact it implies library and setuptools and wheel were installed as a side-effect. Somehow it messed up my pylama setup within pymode and it broke my black and autoformatting. Lol, I guess. What is worse, I removed the name from pyproject.toml but it didn't uninstall either setuptools nor wheel, I had to manually pip uninstall it.

**Comment by frostming** [comment]
PEP 621 doesn't apply to a project that is not intended to be distributed as a package. It is designed as such so that users can read and write the same configuration, and it will only be validated when users trying to package and build it(as a library)

**Comment by frostming** [comment]
Except for the implicit rule, I still can't understand what is blocking. By giving the name manually, you didn't also supply the `build-system` table, and the builder will fall back to `setuptools` as the build tool. Is it that `setuptools` can't work with your project?

**Comment by frostming** [comment]
After reproducing with the docker and some debugging I found it's running from `/` which causes this, switch to a `app` directory` and it will be fine.

**Comment by shaozi** [comment]
I found another work around: add `--no-self` to `pdm install`: `pdm install --no-self`. 

I would have thought that option should be the default when I did not specify the project is a library when running `pdm init`, however, in pyproject.toml, this information is not saved. Should it show up some where there?

**Comment by frostming** [comment]
> when I did not specify the project is a library

It becomes a library if you give it a name, as you did.

**Comment by berislavlopac** [comment]
One solution might be a switch to enforce the desired behaviour using a PDM configuration variable? Something like `is_library = false`, which would default to the current behaviour. That would allow non-libraries to have a name defined in `pyproject.toml`, for documentation and other purposes.

**Comment by deronnax** [comment]
I just got it by the problem, for a library for which we provide a docker-based development workflow. I think this bug is worth addressing (and with the generalization of dev-containers, people might run into it more and more)
