### ISSUE TITLE
Update docs pdm-pep517 -> pdm-backend

### ISSUE THREAD

**Issue by pawamoy** [pdm-project/pdm#1722]
This page https://pdm.fming.dev/latest/pyproject/build/ still mentions the old name: `pdm-pep517`.
It should be updated to use the new name: `pdm-backend`.

**Comment by lofidevops** [comment]
Does this mean pdm-pep517 and pdm-backend are equivalent? When I run `pdm init` from pdm 2.4.8 I am offered both:

```
Which build backend to use?
0. pdm-pep517
1. setuptools
2. flit-core
3. hatchling
4. pdm-backend
```

(Happy to create a new issue if needed.)

**Comment by frostming** [comment]
@lofidevops The default backend has been already switched on the dev branch, so this issue can be resolved after it is merged.

**Comment by frostming** [comment]
@pawamoy You can still write it as `license = {text = "MIT"}`

**Comment by pawamoy** [comment]
Oh :open_mouth: ! That's great, didn't know that :tada: :rocket: 
It also picks up my LICENSE file :+1: 
Well OK, here I come `pdm-backend` :slightly_smiling_face:
