### ISSUE TITLE
pdm publish: pdm.exceptions.NoConfigError: 'No such config item: .password'

### ISSUE THREAD

**Issue by edouard-lopez** [pdm-project/pdm#1724]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```
git clone github.com:edouard-lopez/pure.py.git
git fetch origin ci/publish-to-pipy
git switch ci/publish-to-pipy
git checkout a190882
```
Edit the `.pdm.toml`:

```
[pypi]
url = "https://pypi.org/simple"

[python]
path = "/data/projects/pure/pure.py/.venv/bin/python"

[pure-prompt]
repository = "https://upload.pypi.org/legacy/"
username = "__token__"
password = "pypi-foo-bar"
```

Finally try to publish:
```
❯ pdm publish --verbose
```

## Actual behavior

```
❯ pdm publish --verbose
Building sdist...
[NoConfigError]: 'No such config item: pure-prompt.repository'
```

<details>
<summary>Verbose output/log</summary>
<pre>
Traceback (most recent call last):
  File "/home/ed8/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/ed8/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 259, in main
    return Core().main(args)
  File "/home/ed8/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 168, in main
    self.ui.set_theme(project.global_config.load_theme())
  File "/home/ed8/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/project/config.py", line 326, in load_theme
    {k[6:]: v for k, v in self.items() if k.startswith("theme.")}
  File "/home/ed8/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/project/config.py", line 326, in <dictcomp>
    {k[6:]: v for k, v in self.items() if k.startswith("theme.")}
  File "/usr/lib/python3.10/_collections_abc.py", line 906, in __iter__
    yield (key, self._mapping[key])
  File "/home/ed8/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/project/config.py", line 383, in __getitem__
    raise NoConfigError(key)
pdm.exceptions.NoConfigError: 'No such config item: pure-prompt.username'

</pre>
</details>

## Expected behavior

Well, I was expecting the new version of the package to be published in https://pypi.org/project/pure/.

## Environment Information

```bash
❯ pdm info 
[NoConfigError]: 'No such config item: pure-prompt.repository'
```

If I remove all property under `pure-prompt`, I get:

```
❯ pdm info && pdm info --env
PDM version:
  2.4.5
Python Interpreter:
  /data/projects/pure/pure.py/.venv/bin/python (3.10)
Project Root:
  /data/projects/pure/pure.py
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.10",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.0-60-generic",
  "platform_system": "Linux",
  "platform_version": "#66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023",
  "python_full_version": "3.10.10",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}

**Comment by frostming** [comment]
read the docs pls
