### ISSUE TITLE
How to install requirements from non-pypi index (codeartifact)?

### ISSUE THREAD

**Issue by zyd14** [pdm-project/pdm#1728]
## Is your feature request related to a problem? Please describe.

Thanks for the really cool project! I'd really like to use it for a large monorepo project of mine, but I'm running into an issue getting going. Maybe this is already possible but I'm having trouble finding anywhere in the documentation how to configure non-pypi indexes. I have some requirements that reside in AWS Codeartifact, while most are pulled from pypi. Is it currently possible to configure PDM to allow for pulling of dependencies from different indexes? 

## Describe the solution you'd like
I'd like to be able to configure additional indexes to search when installing dependencies through PDM. I would need to be able to pass in credentials, ideally via environment variable. Ideally I could configure multiple additional indexes.

**Comment by frostming** [comment]
https://pdm.fming.dev/latest/pyproject/tool-pdm/#specify-other-sources-for-finding-packages
