### ISSUE TITLE
Request for Adding Support for Nuitka Build-Backend

### ISSUE THREAD

**Issue by xiaojinwhu** [pdm-project/pdm#1733]
Currently, this repository does not support the use of [Nuitka](https://github.com/Nuitka/Nuitka) as a build-backend.

sample code in pyproject.toml:
```
[build-system]
requires = ["setuptools>=42", "wheel", "nuitka", "toml"]
build-backend = "nuitka.distutils.Build"

[nuitka]
# These are not recommended, but they make it obvious to have effect.

# boolean option, e.g. if you cared for C compilation commands, leading
# dashes are omitted
show-scons = true

# options with single values, e.g. enable a plugin of Nuitka
enable-plugin = "pyside2"

# options with several values, e.g. avoiding including modules, accepts
# list argument.
nofollow-import-to = ["*.tests", "*.distutils"]
```
error:
`ValueError: invalid pyproject.toml config: data.project.dependencies.configuration error: `

**Comment by pawamoy** [comment]
Can you show the command you're running in verbose mode, and show the full traceback and logs please?

The error seems related to dependencies. Have you tried declaring an empty `dependencies = []` in pyproject.toml?

**Comment by xiaojinwhu** [comment]
Thank you for the reminder. I am working to identify the issue. 
> In some scenarios, it is necessary to deploy the source code in an encrypted form, and compiling with Nuitka is a good solution for this.

**Comment by xiaojinwhu** [comment]
with the config,  build success。
```
[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"
```
---------
but failed in the above build-system.
![image](https://user-images.githubusercontent.com/10114923/221149210-d852e2d3-c669-4b03-b988-35252ffd74aa.png)

**Comment by pawamoy** [comment]
Again, the error message speaks about dependencies:

> Have you tried declaring an empty dependencies = [] in pyproject.toml?

Please show your full pyproject.toml.

**Comment by xiaojinwhu** [comment]
I tried commenting out the dependencies, but the error persisted as usual.
![image](https://user-images.githubusercontent.com/10114923/221155341-bc0dd1b7-7f54-47dd-a54d-7c9bfb02137d.png)

**Comment by pawamoy** [comment]
Try removing `dynamic = ["dependencies"]`. You can't declare them as both dynamic and static.

**Comment by xiaojinwhu** [comment]
It worked! Thank you for your kind words. @pawamoy 
PDM is indeed a great tool !
