### ISSUE TITLE
Include .pdm.toml in root .gitignore when running `pdm init`

### ISSUE THREAD

**Issue by Nadock** [pdm-project/pdm#1749]
## Is your feature request related to a problem? Please describe.

When running `pdm --init` add a root level `.gitignore` and write the `.pdm.toml` path to it. Alternatively, if a `.gitignore` already exists append the path to the file.

This would be similar to how `pdm --init` created `__pypackages__/.gitignore`, but for the `.pdm.toml` file. (#446)

This would save people a bit of extra time reading the docs (#1364) to know that you don't want to commit this file.

## Describe the solution you'd like

The `pdm --init` creates (or updates) the project root's `.gitignore` to include the `.pdm.toml` path.

---

If this is accepted I would be happy to open a PR to implement this.

**Comment by frostming** [comment]
In fact, we have changed the config strategy in the dev branch. `.pdm.toml` will be renamed to `pdm.toml` and can be shared.

**Comment by Nadock** [comment]
Neat! I haven't tried it out on the dev branch, but it seems like `.pdm-python` could/should be added to the root `.gitignore` in that case?

**Comment by frostming** [comment]
> but it seems like `.pdm-python` could/should be added to the root `.gitignore` in that case?

Yeah, that SGTM.

**Comment by pawamoy** [comment]
> .pdm.toml will be renamed to pdm.toml and can be shared.

Hmm is this really necessary? :thinking: 
Lots of config files meant to be versioned still start with a dot.
Changing the name will require *everybody* to update their .gitignore.

**Comment by pawamoy** [comment]
Hmmmm everybody will have to update their `.gitignore` anyway to include `.pdm-python`. Still, I'd prefer to have both `.pdm-python` and `.pdm.toml` next to each other in my file tree. But that's not very important, don't bother too much :+1:

**Comment by Ttayu** [comment]
I suggest using the Python .gitignore template from https://github.com/github/gitignore/blob/main/Python.gitignore as the starting point.
Here, files like .pdm.toml are being ignored as well.

**Comment by frostming** [comment]
> Changing the name will require _everybody_ to update their .gitignore.

Yes that is intentional, the renamed file `pdm.toml` doesn't need to be ignored. There will be a hint and a command to automatically do the fix.

**Comment by Nadock** [comment]
> I suggest using the Python .gitignore template from https://github.com/github/gitignore/blob/main/Python.gitignore as the starting point. 

There's a discussion in the related PR #1751 on this point, FYI.

**Comment by Ttayu** [comment]
> > I suggest using the Python .gitignore template from https://github.com/github/gitignore/blob/main/Python.gitignore as the starting point.
> 
> There's a discussion in the related PR #1751 on this point, FYI.

In fact, the intention here was not to modify .gitignore in pdm, but to create a PR in gitignore's repository. However, this will be merged soon.
