### ISSUE TITLE
`pdm info --packages` display `None`

### ISSUE THREAD

**Issue by abersheeran** [pdm-project/pdm#1750]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```
$ pdm info --packages
None
```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.4.7
Python Interpreter:
  /Users/aber/Documents/Coding/oldtime/oldtime/.venv/bin/python (3.10)
Project Root:
  /Users/aber/Documents/Coding/oldtime/oldtime
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.9",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "22.1.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103",
  "python_full_version": "3.10.9",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
This property is designed as a helper for the PEP 582 layout and if you are not using PEP 582, it will show as None. So it should be kept as-is now unless we decide to give it another meaning.

**Comment by abersheeran** [comment]
Maybe need add a warning like `This property is designed as a helper for the PEP 582 layout` when Project Packages is None.
