### ISSUE TITLE
pdm uses active conda virtualenv despite PDM_VENV_BACKEND=virtualenv

### ISSUE THREAD

**Issue by mforbes** [pdm-project/pdm#1756]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

Summary: There is no easy way to ignore an active conda environment and force the use of the `venv.backend = virtualenv`.

Use case: I use a conda environment to install various tools, so I need to keep this active, but don't want to use or pollute this environment when I am using pdm to manage projects.  I expect that explicitly setting the backend to `virtualenv` instead of `conda` should allow this use, and see no easy workaround short of deactivating my conda environment and finding some other way of making the tools in there available.

There is some magic under the hood that detects and tries to use the underlying conda environment as a virtual env.  This might be fine, but one should be able to explicitly disable it with flags or environmental variables. *(One might consider revising this magic to ignore the `base` environment. I think `poetry` does this, so some users might come expecting this.)*

Note: the magic fails if the conda environment is not writable by the user.  In this case, pdm will try to use the environment, but install will fail.  (This is actually how I set things up on my machine, but to simplify the MnWE, I created a writable environment below which `pdm` will happily install into.)

## Steps to reproduce

1. Create and activate a conda environment with a version of python supported by your project:

    ```bash
    conda create -n tst-pdm python==3.10
    conda activate test-pdm
    ```
2. Use a `pyproject.toml` file like this:

    ```toml
    [tool.pdm]
    
    [project]
    name = ""
    version = ""
    description = ""
    authors = []
    dependencies = [
        "uncertainties>=3.1.7",
    ]
    requires-python = ">=3.10"
    license = {}
    ```
3. Install the project with the `virtualenv` backend (not conda).

    ```bash
    $ PDM_VENV_IN_PROJECT=1 PDM_USE_VENV=1 PDM_VENV_BACKEND=virtualenv PDM_IGNORE_SAVED_PYTHON=1 pdm install -v
    Lock file does not exist
    Updating the lock file...
    Inside an active virtualenv /Users/mforbes/.conda/envs/tst-pdm, reusing it.
    ...
    ```

## Actual behavior

The active conda environment is reused despite me explicitly telling pdm to use the "virtualenv" backend (see above).

## Expected behavior

A virtual environment is created in `.venv` using the specified `virtualenv` backend and used to install.  Note: this behaviour does occur if the python version in `pyproject.toml` is incompatible with the version of python in the conda environment (for example, by setting `requires-python = ">=3.11"` above.)

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
pdm info && pdm info --env
Inside an active virtualenv /Users/mforbes/.conda/envs/tst-pdm, reusing it.
PDM version:
  2.4.7
Python Interpreter:
  /Users/mforbes/.conda/envs/tst-pdm/bin/python (3.10)
Project Root:
  /Users/mforbes/_tmp
Project Packages:
  None
Inside an active virtualenv /Users/mforbes/.conda/envs/tst-pdm, reusing it.
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.0",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "21.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 21.6.0: Mon Dec 19 20:43:09 PST 2022; root:xnu-8020.240.18~2/RELEASE_ARM64_T6000",
  "python_full_version": "3.10.0",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
unset env CONDA_PREFIX should skip that. Or don't rely on the auto-creation, but manually create one and pdm use to switch to it.

**Comment by mforbes** [comment]
@frostming Thanks: `CONDA_PREFIX=` works (and since I am trying to do this in a Makefile, this is a fine workaround.)  I still think that the issue should be resolved properly though: In other contexts, setting `CONDA_PREFIX=` in a session might cause other issues.

One question about `pdm use`: I am seeing this:

```bash
$ pdm -v venv create 3.10
Virtualenv /Users/mforbes/_tmp/.venv is created successfully
$ pdm -v use .venv
Using the last selection, add '-i' to ignore it.
Using Python interpreter: /Users/mforbes/current/pwg/testing/.venv/bin/python3 (3.11)
```

Why does this say (3.11) at the end?  The version of python installed is 3.10:

```bash
$ pdm -v use .venv/bin/python3.10
Using the last selection, add '-i' to ignore it.
Using Python interpreter: /Users/mforbes/_tmp/.venv/bin/python3.10 (3.10)
```

Is this a bug I should report, or am I missing the meaning of the `(3.11)` reported?

**Comment by frostming** [comment]
> ```shell
> Using Python interpreter: /Users/mforbes/current/pwg/testing/.venv/bin/python3 (3.11)
> ```

Note it is using a different Python from the what is just created, this is because PDM will *cache* the resolution when a name is given to `pdm use`, as the line implies:

```
Using the last selection, add '-i' to ignore it.
```

So you need to add `-i`, or use the absolute path instead.

**Comment by mforbes** [comment]
Ah.  I see. No bug then.  This was not what I was expecting since I specified a fully qualified local path to the virtual environment, but indeed it is using a cached version that I must have specified in the past, and that is correctly labelling this as 3.11.

I think there may need to be a tutorial somewhere describing how to use pdm in two different cases:

1. As a casual user where it tries to guess to make things as easy as possible for the user.
2. In a development setting (like a Makefile) where the user wants to know exactly what is going on in a reproducible way.

The defaults implement 1. which are causing me to have lots of hangups when trying to do 2.

Thanks for the help.

**Comment by mforbes** [comment]
Just a note: to programmatically disable detection of another active virtual environment, one can unset `VIRTUAL_ENV=` similar to how unsetting `CONDA_PREFIX=` works as @frostming suggested.

**Comment by frostming** [comment]
Added env var `PDM_IGNORE_ACTIVE_VENV` to ignore the active venv/conda environment.
