### ISSUE TITLE
Missing `compatible` strategy.save in docs

### ISSUE THREAD

**Issue by wgordon17** [pdm-project/pdm#1769]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

This is more of a docs bug than anything at the moment. When trying to understand the "save" strategy, I found on the configuration page

---

strategy.save | Specify how to save versions when a package is added | minimum(can be: exact, wildcard, minimum) | Yes
-- | -- | -- | --

---

2 issues with this

1. I don't see `compatible` listed, but it looks like it was added over 2 years ago #230
2. I see `wildcard` listed (also on the CLI page), but I don't see `wildcard` as any option https://github.com/pdm-project/pdm/blob/main/src/pdm/cli/utils.py#L468, so I'm confused as the behavior of `wildcard`.

Finally, this one might be a bit controversial, but I was wondering if it's worth opening an `Enhancement` issue to suggest moving from `minimum` to `compatible` as the default save strategy. This _could_ be considered a breaking change, but IMO, it's the _correct_ behavior, to default to compatible package versions instead of just specifying a minimum and letting packages upgrade to breaking semvar versions. I feel like that behavior is surprising, to say the least (I was surprised by it). I don't want to hash out this discussion here, since I want to focus on the docs bug here. Mostly just wondering if it's worth opening the `Enhancement` or let me idea just die here if there's no interest

**Comment by frostming** [comment]
> but IMO, it's the _correct_ behavior, to default to compatible package versions instead of just specifying a minimum and letting packages upgrade to breaking semvar versions.

Not really, you may be from the application perspective, but for a library, version specifiers with **upper bound** [may be harmful](https://iscinumpy.dev/post/bound-version-constraints/), and this effect is harder to fix than a minimum strategy used on an application, so we decide to make it the default.

**Comment by wgordon17** [comment]
Ahh, ok...that definitely makes sense then. Yeah, coming at this from an application perspective...at least it's configurable 🚀
