### ISSUE TITLE
PEP 582/python search path conflict with pyright

### ISSUE THREAD

**Issue by adamhl8** [pdm-project/pdm#1770]
I was having an issue when using pyright with a PEP 582 project where I was getting missing type stub errors. I opened an [**issue**](https://github.com/microsoft/pyright/issues/4771) on the pyright repo and ultimately the cause of the issue is that PDM is adding my `project_root/src` directory to the python search path, causing pyright to consider it an external library.

To outline what's going on:

- I have `/home/<user>/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/pep582` on PYTHONPATH as added by `pdm --pep582`.
- From what I understand, this causes `sitecustomize.py` to "inject" the `__pypackages__` lib path to the python search path.
- However, this also seems to add an (unnecessary?) path as well that maps to my `src` folder.
- pyright picks all of these up and uses them to resolve imports.

With the `pdm --pep582` path on PYTHONPATH, pyright receives the following directories:
```
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/usr/local/lib/python3.10/dist-packages
/usr/lib/python3/dist-packages
/home/<user>/dev/<project>/__pypackages__/3.10/lib
/home/<user>/dev/<project>/src
```

And without `pdm --pep582` on PYTHONPATH:

```
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/usr/local/lib/python3.10/dist-packages
/usr/lib/python3/dist-packages
```

As you can see, PDM adds these additional paths:
```
/home/<user>/dev/<project>/__pypackages__/3.10/lib
/home/<user>/dev/<project>/src
```

So I suppose my question is why is my `src` folder also being added? I would assume that the `__pypackages__` lib folder should be the only addition.

**Comment by frostming** [comment]
> So I suppose my question is why is my `src` folder also being added? I would assume that the `__pypackages__` lib folder should be the only addition.

Because your project is installed in editable mode, which puts a `.pth` file under the library path and it's loaded when `__pypackages__` is added. The `.pth` file adds the `src` to the `sys.path` so you can import your own modules.

**Comment by adamhl8** [comment]
Ah gotcha. In my case I'd want to do `pdm install --no-self`.

What's the purpose of defaulting to installing the project in editable mode? Doesn't python automatically add the directory containing the invoked module to `sys.path`?

**Comment by frostming** [comment]
> Doesn't python automatically add the directory containing the invoked module to `sys.path`?

Nope, why should it do that?

**Comment by adamhl8** [comment]
I might be misunderstanding what you're saying, but that's why python adds the parent directory of the module to `sys.path`.

> The first entry in the module search path is the directory that contains the input script, if there is one.

https://docs.python.org/3/library/sys_path_init.html

**Comment by frostming** [comment]
> > Python only knows how to import a module when its path is in sys.path
> 
> I might be misunderstanding what you're saying, but that's why python adds the parent directory of the module to `sys.path`.
> 
> From https://docs.python.org/3/library/sys_path_init.html:
> 
> > The first entry in the module search path is the directory that contains the input script, if there is one.

But if your module resides in `src`, how can Python import it without adding `src` to the `sys.path`?

**Comment by adamhl8** [comment]
If I have a folder structure like so:

```
project_root/
└── src/
    ├── module_a.py
```

And then from `project_root` run `python src/module_a.py`, `/path/to/project_root/src` is automatically added to `sys.path`.

**Comment by frostming** [comment]
> 



> And then from `project_root` run `python src/module_a.py`, `/path/to/project_root/src` is automatically added to `sys.path`.

True, but it will also enable `python -m module_a.py`. Or `import module_a` in the python REPL started under the project root.

**Comment by adamhl8** [comment]
It seems like this is the default behavior for other package managers as well. This [poetry issue ](https://github.com/python-poetry/poetry/issues/2458) has some interesting discussion around it.

Would you consider a `[tool.pdm]` setting called something like `installNoRoot = true` so I can adjust this per project?

**Comment by pawamoy** [comment]
@adamhl8 are you actually developing individual Python scripts rather than a Python package? I ask because you said you run them with `python src/module_a.py`.

**Comment by adamhl8** [comment]
I'm developing a package so it's not something I'd normally run with python directly. Overall I suppose I don't really understand why PDM (and other tools like poetry) default to installing the root project (i.e. adding it to `sys.path`).

I think my issue and the issues people outlined in the poetry issue I linked above demonstrates how this can cause problems. Is it  just so you can more easily run `python -m module_a.py` or import in the REPL?

**Comment by frostming** [comment]
> Overall I suppose I don't really understand why PDM (and other tools like poetry) default to installing the root project (i.e. adding it to `sys.path`).

When you run `pdm/poetry install`, it's usually because you want to start developing and want to run the tests to verify the behavior of your package. As you're developing a package after all, It doesn't make sense to only install `pytest` without the package itself. What am I supposed to do with just `pytest`?

IMO the current behavior is quite reasonable, with an opt-out `--no-self` option.
