### ISSUE TITLE
PDM's output is not clean on Windows

### ISSUE THREAD

**Issue by iincer** [pdm-project/pdm#1772]
This is a duplicate of issue #939, which was closed on Jun 28, 2022, but which is still showing up.

## Steps to reproduce
I have a Windows machine with pdm 2.4.0. When I run the command `pdm -V`, this is my output on cmd, powershell, and bash:
```
←[1mPDM←[0m, version ←[32m2.4.0←[0m
```

## Expected behavior

I would expect a clean output string.

**Comment by frostming** [comment]
Please make sure virtual terminal feature is turned on for your terminal, google it fow how to.
It is not something solvable in PDM side. See also: https://github.com/Textualize/rich/issues/2688

**Comment by iincer** [comment]
Thank you @frostming. I followed your suggestion, and things are working.
