### ISSUE TITLE
Correct version no longer printed for dynamic versions (from file)

### ISSUE THREAD

**Issue by mfeteanu-cais** [pdm-project/pdm#1775]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

I believe this was broken by this PR: https://github.com/pdm-project/pdm/pull/1740
Specifically this line: https://github.com/pdm-project/pdm/pull/1740/files#diff-9b11b79e096e6e61fe0c411ad17368e505cef292ce2606b1064255331effaa52R61

## Steps to reproduce

In pyproject.toml:
```

[tool.pdm]
version = { source = "file", path = "myproject/__version__.py" }

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"
```

```
pdm show --version
```

## Actual behavior

It prints:
```
DYNAMYC
```

## Expected behavior
It prints
```
1.2.3
```

Or whatever is in myproject/__version__.py

## Environment Information

```bash
PDM version:
  2.4.9
Python Interpreter:
..../python (3.10)
Project Root:
....
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.5",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "22.3.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000",
  "python_full_version": "3.10.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}


```

**Comment by edsq** [comment]
Is this a duplicate of #1753?  The solution found there was to run  `pdm show --version <package name>`.

**Comment by mfeteanu-cais** [comment]
This is a duplicate, yes. I am closing this then. However, will this eventually be fixed to work just with `pdm show --version`. It seems like printing DYNAMIC is almost never the correct behaviour.

**Comment by mfeteanu-cais** [comment]
duplicate of #1753
