### ISSUE TITLE
Inability to pin a dependency

### ISSUE THREAD

**Issue by timcogan** [pdm-project/pdm#1777]
## Steps to reproduce

I have 3 repos I'm working with: `RA`, `RB`, and `RC`.

`RA` installs `RB` as a dependency, and `RB` installs `RC` as a dependency: `RA` <- `RB` <- `RC`.

Therefore, `RC` is a dependency of both `RA` and `RB`.

The error occurs when I try to pin the version of `RC` from within `RA`.

## Actual behavior

I'd like to pin the version of `RC` when it is installed in `RA`. However, when I try to do so, I get the following error:

```bash
Unable to find a resolution for RC
because of the following conflicts:
  RC @ git+ssh://git@github.com/MY_ORG/RC.git (from RB@git+ssh://git@github.com/MY_ORG/RB.git)
  RC @ git+ssh://git@github.com/MY_ORG/RC.git@abcd123 (from project)
```

## Expected behavior

This error should not exist since there is no conflict between the pinned version of `RC` and the unpinned version. A related issue arises if `RC` is listed with `https` instead of `ssh`, whether or not it's pinned.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
❯ pdm info
PDM version:
  2.4.8
Python Interpreter:
  PROJECT_ROOT/env/bin/python (3.10)

❯ pdm info --env
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.6",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.0-67-generic",
  "platform_system": "Linux",
  "platform_version": "#74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023",
  "python_full_version": "3.10.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
As the error shows, there is a conflict:
```
  RC @ git+ssh://git@github.com/MY_ORG/RC.git (from RB@git+ssh://git@github.com/MY_ORG/RB.git)
  RC @ git+ssh://git@github.com/MY_ORG/RC.git@abcd123 (from project)
```

The top project requests for `RC.git` at ref `abcd123`, while the `RB` package requires the latest commit on the default branch, which are not the same, hence the conflict. You may have different expectations, but this is how PDM looks at them.
