### ISSUE TITLE
use venv if virtualenv is not present

### ISSUE THREAD

**Issue by franzhaas** [pdm-project/pdm#1808]
## Is your feature request related to a problem? Please describe.

To my understanding, pdm uses virtualenv by default. Virtualenv is an optional package which may or may not be present on a given installation. However venv is part of standard python since 3.3.

It would be real great if pdm would use venv if virtualenv is not present. On some linux distributions python is stripped of venv although it should be part of a python distribution, but I still believe it would be the better option.

Thanks in advance,
Franz

**Comment by frostming** [comment]
I don't understand what you mean by "virtualenv is not present", virtualenv is a hard dependency of PDM, using it as a default should be the best option, as venv is not installed on some distros.

**Comment by franzhaas** [comment]
Ok, thats odd. Starting from python 3.3 venv is part of the standard library. When I install python from python.org (windows), it comes with venv, but not virutalenv... Running pdm from a zipapp here brings me into the situation that venv does exist but virtualenv does not.
