### ISSUE TITLE
Allow the option to --prefer-binary

### ISSUE THREAD

**Issue by peircej** [pdm-project/pdm#1812]
Apologies if I've misunderstood how this works - I'm new to `pdm` (and enjoying it a great deal! 😁 ) and I may not have understood how pdm and pip play together

## The problem

Some dependent packages need compiling, but as they generally provide wheels we don't typically need to worry about it. Then they make a release and forget the wheel, or the wheel is delayed appearing, and suddenly automated build scripts fail because they haven't been given the compiler dependencies to do the build. OK so the developer can make sure that their build script includes all headers/dylibs etc for dependent packages just in case this time it needs a compile step, but it would be nice not to bother!

With simple pip installs that's fine - specify `--prefer-binary` and it will try to find a version that _did_ have a wheel rather than installing necessarily the latest version. Unfortunately that's broken (if I understand correctly) by using pdm because there isn't this option when adding a dependency via pdm, and that's what pip then uses for its install (so `--prefer-binary` has no effect on pip anymore)

## Describe the solution you'd like

It would be nice to have either a per-package option to `--prefer-binary` during `pdm add` (although I'm not sure that's possible if no way of storing it in pyproject) or an option like that during `pdm lock` for all packages so that we can set that preference when creating the lock file to be used

**Comment by frostming** [comment]
This is supported and released in 2.5.0, read the [changelog](https://github.com/pdm-project/pdm/releases/tag/2.5.0) for how to do it.
