### ISSUE TITLE
Post install script run

### ISSUE THREAD

**Issue by lyz-code** [pdm-project/pdm#1813]
Hi, I'm trying to run a script each time a user runs `pip install my_package` to create some files in the user home directory that my package needs. I tried using the build hook scripts but I clearly misunderstood them.

[Searching online](https://stackoverflow.com/questions/15853058/run-custom-task-when-call-pip-install) I've seen that this is usually done through `setuptools.command.install`. Can you point me in the direction on how to do this using pdm?

Thanks

**Comment by lyz-code** [comment]
Sorry if I didn't add the enough context in the issue. I'm building a [command line tool](https://github.com/lyz-code/pass-collaborate) that needs some user configuration for it to work.

As much as I love `pdm` I'm aware that 99% of the people still uses `pip` to install the packages, so I build my python packages with `pdm` but expect them to be installed with `pip`.

With that in mind the question would be if there is a way to configure `pdm` through the `pyproject.toml` so that when it builds the package it somehow tells the installer tool (being it `pip`, `pdm`, `poetry` or whatever) to run these tasks when the user installs the package:

- Create a directory in the user's home
- Copy some files into that directory
- Append some text to other files (such as `.bashrc` or `.zshrc`)

The alternative I can think of is that each time the user runs the command line tool it first checks if these conditions are met and if they aren't to run the necessary actions. However this approach adds an overhead on each run which I rather not have.

Can you think of any other solution?

**Comment by frostming** [comment]
Oh, I understand what you're doing now. Just put a `pdm_build.py` in the project root and following [this guide](https://pdm-backend.fming.dev/hooks/#add-more-files-or-change-the-collected-files) to write your build hook. Note you should use `pdm-backend` as the build backend and ensure users must install from sdist. Other backends such as [hatchling](https://hatch.pypa.io/latest/plugins/build-hook/custom/) also has similar abilities.

**Comment by lyz-code** [comment]
Thanks for the quick reply, I'm trying to follow the steps in [this PR](https://github.com/lyz-code/pass-collaborate/pull/2/files), but I'm encountering the next error in the CI when it tries to execute `pdm install --dev`:

```
pdm install --dev
STATUS: Resolving packages from lockfile...
Inside an active virtualenv /home/runner/work/pass-collaborate/pass-collaborate/.venv, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
STATUS: Fetching hashes for resolved packages...
Synchronizing working set with lock file: 164 to add, 1 to update, 0 to remove

  ✔ Update setuptools 67.4.0 -> 67.2.0 successful
  ✔ Install astor 0.8.1 successful
  ✔ Install argcomplete 2.0.0 successful
  ✔ Install astpretty 2.1.0 successful
  ✔ Install astroid 2.11.7 successful
  ✔ Install asttokens 2.2.1 successful
  ✔ Install attrs 22.2.0 successful
  ✔ Install autoflake 1.7.8 successful
  ✔ Install autoimport 1.3.3 successful
  ✔ Install bandit 1.7.4 successful
  ✔ Install beautifulsoup4 4.11.2 successful
  ✔ Install black 23.1.0 successful
  ✔ Install bleach 6.0.0 successful
  ✔ Install babel 2.11.0 successful
  ✔ Install certifi 2022.12.7 successful
  ✔ Install cffi 1.15.1 successful
  ✔ Install cfgv 3.3.1 successful
  ✔ Install charset-normalizer 2.1.1 successful
  ✔ Install click 8.1.3 successful
  ✔ Install colorama 0.4.6 successful
  ✔ Install commitizen 2.42.0 successful
  ✔ Install coverage 7.1.0 successful
  ✔ Install cryptography 39.0.1 successful
  ✔ Install decli 0.5.2 successful
  ✔ Install dill 0.3.6 successful
  ✔ Install distlib 0.3.6 successful
  ✔ Install distro 1.8.0 successful
  ✔ Install dlint 0.14.0 successful
  ✔ Install dnspython 2.2.1 successful
  ✔ Install docutils 0.19 successful
  ✔ Install csscompressor 0.9.5 successful
  ✔ Install dparse 0.6.2 successful
  ✔ Install email-validator 1.3.0 successful
  ✔ Install entrypoints 0.4 successful
  ✔ Install eradicate 2.1.0 successful
  ✔ Install exceptiongroup 1.1.0 successful
  ✔ Install execnet 1.9.0 successful
  ✔ Install filelock 3.9.0 successful
  ✔ Install flake8 4.0.1 successful
  ✔ Install faker 16.8.1 successful
  ✔ Install flake8-aaa 0.12.2 successful
  ✔ Install flake8-annotations-complexity 0.0.7 successful
  ✔ Install flake8-annotations 2.9.1 successful
  ✔ Install snowballstemmer 2.2.0 successful
  ✔ Install sh 1.14.3 successful
  ✔ Install soupsieve 2.3.2.post1 successful
  ✔ Install stevedore 3.5.2 successful
  ✔ Install termcolor 2.2.0 successful
  ✔ Install toml 0.10.2 successful
  ✔ Install tomli 2.0.1 successful
  ✔ Install tomlkit 0.11.6 successful
  ✔ Install twine 4.0.2 successful
  ✔ Install typer 0.7.0 successful
  ✔ Install types-click 7.1.8 successful
  ✔ Install typing-extensions 4.4.0 successful
  ✔ Install urllib3 1.26.14 successful
  ✔ Install watchdog 2.2.1 successful
  ✔ Install wcwidth 0.2.6 successful
  ✔ Install webencodings 0.5.1 successful
  ✔ Install virtualenv 20.19.0 successful
  ✔ Install wrapt 1.15.0rc1 successful
  ✔ Install xdg 5.1.1 successful
  ✔ Install yamlfix 1.8.1 successful
  ✔ Install yamllint 1.29.0 successful
  ✔ Install zipp 3.13.0 successful
Installing the project as an editable package...
  ✖ Install pass-collaborate 0.0.0+editable failed

See /tmp/pdm-install-mx59gp55.log for detailed debug log.
[BuildError]: Build backend raised error: Showing the last 10 lines of the build output:
    return hook(wheel_directory, config_settings, metadata_directory)
  File "/tmp/pdm-build-env-ac2740te-shared/lib/python3.9/site-packages/pdm/backend/__init__.py", line 100, in build_editable
    return builder.build(
  File "/tmp/pdm-build-env-ac2740te-shared/lib/python3.9/site-packages/pdm/backend/base.py", line 191, in build
    artifact = self.build_artifact(context, files)
  File "/tmp/pdm-build-env-ac2740te-shared/lib/python3.9/site-packages/pdm/backend/wheel.py", line 129, in build_artifact
    records.append(self._add_file_to_zip(zf, rel_path, full_path))
  File "/tmp/pdm-build-env-ac2740te-shared/lib/python3.9/site-packages/pdm/backend/wheel.py", line 211, in _add_file_to_zip
    st_mode = os.stat(full_path).st_mode
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/.password-store/.extensions/access.bash'
Add '-v' to see the detailed traceback
make: *** [Makefile:8: install] Error 1
```

I'm quite sure that the `/home/runner/.password-store/.extensions` directory doesn't exist, either for the CI user nor for the target user. I expected the installation process to create it, is that possible?

**Comment by frostming** [comment]
i dont see the necessity creating files post install, why not create it when actually needed in runtime?

**Comment by frostming** [comment]
the build hook can't create files beyond the wheel zipball, which is considered insecure. You can use pdm's post_install script to do that, but it will be executed after the whole install, not individual packages

**Comment by lyz-code** [comment]
> why not create it when actually needed in runtime?

For two reasons:

- The package is not ever called by the user directly. It is a plugin of another program (`pass`) and those files that I'm creating are what will be used to instantiate it. For example, in my package you can run `pass_collaborate group list`, and at that point I could check if the files exist and then create them if they don't. Users won't use this command, they will use `pass group list`, which behind the scenes calls the previous command. Basically, if the install process doesn't do it automatically, I need the users to copy those files manually as part of the installation process.

- Doing the checks if the files exist on every command run is not needed and will worsen the program performance

I'm going to try with the `post_install` script, thanks

**Comment by frostming** [comment]
note that the post_install script only works with the current project because it is called by pdm install. if the users use other installers that won't work. and you can't make it work if it is defined in the dependencies pyproject.toml

so i still think runtime creation may be the best. you can make it run, when the package is imported so it will work smoothly in a plugin, the performance is of course affected but i dont think it's a big deal.

**Comment by lyz-code** [comment]
Got it, thanks as always for your helpful feedback <3
