### ISSUE TITLE
Update to 2.5.0b is not succeeding on windows 10

### ISSUE THREAD

**Issue by cvgaviao** [pdm-project/pdm#1816]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

On Windows 10 with python 3.9.13
```
C:\Users\cristianoga\my-project>pdm -v self update
Installing version 2.5.0b0 succeeds.

PDM 2.4.9 is installed, while 2.5.0b0 is available.
Please run `pdm self update` to upgrade.
Run `pdm config check_update false` to disable the check.
```
## Actual behavior

I just tried the command `pdm -v self update` and it was not updated.

## Expected behavior

I've expected that when the `pdm info` command was issued after the update I would see 2.5.0b instead 2.4.9

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.4.9     
Python Interpreter:
  C:\Users\cristianoga\AppData\Local\Programs\Python\Python39\python.EXE (3.9)
Project Root:
  C:/Users/cristianoga/git-code/my-project
Project Packages:
  C:\Users\cristianoga\git-code\my-project\__pypackages__\3.9

PDM 2.4.9 is installed, while 2.5.0b0 is available.
Please run `pdm self update` to upgrade.
Run `pdm config check_update false` to disable the check.
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.13",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19044",
  "python_full_version": "3.9.13",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "win32"
}

PDM 2.4.9 is installed, while 2.5.0b0 is available.
Please run `pdm self update` to upgrade.
Run `pdm config check_update false` to disable the check.
```

**Comment by cvgaviao** [comment]
@frostming, nope it doesn't.

I have those dependencies in the project:
```
dependencies = [
    "scipy~=1.9",
    "hypothesis~=6.70",
    "click~=8.1",
    "pandas~=2.0",
    "numpy~=1.24",
]
```

**Comment by cvgaviao** [comment]
@yodaldevoid , I do not used that flag. I just followed the message that is being showed when I install the project. 
```
PDM 2.4.9 is installed, while 2.5.0b0 is available.
Please run `pdm self update` to upgrade.
Run `pdm config check_update false` to disable the check.
```

**Comment by yodaldevoid** [comment]
> @yodaldevoid , I didn't use that flag. I just followed the message that is being showed when I install the project.
> 
> ```
> PDM 2.4.9 is installed, while 2.5.0b0 is available.
> Please run `pdm self update` to upgrade.
> Run `pdm config check_update false` to disable the check.
> ```

I think the issue here is not that the update didn't work but that `pdm` is suggesting a prerelease update.

Based on the [release page](https://github.com/pdm-project/pdm/releases/tag/2.5.0b0) 2.5.0b0 is a prerelease so you need to run `pdm self update --pre` to update to it. Either `pdm` needs to add `--pre` to the suggested update command when dealing with a prerelease, or it shouldn't suggest the update to a prerelease in the first place.

For what it is worth, I was able to update to 2.5.0b0 on Windows 10 without issue by following the instructions on the release page.
