### ISSUE TITLE
Disable Upgrade Prompts for Pre-Release Versions

### ISSUE THREAD

**Issue by Xdynix** [pdm-project/pdm#1821]
## Is your feature request related to a problem? Please describe.

Every time I open a new terminal I see the following prompt (I have PDM's autocompletion enabled):

```
PDM 2.4.9 is installed, while 2.5.0b0 is available.
Please run `pdm self update` to upgrade.
Run `pdm config check_update false` to disable the check.
```

I want to automatically check for updates, but only to stable releases.

## Describe the solution you'd like

There can be a new option for configuration `check_update`: `stable_only`. Or we can have a new configuration: `beta_release = false`.

**Comment by frostming** [comment]
We are not going to make the config too complicated. This small feature is not worth having two configuration options. Just hide them all or see them all.
