### ISSUE TITLE
invalid dynamic version based on git tag

### ISSUE THREAD

**Issue by houbie** [pdm-project/pdm#1832]
When my github workflow tries to publish to pypi, I get an error `Client Error: '1.0.0b3+d20230412' is an invalid value for Version`.
It seems that the date is appended to the tag, making the final version invalid.

In pyproject.toml:
```
[project]
dynamic = ["version", ]
[tool.pdm.version]
source = "scm"
```

I could not find documentation on how to use `source = "scm"` (the [dynamic-versioning](https://pdm.fming.dev/latest/reference/build/#dynamic-versioning) in the docs shows the _Build Configuration_ section without additional info on dynamic version)

**Comment by frostming** [comment]
The `+d20230412` part is appended since there is uncommited changes, please clean your working directory before publish

**Comment by frostming** [comment]
The documentation references to the specific backend, depending on what you use, and it is related to the backend, not PDM. Closing it now.
