### ISSUE TITLE
Avoiding duplicate index config in pip and unearth/pdm

### ISSUE THREAD

**Issue by inigohidalgo** [pdm-project/pdm#1845]
Hello,

I am going to be introducing PDM at work to start managing our projects, and I'm trying to figure out a workflow with as few frictions as possible when setting up PDM. Thanks to the introduction of different dependencies in different groups in the lockfile PDM is already 100% ready for us to use day-to-day. There is one source of friction I am trying to overcome: **duplicated index config for pip and pdm**.

The reason for this is that we spend some time developing production code, but we also spend a lot of time performing analysis in notebooks. I have been able to define a workflow which works well, using PDM to manage projects and their virtual environments, and then using pip to install ad-hoc packages into more general-use system-wide environments (conda usually).

We publish our packages to a private index (hosted on Azure) and we then install those into either deployments or local environments for analysis. I have been trying to find a config setup which avoids declaring indices (and user-pwd) in multiple places where possible.

Pip can either be configured through a pip.ini/pip.conf config key, or a `PIP_INDEX_URL=` environment variable. I understand the reasoning behind keeping the configs segregated, as unearth and pip are different programs, so I was looking for a simple way to refer to the PIP_INDEX_URL config. I have tried setting up

```
[pypi]
url = "${PIP_INDEX_URL}"
```

It fails with this error message `unearth.session: Skipping ${PIP_INDEX_URL}/pdm-pep517/ for not being trusted, please add it to `trusted_hosts` list`. I assume that's because the environment variable isn't being expanded as expected, since when I define the url explicitly in config.toml it works, without referencing that trusted_hosts issue. I've seen references to expanding environment variables throughout PDM documentation, but it's usually related to credentials, not as a general feature, is this the case? If it's intentionally limited, is there a reason for this? 

`url=https://${user}:${token}@pkgs.dev.azure.com/.../pypi/simple/` works as expected, but unfortunately pip doesn't support environment variable expansion at all, so my options are to set the full `user:token@url` in `pip.ini` or in PIP_INDEX_URL, so the only option I have to get that within PDM is to expand the full url as I listed above.

It isn't the end of the world, because I've been able to set up something that works with the `keyring` but it isn't ideal since it slows down the resolving process, or I can just duplicate the config, not like it's a lot, but I was wondering if you have any ideas.

Thanks

**Comment by frostming** [comment]
Pip has a complex cascaded config structure, since PDM has stripped out pip as a dependency, it will not be a small change to support it. Nevertheless, this use case still makes some sense and IMO it would be a good fit for a plugin.

**Comment by inigohidalgo** [comment]
Yeah I totally understand, and don't expect to support reading pip.ini config, since that is complex, and for the most part unrelated. I was more asking about the environment variable expansion. Currently expanding username and password in environment variables works, but it's not possible to have the whole index url as an environment variable. I was wondering what the reason was for that distinction.

**Comment by frostming** [comment]
I don't see setting env `PDM_PYPI_URL` is harder than `PIP_INDEX_URL`

**Comment by inigohidalgo** [comment]
It isn't, but it does require 2 different environment variables, whereas if I could reference PIP_INDEX_URL in the pdm config, it would be managed the same, so we would avoid having to refresh tokens in 2 different environment variables when the actual connection is to the same index. But I agree it's not a big deal, I was wondering if there's a reason why we expand credential environment variables and not any arbitrary environment variable in PDM config. Is it related to the locking mechanism? If it's limited by functionality from the resolver, I would just close the issue, but if it's not a limiting factor, maybe I can contribute the expanding functionality, either through an external plugin or a PR, whatever you think makes most sense.

**Comment by inigohidalgo** [comment]
Ended up just going for duplicating the url index environment variable.

Thanks for your amazing work :)
