### ISSUE TITLE
(windows) `pdm use` failed if PATH env contains folder with restricted access

### ISSUE THREAD

**Issue by MVKozlov** [pdm-project/pdm#1849]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

- create empty folder D:\restrictedFolder
- restrict access to folder for current user (for example set access rights for Administrators only)
- add folder to PATH environment variable
- open new shell in project folder and try to `pdm use`

## Actual behavior

<details><summary>[PermissionError]: [WinError 5] Access Denied D:\restrictedFolder</summary>
<p>

> Traceback (most recent call last):
>   File "c:\python\python310\lib\runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "c:\python\python310\lib\runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "c:\python\python310\scripts\pdm.exe\__main__.py", line 7, in <module>
>   File "c:\python\python310\lib\site-packages\pdm\core.py", line 255, in main
>     return Core().main(args)
>   File "c:\python\python310\lib\site-packages\pdm\core.py", line 193, in main
>     raise cast(Exception, err).with_traceback(traceback) from None
>   File "c:\python\python310\lib\site-packages\pdm\core.py", line 188, in main
>     self.handle(project, options)
>   File "c:\python\python310\lib\site-packages\pdm\core.py", line 154, in handle
>     command.handle(project, options)
>   File "c:\python\python310\lib\site-packages\pdm\cli\commands\use.py", line 31, in handle
>     actions.do_use(
>   File "c:\python\python310\lib\site-packages\pdm\cli\actions.py", line 617, in do_use
>     found_interpreters = list(dict.fromkeys(project.find_interpreters(python)))
>   File "c:\python\python310\lib\site-packages\pdm\project\core.py", line 664, in find_interpreters
>     for entry in finder.find_all(*args):
>   File "c:\python\python310\lib\site-packages\findpython\finder.py", line 103, in find_all
>     matched_python = set(self._find_all_python_versions())
>   File "c:\python\python310\lib\site-packages\findpython\finder.py", line 136, in _find_all_python_versions
>     yield from provider.find_pythons()
>   File "c:\python\python310\lib\site-packages\findpython\providers\path.py", line 25, in find_pythons
>     yield from self.find_pythons_from_path(path)
>   File "c:\python\python310\lib\site-packages\findpython\providers\base.py", line 44, in <genexpr>
>     return (
>   File "c:\python\python310\lib\pathlib.py", line 1017, in iterdir
>     for name in self._accessor.listdir(self):
> 

</p>
</details> 

## Expected behavior

Interactive python selection. (may be with warning)
note: Everything works as it should when the shell is started with administrator rights.

## Environment Information

```bash
> pdm info
PDM version:
  2.5.3
Python Interpreter:
  D:\Work\test\.venv\Scripts\python.exe (3.10)
Project Root:
  D:/Work/test

> pdm info --env
Local Packages:
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.9",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19043",
  "python_full_version": "3.10.9",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "win32"
}```

**Comment by frostming** [comment]
You need to upgrade the version of `findpython` inside the environment of PDM.

**Comment by MVKozlov** [comment]
@frostming, my `findpython` version is 0.2.4 - the latest, at the time of report and now
