### ISSUE TITLE
pdm install now always installs optional dependencies? (extras)

### ISSUE THREAD

**Issue by pawamoy** [pdm-project/pdm#1863]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

`pdm install` with optional dependencies specified in pyproject.toml.

## Actual behavior

PDM installs all optional dependencies, while it didn't before.

## Expected behavior

I expect PDM not to install optional dependencies (extras) without me explicitly asking for it (with `-G :all` or `-G myextra`), since there's no way to explicitly exclude them.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.5.3
Python Interpreter:
  /home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.11.0/bin/python3 (3.11)
Project Root:
  /media/data/dev/mkdocstrings
Local Packages:
  /media/data/dev/mkdocstrings/__pypackages__/3.11
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.0",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.2.12-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Thu, 20 Apr 2023 16:11:55 +0000",
  "python_full_version": "3.11.0",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}
```

**Comment by pawamoy** [comment]
By the way `pdm lock` will not include optional dependencies in the lock file, so `pdm lock` then `pdm install` will fail.

An alternative would be to add a `--no-optional` flag to `pdm install` (and maybe to `pdm lock` as well).

So my conclusion is that we should have the following behavior:

- `pdm lock`: lock everything
- `pdm lock -G ...`: lock only the given groups
- `pdm install`: install everything
- `pdm install -G ...`: install only these groups
- `pdm install --no-optional`: install everything except optional deps (extras)

**Comment by frostming** [comment]
More such options will add to the confusion. I will just revert this behavior so that users can choose to include the optional groups. But in the future, we would like to change the options to `--with/--without` to be more orthogonal.

**Comment by pawamoy** [comment]
I understand, reverting to the previous behavior sounds good to me :slightly_smiling_face: 

> But in the future, we would like to change the options to --with/--without to be more orthogonal.

Orthogonal to Poetry :smile:? This was [the initial proposal](https://github.com/python-poetry/poetry/issues/1644) I made there indeed haha, funny. Yeah the `--with` and `--without` syntax is nice I think. Would groups be a comma-separated list, like `--with group1,group2`?

**Comment by frostming** [comment]
> so `pdm lock` then `pdm install` will fail.

This isn't the case at least from my observation, if no options are given to `pdm install`, what are locked in the lockfile will be installed without error.

**Comment by pawamoy** [comment]
Yeah I think my lock file contained all groups. I thought `pdm lock` overwrites it each time it is run, but it seems it reuses its contents instead. My bad.

**Comment by frostming** [comment]
The behavior change here, is when you doesn't give any dependency selection option, PDM will install what is locked in the lockfile.

There is a way to not install the optional dependencies though: `pdm install -d`. I am going to close it now.

**Comment by AndrewLaptev** [comment]
@frostming
Hi! Are you planning to eventually return to the old `pdm install` behavior when optional dependencies are not installed by default? In `pdm` 2.7.0, optional dependencies are still installed by default

**Comment by frostming** [comment]
> although the documentation [says the opposite](https://pdm.fming.dev/latest/usage/dependency/#select-a-subset-of-dependency-groups-to-be-installed-or-locked)

The docs need update.

Yeah when no options are given, all locked groups will be installed. You can pass some flags to select or unselect some groups.
