### ISSUE TITLE
Problem with the home page in Edge

### ISSUE THREAD

**Issue by jabbalaci** [pdm-project/pdm#1867]
Visiting https://pdm.fming.dev/latest/ in Edge (under Linux) behaves strangely: the page appears, but after a second the page disappears and the following error is shown: https://i.imgur.com/2jVyUsp.png

I tried with Firefox too (under Linux) and the page loads normally.

**Comment by frostming** [comment]
We won't look into such problems since it is beyond our responsibility.

**Comment by jabbalaci** [comment]
It should be investigated. Why does it happen? I don't experience it with other sites.

**Comment by frostming** [comment]
> It should be investigated. Why does it happen? I don't experience it with other sites.

Yeah that's right, but PDM is almost maintained by myself alone, I have to put my efforts in fixing bugs, features. and i don't use edge. Don't ask another person to work for you for free, but if you can investigate and find the root cause i will be happy to merge.

**Comment by jabbalaci** [comment]
It would be nice to get feedback from other users too if they have this issue or not. Until then, this ticket should not be closed since it's not resolved.

**Comment by jabbalaci** [comment]
It works now under Linux with Edge. Maybe it was an Edge issue that got resolved with an update.
