### ISSUE TITLE
PyPI Trusted Publisher Support

### ISSUE THREAD

**Issue by BlueGlassBlock** [pdm-project/pdm#1868]
PyPI announced the [Trusted Publishers](https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/) feature some days ago. Would be nice to see in `pdm publish`.

I already saw [maturin](https://github.com/pyo3/maturin) support this in [this PR](https://github.com/PyO3/maturin/pull/1578).

For technical reference, [PyPI Docs](https://docs.pypi.org/trusted-publishers/using-a-publisher/#the-manual-way) basically has all the details.

**Comment by e10v** [comment]
I've just tried to use this feature and failed.
I'm using pdm-project/setup-pdm@v3 to install the latest version of PDM. I made sure it installed the latest version (2.6.0).
But calling `pdm publish` (in github action) returns an error: "[PdmUsageError]: Username and password are required".
Are there any command line options or environment variables I shoud use.?

**Comment by frostming** [comment]
@e10v Did you see the output: `Failed to get PyPI token via GitHub Actions OIDC`?

Please follow these steps to set up publishers
https://pdm.fming.dev/latest/usage/publish/#publish-with-trusted-publishers

**Comment by e10v** [comment]
> Did you see the output: Failed to get PyPI token via GitHub Actions OIDC?

No I didn't see this message. But I didn't set up "permissions: id-token: write". I will try with next release. Thank you for quick replay and sorry for bothering 🙏

**Comment by e10v** [comment]
@frostming I've just tried again. And now I'm getting the following error:
```
Traceback (most recent call last):
  File "/home/runner/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 268, in main
    return Core().main(args)
  File "/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 192, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 187, in main
    self.handle(project, options)
  File "/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 153, in handle
    command.handle(project, options)
  File "/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/cli/commands/publish/__init__.py", line 133, in handle
    repository = self.get_repository(project, options)
  File "/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/cli/commands/publish/__init__.py", line 120, in get_repository
    return Repository(project, config.url, config.username, config.password, config.ca_certs)
  File "/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/cli/commands/publish/repository.py", line 37, in __init__
    username, password = self._ensure_credentials(username, password)
  File "/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/cli/commands/publish/repository.py", line 48, in _ensure_credentials
    token = self._get_pypi_token_via_oidc()
  File "/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/cli/commands/publish/repository.py", line 63, in _get_pypi_token_via_oidc
    self.ui.echo("Getting PyPI token via GitHub Actions OIDC...")
AttributeError: 'Repository' object has no attribute 'ui'
Error: Process completed with exit code 1.
```

**Comment by BlueGlassBlock** [comment]
https://github.com/pdm-project/pdm/blob/b5db072afac42005779c9c162110946da03824c5/src/pdm/cli/commands/publish/repository.py#L23-L40

https://github.com/pdm-project/pdm/blob/b5db072afac42005779c9c162110946da03824c5/src/pdm/cli/commands/publish/repository.py#L40

should move to be the first in `__init__`.

**Comment by frostming** [comment]
@e10v Try the head version:

```yaml
- uses: pdm-project/setup-pdm@v3
  with:
    version: 'head'
```

**Comment by frostming** [comment]
Tested with 2.6.1 and it succeeded.
![image](https://github.com/pdm-project/pdm/assets/16336606/c0739e72-8dce-4678-ada7-cecd77cd4c63)

**Comment by drunkwcodes** [comment]
https://github.com/drunkwcodes/bb7/actions/runs/10659567911/job/29542289097#step:4:26

I failed to get PyPI token via GitHub Actions OIDC, please help.

**Comment by frostming** [comment]
> https://github.com/drunkwcodes/bb7/actions/runs/10659567911/job/29542289097#step:4:26
> 
> I failed to get PyPI token via GitHub Actions OIDC, please help.

Make sure the publisher is configured correctly on PyPI:

![image](https://github.com/user-attachments/assets/3b858781-6d3b-434c-b1a4-ed648f2e2a51)

**Comment by drunkwcodes** [comment]
I did configured the publisher on PYPI. But the result is still in vain.

![螢幕快照 2024-09-04 22-23-06](https://github.com/user-attachments/assets/a2397565-bbe4-4b98-bffa-d88e5212ee37)

**Comment by frostming** [comment]
you haven't set environment name in your action workflow so you should leave that empty

**Comment by drunkwcodes** [comment]
The [test release passed.]( https://github.com/drunkwcodes/bb7/actions/runs/10706469322)

Thanks a lot!
