### ISSUE TITLE
Typo in document docs/docs/usage/scripts.md

### ISSUE THREAD

**Issue by ProFatXuanAll** [pdm-project/pdm#1870]
https://github.com/pdm-project/pdm/blob/8b1da395aa7e1003252fc01fa997584667e25b94/docs/docs/usage/scripts.md?plain=1#L298

I believe that it should be `post_run` instead of `post_script`.

**Comment by frostming** [comment]
Definitely. Interested in sending a PR?

**Comment by ProFatXuanAll** [comment]
Will do it in an hour or two.
