### ISSUE TITLE
Automatically remove empty optional dependency groups

### ISSUE THREAD

**Issue by twhentschel** [pdm-project/pdm#1873]
When I remove all the dependencies from an (optional) dependency group, the empty group itself stays in the pyproject.toml file. For example, I added pysocks with `pdm add -G socks pysocks`, and then removed it with `pdm remove -G socks pysocks`. The resulting .toml file is: 
```
[tool.pdm]

[project]
name = "my-pdm-project"

...

[project.optional-dependencies]
socks = [
]
```

## Describe the solution you'd like

I think it would be neat if pdm would automatically remove the empty group once all the dependencies are removed. The alternative is to remove this part from the .toml file by hand, which is also not a big deal.

edit: actually, it doesn't look like removing the group from the .toml file by hand is sufficient - the group is still included in the metadata section in the pdm.lock file, which looks like it should not be edited by hand.

**Comment by frostming** [comment]
You may need to check the main branch, it has been fixed by https://github.com/pdm-project/pdm/pull/1862/files#diff-11cc4644bc62634ec6d6a6ae50ae92449288dd9dc07fd6ef2316f2120cdfa340
