### ISSUE TITLE
PDM is incompatible with urllib3 v2

### ISSUE THREAD

**Issue by adriangb** [pdm-project/pdm#1880]
It seems like PDM will crash if run with urllib3 >= 2: https://github.com/pydantic/pydantic/actions/runs/4874441733/jobs/8695375959#step:4:20

Manually doing `pip install urllib<2` fixes it for me.

**Comment by Roger-luo** [comment]
see #1879 it seems due to cache control

**Comment by adriangb** [comment]
Thanks it was hard to determine the cause
