### ISSUE TITLE
make pip install reproducible by publishing dependencies from lock file

### ISSUE THREAD

**Issue by houbie** [pdm-project/pdm#1888]
## Is your feature request related to a problem? Please describe.

#1883 showed that published versions of PDM (or any other python tool) can suddenly break because of a release of a dependency.
Despite the usage of lock files, we publish loose dependency constraints to pypi. This makes sense for libraries, but not for standalone tools where reliability over time is important.

## Describe the solution you'd like

A config option `tool.pdm.publish-locked-dependencies`, resulting in listing locked versions in the distributions' METADATA, would make pip installs reproducible.

**Comment by sigma67** [comment]
@frostming is this something you would accept a MR for?

**Comment by frostming** [comment]
@sigma67 certainly, appreciate that. But since the locked dependencies lose the environment markers, which isn't easy to overcome.

**Comment by sigma67** [comment]
I would be willing to tackle this. Could you assign and provide some pointers for getting started?

**Comment by sigma67** [comment]
So I had a look at the code and came up with a basic implementation plan.

pdm
-------------------

``build.py:do-build()``

  - if ``project.pyproject.settings.get("publish-locked-dependencies")`` is set only, do the following
  - modify `config_settings` to add an extra key `locked-dependencies`, which maps to a List[Dict[str,str]] of locked dependencies. Locked dependencies are retrieved from project.lockedrepository.candidate_info

add appropriate test

pdm-backend
-------------------
``wheel.py:_fix_dependencies``
- based on `self.config_settings`, determine if `locked_dependencies` exist
- if so, use the data within to create another `optional-dependencies` group named `locked`, which contains the same dependencies as `metadata['dependencies']`, but locked to the versions contained in `self.config_settings['locked_dependencies']`

add appropriate test

Do you agree with this proposal? Any suggestions?

**Comment by sigma67** [comment]
I was made aware that this is likely in conflict with PEP-621. 

Instead we are now considering implementing a PDM plugin to build a separate, locked version of the project. 

The command could look like ``pdm build --locked`` to build a modified version of `mypkg`, for example called `mypkg-locked`, which includes `mypkg` and all its dependencies & optional-dependencies pinned to the version specified in `pdm.lock`.

**Comment by frostming** [comment]
You shouldn't rely on PDM and all changes should happen in `pdm-backend`

**Comment by sigma67** [comment]
As I mentioned above, I don't think we can achieve this in `pdm-backend` due to `PEP621`. Build backends cannot modify dependency data specified statically when creating core metadata. The only way to achieve locked dependencies then would be to mark dependencies and optional-dependencies dynamic and specify them somewhere in `tool.pdm`, which is probably not what we want.

**Comment by sigma67** [comment]
We have a working plugin internally, if there is any interest from the community we can work towards publishing it.

**Comment by houbie** [comment]
Super!
I would use it for sure and hope that PDM itself will use it.
Unless there is another way to make sure that future installs of PDM can't be broken anymore by downstream dependencies like in #1883

**Comment by sigma67** [comment]
Here it is: https://github.com/sigma67/pdm-build-locked

**Comment by sigma67** [comment]
This would be a topic for @frostming to consider. I'm not sure if the recursion is a problem

**Comment by frostming** [comment]
It's not necessary, publishing the versions from lock file is only needed if you want to publish an application (CLI or web) to pypi, and it's convenient enough to just add a pdm-build-locked dependency

**Comment by sigma67** [comment]
Exactly, pdm is a CLI application that is being published to pypi?

**Comment by pawamoy** [comment]
PDM is both a CLI and library. Users depending on it as a library really do not want the locked dependencies. Generally speaking, any *package* (for example published to PyPI) should *not* pin dependencies, because any package (whether it advertise itself as a CLI tool, a library, an app, whatever) can be used as a library.

**Comment by sigma67** [comment]
> Let me check how pdm-build-locked works though. If it only adds a locked optional extra, this might work for PDM

Exactly, that's how it works. 

We use it extensively internally for tools that target both library and CLI use cases. 

The user decides how to install - 

`pipx install pdm[locked]`

installs pinned dependencies. Nothing changes for the regular case 

`pipx install pdm`

Existing optional dependency groups are duplicated as pinned and postfixed with `-locked`

**Comment by pawamoy** [comment]
OK, that's quite cool, amazing job @sigma67 :smile: I could see such a mechanism become a standard recommendation for when users install packages in isolated venvs, to be used as tools only (typically, with `pipx`).

**Comment by frostming** [comment]
@sigma67 can you help make the changes in a PR? Thanks
