### ISSUE TITLE
[Feature Request] Publishing - authenticating to PyPI with API token

### ISSUE THREAD

**Issue by tddschn** [pdm-project/pdm#1891]
## Is your feature request related to a problem? Please describe.

In the near future, PyPI will begin prohibiting uploads using basic authentication for accounts with two-factor authentication enabled. 

I got the following email shortly after publishing a package with `pdm publish -u <username> -P <pw>`:

<img width="693" alt="CleanShot-2023-05-06T11-51-10@2x Redacted" src="https://user-images.githubusercontent.com/45612704/236598274-2592f82c-91c5-4fd5-811c-658a21a67f9f.png">

## Describe the solution you'd like

Add support for authenticating PyPI with API Token in relavent pdm commands, such as `publish`.

**Comment by frostming** [comment]
Use `__token__` as the username and API token as the password

**Comment by tddschn** [comment]
Thank you for answering my question!

I remember using `__token__` as username somewhere before, but `pdm publish --help` doesn't include this tip and I was under the false impression that pdm doesn't support authenticating using token.

```
pdm publish --help

...
  -u USERNAME, --username USERNAME
                        The username to access the repository [env var: PDM_PUBLISH_USERNAME]
  -P PASSWORD, --password PASSWORD
                        The password to access the repository [env var: PDM_PUBLISH_PASSWORD]
...
```

I think it would be be helpful to include the `__token__` tip in the command line help usage, would you consider adding it?
