### ISSUE TITLE
Uninstall the installed project library

### ISSUE THREAD

**Issue by SunilMallireddy** [pdm-project/pdm#1901]
## Is your feature request related to a problem? Please describe.

I am having trouble uninstalling an installable library I created using a pyproject.toml file and the pdm install command, as there is no available command to remove the project itself.

## Describe the solution you'd like

 I would like PDM to provide an option to uninstall the installable library that was previously installed.

Please find the following discussion for additional details:

https://github.com/pdm-project/pdm/discussions/1892#discussioncomment-5825001

**Comment by SunilMallireddy** [comment]
@frostming  what is the command to uninstall the package?  I tried `pdm remove package` but its not working

**Comment by frostming** [comment]
@SunilMallireddy `pdm sync --no-self --clean`

**Comment by TiansuYu** [comment]
... Why this is not well documented, and why inventing another set of commands, there are already enough to remember after `pip`, `pipenv` and `poetry`.

**Comment by TiansuYu** [comment]
This breaks my base conda environment... Now my `conda env info` returns `/xxx/anaconda/bin/conda No such file or directory`

**Comment by hitesh-pathak** [comment]
This removes all packages installed using `conda` in the environment. While there is a `pdm remove <package>` for dependencies, I can't find anything to remove project library that is installed in editable mode

using `pdm remove <project-library-name>` simply errors out as it's not in dependencies. Is there something trivial that I'm missing..?

**Comment by ixenion** [comment]
Also wondering Is there something to remove project library?
