### ISSUE TITLE
Allow multiple lockfiles targeting different platforms

### ISSUE THREAD

**Issue by oyarsa** [pdm-project/pdm#1911]
Now that we have #1898, it could be interesting to have platform-specific lockfiles, each generated by something like `--no-cross-platform`. 

My primary use case for this is `pytorch`: ideally, you would get different results depending on your platform: the CUDA version on Linux and the MPS version on macOS. As it stands, I'm getting the CPU version on Linux if I use the lockfile generated on macOS.

My current solution is not to commit the lockfile and let PDM figure it out every time I do a `pdm install`. Instead, if we have multiple lockfiles, I could generate specific ones for each platform I support.

The UX for this could be something like this:
- Manual: new flag `--lockfile <file>` that creates a lockfile in path `file` if it doesn't exist or uses it to install dependencies. This would be required for every `pdm install`. 
- Supply once, use it always: `pdm install` needs the argument once per instance, but after that, you don't need to specify it anymore
- Automated: when using `--no-cross-platform`, the lockfile generated encodes the platform in its name, and `pdm install` would automatically use that if it exists, prioritising it over other lockfiles.

**Comment by frostming** [comment]
Resolved by #2995
