### ISSUE TITLE
Lock file hash never matches with --dev

### ISSUE THREAD

**Issue by pawamoy** [pdm-project/pdm#1916]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

Following discussions in https://github.com/pdm-project/pdm/issues/1863 and https://github.com/pdm-project/pdm/discussions/1909, I lock deps with `pdm lock --dev`, and every time I install them with `pdm install --dev`, it says that the "Lock file hash doesn't match pyproject.toml, packages may be outdated", and proceeds to update the lock file. I diff'ed the lock file before and after: no changes.

## Steps to reproduce

You can try it within my project:

```bash
git clone https://github.com/mkdocstrings/mkdocstrings
cd mkdocstrings
pdm lock -d
pdm install -d  # says hash doesn't match
pdm install -d  # still says it
```

Note that my project has optional dependencies (extras).

## Actual behavior

PDM says that the lock file hash doesn't match pyproject.toml, and updates the lock file each time I run `pdm install -d`, however after that the lock file is identical. So the hash "never matches". Not sure the hash actually doesn't match.

## Expected behavior

Locking with `-d` then installing with `-d` shouldn't trigger lock file updates. The hash should match.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.6.1
Python Interpreter:
  /home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.11.0/bin/python3 (3.11)
Project Root:
  /media/data/dev/mkdocstrings
Local Packages:
  /media/data/dev/mkdocstrings/__pypackages__/3.11
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.0",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.3.1-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Mon, 01 May 2023 17:42:39 +0000",
  "python_full_version": "3.11.0",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
Can you help fix it? This one should be obvious.
