### ISSUE TITLE
Tests fail due to wrong Python interpreter (auto-)selection

### ISSUE THREAD

**Issue by falbrechtskirchinger** [pdm-project/pdm#1917]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

When running the test suite on my Gentoo system using `python3.11 -m pytest ...`, some tests fail with two types of errors:
1) a version mismatch, e.g. `'3.10' != '3.11'`
2) a failure to resolve certain packages (typically either wheel or setuptools)

Both errors can be traced back to `.pdm-python` pointing to `/usr/bin/python3.10` when `/usr/bin/python3.11` is expected.

Per the documentation, I've set `PDM_PYTHON` to `/usr/bin/python3.11`. The failing tests do pass, but unfortunately, different tests start failing. For example, `tests/test_project.py::test_project_use_venv`.

Modifying the test to delete the environment variable via `monkeypatch.delenv("PDM_PYTHON", raising=False)` does work as expected, but I'm unsure whether that's the best solution.

**Is there an alternative way to solve my initial problem?**
**If not, is adding `monkeypatch.delenv(...)` to all relevant tests acceptable?**

Please advise and I'd be happy to submit a PR.

## Environment Information

```bash
$ pdm info && pdm info --env
PDM version:
  0.1.dev2266+g43b5f30.editable
Python Interpreter:
  /home/flo/projects/pdm/fix-resource-warnings/.venv/bin/python (3.11)
Project Root:
  /home/flo/projects/pdm/fix-resource-warnings
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.3",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.1.19-gentoo-x86_64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Fri Apr  7 15:58:57 CEST 2023",
  "python_full_version": "3.11.3",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}
```

**Comment by falbrechtskirchinger** [comment]
@frostming Could you please comment on this? I was able to work around this issue in the Gentoo ebuild [1] test code but would prefer to remove the workaround ASAP to reduce the maintenance burden on whoever will eventually take over for me. Thank you!

[1]: It's in GURU for any Gentoo users reading.

**Comment by frostming** [comment]
Setting `PDM_PYTHON` just doesn't work because the test suite relies on that for some cases.
Can you point me to what cases are failing?

**Comment by falbrechtskirchinger** [comment]
My Python environment has changed since, and I'm once again unable to reproduce the issue, but you can find identical failures in this bug report: https://bugs.gentoo.org/902885#c2

Those are the same tests that failed when I opened this issue. Same `AssertionError`, different Python versions, though.

<hr />

As for the tests that fail with `PDM_PYTHON` set, here's the list as of 2.5.1, I believe:
```
tests/cli/test_add.py::test_add_editable_package
tests/cli/test_add.py::test_non_editable_override_editable
tests/cli/test_list.py::test_list_csv_include_exclude
tests/cli/test_list.py::test_list_csv_include_exclude_valid
tests/cli/test_list.py::test_list_dependency_graph_include_exclude
tests/test_project.py::test_project_packages_path
tests/cli/test_init.py::test_init_non_interactive
tests/cli/test_remove.py::test_remove_editable_packages_while_keeping_normal
tests/cli/test_venv.py::test_conda_backend_create
tests/models/test_backends.py::test_project_backend
```

Taken from here: https://github.com/gentoo/guru/blob/e3a9f5ef2abf6fe5599d64f4c3a384de958b1332/dev-python/pdm/pdm-2.6.1.ebuild#L67-L76

**Comment by frostming** [comment]
It's true that some cases rely on the auto-selection whose result may highly depend on the current environment it is running on. But I personally don't have the energy to keep it consistent in arbitrary environment it will be run on. I hope you to understand that.

**Comment by falbrechtskirchinger** [comment]
Well, running the tests in a different environment from the installation environment kind of defeats the purpose. So, I guess we'll have to keep the workaround in place for now.

Can you point me to where in the code this auto-selection happens? Maybe there's something to be done there.

**Comment by falbrechtskirchinger** [comment]
> @falbrechtskirchinger
> 
> https://github.com/pdm-project/pdm/blob/4618fc8445df1a854565d98ddf4e54771c934e9b/src/pdm/project/core.py#L186

Thank you!

Unfortunately, injecting debug statements into the package build environment is rather tedious. It has taken me a couple of hours of hunting down red herrings to arrive at the rather mundane solution of simply deleting `.pfm-python` between test runs.
All tests (minus those marked "network") pass now!
