### ISSUE TITLE
Existing PDM installation on PYTHONPATH breaks `install-pdm.py`

### ISSUE THREAD

**Issue by dranjan** [pdm-project/pdm#1920]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

I'm not sure if this would be considered a bug or "user error," but specifically if there's an old PDM installation on PYTHONPATH, then `install-pdm.py` will fail to install a second one. I encountered this error because in my org we're migrating from `pip install` to the recommended installation method, and someone ran it with a stale environment from our previous setup.

## Steps to reproduce

```bash
#!/usr/bin/env bash

set -euxo pipefail

unset PYTHONPATH

python install-pdm.py --path build/root1

export PYTHONPATH=build/root1/venv/lib/python3.8/site-packages

python install-pdm.py --path build/root2
```

## Actual behavior

The first PDM is installed successfully, but the second one is not:

```
+ python install-pdm.py --path build/root2
Installing PDM (2.6.1): Creating virtual environment
Installing PDM (2.6.1): Installing PDM and dependencies
Installing PDM (2.6.1): Making binary at /home/darsh/work/pdm-install-bug/build/root2/bin
Traceback (most recent call last):
  File "install-pdm.py", line 453, in <module>
    main()
  File "install-pdm.py", line 449, in main
    installer.install()
  File "install-pdm.py", line 366, in install
    self._post_install(venv, bin_dir)
  File "install-pdm.py", line 336, in _post_install
    subprocess.check_call([str(script), "--help"])
  File "/usr/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/darsh/work/pdm-install-bug/build/root2/bin/pdm'
```
I think PDM simply inherits this behavior from `pip`, which can see the first installation through PYTHONPATH and decides not to install another identical one.

## Expected behavior

Two PDM installations are created in the two directories.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

(This occurs before PDM itself is installed.)

```

**Comment by frostming** [comment]
> if there's an old PDM installation on PYTHONPATH,

This is a very strange step, sounds like you are deliberately testing odd cases to break the script. Why do you need to set that env value, to an isolated installation of a tool?

**Comment by dranjan** [comment]
> This is a very strange step, sounds like you are deliberately testing odd cases to break the script.

Ha ha, I'm probably not creative enough to come up with this one.

Now that I look more closely, it was a very strange setup that triggered this: someone had PDM installed in `~/.local`, and they also had their user-site directory on PYTHONPATH for some reason. In any case, though, since the install script has zero third-party dependencies that I can see, I thought it might be unintended for PYTHONPATH to affect the behavior of the script at all.

**Comment by frostming** [comment]
> I thought it might be unintended for PYTHONPATH to affect the behavior of the script at all.

It does affect `pip install` so it affects the script, too.

**Comment by dranjan** [comment]
Thinking about it more, I guess PYTHONPATH also affects the installed PDM, as in, PDM's own virtualenv does not isolate against PYTHONPATH. I would say that's unfortunate, but it's pretty much how Python is designed to work. Where I'm going is, I think pretty much all Python code can in general be influenced by PYTHONPATH, and the user should be aware of this if they set the variable. So I think I'm also moving toward the "not a bug" side.
