### ISSUE TITLE
editable installation place files in the wrong place. 

### ISSUE THREAD

**Issue by ubaldot** [pdm-project/pdm#1921]
I- [x] I have searched the issue tracker and believe that this is not a duplicate.

When using editable builds, it seems that the files are installed in the wrong place. 
My project has the following structure:

```
conda/
dist/
scripts/
src/
tests/
LICENSE
README.md
Some_other_files
```

My `pyproject.toml` include the following sections:

```
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

...

[tool.pdm.build]
includes = [ "docs",
         "src",
         "tests",
         "scripts",
         "LICENSE"]


```
By running `python -m pip install -e .`  the package seems installed. 
However, the tests cannot find some files and therefore fail.

Inspection of `site-packages` show that `docs` and `scripts` folders are installed "outside" `site-package/mypackage` folder.

This can be immediately seen when running `python -m pip uninstall mypackage`: the output contains lines as it follows (excerpt)

```
...
/opt/homebrew/Caskroom/miniconda/base/envs/mypackage_dev/lib/python3.10/sitepackages/scripts/Motor.fmu
/opt/homebrew/Caskroom/miniconda/base/envs/mypackage_dev/lib/python3.10/sitepackages/scripts/Motor.svg /opt/homebrew/Caskroom/miniconda/base/envs/mypackage_dev/lib/python3.10/sitepackages/scripts/MotorLogs.h5
/opt/homebrew/Caskroom/miniconda/base/envs/mypackage_dev/lib/python3.10/site-packages/scripts
...
```

whereas I would have expect the following:

```
...
/opt/homebrew/Caskroom/miniconda/base/envs/mypackage_dev/lib/python3.10/sitepackages/mypackage/scripts/Motor.fmu
/opt/homebrew/Caskroom/miniconda/base/envs/mypackage_dev/lib/python3.10/sitepackages/mypackage/scripts/Motor.svg /opt/homebrew/Caskroom/miniconda/base/envs/mypackage_dev/lib/python3.10/sitepackages/mypackage/scripts/MotorLogs.h5
/opt/homebrew/Caskroom/miniconda/base/envs/mypackage_dev/lib/python3.10/site-packages/mypackage/scripts
...
```

Note that inspection of the *tar.gz file build from `pdm build` looks correct instead, so the problem is only with the editable install.  

Is there a way to fix this or it is a bug?

## Environment Information

```pdm info && pdm info --env
Inside an active virtualenv /opt/homebrew/Caskroom/miniconda/base/envs/dymoval_dev, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
PDM version:
  2.6.1
Python Interpreter:
  /opt/homebrew/Caskroom/miniconda/base/envs/dymoval_dev/bin/python (3.10)
Project Root:
  /Users/ubaldot/Documents/github/dymoval
Local Packages:
  
Inside an active virtualenv /opt/homebrew/Caskroom/miniconda/base/envs/dymoval_dev, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.11",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "22.4.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; 
root:xnu-8796.101.5~3/RELEASE_ARM64_T6000",
  "python_full_version": "3.10.11",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}

```

**Comment by frostming** [comment]
This is misuse and misunderstanding of the package structure. I can't reply with details because im out, but that's it.

**Comment by ubaldot** [comment]
Ok, looking forward for a more detailed reply. 

I tried to follow things "by the book" starting reading here:
https://packaging.python.org/en/latest/tutorials/packaging-projects/

plus a number of other guides discussing the "src layout" (which is what I am using) and various guides e.g. on where to place the test folder (I placed it outside the src folder), but apparently I am missing something and I would be glad to learn.

**Comment by ubaldot** [comment]
Ok, looking forward for a more detailed reply when you will have time.

I tried to structure my package “by the book” after having read a number of guides, but apparently I am missing something (especially for the script folder in my layout).

**Comment by frostming** [comment]
The biggest misunderstanding here is PDM backend(and all other backends) won't automatically create a namespace under `site-packages` for your package. Instead, all files in the wheel will be copied under site-packages **as-is**. For example:

```
xxx.whl/path/abc/foo.py -> <site-packages>/path/abc/foo.py
```

You are responsible to create the required file structure manually and include them in a wheel. If you need them to be placed under `site-packages/mypackage`, just create `mypackage` yourself and put files under it.

**Comment by ubaldot** [comment]
Thank you for the reply! 
I have restructured my package filesystem and now I got what I wanted. :)

**Comment by ubaldot** [comment]
I read the pdm docs and I must admit that the docs was perhaps the main reason I picked your tool for building & publishing. Nevertheless, I dare to provide some feedback that I believe may further improve the docs.

To make the examples more complete, I would add a couple of folders in the structures so it becomes even more clear what end up in the sdist and in the wheel. You could trivially add a `docs` and a `scripts` folder so that the following:

```
├── pyproject.toml
├── mypackage
│   ├── __init__.py
│   └── lib.py
└── tests
    └── test_lib.py
```

become this:

```
├── pyproject.toml
├── mypackage
│   ├── __init__.py
│   └── lib.py
└── tests
    └── test_lib.py
├── docs
└── scripts
    └── myscript.py
```

In the section _include or exclude_ files you mentioned a folder `scripts/ `and a file `script.py`.
It could be easy for a reader believe that `script.py` is under the `scripts/ folder`, therefore I would start the section with a reference filesystem like the one I posted above to show more carefully how the include/exclude mechanism work. 

I would also remind that python consider packages folders that contain a `__init__` file in it. 

Just my two cents :)
