### ISSUE TITLE
equivalent of "extra-index-url"

### ISSUE THREAD

**Issue by amor71** [pdm-project/pdm#1922]
## Is your feature request related to a problem? Please describe.

Add the ability to use additional external repositories(s).

The problem I am facing:
- I am deploying Functions to GCP (Google Cloud) via Terraform. 
- Shared code is placed on GCP Artifact Manager to avoid code duplication

## Describe the solution you'd like

A configuration similar to `extra-index-url` in `pip.conf` file

**Comment by frostming** [comment]
https://pdm.fming.dev/latest/usage/config/#configure-the-package-indexes
