### ISSUE TITLE
Mention repository.* config items in section "Available Configurations"

### ISSUE THREAD

**Issue by p-rogalski** [pdm-project/pdm#1926]
## Is your feature request related to a problem? Please describe.

The config items with the scheme `repository.*` are not mentioned in the documentation section [Available Configurations](https://pdm.fming.dev/latest/reference/configuration/#available-configurations).

## Describe the solution you'd like

Mention all of the config items with the scheme `repository.*`.

**Comment by frostming** [comment]
PR welcome
