### ISSUE TITLE
Add option repository.company.verify_ssl

### ISSUE THREAD

**Issue by p-rogalski** [pdm-project/pdm#1928]
## Is your feature request related to a problem? Please describe.

When defining an index with PDM, one can skip SSL verification with `verify_ssl = false`. This does not work for repositories.

## Describe the solution you'd like

Add the option `repository.company.verify_ssl`. This is especially useful for private company repositories.

**Comment by frostming** [comment]
Would you like to PR?

**Comment by p-rogalski** [comment]
Sure, I will try!

**Comment by p-rogalski** [comment]
Could you give me a hint where to look?
