### ISSUE TITLE
pdm export support env variables in credentials

### ISSUE THREAD

**Issue by Drachenfels** [pdm-project/pdm#1939]
## Is your feature request related to a problem? Please describe.

Pipelines sometimes work with generated requirements.txt as backward compatibility, if one uses a different index like this:
```
[[tool.pdm.source]]
url = "https://${PDM_USERNAME}:${PDM_PASSWORD}@path/to/custom/pypi/package/simple/"
verify_ssl = true
name = "pypi"
````

and PDM_USERNAME (example: john) / PDM_PASSWORD (example: password123) is set, 

and runs pdm export like this:
```
pdm export --prod -o requirements.txt --without-hashes
```

the resulting requirements file will have a username and password in plaintext:
```
# This file is @generated by PDM.
# Please do not edit it manually.

zipp==3.15.0
--index-url https://john:password123@path/to/custom/pypi/package/simple/
```

## Describe the solution you'd like

PIP allows to use env variables that are expanded at runtime: https://pip.pypa.io/en/stable/reference/requirements-file-format/#using-environment-variables

My proposal would be to add a switch `--no-env-expansion` (please suggest a better name) that will generate an export file but with an env notation that pip likes, example:
```
# This file is @generated by PDM.
# Please do not edit it manually.

zipp==3.15.0
--index-url https://${PDM_USERNAME}:${PDM_PASSWORD}@path/to/custom/pypi/package/simple/
```

**Comment by Drachenfels** [comment]
Hi @frostming 

I wonder what was the resolution of this issue, if I read the commit correctly, you consider it was actually a bug and from now on by default, we are going to have env vars in requirements. Am I correct?

**Comment by frostming** [comment]
Yes, I think preserving the env vars make more sense. And the variable substitution is also supported by `pip`.

It may be a little breaking change but I think people writing variables in their source settings can expect it.

**Comment by berislavlopac** [comment]
Wouldn't it make sense to keep a runtime option to force the variable expansion?

**Comment by berislavlopac** [comment]
@frostming you said:

> And the variable substitution is also supported by pip.

Can you point out this in any documentation? As far as I can tell, https://github.com/pypa/pip/issues/4789 is still open... 🤔
