### ISSUE TITLE
sha256sum of `install-pdm.py` does not match the one given in docs

### ISSUE THREAD

**Issue by prehensilecode** [pdm-project/pdm#1942]
- [✅] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

- Download copy of `install-pdm.py` from `main` branch: `wget https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py`
- Compute sha256sum: `06abd94a6678636eba640529bf91b242759363c45d3620cdfabaa0053d826b30  install-pdm.py`
- Compare against [value given in docs](https://pdm.fming.dev/latest/): “For security reasons, you should verify the checksum of `install-pdm.py`. The sha256 checksum is: `e0a116987b2667231391d13dd005006433114033cac74aa18f0b2dec5538d03`”

## Environment
- sha256sum version: `sha256sum (GNU coreutils) 9.3`

**Comment by frostming** [comment]
You are visiting the wrong version of docs, it should be: https://pdm.fming.dev/dev/

And if you are getting `install-pdm.py` from the main branch, you should check the sha256sum from the main README.md as well.
