### ISSUE TITLE
If using multiple package indices, an unresolved host error prevents the subsequent indices from being tried

### ISSUE THREAD

**Issue by taranlu-houzz** [pdm-project/pdm#1945]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

I have a situation where the DNS for an internal pypi index is different between my local laptop and the ci node we use to build packages (I think it is probably the same EC2 instance, but the DNS is just different). This makes dev/ci a bit challenging, since `pdm` fails with an error on `pdm install` if the dns for a source cannot be resolved, even if multiple sources have been specified. Here is an example of the setup that I am trying:

```toml
[tool.pdm.resolution]
respect-source-order = true

[[tool.pdm.source]]
name = "ci"
url = "http://<name 1>.com:8081"
verify_ssl = false

[[tool.pdm.source]]
name = "local"
url = "http://<name 2>:8081"
verify_ssl = false
```

Each source works individually for either CI on Jenkins or locally on my laptop.

## Actual behavior

`pdm` fails due to a exception raised when it is unable to resolve the DNS for one of the sources:

```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='<name 1>', port=8081): Max retries exceeded with url: /<my package name>/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x1062abd30>: Failed to resolve '<name 1>' ([Errno 8] nodename nor servname provided, or not known)")
```

* I replaced the actual host name and package name for this issue manually with e.g. `<name 1>`.

## Expected behavior

Instead of failing with an exception, it seems like it would be better to catch the error, log it, and then move on to the next source (if available).

## Environment Information

```bash
❯ pdm info && pdm info --env
PDM version:
  2.6.1
Python Interpreter:
  /Users/<path to project dir>/<package name>/.venv/bin/python (3.7)
Project Root:
  /Users/<path to project dir>
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.7.16",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "22.4.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000",
  "python_full_version": "3.7.16",
  "platform_python_implementation": "CPython",
  "python_version": "3.7",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
I don't agree, LinkCollectionError will be silent unless `-v` is passed, which makes you never have a chance to spot the error.

**Comment by taranlu-houzz** [comment]
That is a good point, but that means that there isn't really any way to resolve the situation that I have run into. Because the DNS is different locally vs ci, the project will have to choose one or the other for the source, since having both will break things. I am trying to see if we can get the DNS issue consistent, but it seems to me that others might run into a similar issue...

Would it be possible to add a parameter for sources that allows them to be skipped if they fail?

**Comment by taranlu-houzz** [comment]
@frostming So, in order to get around this, I figured that I could use the global pdm config to set the repository, and just have different config in ci vs local. This works, but I did notice that it seems that `pdm config --global pypi.<my pypi index name>.verify_ssl False` results in a quoted string `"False"` in the `pdm/config.toml` file, which then fails to be considered a valid, trusted_host here: https://github.com/pdm-project/pdm/blob/1638e621d8e1ee0a1302f60e9187ecd79d0bc919/src/pdm/utils.py#L64
