### ISSUE TITLE
Pytest ImportError occurred when using pdm editable install

### ISSUE THREAD

**Issue by drunkwcodes** [pdm-project/pdm#1946]
I started to use `pdm` yesterday, install my project with `pdm add -e ./sub-package --dev `
and wrote a test importing project's module:

```python
from matty_web.utils import init_data, generate_password, conf
import os

def test_init_data():
    init_data()
    assert os.path.exists(conf["data_folder"])
```

The pytest returned with error:
`E   ModuleNotFoundError: No module named 'matty_web'`

The workaround is using `pip install -e .`, pytest runs without ImportError now.
Please tell me why pip editable install works but pdm editable install no, thanks.

**Comment by frostming** [comment]
What `pytest` did you call from? You seem to use the wrong environment.

**Comment by drunkwcodes** [comment]
@frostming I'm using the .venv/ pdm creates below the project root folder.

**Comment by frostming** [comment]
Can you show the output of `pdm info` and `pip --version`?

After you run `pdm install`, where does the `matty_web` module go?
And after you run `pip install`, where does the `matty_web` module go? You will likely see some difference.

**Comment by drunkwcodes** [comment]
Output of `pdm info`:

```
PDM version:
  2.6.1
Python Interpreter:
  D:\projects\matty_web\.venv\Scripts\python.exe (3.11)
Project Root:
  D:/projects/matty_web
Local Packages:
```

Output of `pip --version`:
```
pip 22.3.1
```

> Wait, you run pdm add -e ./sub-package but run pip install -e .? They even install different things! one is sub-package and the other is .

@frostming I pasted from pdm's doc and I installed `.` for sure.

I can find `matty_web` in `.venv` but I can't tell the difference between pdm and pip.

**Comment by frostming** [comment]
> pip 22.3.1

Why strip the important part, I want to see the path of pip

**Comment by drunkwcodes** [comment]
`pip --version`:

```
pip 22.3.1 from C:\Users\Eric\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip (python 3.11)
```

**Comment by frostming** [comment]
> `pip --version`:
> 
> ```
> pip 22.3.1 from C:\Users\Eric\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip (python 3.11)
> ```

With that pip the modules will be installed under `C:\Users\Eric\AppData\Local\Programs\Python\Python311\Lib\site-packages`, I guess you are also using a `pytest` from there. It's a misuse.

**Comment by frostming** [comment]
> But I remember I only installed in `.venv`

No, when you run `pip install -e .` you installed it there. And you probably didn't `pytest` into the venv, so when you run `pytest`, you called the one under the global site-package.

**Comment by drunkwcodes** [comment]
@frostming I don't know how to make pytest into venv. Do you know how to do that?
Maybe it's pytest problem, is there anybody know how to deal with it?

**Comment by frostming** [comment]
@drunkwcodes just use pdm to install dependencies and run scripts, all will go to pdm managed venv:

```bash
pdm add -d -G dev pytest
pdm run pytest
```

**Comment by drunkwcodes** [comment]
@frostming Thanks, I will try it tomorrow.

**Comment by drunkwcodes** [comment]
@frostming It works, thanks a lot.
