### ISSUE TITLE
Editable local installation behaves differently

### ISSUE THREAD

**Issue by liran-cohen-hs** [pdm-project/pdm#1952]
## Steps to reproduce
I have project with internal dependencies which are installed as packages
lets say main project directory is A and I have directory B in A with another directory which is also B and setup.py in it
so it looks like this:

```
A/
  B/
    setup.py
    B/
      __init__.py
```

`__init__.py` defines global variable, lets call it `GLB_VAR`
now for local development I am installing B as editable dependency-
`pdm add -e ./B --dev`
and now I want to import `GLB_VAR`

## Actual behavior
Up until now with `pip` editable install or with **PDM no-editable installation**, I imported the following way:
`from B import GLB_VAR`
with PDM editable install I need to import as:
`from B.B import GLB_VAR`
if I try to import the old way it errors with `ERROR  - ImportError: cannot import name 'GLB_VAR' from 'B'`

## Expected behavior
I am expecting imports to be the same for editable/non-editable installations, otherwise, project setup is kinda tricky

## Environment Information
Adding link to a github repository with the described setup:
https://github.com/liran-cohen-hs/pdm-reproduce-1952
`main.py` describes the actual vs expected behavior

```bash
PDM version:
  2.5.6
Python Interpreter:
  /Users/liran/hiredscore/git/screenit/.venv/bin/python (3.9)
Project Root:
  /Users/liran/hiredscore/git/screenit
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.16",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "22.3.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000",
  "python_full_version": "3.9.16",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "darwin"
}
```

**Comment by pawamoy** [comment]
I've edited your comment to show the file tree with a code block rather than quotes (>). It does not look right to me as one cannot have two files or directories with the same name (B) in a given directory (A). Could you edit and fix the file tree?

Generally, it would be better if you could create and publish a Git repository on GitHub containing the contents reproducing the issue you describe.

**Comment by liran-cohen-hs** [comment]
> I've edited your comment to show the file tree with a code block rather than quotes (>). It does not look right to me as one cannot have two files or directories with the same name (B) in a given directory (A). Could you edit and fix the file tree?
> 
> Generally, it would be better if you could create and publish a Git repository on GitHub containing the contents reproducing the issue you describe.

Thanks
fixed the file tree
I can add a git repository with the files but I feel it really doesn't matter that much
it's just about a local python package being installed as editable dependency

**Comment by frostming** [comment]
> Up until now with `pip` editable install or with **PDM no-editable installation**, I imported the following way:
> `from B import GLB_VAR`

I tested with `pip` the behavior is the same:

```bash
pip install -e my_package/
python -c "from my_package import MY_VARIABLE"  # ERROR
python -c "from my_package.my_package import MY_VARIABLE"  #SUCCESS
```

This is caused by the new ["strict" editable install mode](https://setuptools.pypa.io/en/latest/userguide/development_mode.html#strict-editable-installs) introduced by recent versions of `setuptools`. This is not related to PDM.

To fix this, you either rename the package directory to avoid name conflict with the import name or you explicitly configure the setuptools to not use strict mode, or use another build backend for `my_package`.

**Comment by liran-cohen-hs** [comment]
> > Up until now with `pip` editable install or with **PDM no-editable installation**, I imported the following way:
> > `from B import GLB_VAR`
> 
> I tested with `pip` the behavior is the same:
> 
> ```shell
> pip install -e my_package/
> python -c "from my_package import MY_VARIABLE"  # ERROR
> python -c "from my_package.my_package import MY_VARIABLE"  #SUCCESS
> ```
> 
> This is caused by the new ["strict" editable install mode](https://setuptools.pypa.io/en/latest/userguide/development_mode.html#strict-editable-installs) introduced by recent versions of `setuptools`. This is not related to PDM.
> 
> To fix this, you either rename the package directory to avoid name conflict with the import name or you explicitly configure the setuptools to not use strict mode, or use another build backend for `my_package`.

Thanks for the information ! very helpful
