### ISSUE TITLE
Clean from not required packages

### ISSUE THREAD

**Issue by aryadovoy** [pdm-project/pdm#1953]
## Is your feature request related to a problem? Please describe.

I have some conflicts between packages, but I haven't some packages in my pyproject.toml and lock file. I checked the list of packages and found 2 extra packages, but I couldn't delete them by PDM, so I add them and after that delete.

![image](https://github.com/pdm-project/pdm/assets/26593349/20e4cbbd-2257-4144-b656-804ab25a2ea9)

## Describe the solution you'd like

I check the docs and couldn't find solution, so my suggestion: add `clean` function for deleting unused (not required) packages.

**Comment by edsq** [comment]
I believe what you want is just `pdm sync --clean`.  See also the docs on [installing packages in the lock file](https://pdm.fming.dev/latest/usage/dependency/#install-the-packages-pinned-in-lock-file).
