### ISSUE TITLE
Allow the lock file to be independent of the python package repository being used

### ISSUE THREAD

**Issue by theredfoxlee** [pdm-project/pdm#1960]
## Feature request

Would it be possible to implement an option like `lock.store_url = False` so that the package's URL is not stored in the `pdm.lock` file?

## Motivation

I have a standalone private python package repository. Sometimes, I also use a locally created PyPI server. Both repositories have different URLs for downloaded packages, but the hash of those packages is the same.

I would like to use one `pdm.lock` with both repositories (e.g. by changing `PDM_PYPI_URL` environment variable), but currently it's not possible as urls stored in `pdm.lock` seem to be used for some kind of authentication that fails as follows:

```python
Synchronizing working set with lock file: 79 to add, 0 to update, 0 to remove

  ✖ Install setuptools 67.8.0 failed

See /tmp/pdm-install-ay13yv08.log for detailed debug log.
[PdmException]: The credentials for <url-from-lock-file> are not provided. To give them via interactive shell, please rerun the command with `-v` option.
```

> I have generated that error with `pdm` version: **2.7.0**

Would it possible to have a `pdm.lock` that is independent of the python package repository being used?

## Footnotes

Similar request (but for poetry):
1. https://github.com/python-poetry/poetry/issues/5317

**Comment by theredfoxlee** [comment]
A temporary workaround for this issue is to use a bare pip during installation from a different Python package repository:
```Dockerfile
RUN pdm export --prod -f requirements -o requirements.txt && pip install -r requirements.txt
COPY ./ ./
RUN pip install .
```

**Comment by theredfoxlee** [comment]
@frostming - Does [pdm==2.8.0](https://github.com/pdm-project/pdm/releases/tag/2.8.0) address this issue? I think that running `pdm lock --no-static-urls --refresh` removes URLs from `pdm.lock`, making it independent from the python package repository :thinking:

**Comment by frostming** [comment]
Yes
