### ISSUE TITLE
`pdm export --only-defaults`

### ISSUE THREAD

**Issue by colobas** [pdm-project/pdm#1966]
## Is your feature request related to a problem? Please describe.

I'm trying to export a `requirements.txt` file for a project, containing only the default dependencies, but there doesn't seem to be an option to do this. I'm getting the same results doing `$ pdm export -G :all ...` and simpy `$ pdm export`.

## Describe the solution you'd like

A new flag `--only-defaults` allowing me to export a requirements file without any optional dependencies.

**Comment by frostming** [comment]
did you look for other flags? that's --prod

**Comment by colobas** [comment]
I though `--prod` was excluding dev dependencies

**Comment by frostming** [comment]
optional deps are opt-in, and dev deps are opt-out. So excluding dev deps is default-only

**Comment by colobas** [comment]
Yeah I understand now.
My problem was with how I was creating my `pdm.lock` file, not with `pdm export`
