### ISSUE TITLE
Semantic versions constrants operators support for add command 

### ISSUE THREAD

**Issue by dbalabka** [pdm-project/pdm#1967]
## Is your feature request related to a problem? Please describe.

PDM already supports Poetry's semantic versions constraints operators when it imports dependencies from existing `pyproject.toml` created by Poetry.

It would be great to reuse the support of `^` and `~` operators for `add` command. For example:

Before
```
pdm add numpy>=1.21.0,<2.0.0
```
After
```
pdm add numpy^1.21
```

Before
```
pdm add numpy>=1.21.0,<1.22.0
```
After
```
pdm add numpy~1.21
````

**Comment by frostming** [comment]
We only support standard version specifiers(PEP 440).

**Comment by dbalabka** [comment]
@frostming , I apologize if my intent was not clear in my previous message. The idea is to keep the constraints in `pyproject.toml` according to `PEP440` while having shortcuts for `pdm add` command.

**Comment by pawamoy** [comment]
@dbalabka wouldn't this be confusing to users?

**Comment by dbalabka** [comment]
@pawamoy, people who are using Poetry or coming from other languages (e.g. npm, composer, cargo, etc.) are more familiar with the Semantic Versioning version constraint operators like `~` and `^`, but less with `~=`. Supporting semantic versioning, at least for `pdm add` command, might improve the developer experience.  I agree that a developer might be confused that `pyproject.toml` contains equivalent construction instead of the exact operator. It is a small tradeoff to partially support Semantic Versioning operators that are not included in PEP440.

**Comment by pawamoy** [comment]
I don't think it is worth it to add such support in PDM commands, while not in pyproject.toml since it's not in the standard PEP 440. However maybe there's a way to improve UX by either writing useful error messages when such operators are used in PDM commands/pyproject.toml, or at least document their lack of support and `~=` alternative.
