### ISSUE TITLE
After updating PDM with scoop, an error occurs when starting Windows Terminal.

### ISSUE THREAD

**Issue by brucmao** [pdm-project/pdm#1978]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```
scoop update pdm
scoop cleanup -k pdm
```

## Actual behavior
I encountered an error when launching Windows Terminal after upgrading PDM using Scoop.

![image](https://github.com/pdm-project/pdm/assets/6119652/41822166-6b9a-4c8e-aacf-1e64d0724e7c)

I found that the variable "PDM_PYTHON" in the pdm_completion.ps1 file still points to an old version path.
```
if ((Test-Path Function:\TabExpansion) -and -not (Test-Path Function:\_pdm_completeBackup)) {
    Rename-Item Function:\TabExpansion _pdm_completeBackup
}

$PDM_PYTHON = "C:\Users\brucm\scoop\apps\pdm\2.6.1\venv\Scripts\python.exe"
$PDM_PIP_INDEX = (& $PDM_PYTHON -m pdm config pypi.url).Trim()
$CONFIG_DIR = "$env:LOCALAPPDATA\pdm"
```

## Expected behavior

Update the pdm_completion.ps1 file automatically when using scoop to update PDM.

## Environment Information

windows 11  
powershell 7.3.4

**Comment by frostming** [comment]
Please try the latest version

**Comment by brucmao** [comment]
I resolved the issue by deleting the 'pdm_completion.ps1' file and running 'pdm init' again.
