### ISSUE TITLE
pdm install always clears the build directory

### ISSUE THREAD

**Issue by szandara** [pdm-project/pdm#1979]
- [x ] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

For our project we use the `build` directory for some custom functionalities but `pdm install` always clears that directory once it's done. I think that the `build` directory is cleared up because of installing `self` as editable package. Is there a way to avoid clearing up `build` when running `pdm install`?

```
pdm.termui: Synchronization complete.
pdm.termui:  - Adding build/xxx-0.1.0+editable.dist-info/METADATA -> xxx-0.1.0+editable.dist-info/METADATA
pdm.termui:  - Adding build/xxx-0.1.0+editable.dist-info/WHEEL -> xxx-0.1.0+editable.dist-info/WHEEL
pdm.termui:  - Adding build/xxx-0.1.0+editable.dist-info/licenses/LICENSE -> xxx-0.1.0+editable.dist-info/licenses/LICENSE
pdm.termui:  - Adding build/xxx.pth -> xxx.pth
pdm.termui:  - Adding xxx-0.1.0+editable.dist-info/RECORD -> xxx-0.1.0+editable.dist-info/RECORD
  ✔ Update xxx 0.1.0+editable -> 0.1.0 successful
```

## Steps to reproduce

- Run `PDM_BUILD_NO_CLEAN=1 pdm install -v`
or
- Run `PDM_BUILD_NO_CLEAN=1 pdm build -v`

## Actual behavior

- `build/` directory is cleared up

## Expected behavior

- `build/` directory is not cleared up

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

PDM version:
  2.7.0
Python Interpreter:
  /home/coder/xxx/.venv/bin/python (3.9)
Project Root:
  /home/coder/xxx
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.5",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.0-1036-azure",
  "platform_system": "Linux",
  "platform_version": "#43-Ubuntu SMP Wed Mar 29 16:11:05 UTC 2023",
  "python_full_version": "3.9.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}

```

**Comment by szandara** [comment]
Anyway the bug problem is also reproducible with `pdm build` for me

**Comment by pawamoy** [comment]
What I mean is that you could `pdm install` a first time, so the package is installed locally, and then only use `pdm install --no-self` to avoid re-building the distributions. But yeah, it's a workaround.

**Comment by szandara** [comment]
@pawamoy I see what you mean but it won't work for me as the problem happens in the CI run where we use the build directory for internal purposes.

**Comment by szandara** [comment]
I think this is a bug, I made a tentative fix: https://github.com/pdm-project/pdm-backend/pull/174/files

**Comment by sanmai-NL** [comment]
@szandara #174 -> #177 was merged. Can the issue be closed?
