### ISSUE TITLE
Add support for beta releases (eg `3.12.0b1+`)

### ISSUE THREAD

**Issue by patrick91** [pdm-project/pdm#1982]
I think this is the same issue as https://github.com/python-poetry/poetry/issues/6925

I'm trying to use python 3.12 with pdm, but I'm getting `No python is found meeting the requirement python` error when doing:

```
pdm use python3.12
```

I believe it is because my installation of python has a `+` in the version name, `3.12.0b1+` and it is not getting parsed properly.

I installed it using `asdf` :)

**Comment by frostming** [comment]
Does it show any candidates after `Interpreters found but not matching:`?

**Comment by patrick91** [comment]
@frostming no, here's the full error:

```
pdm use /Users/patrick/.asdf/installs/python/3.12-dev/bin/python
[NoPythonVersion]: No Python interpreter matching
/Users/patrick/.asdf/installs/python/3.12-dev/bin/python is found.
```

btw I found that installing the version in this way:

`asdf install python 3.12.0b1`

make the issue go away, as the python version won't include the `+`, so maybe it is not worth adding support for the plus in the name?

**Comment by frostming** [comment]
But it is already stripped: https://github.com/frostming/findpython/blob/e440430d11053aaa2969fc117462931feadae7d7/src/findpython/python.py#L165-L168

What is the value of `requires-python` in `pyproject.toml`?

**Comment by patrick91** [comment]
> But it is already stripped: https://github.com/frostming/findpython/blob/e440430d11053aaa2969fc117462931feadae7d7/src/findpython/python.py#L165-L168

oh, that's odd :) maybe I can add some logs tomorrow

> What is the value of `requires-python` in `pyproject.toml`?

I think it was `python>=3.7<4"

**Comment by frostming** [comment]
Hi, any updates? What PDM version are you on?

**Comment by frostming** [comment]
Closing due to no further info.
