### ISSUE TITLE
Connection broken: IncompleteRead on pdm install

### ISSUE THREAD

**Issue by jorge-wonolo** [pdm-project/pdm#1989]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Run `pdm install`

## Actual behavior

Unable to install dependencies
[pdm.log](https://github.com/pdm-project/pdm/files/11691231/pdm.log)

## Expected behavior

dependencies can be resolved

## Environment Information

```bash
PDM version:
  2.7.1
Python Interpreter:
  /Users/jorge/Development/deploy-valet/.venv/bin/python (3.11)
Project Root:
  /Users/jorge/Development/deploy-valet
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.11.3",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "22.5.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000",
  "python_full_version": "3.11.3",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
2.7.1 is yanked, downgrade your PDM to 2.7.0 please, you may also need to do `pdm cache clear` to fix the broken cache.
