### ISSUE TITLE
Impossible to use binary flags

### ISSUE THREAD

**Issue by mixmind** [pdm-project/pdm#2000]
- [V] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
Run in docker

```
FROM python:3.8-bullseye
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -qq gcc

RUN python3 -m pip install pdm
RUN pdm init -n && PDM_PREFER_BINARY=:all: pdm add -v psycopg2-binary && ldd .venv/lib/python3.8/site-packages/psycopg2_binary.libs/libkrb5support-d0bcff84.so.0.1

```
## Actual behavior
PIP_NO_BINARY and PDM_PREFER_BINARY are not working as expected
It's installs package from pypi, but I want/need to compile package on my env.
![image](https://github.com/pdm-project/pdm/assets/33128809/4d550cfc-9983-4712-8769-7ad29778e320)
## Expected behavior
pdm will consider to use provided flags and will compile requested packages

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

```
![Screenshot from 2023-06-11 11-00-36](https://github.com/pdm-project/pdm/assets/33128809/746fa491-4e56-45cb-a90f-0d6c8f113583)

**Comment by pawamoy** [comment]
I'm not sure to understand.

- you tell PDM that you prefer to install binaries, and ask it to install psycopg2-binary
- PDM installs psycopg2-binary using a wheel
- then you tell pip (?) to refuse binaries and only install from source distributions, and ask PDM to install psycopg2-binary again (?)
- then you interrupt the command (?)

Why did you interrupt the last command? You're `cat`ing pdm.lock but your screenshot is truncated? Why do you try to both install psycopg2-binary from a wheel and from an sdist? PDM does not use pip internally but unearth (mentioned in the logs).

If you want to install psycopg2-binary from source, shouldn't you use `PDM_NO_BINARY=psycopg2-binary pdm add psycopg2-binary`?

**Comment by mixmind** [comment]
> I'm not sure to understand.
> 
> * you tell PDM that you prefer to install binaries, and ask it to install psycopg2-binary
> * PDM installs psycopg2-binary using a wheel
> * then you tell pip (?) to refuse binaries and only install from source distributions, and ask PDM to install psycopg2-binary again (?)
> * then you interrupt the command (?)
> 
> Why did you interrupt the last command? You're `cat`ing pdm.lock but your screenshot is truncated? Why do you try to both install psycopg2-binary from a wheel and from an sdist? PDM does not use pip internally but unearth (mentioned in the logs).
> 
> If you want to install psycopg2-binary from source, shouldn't you use `PDM_NO_BINARY=psycopg2-binary pdm add psycopg2-binary`?

PDM_NO_BINARY fixed the issue, I misread the documentation and used incorrectly flags.
Thanks for help, sorry for you time loss

**Comment by pawamoy** [comment]
No worries, thank you for coming back and closing the issue :)
