### ISSUE TITLE
PDM won't install package in editable modle

### ISSUE THREAD

**Issue by thmsklngr** [pdm-project/pdm#2001]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

- Create a minimal package with a correct `pyproject.toml`
- run `pdm add --dev -e .`
- PDM will report that the package has been successfully installed and changes are written to `pyproject.toml`
- Only `pyproject.toml` is present, no `setup.cfg` or `setup.py` (using Flit as build backend)

## Actual behavior

- Package is not installed in editable mode
- Scripts from section `[project.scripts]` won't appear under `.venv/bin`
- PDM command `list` does not show the package (also `pdm run pip list` won't)
- `pdm run pip install -e .` will do the trick
- It does not matter if the virtual environment is activated or not

## Expected behavior

- Package is installed in editable mode

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.7.0
Python Interpreter:
  /home/thomas/Projekte/svmm_elt/.venv/bin/python (3.6)
Project Root:
  /home/thomas/Projekte/svmm_elt
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.6.15",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.114-2-MANJARO",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT Sun Jun 4 10:32:43 UTC 2023",
  "python_full_version": "3.6.15",
  "platform_python_implementation": "CPython",
  "python_version": "3.6",
  "sys_platform": "linux"
}
```
## Additional information
```bash
$ pdm add --dev -e .
Package svmm_elt is the project itself.
🔒 Lock successful
Changes are written to pyproject.toml.
All packages are synced to date, nothing to do.

🎉 All complete!

$ cat pyptoject.toml
[project]
name = "svmm_elt"
authors = [
    {name = "Thomas Klinger", email = "thomas.klinger@me.com"},
]
dependencies = [
    "typer>=0.9.0",
    "python-box>=6.0.2",
    "jinja2>=3.0.3",
]
requires-python = ">=3.6.2"
readme = "README.md"
license = {text = "Propietary"}
dynamic = ["version", "description"]

[project.scripts]
svmm_elt = 'svmm_elt.main:app'

[build-system]
requires = ["flit_core>=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.pdm.dev-dependencies]
dev = [
    "flit>=3.9.0",
    "flake8>=2.5.5",
    "autopep8>=2.0.2",
    "black>=22.8.0",
    "mypy>=0.971",
    "types-setuptools>=67.8.0.0",
]

```

**Comment by frostming** [comment]
You don't need to add the self package. It will be installed automatically when you run `pdm install`, unless `--no-self` is given.
