### ISSUE TITLE
Unexpected breaking change in BaseCommand when updating Patch-Version

### ISSUE THREAD

**Issue by carstencodes** [pdm-project/pdm#2009]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

Update your PDM installation from PDM 2.7.1 to 2.7.2 and run a plug-in, e.g. pdm-bump

## Actual behavior

```bash
Failed to load plugin pdm-bump=pdm_bump:main: BumpCommand.__init__() missing 1 required positional argument: 'parser'
Usage: pdm [-h] [-V] [-c CONFIG] [-v] [-I] [--pep582 [SHELL]] __root__ ...
pdm: error: unrecognized arguments: dev
```
src: https://github.com/carstencodes/pdm-bump/actions/runs/5246929518/jobs/9478135588#step:12:34

## Expected behavior

The plug-in can be started without errors

## Environment Information

```bash
## Not part of the CLI output. 
```

Problematic change: https://github.com/pdm-project/pdm/commit/f08b414fc0d15023e5116462c2a32405dd4c893b in https://github.com/pdm-project/pdm/pull/1983

**Comment by frostming** [comment]
Thanks, will release the fix soon
