### ISSUE TITLE
JSONDecodeError on self-check cache

### ISSUE THREAD

**Issue by genericmoniker** [pdm-project/pdm#2016]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

I've seen issues around caching with 2.7.1, but I think this one is different.

## Steps to reproduce

Repeatedly running `pdm config check_update true` over time, ended up with a cache file that looks like this (extra closing brace):

```json
{"latest-version": "2.7.0", "last-check": 1686232822.25927}}
```

## Actual behavior

Exception when running `pdm config check_update true` (every time once cache file is bad):

```
Traceback (most recent call last):
  File "/opt/sc/sdk/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/opt/sc/sdk/lib/python3.10/site-packages/pdm/core.py", line 268, in main
    return Core().main(args)
  File "/opt/sc/sdk/lib/python3.10/site-packages/pdm/core.py", line 202, in main
    check_update(project)
  File "/opt/sc/sdk/lib/python3.10/site-packages/pdm/cli/actions.py", line 843, in check_update
    latest_version = get_latest_version(project)
  File "/opt/sc/sdk/lib/python3.10/site-packages/pdm/cli/actions.py", line 821, in get_latest_version
    state = json.loads(cache_file.read_text())
  File "/opt/sc/sdk/lib64/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/sc/sdk/lib64/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 60 (char 59)
```

## Expected behavior

1. The cache file should generally be parseable
2. If not, PDM should be able to recover (maybe moving the cache file and emitting a warning?)

## Environment Information

(Technically from a different but similarly configured machine.)

```bash
$ pdm info && pdm info --env
PDM version:
  3.6.1
Python Interpreter:
  /home/vagrant/projects/j/.venv/bin/python (3.10)
Project Root:
  /home/vagrant/projects/j
Local Packages:


PDM 2.6.1 is installed, while 2.7.0 is available.
Please run `pdm self update` to upgrade.
Run `pdm config check_update false` to disable the check.
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.8",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "3.10.0-1127.el7.x86_64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Tue Mar 31 23:36:51 UTC 2020",
  "python_full_version": "3.10.8",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}

PDM 2.6.1 is installed, while 2.7.0 is available.
Please run `pdm self update` to upgrade.
Run `pdm config check_update false` to disable the check.
```

Not sure if this is relevant, but I notice that on another machine (not having the problem), the timestamp in the cache has more digits (write to file w/o truncation?):

```
{"latest-version": "2.7.0", "last-check": 1686362445.228455}  # good cache file
{"latest-version": "2.7.0", "last-check": 1686232822.25927}}  # bad cache file
```

**Comment by frostming** [comment]
Can you provide stable steps to reproduce this? I failed to reproduce on my side and I can't fix based on some wild guesses.

**Comment by genericmoniker** [comment]
I spent some time last night trying -- by scripting repeated `pdm config check_update true` calls and deleting the cache file so that it would continuously be rewritten -- but didn't ever reproduce it. I *could* see that the timestamp digits didn't matter, so one wild guess debunked :smile:

The situation where it was seen was on a CI server where builds all began to fail and continued until a manual intervention was made to repair the cache file. Maybe it was some kind of weird IO problem as opposed to a PDM bug.

I can also understand if you don't want to clutter the code with error handling for cache failure since that *shouldn't* happen. 

Thanks for looking into it :+1:
