### ISSUE TITLE
Question: How to select python version when using pyenv?

### ISSUE THREAD

**Issue by startakovsky** [pdm-project/pdm#2031]
After installing with `pipx` and running `pdm init`, I am seeing this and have no clue how to proceed because my understanding is these pyenv shims are temporary? Are there guidelines for proceeding with pdm and pyenv?

```text
0. /Users/steven/.pyenv/shims/python3 (3.11)
1. /Users/steven/.local/share/virtualenvs/myenv-qwB/bin/python (3.11)
2. /Users/steven/.pyenv/versions/3.11.4/bin/python3.11 (3.11)
3. /Users/steven/.pyenv/shims/python3.11 (3.11)
4. /Users/steven/.pyenv/shims/python (3.11)
5. /Users/steven/.pyenv/versions/3.11.3/bin/python3.11 (3.11)
6. /opt/homebrew/bin/python3.11 (3.11)
7. /Users/steven/.pyenv/shims/python3.10 (3.10)
8. /opt/homebrew/bin/python3.10 (3.10)
9. /Users/steven/.pyenv/versions/anaconda3-2023.03/bin/python3.10 (3.10)
10. /Users/steven/.pyenv/versions/mambaforge/bin/python3.10 (3.10)
11. /Users/steven/.pyenv/versions/3.10.6/bin/python3.10 (3.10)
12. /Users/steven/.pyenv/versions/3.10.1/bin/python3.10 (3.10)
13. /opt/homebrew/bin/python3.9 (3.9)
14. /usr/bin/python3 (3.9)
15. /Users/steven/.pyenv/versions/3.8.16/bin/python3.8 (3.8)
```

**Comment by pawamoy** [comment]
If you have configured global pyenv versions with `pyenv global`, don't worry about the interpreter you select when initializing a project with PDM: you can change the interpreter any time you want with `pdm use python3.11`  for example.

**Comment by startakovsky** [comment]
Thanks @pawamoy , I'll experiment with that to see what happens!

**Comment by startakovsky** [comment]
Got through it but got stuck for some time isolating this bug: https://github.com/pdm-project/pdm/issues/2032

**Comment by frostming** [comment]
I close this because I don't think he will add more and the outputs seems no problem.
