### ISSUE TITLE
'pdm update' does not update pyproject.toml

### ISSUE THREAD

**Issue by vitidev** [pdm-project/pdm#2035]
- [ x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

     pdm init
     pdm add numpy==1.22.0

modify `pyproject.toml`

    dependencies = [
        "numpy>=1.22.0",
    ]

continue

    $ pdm update numpy -v
    Updating packages: numpy.
    STATUS: Resolving dependencies
    pdm.termui: ======== Start resolving requirements ========
    pdm.termui:   numpy>=1.22.0
    pdm.termui:   python>=3.11
    pdm.termui:   Adding requirement numpy>=1.22.0
    pdm.termui:   Adding requirement python>=3.11
    pdm.termui: ======== Starting round 0 ========
    STATUS: Resolving: new pin python>=3.11
    pdm.termui: Pinning: python None
    pdm.termui: ======== Ending round 0 ========
    pdm.termui: ======== Starting round 1 ========
    STATUS: Resolving: new pin numpy 1.25.0
    pdm.termui: Pinning: numpy 1.25.0
    pdm.termui: ======== Ending round 1 ========
    pdm.termui: ======== Starting round 2 ========
    pdm.termui: ======== Resolution Result ========
    pdm.termui: Stable pins:
    pdm.termui:   python None
    pdm.termui:    numpy 1.25.0
    STATUS: Fetching hashes for resolved packages...
    pdm.termui: Fetching hashes for numpy@1.25.0
      Lock successful
    STATUS: Resolving packages from lockfile...
    STATUS: Fetching hashes for resolved packages...
    Synchronizing working set with lock file: 0 to add, 1 to update, 0 to remove

    pdm.termui: Removing distribution numpy
    unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/de/8b/b2d73b913be92056b1f77b0b9d184d93f368353540adf91e699a10a2effb/numpy-1.25.0-cp311-cp311-win_amd64.whl (from None)>
      v Update numpy 1.22.0 -> 1.25.0 successful

      All complete!

## Actual behavior

    [project]
    name = ""
    version = ""
    description = ""
    authors = [
        {name = "vitidev", email = "vitidev@users.noreply.github.com"},
    ]
    dependencies = [
        "numpy>=1.22.0",
    ]
    requires-python = ">=3.11"
    license = {text = "MIT"}

## Expected behavior

    [project]
    name = ""
    version = ""
    description = ""
    authors = [
        {name = "vitidev", email = "vitidev@users.noreply.github.com"},
    ]
    dependencies = [
        "numpy>=1.25.0",
    ]
    requires-python = ">=3.11"
    license = {text = "MIT"}

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
pdm info && pdm info --env
PDM version:
  2.7.4
Python Interpreter:
  G:\Dev\Python\python.EXE (3.11)
Project Root:
  z:/test
Local Packages:
  z:\test\__pypackages__\3.11
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.3",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19045",
  "python_full_version": "3.11.3",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "win32"
}
```

flags `--update-eager`, `--update-all` do nothing. 

`pdm lock` also affected
same for active venv

Is this a bug or a new update policy? I haven't used pdm for a long time

**Comment by frostming** [comment]
you are looking for `--unconstrained` to remove the constraints.

**Comment by vitidev** [comment]
@frostming 
I don't understand. What does `--unconstrained` really do?

    pdm update --help
    -u, --unconstrained   Ignore the version constraint of packages

`pdm update` (without `--unconstrained`) updates installed package and `pdm.lock` to latest package version and just not update `pyproject.tomlё

`pdm update -u` does the same but additionally updates 'pyproject.toml`

What kind of constraints `--unconstrained` remove?

**Comment by pawamoy** [comment]
@frostming if I understand correctly, @vitidev wants to update the lower bound *in pyproject.toml*, not just in pdm.lock.

**Comment by vitidev** [comment]
@pawamoy

Yes.  I prefer update the lower bound in pyproject.toml

Ok, there is a flag `--unconstrained`

But this flag is strange
`pdm update` updates packages, except pinned with '=='
`pdm update --unconstrained` (according to the name and description) allows to ignore contsraints and update those packages as well...BUT also update pyproject.toml....why it just not "ignore contsraints"?

Why does this flag have such a side effect?

If I use this flag to update the lower bound in pyproject.toml, it will break all '=='

I think `--unconstrained` should just be "only ignore contsraints" as its semantics implies.
And there should be a separate flag for actualizing updated packages in pyproject.toml (at any time)

**Comment by frostming** [comment]
> I think `--unconstrained` should just be "only ignore contsraints" as its semantics implies.


`--unconstraints` removes all constraints, only only lower bounds, but also upper bounds and pins. Then how would it make sense if we only ignore without updating them?

We would ignore `<X` constraint and update to an version higher than X, shouldn't `pyproject.toml` be updated to keep an valid requirements-lock pair?

**Comment by frostming** [comment]
Another aspect is to consider when you will need an update to `pyproject.toml`? For a library, the version bounds that used to work should keep working, you only need to update the lockfile to update the package versions in your working set. If you believe a package version doesn't work any more and you need to update the lower bounds, just `pdm update --unconstraints <package>[ <package2>...]` to update for the single packages. I don't think there will be any case you need to update and rewrite the version bounds for all packages.

**Comment by vitidev** [comment]
> Another aspect is to consider when you will need an update to `pyproject.toml`?

For library development it doesn't make sense.

For app development (solo)... it's better to have (if possible) the latest versions of packages - perhaps there are closed vulnerabilities, fixed some bugs, new features, etc. So the need to update is clear - actually `pdm update` updates packages if constraints are allowed

1 update packages
2 fix if something is broken
3 Actually already here I don’t need old versions of packages. And if I develop new features, then all the more I lose guarantees that it will work with the versions specified in the `pyproject.toml`

So for me the most obvious step is to update the constraints in pyproject.toml

`pdm update -u` will affect those versions that cannot be updated (==/<)
And manually specifying all the package names `pdm update --unconstraints <package>[ <package2>...]`....is tedious - because I don’t even know which packages have been updated,  it's easier to parse pyproject.toml and extract from there everything with >= and actualize

**Comment by frostming** [comment]
> For library development it doesn't make sense.

Agree, but why it does for applications? There are pdm.lock to track the **working** combination of package versions and you only need to update that. If you care about the version ranges in `pyproject.toml` much, then the same rule for library development applies. That is, for an application, what you do want to tell by the version ranges in the `pyproject.toml`? If you already have a lockfile?

**Comment by frostming** [comment]
> After all, I already have a working set of dependencies. And I can just reflect it in pyproject.toml

If this is your workflow, then I would recommend using pinned versions for all deps in `pyproject.toml` and run `pdm update --unconstrained --save-exact` to update them.

**Comment by vitidev** [comment]
> Since you do not care about the other versions of a specific package the versions ranges are useless to you.

You are not quite right. I still need pinned versions. I just need to update >= contraints
In general, this is how `pdm update` works. I just want to additionally reflect the updated versions in `pyproject.toml` (the reasons I described above - these versions may well become irrelevant and I do not want to manually deal with this)

**Comment by frostming** [comment]
So that's it, for consistency, we will not treat pinned versions and version ranges differently. If we ignore constraints, we ignore(and rewrite) them all.  Though your workflow may be a little unique, we still provide a way to make it work(pdm update with selected packages). I think it's enough to resolve this feature request.

**Comment by vitidev** [comment]
> If we ignore constraints, we ignore(and rewrite) them all. 

I don't ignore constraints. Never.
I am using `pdm update` (without `--unconstrained`). Obviously, this command only updates >=, which is the expected workflow by design (is not it so?)

And after checked that everything works fine I sync updated constraints `pdm.lock -> pyproject.toml`. I see no reason not to. This is not library development.

While manually. And if pdm doesn't provide the required functionality... well, I'll write a plugin, or, if I can't, then just a python script for this.

**Comment by frostming** [comment]
> Obviously, this command only updates >=, which is the expected workflow by design (is not it so?)

Of course, if a version is pinned, how can the version be updated?



> I see no reason not to. This is not library development.

The reason has been explained above. IMHO, on the contrary, updating the lower bounds isn't library development.
