### ISSUE TITLE
Changelog and Contributing pages blank in latest version of docs

### ISSUE THREAD

**Issue by inigohidalgo** [pdm-project/pdm#2040]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

Changelog and Contributing is missing from 2.7 version of docs. I navigate to either https://pdm.fming.dev/2.7/dev/changelog/ or https://pdm.fming.dev/latest/dev/changelog/ (and the same for contributing) and I am presented with an empty page. 2.6 page works fine: https://pdm.fming.dev/2.6/dev/changelog/

![image](https://github.com/pdm-project/pdm/assets/20395965/249763c7-875c-4425-b87e-69e656f67e9a)

It is accessible in the repository as always though [Changelog.md](https://github.com/pdm-project/pdm/blob/main/CHANGELOG.md)

P.D: Unrelated but I wanted to thank you again for such an awesome project. We are in the process of migrating all our projects running in production to use PDM <3

**Comment by frostming** [comment]
It might be broken by dependency updates, I tried downgrading the dependency versions to the same as 2.6.x and it works. @pawamoy do you have any clue?

**Comment by frostming** [comment]
Ok, find it: https://facelessuser.github.io/pymdown-extensions/about/changelog/#100
