### ISSUE TITLE
Add project path argument while running pdm venv command

### ISSUE THREAD

**Issue by zhupengjia** [pdm-project/pdm#2042]
## Is your feature request related to a problem? Please describe.

I often find it frustrating when trying to run the pdm venv command without being able to specify the project path. Currently, the command assumes that the project is located in the current working directory, which can be inconvenient in certain scenarios.

## Describe the solution you'd like

I would like to propose adding a project path argument to the pdm venv command. This would allow users to specify the path to their project directory when creating a virtual environment. This feature would provide more flexibility and convenience, especially for projects that are not located in the current working directory.

By adding the project path argument, users can easily create virtual environments for projects located in different directories without having to navigate to each project's directory first. This would streamline the workflow and save time for developers working with multiple projects simultaneously.

Overall, the addition of the project path argument to the pdm venv command would greatly enhance the usability and flexibility of the PDM tool.

**Comment by frostming** [comment]
SGTM, I will leave it as contributor friendly and PR is welcomed.

It would be as easy as adding the `project_option` to the options list at: https://github.com/pdm-project/pdm/blob/f08b414fc0d15023e5116462c2a32405dd4c893b/src/pdm/cli/commands/venv/__init__.py#L20
