### ISSUE TITLE
No module named 'pdm' after failing to update

### ISSUE THREAD

**Issue by berzi** [pdm-project/pdm#2070]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

I failed to install with `pdm self update` for unclear reasons (probably lacking permissions). After that, any pdm command (including a bare `pdm`) fails with
> Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "...mypythonpath...\Scripts\pdm.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'pdm'

## Environment Information

Windows 11

Python 3.11

`pdm info` commands fail.

**Comment by frostming** [comment]
It is expected when you abort in the middle of an update. Remove and re-install please.

**Comment by berzi** [comment]
That's what I did but it's not really great developer/user experience. If there's no way to avoid it the message should at least be clearer, less experienced devs won't be able to tell what's wrong.

**Comment by pawamoy** [comment]
There's nothing PDM can do here.

You still have the PDM shim on your system, but PDM is not installed, so Python tells you "module not found".

```
Traceback (most recent call last):
File "", line 198, in _run_module_as_main
File "", line 88, in run_code
File "...mypythonpath...\Scripts\pdm.exe_main.py", line 4, in
ModuleNotFoundError: No module named 'pdm'
```

That's a broken state, and it it is not supposed to happen. If it does, the solution is to clean up the environment (remove any left overs if needed, and reinstall PDM).
