### ISSUE TITLE
Clarify what `--no-isolated` does

### ISSUE THREAD

**Issue by sanmai-NL** [pdm-project/pdm#2071]
The current docs list a parameter common to many of PDM's subcommands:

> --no-isolation: Do not isolate the build in a clean environment

What does this really do, however? Can it be described more concretely/technically?

**Comment by frostming** [comment]
Here is the pip's help message:

```
--no-build-isolation        Disable isolation when building a modern source distribution. Build dependencies
                              specified by PEP 518 must be already installed if this option is used.
```
Is it more clear?

**Comment by sanmai-NL** [comment]
Thanks, yes, but what is a modern source distribution?

**Comment by frostming** [comment]
> but what is a modern source distribution?

One that follows PEP-517 build system standard.

**Comment by sanmai-NL** [comment]
I'll author a PR with your clarifications.

**Comment by frostming** [comment]
@sanmai-NL Are you still going to work on this?

**Comment by sanmai-NL** [comment]
Yes.
