### ISSUE TITLE
Unable to install pyinstaller new version use pdm.

### ISSUE THREAD

**Issue by hxse** [pdm-project/pdm#2074]
`pdm run python -V`
Python 3.11.4

`pip -V`
pip 23.1.2 (python 3.11)

`pdm add pyinstaller`
`pdm show`
pyinstaller │ 4.5.1

`pip install pyinstaller`
`pip list`
pyinstaller 5.13.0

Why are the versions different of isntall pyinstaller by pdm and pip?
The test project is empty "hello world" and there is no other library dependence, It's so strange.

**Comment by frostming** [comment]
`pyinstaller 5.13.0` has a upper bound for `requires-python`: `>=3.7,<3.13` so you have to include the `<3.13` in your project `requires-python` as well. This is how a cross-version package manger differs from pip which only cares about the current version.

You can read the reason why you need to do this at https://pdm.fming.dev/latest/usage/project/#set-requires-python-value
