### ISSUE TITLE
Add a way of excluding/including certain files from the resulting wheel

### ISSUE THREAD

**Issue by jfrere** [pdm-project/pdm#2087]
## Is your feature request related to a problem? Please describe.

I have a project with in-source tests (i.e. inside the `myproject/` directory, there are both `myproject/server.py` and `myproject/server_test.py`).  Currently, the test files end up in the built wheel, but there is no need for them to be in there.

## Describe the solution you'd like

I would like to be able to set a key in my `pyproject.toml` file that allows me to exclude (and presumably include in other situations) certain files.  E.g.

```toml
[tool.pdm]
exclude = ["**/*_test.py"]
```

(If this is already possible, could it be documented more clearly?  I had a look, and I think this is explicitly not included in e.g. PEP 621, and I couldn't find any PDM-specific documentation on the website.)

Thanks!

**Comment by frostming** [comment]
You need to understand that PDM is just a front-end for building, without knowing any configuration of the build process.
Moreover, it supports [many build backends](https://pdm.fming.dev/2.8/reference/build/#build-configuration) and the configurations may vary in different backends. Read the docs for corresponding backend for how to do it.

For example, if you use `pdm-backend`, the configuration would be: https://pdm-backend.fming.dev/build_config/#include-or-exclude-files

```toml
[tool.pdm.build]
excludes = ["**/*_test.py"]
```

Closing for not related to this project.
