### ISSUE TITLE
Failure to self update and inconsistent version info reported

### ISSUE THREAD

**Issue by Mjboothaus** [pdm-project/pdm#2091]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

```
PDM 0.1.dev1+ga5ddca6 is installed, while 2.8.0a2 is available.
Please run `pdm self update` to upgrade.
Run `pdm config check_update false` to disable the check.

(horse-logic-3.11) mjboothaus@Michaels-Laptop horse-logic % pdm --version
PDM, version 2.7.4

(horse-logic-3.11) mjboothaus@Michaels-Laptop horse-logic % pdm self update
[ChunkedEncodingError]: ('Connection broken: IncompleteRead(36603 bytes read, 344 more expected)', IncompleteRead(36603 bytes read, 344 more expected))
Add '-v' to see the detailed traceback

(horse-logic-3.11) mjboothaus@Michaels-Laptop horse-logic % pdm self update -v

Traceback (most recent call last):
  File "/Users/mjboothaus/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/mjboothaus/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 289, in main
    return Core().main(args)
           ^^^^^^^^^^^^^^^^^
  File "/Users/mjboothaus/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 207, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/Users/mjboothaus/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 202, in main
    self.handle(project, options)
  File "/Users/mjboothaus/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/Users/mjboothaus/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/commands/self_cmd.py", line 234, in handle
    version = get_latest_pdm_version_from_pypi(project, options.pre)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mjboothaus/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/actions.py", line 290, in get_latest_pdm_version_from_pypi
    candidate = finder.find_best_match("pdm", allow_prereleases=prereleases).best
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mjboothaus/.local/pipx/venvs/pdm/lib/python3.11/site-packages/unearth/finder.py", line 357, in find_best_match
    best_match = next(iter(applicable_candidates), None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mjboothaus/.local/pipx/venvs/pdm/lib/python3.11/site-packages/unearth/finder.py", line 294, in _find_packages_from_requirement
    yield from self._find_packages(requirement.name, allow_yanked, hashes)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mjboothaus/.local/pipx/venvs/pdm/lib/python3.11/site-packages/unearth/finder.py", line 263, in _find_packages
    return sorted(all_packages, key=self._sort_key, reverse=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mjboothaus/.local/pipx/venvs/pdm/lib/python3.11/site-packages/unearth/collector.py", line 135, in collect_links_from_location
    yield from _collect_links_from_index(session, location)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mjboothaus/.local/pipx/venvs/pdm/lib/python3.11/site-packages/unearth/collector.py", line 155, in _collect_links_from_index
    page = fetch_page(session, location)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mjboothaus/.local/pipx/venvs/pdm/lib/python3.11/site-packages/unearth/collector.py", line 142, in fetch_page
    resp = _get_html_response(session, location)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mjboothaus/.local/pipx/venvs/pdm/lib/python3.11/site-packages/unearth/collector.py", line 177, in _get_html_response
    resp = session.get(
           ^^^^^^^^^^^^
  File "/Users/mjboothaus/.local/pipx/venvs/pdm/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mjboothaus/.local/pipx/venvs/pdm/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mjboothaus/.local/pipx/venvs/pdm/lib/python3.11/site-packages/requests/sessions.py", line 747, in send
    r.content
  File "/Users/mjboothaus/.local/pipx/venvs/pdm/lib/python3.11/site-packages/requests/models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mjboothaus/.local/pipx/venvs/pdm/lib/python3.11/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(36603 bytes read, 344 more expected)', IncompleteRead(36603 bytes read, 344 more expected))
```

## Steps to reproduce

See commands listed inline above.

## Actual behavior

See output above

## Expected behavior

Expected the the reported version in initial output above would match the output from `pdm --version`.

Not `PDM 0.1.dev1+ga5ddca6` vs `PDM, 2.7.4`

Also that self update would successfully update PDM or exit gracefully.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.7.4
Python Interpreter:
  /Users/mjboothaus/code/github/databooth/horse-logic/.venv/bin/python (3.11)
Project Root:
  /Users/mjboothaus/code/github/databooth/horse-logic
Local Packages:
  
/Users/mjboothaus/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/actions.py:307: RuntimeWarning: Failed to get latest version: ('Connection broken: IncompleteRead(36603 bytes read, 344 more expected)', IncompleteRead(36603 bytes read, 344 more expected))
  warnings.warn(f"Failed to get latest version: {e}", RuntimeWarning, stacklevel=1)
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.2",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "22.5.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000",
  "python_full_version": "3.11.2",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}
/Users/mjboothaus/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/actions.py:307: RuntimeWarning: Failed to get latest version: ('Connection broken: IncompleteRead(36603 bytes read, 344 more expected)', IncompleteRead(36603 bytes read, 344 more expected))
  warnings.warn(f"Failed to get latest version: {e}", RuntimeWarning, stacklevel=1)
```

**Comment by frostming** [comment]
I am not clear what is going on your computer and it may highly depend on your personal setup. The best effort we can do is to remove all PDM-related library files and re-install it and see if it recovers.

**Comment by vvanglro** [comment]
Maybe it has something to do with this. [Latest release of requests causes urllib3 to throw an error](https://github.com/psf/requests/issues/6443)

The same happens in the comments: https://github.com/psf/requests/issues/6443#issuecomment-1568210854

**Comment by Mjboothaus** [comment]
Ok sure.

I did do a uninstall/reinstall without success i.e. the Bug report was
provided after I did this.

**Comment by Mjboothaus** [comment]
p.s. I have it installed via pipx i.e.:

   package pdm 2.7.4, installed using Python 3.11.4
    - pdm

**Comment by Mjboothaus** [comment]
Also I uninstalled the pipx version and did a brew install and I'm still
getting errors (I don't think it is environment specific as the brew
version should be completely isolated) - output below - cheers:

(horse-logic-3.11) ***@***.*** horse-logic % pdm info && pdm
info --env
PDM version:
  2.7.4
Python Interpreter:
  /Users/mjboothaus/code/github/databooth/horse-logic/.venv/bin/python
(3.11)
Project Root:
  /Users/mjboothaus/code/github/databooth/horse-logic
Local Packages:

/opt/homebrew/Cellar/pdm/2.7.4/libexec/lib/python3.11/site-packages/pdm/cli/actions.py:307:
RuntimeWarning: Failed to get latest version: ('Connection broken:
IncompleteRead(36603 bytes read, 344 more expected)', IncompleteRead(36603
bytes read, 344 more expected))
  warnings.warn(f"Failed to get latest version: {e}", RuntimeWarning,
stacklevel=1)
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.2",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "22.5.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24
PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000",
  "python_full_version": "3.11.2",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}
/opt/homebrew/Cellar/pdm/2.7.4/libexec/lib/python3.11/site-packages/pdm/cli/actions.py:307:
RuntimeWarning: Failed to get latest version: ('Connection broken:
IncompleteRead(36603 bytes read, 344 more expected)', IncompleteRead(36603
bytes read, 344 more expected))
  warnings.warn(f"Failed to get latest version: {e}", RuntimeWarning,
stacklevel=1)

**Comment by Mjboothaus** [comment]
Finally, if for example I do pdm list the command runs find, but it looks
like it is trying to check for the current available update version and
failing on this step.

(horse-logic-3.11) ***@***.*** horse-logic % pdm list
╭──────────────────────────┬──────────┬──────────╮
│ name                     │ version  │ location │
├──────────────────────────┼──────────┼──────────┤
│ pathspec                 │ 0.11.1   │          │
│ setuptools               │ 68.0.0   │          │
│ rfc3339-validator        │ 0.1.4    │          │
│ appnope                  │ 0.1.3    │          │
│ Pillow                   │ 9.5.0    │          │
│ pyrsistent               │ 0.19.3   │          │
│ wcwidth                  │ 0.2.6    │          │
│ fqdn                     │ 1.5.1    │          │
│ decorator                │ 5.1.1    │          │
│ notebook                 │ 6.5.4    │          │
│ Jinja2                   │ 3.1.2    │          │
│ jupyter_client           │ 8.2.0    │          │
│ pandocfilters            │ 1.5.0    │          │
│ ptyprocess               │ 0.7.0    │          │
│ isoduration              │ 20.11.0  │          │
│ cfgv                     │ 3.3.1    │          │
│ fsspec                   │ 2023.6.0 │          │
│ tinycss2                 │ 1.2.1    │          │
│ pandera                  │ 0.14.5   │          │
│ bleach                   │ 6.0.0    │          │
│ webencodings             │ 0.5.1    │          │
│ pyzmq                    │ 25.1.0   │          │
│ python-dateutil          │ 2.8.2    │          │
│ pre-commit               │ 3.3.3    │          │
│ attrs                    │ 23.1.0   │          │
│ Pygments                 │ 2.15.1   │          │
│ pytz                     │ 2023.3   │          │
│ asttokens                │ 2.2.1    │          │
│ tornado                  │ 6.3.2    │          │
│ python-json-logger       │ 2.0.7    │          │
│ jupyter_server_terminals │ 0.4.4    │          │
│ defusedxml               │ 0.7.1    │          │
│ jsonpointer              │ 2.4      │          │
│ pickleshare              │ 0.7.5    │          │
│ stack-data               │ 0.6.2    │          │
│ nest-asyncio             │ 1.5.6    │          │
│ jupyter-events           │ 0.6.3    │          │
│ parso                    │ 0.8.3    │          │
│ executing                │ 1.2.0    │          │
│ six                      │ 1.16.0   │          │
│ mypy-extensions          │ 1.0.0    │          │
│ kiwisolver               │ 1.4.4    │          │
│ contourpy                │ 1.1.0    │          │
│ filelock                 │ 3.12.2   │          │
│ typing-inspect           │ 0.9.0    │          │
│ click                    │ 8.1.3    │          │
│ webcolors                │ 1.13     │          │
│ virtualenv               │ 20.23.1  │          │
│ argon2-cffi              │ 21.3.0   │          │
│ tzdata                   │ 2023.3   │          │
│ debugpy                  │ 1.6.7    │          │
│ nodeenv                  │ 1.8.0    │          │
│ arrow                    │ 1.2.3    │          │
│ idna                     │ 3.4      │          │
│ platformdirs             │ 3.5.3    │          │
│ pycparser                │ 2.21     │          │
│ distlib                  │ 0.3.6    │          │
│ piicodev                 │ 1.10.0   │          │
│ comm                     │ 0.1.3    │          │
│ wrapt                    │ 1.15.0   │          │
│ pure-eval                │ 0.2.2    │          │
│ backcall                 │ 0.2.0    │          │
│ cycler                   │ 0.11.0   │          │
│ fastparquet              │ 2023.7.0 │          │
│ matplotlib-inline        │ 0.1.6    │          │
│ notebook_shim            │ 0.2.3    │          │
│ terminado                │ 0.17.1   │          │
│ cramjam                  │ 2.6.2    │          │
│ ipython-genutils         │ 0.2.0    │          │
│ multimethod              │ 1.9.1    │          │
│ beepy                    │ 1.0.7    │          │
│ PyYAML                   │ 6.0      │          │
│ beautifulsoup4           │ 4.12.2   │          │
│ packaging                │ 23.1     │          │
│ jupyterlab-pygments      │ 0.2.2    │          │
│ nbconvert                │ 7.5.0    │          │
│ jupyter_server           │ 2.6.0    │          │
│ nbclassic                │ 1.0.0    │          │
│ websocket-client         │ 1.5.3    │          │
│ pexpect                  │ 4.8.0    │          │
│ typing_extensions        │ 4.6.3    │          │
│ cffi                     │ 1.15.1   │          │
│ psutil                   │ 5.9.5    │          │
│ tokenize-rt              │ 5.1.0    │          │
│ uri-template             │ 1.2.0    │          │
│ nbformat                 │ 5.9.0    │          │
│ pigpio                   │ 1.78     │          │
│ jupyter_core             │ 5.3.1    │          │
│ smbus2                   │ 0.4.2    │          │
│ rfc3986-validator        │ 0.1.1    │          │
│ pandas                   │ 2.0.3    │          │
│ prompt-toolkit           │ 3.0.38   │          │
│ numpy                    │ 1.24.3   │          │
│ argon2-cffi-bindings     │ 21.2.0   │          │
│ Send2Trash               │ 1.8.2    │          │
│ simpleaudio              │ 1.0.4    │          │
│ sniffio                  │ 1.3.0    │          │
│ soupsieve                │ 2.4.1    │          │
│ prometheus-client        │ 0.17.0   │          │
│ overrides                │ 7.3.1    │          │
│ nbclient                 │ 0.8.0    │          │
│ fastjsonschema           │ 2.17.1   │          │
│ mistune                  │ 2.0.5    │          │
│ black                    │ 23.3.0   │          │
│ ipykernel                │ 6.23.2   │          │
│ pydantic                 │ 1.10.9   │          │
│ anyio                    │ 3.7.0    │          │
│ matplotlib               │ 3.7.2    │          │
│ MarkupSafe               │ 2.1.3    │          │
│ pyparsing                │ 3.0.9    │          │
│ fonttools                │ 4.40.0   │          │
│ jedi                     │ 0.18.2   │          │
│ ipython                  │ 8.14.0   │          │
│ identify                 │ 2.5.24   │          │
│ traitlets                │ 5.9.0    │          │
│ jsonschema               │ 4.17.3   │          │
╰──────────────────────────┴──────────┴──────────╯
/opt/homebrew/Cellar/pdm/2.7.4/libexec/lib/python3.11/site-packages/pdm/cli/actions.py:307:
RuntimeWarning: Failed to get latest version: ('Connection broken:
IncompleteRead(36603 bytes read, 344 more expected)', IncompleteRead(36603
bytes read, 344 more expected))
  warnings.warn(f"Failed to get latest version: {e}", RuntimeWarning,
stacklevel=1)

**Comment by vvanglro** [comment]
@Mjboothaus 
Hi, Let's do the following to see if we can fix the problem:
```sh
/opt/homebrew/Cellar/pdm/2.7.4/libexec/bin/python -m pip install requests==2.29.0
```

**Comment by Mjboothaus** [comment]
Hi

Yes downgrading to `requests==2.29.0` seems to have fixed the problem.

Thank you

Output is now:

(horse-logic-3.10) ***@***.*** horse-logic % pdm info && pdm
info --env
PDM version:
  2.7.4
Python Interpreter:
  /Users/mjboothaus/code/github/databooth/horse-logic/.venv/bin/python
(3.10)
Project Root:
  /Users/mjboothaus/code/github/databooth/horse-logic
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.10.12",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "22.5.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24
PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000",
  "python_full_version": "3.10.12",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}

Also

horse-logic-3.10) ***@***.*** horse-logic % pdm self update

returns

Already up-to-date: 2.7.4

**Comment by vvanglro** [comment]
> Hi Yes downgrading to `requests==2.29.0` seems to have fixed the problem. Thank you Output is now: 

@Mjboothaus Hi. Glad to have it sorted out. Before downloading the specified version of `reqeusts`, have you ever tried to change the network or use a proxy to execute `pdm self update`? If you try, will it still be the same error? This will help to troubleshoot the problem, thank you.

**Comment by frostming** [comment]
I guess the issue is gone if you clean the caches by `pdm cache clear`(with requests>2.29)

**Comment by Mjboothaus** [comment]
Hi - I have subsequently updated requests to 2.31.0 and it runs fine (I did
not need to run `pdm cache clear`)

I realised that the other issue I reported with the difference in version
numbers issue was related to the running of the pre-commit hook for pdm
export that I have running which was pointing to an earlier revision
(2.4.9).

I assume this hook should point to the same version as the current
installed version of pdm (as returned by `pdm --version`)?
