### ISSUE TITLE
Parsing failure for git dependency with version speficier

### ISSUE THREAD

**Issue by adriangb** [pdm-project/pdm#2093]
```
pdm add 'git+https://github.com/python/typing_extensions.git ; python_version >= "3.8"'
```
Fails with

```
[RequirementError]: Invalid marker: Expected a marker variable or quoted string
     ; python_version >= "3.8"
     ^
```

On the other hand `pip install 'git+https://github.com/python/typing_extensions.git ; python_version >= "3.8"'` works fine.

I noticed that if I remove the `;` PDM parses correctly but doesn't consider the environment marker:

```
Unable to find a resolution because the following dependencies don't work on all Python versions in the range of the project's `requires-python`: >=3.7.
``` 

Which is true but means that the `python_version >= "3.8"` part was ignored.

**Comment by frostming** [comment]
According to PEP 508, you are missing the name part, to fix it:

```
typing-extensions @ git+https://github.com/python/typing_extensions.git ; python_version >= "3.8"
```

This is behavior of `packaging.requirements`.

**Comment by adriangb** [comment]
Thanks!!
