### ISSUE TITLE
Allow setting custom venv path

### ISSUE THREAD

**Issue by DeD1rk** [pdm-project/pdm#2096]
## Is your feature request related to a problem? Please describe.

I would like to install a venv outside of the project root, but need the location to still be easily predictable. Specifically, I need this in a Dockerfile so I can copy out the venv to a different stage. Installing in the project root is not practical for me, and the location generated when using a named venv (which includes the hash of the project location) is unpredictable, so I can't refer to it easily in the next stage of a multi-stage dockerfile.

## Describe the solution you'd like

It would be great if we can specify a custom path of a venv to use. For example, it would be great if I can specify with e.g. `pdm sync --venv-path /opt/venv` that a venv should be used/created (although having to create it first with `pdm venv create --venv-path /opt/venv` would be fine too) at `/opt/venv`.

**Comment by frostming** [comment]
Create it manually and point to it later:

```bash
python3 -m venv /path/to/my/venv
pdm use -f /path/to/my/venv
```

**Comment by DeD1rk** [comment]
Oh wow, I had no idea that was possible, thanks! Might be nice to add a note to the documentation around https://pdm.fming.dev/latest/usage/venv/#create-a-virtualenv-yourself?
