### ISSUE TITLE
显示一下下载进度，下载速度，

### ISSUE THREAD

**Issue by fushun1990** [pdm-project/pdm#2104]
## Describe the solution you'd like

![image](https://github.com/pdm-project/pdm/assets/10917744/63160eb4-12aa-48f2-9ad3-d2faec895d06)
1、显示一下下载进度，下载速度，
2、我不需要安装项目本身，每次都需要带参数，可以在配置文件中配置最好了

**Comment by frostming** [comment]
> 显示一下下载进度，下载速度，

No, the downloading is performed in parallel behind a spinner, where we cannot display a progress bar.



> 我不需要安装项目本身，每次都需要带参数，可以在配置文件中配置最好了

https://pdm.fming.dev/latest/usage/config/#passing-constant-arguments-to-every-pdm-invocation
