### ISSUE TITLE
2.8.0: Failing tests due to `Unknown format: pep561-stub-name`

### ISSUE THREAD

**Issue by dvzrv** [pdm-project/pdm#2107]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Hi! I'm currently trying to upgrade to 2.8.0 on Arch Linux. This unfortunately fails on a bunch of tests due to `Unknown format: pep561-stub-name`.

The previous build script can be found here: https://gitlab.archlinux.org/archlinux/packaging/packages/python-pdm/-/blob/d32a76cfd264cd12457b5838ccf107a8a3ff5009/PKGBUILD
The new one only differs in so far, that I have switched to using auto-generated Github tarballs with the help of `PDM_BUILD_SCM_VERSION`, since we are starting to discourage the use of PyPi distribution wide.

## Actual behavior

[python-pdm-2.8.0-1-x86_64-all.log](https://github.com/pdm-project/pdm/files/12061190/python-pdm-2.8.0-1-x86_64-all.log)

[python-pdm-2.8.0-1-x86_64-check.log](https://github.com/pdm-project/pdm/files/12061183/python-pdm-2.8.0-1-x86_64-check.log)

## Expected behavior

Tests do not fail.

## Environment Information

I'm building against Python 3.11.4 and using the release tarball for pdm 2.8.0 (with pdm-backend 2.1.4 - tested with vendored and devendored versions). More information on used versions of dependencies can be found in the above "all" log.

**Comment by dvzrv** [comment]
FWIW, the affected tests seem to be:

- tests/cli/test_hooks.py::test_hooks
- tests/cli/test_hooks.py::test_skip_all_option_from_signal
- tests/cli/test_hooks.py::test_skip_option_from_signal
- tests/cli/test_hooks.py::test_skip_pre_post_option_from_signal
- tests/cli/test_run.py::test_pep582_launcher_for_python_interpreter
- tests/models/test_candidates.py::test_cache_vcs_immutable_revision

**Comment by frostming** [comment]
You seem to be using an outdated version of pdm-backend, can you update it first?

**Comment by dvzrv** [comment]
Arch Linux ships pdm-backend 2.1.4 (which was released a bit earlier than pdm 2.8.0).

Seeing something like the following in the logs makes me believe the test environment installs some verison of pdm-backend on its own though:

```
/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.11/site-packages/pdm/backend/_vendor/validate_pyproject/_vendor/fastjsonschema/generator.py
```

**Comment by frostming** [comment]
How do you get the test environment?
2.1.4 doesn't ship that file as can be seen here: https://pypi-browser.org/package/pdm-backend/pdm_backend-2.1.4-py3-none-any.whl

**Comment by dvzrv** [comment]
> The previous build script can be found here: https://gitlab.archlinux.org/archlinux/packaging/packages/python-pdm/-/blob/d32a76cfd264cd12457b5838ccf107a8a3ff5009/PKGBUILD

Currently I'm building/ testing as follows:
https://gitlab.archlinux.org/archlinux/packaging/packages/python-pdm/-/blob/6b5dfd53b9cc62e530feab9a46fbdb6fd6bc9f3a/PKGBUILD

**Comment by frostming** [comment]
It turned out to be an old version of pdm-backend used by the test fixtures, but I've got no idea why it passes CI but fails your build.

**Comment by dvzrv** [comment]
> It turned out to be an old version of pdm-backend used by the test fixtures, but I've got no idea why it passes CI but fails your build.

Why is pdm-backend from the environment I build in not used though? Are these special use-case tests somehow?
Why can they not use my system-provided pdm-backend?

> @dvzrv can you revert the PKGBUILD after the bugfix is released?

If by revert you mean "run the deselected tests again" once you have made a release, then yes!
