### ISSUE TITLE
pycharm lock 文件显示问题

### ISSUE THREAD

**Issue by A2Data** [pdm-project/pdm#2116]
如图所示，名字改为  poetry 就可以正常显示，而 pdm.lock 就不可以，非常难受，怎么设置一下呢

![image](https://github.com/pdm-project/pdm/assets/39373008/00de0b08-2835-4f9c-8d08-ac8df2699b52)

**Comment by frostming** [comment]
It's pycharm not supporting PDM file icon, why report here?
