### ISSUE TITLE
关于环境路径异常的问题

### ISSUE THREAD

**Issue by A2Data** [pdm-project/pdm#2118]
我搜索了关于这类的问题并没有找到想要的解答。

我在pycharme的ide下编辑，可以正常激活虚拟环境，也可以正常
pdm add & pdm install

但是我在run的时候 会导致路径找不到，
如下图，我困惑这个问题很久了，也尝试sys 引入根路径等尝试，都无效

但是我尝试使用编辑器引入本地python3.11.3 运行时确是正常的。

而虚拟环境和pdm 使用的是 3.10.12

希望可以得到解答

![image](https://github.com/pdm-project/pdm/assets/39373008/3555ca86-ef1c-403c-9c62-4461d4422068)

![image](https://github.com/pdm-project/pdm/assets/39373008/8b4e731d-4043-4cac-b98f-19d255cab585)

**Comment by frostming** [comment]
You are running under the directory `fast_dev`, how can it find `fast_dev` module? It just doesn't exist there.

**Comment by frostming** [comment]
Not related to PDM, closing it now.
