### ISSUE TITLE
Different  `requires-python` for a development dependency group

### ISSUE THREAD

**Issue by veghdev** [pdm-project/pdm#2119]
## Is your feature request related to a problem? Please describe.

My library works with a wide range of python versions (for example  requires-python = ">=3.6") because using a few dependencies only, but I am using a lot of development dependencies for testing, generating the documentation site etc.

I would like to use pdm to package and publish my lib and don`t want to create a lock file for it.
But iI would like to manage/lock our development dependencies with pdm, so I run the lock command with these flags:
`pdm lock --no-default -d`

It's not working, because it tries to lock the development dependencies with python >=3.6 too.

## Describe the solution you'd like

I think it is a valid use case, and it could be useful if we can define a different subset of python versions for a development dependency group (for example the project requires-python = ">=3.6", and the dev requires-python = ">=3.10"), especially when only need the development dependencies to lock (`--no-default -d`).

PDM, version 2.8.0

**Comment by frostming** [comment]
Add (for example) `; python_version >= '3.10'` to these dependencies.

**Comment by veghdev** [comment]
Thank you.
