### ISSUE TITLE
docs: Explain a difference between project.scripts and tool.pdm.scripts

### ISSUE THREAD

**Issue by Fak3** [pdm-project/pdm#2121]
## Is your feature request related to a problem? Please describe.

In the current "usage" section of documentation, I struggled to find any information on how to build a package which provides executable python script. There is currently a section called "pdm scripts": https://pdm.fming.dev/latest/usage/scripts/, which does not explain clearly that **[tool.pdm.scripts]** are not installed when someone else installs your package with pip. 

## Describe the solution you'd like

It would be helpful to add a note that pdm scripts are different from **[project.scripts]**. Having a note on top of https://pdm.fming.dev/latest/usage/scripts/ page would help to avoid confusion. For someone looking for installable console scripts, this note can provide a link to appropriate reference documentation: https://pdm.fming.dev/latest/reference/pep621/#console-scripts

**Comment by frostming** [comment]
Would you like to contribute that?

**Comment by Fak3** [comment]
Ok, I'll try to create a pull request

**Comment by baggiponte** [comment]
Hi, is this issue being worked on? If anyone needs, I'd gladly help out.

**Comment by frostming** [comment]
@baggiponte feel free to pick it up.

**Comment by baggiponte** [comment]
Thanks. I think I will add a callout/admonition below [this section](https://pdm-project.org/latest/usage/scripts/#user-scripts) redirecting to [the pypa pyproject.toml spec](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#creating-executable-scripts). WDYT?

**Comment by frostming** [comment]
@baggiponte No objection, but you don't need to ask, just submit a pull request directly and I will leave comments.
