### ISSUE TITLE
Error printed by `pdm install` for group not in lockfile may be confusing

### ISSUE THREAD

**Issue by whitequark** [pdm-project/pdm#2124]
It is useful to be able to install optional dependencies via their named specification when developing, to test the behavior of your package with these dependenies present. At the moment I can't seem to find a way to do this--despite being in the same namespace as dependency groups, the `-G` switch refuses to install optional dependencies.

Using `-G` is unambiguous so `-G` could probably be extended to support that, or another switch could be added instead.

**Comment by frostming** [comment]
Can you give an example of what you'd like to achieve? I can't extract it from reading the OP.

We also have a bunch of examples in the docs in case you miss it: https://pdm.fming.dev/latest/usage/dependency/#select-a-subset-of-dependency-groups-to-be-installed-or-locked

**Comment by whitequark** [comment]
Sorry, I guess my explanation was poorly written.

E.g. this:
```shell
$ git clone https://github.com/GlasgowEmbedded/glasgow
$ cd glasgow/software
$ pip install -e .[toolchain] # this works and installs the "toolchain" dependencies into the current venv or w/e
$ pdm install # this works but does not install "toolchain" dependencies into ./.venv. I would like it to do that
```

**Comment by frostming** [comment]
> [PdmUsageError]: Requested groups not in lockfile: toolchain

As it indicates, you can't install a group if it is not locked in lockfile in preceding steps. To add it, you can do: `pdm add -G toolchain`, or regenerate one: `pdm lock -G toolchain`.

**Comment by frostming** [comment]
pdm install and pdm sync only looks at the lockfile, and can't install packages not in it.

**Comment by whitequark** [comment]
Thank you. I misunderstood the error message, and indeed I see the behavior I'm asking for is already implemented.

May I suggest changing the error message for this case to be something like this?

     [PdmUsageError]: Requested groups not in lockfile: toolchain. Use `pdm add -G toolchain`

**Comment by whitequark** [comment]
Also, could you explain the rationale behind `pdm add -G`? I would never think that it would be applicable here, since the description states:

    Add package(s) to pyproject.toml and install them

and it seems like a reasonable conclusion that this command is useful only when you want to updating `pyproject.toml` and not when you want to update the lockfile.

**Comment by frostming** [comment]
> Also, could you explain the rationale behind `pdm add -G`?

`pdm add -G <group> <package>` means to add the `package` to group`group`, and update the lockfile. If you don't give the `package`, it's just to update the lockfile with the requested group.

In other words, `pdm lock` and `pdm add` are the only two commands that can update the `groups` recorded in the lockfile. If you encounter the error as the above, you should seek help from these commands

**Comment by whitequark** [comment]
Thanks. Feel free to close the issue if you think the error message for this case is good enough.
