### ISSUE TITLE
PDM commands complete successfully but won't terminate

### ISSUE THREAD

**Issue by HadilD** [pdm-project/pdm#2128]
When I run a pdm command like

- pdm sync
- pdm lock
- pdm add somepackage
- pdm install

The command completes successfully, but the process won't terminate on its own and I have to ctrl-C to kill it. For example, running a `pdm install` will create the lock file and install all dependencies specified in pyproject.toml sucessfully, and the command output would end in:

`🎉 All complete!`

Yet, I still need to kill it to stop the process.

## Environment Information

Output of `pdm info && pdm info --env` (even this command did not terminate):

```
PDM version:
  2.8.0
Python Interpreter:
  /home/hadil/proj/.venv/bin/python (3.7)
Project Root:
  /home/hadil/proj/
Local Packages:
```
OS: Debian GNU/Linux

I am not sure what other information I should provide, so please let me know.

**Comment by pawamoy** [comment]
Is there a traceback when you ctrl-c?

**Comment by frostming** [comment]
Try turn off the check_update feature by `pdm config check_update off`

**Comment by HadilD** [comment]
@pawamoy 

Here's a Traceback:

> 🎉 All complete!
> ^CTraceback (most recent call last):
>   File "/home/hadil/.local/bin/pdm", line 8, in <module>
>     sys.exit(main())
>   File "/home/hadil/.local/lib/python3.7/site-packages/pdm/core.py", line 290, in main
>     return Core().main(args or sys.argv[1:])
>   File "/home/hadil/.local/lib/python3.7/site-packages/pdm/core.py", line 220, in main
>     check_update(project)
>   File "/home/hadil/.local/lib/python3.7/site-packages/pdm/cli/actions.py", line 334, in check_update
>     latest_version = get_latest_version(project)
>   File "/home/hadil/.local/lib/python3.7/site-packages/pdm/cli/actions.py", line 315, in get_latest_version
>     latest_version = get_latest_pdm_version_from_pypi(project)
>   File "/home/hadil/.local/lib/python3.7/site-packages/pdm/cli/actions.py", line 300, in get_latest_pdm_version_from_pypi
>     candidate = finder.find_best_match("pdm", allow_prereleases=prereleases).best
>   File "/home/hadil/.local/lib/python3.7/site-packages/unearth/finder.py", line 357, in find_best_match
>     best_match = next(iter(applicable_candidates), None)
>   File "/home/hadil/.local/lib/python3.7/site-packages/unearth/finder.py", line 294, in _find_packages_from_requirement
>     yield from self._find_packages(requirement.name, allow_yanked, hashes)
>   File "/home/hadil/.local/lib/python3.7/site-packages/unearth/finder.py", line 263, in _find_packages
>     return sorted(all_packages, key=self._sort_key, reverse=True)
>   File "/home/hadil/.local/lib/python3.7/site-packages/unearth/collector.py", line 133, in collect_links_from_location
>     yield from _collect_links_from_index(session, location)
>   File "/home/hadil/.local/lib/python3.7/site-packages/unearth/collector.py", line 153, in _collect_links_from_index
>     page = fetch_page(session, location)
>   File "/home/hadil/.local/lib/python3.7/site-packages/unearth/collector.py", line 140, in fetch_page
>     resp = _get_html_response(session, location)
>   File "/home/hadil/.local/lib/python3.7/site-packages/unearth/collector.py", line 187, in _get_html_response
>     "Cache-Control": "max-age=0",
>   File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 600, in get
>     return self.request("GET", url, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 587, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 701, in send
>     r = adapter.send(request, **kwargs)
>   File "/home/hadil/.local/lib/python3.7/site-packages/cachecontrol/adapter.py", line 76, in send
>     resp = super().send(request, stream, timeout, verify, cert, proxies)
>   File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 499, in send
>     timeout=timeout,
>   File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 710, in urlopen
>     chunked=chunked,
>   File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 386, in _make_request
>     self._validate_conn(conn)
>   File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
>     conn.connect()
>   File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 358, in connect
>     self.sock = conn = self._new_conn()
>   File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 175, in _new_conn
>     (self._dns_host, self.port), self.timeout, **extra_kw
>   File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 85, in create_connection
>     sock.connect(sa)
> KeyboardInterrupt

**Comment by HadilD** [comment]
> Are you using a PyPI mirror for your project? Try turn off the check_update feature by `pdm config check_update off`

Yes, that fixes it. Thanks!

**Comment by frostming** [comment]
But that's also weird, since it can reuse the main index url your configured, it shouldn't have network issue if `lock` and `sync` both succeed.

**Comment by HadilD** [comment]
> But that's also weird, since it can reuse the main index url your configured, it shouldn't have network issue if `lock` and `sync` both succeed. It may be related to your network configuration, such as behind a proxy.

I am running the commands behind corporate VPN.

**Comment by frostming** [comment]
When checking for update, it will visit the default index(named `pypi`), make sure that can be accessed.

But anyway, turning off the `check_update` is an acceptable workaround. I will close this issue.
