### ISSUE TITLE
Add support for full conda environment detection 

### ISSUE THREAD

**Issue by gvariable** [pdm-project/pdm#2144]
## Is your feature request related to a problem? Please describe.

I'm new to `pdm`, and I recently created a project using `pdm init`. When setting up the project, I was prompted to select a Python interpreter. Since I'm using `conda` to manage my Python environment, I noticed that I could only choose the interpreter that is currently activated and not any other available interpreters.

I expected to have the option to choose from multiple Python interpreters installed through `conda`, but it seems that `pdm` only displays the interpreter that is currently activated in the terminal. This limitation restricts my ability to easily switch between different interpreter versions for my project.

Upon further examination of the pull request [#749 ](https://github.com/pdm-project/pdm/pull/749/files), I discovered that it specifically adds support for only the activated environment.

## Describe the solution you'd like

I perceive the solution to be relatively straightforward, with at least two possible approaches:

1. Similar to [#749 ](https://github.com/pdm-project/pdm/pull/749/files), the initial method entails locating the conda installation directory and subsequently searching for the specific directory, such as "envs", within the conda environment.
2. The second approach (preferred) entails checking if conda exists and utilizing a subprocess to execute the command "conda env list --json" in order to obtain the full paths of existing Python environments.3. 

Furthermore, I would like to address this issue if it is deemed necessary for the majority of users.

**Comment by frostming** [comment]
It should be easy to do with the new `find_python.register_provider` function introduced in [0.3.0](https://github.com/frostming/findpython/releases/tag/0.3.0)

And IMO it would be more appropriate to do in a plugin. Report it to [pdm-conda](https://github.com/macro128/pdm-conda) to see if anyone has interest or you could contribute it there.
