### ISSUE TITLE
Update pyproject.toml only

### ISSUE THREAD

**Issue by Wurstnase** [pdm-project/pdm#2149]
## Is your feature request related to a problem? Please describe.

Before https://github.com/pdm-project/pdm/commit/c4516c8d64d934debb4e758e8f1b5bd613c81357, a somehow hidden feature, I was able to update my pyproject.toml. 

## Describe the solution you'd like

I would like to update my pyproject.toml, without creating any lock-file. Maybe also without creating a virtual environment.

**Comment by frostming** [comment]
![image](https://github.com/pdm-project/pdm/assets/16336606/56484ba3-d600-450d-b861-f1a44fdfac49)

Closing it now.
