### ISSUE TITLE
Can create project with Python RC Version but all commands to work on the project fail (venv Can't Reslove python interpreter)

### ISSUE THREAD

**Issue by maltevesper** [pdm-project/pdm#2156]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. On Ubuntu Install python `3.11.0~rc1-1~22.04` 
2. Create a new project with pdm, and select the 3.11 interpreter from the list
3. Make sure the Project requests python>=3.11

## Actual behavior

Running subsequent commands results in an error stating that the python interpreter can not be resolved. Unless I change the project to a lower python interpreter, i.e. `python>=3.10` I am unable to use pdm.

```
pdm add -d pytest -v
Adding group dev to lockfile
Adding packages to dev dev-dependencies: pytest
The saved Python interpreter doesn't match the project's requirement. Trying to find another one.
python.use_venv is on, creating a virtualenv for this project...
[VirtualenvCreateError]: Can't resolve python interpreter
```

## Expected behavior

The release candidate interpreter is accepted

## Environment Information

```bash
pdm info && pdm info --env
python.use_venv is on, creating a virtualenv for this project...
[VirtualenvCreateError]: Can't resolve python interpreter
```

After modifying the project file,to accept python 3.10 I can generate actual output
```bash
Virtualenv /home/malte/projects/selenium-form/.venv is reused.
PDM version:
  2.8.2
Python Interpreter:
  /home/malte/projects/selenium-form/.venv/bin/python (3.11)
Project Root:
  /home/malte/projects/selenium-form
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.0c1",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.0-78-generic",
  "platform_system": "Linux",
  "platform_version": "#85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023",
  "python_full_version": "3.11.0rc1",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}
```

I assume it is since python identifies as `Python 3.11.0rc1` (python3.11 -V). Also updating python 3.11 to a non rc version resolved the issue.

**Comment by maltevesper** [comment]
#1377 looks slightly related, however, this seems mostly related to the rc in the python Version string

**Comment by maltevesper** [comment]
on second look this sticks out in pdm info: "implementation_version": "3.11.0c1", the c1 part looks like it might issues (without looking into the actual pdm code)

**Comment by frostming** [comment]
> 3\. Make sure the Project requests python>=3.11

According to the PEP 440 standard, `3.11.0rc1` is out of the range of `>=3.11`(prereleases are lower than 3.11.0), that may be a little different from semver.




> the c1 part looks like it might issues (without looking into the actual pdm code)

It's normal, it's how PEP 440 normalizes versions.

I suggest you read the PEP.

**Comment by maltevesper** [comment]
Thanks for pointing me to the pep. Taking a step back it all makes sense now.
