### ISSUE TITLE
-graph option in pdm list omits selected fields

### ISSUE THREAD

**Issue by carstencodes** [pdm-project/pdm#2161]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

I am running PDM 2.8.2 and want to produce a dependency graph and selecting the fields

## Steps to reproduce

In [pdm-bump](https://github.com/carstencodes/pdm-bump) on v0.8.0a1 run

```bash
$  pdm list --json --graph  --fields name,version,licenses,location
```

## Actual behavior

The JSON graph is printed with a list of default fields

## Expected behavior

The JSON graph is printed with a list of selected fields

**OR**

A warning is issued, that the fields command cannot be combined with --graph 
(Also noted in documentation)

## Environment Information

```bash
PDM version:
  2.8.2
Python Interpreter:
  /home/carsten/dev/python/pdm/plugins/pdm-bump/.venv/bin/python (3.9)
Project Root:
  /home/carsten/dev/python/pdm/plugins/pdm-bump
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.15",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.19.0-50-generic",
  "platform_system": "Linux",
  "platform_version": "#50-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 18:24:29 UTC 2023",
  "python_full_version": "3.9.15",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
graph doesn't work with `--fields` option.

**Comment by carstencodes** [comment]
Ok, good to know. But documentation does not provide any hint on this. Just a hint.

I'll see, what I can do.
