### ISSUE TITLE
PDM init in existing directory overwrite README.md and create src and tests directories

### ISSUE THREAD

**Issue by wagga40** [pdm-project/pdm#2163]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

`pdm init -n` or `pdm init` on any directory

## Actual behavior

```
$ mkdir test
$ cd test
$ echo "test" > README.md
$ ls -al
total 8
-rw-r--r--  1 user  user  5 Aug  3 07:19 README.md

$ pdm init -n                                                                
Creating a pyproject.toml for PDM...
Run command: ['/opt/homebrew/Cellar/pdm/2.8.2/libexec/bin/python3.11', '-m', 'virtualenv',
'/Users/user/Desktop/test/.venv', '-p', '/opt/homebrew/bin/python3.11', '--prompt=test-3.11', '--no-pip',
'--no-setuptools', '--no-wheel']
created virtual environment CPython3.11.4.final.0-64 in 27ms
  creator CPython3Posix(dest=/Users/user/Desktop/test/.venv, clear=False, no_vcs_ignore=False, global=False)
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
Virtualenv is created successfully at /Users/user/Desktop/test/.venv
Project is initialized successfully

$ ls -l                                                            
total 16
-rw-r--r--  1 user  user   18 Jul 31 08:41 README.md
drwxr-xr-x  3 user  user   96 Aug  3 07:21 __pycache__/
-rw-r--r--  1 user  user  232 Aug  3 07:21 pyproject.toml
drwxr-xr-x  3 user  user   96 Aug  3 07:21 src/
drwxr-xr-x  3 user  user   96 Aug  3 07:21 tests/

$ cat README.md
# example-package

```

`pdm init` with default answers produce the same results.
same commands with `pdm 2.7.0` don't create these directories. Nothing was found in the help or the docs to disable this.

## Expected behavior

README.md, src and tests directories should not overwrite existing ones.

## Environment Information

```bash
PDM version:
  2.8.2
Python Interpreter:
  /Users/user/Desktop/test/.venv/bin/python (3.11)
Project Root:
  /Users/user/Desktop/test
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.11.4",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "22.5.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023;
root:xnu-8796.121.3~7/RELEASE_ARM64_T6000",
  "python_full_version": "3.11.4",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
Are you willing to contribute? You can modify this function to ignore existing files:

https://github.com/pdm-project/pdm/blob/105221ab44d815d693e3310cdc8fcaf373a69a84/src/pdm/cli/templates/__init__.py#L91-L105

**Comment by frostming** [comment]
Somebody wants few but others want more. There are thousands of tastes and you can't make them all happy. Scaffolding is a reasonable and common feature for a package manager. More understanding and less complaints, please.

**Comment by frostming** [comment]
if you have trouble with the code that's okay i will do it. I'm just trying to attract some potential contributors as it is only me maintaining the project most of time.

**Comment by wagga40** [comment]
>  More understanding and less complaints, please.

I am sorry, I wasn't trying to make you angry. *Pdm* is great and I love it.
