### ISSUE TITLE
Python scripts not installed correctly when using `pdm install -d --no-isolation`

### ISSUE THREAD

**Issue by drunkwcodes** [pdm-project/pdm#2168]
- [v ] I have searched the issue tracker and believe that this is not a duplicate.

Please see https://github.com/drunkwcodes/mojopi/actions/runs/5757951393/job/15609764942,

pdm installed coverage and pytest successfully, but the console scripts did not found on Path.

`✔ Install coverage 7.2.7 successful`
 `✔ Install pytest 7.3.1 successful`

Run pytest tests
/home/runner/work/_temp/f36d16ac-f5e7-4b4b-9fbd-18e3fbee3169.sh: line 1: pytest: command not found
Error: Process completed with exit code [12](https://github.com/drunkwcodes/mojopi/actions/runs/5757951393/job/15609764942#step:6:13)7.

## Steps to reproduce

Here is my pyproject.toml:

https://github.com/drunkwcodes/mojopi/blob/main/pyproject.toml

```
pdm install -d --no-isolation
pytest
coverage
```
## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
pdm 2.8.2
Ubuntu-latest
python 3.10
```

**Comment by frostming** [comment]
This is a misunderstanding, `--no-isolation` doesn't mean to install globally and make the script globally discoverable, please prefix the commands with `pdm run`.

**Comment by drunkwcodes** [comment]
It works. Thanks a lot!
