### ISSUE TITLE
Publish a repository using credentials from `.pypirc`

### ISSUE THREAD

**Issue by lmmx** [pdm-project/pdm#2170]
I can't tell if this is supposed to be implemented already, namely because there's mention of a variable `$(PYPIRC_PATH)` in #2141:

- https://github.com/pdm-project/pdm/pull/2141#issuecomment-1655083979

```yaml
  - script: |
      pdm publish --repository $(PYPIRC_PATH)
    displayName: 'Build package and publish'
```

I think though that it's intended to indicate a URL. I initially saw that and thought I was meant to supply `~/.pypirc` (which is where `twine` gets my token from when I publish Python packages typically).

I dug into what actually goes on and ended up breakpointing at `pdm/project/config.py(447)get_repository_config()`.

The `.pypirc` file looks like this:

```ini
[pypi]
  username = __token__
  password = pypi-XXXXXXXXX...
```

Can this be used to generate the repository URL with all the necessary config instead of requiring it be passed in? Or does this feature already exist somewhere I missed?

More simply (if the `--repository` flag is not the place for this), the feature request could also be phrased as "autodetect username and password from `.pypirc` when running `pdm publish`". In this case the solution was to just manually copy the username (`__token__`) and password from this file and supply them to `--publish`.

**Comment by frostming** [comment]
The value of `--repository` can be either a upload URL or the name of a **configured** repository in pdm config. Yeah, PDM has its own config file and won't read `.pypirc`.

Read [this section](https://pdm.fming.dev/latest/usage/config/#configure-the-repositories-for-upload) from the docs.
