### ISSUE TITLE
`pdm lock` crashes if `required-python` obsoletes a Python version gated requirement

### ISSUE THREAD

**Issue by whitequark** [pdm-project/pdm#2175]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

`pyproject.toml`:
```toml
[project]
requires-python = "~=3.8"
dependencies = ["importlib_metadata; python_version<'3.8'"]
```

```console
$ pdm lock -v
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   importlib-metadata; python_version < "3.8"
pdm.termui:   python>=3.8,<4.0
pdm.termui:   Adding requirement importlib-metadata; python_version < "3.8"
pdm.termui:   Adding requirement python>=3.8,<4.0
pdm.termui: ======== Starting round 0 ========
[InvalidPyVersion]: Invalid specifier: 'impossible'
```

## Actual behavior

`pdm lock` crashes with `InvalidPyVersion` and without a reference to the problematic requirement.

## Expected behavior

Nothing is done (as far as I can tell, the requirement is valid, if meaningless). A warning would be useful. At the very least, the specific requirement that caused the crash should be shown.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
$ pdm info && pdm info --env
PDM version:
  2.8.2
Python Interpreter:
  /home/whitequark/test/.venv/bin/python (3.11)
Project Root:
  /home/whitequark/test
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.11.2",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.1.0-9-amd64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08)",
  "python_full_version": "3.11.2",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}
```

**Comment by pawamoy** [comment]
You're specifying that your project works on Python 3.8 and higher, and specify a dependency for Python 3.7 and lower. Even if harmless, I guess PDM considers it wrong. Remember that PDM must do the correct thing here, and adding a never-used dependency to the package metadata is probably not correct. Silently ignoring it is not correct either. The error message could be improved to point at the issue, you're right.

**Comment by whitequark** [comment]
I recognize that there is inherent ambiguity in whether this metadata is correct or not, and I'm happy for PDM to point out that the requirement is meaningless. Which way to resolve the ambiguity is not up to me, but I thought the report on a poor diagnostic would be useful whichever way it is resolved.

**Comment by whitequark** [comment]
Regarding correctness, PEP 621 says nothing about rejecting such metadata, which is why I listed that my expected behavior here would be to accept it. I don't know how strictly PDM wants to treat PEP 621 in cases like this (that PEP is quite underspecified) and I really don't want to get into any argument over this minor issue; I just wanted to explain why I filed this bug the way I did.

**Comment by pawamoy** [comment]
Of course, thanks for filing it :slightly_smiling_face:

**Comment by whitequark** [comment]
Thanks!
