### ISSUE TITLE
Clarification on documentation

### ISSUE THREAD

**Issue by Drachenfels** [pdm-project/pdm#2179]
I am reading documentation (https://pdm.fming.dev/latest/usage/project/#set-requires-python-value) and what is written there I do not understand, not sure if there is something about python version qualifier I am not aware of or maybe there is mistake in docs.

The paragraph in question:

> For example, consider the following setup:
> 
>  * Project: requires-python = ">=3.9"
>  * Package foo: requires-python = ">=3.7,<3.11"
> 
> Resolving the dependencies will cause a ResolutionImpossible.
> 
> Because the dependency's requires-python is >=3.7,<3.11, it doesn't cover the project's requires-python range of >=3.9. In other words, the project promises to work on Python 3.11 and above, but the dependency doesn't support it. Since PDM creates a cross-platform lockfile that should work on all Python versions within the requires-python range, it can't find a valid resolution. To fix this, you need add a maximum version to requires-python, like >=3.9,<3.11.

My question is why, the project requires >=3.9 and dependency is >=3.7 and <3.11. I would think that the overlapping range of versions are 3.9 and 3.10. 

Also, doc says: `In other words, the project promises to work on Python 3.11 and above, but the dependency doesn't support it.`, I would argue that the project promises to work on Python 3.9 and above (and it confused me hella lot)

After writing all of that, I am guessing the issue is that the project is open-ended while sub-dependency is limited to 3.10 max.

Maybe doc should read something like that:

`In other words, the project promises to work on Python 3.9, 3.10, 3.11 (and so on), but the dependency doesn't support Python 3.11 (or any higher).`

The second question is this screenshot of documentation:

![selection-20230811141710](https://github.com/pdm-project/pdm/assets/135730/cd09b934-5c05-4e2b-b1d8-9e452d05dd96)

The second row has a typo perhaps? It should read: "Python 3.7, 3.8, **3.9** and 3.10" vs current: "Python 3.7, 3.8 and 3.10"

While this is minor, due to confusion with the sentence above, it made me question my senses (or perhaps I am having gaps in my knowledge).

**Comment by pawamoy** [comment]
> Maybe doc should read something like that

Yes, that would be nice, do you want to send a PR?

> The second row has a typo perhaps?

Definitely, feel free to fix this as well in the smae PR if you send one! Thanks for reporting :)

**Comment by Drachenfels** [comment]
Sure, thing, let me figure out how to update docs and PR will be up in a day or two.

**Comment by sanmai-NL** [comment]
@Drachenfels Do you have a new time frame?

**Comment by Drachenfels** [comment]
Apologies guys, I originally planned to do it as I said 1 or 2 days later, but work being work I got sucked by it, and shortly after I went for 2 weeks holidays and completely forgot about it afterward.

Thanks for merging it tho!
