### ISSUE TITLE
Add a timeout to Pypi calls

### ISSUE THREAD

**Issue by logut** [pdm-project/pdm#2183]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce
1. Create a vm with all outgoing packets droped by a firewall
  eg with `sudo iptables -A OUTPUT -j DROP`
2. Try to `pdm sync`, or `pdm self update`

## Actual behavior
PDM hangs indefinitely

## Expected behavior
A timout with a clear message should be shown. Maybe after 10 or 60 seconds ?

In my case the dev vm is in corporate network, without access to the internet, all packets are dropped. I forgot to update the `pdm config pypi.url` to our internal mirror thinking it would use the /etc/pip.conf config file. Having a timeout with an error message would have helped finding my mistake.

## Environment Information

```bash
pdm info
PDM version:
  2.8.2
Python Interpreter:
  /home/.../dev/misc/.venv/bin/python (3.9)
Project Root:
  /home/.../dev/misc
Local Packages:

pdm info --env
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.16",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "4.18.0-477.15.1.el8_8.x86_64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Fri Jun 2 08:27:19 EDT 2023",
  "python_full_version": "3.9.16",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by elramen** [comment]
As part of a school project, my group will work on this issue during this week :)

**Comment by frostming** [comment]
@elramen Thanks, assigned it to you.

**Comment by chapmanjacobd** [comment]
Weird because I have seen with increasing frequency: 

```
[ReadTimeout]: HTTPSConnectionPool(host='upload.pypi.org', port=443): Read timed out. (read timeout=10)
```

but I guess that is for `pdm publish` which is different. 

https://github.com/chapmanjacobd/library/actions/runs/8082043573/job/22082109346

Does pdm have an env var like `PIP_DEFAULT_TIMEOUT=100` to increase this timeout ?

**Comment by elramen** [comment]
We have investigated this issue and it seems to arise when "pypi.org" is resolved but all other packages, i.e. non-DNS packages, are dropped. We are working on a fix now!
