### ISSUE TITLE
Project script is not installed on Windows cmd

### ISSUE THREAD

**Issue by drunkwcodes** [pdm-project/pdm#2194]
- [v] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Install this package as the README says.

https://github.com/drunkwcodes/mojo_muse

## Actual behavior

The installation is successful. But calling `muse` failed.

## Expected behavior

`muse` command is installed too and can be used. CMD say the command is not found.

Note: the command is installed on powershell.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.11",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19045",
  "python_full_version": "3.10.11",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "win32"
}
```

**Comment by frostming** [comment]
Why should it be installed to the PATH? It is never intended so. All scripts installed by PDM would be located inside the venv and must be run with `pdm run`. You can activate the venv to make the scripts discoverable in the PATH.

**Comment by drunkwcodes** [comment]
Oops. My mistake. The trouble now is git dependency "mups" is not installed.

**Comment by drunkwcodes** [comment]
Ok, it's my fault again!
I put wrong mojopi url behind mups dep. Sorry for that.

It's working like a charm now. Closing.
