### ISSUE TITLE
Local dependencies with whitespace in path raises an error

### ISSUE THREAD

**Issue by EmreTech** [pdm-project/pdm#2197]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. Create two projects (A and B for example) where one of the parent folders has a space in it (for example, one of my folders is "Discord API Wrappers")
2. Try to add project A as a local dependency for project B
3. Install the project with the new dependency (`pdm add` automatically does this for you)

## Actual behavior

PDM raises an error claiming that the local dependency string does not comply with PEP 508 standards. In actuality, it seems to comply:

> Non line-breaking whitespace is mostly optional with no semantic meaning. The sole exception is detecting the end of a URL requirement.
[PEP 508](https://peps.python.org/pep-0508#whitespace)

Here's the [traceback](https://workbin.dev/?id=1692732455360504) if needed, but I think my description is enough to show the problem.

## Expected behavior

The local dependency installs without any problems.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.8.2
Python Interpreter:
  /Users/emreterzioglu/Documents/Programming/Python/Discord API Wrappers/discatpy/library-restructure/library/discathttp/.venv/bin/python (3.11)
Project Root:
  /Users/emreterzioglu/Documents/Programming/Python/Discord API Wrappers/discatpy/library-restructure/library/discathttp
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.4",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "22.5.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.5.0: Thu Jun  8 22:21:34 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8112",
  "python_full_version": "3.11.4",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
Fixed by pdm-backend 2.1.6
