### ISSUE TITLE
Utilize `py` launcher on windows for `pdm use` and `pdm venv`

### ISSUE THREAD

**Issue by p-rogalski** [pdm-project/pdm#2225]
## Is your feature request related to a problem? Please describe.

Python interpreters can be specified for the commands `pdm use` and `pdm venv`. However the full path to the Python interpreter must be given.

Alternatively all the Python interpreters can be added to PATH, which creates a big mess on Windows, since all Python executables are named the same. This mess is solved by the `py` launcher on Windows: https://docs.python.org/3/using/windows.html#python-launcher-for-windows

## Describe the solution you'd like

It would be really helpful if PDM could utilize the `py` launcher to find Python executables. Specifically if you could specify the same version selectors like for the `py` launcher. Some examples:

```shell
pdm use "3.10"                   # Use Python 3.10
pdm use "3.11-32"                # Use Python 3.11 (32 bit)
pdm venv create "3.9-64"         # Create venv with Python 3.9 (64 bit)
pdm venv create "3"              # Create venv with Python 3
```

## References

- [PEP 397 – Python launcher for Windows](https://peps.python.org/pep-0397/)

**Comment by frostming** [comment]
The python finder nows reads from the same source as `py` so what is not working for now?

**Comment by p-rogalski** [comment]
Ah my mistake, `pdm use 3.10` and the like actually works. However, I found no way to specify the architecture (32/64 bit):

```shell
> pdm use 3.10  
Please enter the Python interpreter to use
0. C:\Users\p.rogalski\AppData\Local\Programs\Python\Python310-32\python.exe (3.10-32)
1. C:\Users\p.rogalski\AppData\Local\Programs\Python\Python310\python.exe (3.10)
```

```shell
> pdm use 3.10-32
[NoPythonVersion]: No Python interpreter matching 3.10-32 is found.
```

**Comment by frostming** [comment]
No you can't, just choose from the listed interpreters and I think it's just easy enough.

**Comment by p-rogalski** [comment]
Ok fair enough, thank you for your time!
