### ISSUE TITLE
PDM 2.8+: hashes missing when exporting requirements

### ISSUE THREAD

**Issue by henryiii** [pdm-project/pdm#2226]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

The following hook:

```yaml
  - repo: https://github.com/pdm-project/pdm
    rev: 2.7.4
    hooks:
      - id: pdm-export
        args: [-o, requirements.txt, -Gdeploy]
        language_version: "3.8"

```

Works fine, but when updating to any 2.8[^1] release, suddenly all the hashes disappear from the lock file, even though `--without-hashes` was not added.

## Actual behavior

```console
$ pdm export -Gdeploy -o requirements.txt -v
The exported requirements file is no longer cross-platform. Using it on other platforms may cause unexpected result.
STATUS: Resolving packages from lockfile...
STATUS: Fetching hashes for resolved packages...
$ cat requirements.txt
# No hashes
```

## Expected behavior

Hashes should be present, just like in 2.7 (unless `--no-hashes` was passed).

## Environment Information

The pre-commit environment, or the one below, which was used to produce the lines above:

```console
$ pdm info && pdm info --env
PDM version:
  2.9.0
Python Interpreter:
  /Users/henryschreiner/.pyenv/versions/3.9.1/bin/python3 (3.9)
Project Root:
  /Users/henryschreiner/git/CMS/hypernewsviewer
Local Packages:
  /Users/henryschreiner/git/CMS/hypernewsviewer/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.1",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "22.3.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64",
  "python_full_version": "3.9.1",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "darwin"
}
```

Also, pre-commit can't resolve dynamic versions anymore due to using faster checkouts, so the message "PDM 0.1.dev1+g4b06c6a is installed, while 2.9.0 is available." always shows up when run in pre-commit.

[^1]: 2.8.0a2 still produces the hashes, by the way.

**Comment by frostming** [comment]
Try refreshing the lockfile by `pdm lock --refresh`

**Comment by henryiii** [comment]
Thanks! The hashes are back. (A little different, but back). It would be nice to get some sort of warning if the old pdm.lock file is present.
