### ISSUE TITLE
Support binary-only, with (prefer-binary) exceptions

### ISSUE THREAD

**Issue by sanmai-NL** [pdm-project/pdm#2228]
## Is your feature request related to a problem? Please describe.

Binary-only builds are a way to keep CI pipelines efficient, so as to also prevent building non-Python source code, which costs a lot of resources.

Currently, it's possible to specify the set of binary-only packages, as well as binary-preferred or source-preferred packages. But it appears to not be possible to make exceptions to these specifications. For example, `PDM_ONLY_BINARY=:all:` with `PDM_PREFER_BINARY=exceptionalpackage`.

## Describe the solution you'd like

Define an order of precedence for these env vars and resolve them respecting that order. Perhaps, for the most general solution, in addition some more environment variables are needed, such as `PDM_PREFER_SOURCE`.

**Comment by frostming** [comment]
`PDM_PREFER_BINARY` is not able to override `PDM_ONLY_BINARY` and `PDM_NO_BINARY`, since they take effect at different stages. However, with unearth 0.11.0 only-binary takes precedence over no-binary, and specific package names take precedence over `:all:`.

**Comment by sanmai-NL** [comment]
Does this mean that `PDM_NO_BINARY=package` overrides `PDM_ONLY_BINARY=:all:` for `package`?

**Comment by frostming** [comment]
> Does this mean that `PDM_NO_BINARY=package` overrides `PDM_ONLY_BINARY=:all:` for `package`?

Correct, and `PDM_ONLY_BINARY=package` wins over `PDM_NO_BINARY=package`

**Comment by sanmai-NL** [comment]
My experience today does not match this rule:

```console
$ env PDM_ONLY_BINARY=':all:' PDM_NO_BINARY='utm eccodes findlibs' pdm install --verbose --verbose
...
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/f7/7e/629ddbe63164f71bf2b03e151a69bfbf439692652432af4b2a78f21b0a18/utm-0.7.0.tar.gz (from https://pypi.org/simple/utm/)>: source distribution is not allowed for utm
...
```

**Comment by frostming** [comment]
> My experience today does not match this rule:
> 
> 
> 
> ```console
> 
> $ env PDM_ONLY_BINARY=':all:' PDM_NO_BINARY='utm eccodes findlibs' pdm install --verbose --verbose
> 
> ...
> 
> unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/f7/7e/629ddbe63164f71bf2b03e151a69bfbf439692652432af4b2a78f21b0a18/utm-0.7.0.tar.gz (from https://pypi.org/simple/utm/)>: source distribution is not allowed for utm
> 
> ...
> 
> ```

But specific wins over :all:, that I'd exprcted

**Comment by sanmai-NL** [comment]
@frostming In the example, specific means a source distribution is allowed while the log says the source distribution is disallowed.

**Comment by frostming** [comment]
> @frostming In the example, specific means a source distribution is allowed while the log says the source distribution is disallowed.

Oh, multiple packages should be separated by comma
