### ISSUE TITLE
installation of xmlsec

### ISSUE THREAD

**Issue by liran-cohen-hs** [pdm-project/pdm#2232]
- [V] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce
`pdm add xmlsec==1.3.13`

## Actual behavior
```
pdm.exceptions.BuildError: Build backend raised error: Showing the last 10 lines of the build output:
#define DO_JOIN2(X,Y) X##Y
                      ^
<scratch space>:193:1: note: expanded from here
xmlSecSoap12Ns
^
/opt/homebrew/Cellar/libxmlsec1/1.3.1_1/include/xmlsec1/xmlsec/strings.h:34:33: note: 'xmlSecXPath2Ns' declared here
XMLSEC_EXPORT_VAR const xmlChar xmlSecXPath2Ns[];
                                ^
2 errors generated.
error: command '/usr/bin/clang' failed with exit code 1

```

## Expected behavior
Installation of the desired package
Tried to install it with the latest pip and setuptools and it worked

## Environment Information

```bash
PDM version:
  2.8.2
Python Interpreter:
  /Users/liran/hiredscore/git/packages-spec/pdms/18/.venv/bin/python (3.9)
Project Root:
  /Users/liran/hiredscore/git/packages-spec/pdms/18
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.16",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "22.3.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000",
  "python_full_version": "3.9.16",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "darwin"
}


```

**Comment by frostming** [comment]
> Tried to install it with the latest pip and setuptools and it worked

I can't install with pip either with the same error

**Comment by pawamoy** [comment]
And I can install with PDM. The package is compiled with gcc on my end.

**Comment by pawamoy** [comment]
@liran-cohen-hs, you have to read the whole compilation logs (there must be a link to the logs file in PDM's output) to find out why the compilation fails.

**Comment by frostming** [comment]
Here is a related topic: https://stackoverflow.com/questions/76005401/cant-install-xmlsec-via-pip

Maybe I didn't install necessary libraries.

**Comment by liran-cohen-hs** [comment]
> Here is a related topic: https://stackoverflow.com/questions/76005401/cant-install-xmlsec-via-pip
> 
> Maybe I didn't install necessary libraries.

followed the first comment there and it worked :)
thanks
