### ISSUE TITLE
command-line option that bumps the version of the project 

### ISSUE THREAD

**Issue by miguelteixeiraa** [pdm-project/pdm#2239]
###  Is your feature request related to a problem?
**That would make it easy to create some automation**. Example: A workflow-call for releases on github actions that would receive the new version/tag as input and update the project's pyproject.toml through pdm. 

Maybe this feature already exists, please let me know if that's the case. I couldn't find it in the docs. 

### Describe the solution you'd like
Something similar to:
https://python-poetry.org/docs/cli/#version
```bash
poetry version 0.1.0 # bumps the version to 0.1.0, updating the pyproject.toml
```

**Comment by frostming** [comment]
pdm-backend supports dynamic versioning from SCM, and there is also a plugin `pdm-bump` that takes care of the version bump. Therefore, we are not going to add this in the main project.
