### ISSUE TITLE
Allow opting-out from optional groups

### ISSUE THREAD

**Issue by 2e0byo** [pdm-project/pdm#2258]
## Is your feature request related to a problem? Please describe.

I often want to install all optional groups except one, which contains e.g. expensive ML libraries I don't require. With poetry I could just `install --without ml`, but pdm doesn't seem to have any negative resolving logic.  As a workaround I can generate all the groups by parsing the pyproject.toml myself, but this feels like a hack.

## Describe the solution you'd like

It should be possible to install with all optional groups except some.  Something like:

```bash
pdm {install sync} -G:all -G "not expensive-group"
```

Alternatively, pdm could behave like poetry:

```bash
pdm {install sync} --with group --without group --without group
```

Apologies if this is already possible and I've just missed it.

**Comment by elramen** [comment]
Almost done with this issue, could you please assign me to it? :)
