### ISSUE TITLE
Readme correction

### ISSUE THREAD

**Issue by dunkmann00** [pdm-project/pdm#2259]
In the Readme, in the "This Project" section it states:

> Unlike Poetry and Hatch, PDM is not limited to a specific build backend; users have the freedom to choose any build backend they prefer.

Unless I'm getting something mixed up, Poetry is [PEP 517 compliant](https://python-poetry.org/docs/pyproject#poetry-and-pep-517) and also does not limit to a specific build backend.

**Comment by frostming** [comment]
Can you use hatchling backend in the `build-system` of Poetry? That is what I mean by "limited"
