### ISSUE TITLE
[feature] add `venv.dir_name` configuration

### ISSUE THREAD

**Issue by joe733** [pdm-project/pdm#2260]
## Is your feature request related to a problem? Please describe.

I have a monorepo kind of setup. There are sub-projects with their own virtual environments. By default when PDM creates a virtual environment in the project directory, it does so in a folder called `.venv`.

- When switching between virtual environments VSCode shows the directory name instead of prompt name, which is annoying if every one of them is named `.venv`
- When attempting to test different sets of dependencies, multiple virtual environments are great to have.

Currently, you have to do the following steps to get the same results thay would be achieved by the proposed configuration:

```console
$ python -m venv ./.venv.deps_A
$ pdm use -f ./.venv.deps_A
$ pdm install
```

> Edit: For some reason, installing `lxml` fails when virtual environment is created in this manner.

## Describe the solution you'd like

Have a `venv.dir_name` configuration item.

```console
$ cat pdm.toml
[venv]
dir_name = ".venv.deps_A"

$ pdm venv create --dir-name .venv.deps_B # overrides pdm.toml
```

**Comment by frostming** [comment]
PDM supports managing multiple virtualenvs. Just give a name to `pdm venv create --name <name>` and it will be created under the path specified by `venv.location` config.

We are not likely to add this kind of shortcut.

**Comment by joe733** [comment]
`venv.location` is not allowed to be set in project configuration. So a virtualenv created with `--name` option will never be in the same directory as the project.

In other words `--name` option overrides `venv.in_project` (local & global) configuration.

I'm not asking for a shortcut to existing configurations, but instead a new configuration, that allows creation of virtual environments with a custom name, in the active project directory.
