### ISSUE TITLE
`pdm venv activate` does not activate the venv successfully, though no failure reported

### ISSUE THREAD

**Issue by jt-wang** [pdm-project/pdm#2266]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
1. Fresh checkout a project, e.g. https://github.com/yihong0618/epubhv
2. `cd` into the project, run `pdm install -d` and `pdm venv activate`
3. Log output shows the venv is created and activated successfully
```shell
python.use_venv is on, creating a virtualenv for this project...
Virtualenv is created successfully at /Users/jt-wang/projects/epubhv/.venv
Synchronizing working set with resolved packages: 18 to add, 0 to update, 0 to remove

  ✔ Install mypy-extensions 1.0.0 successful
  ✔ Install iniconfig 2.0.0 successful
  ✔ Install docstring-parser 0.15 successful
  ✔ Install click 8.1.7 successful
  ✔ Install beautifulsoup4 4.12.2 successful
  ✔ Install packaging 23.1 successful
  ✔ Install pathspec 0.11.2 successful
  ✔ Install platformdirs 3.10.0 successful
  ✔ Install pluggy 1.3.0 successful
  ✔ Install opencc-python-reimplemented 0.1.7 successful
  ✔ Install soupsieve 2.5 successful
  ✔ Install typing-extensions 4.7.1 successful
  ✔ Install typed-argument-parser 1.8.1 successful
  ✔ Install typing-inspect 0.9.0 successful
  ✔ Install cssutils 2.7.1 successful
  ✔ Install pytest 7.4.2 successful
  ✔ Install black 23.9.1 successful
  ✔ Install lxml 4.9.3 successful
Installing the project as an editable package...
  ✔ Install epubhv 0.3.0 successful

🎉 All complete!

source /Users/jt-wang/projects/epubhv/.venv/bin/activate
```
4. However, when `which python` and `which python3`, they still point to system's default python binary.

## Actual behavior

```shell
# project venv does exit
pdm venv list
Virtualenvs created with this project:

*  in-project: /Users/jt-wang/projects/epubhv/.venv

# project venv does contain python and other binaries
.venv/bin/python3
Python 3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

# pdm command runs without failure
pdm venv activate
source /Users/jt-wang/projects/epubhv/.venv/bin/activate

# However, venv is not activated
which python                    
/Library/Frameworks/Python.framework/Versions/2.7/bin/python

which python3  
/opt/homebrew/bin/python3
```
## Expected behavior
```shell
which python3

# should point to ./.venv/bin/python
```

## Environment Information
Strangely, even pdm "think" it gets python interpreter as the venv's one.
```bash
# Paste the output of `pdm info && pdm info --env` below:
pdm info && pdm info --env
PDM version:
  2.9.2
Python Interpreter:
  /Users/jt-wang/projects/epubhv/.venv/bin/python (3.11)
Project Root:
  /Users/jt-wang/projects/epubhv
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.11.5",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "23.0.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 23.0.0: Thu Aug 17 21:23:05 PDT 2023;
root:xnu-10002.1.11~3/RELEASE_ARM64_T6000",
  "python_full_version": "3.11.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}
```
**FYI**: I don't use or have other venv managers in my system.

**Comment by jt-wang** [comment]
My observation is that it's essentially because 
`source /Users/jt-wang/projects/epubhv/.venv/bin/activate` often doesn't work without any useful failure output. Sometimes the first run of this command works, and in other situations I have to run around 10 times, or totally in vain.

**Comment by pawamoy** [comment]
`pdm venv activate` does not activate the venv: it **prints the command that does**. You have to execute that command again to activate the venv:

```console
% pdm venv activate                                                           
source /home/pawamoy/.local/share/pdm/venvs/griffe-IdQP7oua-3.9/bin/activate
% type python
python is /home/pawamoy/.rye/shims/python
% eval $(pdm venv activate)
% type python
python is /home/pawamoy/.local/share/pdm/venvs/griffe-IdQP7oua-3.9/bin/python
```

See https://pdm.fming.dev/latest/usage/venv/#activate-a-virtualenv.

**Comment by jt-wang** [comment]
@pawamoy Thanks! I totally forgot about it though I did read about this part. It would be great if pdm could 
1. modify the semantics here, 
2. **or** provide two separate commands, 
3. **or** provide better output logging says "it doesn't activate the venv but only print the command ", 

as it's a little confusing from the command itself :)

**Comment by pawamoy** [comment]
I'd vote for option 3, it could output comments above the command:

```console
$ pdm venv activate
# The following command must be evaluated to activate the virtualenv:
source ...
```

**Comment by jt-wang** [comment]
@pawamoy Thanks! I'd love to. However, because 
1. `eval` execute whatever passed in
2. `eval` doesn't support inline comments
3. `eval $(pdm venv activate)` is the typical usage of `pdm venv activate`, it's not possible to add comment to it.

Therefore, I'd love to hear what @frostming thinks about it.

**Comment by frostming** [comment]
> @pawamoy Thanks! I'd love to. However, because
> 
> 1. `eval` execute whatever passed in
> 2. `eval` doesn't support inline comments
> 3. `eval $(pdm venv activate)` is the typical usage of `pdm venv activate`, it's not possible to add comment to it.
> 
> Therefore, I'd love to hear what @frostming thinks about it.


It is possible, print comments to stdout and it won't be eval'd

**Comment by jt-wang** [comment]
@frostming I tried to follow `CONTRIBUTING.md` and fresh checkout the `pdm` repo, but `pre-commit` test failed (I haven't changed anything)

```
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

src/pdm/cli/commands/venv/utils.py:65: error: Name "t.Self" is not defined  [name-defined]
Found 1 error in 1 file (checked 108 source files)
```

Is this error expected?

**Comment by frostming** [comment]
> Is this error expected?

Yeah, that runs on Python 3.10+, you can ignore that.

**Comment by deronnax** [comment]
+1, the current working/wording is very confusing, everything makes you believe the venv will be activated. It takes some round of investigations (I had to read the source code to be sure) that actually the command *just* prints what needs to be done to get the venv activated.
I think the command name should even be changed (but it's a bigger change, I understand).
@jt-wang are you doing the PR?

**Comment by deronnax** [comment]
Sorry to come back with this: today, there was kind of an outrage in my company because many devs lost dozens of minutes trying to activate the pdm venv (which they have to do since there is no pdm shell command) and they did not understand why the `pdm activate` did not activate the venv. Something worth noting: none of them had the idea to look at the help line of the command, because to them it was obvious that `pdm activate` would activate the venv (what else?). And I have seen this one quite a lot. Actually it was my first WTH moment with PDM: why `activate` doesn't activate?

I think renaming the command to something like `show-activate` (yes it looks bad, suggestions welcome) should be seriously considered.
