### ISSUE TITLE
Allow usage without virtual environments

### ISSUE THREAD

**Issue by SRv6d** [pdm-project/pdm#2267]
When PDM is used inside of a VM or container specific to a project, virtual environments provide no benefit and must be sourced manually.
It would be great if PDM could be used without a virtual environment in a similar manner to Poetry.

**Comment by frostming** [comment]
`--global --project .`

**Comment by SRv6d** [comment]
@frostming Could this be emphasized in the docs and an env var added to configure this, or is it `global_project.user_site`?

**Comment by frostming** [comment]
@SRv6d I don't know if #2271 is emphasized enough from your point of view. Docs are structured into certain sections, and we can't put all things in the index page because something confusing to someone will be obvious to others and that will make the index page bulky and lose focus.

**Comment by SRv6d** [comment]
@frostming It is actually quite visible, I just looked in the configuration section instead of in "Manage Dependencies" because I expected it to be a poetry-like flag, not a CLI argument. Is there any way to use this without specifying it in every command? Ideally using environment vars. I thought `global_project.fallback = True` & `python.use_venv = False` might do the trick together, but that will use PEP 582.
