### ISSUE TITLE
Possible error in docs link for dynamic versioning

### ISSUE THREAD

**Issue by sr-murthy** [pdm-project/pdm#2269]
- [Y ] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

Click on the [dynamic versioning internal link](https://pdm.fming.dev/latest/reference/build/#dynamic-versioning) on the [package versioning page](https://pdm.fming.dev/latest/reference/pep621/#package-version). This link has the target:
```
https://pdm.fming.dev/latest/reference/build/#dynamic-versioning
```
but takes you to the [build configuration page](https://pdm.fming.dev/latest/reference/build/#build-configuration), which is unrelated.

## Actual behavior

As described above. Dynamic versioning link target appears to be wrong.

## Expected behavior

Link to the correct dynamic versioning page.

## Environment Information

```bash
PDM version:
  2.9.2
Python Interpreter:
  /Users/sandeep.murthy/Documents/clairvoyant/../clairvoyant-env/bin/python3.9 (3.9)
Project Root:
  /Users/sandeep.murthy/Documents/clairvoyant
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.6",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "22.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64",
  "python_full_version": "3.9.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
Would you like to contribute? also refer to #2089, closing this one.

**Comment by sr-murthy** [comment]
@frostming  Sure, I can open a PR.
