### ISSUE TITLE
sync twice or build first when cython is used with setup-script

### ISSUE THREAD

**Issue by franzhaas** [pdm-project/pdm#2272]
- [ x] I have searched the issue tracker and believe that this is not a duplicate.

I believe that when I am using a build method like that in my project.:

```bash
[tool.pdm.build]
setup-script = "build.py"
run-setuptools = true
is-purelib = false
```

I need to run sync twice, or run pdm build before I can succesfully sync.
In my case the build.py script uses cython.

Is this expected behaviour?

The error message on the first sync/the sync without building first looks like this.:
```
workspace\pdm.exe\pdm\installers\installers.py:174: UserWarning: Validation of the RECORD file of C:\Users\PXI_USER\AppData\Local\Temp\pdm-wheel-cache-b6ylgbai\90\09\ab\fae721fee8aefd105bb98e17bc8fbdb6ecef1ea8d2bd2331ea\XXXXXXXXXX-0.1.dev131+g69cbefb.d20230923-cp39-cp39-win_amd64.whl failed. Please report to the maintainers of that package so they can fix their build process. Details:
08:21:23  Unable to retrieve `RECORD` from C:\Users\XXXXXXX\AppData\Local\Temp\pdm-wheel-cache-b6ylgbai\90\09\ab\fae721fee8aefd105bb98e17bc8fbdb6ecef1ea8d2bd2331ea\XXXXXXXXXX-0.1.dev131+g69cbefb.d20230923-cp39-cp39-win_amd64.whl: KeyError("There is no item named 'XXXXXXXXXXX-0.1.dev131+g69cbefb.dist-info/RECORD' in the archive")
```

I have the same behaviour with 2.8.2. and 2.9.2

**Comment by frostming** [comment]
What error did you see? cannot find cython?

Did you list cython in the `requires` field of `build-system` table?

**Comment by franzhaas** [comment]
Yes  i do.:

<code>
---8<---8<---8<---8<---8<---8<---
[build-system]
requires = ["setuptools", "wheel", "Cython","XXXXXXXX", "pdm-pep517"]
build-backend = "pdm.pep517.api"
---8<---8<---8<---8<---8<---8<---
</code>

**Comment by frostming** [comment]
Oh, can you migrate to `pdm.backend`? the old backend doesn't receive updates.

**Comment by pvcnt** [comment]
Hello, I am hitting the same issue, with pdm-backend:

```toml
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
```

It was working a few weeks ago and started to break today. Issue is:
```
Adding myservice-0.1.dev200+g09cc5f0.d20230926.editable.dist-info/RECORD -> myservice-0.1.dev200+g09cc5f0.d20230926.editable.dist-info/RECORD
UserWarning: Validation of the RECORD file of /tmp/pdm-wheel-cache-i2gicleg/89/1d/cc/b8f5867241d4********4edf0e4cc5930c1ac76d0a81c49b670fde90/myservice-0.1.dev200+g09cc5f0.d20230926.editable-py3-none-any.whl failed. Please report to the maintainers of that package so they can fix their build process. Details:
Unable to retrieve `RECORD` from /tmp/pdm-wheel-cache-i2gicleg/89/1d/cc/b8f5867241d4********4edf0e4cc5930c1ac76d0a81c49b670fde90/myservice-0.1.dev200+g09cc5f0.d20230926.editable-py3-none-any.whl: KeyError("There is no item named 'myservice-0.1.dev200+g09cc5f0.editable.dist-info/RECORD' in the archive")
```

There seems to be a discrepancy between the two version numbers ("g09cc5f0.d20230926" vs "g09cc5f0"), but I don't know where this is coming from. This is failing on my CI, but not on my laptop, but I have not been able to pinpoint the source of the error yet.

**Comment by pvcnt** [comment]
Reported here as well: https://github.com/pdm-project/pdm/discussions/2208

**Comment by frostming** [comment]
@pvcnt Can't share the project or the CI log URL for reproduce?

**Comment by waketzheng** [comment]
Thanks @franzhaas , this worked for me:
- pyproject.toml
```TOML
[tool.pdm.build]
run-setuptools = true
custom-hook = "build.py"
include = ["CHANGELOG.md", "LICENSE", "README.md"]

[build-system]
build-backend = "pdm.backend"
requires = ["pdm-backend", "setuptools", "cython"]
```
- build.py (For some reasons I don't want to use the default [pdm_build.py](https://backend.pdm-project.org/hooks/))
```py
from Cython.Build import cythonize


def pdm_build_update_setup_kwargs(context, setup_kwargs) -> None:
    setup_kwargs["ext_modules"] = cythonize(
        ["my_package/*.pyx"],
        language_level="3",
    )
```
- lib structure
```tree
.
├── my_package
│   ├── auth.py
│   ├── xxx.pyx
│   ├── yyy.pyx
│   └── version.py
├── build.py
├── CHANGELOG.md
├── conftest.py
├── LICENSE
├── Makefile
├── pyproject.toml
├── README.md
├── tests
│   ├── __init__.py
│   └── test_xxx.py
└── uv.lock
```
