### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by sr-murthy** [pdm-project/pdm#2273]
@frostming I'm not sure this fits in as a "feature request", but you've mentioned test coverage as needing improvement in the docs. I'm a newbie, but I've set up my PDM dev. env. Would it be worth adding a test coverage script to `tool.pdm.scripts`, which will measure and report coverage (default to console), e.g. something like:

    coverage = "pytest --cov=src/pdm --cov-branch tests/"

Currently, this produces an overall coverage of 83%. There are some modules with much lower coverage. Are there any simple ones I could start on improving test coverage? Thanks for any suggestions.

**Comment by sr-murthy** [comment]
@frostming FYI I'm planning to submit a PR containing test cases for generic utilities and other functions which are more "Standalone", since I'm relatively new to the codebase and still trying to work my way through. I hope that's OK.

**Comment by frostming** [comment]
Nice, welcome to contribute
