### ISSUE TITLE
FutureWarning - requirements.py

### ISSUE THREAD

**Issue by Mjboothaus** [pdm-project/pdm#2284]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

pdm add a package

## Actual behavior

/opt/homebrew/Cellar/pdm/2.9.2/libexec/lib/python3.11/site-packages/pdm/models/requirements.py:496: FutureWarning:
.* suffix can only be used with `==` or `!=` operators

## Expected behavior

Warning not error - FYI only

## Environment Information

```bash
PDM version:
  2.9.2
Python Interpreter:
  /Users/mjboothaus/code/github/databooth/grn/.venv/bin/python (3.10)
Project Root:
  /Users/mjboothaus/code/github/databooth/grn
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.12",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "22.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; 
root:xnu-8796.141.3~6/RELEASE_ARM64_T6000",
  "python_full_version": "3.10.12",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
As the warning message tells. Not PDM's fault.

**Comment by Mjboothaus** [comment]
I think if you look more closely at the path/warning you’ll see it is part
of the PDM codebase ie

src/pdm/models/requirements.py

Either way it’s just a warning for now.

**Comment by pawamoy** [comment]
I've asked about this here: https://github.com/pdm-project/pdm/discussions/2211.

**Comment by frostming** [comment]
Since the place where the warning is emitted doesn't have the context of the package it comes from, so this can be done with catching warnings and reraise. Welcome if anyone would like to help.

**Comment by pawamoy** [comment]
I tried to use `warnings.catch_warnings`, but it is not thread-safe so it doesn't work well during PDM installation loop.

**Comment by pawamoy** [comment]
As commented in the mentioned discussion, these warnings are not actionable. Maybe they should be logging messages or part of the verbose output instead?
