### ISSUE TITLE
Allow filtering some platforms out during locking

### ISSUE THREAD

**Issue by f3flight** [pdm-project/pdm#2288]
## Is your feature request related to a problem? Please describe.
When using a private index in an organization, some packages for some platforms may not be available as these platforms are not supported by the organization. In case some package has a conditional dependency for such an unsupported platform, "pdm lock" will fail as it won't be able to find such dependency in an internal index. A workaround is to use `--no-cross-platform` but this causes an issue that multiple lock files must be maintained for multiple platforms and even Python versions, and they have to be created and maintained separately on these platforms (i.e. run `pdm lock` on linux, then on mac, etc), which is cumbersome for the developer, and especially when developing libraries which should be tested against multiple Python versions on the same platform.

Example of such conditional dependency which may not exist in an internal index:
```
pdm.termui:   Adding requirement pywin32-ctypes>=0.2.0; sys_platform == "win32"(from keyring 24.2.0)
```

## Describe the solution you'd like
Pdm should allow including/excluding conditional dependencies (regex?). This should work without using `--no-cross-platform`.

**Comment by frostming** [comment]
Duplicated with #1911
