### ISSUE TITLE
pdm run does not catch ctrl-c on 2nd run (Win11)

### ISSUE THREAD

**Issue by srfoster65** [pdm-project/pdm#2292]
- [ x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

Given a project that is setup to support mkdocs for generating documentation.
From a windows command shell (cmd), cd to the project root and enter the following commands

pdm run mkdocs serve

[ctrl-c] - To terminate serve process - this works correctly.

pdm run mkdocs serve

[ctrl-c] - Does not interrupt/terminate process

Note:
I have tested the same project with poetry, and this can repeatedly start and stop mkdocs serve with the command "poetry run mkdocs serve". 

## Actual behaviour

mkdocs serve process continues to run.

## Expected behaviour

mkdocs serve process should be interrupted

## Environment Information

pdm info
PDM version:
  2.9.3
Python Interpreter:
  C:\Users\Steve\Development\python\arg_init\.venv\Scripts\python.exe (3.11)
Project Root:
  C:/Users/Steve/Development/python/arg_init
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.11.3",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.22621",
  "python_full_version": "3.11.3",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "win32"
}

**Comment by srfoster65** [comment]
Something very odd is happening here. Almost certainly windows specific.

The issue is in the file pdm\cli\commands\run.py and function _run_process().

If I simplify the code in _run_process() (This is not a solution, but an attempt to understand program flow) and remove the signal handler function and replace with a try/except block.

       try:
            process = subprocess.Popen(expanded_args, cwd=cwd, env=process_env, shell=shell, bufsize=0)
            process.wait()
        except KeyboardInterrupt:
            process.send_signal(signal.SIGINT) 

This works everytime. NotE this is sending signal.SIGINT to the subporocess.

If I modify the existing forward_signal() function

        def forward_signal(signum: int, frame: FrameType | None) -> None:
            process.send_signal(signum)

This will raise 
[ValueError]: Unsupported signal: 2

everytime, but will abort the script.

But why should this raise a ValueError when calling send_signal() in the exception handler with the same value (signal.SIGINT = 2) does not?

**Comment by srfoster65** [comment]
https://docs.python.org/3/library/signal.html#signal.CTRL_C_EVENT

signal.CTRL_C_EVENT
The signal corresponding to the Ctrl+C keystroke event. This signal can only be used with [os.kill()](https://docs.python.org/3/library/os.html#os.kill).

So the code in forward signal should not work as intended, and may partially explain the observed behaviour.

**Comment by srfoster65** [comment]
A solution I found on stackoverflow that was used for a similar issue on postgress was to use signum=signal.SIGTERM for windows.

        def forward_signal(signum: int, frame: FrameType | None) -> None:
            if sys.platform == "win32" and signum == signal.SIGINT:
                signum = signal.SIGTERM
            process.send_signal(signum)


I have tested this and this seems to reliably terminate the subprocess.

**Comment by frostming** [comment]
> A solution I found on stackoverflow that was used for a similar issue on postgress was to use signum=signal.SIGTERM for windows.
> 
> ```
>     def forward_signal(signum: int, frame: FrameType | None) -> None:
>         if sys.platform == "win32" and signum == signal.SIGINT:
>             signum = signal.SIGTERM
>         process.send_signal(signum)
> ```
> 
> I have tested this and this seems to reliably terminate the subprocess.

This seems to fix the issue without causing any other problems. Would you or @xzmeng like to send a PR?

**Comment by srfoster65** [comment]
Sure, I will create a PR.
This will be my first PR, so I hope I get things right.
