### ISSUE TITLE
[feature] ability to save updated dependency version to `pyproject.toml`

### ISSUE THREAD

**Issue by yozachar** [pdm-project/pdm#2293]
### Is your feature request related to a problem? Please describe.

In a web project, if you run say `pnpm update`, it not only updates the version in `[pnpm].lock` file but also modifies `package.json`. AFAIK, PDM does not do that.

### Describe the solution you'd like

Provide and option say `--write-to-pyproejct`, so when `pdm update --write-to-pyproject` is run if `pytest` is updated from `7.4.1` to `7.4.2` in `pdm.lock`, `pyproject.toml` is modified like so:

```diff
[tool.pdm.dev-dependencies]
- tooling = ["black>=23.9.1", "ruff>=0.0.292", "pyright>=1.1.329", "pytest>=7.4.1"]
+ tooling = ["black>=23.9.1", "ruff>=0.0.292", "pyright>=1.1.329", "pytest>=7.4.2"]
```

**Comment by pawamoy** [comment]
We had a similar discussion previously. Let me try to find it.

**Comment by pawamoy** [comment]
https://github.com/pdm-project/pdm/issues/2035

**Comment by yozachar** [comment]
Ah I see `pdm update -u`. Thanks!
