### ISSUE TITLE
Supporting python 3.12

### ISSUE THREAD

**Issue by laixintao** [pdm-project/pdm#2300]

**Comment by frostming** [comment]
I'd say this error comes from a package using an old version of setuptools(v59) that uses an attribute removed on Python 3.12. It doesn't look like an issue with PDM.

**Comment by laixintao** [comment]
> I'd say this error comes from a package using an old version of setuptools(v59) that uses an attribute removed on Python 3.12. It doesn't look like an issue with PDM.

Yes, removed.

the error came from installing pandas.

removed.
