### ISSUE TITLE
Attempting to add git+ssh dependency results in hang

### ISSUE THREAD

**Issue by mcclure** [pdm-project/pdm#2302]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

I have a [project](https://github.com/mcclure/analogue-core-template-amaranth/tree/2354a5ee55df975bdebbd1100a7ad10f087a7eab) in which my pyproject.toml contains this dependency:

```
 dependencies = [
    "amaranth[builtin-yosys] @ git+https://github.com/amaranth-lang/amaranth.git",
 ]
```

I think: Why am I using git+https. Normally I check out git revisions with ssh. (This might even be *necessary* if I wanted to set a private repository as a dependency.) I am used to there being a git+ssh:// protocol recognized in Mercurial.

So I change it to:

```
dependencies = [
    "amaranth[builtin-yosys] @ git+ssh://git@github.com/amaranth-lang/amaranth.git"
]
```

I run `python3 -m pdm install`.

## Actual behavior

```
Andi@Alita:/mnt/c/Users/Andi/work/f/temp/analogue-core-template-amaranth$ (cd src/fpga/amaranth_core/ && python3 -m pdm install)
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.0.5) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Lock file hash doesn't match pyproject.toml, packages may be outdated
Updating the lock file...
⠏ Resolving dependencies
```

…and then it freezes forever. The `⠋` is a little animated thing that loops forever.

## Expected behavior

EITHER the url should work, OR, if there is some reason that is not possible, it should fail reasonably rapidly and print a helpful error message.

## Environment Information

I see this with: Python 3.8.10, installed from apt, on Ubuntu 20.04 LTS, running inside WSL1 on Win 10.
I have pdm 2.9.1.

I don't quite understand the "/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.0.5) or chardet (3.0.4) doesn't match a supported version!" error. I always get that when running pdm with this project and this python installation.

# On Python 3.11 it behaves better, sort of

Imagine instead of the above Python, I run with Python 3.11.5, direct installation on Windows 10 from python.org, pdm 2.9.1. I `git clean -xffd` to prevent interference from the linux venv and run `python.exe -m pdm install`

```
Lock file hash doesn't match pyproject.toml, packages may be outdated
Updating the lock file...
python.use_venv is on, creating a virtualenv for this project...
Virtualenv is created successfully at C:\Users\Andi\work\f\temp\analogue-core-template-amaranth\src\fpga\amaranth_core\.venv
See C:\Users\Andi\AppData\Local\Temp\pdm-lock-v_666ekw.log for detailed debug log.
[UnpackError]: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Add '-v' to see the detailed traceback
```

This is better, in that I get an error message rather than a hang. However, I can't explain why my key is being denied. I don't usually use git on Windows, I normally use it inside the WSL1 "VM". If I configure and test Windows Git, git.exe is able to check out repos from github, but the error in pdm is not fixed. I do not know whether the "Better" behavior is caused by Python 3.11, or Windows, or if there's a dark possibility like *the hang only occurs if git authentication succeeds* (one possible example: you launched git in interactive mode and it is waiting for me to enter my ssh key passphrase)

**Comment by frostming** [comment]
You may need `-v` to disable the animated spinner, to see what is hanging, maybe a prompt waiting for input.

**Comment by mcclure** [comment]
With the `-v`, it ends with `Enter passphrase for key '[keypath]'`.

In testing if my known_hosts is messed up, I also can get it to freeze like:

```
Updating the lock file...
Warning: the ECDSA host key for 'github.com' differs from the key for the IP address '140.82.113.4'
Offending key for IP in /home/Andi/.ssh/known_hosts:14
Matching host key in /home/Andi/.ssh/known_hosts:27
⠇ Resolving dependencies
```

With -v this becomes like:

```
Warning: the ECDSA host key for 'github.com' differs from the key for the IP address '140.82.112.3'
Offending key for IP in /home/Andi/.ssh/known_hosts:17
Matching host key in /home/Andi/.ssh/known_hosts:26
Are you sure you want to continue connecting (yes/no)?
```

It also appears the prompt is present, if I run *without* -v and press "return" I get:

```
Lock file hash doesn't match pyproject.toml, packages may be outdated
Updating the lock file...
⠸ Resolving dependencies
See /tmp/pdm-lock-khv7ha81.log for detailed debug log.
[UnpackError]: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Add '-v' to see the detailed traceback
```

it's just that the animation swallows the final line of the prompt (be it "type yes/no" or "enter passphrase". Lines printed before the final line are allowed to be displayed it appears.
Also now that I know what I'm looking for, I realize that when the spinner animation is happening, the "enter passphrase" line flickers into being for like, 30 ms or something, short enough I hadn't noticed it before.

So, I now understand the problem and how to work around it locally.

However, in my opinion this is not friendly. I needed to seek help from you on the github to understand what is happening, and the case that can trigger this behavior (error in known_hosts or ssh key needs passphrase entry) is pretty common.

It's very hard to guess that a spinner is masking a secret prompt; if I had figured out on my own I get an error message by hitting return, the message it prints when hitting return is nonobvious (because the "enter passphrase" line is fully swallowed) and would have left me wondering what was wrong with my key rather than realizing I'd messed up a prompt.

Even now I understand what is happening, it is counter-intuitive that I need to pass "-v" anytime I pdm install something that has an ssh dependency or sub-dependency. "-v" is usually not a way of communicating "allow prompts".

**Comment by frostming** [comment]
Yes, the live update of Spinner swallows any output prints to the console. I am not sure if we can fix it in PDM side. Gentle ping @willmcgugan if he has any proper solution.

**Comment by willmcgugan** [comment]
I don't know of any way to detect if something is waiting for a prompt. You could disable the auto refresh, but then the spinner wouldn't spin.

Perhaps pdm could detect dependancies that might prompt, and attempt to connect to them outside of the spinner.

**Comment by pawamoy** [comment]
> it is counter-intuitive that I need to pass "-v" anytime I pdm install something that has an ssh dependency or sub-dependency. "-v" is usually not a way of communicating "allow prompts".

Indeed, `-v` stands for verbose. In non-verbose mode, you get a compact output. Any subprocess output is generally captured to avoid cluttering the console. When there's an error or incorrect behavior, it is pretty common to re-run in verbose mode to get more information. This should be the first thing a user does to debug something. It's actually written in PDM's issue template: `Make sure you run commands with -v flag before pasting the output`. So IMO it's a bit unfair to say that PDM is not friendly :confused: 

Anyway, if there's a way for PDM to improve handling of SSH dependencies, that's great :slightly_smiling_face:
