### ISSUE TITLE
set publish pypi username password from 

### ISSUE THREAD

**Issue by markonop93** [pdm-project/pdm#2306]
## Is your feature request related to a problem? Please describe.

set custom env variable to username and password

## Describe the solution you'd like

is possible to set username password in pyproject.toml with environment variable ??

**Comment by pawamoy** [comment]
Yes :slightly_smiling_face: 

From https://pdm.fming.dev/latest/reference/cli/#publish:

> -u, --username: The username to access the repository [env var: PDM_PUBLISH_USERNAME]
-P, --password: The password to access the repository [env var: PDM_PUBLISH_PASSWORD]
