### ISSUE TITLE
Lock dependencies to minimal versions

### ISSUE THREAD

**Issue by whitequark** [pdm-project/pdm#2310]
## Is your feature request related to a problem? Please describe.

When shipping software that depends on ranges of versions of other software, it is often the case that everyone developing the software installs the latest versions of the dependencies, and inadvertently introduces uses of functionality not included in the minimal version specified in the `pyproject.toml` file.

## Describe the solution you'd like

A mode for `pdm lock` that inverts the version resolution algorithm so that the lowest versions are picked for each direct dependency.

Other package management systems include similar functionality, e.g. [`cargo -Z minimal-versions`](https://doc.rust-lang.org/cargo/reference/unstable.html#minimal-versions) and [`cargo -Z direct-minimal-versions`](https://doc.rust-lang.org/cargo/reference/unstable.html#direct-minimal-versions). Here I am only asking for the second one, which I think is easier to implement and is more useful for my use case.

**Comment by pawamoy** [comment]
Also see discussion in https://github.com/pdm-project/pdm/discussions/2033.

**Comment by whitequark** [comment]
To add more context: the alternative to this is a manually maintained lockfile, which is very not fun to do.

**Comment by whitequark** [comment]
@frostming Oh wow!!! You're incredible. Thank you so much. I'll get on to testing this right away, and will likely use the feature on all of my projects of any significance.

**Comment by whitequark** [comment]
@frostming I have went ahead and used this feature in the Glasgow Interface Explorer software stack. You can see how it's done in https://github.com/GlasgowEmbedded/glasgow/pull/463. It appears to work perfectly well, to the point where I went ahead and switched our CI to use head PDM version.
