### ISSUE TITLE
`pdm init` forcefully write the src folder while setup with an existing project.

### ISSUE THREAD

**Issue by Mr-Sunglasses** [pdm-project/pdm#2319]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

By default create that src/ folder in my already setup project

## Actual behavior

ideally, It should not create that `src` folder

## Expected behavior

ideally, It should not create that `src` folder ( [Expected like poetry](https://python-poetry.org/docs/basic-usage/#initialising-a-pre-existing-project) )

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

PDM version:
  2.9.3
Python Interpreter:
  /private/tmp/Bloom-Backend/.venv/bin/python (3.11)
Project Root:
  /private/tmp/Bloom-Backend
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.11.6",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "23.0.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103",
  "python_full_version": "3.11.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}

```

https://github.com/pdm-project/pdm/assets/81439109/0b5a3e7e-cf18-45db-bd4e-dd9109dfbc0c

Also there is not any subcommand in `pdm init -h` to stop this.

![image](https://github.com/pdm-project/pdm/assets/81439109/372fae5a-d104-4611-a38d-19b957dde3a5)

**Comment by sho-87** [comment]
I believe ive seen __init__.py files being created as well?

Either way, I agree with this. Additionally, there are also situations where I want to create a managed environment, but the environment is not intended to be a python package, hence no src directory necessarily (simply a set of managed dependencies that I can quickly activate/deactivate)

**Comment by pawamoy** [comment]
I think you'll be interested in this merged PR: https://github.com/pdm-project/pdm/pull/2558.

```
pdm init minimal
```

Not sure it has been released yet.
