### ISSUE TITLE
Official docs and/or README should link to Docker Hub image

### ISSUE THREAD

**Issue by sh-at-cs** [pdm-project/pdm#2321]
## Is your feature request related to a problem? Please describe.

https://hub.docker.com/r/frostming/pdm says it is the official Docker image for PDM, but as far as I can tell, there is no link from PDM's docs or README to it.

Hence, there is no way to verify that the Docker image hasn't been created by some random person under a misleading name to trick people into installing malware or something like that.

## Describe the solution you'd like

Add a link from PDM's docs and/or README to the Docker Hub image. Just a badge in the README would be fine I guess.

**Comment by frostming** [comment]
`frostming/pdm` has not been updated for a long time, and I found that updating such an image is of little value.
People often need to work on different versions of Python and different base images. A single pdm image is not very useful.

**Comment by sh-at-cs** [comment]
Oh I see, fair enough! Maybe the description of the image could be updated to say it is deprecated?

**Comment by frostming** [comment]
Done.

**Comment by sh-at-cs** [comment]
Thanks!!
