### ISSUE TITLE
Generate entry points in (ex-)PEP-582 mode

### ISSUE THREAD

**Issue by ytimenkov** [pdm-project/pdm#2325]
It's a pity that PEP-582 got dropped, because I thought that it finally could be a good solution for distribution or deployment of python applications.

I know that it is still possible to manage dependencies with PDM and run scripts, however it would be nice if PDM could generate entry points (at least for console scripts) which run system-wide python but set python path to fins dependencies in a local folder. Something like pyinstaller in folder mode, but much more lightweight.

Then deploying somewhere or building a container image will be just copying of a directory (close to the initial goal of PEP-582).

The main problem with venv in this case is that venv "is not relocatable". And while it could be fine if you build docker and move venv from one layer to another preserving the same full path, it won't work for cases when installation directory is unknown (say, in a user folder).

I don't know which directory layout would be good in this case (e.g. a `bin` subfolder?).

In an extreme case when there is only 1 entry point per application and no binary dependencies would be nice to just zip it with `zipapp`.

**Comment by frostming** [comment]
You can make one yourself

1. Initialize a project with PEP 582 mode
2. Specify dependencies and console scripts(PEP 621 `project.scripts`)
3. Run `pdm install --no-editable` to install all in non-editable mode. Now the console scripts should be available at `__pypackages__/$X.$Y/bin`
4. [Enable PEP 582 package finding](https://pdm.fming.dev/latest/usage/pep582/#enable-pep-582-globally)
5. Now running `__pypackages__/$X.$Y/bin/foo` will successfully run with the dependencies loaded.

**Comment by ytimenkov** [comment]
Thanks, I'll check the suggestion. My primary concern is which shebang is generated in the scripts.
It seems logical to me to not require extra configuration to set up path. Could be done in the script directly.

**Comment by frostming** [comment]
> My primary concern is which shebang is generated in the scripts.

It is the interpreter path you selected when `pdm init` or `pdm use`.

**Comment by ytimenkov** [comment]
Apologizing for the delay.

I checked this and it works as you described. Or rather what you suggested works 😁 🙇‍♂️.

I just wonder - what is the point of enabling PEP-582 globally compared to setting `PYTHONPATH` pointing right into `__pypackages__`? I checked, the resulting `sys.path` is slightly different (PEP-582 site customization adds `__pypackages__` in the middle of the list, but after system folders.
I think for the purposes of "create something I can copy for deployment" they are the same except that PEP-582 requires PDM on the target while the other approach requires setting a variable.

Overall I'm very positive :) I think with a bit of scripting it should be possible to create a very slim deployable bundles. 

Thank you!

**Comment by pawamoy** [comment]
Enabling PEP 582 globally allows Python to find dependencies in `__pypackages__`. It means you can run `python -m tool` instead of passing through PDM with `pdm run tool` (as long as the tool in question has a `__main__` module, but that's another story).

Basically, enabling PEP 582 globally makes Python run a bit of code each time it starts to add a potential `__pypackages__` folder to `sys.path`.

**Comment by frostming** [comment]
setting `PYTHONPATH` pointing right into `__pypackages__` only sets the same `__pypackages__` globally.
While `pdm --pep582` will install a startup script that can find the nearest `__pypackages__` based on the script path being run.
