### ISSUE TITLE
`pdm publish` generating a 405 when publishing to a (private) Artifactory repo

### ISSUE THREAD

**Issue by sr-murthy** [pdm-project/pdm#2335]
- [Y ] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

@frostming I'm trying to build and publish artifacts (wheel + sdist) to a private Artifactory repo in one step using `pdm publish` - prior to the command, artifacts do exist in a `dist` subfolder in the working directory:

    pdm publish --verbose --project . --repository "<private Artifactory repo URL>" --username "<username>" --password "<password>"

## Actual behavior

Generates a 405 error:

    Uploading <package name + version>-py3-none-any.whl
    pdm.termui: Response from "<private Artifactory repo URL>":
    405 Method Not Allowed
    [PublishError]: 405 Client Error: Method Not Allowed for url: "<private Artifactory repo URL>"

I can see that PDM publish [uses a POST request](https://github.com/pdm-project/pdm/blob/main/src/pdm/cli/commands/publish/repository.py#L163) to upload the artifacts, but it seems that Artifactory and Artifactory instances [only accept PUT requests](https://jfrog.com/help/r/artifactory-how-to-debug-artifactory-issues-based-on-http-status-codes/405-method-not-allowed).

I've checked with Artifactory docs, and unless I'm wrong there doesn't seem to be a way of doing anything on the Artifactory side to allow `pdm publish` to work.

## Expected behavior

A successful upload of artifacts to the target repo.

## Environment Information

```bash
PDM version:
  2.9.3
Python Interpreter:
  /path/to/my/project/env//bin/python3.9 (3.9)
Project Root:
  /path/to/my/project
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.6",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "22.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.6.0: Fri Sep 15 13:39:52 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_X86_64",
  "python_full_version": "3.9.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "darwin"
}
```

Can we possibly add an option to set the upload method (PUT or POST) and have that passed to the CLI?

**Comment by frostming** [comment]
Interesting, so how would the pypa recommended tool `twine` suppose to work since it also uses POST. Or, which tool you used before for publishing to artifactory?

**Comment by pawamoy** [comment]
I remember using Twine to publish to Artifactory before :thinking: Would be surprising if they broke Twine by changing the HTTP verb.

**Comment by sr-murthy** [comment]
@frostming I don't know, but in other projects, which are maintained by other people not me, they use `twine` or in some cases unfortunately, `distutils`. These are proprietary projects publishing to an internal Artifactory instance.

This issue is in a project I maintain myself, and I use PDM for everything else, including building artifacts. It would be nice to use it to publish also, but it looks like I'll have to use twine for the moment.

**Comment by sr-murthy** [comment]
I can see that `twine upload` uses POST, but it seems to work this Artifactory instance:

    #18 [13/14] RUN twine upload -r artifactory_dev dist/*
    #18 0.985 Uploading distributions to 
    #18 0.985 <Artifactory instance URL>
    #18 1.014 Uploading <package wheel>-py3-none-any.whl
    100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.5/125.5 kB • 00:00 • 36.9 MB/s
    #18 1.174 Uploading <package sdist>.tar.gz
    100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.8/77.8 kB • 00:00 • 53.8 MB/s
    #18 1.283 
   #18 DONE 1.7s

I cannot explain why. Does/would the PDM POST request look similar to the `twine` request? I'm guessing they are similar. I haven't debugged this, so I suppose we could look at any differences in the actual requests being made.

**Comment by frostming** [comment]
I can't reproduce the 405 error with a trial Artifactory instance.

**Comment by sr-murthy** [comment]
@frostming The Artifactory instance is on-premise and with the repository it has a URL like:

    https://artifactory.<org-name>.local/parent/PypiDev/

One thing I should mention is that when I ran `pdm publish` I was using an Artifactory account password as the password value in `pdm publish`. But with `twine upload` I was using an API token. I will try it using the same API token as the password value in `pdm publish`. That might work, hopefully.

**Comment by sr-murthy** [comment]
@frostming I did not add the index to PDM config before running `pdm publish`, because the Artifactory instance is only used to publish internal releases. It is not used as the main PyPI source. Is adding to config a requirement for `pdm publish`?

Also, I just tried a similar command with `--ca-certs`:

    $ pdm publish --verbose --project . -r "$ARTIFACTORY_PYPI" -u "$ARTIFACTORY_PYPI_USER" -P "$ARTIFACTORY_PYPI_TOKEN" --no-build --ca-certs $(python -m certifi)

    requests.exceptions.SSLError: HTTPSConnectionPool(host='artifactory.oxfordnanolabs.local', port=443): Max retries exceeded with url: /artifactory/api/pypi/ONTDev-Pypi (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

Why does this not work?

**Comment by sr-murthy** [comment]
Tried again same error, but this now seems much closer to work - the error seems purely related to SSL certs required by the Artifactory instance. Not PDM publish. So I'll keep it open, unless you feel it's a wontfix, in which case you can close it.

**Comment by sr-murthy** [comment]
Closing now, as it does seem to be SSL related.

I think it would useful to add some more examples in `publish` docs.
