### ISSUE TITLE
PDM complains when using 3.12 with requires-python >=3.10

### ISSUE THREAD

**Issue by lmmx** [pdm-project/pdm#2347]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

I had a numpy dependency which wouldn't install, it turned out to be a 3.12 requirement to use numpy>=1.26 ([see](https://github.com/pypa/pip/issues/12179)).

When I installed a package with the following TOML sections

```
dependencies = [
    "numpy>=1.26",
    "transformers",
    "pydantic>=2.4.2",
    "defopt",
]
requires-python = ">=3.10,<3.13"
```

I got the error:

```sh
$ python --version
Python 3.12.0
$ pdm install
Lock file does not exist
Updating the lock file...
🔒 Lock failed
Unable to find a resolution because the following dependencies don't work on all Python versions in the range of the project's `requires-python`: >=3.10.
  python>=3.9,<3.13 (from <Candidate numpy@1.26.0 from https://pypi.org/simple/numpy/>)
  python>=3.9,<3.13 (from <Candidate numpy@1.26.1 from https://pypi.org/simple/numpy/>)
A possible solution is to change the value of `requires-python` in pyproject.toml to >=3.10,<3.13.
See /tmp/pdm-lock-h1jlyfvt.log for detailed debug log.
[ResolutionImpossible]: Unable to find a resolution
Add '-v' to see the detailed traceback
```

## Actual behavior

Installation fails.

## Expected behavior

I presume it should be able to resolve the Python version without pinning the range like this?

If I have 3.12 and the Python version TOML config says `>=3.10` then I would expect it to install for 3.12 without failing.

## Environment Information

```sh
pdm info && pdm info --env
```

```bash
PDM version:
  2.10.0
Python Interpreter:
  /home/louis/miniconda3/envs/classipypi/bin/python (3.12)
Project Root:
  /home/louis/dev/classipypi
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.12.0",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.0-60-generic",
  "platform_system": "Linux",
  "platform_version": "#66~20.04.1-Ubuntu SMP Wed Jan 25 09:41:30 UTC 2023",
  "python_full_version": "3.12.0",
  "platform_python_implementation": "CPython",
  "python_version": "3.12",
  "sys_platform": "linux"
}
```

**Comment by xzmeng** [comment]
I've encoutered this problem several times recently, and it seems to be caused by numpy 1.26 pinning its maximum python version.

https://github.com/numpy/numpy/blob/411a55b9ec084c3315fe5f199351c31d0eb3c352/pyproject.toml#L29C19-L29C19

**Comment by pawamoy** [comment]
[Yes](https://github.com/pdm-project/pdm/issues/2339). As hinted in the error message, you have to add the upper bound to `requires-python` so that it is a subset of what your dependencies support.

The example you gave should work:

```toml
dependencies = [
    "numpy>=1.26",
    "transformers",
    "pydantic>=2.4.2",
    "defopt",
]
requires-python = ">=3.10,<3.13"
```

I suspect you didn't save before running `pdm lock` again?

**Comment by frostming** [comment]
In fact, version 2.10.0 introduced a new warning message that explicitly tells you how to fix it. It should have been shown but I don't know why it didn't appear in the output you pasted.

**Comment by sr-murthy** [comment]
> I've encoutered this problem several times recently, and it seems to be caused by numpy 1.26 pinning its maximum python version.
> 
> https://github.com/numpy/numpy/blob/411a55b9ec084c3315fe5f199351c31d0eb3c352/pyproject.toml#L29C19-L29C19

I think Numpy applied this pin via a [release branch](https://github.com/numpy/numpy/pull/24962) - it doesn't appear in the `main` [project TOML](https://github.com/numpy/numpy/blob/main/pyproject.toml#L19).

**Comment by xzmeng** [comment]
So numpy 1.26.2 will not complain it any more. Thanks for the information!
