### ISSUE TITLE
Optimise docker build when private repo is used

### ISSUE THREAD

**Issue by oau-dev** [pdm-project/pdm#2353]
hello,

when I build a docker image with a private repo I need to inject gitlab token in build args. Like :

```
FROM python:3.10-slim AS builder
WORKDIR /app
RUN pip install -U pip setuptools wheel && pip install pdm
RUN apt-get update && apt-get install -y librdkafka-dev gcc && apt-get clean
COPY pyproject.toml pdm.lock /app/
ARG CI_JOB_TOKEN
ENV CI_JOB_TOKEN=$CI_JOB_TOKEN
RUN pdm install --prod --no-lock --no-editable
```
The result is that pdm install is run for each build. Any clue how I can prevent this.

many thx for your help.

oau

here the full dockerfile : 

```
FROM python:3.10-slim
WORKDIR /app
RUN useradd --create-home app
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONFAULTHANDLER 1
ENV PYTHONUNBUFFERED 1
ENV VIRTUAL_ENV=/app/.venv/
ENV PATH=/app/.venv/bin:$PATH
ENV PYTHONPATH=/app/.venv/lib/python3.10/site-packages/
COPY --from=builder /app/.venv /app/.venv/
COPY backend /app
USER app
CMD daphne -b 0.0.0.0 --application-close-timeout 300 --proxy-headers backend.asgi:application
```

**Comment by frostming** [comment]
Here is a simplified form of the Dockerfile, but I failed to reproduce the issue you described

```docker
FROM python:3.10-slim
WORKDIR /app
RUN pip install -U pip setuptools wheel && pip install pdm
COPY pyproject.toml pdm.lock /app/
ARG CI_JOB_TOKEN
ENV CI_JOB_TOKEN=$CI_JOB_TOKEN
RUN pdm install --prod --no-lock --no-editable
```

Build it with `docker build . --build-arg CI_JOB_TOKEN=abc -t pdm-test`

**Comment by oau-dev** [comment]
With this pdm install is not ran everytime you build the image even pyproject.toml pdm.lock did not change ?

**Comment by frostming** [comment]
As long as pyproject.toml and pdm.lock and CI_JOB_TOKEN don't change, it won't build again.

**Comment by oau-dev** [comment]
ok, let me try this. Thx for your help.

**Comment by oau-dev** [comment]
Ok, I got it. CI_JOB_TOKEN is different for each pipeline. Rebuilding all the image each time. It's a gitab issue. Many thx for your help.

**Comment by frostming** [comment]
> Ok, I got it. CI_JOB_TOKEN is different for each pipeline. Rebuilding all the image each time. It's a gitab issue. Many thx for your help.


You can setup a shared cache for .venv folders. So that `pdm install` doesn't last too long when cache hits.
