### ISSUE TITLE
Problems installing nmslib

### ISSUE THREAD

**Issue by Lunatik00** [pdm-project/pdm#2368]
- [ ] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
Use interpreter 3.10 or superior and trying to add nmslib

## Actual behavior

NMSlib is a library that has to be build for 3.10, but it can't be build for 3.11, for some weird reason when I am trying to add it with 3.10 fails to build (I have used it with pip install in 3.10 and it builds fine), apparently for some reason is trying to use 3.11 to build, I specify to only use 3.10  with the requires-python = ">=3.10,<3.11", 

## Expected behavior

NMSlib should be built with 3.10, the specified restriction in the .toml 

## Environment Information
I use arch, it has python 3.11 as the system python, I also have 3.9 from AUR and 3.10 from pyenv

{
  "implementation_name": "cpython",
  "implementation_version": "3.10.12",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.5.8-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Thu, 19 Oct 2023 22:52:14 +0000",
  "python_full_version": "3.10.12",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}

**Comment by frostming** [comment]
> apparently for some reason is trying to use 3.11 to build, I specify to only use 3.10 with the requires-python = ">=3.10,<3.11",

Please show the log to prove that is "apparent"

**Comment by Lunatik00** [comment]
I said apparent because it points to python3.11 in the error, sorry for the unclear language, it's how I talk just because I am not 100% sure, because it can point to it for another reason since PDM is installed with 3.11, also, this is just speculation as a starting point, the main point is that with pip in 3.10 works and builds it correctly but with PDM it doesn't work. 

```
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "", email = ""},
]
dependencies = [
    "nmslib>=2.1.1",
]
requires-python = ">=3.10,<3.11"
readme = "README.md"
license = {text = "MIT"}
```


![Screenshot_20231105_230845](https://github.com/pdm-project/pdm/assets/72462823/c973f56b-a0cf-4229-8544-4d544b55e841)

**Comment by frostming** [comment]
PDM is installed in Python 3.11, but it will use what you specified for your project to build. So the cause you suspect is not valid. You should look more close at the build error for why it fails.
