### ISSUE TITLE
Wrong dependencies are fetched

### ISSUE THREAD

**Issue by denik** [pdm-project/pdm#2373]
I have a dependency that does the following in setup.py

```
if sys.version_info.major == 3:
   # use dependency1
else:
   # use dependency2
```

and publishes only wheel for py2 and source distribution:
 - m3-4.3.3-py2-none-any.whl    (this has dependency2 in metadata)
 - m3-4.3.3.tar.gz

My pyproject.toml specifies requires-python = ">=3.9,<3.10".

pdm (2.10.0) generates the lock file as follows:

```
[[package]]
name = "m3"
version = "4.3.3"
dependencies = [
  <dependency2>,
]
files = [
    {file = "m3-4.3.3.tar.gz", hash = "..."},
]
```

In other words, it uses dependency information from the py2 wheel and not from the source. It correctly added source distribution and not the wheel to the list of files though.

I think it has to do with allow_all parameter here, this patch fixes the dependency (but I don't know if it breaks something else or if there is a deeper problem):

```
diff --git a/src/pdm/models/candidates.py b/src/pdm/models/candidates.py
index 434df1ac..b1c8a5cd 100644
--- a/src/pdm/models/candidates.py
+++ b/src/pdm/models/candidates.py
@@ -479,7 +479,7 @@ class PreparedCandidate:
                     self._unpacked_dir = result

     def prepare_metadata(self, force_build: bool = False) -> im.Distribution:
-        self.obtain(allow_all=True, unpack=False)
+        self.obtain(allow_all=False, unpack=False)

         metadata_parent = create_tracked_tempdir(prefix="pdm-meta-")
         if self.wheel:
```

**Comment by frostming** [comment]
Ignore the wheel for this package: `export NO_BINARY=ms`

**Comment by denik** [comment]
> We assume all wheels have the same dependencies, this could save build time for most packages.

This is a big and often wrong assumption, especially if wheel is py2 and target Python version is 3.x.

> You need to manually ignore the wheels for those packages which break this assumption. Does that make sense to you?

Well, I don't know in advance which wheels break this assumption. This one was discovered by accident. I'd prefer to have a tool to figure out the dependencies, but I understand if that's not the direction you want to take. In that case, caveat in documentation would be helpful. Also, calling the lock file "cross platform" is somewhat misleading.

**Comment by frostming** [comment]
> especially if wheel is py2 and target Python version is 3.x.

In my experience that is not often. Old packages that support py2 often ship "universal" wheels(py2.py3). It's the first time i've seen a py2 only wheel like this.
