### ISSUE TITLE
pdm self update does not work but reports that it does

### ISSUE THREAD

**Issue by johnkangw** [pdm-project/pdm#2377]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
Run 
`pdm self update -v`

## Actual behavior

Does not update from 2.10.0 to 2.10.1
## Expected behavior
Update to 2.10.1
I tried running the 
`Please run C:\Users\JKANG1\AppData\Local\Programs\Python\Python311\python.exe -m pdm self update to upgrade.
`
But that does not work either
## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
pdm info
Inside an active virtualenv C:\Users\JKANG1\PycharmProjects\dash-site-evaluation\.venv, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
PDM version:
  2.10.0
Python Interpreter:
  C:\Users\JKANG1\PycharmProjects\dash-site-evaluation\.venv\Scripts\python.exe (3.11)
Project Root:
  C:/Users/JKANG1/PycharmProjects/dash-site-evaluation
Local Packages:


PDM 2.10.0 is installed, while 2.10.1 is available.
Please run `C:\Users\JKANG1\AppData\Local\Programs\Python\Python311\python.exe -m pdm self update` to upgrade.
Run `pdm config check_update false` to disable the check.

(dash-site-evaluation-3.11) PS C:\Users\JKANG1\PycharmProjects\dash-site-evaluation> pdm info --env
Inside an active virtualenv C:\Users\JKANG1\PycharmProjects\dash-site-evaluation\.venv, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.6",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.22621",
  "python_full_version": "3.11.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "win32"
}

PDM 2.10.0 is installed, while 2.10.1 is available.
Please run `C:\Users\JKANG1\AppData\Local\Programs\Python\Python311\python.exe -m pdm self update` to upgrade.
Run `pdm config check_update false` to disable the check.

```

**Comment by frostming** [comment]
Can you show the output you run `C:\Users\JKANG1\AppData\Local\Programs\Python\Python311\python.exe -m pdm self update` or do you expect I can reproduce on my side?

**Comment by johnkangw** [comment]
Hi @frostming Thanks for the reply!

**Comment by frostming** [comment]
Can you run with `-v` option? also please quit the current venv.

**Comment by johnkangw** [comment]
@frostming Sure thing! Results below:

PS C:\Users\JKANG1> C:\Users\JKANG1\AppData\Local\Programs\Python\Python311\python.exe -m pdm self update -v
Running pip command: ['install', '--upgrade', 'pdm==2.10.1']
STATUS: Updating pdm to version 2.10.1
Installing version 2.10.1 succeeds.

PDM 2.10.0 is installed, while 2.10.1 is available.
Please run `C:\Users\JKANG1\AppData\Local\Programs\Python\Python311\python.exe -m pdm self update` to upgrade.
Run `pdm config check_update false` to disable the check.
PS C:\Users\JKANG1> C:\Users\JKANG1\AppData\Local\Programs\Python\Python311\python.exe -m pdm self update -v
Running pip command: ['install', '--upgrade', 'pdm==2.10.1']
STATUS: Updating pdm to version 2.10.1
Installing version 2.10.1 succeeds.

PDM 2.10.0 is installed, while 2.10.1 is available.
Please run `C:\Users\JKANG1\AppData\Local\Programs\Python\Python311\python.exe -m pdm self update` to upgrade.
Run `pdm config check_update false` to disable the check.

**Comment by frostming** [comment]
It is just running this command and no other magic here:

```
C:\Users\JKANG1\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pdm==2.10.1
```

And if it doesn't work either there is likely some issue with your environment, not PDM's fault. You might need to nuke it and reinstall from clean.

**Comment by johnkangw** [comment]
@frostming Makes sense! Thanks for the heads up. The command you gave me actually worked! Thanks so much! I'm now up to the current version of 2.10.2!

**Comment by johnkangw** [comment]
@frostming Do you know why the pdm self update did not work but the command you gave me did?

**Comment by frostming** [comment]
I don't if I cant reproduce this

**Comment by frostming** [comment]
One possibility is that `pip install` itself reports a success status while fails actually. In that case the output won't be shown by PDM so you can't inspect it. We need to improve the logging here.

Anyway, did you succeed updating pdm to the latest versions with `self update`?

**Comment by lazarillo** [comment]
I also was not able to update via `pdm self update`, but was able to update without any^ problems using `python -m pip install --upgrade pdm`.

I ran `pdm self update -vv`.  It just hung forever, without ever even emitting any logging information except for the first line, which says that it is executing the file.

^ I do have one problem with `pip`s dependency resolver, because it complains that the version of `protobuf` that I am using is incompatible with the version of `apache-beam` that I am using. This is unrelated - unless perhaps `pdm self update` stalls if the dependency resolver has problems - and is inevitable if one uses both Apache Beam (Dataflow) and Protocol Buffers, because Google is both putting overly stringent *ceilings* on the install versions, and it is ridiculously behind in lifting those ceilings. (Currently 11 months out of date.)
