### ISSUE TITLE
PDM does not correctly install packages working in the same top level directory

### ISSUE THREAD

**Issue by sdebruyn** [pdm-project/pdm#2378]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

Projects like dbt and its adapters make use of the same top level directory (`dbt`) to install one or more adapters into dbt. When you install `dbt-postgres` using pip, you correctly see the adapter in the folder `dbt/adapters` in your `site_packages`. When you do the same with PDM, the adapter is not there. It cannot be found by Python either.

## Steps to reproduce

1. `pdm init`
2. `pdm add dbt-postgres`
3. `.venv/bin/python -c 'from dbt.adapters.postgres import PostgresAdapter'`

## Actual behavior

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'dbt.adapters.postgres'
```

## Expected behavior

No error

## Environment Information

```
PDM version:
  2.10.0
Python Interpreter:
  /Users/sam/projects/pdm-dbt-adapters/.venv/bin/pyth
on (3.11)
Project Root:
  /Users/sam/projects/pdm-dbt-adapters
Local Packages:
```

```json
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.6",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "23.0.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 23.0.0: 
Thu Aug 17 21:24:46 PDT 2023; 
root:xnu-10002.1.11~3/RELEASE_ARM64_T6020",
  "python_full_version": "3.11.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}
```

**Comment by xzmeng** [comment]
try `pdm config --local install.cache false` to disable the cache.

Or `pdm config --local install.cache_method pth` to not use symbolic link.

**Comment by sdebruyn** [comment]
Awesome, that works! Thank you! :)
