### ISSUE TITLE
`pdm build` creates `sdist` with potentially oversized `PKG-INFO` Description

### ISSUE THREAD

**Issue by sanmai-NL** [pdm-project/pdm#2399]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

`pdm build` a project with a `README.md` file longer than 4000 characters.

## Actual behavior

The `README.md` is included as Description, without limit.
Upon publishing such an artifact, the package registry may reject it because of the oversized Description.

## Expected behavior

- The user can control how Description is sourced, insofar that a `README.md` is not automatically included as Description.
- When the user has decided to use `README.md` as Description, the Description's text length is checked to a set of limits that are seen in practice. For example, for the GitLab Package Registry, the limit is 4000 characters.
- When the check fails the build should fail, but it should be possible to override the check.

## Environment Information

```sh
# Paste the output of `pdm info && pdm info --env` below:
## Stripped of sensitive yet irrelevant info.
...
PDM version:
  2.10.1
...
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.6",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "23.1.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:45 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6020",
  "python_full_version": "3.11.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
We are not going to add this check on build, it's more like a backend feature.

And the PyPI will always validate this when uploading. Close it now.
