### ISSUE TITLE
pdm init offers to import requirements on existing project, but fails with unfriendly error if you accept

### ISSUE THREAD

**Issue by mcclure** [pdm-project/pdm#2416]
There is a popular open-source Python library here: https://github.com/enjoy-digital/litex

It does not use PDM, but I like to introduce PDM in my local copies of Python projects as a easy way of venv'ing their dependencies. When I attempted `pdm init` on this project, pdm recognized it was an existing project and made an offer to import its dependencies into the pdm pyproject.toml. When I said "yes", bad stuff happened.

**REPRO STEPS**

git clone https://github.com/enjoy-digital/litex . pdm init in the repro root. take the defaults until it asks if you want to import "files from other formats", then agree.

**OBSERVED BEHAVIOR**

When it asks about importing "files from other formats", it gives me two offers: Import "requirements" (meaning, requirements.txt?) or import "setuppy" (setup.py?). Each fails, with a different error.

If I pick "requirements":

```
mcc@Anthy:~/work/r/v/agg23/litex$ pdm init
Creating a pyproject.toml for PDM...
Please enter the Python interpreter to use
0. /usr/bin/python3.11 (3.11)
1. /usr/bin/python3 (3.11)
Please select (0): 1
Using Python interpreter: /usr/bin/python3 (3.11)
Would you like to create a virtualenv with /usr/bin/python3? [y/n] (y): y
Virtualenv is created successfully at /home/mcc/work/f/other/litex/.venv
Is the project a library that will be uploaded to PyPI [y/n] (n): n
License(SPDX name) (MIT): no license
Author name (mcc): 
Author email ([REDACTED]) 
Python requires('*' to allow any) (>=3.11): 
Changes are written to pyproject.toml.
Found following files from other formats that you may import:
0. /home/mcc/work/f/other/litex/setup.py (requirements)
1. /home/mcc/work/f/other/litex/setup.py (setuppy)
2. don't do anything, I will import later.
Please select: 0
[RequirementError]: The local path 'from' does not exist.
```

If I pick "setuppy":

```
mcc@Anthy:~/work/r/v/agg23/litex$ pdm init
Creating a pyproject.toml for PDM...
Please enter the Python interpreter to use
0. /usr/bin/python3.11 (3.11)
1. /usr/bin/python3 (3.11)
Please select (0): 1
Using Python interpreter: /usr/bin/python3 (3.11)
Would you like to create a virtualenv with /usr/bin/python3? [y/n] (y): 
Virtualenv is created successfully at /home/mcc/work/f/other/litex/.venv
Is the project a library that will be uploaded to PyPI [y/n] (n): 
License(SPDX name) (MIT): no license
Author name (mcc): 
Author email ([REDACTED]): 
Python requires('*' to allow any) (>=3.11): 
Changes are written to pyproject.toml.
Found following files from other formats that you may import:
0. /home/mcc/work/f/other/litex/setup.py (requirements)
1. /home/mcc/work/f/other/litex/setup.py (setuppy)
2. don't do anything, I will import later.
Please select: 1
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pdm/models/in_process/parse_setup.py", line 211, in <module>
    print(json.dumps(parse_setup(sys.argv[1])))
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pdm/models/in_process/parse_setup.py", line 174, in parse_setup
    import setuptools
ModuleNotFoundError: No module named 'setuptools'
[CalledProcessError]: Command '['/home/mcc/work/f/other/litex/.venv/bin/python', '-Es', 
'/usr/lib/python3/dist-packages/pdm/models/in_process/parse_setup.py', '/home/mcc/work/f/other/litex/setup.py']' 
returned non-zero exit status 1.
Add '-v' to see the detailed traceback
```

At this point the program exits; a pyproject.toml and some dotfiles are created, but it is unclear if the app completed "successfully" or if my pdm for the repo is in an inconsistent state.

I consider neither of the provided errors actionable. If the errors stem from unexpected format in a local file, it does not tell me which files are of incorrect format.

**Expected behavior**

There are two divergences from what I expect here.

First off, even before the error occurs, the initial question about importing "files" is not as helpful as it could be. It is unclear exactly what this feature is importing (dependencies? dependencies and other information?) and not *totally* clear what files it is importing from. If doing so is practical, I would expect this feature to say something like "Found following files from other formats. Import dependencies?" . I would also expect, rather than simply saying "requirements" and "setuppy", for it to indicate the paths to the found files. (The litex project I link above has a setup.py, but does *not* have a requirements.txt, so I still don't know what "requirements" was importing.)

Second off, due to the program terminating abnormally and thus leaving me uncertain if the repo is in an inconsistent state, in this case the feature offer turns out to be "worse than nothing". (I attempted to undo the pdm init before trying again, but it's less than clear exactly what I need to delete to wind back the pdm init.) Therefore, I would "expect" any one of the following behaviors:

1. Remove the "import files" feature.
2. The "import files" feature detects ahead of time whether importing a particular file will fail; if it will fail, it does not offer to import the file.
3. If the import files feature fails, it catches the exception, and prints a helpful user message such as "pdm is successfully set up, but importing file [filepath] failed. your dependencies were not imported." (*Also* printing the exception for debugging could be helpful, and for gold plating printing the command we can enter to try importing again would be *great*— but the information that pdm succeeded other than the import step is most important.)

**Form values**

- [X] I have searched the issue tracker and believe that this is not a duplicate.

"Environment Information" / "Make sure you run commands with `-v` flag before pasting the output."

Output of `env`: [env.txt](https://github.com/pdm-project/pdm/files/13418792/env.txt)
-v followed by pdm info commands, [requirements-case.txt](https://github.com/pdm-project/pdm/files/13418794/requirements-case.txt)
-v followed by pdm info commands, [setuppy-case.txt](https://github.com/pdm-project/pdm/files/13418795/setuppy-case.txt)

litex branch master, commit 022776801a44
Ubuntu 23.10, Python 3.11.6

**Comment by frostming** [comment]
We already emits a friendly message on failure, but you are on an old version of PDM.
