### ISSUE TITLE
`pdm install` in  a venv might kill itself due to dependencies

### ISSUE THREAD

**Issue by didib** [pdm-project/pdm#2426]
- [x ] I have searched the issue tracker and believe that this is not a duplicate.

I am new to  pdm, so might have missed something.

I got some error message, found it in google, so added my own comment here: https://github.com/certifi/python-certifi/issues/225#issuecomment-1822947503

But I now think this is actually a bug in pdm, so reporting current issue as well.

## Steps to reproduce

Not sure. I didn't try to create a minimal reproducer. I think the minimum should be something like:
1. Have a project with a pdm.lock that requires a package which is a dependency of pdm itself, at a non-latest version (or a version different from what pdm wants)
2. Create a python venv
3. Inside the venv, `pip install pdm`
4. `pdm install`

## Actual behavior

It seems that pdm noticed the requirement for the older version of the dependency, and this causes it to remove it, and this breaks pdm itself later on.

## Expected behavior

That's the hard part :-). Perhaps pdm should have a list of its own dependencies, and if these are not already installed, or are installed at wrong versions (wrong for both itself and the package that uses it), should have special behavior - such as to first install these with the versions required in pdm.lock, then restart itself (to make sure it then uses the correct versions).

## Environment Information

In my specific case, I am on RHEL8, and did something like:
```
python3.9 -m venv /path/to/venv
. /path/to/venv/bin/activate
. pip install pdm
cd /path/to/package
pdm install
```

My specific failure was (copying from the pdm log file):
```
...
pdm.termui: Removing distribution certifi
...
pdm.termui: Error occurs: 
Traceback (most recent call last):
  File "/usr/lib64/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
  File "/path/to/venv/lib64/python3.11/site-packages/requests/adapters.py", line 261, in cert_verify
    raise OSError(
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /path/to/venv/lib64/python3.11/site-packages/certifi/cacert.pem
```

My workaround was, before `pdm install`, to run `pip install certifi==2023.7.22` (the version that was in the package's pdm.lock).

**Comment by didib** [comment]
> The short answer is: don't install PDM in the venv. It must be isolated from your dependencies. Use one of the recommended installation methods.

This makes a lot of sense. If so, perhaps negate the name and meaning of `PDM_IGNORE_ACTIVE_VENV`? E.g. call it `PDM_USE_ACTIVE_VENV`, and use the venv only if it's set? And/or check if pdm itself is being used from inside the active venv?

I don't mind closing current issue. Many years ago I was in a similar situation (a python project that installs dependencies for itself then restarts itself) and I understand if you do not want to go this way.

**Comment by frostming** [comment]
We've changed to a less-destructive update approach in #2427 , so this won't appear.
