### ISSUE TITLE
`pdm run` picks a surprising environment to run a loose .py script

### ISSUE THREAD

**Issue by whitequark** [pdm-project/pdm#2432]
I have searched the issue tracker, but there are so many results for any reasonable query that I'm not sure if this wasn't discussed before.

## Steps to reproduce

1. Create two PDM projects `~/prj1` and `~/prj2` with `pyproject.toml` in it and run `pdm install`.
2. Create a loose script file in `~/prj1/t.py`.
3. Run `cd ~/prj2; pdm run ~/prj1/t.py`.

## Actual behavior

The script is executed within the `~/prj1/.venv` environment.

## Expected behavior

The script is executed within the `~/prj2/.venv` environment (where `pdm run` is run), just like any other command invoked with `pdm run` inside `~/prj2`.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.10.5.dev1+gd3f127cb
Python Interpreter:
  /home/whitequark/Projects/amaranth/.venv/bin/python (3.11)
Project Root:
  /home/whitequark/Projects/amaranth
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.11.6",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.1.0-13-amd64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29)",
  "python_full_version": "3.11.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}
```

**Comment by whitequark** [comment]
I discovered that the same behavior happens if I create `~/prj2/tt.py` as a symlink to `../prj1/tt.py`. That is even more surprising!

**Comment by frostming** [comment]
But I can't reproduce, here is the content of `proj1/test.py` and `proj2/test.py`:

```python
import click

print(click)
```

And install `click` into both projects. Run:

```
cd proj2
pdm run ../proj1/test.py
```
I got:
```
<module 'click' from '/Users/fming/wkspace/github/test-pdm/proj2/.venv/lib/python3.12/site-packages/click/__init__.py'>
```

**Comment by whitequark** [comment]
Thanks for looking into it, I will try to narrow down what is it about my environment that causes this.
