### ISSUE TITLE
Prevent the creation of .pdm-python

### ISSUE THREAD

**Issue by linusheinz** [pdm-project/pdm#2438]
I would like to use pdm sync in production, I couldn't find a way in Docs to prevent the creation of the /.pdm-python. Is there currently a flag for that. 

Best Linus

**Comment by frostming** [comment]
No, the file is for locking the interpreter being used so following steps can use the same one. It makes the environment stable. Why don't you want that?

**Comment by pawamoy** [comment]
I suppose @linusheinz is getting a permission error since `HOME` isn't set and PDM tries to create the file at `/.pdm-python`. @linusheinz you can set your HOME to a temporary, writable directory in production:

```bash
export HOME=/tmp/home
mkdir $HOME
```

**Comment by linusheinz** [comment]
Sorry my bad, now I understand. @pawamoy Thanks for the help, that solved it.
@frostming I could not find documentation about this file in the docs, maybe this could help prevent this question in the future.
