### ISSUE TITLE
on windows User enviroment variable path is used

### ISSUE THREAD

**Issue by 07pepa** [pdm-project/pdm#2443]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
run instalation comand from website
## Actual behavior
everything is correct just user (not system) path enviroment variable is used
## Expected behavior
system enviroment variable for path should be used since different users may use only them... like pycharm does
## Environment Information
Windows 11

**Comment by pawamoy** [comment]
I don't think it has anything to do with PDM. It's purely Windows environment variables configuration.
