### ISSUE TITLE
Unable to install gym==0.21.0

### ISSUE THREAD

**Issue by ethanluoyc** [pdm-project/pdm#2446]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```
pdm add 'gym==0.21.0'

```

## Actual behavior

```
pdm.termui: Candidate rejected because it contains invalid metadata: gym@0.21.0
pdm.termui: Conflicts detected:

🔒 Lock failed
Traceback (most recent call last):
  File "/home/yicheng/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/yicheng/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 295, in main
    return Core().main(args or sys.argv[1:])
  File "/home/yicheng/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/home/yicheng/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 203, in main
    self.handle(project, options)
  File "/home/yicheng/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/home/yicheng/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/cli/commands/add.py", line 69, in handle
    self.do_add(
  File "/home/yicheng/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/cli/commands/add.py", line 162, in do_add
    resolved = do_lock(
  File "/home/yicheng/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/cli/actions.py", line 119, in do_lock
    ui.echo(format_resolution_impossible(err), err=True)
  File "/home/yicheng/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/cli/utils.py", line 654, in format_resolution_impossible
    project_requires: PythonRequirement = next(cause.requirement for cause in causes if cause.parent is None)
StopIteration
```

The reason is that gym==0.21.0 has some quirk dependency on opencv in the form of `opencv-python>=3.`
https://github.com/openai/gym/blob/c755d5c35a25ab118746e2ba885894ff66fb8c43/setup.py#L20C30-L20C47

Running `pdm add 'opencv-python>=3.'` fails too, but if I run with `pip install 'opencv-python>=3.'` pip will install the correct version, so pdm is inconsistent with the behavior with pip.

## Expected behavior

pdm should allow installing 'gym==0.21.0' even when the dependency specification is slightly unusual to be consistent with pip.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.10.4
Python Interpreter:
  /<redacted>/python (3.10)
Project Root:
  /<redacted>
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.10.13",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.0-89-generic",
  "platform_system": "Linux",
  "platform_version": "#99~20.04.1-Ubuntu SMP Thu Nov 2 15:16:47 UTC 2023",
  "python_full_version": "3.10.13",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}
```

**Comment by pawamoy** [comment]
Unfortunately, this version of gym has broken metadata, and PDM is not as forgiving as pip was/is. It seems their setup.py was fixed in next versions: are they compatible with your project? Maybe there's room for improvement in PDM's error reporting here.

**Comment by frostming** [comment]
> Maybe there's room for improvement in PDM's error reporting here.

I doubt it would be of much help. The main concern here is users think PDM should be consistent with pip.

**Comment by pawamoy** [comment]
Yes, maybe this could be listed as a non-goal in the readme.

What I meant is that PDM told there was invalid metadata in gym 0.21.0, but didn't show what particular metadata was invalid. Showing where the error is helps to fix the projects with broken metadata, at least to publish new unbroken dists :)

**Comment by frostming** [comment]
To provide a little bit context: `pip` is still using a vendored `packaging==21.3` in the year of 2023. Python packaging group makes new PEP standards and try to make the python packaging implementation-agnostic, allowing more tools to enter this area. But at present, from what I can tell, a lot of details still exist only in pip's implementation.

**Comment by ethanluoyc** [comment]
Thanks @pawamoy @frostming. 

I agree that it's actually a good idea for PDM to be more strict. gym==0.21 came up because of one of my upstream dependency. I will get this sorted upstream on my dependency repos. Generally I would love to not do this because some the projects are for research and are not maintained very well :) I am getting quite reluctant of maintaining my forks nowadays (10+ of them) 

I worked around this issue for now with dependency overrides.

**Comment by pawamoy** [comment]
Ah, great, didn't try locally to see for myself, thanks :)

@ethanluoyc yeah I completely understand the need to be able to install old and broken things, sometimes you just can't go around it. If it's impossible to fix, I would personally use pip to force-install it, or write a script that gets the sources, patches them, builds and install the dist. That's probably what you're doing with your forks somehow, and it has a cost for sure :/

**Comment by frostming** [comment]
Yes, it shouldn't be hard to workaround for an actively maintained library. Change it a compatible version with correct metadata and use `resolution.overrides` if necessary. Alternatively, you can also pin `packaging<22` inside PDM's environment, which can be done via `pdm self add "packaging<22"`. If neither is acceptable you can take @pawamoy 's suggestion, to patch and install locally.

**Comment by Fedeloz** [comment]
I came across the same issue. Using an older version of `wheel` solves the problem, since versions `<0.40.0` are more permissive with legacy `setup.py` metadata:

`pip install setuptools==65.5.0 "wheel<0.40.0"`
`pip install gym==0.21.0`
