### ISSUE TITLE
找不到安装出错后怎么卸载的文档

### ISSUE THREAD

**Issue by bthulu** [pdm-project/pdm#2470]
刚才通过install-pdm.py安装出错了, 想卸掉再通过pip install --user pdm重试一下.

结果文档里根本找不到怎么卸载.

有安装不就应该有卸载么, 为啥文档里根本就没有卸载相关的内容, 还是说这个东西装了就卸不掉的? 360也没这么流氓的.

**Comment by frostming** [comment]
Speculating maliciously before understanding the situation is very rude behavior.

https://arc.net/l/quote/gdbemrvv

**Comment by bthulu** [comment]
抱歉, 当时没找到. Installation那么大, 还单独成行, --remove缺藏的那么好, 我还全局搜了uninstall, 没想到指令是remove.
