### ISSUE TITLE
`pdm` fails to resolve venv when a file called `types.py` is in the current directory for no apparent reason

### ISSUE THREAD

**Issue by arxanas** [pdm-project/pdm#2478]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```sh
$ rm -rf foo && mkdir foo && cd foo
$ touch types.py
$ pdm init -vv
Creating a pyproject.toml for PDM...
Interpreters found but not matching:
  - /usr/local/bin/python (Invalid)
  - /home/waleed/.local/share/pdm/venv/bin/python (Invalid)
[NoPythonVersion]: No python is found meeting the requirement python 
```

## Actual behavior

`pdm init` should prompt to install the virtualenv, etc.

If it fails, it should provide a useful/actionable error message/stack trace. (Of course, this probably happens because there is a module named `types` in the standard library.)

## Expected behavior

`pdm init` should succeed in installing the virtualenv.

## Environment Information

```bash
$ pdm info && pdm info --env
[ProjectError]: The pyproject.toml has not been initialized yet. You can do this by running `pdm init`.
```

(Hmm 🤔)

**Comment by frostming** [comment]
The error is swallowed when we decide whether a Python interpreter is valid, the interpreter may be broken for whatever reasons and we don't want to bother users with the error in those cases.

I think there is a consensus to avoid using file name same as std libs. Closing this now as won't fix.

**Comment by arxanas** [comment]
@frostming not supporting `types` is probably fine, but currently the error message is not actionable, which is not good technical writing (see e.g. https://developers.google.com/tech-writing/error-messages). Can we reopen this issue to focus on improving the error messaging rather than supporting `types`?
