### ISSUE TITLE
Cannot install black 23.12.0

### ISSUE THREAD

**Issue by lucidfrontier45** [pdm-project/pdm#2487]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```sh
pdm add -d black==23.12.0 -v
```

## Actual behavior
```
    raise UndefinedEnvironmentName(
packaging.markers.UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.
```

## Expected behavior

`black` is installed without any error

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

PDM version:
  2.10.4
Python Interpreter:
  /data/home/du/workspace/pdm_test/.venv/bin/python (3.11)
Project Root:
  /data/home/du/workspace/pdm_test
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.11.4",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.0-88-generic",
  "platform_system": "Linux",
  "platform_version": "#98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023",
  "python_full_version": "3.11.4",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}

```

**Comment by lucidfrontier45** [comment]
The previous version `black==23.11.0` can be installed correctly.

**Comment by frostming** [comment]
I can't reproduce this issue, even in a clean docker container.

**Comment by lucidfrontier45** [comment]
@frostming Thank you for reply.

I tried in another machine and as you said I couldn't reproduce the problem.

I was originally working on Ubuntu 22.04 and installed PDM with pipx. The pipx was installed by apt.
After uninstalled PDM and reinstalled it by pipx, it also worked fine in this machine.
Since I can no more reproduce this problem, I'll close this issue. Thank you again.
