### ISSUE TITLE
Add --no-self instruction ad configurable pyproject setting

### ISSUE THREAD

**Issue by JeyDi** [pdm-project/pdm#2492]
## Description

I have different Python projects that are not libraries or packages, for example: API, Simple scripts, Dashboards, etc...

Every time that I launch a pdm command to install dependencies like: `pdm install` PDM will try also to install the project itself as if it were a normal python library.

I know that I have to use the flag: `--no-self` to avoid this behavior, but since in the team there are a lot of Junior developers and people not experts in Python I want to avoid creating macros, Makefile or something else to simplify and remind everyone of this behavior (also because we know that developers' memory is short :) )

## Solution

The best solution will be to have settings in the `pyproject.toml` to have this behavior configurable by default for the project, so I can also create some boilerplates for different projects.

For example:

```toml
[tool.pdm]
self-install = false
```

**Comment by frostming** [comment]
> I have different Python projects that are not libraries or packages, for example: API, Simple scripts, Dashboards, etc...

For non-library projects, just answer `no` on the corresponding question when running `pdm init` or manually add `package-type = "application"` under `[tool.pdm]`

We also support adding fixed args to specific commands via `[tool.pdm.options]` table.

Close this now.

**Comment by baggiponte** [comment]
> We also support adding fixed args to specific commands via [tool.pdm.options] table.

I found out about this option in the docs [here](https://pdm-project.org/latest/usage/config/#passing-constant-arguments-to-every-pdm-invocation) after some digging. Do you think it might be easier to see if the pages were splitted?

There is a lot under "Configure the project" and intuitively I wouldn't think of looking for "passing constant arguments to every invocation" there. The page contains configurations about PDM itself (how it finds Python interpreters and manages the caches) as well as projects and, while I have been using PDM for ~2 years now, I don't have a clear picture about what configurations can go under both a `pdm.toml` and a `pyproject.toml`.

Glad to help out if you think my point holds :)

**Comment by JeyDi** [comment]
Thank you @baggiponte and @frostming this is exactly what I was looking for :)
