### ISSUE TITLE
Change name of `--no-lock` flag for install

### ISSUE THREAD

**Issue by esuh-descript** [pdm-project/pdm#2496]
## Is your feature request related to a problem? Please describe.

Although the documentation is clear on what `--no-lock` does, the name is quite unintuitive, as it could be interpreted to also be to ignore lockfiles on read, rather than just on write.

## Describe the solution you'd like

Package managers in the Node ecosystem like `pnpm` or `yarn` call this option `--frozen-lockfile` or `--immutable`, respectively. I think that something along those lines might be a more intuitive name.

**Comment by deronnax** [comment]
@frostming I think this issue can be closed (you probably wanted the commit [9c9426f](https://github.com/pdm-project/pdm/commit/9c9426f81a7a5bd2d89c54f90c9479ecf4af7898) to do it, but it did not)
