### ISSUE TITLE
Usability: I expected `pdm init package_name` to create a directory package_name, not make the current directory into a package

### ISSUE THREAD

**Issue by noamraph** [pdm-project/pdm#2504]
## Is your feature request related to a problem? Please describe.

I'm creating a new project.
I did:

```bash
cd ~/work
pdm init my_interesting_project

Creating a pyproject.toml for PDM...
Please enter the Python interpreter to use
0. /usr/bin/python (2.7)
1. /usr/bin/python3.11 (3.11)
2. /usr/bin/python3.7m (3.7)
Please select (0): 1
Would you like to create a virtualenv with /usr/bin/python3.11? [y/n] (y): 
Virtualenv is created successfully at /tmp/work/.venv
Project name (work):
```

And only then I discovered that it actually tried to initialize a project in my `work` directory, and I had to remove `.venv`.

I suggest to mimic `git init`: when it gets a name, it creates a directory with this name. cargo does this as well.

Thanks!
Noam

**Comment by frostming** [comment]
That's `pdm init -p my_interesting_project`
