### ISSUE TITLE
A suggestion: change the "feature request" issue category to "feature request / enhancement proposal"

### ISSUE THREAD

**Issue by noamraph** [pdm-project/pdm#2505]
## Is your feature request related to a problem? Please describe.

I want to suggest a better wording for a question ("Is the project a library that is installable?"). It's not a bug report, and it's not a feature request.

## Describe the solution you'd like

I suggest to change the description of the issue category from "feature request" to something like "feature / enhancement request".

Thanks!
Noam

**Comment by frostming** [comment]
SGTM, would you like to contribute?

**Comment by noamraph** [comment]
Sure! How's this PR? https://github.com/pdm-project/pdm/pull/2508
