### ISSUE TITLE
Support copying caching method, in addition to symlinking and hardlinking

### ISSUE THREAD

**Issue by sanmai-NL** [pdm-project/pdm#2511]
## Is your feature/enhancement proposal related to a problem? Please describe.

Hardlinks do not work across filesystems, which means they don't work across layers in OverlayFS as used for containers. Other tools similar to PDM suffer from this too (https://github.com/rust-lang/rustup/issues/2949). This can result in broken container images with PDM-managed applications, as they miss dependencies.

PDM currently links to dependencies in the cache to avoid duplicating them. But a lot of efficiency value is already in the reuse of cached data, even if it were copied in the end. In the context of container builds, [cache mounts](https://docs.docker.com/build/guide/mounts/) disappear after build, so no data will end up duplicated inside the container image anyway.

## Describe the solution you'd like

Support copying caching method, in addition to symlinking and hardlinking.

**Comment by sanmai-NL** [comment]
@frostming I'm prepared to start implementing this. Is there any caching architecture reengineering, i.e. major changes that would cause merge conflicts, you want to merge first?

**Comment by frostming** [comment]
sorry I didn't get the point here. isn't copying method the same as disabling cache? no disk space is shared and each project owns a copy

**Comment by sanmai-NL** [comment]
No, since the cache mount is shared between container builds. This means if I remove an image and rebuild it, the PyPI packages are still cached by Buildkit.

**Comment by frostming** [comment]
fine, it's like a local index server.

the summary is the same, we don't need a copying caching method, it can be achieved in other ways

**Comment by sanmai-NL** [comment]
At what paths is what cached, exactly? If I understand you correctly, I can mount the cache mount at some subpath of the PDM cache and the broken links to packages would not end up in my venv?

**Comment by pawamoy** [comment]
I think everything is in `~/.cache/pdm`.

**Comment by sanmai-NL** [comment]
Then I don't understand @frostming's comment. That cache path I want to cache, and I don't want links from the venv into it.

**Comment by pawamoy** [comment]
The cache is the canonical location. Symlinks are created in the venvs, pointing to contents in the cache, not the contrary (not sure this is what you meant/understood).

Mounting this single folder as a volume should do the trick.

**Comment by sanmai-NL** [comment]
Exactly, so I intend to make a caching method that instead of links from venvs to the cache (which in PDM isn't reality a cache, but a persistent global data store), copies from the cache into the venv. You call PDM's cache a cache because its contents could in theory be reproduced, perhaps. But when a _cache_ is cleared a software system using it should never fail, whereas it could with a data store. Alas, PDM's cache is a bit of a misnomer/mixture of concerns.

Back to the container world. A mount cache cannot be re-mounted in an image. It is an opaque cache specific to the Buildkit builder. It is a true cache, meaning that its contents are never required and can be garbage collected at any time. It's contents also cannot be copied into the image at build time, since it may well contain much more than required for just the current build. E.g., stale non-conflicting data, extraneous data for other product builds that happen to share the cache. This is why PDM needs the copying cache method, as Rustup does.

I see there have been some misconceptions within the PDM world on this so far. I will investigate how alternative Python product management tools have taken up this topic and need.

**Comment by frostming** [comment]
> which in PDM isn't reality a cache, but a persistent global data store

Indeed, that is a more accurate name.

**Comment by sanmai-NL** [comment]
[Poetry](https://github.com/python-poetry/poetry/blob/master/docs/repositories.md#caches) doesn't cache for disk usage savings, it appears. And thus, on the upside, does not have an implementation limited to non-container context.

**Comment by frostming** [comment]
We don't plan to implement such method, closing it now.

**Comment by sanmai-NL** [comment]
@frostming My suggestion was that I'd implement it, which means you wouldn't have to plan for it.

How can users in the context I described benefit from caching. I suspect you don't yet understand the use case.

**Comment by frostming** [comment]
> @frostming My suggestion was that I'd implement it, which means you wouldn't have to plan for it.

It is so weird to support copy method to me. However I am okay to relocate the package store outside of `caches`

**Comment by sanmai-NL** [comment]
To summarize: copy has all advantages of symlinking and hardlinking, once the cache is dismounted. Even outside containers, one has to account for the cache and the venv being on seperate filesystems with potentially different lifecycles, so deduplication is only relevant when they are on the same filesystem (hardlinking method) or at least have the same lifecycle (symlinking method).

I'm thinking hard but cannot envisage a solution where relocating the caches directory would solve this issue. The problem is that this caches directory is no longer available once the container build process has completed. And you want to avoid copying it into the container filesystem afterwards/overwriting all symlinks in the venv with copies.

**Comment by frostming** [comment]
Let me explain it further. The peculiarity arises from the fact that `install.cache` aims to minimize the disk usage of dependencies across projects, while the package store serves as more of an implementation detail in my opinion. Although it happens to be capable for that, their purposes are not the same.

Now let's review your use case from a higher perspective. Essentially, what you want is to "copy files from a single local package store", which is exactly what a normal installation does. What you need to do is to prepare the wheels in a directory and add it as a `find_links` source in `pyproject.toml`. And by "prepare" I mean downloading and building the wheels if necessary. Yes, we lack this utility currently, which is similar to what `pip wheel` does, but it can be provided by a plugin(not implemented yet).

**Comment by frostming** [comment]
If you are still not convinced, I just thought of another point. When running `install_wheel_with_cache()`, the wheel containing all package files are already downloaded and prepared. At this particular point, I can see no point copying from the cache store rather than unpacking the wheel and copy the files there.

**Comment by sanmai-NL** [comment]
Where are the wheels stored vs. the cache items?

**Comment by frostming** [comment]
> Where are the wheels stored vs. the cache items?

They are downloaded into temp dir, with cache mapped to `$PDM_CACHE_DIR`. The point here is they are downloaded even if `install.cache` is enabled. 
.

**Comment by frostming** [comment]
Worth to mention here that copy method has become the default installation method when `install.cache` is `false`.

@sanmai-NL
