### ISSUE TITLE
Misleading `PackageWarning` when adding a package (`myst-nb==1.0.0`) with a version free dependency (`ipython`) whose `requires-python` range is not satisfied on the latest version

### ISSUE THREAD

**Issue by jeertmans** [pdm-project/pdm#2522]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

Just add `myst-nb==1.0.0` to any project that has a minimal Python version below or equal to `3.9`, like in the screenshot below:

![image](https://github.com/pdm-project/pdm/assets/27275099/229b09d2-aec1-446b-92a7-27aed7abdce2)

## Actual behavior

A warning is thrown, when a valid version could be found anyway.

## Expected behavior

Just don't raise a warning because that scared me a bit like: do I have dependencies conflicts? Did I do something?

There is no issue that the latest version available may not be compatible with the Python versions you claim to support in the `requires-python` range. But what's the problem with that?

## Environment Information

```bash
PDM version:
  2.11.1
Python Interpreter:
  /home/jeertmans/Desktop/install-warning/.venv/bin/python (3.10)
Project Root:
  /home/jeertmans/Desktop/install-warning
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.12",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.2.0-39-generic",
  "platform_system": "Linux",
  "platform_version": "#40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 
UTC 2",
  "python_full_version": "3.10.12",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}

```

**Comment by frostming** [comment]
This is a frequently asked question by users: Why did it install version 1.24 when the latest version of `numpy` is 1.26.x? Previously, PDM silently fell back to the old version, but just TOO MANY users were confused about this and didn't understand how `requires-python` affects the resolution result. So I think it's necessary to tell them about this and explain how to use the new version if they want to. The warning can be silenced with `-q` config or [project configuration](https://pdm-project.org/latest/usage/config/#ignore-package-warnings).

**Comment by jeertmans** [comment]
Hello, first my apologies for the tone, I really didn’t want to sound harsh or else.

Thanks for the clarification, I understand know why the warning exists in the first place. I think I didn’t expect it because I previously used Poetry which does not seem to output such kind of warning.

If I may, I would suggest to rephrase a bit the warning like so: latest available version for package P (x.y.z) could not be installed the specified Python version requirements. Instead, the latest version of that package that supports your Python range will be installed.

**Comment by frostming** [comment]
> If I may, I would suggest to rephrase a bit the warning like so: latest available version for package P (x.y.z) could not be installed the specified Python version requirements. Instead, the latest version of that package that supports your Python range will be installed.

Can you submit a PR for this and I can review.

**Comment by jeertmans** [comment]
> > If I may, I would suggest to rephrase a bit the warning like so: latest available version for package P (x.y.z) could not be installed the specified Python version requirements. Instead, the latest version of that package that supports your Python range will be installed.
> 
> Can you submit a PR for this and I can review.

Sure, done :-)
