### ISSUE TITLE
2.11.2: pdm always prints `INFO: Inside an active virtualenv`

### ISSUE THREAD

**Issue by sigma67** [pdm-project/pdm#2529]
- [ x ] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

`pdm run <cmd>`

## Actual behavior

as of 2.11.2 now prints

```
INFO: Inside an active virtualenv /.../project-dir/.venv, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
```

## Expected behavior

no print

## Environment Information

(same issue here)

```bash

# Paste the output of `pdm info && pdm info --env` below:
INFO: Inside an active virtualenv /.../project-dir/.venv, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
PDM version:
  2.11.2
Python Interpreter:
  /.../project-dir/.venv/bin/python (3.12)
Project Root:
  /.../project-dir
Local Packages:
  
INFO: Inside an active virtualenv /.../project-dir/.venv, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
{
  "implementation_name": "cpython",
  "implementation_version": "3.12.1",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.0-91-generic",
  "platform_system": "Linux",
  "platform_version": "#101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023",
  "python_full_version": "3.12.1",
  "platform_python_implementation": "CPython",
  "python_version": "3.12",
  "sys_platform": "linux"


```

**Comment by frostming** [comment]
Please describe why you think it is unexpected. You are in an activated venv, why shoudn't it show? Check it by `echo $VIRTUAL_ENV`

**Comment by sigma67** [comment]
Unfortunately I am failing to reproduce this consistently. Will close for now.

Anecdotally, most of the time this message doesn't show for me when using `pdm run`, even if the venv is active. This is what I would consider expected behavior
