### ISSUE TITLE
[Want help]Is it possible to use pdm with readthedocs?

### ISSUE THREAD

**Issue by shenmishajing** [pdm-project/pdm#2535]
## Is your feature/enhancement proposal related to a problem? Please describe.

If I have to install the project in editable mode, when I build the docs for it. What should I do if I want to use pdm with [readthedocs](https://readthedocs.org/)? 

The [doc](https://docs.readthedocs.io/en/stable/config-file/v2.html#python-install) of readthedocs claims that they only support pip to install packages or projects in editable mode.

## Describe the solution you'd like

An example pyproject.toml for using pdm with readthedocs.

**Comment by frostming** [comment]
But you can use custom build commands: https://docs.readthedocs.io/en/stable/config-file/v2.html#build-commands

**Comment by shenmishajing** [comment]
@frostming Ok, thanks for your reply. I will try it.
