### ISSUE TITLE
Make venv.with_pip default to True

### ISSUE THREAD

**Issue by bitnom** [pdm-project/pdm#2541]
Let's make `venv.with_pip` default to `True`. It's a bit embarrassing that it's not already (anticipating that I'm about to have to explain this to a major repo I recommended pdm to). Please forgive my ignorance if I'm missing something about this option.

related to #1819

**Comment by bitnom** [comment]
The reason I came to this because the repo I'm working on has a feature which often relies on the downstream usage of `pip` in its implementation (Included in its public code examples), which is unavailable by default with the current behavior. It was unexpected, and I had to go searching. Less knowledgeable module users will be less inclined to solve the issue.

**Comment by pawamoy** [comment]
Do you mean that this project actually imports (from) pip within its own code?

**Comment by frostming** [comment]
IIUC, if your project relies on the code of pip, that means your project *depend* on `pip` and should mark it as an explicit dependency.

**Comment by paulschmeida** [comment]
> IIUC, if your project relies on the code of pip, that means your project _depends_ on `pip` and should mark it as an explicit dependency.

That's not always the case, for example I need pip in the .venv to add packages required for jupyter notebooks to work in vscode, but I don't want these packages to end up in project dependencies as the end result will be packaged and not in the notebooks.

**Comment by pawamoy** [comment]
Then you could list these extra deps in your project `optional-dependencies`, so that user can do `pip install your-project[notebooks]`.

**Comment by frostming** [comment]
`dev-dependencies` may best fit your need as it holds dependencies only used when users runs `pdm install` on your project.

Given the recent trends in Python packaging, it is reasonable to assume that pip will gradually step down as the sole **package installer for Python™️** projects.
