### ISSUE TITLE
Weird behavior with pdm run and torch distributed. Poetry works correctly by setting sys.argv[0]

### ISSUE THREAD

**Issue by vikigenius** [pdm-project/pdm#2553]
I have a torch distributed training script in an application. When using PDM run to run it:

`pdm run llmft seanmor5/tiny-llama-test`

 I got a weird error

`/home/void/Projects/Research/llmft/.venv/bin/python: can't open file '/home/void/Projects/Research/llmft/-c': [Errno 2] No such file or directory`

I tried to reproduce this in poetry, but couldn't.

Relevant snippet from PDM's pyproject.toml

```
[tool.pdm]
package-type = "application"

[tool.pdm.scripts]
llmft = {call = "llmft.cli:run"}
```

For poetry it becomes
```
[tool.poetry.scripts]
llmft = 'llmft.cli:run'
```

The other differences I can think of is that poetry actually installs the script to the environment.

Here are the commands emmited by poetry

`['python', '-c', "import sys; from importlib import import_module; sys.argv = ['/home/void/Projects/Research/llmft/.venv/bin/llmft', 'seanmor5/tiny-llama-test']; sys.exit(import_module('llmft.cli').run())"]`

Here are the commands emmited by pdm

`['python', '-c', 'import sys, llmft.cli as _1;sys.exit(_1.run())', 'seanmor5/tiny-llama-test']`

I think the main issue is that pdm does not have a proper `sys.argv[0]` set.

poetry sys.argv `'/home/void/Projects/Research/llmft/.venv/bin/llmft'`
pdm sys.argv `-c`  # This is problematic

Can we get `pdm run` to behave more like `poetry run` so that issues like this don't happen. I think the issue is torch distributed probably uses `sys.argv[0]` to initialize

**Comment by vikigenius** [comment]
Maybe pdm can also install the user script to the  bin location and then set sys.argv[0] appropriately.

**Comment by frostming** [comment]
`[tool.poetry.scripts]` is the way to expose a [console script entry point]（https://packaging.python.org/en/latest/specifications/pyproject-toml/#entry-points) for the installable package. The equivalent in PDM is the PEP standard `[project.scripts]`.

On the contrast, `[tool.pdm.scripts]` is only a table of tasks with a name for each.

**Comment by vikigenius** [comment]
@frostming `pdm install` does not seem to work or install the project itself.

I added the following to pyproject.toml after removing the `[tool.pdm.scripts]`

```
[project.scripts]
llmft = "llmft.cli:run"
```

After doing `pdm install` it doesn't say anything about installing the project. Just says all packages are synced nothing to do.

When I do `pdm run llmft` it says

`[PdmUsageError]: Command 'llmft' is not found in your PATH.`

I try to manually run `pdm run python llmft/cli.py`

```
λ pdm run python llmft/cli.py
Traceback (most recent call last):
  File "/home/void/Projects/Research/llmft/llmft/cli.py", line 3, in <module>
    from llmft.fit import fit
ModuleNotFoundError: No module named 'llmft'
```

So the project itself is not being installed?

**Comment by vikigenius** [comment]
@pawamoy 

I do have it, here is my pyproject.toml

```
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "llmft"
version = "0.1.0"
description = "LLM Finetuner"
authors = [
    {name = "Vikash Balasubramanian", email = "vikash@alexi.com"},
]
dependencies = [
    "torch>=2.1.2",
    "numpy>=1.26.3",
    "transformers>=4.36.2",
    "peft>=0.7.1",
    "datasets>=2.16.1",
    "arger>=1.4.8",
    "pytorch-lightning>=2.1.3",
]
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}

[project.scripts]
llmft = "llmft.cli:run"

[tool.pdm]
package-type = "application"

[tool.pdm.dev-dependencies]
qa = [
    "ruff>=0.1.11",
    "mypy>=1.8.0",
]
tools = [
    "python-lsp-server>=1.9.0",
    "ruff-lsp>=0.0.49",
]
```

**Comment by frostming** [comment]
the package type has to be "library" to make it installable

**Comment by vikigenius** [comment]
@frostming Ok thanks for that. Maybe it would be helpful if the document made it a bit more clear the differences between application and library.

I thought my project was an application since it had a console script entry point as a CLI application.
