### ISSUE TITLE
Pre built wheel files not used if different for multiple python versions

### ISSUE THREAD

**Issue by enCHineer** [pdm-project/pdm#2555]
## Is your feature/enhancement proposal related to a problem? Please describe.

I set up a pyproject.toml for multiple python versions. For example Python 3.8 and Python 3.9.
In addition I have `matplotlib ` as a dependency of this project. There are wheel files for either of the two python versions available, but each python version will need a different wheel file. PDM therefore does not use these wheel files during the lock process.
As a result: when installing from the lock file it will use the sources and try to build matplotlib itself. This means I can only use this lock file on systems which are set up to build all the dependency packages which have this issue.

## Describe the solution you'd like

If there are wheel files available for any python version they should be included in the `pdm.lock`. When installing the lock file the wheel file can be used on either of the two python versions.

**Comment by frostming** [comment]
I don't understand what you encounter because pdm.lock does record all wheels.

what does it contain on your side?

**Comment by enCHineer** [comment]
You got me thinking. While doing a minimal example I found that you are right in the default case.
The problem does only occur when doing `pdm lock --strategy no_cross_platform`

But what I intend to do with `no_cross_platform` is only limiting the platform and not the python version. I would expect to see all the wheel files of my current platform but with multiple python versions. But I get only a single wheel file.

Or is it intended to lock as well the python version?

**Comment by frostming** [comment]
> Or is it intended to lock as well the python version?

If you know the mechanic of the wheel selection, the platform tags are compared together.

**Comment by enCHineer** [comment]
But it looks like not only the platform tag is compared.

If I define the python version as `>=3.8.*,<3.10.*` using `--strategy cross_platform` I get all the wheel files for the selected version of matplotlib (3.7.4) in the `pdm.lock`. These include the following for Windows (and many more for the other platforms):
- matplotlib-3.7.4-cp39-cp39-win_amd64.whl
- matplotlib-3.7.4-cp38-cp38-win_amd64.whl

If I change over to `pdm lock --strategy no_cross_platform` only one wheel file will be included in `pdm.lock`:
- matplotlib-3.7.4-cp39-cp39-win_amd64.whl

This means not only the platform tag of the wheel file is compared but as well the python-tag. This is not what I would expect. I would still expect to see all wheel files for the available python versions but only one platform.

**Comment by frostming** [comment]
Platform tags means python+abi+platform

**Comment by enCHineer** [comment]
When looking at PEP427 this does not sound right. The python-tag is something different and is not part of the platform-tag. All the three last ones together are called "compatibility tags" (PEP425).

But okay. So my enhancement proposal would be to get a possibility to lock to a specific platform (platform-part of the platform-tag?) with multiple python versions. As this is currently not possible.

**Comment by frostming** [comment]
> . So my enhancement proposal would be to get a possibility to lock to a specific platform (platform-part of the platform-tag?) with multiple python versions.

The cross-platform strategy does more than that. Under non-cross-platform tag, the environment markers will be evaluated at lock time to discard unmatching requirements. So it is not easy to strip the python tag out of it.
