### ISSUE TITLE
Make pdm-project a GitHub "Verified Creator"

### ISSUE THREAD

**Issue by ModeSevenIndustrialSolutions** [pdm-project/pdm#2557]
## Proposal

Make pdm-project a [Verified Creator on Github](https://docs.github.com/en/apps/github-marketplace/github-marketplace-overview/about-marketplace-badges)

This was originally requested here:

https://github.com/pdm-project/update-deps-action/issues/3

...and as mentioned there, some organisational policies can restrict Github Actions usage based on this status. Given that duplication of repos (primarily through forking) is an extremely common occurrence with GIT/GitHub, any additional steps that verify/certify origin are of potential value.

## Solution

I would be happy to contribute time/effort to get the PDM project added as a Github verified creator, although right now I have no particular affiliation with the PDM project/organisation.

GitHub Docs
[Applying for publisher verification for your organization](https://docs.github.com/en/apps/github-marketplace/github-marketplace-overview/applying-for-publisher-verification-for-your-organization)

This looks to be really straightforward; you need to generate a TXT token in the GitHub portal and add that to your project's DNS records. Once the DNS record is added, it is just a few more clicks in the GitHub portal, really only ten minutes work in total. This does require a user account with access to the GitHub ORG (which I don't have for PDM), and the ability to add a DNS record to the project domain: pdm-project.org

It would seem to be a good idea to get this small piece of admin done? It links the PDM project site in a verified way to the related content on GitHub. I think this helps users confirm that they are dealing with the project and original content, not forks and other potential sources of confusion?

**Comment by frostming** [comment]
Replied in the original issue.
