### ISSUE TITLE
"Couldn't find version in file" error when version is assigned in a way that doesn't match the expected regex

### ISSUE THREAD

**Issue by DetachHead** [pdm-project/pdm#2562]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

https://github.com/pdm-project/pdm-backend/blob/ad7de0985c209136d70d19d76e1325dbcc502eb8/src/pdm/backend/hooks/version/__init__.py#L79

## Steps to reproduce

for example if the `__version__` variable has a type annotation:
```py
# __version__.py

__version__: str = "1.0.0"
```

## Actual behavior

```
pdm.backend.exceptions.ConfigError: Couldn't find version in file WindowsPath('C:/Users/user/project/__version__.py'), it should appear as `__version__ = 'a.b.c'`.
```

## Expected behavior

no error. it should probably evaluate the version by importing the module and checking the variable that way instead.

**Comment by frostming** [comment]
Just stick to the current rules. You don't need a str hint for a static literal value

Executing the file isn't a good idea.
