### ISSUE TITLE
Unexpected installation location as described in the document

### ISSUE THREAD

**Issue by Wsine** [pdm-project/pdm#2565]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

`curl -sSL https://pdm-project.org/install-pdm.py | python3 -`

## Actual behavior

```
Successfully installed: PDM (2.12.1) at /Users/xxx/Library/Python/3.9/bin/pdm
Post-install: Please add /Users/xxx/Library/Python/3.9/bin to PATH by executing:
    export PATH=/Users/xxx/Library/Python/3.9/bin:$PATH
```

## Expected behavior

The pdm executable file should be installed in `$HOME/.local/bin` for Unix as described in the document.

https://pdm-project.org/latest/#:~:text=%24HOME/.local/bin%20for%20Unix 

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

```

Not related.

![image](https://github.com/pdm-project/pdm/assets/8842278/aa2e6d58-0836-4f07-a635-c79ce580de43)

**Comment by frostming** [comment]
The documentation is not correct.

We install the bin under `site.getuserbase()`
