### ISSUE TITLE
Ability to take into account a limit date to compute a lockfile

### ISSUE THREAD

**Issue by paugier** [pdm-project/pdm#2567]
Unlike Poetry and Pixi, PDM does not by default include a range of versions. I'm very happy with this behavior because I think it makes sense for Python packaging (see https://iscinumpy.dev/post/bound-version-constraints/).

 It seems to me that with upper bounds of dependencies, we have one syntax to say two very different things:

- "I'm sure that it works with this range and a version higher than X might leads to issues."
- "I know that this code needs a version smaller than X"

I'd like to keep upper bounds only for the second case.

However, I also know that after some times, there is a high probability that the result of a new `pixi lock` will produce a lockfile leading to failures (because new incompatible packages were uploaded to PyPI).

I remembered that I was able to recreate successful environments with https://pypi.org/project/pypi-timemachine/, which allows one to "install packages with pip as if you were at some fixed date in the past".

So I was thinking that it would be nice to be able to reproduce in few years a "successful lockfile" only from dependency data and a date.

To conclude, I was wondering if something like `pdm lock --discard-versions-newer-than 2024-01-01` could be useful and supported.

**Comment by pawamoy** [comment]
Big +1 :+1: 

When solving deps for old package versions, limiting selection to dependency version that existed **up to a certain date** helps tremendously, because we're pretty sure that at this time, dependencies could be solved.

Such a strategy would help a lot with reproducing old builds, which in turn could help adoption of less upper bounds in the ecosystem (the "version higher than X might leads to issues" ones).

**Comment by paugier** [comment]
> It should work with PDM as well, which you should consider first.

This is a quite inconvenient solution and pypi-timemachine writes in its README: "Disclaimer: this is alpha-quality software". 

I'm asking about this feature to get something easier to use and builtin.

> or just let it be overwritten?

For my personal usage, it would already be good to be able to run:

```
pdm lock --discard-versions-newer-than 2024-01-01
pdm sync --clean
```

to easily produce a working environment to use an old version of an application.

It would not be a problem if other calls of `pdm lock` or `pdm update` would break this.

**Comment by frostming** [comment]
Hi, @paugier `--exclude-newer` option was landed in main branch, feel free to try and give feedback!

**Comment by frostming** [comment]
Also `Manage Dependencies` page is getting large, it seems need to be rewritten and split into several pages. Anyone willing to help?
