### ISSUE TITLE
Fails to install nested package (for example `paho-mqtt`)

### ISSUE THREAD

**Issue by dostuffthatmatters** [pdm-project/pdm#2570]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Run the following commands inside a venv:

1. `pdm init`
2. `pdm add paho-mqtt`

## Actual behavior

The directory `.venv/lib/python3.X/site-packages/paho` which contains the source code of the `paho-mqtt` library (https://github.com/eclipse/paho.mqtt.python, https://pypi.org/project/paho-mqtt/) is not present. With PIP and Poetry, this works. But PDM fails to install this directory. I only have `.venv/lib/python3.X/site-packages/paho_mqtt-1.6.1.dist-info` but now the actual source code.

## Expected behavior

PDM should be able to install this. I don't know why it can't. A quick fix is to simply use `pip install .` or `pip install ".[dev]"`.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.12.1
Python Interpreter:
  /Users/moritz/Documents/work/esm/ivy-seed/.venv/bin/python (3.10)
Project Root:
  /Users/moritz/Documents/work/esm/ivy-seed
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.13",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "23.2.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000",
  "python_full_version": "3.10.13",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
Can't reproduce
