### ISSUE TITLE
Relative paths to local packages without PDM build-backend?

### ISSUE THREAD

**Issue by paugier** [pdm-project/pdm#2592]
For some packages, it does not make sense to use the PDM build-backend (for example those for which Meson is particularly useful) and it is useful to use relative paths to local packages in a dependency group.

Currently writing something like:

```
[tool.pdm.dev-dependencies]

plugins = [
    "-e fluidfft-mpi4pyfft @ file:///${PROJECT_ROOT}/plugins/fluidfft-mpi4pyfft",
]
```

does not work if we don't use `build-backend = "pdm.backend"`.

It would be great to be able to add local package with relative path even without `build-backend = "pdm.backend"`.

**Comment by frostming** [comment]
The `file:///${PROJECT_ROOT}` syntax is backend-specific.

You can however do this by `pdm add -dG plugins -e ./plugins/fluidifft-mpi4pyfft` and let PDM write that for you.
