### ISSUE TITLE
Same package as default and editable dev dependency race condition

### ISSUE THREAD

**Issue by ossimoi** [pdm-project/pdm#2593]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Trying to add a package to both prod and dev dependencies as follows:

```
dependencies = [
    "mypckage"
]

[tool.pdm.dev-dependencies]
local_libs = [
    "-e file:///${PROJECT_ROOT}/../mypackage/
]
```
## Actual behavior
Running `pdm update` fails with 50% probability on first run without pdm.lock, second run always works. Running with -v works 100% of the time.

`[CandidateNotFound]: Unable to find candidates for mypackage. There may exist some issues with
the package name or network condition.`

## Expected behavior
`pdm update` should find mypackage and install it as editable dependency.

This might be completely wrong way to accomplish what I'm trying to. When developing locally, I need mypackage as editable dependency. However, in CI, the package is available as pre-built wheel from static path. I've tried to add pdm.source which points to this path, but running `pdm sync --prod --no-editable`  reads the lockfile and tries to install mypackage from relative development path.

I'm not certain this is the correct way to do this. Please let me know if there's a better one. This is a separate problem, I'll open another issue if needed.

## Environment Information

```bash
PDM version:
  2.12.2
Python Interpreter:
  /home/user/project/.venv/bin/python (3.11)
Project Root:
  /home/user/project
Local Packages:


{
  "implementation_name": "cpython",
  "implementation_version": "3.11.7",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.7.1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Thu Jan 25 12:30:48 EET 2024",
  "python_full_version": "3.11.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
When locking the first time, it will always try to find `mypackage` from the sources since it doesn't know the `local_libs` is a **local** version of that package, because you didn't give the package name, you can do this by:

```
 -e file:///${PROJECT_ROOT}/../mypackage/#egg=mypackage
```
