### ISSUE TITLE
`PDM_NO_EDITABLE` just like `PDM_NO_SELF`?

### ISSUE THREAD

**Issue by huxuan** [pdm-project/pdm#2602]
## Is your feature/enhancement proposal related to a problem? Please describe.

When building documentation within a release CI/CD where version is extracted from the installed package, we need to leverage the `--no-editable` option. Better to have an env `PDM_NO_EDITABLE` to control the behavior, so that we can easily reuse the build scripts without affecting other scenarios, for example, when developing/working on the documentation on local. 

## Describe the solution you'd like

Support `PDM_NO_EDITABLE` just like what `PDM_NO_SELF` do.

BTW, if possible, I can try to submit a pull request.

**Comment by frostming** [comment]
Contribution welcome
