### ISSUE TITLE
`pdm install` does not update dependencies in monorepo

### ISSUE THREAD

**Issue by Valahaar** [pdm-project/pdm#2606]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

Installing newly-added dependencies with `pdm install` in a monorepo after it has been executed once already does not work. The quick fix is to delete the `pdm.lock` file, which forces PDM to re-install everything, but that is sub-optimal.

I'm pretty new to PDM, sorry if I missed something!

## Steps to reproduce

Clone [the example monorepo](https://github.com/pdm-project/pdm-example-monorepo), run `pdm install` once, add a dependency (e.g., `requests`) to any package under `packages/`, run `pdm install` again.

## Actual behavior
`requests` does not get installed.

## Expected behavior
I think it should update sub-packages dependencies as well.

## Environment Information

```bash
PDM version:
  2.12.3
Python Interpreter:
  /path/to/pdm-example-monorepo/.venv/bin/python (3.10)
Project Root:
  /path/to/pdm-example-monorepo
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.10",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.0-91-generic",
  "platform_system": "Linux",
  "platform_version": "#101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023",
  "python_full_version": "3.10.10",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
> run `pdm install` again.

`pdm installl` doesn't detect changes in sub packages, but rather run `pdm update` instead.
