### ISSUE TITLE
Add script hooks to `sync` and `update` command

### ISSUE THREAD

**Issue by jvllmr** [pdm-project/pdm#2607]
## Is your feature/enhancement proposal related to a problem? Please describe.
I have a project with a FastAPI backend and a React frontend in a monorepo.
When I run `pdm update` or `pdm sync` I want to take actions with `pnpm` as well.
That is currently not possible. 

## Describe the solution you'd like
Add hooks for `sync` and `update` and add them to documentation here: https://pdm-project.org/latest/usage/scripts/#hook-scripts

**Comment by frostming** [comment]
The hooks are not for per command but rather per action.

The sync and update command also do `install` behind the scene, so the `install` hook should work, too.
