### ISSUE TITLE
`pdm import` (or implicit import) of a project with setuptools_scm does not set dynamic version

### ISSUE THREAD

**Issue by intelfx** [pdm-project/pdm#2609]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. Check out any project that does not use PEP 621-compliant metadata and uses dynamic version with setuptools_scm, for example, [liquidctl/liquidctl](https://github.com/liquidctl/liquidctl/)
2. Work around #2608 somehow (e. g. run `pdm install`, wait for it to fail, then run `pdm install` again)
3. Attempt to run `pdm install`

## Actual behavior

pdm fails to install the project, citing absence of the `version` property in the project configuration:

```
  ✖ Install liquidctl None failed

See /tmp/pdm-install-8l7bqn_w.log for detailed debug log.
[BuildError]: Build backend raised error: Showing the last 10 lines of the build output:
    pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
  File "/tmp/pdm-build-env-l_xkkywg-shared/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 66, in apply_configuration
    config = read_configuration(filepath, True, ignore_option_errors, dist)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pdm-build-env-l_xkkywg-shared/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 127, in read_configuration
    validate(subset, filepath)
  File "/tmp/pdm-build-env-l_xkkywg-shared/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 55, in validate
    raise ValueError(f"{error}\n{summary}") from None
ValueError: invalid pyproject.toml config: `project`.
configuration error: `project` must contain ['version'] properties
```

[Full `pdm install -vv` log](https://github.com/pdm-project/pdm/files/14149371/pdm-install.log)

## Expected behavior

pdm infers the presence of dynamic version, configures the newly-written PEP 621 metadata accordingly, and successfully imports the project.

## Environment Information

```bash
$ pdm info && pdm info --env
PDM version:
  2.12.3+editable
Python Interpreter:
  /home/intelfx/devel/ext/liquidctl/.venv/bin/python (3.11)
Project Root:
  /home/intelfx/devel/ext/liquidctl
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.11.6",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.7.3-arch1pf5-2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Thu, 01 Jan 1970 00:00:00 +0000",
  "python_full_version": "3.11.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
No we can't, `pdm import` isn't a full-featured converter to cover all build backends.

**Comment by intelfx** [comment]
@frostming Sure, but some cases can be handled with relatively simple heuristics.
