### ISSUE TITLE
Allow dynamic loading of env vars from script

### ISSUE THREAD

**Issue by Valahaar** [pdm-project/pdm#2619]
## Is your feature/enhancement proposal related to a problem? Please describe.

I think it would be useful, in some cases, if it were possible to dynamically load environment variables for PDM scripts by using another (PDM) script.
I would like (at least one of) two different scenarios to be implemented:

### Scenario 1
I have a series of env vars that need to be injected into a script, but these are dynamically computed by another script.

```
[tool.pdm.scripts]
envvars = "my-script" # this scripts runs and returns an env-like file ("ENV1=a\nENV2=b\n" and so on)
_.env_cmd = "{pdm} run envvars"  # accept anything that normal scripts accept (shell, cmd, etc)
```

Here, I think maybe `env_cmd` could run `my-script` and populate the env vars of all other scripts with those it returned.

### Scenario 2
I have one (or more) env vars that are dynamically computed.

```
[tool.pdm.scripts]
_.env = { ENV1 = { cmd = "{pdm} run get-env-1"}, ENV2 = { shell = "echo 'env2'" } }
# or, more generally,
_.env.ENV1 = { cmd = "..." }
_.env.ENV2 = { shell = "..." }
```

What do you think? Is it already possible without running a `shell` command that wraps this kind of behavior?

Thanks!

**Comment by frostming** [comment]
It is over-complicated and beyond the scope of PDM. Users can achieve this by a shell script.
