### ISSUE TITLE
Add an option for PDM's scripts to set the current working directory

### ISSUE THREAD

**Issue by madebylydia** [pdm-project/pdm#2620]
## Is your feature/enhancement proposal related to a problem? Please describe.

This issue suggest adding a new key for commands defined under `tool.pdm.scripts`, to set the current working directory before running the given action.

Consider the following project structure:

```
my_project/
├─ docs/
│  ├─ source/
│  ├─ Makefile
│  ├─ make.bat
├─ src/
│  ├─ my_package/
├─ pyproject.toml
```
This is a recurring structure given Sphinx's proposed setup.
There are commands that can only be ran in the `docs/` directory, due to the nature of `make` that uses the `Makefile` available at the root of the current working directory.

## Describe the solution you'd like

This key, which could be called `cwd`, or `in_path`, or any given suggestion, would provide an OS-agnostic way to set the current working directory.

When a command will be running, and this property is set with a relative path (In this example `./docs`), PDM should come back to the root of the project (`pdm info --where`), so that moving in directories is seamless, and would not surprise us in case our current working directory was in `src/my_package`, for example.

Alternatively, this could be done by using operators like `&&` in a shell script, but such operator (In my knowledge) could be different depending on the OS used.

Adding such key would, in my opinion, increase confidence when creating new scripts that require to move to specific directories.

- - -

I am willing to work on this issue and submit a PR.

**Comment by frostming** [comment]
You can change the root of `make` command by `-C <path>` right?

**Comment by madebylydia** [comment]
This is only an example. There are other use cases that could require changing the current working directory.

**Comment by frostming** [comment]
> This is only an example. There are other use cases that could require changing the current working directory.

I was not saying that is not necessary, just in case you would think it blocks your workflow.
