### ISSUE TITLE
Central installation cache packages duplicated in local Windows project

### ISSUE THREAD

**Issue by eckelsjd** [pdm-project/pdm#2625]
- [✅] I have searched the issue tracker and believe that this is not a duplicate.

I have a local pdm project named `amisc` on Windows.

## Steps to reproduce
```shell
cd amisc
pdm config install.cache on --local
pdm venv remove -y in-project
pdm sync
```

## Actual behavior
The new `.venv` folder is created and it contains duplicates of all the "cached" packages found in `$(pdm config cache_dir)`. The packages do appear to download correctly to the cache dir as shown here:
![image](https://github.com/pdm-project/pdm/assets/33996464/a575602c-c9bd-4dfd-b37c-457888e2e8cd)

but they also get downloaded to `.venv` as shown here:
![image](https://github.com/pdm-project/pdm/assets/33996464/695542b1-5fc4-4303-89cf-b75499845749)

## Expected behavior
The cached packages should only download to the cache dir, and symlinks should be made inside the `.venv` folder. This would save GBs on my system since I have several projects which require the same set of packages.

## Environment Information

```bash
PDM version:
  2.12.3
Python Interpreter:
  C:\Users\eckel\Documents\GitHub\amisc\.venv\Scripts\python.exe (3.11)
Project Root:
  C:/Users/eckel/Documents/GitHub/amisc
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.11.7",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.22621",
  "python_full_version": "3.11.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "win32"
}
```

**Comment by frostming** [comment]
symlink may not be supported on your system. In that case hardline will be used

**Comment by eckelsjd** [comment]
I checked and they are in fact hardlinks. But Windows does support symlinking, the question is why did it default to hardlinks instead? I have `pdm config install.cache_method` set to `symlink`.

**Comment by frostming** [comment]
> the question is why did it default to hardlinks instead?

Yes, it fallbacks silently so users won't be bothered.
