### ISSUE TITLE
Redundant download optimization

### ISSUE THREAD

**Issue by somata-cn** [pdm-project/pdm#2630]
## Is your feature/enhancement proposal related to a problem? Please describe.
I just want to use PDM as a package management tool, not a package building tool, but PDM downloads a lot of whl packages that I don't need.
我只是想要将PDM作为包管理工具，不是包构建工具，但PDM会下载许多我并不需要的whl包。

For example, I only want to install `torch-2.2.0+cu118-cp311-cp311-win_amd64.whl`, but PDM downloads all of the following files (12GB of downloads in total, and only 2.5GB used):
例如，我只想安装`torch-2.2.0+cu118-cp311-cp311-win_amd64.whl`, 但PDM会下载以下所有文件（共计下载12GB，仅使用到了2.5GB）：
- torch-2.2.0+cu118-cp310-cp310-linux_x86_64.whl 
- torch-2.2.0+cu118-cp310-cp310-win_amd64.whl 
... 13 whl packages are omitted here ...
- torch-2.2.0-cp312-cp312-manylinux1_x86_64.whl 
- torch-2.2.0-cp312-cp312-manylinux2014_aarch64.whl 
- torch-2.2.0-cp312-cp312-win_amd64.whl 
- torch-2.2.0-cp312-none-macosx_10_9_x86_64.whl 
- torch-2.2.0-cp312-none-macosx_11_0_arm64.whl 

This made me wait a very, very long time while installing torch!
这让我在安装torch的时候等待了非常非常长的时间！！！

## Describe the solution you'd like
When using PDM only as a package management tool, I hope PDM to reduce the number of non-essential downloads and download only essential packages.
在只作为包管理工具的时候,我希望PDM能减少非必要下载，只下载必要软件包。

**Comment by frostming** [comment]
PDM needs to get the file hashes for all installable candidates. In a private index like pytorch, the only way is to download that file and calculate the hash locally.

**Comment by somata-cn** [comment]
> PDM needs to get the file hashes for all installable candidates. In a private index like pytorch, the only way is to download that file and calculate the hash locally.

Is there any way to disable this behaviour in PDM?
