### ISSUE TITLE
Config-settings option for `pdm install` command

### ISSUE THREAD

**Issue by amolenaar** [pdm-project/pdm#2636]
## Is your feature/enhancement proposal related to a problem? Please describe.

`pdm build` takes optional config settings, which are passed to the backend.

`pdm install` does not have such a feature, although it would be useful to add options to (for example) meson-python, to create debug builds.

## Describe the solution you'd like

It would be nice to have a `--config-settings` option for `pdm install`. 

I'm not sure if this option should apply only to the project or to all installed dependencies.

**Comment by elramen** [comment]
I would like to give this a go! Could you assign me to this issue? :)

**Comment by elramen** [comment]
Hi @amolenaar! Could you provide an example of a package and relevant config setting, and what the expected result should be when running it with ```pdm install```?

**Comment by frostming** [comment]
@elramen If you are interested in this feature, I need to remind you that we perform the `build` operation in several places(see `PreparedCandidate.build()`), for different packages. And for now I think it is okay to make a "global" config setting to be shared by all packages to be built. The main problem to be solved in the implementation is how to share that global config elegantly.
