### ISSUE TITLE
Default values for CLI arguments not aligned with documentation

### ISSUE THREAD

**Issue by Pepeze** [pdm-project/pdm#2642]
- [✅] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

When running certain CLI commands, such as `add`, `sync`, or `install`, the default values for the arguments seem to differ from what is written in the documentation.

Thanks for your help and for maintaining such a great package! :)

## Actual behavior

`pdm add`: By default writes pyproject.toml and syncs the working set.
`pdm sync`: By default selects dev dependencies.
`pdm install`: By default selects dev dependencies.

## Expected behavior

`pdm add`: Only writes pyproject.toml and do not sync the working set, as the default of `--no-sync` is `True` in the documentation.
`pdm sync`: Unselects dev dependencies, as the default of --production is `True` in the documentation.
`pdm install`: Unselects dev dependencies, as the default of --production is `True` in the documentation.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

PDM version:
  2.12.3
Python Interpreter:
  /home/my_user/project_name/.venv/bin/python (3.11)
Project Root:
  /home/my_user/project_name
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.11.4",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.133.1-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Thu Oct 5 21:02:42 UTC 2023",
  "python_full_version": "3.11.4",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}

```

**Comment by erklem** [comment]
I have been confused by this as well. It seemed that `pdm sync` would only install required dependencies, based on the documentation. The current behavior installs development dependencies, too - only entering the `--production` flag cleans it up.
