### ISSUE TITLE
Add `requires-pdm` option in pyproject.toml like `requires-python`

### ISSUE THREAD

**Issue by nkhitrov** [pdm-project/pdm#2653]
I usually use the latest version of `pdm`, but some people in my team use older versions. For this reason `pdm` produce warnings like this

```bash
>> python -m pdm sync
Lock file version is not compatible with PDM, installation may fail
...
```

and usage of `pdm lock/install/update/etc` may change lock file format without adding new dependencies

So, I want to pin `pdm` version for project. What do you think about it?

**Comment by frostming** [comment]
This is a responsibility for a higher level tool to manage PDM like `corepack` in the nodejs.

I have an experimental project named [onepm], would you like to have a try?

[onepm]: https://github.com/onepm

**Comment by nkhitrov** [comment]
Looks interesting, thank you! 

If I understand correctly, `onepm` installs via `pip`. But `pdm` can be installed through another manager, for example `brew`. In that case, the check will work?

I like that you can set the version in the `toml` file, but I don't want to install another tool for that. Still, I would like `pdm` to be able to do it itself. It doesn't look too complicated.

Let me clarify, my pain is not about installing or choosing a package manager, so another abstraction in the form of a package manager is redundant in my opinion. The pain is that the developer changes the lock file to an older format when using an older version of `pdm`.  If this can be solved with a strict flag, that would work fine for me. But pin version of `pdm` itself seems to me a more useful feature, which at the same time will exclude problems with updates like `poetry` did

**Comment by frostming** [comment]
> If I understand correctly, `onepm` installs via `pip`. But `pdm` can be installed through another manager, for example `brew`. In that case, the check will work?

Neither can PDM handle that, we need another manager to manage PDM versions right?

**Comment by frostming** [comment]
If you just want to fail when the version doesn't match, we already have a lock version mechanism to do that.

**Comment by nkhitrov** [comment]
> Neither can PDM handle that

Why? We have `pdm info` that can print pdm version, we have config/toml that can be parsed by pdm. So, we have all necessary information. Why we can't check pinned version without, for example, `onepm`? 

> If you just want to fail when the version doesn't match, we already have a lock version mechanism to do that.

I didn't see any information about this in documentation. Can you tell me where I can read about it?

**Comment by frostming** [comment]
> Why? We have `pdm info` that can print pdm version, we have config/toml that can be parsed by pdm. So, we have all necessary information. Why we can't check pinned version without, for example, `onepm`?

I mean not able to manage versions, not only to check versions



> I didn't see any information about this in documentation. Can you tell me where I can read about it?

We have a command `pdm lock --check` to do this

**Comment by pawamoy** [comment]
What happens when the lock file was generated by latest PDM, and someone runs `pdm lock --check` with an older PDM version?

**Comment by pawamoy** [comment]
IIUC @nkhitrov wants to prevent users of older PDM versions to be able to modify the lock file. They want to set a minimum PDM version required to be able to modify the lock file.

**Comment by nkhitrov** [comment]
> We have a command pdm lock --check to do this

Hmm. Looks like a solution.

```bash
>> pdm lock --check
Lock file version is not compatible with PDM, installation may fail
>> echo $?
1
```

Somebody can forget to use this check before updating lock file. But I can add this to CI to solve this problem. Thank you, @frostming !

> IIUC @nkhitrov wants to prevent users of older PDM versions to be able to modify the lock file. They want to set a minimum PDM version required to be able to modify the lock file, or maybe more generally, just prevent updating the lock file from an older PDM version that the one it was generated with.

Yes. I would like to set up a stricter configuration (in project file like toml) so that the developer doesn't need to check the format with an additional command. So that when lock is called without arguments an error will be thrown:

```bash
>> pdm lock
Lock file version is not compatible with PDM, installation may fail
>> echo $?
1
```

**Comment by frostming** [comment]
> Somebody can forget to use this check before updating lock file. But I can add this to CI to solve this problem. Thank you, @frostming !

We have an pre-commit hook for this: https://pdm-project.org/latest/usage/advanced/#check-pdmlock-is-up-to-date-with-pyprojecttoml

**Comment by deronnax** [comment]
@nkhitrov do you know about [asdf](https://github.com/asdf-vm/asdf?tab=readme-ov-file)? It's an universal cli tool package manager, and it handles PDM.

**Comment by nkhitrov** [comment]
> @nkhitrov do you know about [asdf](https://github.com/asdf-vm/asdf?tab=readme-ov-file)? It's an universal cli tool package manager, and it handles PDM.

@deronnax Yes, I use asdf to manage elixir/erlang versions. But it is not a solution of my problem

https://github.com/pdm-project/pdm/issues/2653#issuecomment-1966134657
