### ISSUE TITLE
bug fix report, binaries of wrong "32/64" bitnes in __pypackages__

### ISSUE THREAD

**Issue by franzhaas** [pdm-project/pdm#2654]
Dear all,

when i was using pdm 2.10.2 I encountered the issue that i ended up being unable to pdm build my cffi based binary packages, due to binaries of the wrong 32/64 bitness ending up being used by pdm in the __pypackages__ directory.

I updated to pdm 2.12.4 (including the dependancies), and the issue is gone.

I did not find a mention of this fix in the changelogs, maybe i looked at the wrong place, maybe I overlooked it.

@frostming any tips`?

Best regards,
Franz

**Comment by frostming** [comment]
maybe related #2467

**Comment by franzhaas** [comment]
Hi, thanks for the pointer, I know found it in the changelog unfortunately it just sliped through my search patterns... awesome!
