### ISSUE TITLE
How to add dependency with paddlepaddle or paddlepaddle-gpu

### ISSUE THREAD

**Issue by fancyerii** [pdm-project/pdm#2658]
I have a project need paddlepaddle==2.4.2 or paddlepaddle-gpu==2.4.2. In [this document](https://www.paddlepaddle.org.cn/install/old?docurl=/documentation/docs/zh/install/pip/linux-pip.html). If using pip, I should install different packages depending on the CPU or GPU and the version of CUDA.

```shell
# CPU only
python -m pip install paddlepaddle==2.4.2 -i https://pypi.tuna.tsinghua.edu.cn/simple

...

# CUDA 11.6
python -m pip install paddlepaddle-gpu==2.4.2.post116 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html

# CUDA 11.7
python -m pip install paddlepaddle-gpu==2.4.2.post117 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html
```

I am using cuda 11.7, So I use pdm add paddlepaddle-gpu==2.4.2.post117. Because it use find_links, I also add to pyproject.toml the following lines:

```
[[tool.pdm.source]]
type = "find_links"
url = "https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html"
name = "paddlepaddle"
```

I want to publish my project to pypi so others can install it by pip. So I use pdm publish to publish it to pypi.

But when I installed it:

```
pip install paddlespeechserver
```

it can't install from https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html:

```
Collecting paddlespeechserver
  Downloading paddlespeechserver-0.1.0-py3-none-any.whl (1.4 kB)
ERROR: Could not find a version that satisfies the requirement paddlepaddle-gpu==2.4.2.post117 (from paddlespeechserver) (from versions: 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0rc0, 2.2.0, 2.2.1, 2.2.2, 2.3.0rc0, 2.3.0, 2.3.1, 2.3.2, 2.4.0rc0, 2.4.0, 2.4.1, 2.4.2, 2.5.0rc0, 2.5.0rc1, 2.5.0, 2.5.1, 2.5.2, 2.6.0)
ERROR: No matching distribution found for paddlepaddle-gpu==2.4.2.post117
```

How can I publish my package that tell pip to install dependency(paddlepaddle-gpu) from https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html

Another question: some users may not have gpu or installed different cuda version(not CUDA 11.7). How can I tell the pip install paddlepaddle by the machine configuration?

**Comment by fancyerii** [comment]
I found a related discuss in [pytorch forum](https://discuss.python.org/t/idea-selector-packages/4463/31). But there is no solution.

**Comment by frostming** [comment]
The index config isn't part of the distribution metadata published to the PyPI.

So the projects depending on your package still need to specify the paddle index in their own config.

**Comment by fancyerii** [comment]
> The index config isn't part of the distribution metadata published to the PyPI.
> 
> So the projects depending on your package still need to specify the paddle index in their own config.

That's not very convenient for my users. Any other workaround for this other than pip install -f .... ?

**Comment by frostming** [comment]
> That's not very convenient for my users.

That is, but there isn't other way. This requires a PEP.
