### ISSUE TITLE
`--project` doesn't respect `PDM_PROJECT`

### ISSUE THREAD

**Issue by goyalyashpal** [pdm-project/pdm#2663]
- [x] I have searched the issue tracker and believe that this is not a duplicate.
[gh issue search](https://github.com/pdm-project/pdm/issues?q=is%3Aissue+is%3Aopen+PDM_PROJECT+in+activate)

**Make sure you run commands with `-v` flag before pasting the output.**

## Summary & Titles

`--project` doesn't respect `PDM_PROJECT` which should be auto-set by `activate`

1. the commands like `pdm info`, `pdm list`, and `pdm run` etc don't seem to be respecting the `PDM_PROJECT` env var.
2. shouldn't this env var be set automatically by the activation script (shown by `pdm venv activate`)

## Steps to reproduce & Actual behaviour

In some other directory (say, the parent dir), run any of `pdm`'s project related command: `info`, `list`, `run` etc.
I have done both: activated the venv, and defined the PDM_PROJECT env var, but still these don't run

<details><summary><h3>failed output of command runs</h3></summary>

<br/>

```console
$ cd ur_prjct; $PDM_PROJECT=ur_prjct
$ source .venv/Scripts/activate
(ur_prjct-3.12) $ echo $PDM_PROJECT
ur_prjct
(ur_prjct-3.12) $ cd ..
(ur_prjct-3.12) $ pdm info -v
[ProjectError]: The pyproject.toml has not been initialized yet. You can do this by running `pdm init`.
(ur_prjct-3.12) $ pdm list -v
[ProjectError]: The pyproject.toml has not been initialized yet. You can do this by running `pdm init`.
(ur_prjct-3.12) $ pdm run -v pytest -V
[ProjectError]: The pyproject.toml has not been initialized yet. You can do this by running `pdm init`.
```
</details> 

```console
$ deactivate

$ # it runs fine on using with `-p`
$ pdm run -vp basic_test/ pytest -V
pytest 8.0.2

```

## Expected behavior

Similar as to how it performs when `$PWD` equals project root directory or when `-p ...` is supplied to `pdm`

```console
$ cd ur_prjct
.../ur_prjct

$ pdm info -v
PDM version:
  2.12.4
Python Interpreter: ...
Project Root: ...
Local Packages: ...

$ pdm list -v
╭──────────────┬────────────────┬───────────────────╮
│ name         │ version        │ location          │
├──────────────┼────────────────┼───────────────────┤
... List of packages installed in the current working set ...

$ pdm run -v pytest -V
pytest 8.0.2

```

## Environment Information

This too requires to be in project root dir:

```console
$ # Paste the output of `pdm info && pdm info --env` below:
$ pdm info && pdm info --env
PDM version:
  2.12.4
Python Interpreter:
  ...\ur_prjct\.venv\Scripts\python.exe (3.12)
Project Root:
  .../ur_prjct
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.12.2",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19045",
  "python_full_version": "3.12.2",
  "platform_python_implementation": "CPython",
  "python_version": "3.12",
  "sys_platform": "win32"
}

$ pdm info --env | nu --stdin -c 'from json'
╭────────────────────────────────┬────────────╮
│ implementation_name            │ cpython    │
│ implementation_version         │ 3.12.2     │
│ os_name                        │ nt         │
│ platform_machine               │ AMD64      │
│ platform_release               │ 10         │
│ platform_system                │ Windows    │
│ platform_version               │ 10.0.19045 │
│ python_full_version            │ 3.12.2     │
│ platform_python_implementation │ CPython    │
│ python_version                 │ 3.12       │
│ sys_platform                   │ win32      │
╰────────────────────────────────┴────────────╯

```

**Comment by goyalyashpal** [comment]
hi @frostming ! thanks. 

and any thoughts about this?

> 2\. shouldn't this env var be set automatically by the activation script (shown by `pdm venv activate`)

**Comment by frostming** [comment]
> 2. shouldn't this env var be set automatically by the activation script (shown by `pdm venv activate`

No, `pdm venv activate` doesn't leave the current shell, setting `PDM_PROJECT` would make it impossible to work with other projects anymore.

**Comment by goyalyashpal** [comment]
> Please not limit your sight in the current need

hehe. i don't have much experience with `export` and `source` etc, so, i don't know the other effects of it. thanks for sharing 😄
