### ISSUE TITLE
Resolving dependencies does not work as expected

### ISSUE THREAD

**Issue by matthiasgomolka** [pdm-project/pdm#2669]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

I'm working on a project with `requires-python = ">=3.9.11"` configured in the `pyproject.toml` and I'm using Python 3.11.7. 

Now I want to install a package (via `pdm add`) which was written by a colleage of mine and `requires-python = ">=3.6.14"` in it's `pyproject.toml` (don't ask, we already hate to support Python 3.6).

## Actual behavior

When `pdm add`ing the package (pyidatools), I get the following warning which seems wrong:

```python
C:\Workspace\Python_Runtime\Python\Lib\site-packages\resolvelib\structs.py:127: PackageWarning: Skipping pyidatools@4.0.0 because it requires Python<3.12,>=3.6.14 but the project claims to work with Python>=3.9.11. Instead, another version of pyidatools that supports Python>=3.9.11 will be used.
If you want to install pyidatools@4.0.0, narrow down the `requires-python` range to include this version. For example, "<3.12,>=3.9.11" should work.
```

## Expected behavior

The warning says that pyidatools requires Python<3.12,>=3.6.14. I'm working with Python 3.11.7. I would expect Python 3.11.7 to be in the range [3.6.14, 3.12). Therefore, it should be possible to install the package.

## Environment Information

```bash
PDM version:
  2.12.4    
Python Interpreter:
  C:\Workspace\Python_Runtime\Envs\ida-preshop-mifir-8mTNyt9_-3.11\Scripts\python.exe (3.11)
Project Root:
  C:/Users/s1504gl/projects/ida-preshop-mifir
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.7",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19044",
  "python_full_version": "3.11.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "win32"
}
```

**Comment by pawamoy** [comment]
This is brought up so often that we probably need a dedicated FAQ entry or something :smile: 

The warning is not wrong: the dependency **claims not to work with Python 3.12**, while your project **claims to work with Python 3.12**. This is incompatible. Your project must specify a requirement on Python that is a subset of the intersection of all your dependencies requirements. In short, either add `<3.12` to your project python-requires, or update the dependency to remove the upper bound on Python 3.12.

Your current Python interpreter has nothing to do with this.

**Comment by frostming** [comment]
The main misunderstanding here is locking isn’t for the CURRENT python, but for ALL allowed python versions

**Comment by matthiasgomolka** [comment]
@pawamoy, thanks for the explanation. This makes sense now, but I'm sure I'll reread this a few times in the future ;)

**Comment by frostming** [comment]
@matthiasgomolka in this article I explained a bit about why we are doing like this, for your information

https://frostming.com/en/2024/pdm-lockfile/

**Comment by pawamoy** [comment]
Excellent post @frostming, thanks! This will be useful for future similar questions from users :slightly_smiling_face:
