### ISSUE TITLE
pdm.exe won't work on windows. 

### ISSUE THREAD

**Issue by ubaldot** [pdm-project/pdm#2690]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. Install miniconda (user install)
2. Install pdm through conda
3. Pick any project that has a pyproject.toml 
4. Run `pdm build`

## Actual behavior

`Fatal error in launcher: Unable to create process using '"D:\bld\pdm_1708976200773\_h_env\python.exe"  "C:\Users\yt75534\AppData\Local\miniconda3\envs\myenv\Scripts\pdm.exe" build --help': The system cannot find the file specified.`

## Expected behavior

pdm to build the project.

## Environment Information

Running `pdm info` results in: 

```powershell
Fatal error in launcher: Unable to create process using '"D:\bld\pdm_1708976200773\_h_env\python.exe"  "C:\Users\yt75534\AppData\Local\miniconda3\envs\myenv\Scripts\pdm.exe" info': The system cannot find the file specified.
```

Running on Win10, python 3.12.2

**Comment by frostming** [comment]
It may has something to do with how conda installs tools. Use another installation methods please.

**Comment by ubaldot** [comment]
> > ```
> > "D:\bld\pdm_1708976200773\_h_env\python.exe"
> > ```
> 
> What creates this env?

I don't know who creates this environment. 

> 
> It may has something to do with how conda installs tools. Use another installation methods please.

You mean to install pdm through pip? No, that is too risky if I already use conda (which I cannot change). If pdm does not support conda I am afraid that I will have to switch building system, unfortunately.

**Comment by frostming** [comment]
> If pdm does not support conda I am afraid that I will have to switch building system, unfortunately.

It does support, but the building system has nothing to do with how you install pdm. Namely you can install pdm with pip and still use conda to create environments and pdm can manage that rightly.

**Comment by ubaldot** [comment]
Ok, so why there is the issue with `pdm` when using `conda install pdm` ?

**Comment by frostming** [comment]
> Ok, so why there is the issue with `pdm` when using `conda install pdm` ?

Not familiar with conda, does other CLI tools work in this way? such as `conda install django`

**Comment by ubaldot** [comment]
Yes, they do. So far every package I installed with conda work well, the only issue I am experiencing is with pdm.

**Comment by ubaldot** [comment]
`python.exe -m pdm build` solved the issue. There may be some problem with the pdm feedstock on conda-forge. I am going to open an issue there. Thanks!

**Comment by ubaldot** [comment]
I have an unrelated question though, given that I manage it to work. When I run python.exe -m pdm publish I am asked for username and password. Is there a way to store them in some config file so that pdm publish fetch that info automatically?

**Comment by frostming** [comment]
It's in the docs: https://pdm-project.org/latest/usage/config/#configure-the-repositories-for-upload

**Comment by ubaldot** [comment]
Last question: is it possible for pdm to fetch the credential automatically from `.pypirc` file?
