### ISSUE TITLE
Support uv as the resolver and installer

### ISSUE THREAD

**Issue by txchen** [pdm-project/pdm#2693]
## Is your feature/enhancement proposal related to a problem? Please describe.

uv https://github.com/astral-sh/uv is extremely fast to install pip libs, it would be nice if pdm (install/sync) can optionally invoke uv instead of pip to make it faster.

## Describe the solution you'd like
Add a pip backend option, and support uv.

```[tasklist]
### Tasks
- [ ] https://github.com/pdm-project/pdm/pull/2995
- [ ] #3144 
```

**Comment by frostming** [comment]
There isn't pip in the backend.

We'll see if lockfile format can be standardized and only then we can consider uv.

**Comment by frostming** [comment]
The community and packaging team is making effort on this: https://discuss.python.org/t/lock-files-again-but-this-time-w-sdists/46593

**Comment by Mjboothaus** [comment]
Maybe a pdm-uv package/extension-- keep up the excellent work

**Comment by EtienneT** [comment]
Maybe pdm could leverage just uv resolver.  Like they mention in [this blog post](https://astral.sh/blog/uv), it can be used only as a resolver with uv pip compile.  The speed difference makes a really big difference in the day to day of a dev.

**Comment by frostming** [comment]
> Maybe pdm could leverage just uv resolver. Like they mention in [this blog post](https://astral.sh/blog/uv), it can be used only as a resolver with uv pip compile. The speed difference makes a really big difference in the day to day of a dev.

The way uv resolver works in a different way from PDM's. You must specify the target Python version and platform tags to resolve against, while PDM supports resolving for a wide range of environments.

**Comment by frostming** [comment]
I recently come up a rough plan to leverage uv as the resolver and installer. However it would need to bring some significant change to how cross-platform lockfile works. And ideally it can also solve #46 

I expect it to be a change of large scale and I am not sure if I can make it able to opt in and out. It also depends on how much spare time I can invest in this work, so no promise but stay tuned.

**Comment by frostming** [comment]
The change will be divided into two steps. First, we will support resolving dependencies for the given target platform and Python range combinations, and the current `cross_platform` strategy will be deprecated at the same time. Next, `uv` will be introduced to produce that lock. Therefore, we still need 2 or more minor releases for this to be landed.

**Comment by o-moe** [comment]
@frostming By deprecating `cross_platform` strategy, do you mean that the lock files aren't cross platform anymore?

**Comment by frostming** [comment]
> @frostming By deprecating `cross_platform` strategy, do you mean that the lock files aren't cross platform anymore?

Not by the way it is now. You must specify which platform and python range the lockfile is targeted. You can also specify  several combinations(or matrix) in a single lockfile.

This will make it more smooth to move to the lockfile standard in the future(if it's gonna be a thing).

**Comment by zhuwenxing** [comment]
@frostming 
Hi, I just read a tweet https://x.com/bentomlai/status/1815380726482932107. 
I would like to know how the uv is used.  Is it integrated into PDM or used as a standalone CLI?

**Comment by ipfans** [comment]
@zhuwenxing This PR is not related to PDM tool itself. [src/openllm/venv.py](https://github.com/bentoml/OpenLLM/pull/1054/files#diff-456e3196cb173e8694b7827080eddaca02615e61b96a83f834509c880647f356)

**Comment by frostming** [comment]
An experimental uv integration has landed in the latest **prerelease** of PDM. Or you can try the in-development branch at #3144

**Comment by Super1Windcloud** [comment]
> An experimental uv integration has landed in the latest **prerelease** of PDM. Or you can try the in-development branch at #3144实验性的 uv 集成已出现在最新的 PDM**预发行版**中。或者您可以尝试开发中的分支 #3144

*请问老哥什么时候发布到正式版当中,  现在的解析速度确实过于缓慢,  未来如果用rust或者go重写也是可以考虑 ,还有现在的init template 也不太完善

**Comment by prassanna-ravishankar** [comment]
> An experimental uv integration has landed in the latest **prerelease** of PDM. Or you can try the in-development branch at #3144

looks like #3144 is merged and released. Does that mean this issue is resolved?
