### ISSUE TITLE
Move tool configurations under `setup.cfg` to `pyproject.toml`

### ISSUE THREAD

**Issue by boholder** [pdm-project/pdm#2703]
## Describe the solution you'd like

This repo's [`setup.cfg`](https://github.com/pdm-project/pdm/blob/main/setup.cfg) file contains configurations about three tools: `codespell`, `coverage` and `mypy`.
According to their (newest) documentation, all three tools support to be configured via `pyproject.toml`:
* codespell: https://github.com/codespell-project/codespell?tab=readme-ov-file#using-a-config-file
* coverage: https://coverage.readthedocs.io/en/7.4.3/config.html#sample-file
* mypy: https://mypy.readthedocs.io/en/stable/config_file.html#example-pyproject-toml

By moving configurations to `pyproject.toml`, we can **get rid of `setup.cfg`**, that's what I want, but I'm not sure if it's properly to do.

**Comment by frostming** [comment]
Sounds great, are you interested in contributing to this?

**Comment by boholder** [comment]
> Sounds great, are you interested in contributing to this?

Sure, on going.
