### ISSUE TITLE
pdm lock --update-reuse not updating wheels references in pdm.lock

### ISSUE THREAD

**Issue by deronnax** [pdm-project/pdm#2704]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```
$ pdm init -n --python 3.10
Creating a pyproject.toml for PDM...
Project is initialized successfully
$ pdm add msgpack
Adding packages to default dependencies: msgpack
🔒 Lock successful
Changes are written to pyproject.toml.
Synchronizing working set with resolved packages: 1 to add, 0 to update, 0 to remove

  ✔ Install msgpack 1.0.8 successful

🎉 All complete!

$ grep -c cp310 pdm.lock
11
$ sed  's/3.10/3.11/' -i pyproject.toml
$ pdm lock --update-reuse
INFO: The saved Python interpreter doesn't match the project's requirement. Trying to find another one.
WARNING: Project requires a python version of ==3.11.*, The virtualenv is being created for you as it cannot be matched to the right version.
INFO: python.use_venv is on, creating a virtualenv for this project...
Virtualenv is created successfully at /Users/mathieu/Library/Application Support/pdm/venvs/dpmtest-zz8zpyQg-3.11
🔒 Lock successful
Changes are written to pdm.lock.
$ grep -c cp310 pdm.lock
11
```

## Actual behavior

The references to wheels in pdm.lock are not updated, it still references 3.10 wheels

## Expected behavior

I *think* the references to the wheels should be updated. If not, I think a warning should be printed.
`pdm lock --update-reuse-installed` will correctly update references in the lock file, but implies that the virtualenv have been fully installed, which is not always desirable/doable.
`pdm lock` alone is not an option as it will update the versions in the lock file.

Actually, according to you, what is the good way for upgrading the python version in the pyproject.toml?

## Environment Information

```
$ pdm info && pdm info --env
Loading dotenv file /private/tmp/dpmtest/.env
PDM version:
  2.12.4
Python Interpreter:
  /Users/mathieu/Library/Application Support/pdm/venvs/dpmtest-zz8zpyQg-3.11/bin/python (3.11)
Project Root:
  /private/tmp/dpmtest
Local Packages:

Loading dotenv file /private/tmp/dpmtest/.env
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.7",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "23.4.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 23.4.0: Wed Feb 21 21:51:37 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T8112",
  "python_full_version": "3.11.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}

```

**Comment by frostming** [comment]
I don't understand what you are trying to update in the lockfile. Shouldn't wheels for all python versions locked in `pdm.lock`? Why does it need to update?

**Comment by deronnax** [comment]
No, the wheels in the lock file will be only the ones matching the python versions. In my exemple, there would be only `msgpack-1.0.8-cp310-cp310-[...].whl` wheels references.

**Comment by frostming** [comment]
oh, are you making a no-cross-platform lock?
that should be enabled by default

**Comment by deronnax** [comment]
OK, I think I found what I needed: `pdm lock --refresh` refreshes wheels references, in addition of the `content_hash`. I thought that command was only to refresh the content_hash.

**Comment by frostming** [comment]
I don't think we have implemented such wheel filtering, though it has been requested by someone before.

**Comment by deronnax** [comment]
Thank you for the improved help message, much more telling.
