### ISSUE TITLE
PEP 582 not working for Spyder IDE

### ISSUE THREAD

**Issue by JamesMcIntyre100** [pdm-project/pdm#2705]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

1) On Windows, run pdm --pep582
2) Restart the terminal
3) Inside a python project folder, run pdm init
4) Still inside the project folder, run pdm add [some python package]
5) Inside Spyder, run a python file which imports [some python package]

## Actual behavior

The Spyder console give the error that [some python package] is not installed.
Verified that PEP 582 is working in the terminal as if you run the same python file in the terminal, it works

## Expected behavior

The Python file should run without error in Spyder

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PS C:\Users\James\Documents\Repos\test> pdm info && pdm info --env
At line:1 char:10
+ pdm info && pdm info --env
+          ~~
The token '&&' is not a valid statement separator in this version.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidEndOfLine
```

**Comment by frostming** [comment]
As a deprecated PEP, other tools do not need to support PEP 582. We will no longer put effort on this.

**Comment by JamesMcIntyre100** [comment]
@frostming - does this mean that PEP 582 is no longer an activly supported feature of PDM?

Is it worth changing the wording on [this link](https://pdm-project.org/latest/usage/pep582/) as it implies that even though it's rejected it's still an activly supported feature?
"This is a rejected PEP. However, due to the fact that this feature is the reason for PDM's birth, PDM will retain the support. We recommend using [virtual environments](https://pdm-project.org/latest/usage/venv/) instead."

Do you know if there are any Python package and dependency managers and/or Python forks that support this methodology? Within my industry, it's really hard to work without this feature (I currently basically manually utilitse this methodology but it's very time consuming and untidy)

**Comment by pawamoy** [comment]
> This is a rejected PEP. However, due to the fact that this feature is the reason for PDM's birth, PDM will retain the support. We recommend using [virtual environments](https://pdm-project.org/latest/usage/venv/) instead.

I think the wording is fine, as it says "retain support", and not "actively supported". It also recommends virtualenvs, I think that sets the right expectations.

Besides, PDM works fine here. I would say this is a particularity of Spyder, and PDM can't do anything to improve the situation. I guess Spyder runs a Python interpreter directly, without passing through the shell, and so PEP 582's config in the shell is not used. Try setting the PYTHONPATH variable in your IDE, for example `PYTHONPATH=/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/pep582` (adapt for your own system), and it should fix the issue.

**Comment by JamesMcIntyre100** [comment]
> > This is a rejected PEP. However, due to the fact that this feature is the reason for PDM's birth, PDM will retain the support. We recommend using [virtual environments](https://pdm-project.org/latest/usage/venv/) instead.
> 
> I think the wording is fine, as it says "retain support", and not "actively supported". It also recommends virtualenvs, I think that sets the right expectations.
> 
> Besides, PDM works fine here. I would say this is a particularity of Spyder, and PDM can't do anything to improve the situation. I guess Spyder runs a Python interpreter directly, without passing through the shell, and so PEP 582's config in the shell is not used. Try setting the PYTHONPATH variable in your IDE, for example `PYTHONPATH=/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/pep582` (adapt to your own system/environment), and it should fix the issue.
> 
> > Do you know if there are any Python package and dependency managers and/or Python forks that support this methodology? Within my industry, it's really hard to work without this feature (I currently basically manually utilitse this methodology but it's very time consuming and untidy)
> 
> That is unlikely, as the PEP was rejected. Also, I'm curious to know why this is hard to work without this feature in your industry, if you don't mind elaborating a bit 🙏 Depending on your answer, we could guide you toward different tools/solutions.

I've just tried going into the Spyder PYTHONPATH manager and added "c:\users\james\appdata\roaming\pdm\venv\lib\site-packages\pdm\pep582" and it doesn't work, unfortunately, I can't see a way to directly add \sitecustomize.py directly as it only allows adding folders.

Happy to discuss the reasoning but it's quite complicated. I've had conversations about this on the PDM Discord server and never really managed to explain enough for people to understand. I'm a Process Automation Engineer and virtual envs really don't work well in my line of work

**Comment by pawamoy** [comment]
> I can't see a way to directly add \sitecustomize.py directly as it only allows adding folders.

That's normal, the folder only must be added to PYTHONPATH, not the sitecustomize.py file. If starting a Python interpreter with this setting configured does not work, then there's an issue with how Spyder launches the interpreter. With PYTHONPATH set, the pep582 folder should land in `sys.path`, and Python would execute sitecustomize.py at startup, then allowing to find packages in `__pypackages__` relative to the repository root. Make sure the Python interpreter is launched in the right directory (your repository root, where `__pypackages__` is).

> Happy to discuss the reasoning but it's quite complicated. I've had conversations about this on the PDM Discord server and never really managed to explain enough for people to understand. I'm a Process Automation Engineer and virtual envs really don't work well in my line of work

OK, no problem :smile: Well, you should maybe share your experience on the Python Discuss forum. PEP 582 was rejected but that doesn't mean something similar can't be brought up again.

**Comment by JamesMcIntyre100** [comment]
Ok, so... after a very long time of stressing about this, I've (basically) got it working. For anyone who finds this closed ticket and wants to get this working. Here are the steps for Windows:
1) With PDM installed, run pdm --pep582
2) Put "environment variables" into the the Start menu search and open "Edit the system environment variables"
3) In the advanced tab, click the bottom button "Environment Variables", double click on PYTHONPATH and copy the folder location which should end in pep582
Within the Spyder tools menu, go to IPython console/ Startup tab/ Run a file - check the box "Use the following file" and click the select file button to the right of the path box
4) Past in your path and then choose the "sitecustomize.py" file
5) Click apply

This now should work but at the moment you'll need to restart the console (burger menu/ restart console) before the changes take effect for each new console **even on a fresh start-up** until someone figures out a way to get this to happen automatically or Spyder fix this.

@pawamoy - should the above guide be added to pep582 guides, along side the PyCharm guides etc?

**Comment by pawamoy** [comment]
Sure, feel free to send a PR with an update to the docs, I'll review it :slightly_smiling_face:

**Comment by frostming** [comment]
You can use PEP 582 in PDM, but if other tools do not support PEP 582 well, we have no way to improve this situation, just like this issue.



> Unless @frostming does not want any docs update regarding PEP 582! Let us know 🙂

Why not
