### ISSUE TITLE
Upgrade documentation

### ISSUE THREAD

**Issue by Seven45** [pdm-project/pdm#2719]
## Is your feature/enhancement proposal related to a problem? Please describe.

Hello. I have not found comprehensive documentation for using pdm in gitlab-ci (which my company uses), nor a suitable base image for ci-jobs.

So I implemented a simple docker-image, which I published on dockerhub.

In the readme file I have included some reusable code that may be useful for documenting the pdm itself. For example, using pdm for multistage-build (venv based).

I will be glad if examples from my repository are useful to the pdm community.

## Describe the solution you'd like

https://github.com/Seven45/pdm-ci

What is the right thing to do next?
- create a pull request in pdm
- wait until the maintainers expand the pdm documentation
- maintain my repository regardless of pdm

**Comment by frostming** [comment]
I think it doesn't make much difference from starting from `python` base image and run `pip install pdm` in the builder stage. We have already documented that at https://pdm-project.org/latest/usage/advanced/#use-pdm-in-a-multi-stage-dockerfile. However, you can still maintain the image yourself.

Thanks anyway. I am going to close it.

**Comment by pawamoy** [comment]
@Seven45 you can also try submitting your project at https://github.com/pdm-project/awesome-pdm :slightly_smiling_face:
