### ISSUE TITLE
Being a little more conservative when deleting the build dest directory

### ISSUE THREAD

**Issue by mbyrnepr2** [pdm-project/pdm#2733]
## Is your feature/enhancement proposal related to a problem? Please describe.

Hi! I started playing around with the project for the first time yesterday :)

The command being run:
`pdm build --dest .`

This command removes the current directory (the `clean` option runs by default on the specified `dest` directory).
Understandably, when using the `--dest` option, you probably know what you are doing; so I can see the point that this is currently working as expected.

## Describe the solution you'd like

I had something like the following in mind. If the basename of `dest` is "dist"(the default value of `dest` if the user does not provide the option) then it is probably ok to `clean` it.
Otherwise if the only files in the `dest` directory are `.gz` and `.whl` then proceed to clean `dest`:

```diff
--- a/src/pdm/cli/commands/build.py
+++ b/src/pdm/cli/commands/build.py
@@ -48,7 +48,10 @@ class Command(BaseCommand):
             return
         if not os.path.isabs(dest):
             dest = project.root.joinpath(dest).as_posix()
-        if clean:
+        if clean and (
+            os.path.basename(dest) == "dist"
+            or all(f.endswith((".gz", ".whl")) for f in os.listdir(dest))
+        ):
             shutil.rmtree(dest, ignore_errors=True)
         if not os.path.exists(dest):
             os.makedirs(dest, exist_ok=True)
```

Again, understandable if the current state is ok for everyone - just thought I would pitch the idea. Thanks for this project!

**Comment by frostming** [comment]
That looks cumbersum for such option, I prefer to keep it as it is now.
There are some deleting commands that may lead to disastrous result if used improperly, we need to live with that.

Thanks

**Comment by mbyrnepr2** [comment]
Indeed. Thanks for considering it @frostming.

The only thing is that the build command isn’t obviously a delete command. I understand your stance so fair enough.
