### ISSUE TITLE
pdm python comand from within a zipapp

### ISSUE THREAD

**Issue by franzhaas** [pdm-project/pdm#2738]
Hi,

Due to the need of zstandard for the pdm python commands, which come as  a native libraries, the pdm python commands do not work when running pdm from a zipapp.

I understand that this is a limitation of the zipapp concept. 

I did not look into the details yet, but I believe that the available built-in compression gz might be a good enough alternatives allowing for the use of zipapps. https://github.com/indygreg/python-build-standalone/releases here are also gz compressed downloads...

Do you think that moving from zstd to gz would be an option?

Best regards,
Franz

**Comment by franzhaas** [comment]
after looking more thoroghly, i believe the relevant files are only available as zstd...

**Comment by frostming** [comment]
[pbs-installer@2024.4.1][1] now prefers the `.tar.gz` link, please upgrade it.

[1]: https://github.com/frostming/pbs-installer/releases/tag/2024.4.1

**Comment by franzhaas** [comment]
it works thanks!
