### ISSUE TITLE
pdm 2.13.1 fails at random under Windows with The system cannot find the file specified:  'D:\\a\\...\\.checksum'

### ISSUE THREAD

**Issue by mjurbanski-reef** [pdm-project/pdm#2739]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Not clear steps to reproduce right now, this is where I observed the problem:
https://github.com/Backblaze/b2-sdk-python/actions/runs/8480439097/job/23236188767?pr=487

Seems like regression introduced in https://github.com/pdm-project/pdm/pull/2737/files

```
pdm install  # on Windows
```

## Actual behavior

Seems like race condidtion failing with:
```
The system cannot find the file specified: 
'D:\\a\\...\\Lib\\site-packages\\.checksum'
```

## Expected behavior

Install is successful as it was with pdm 2.13.0 every time.

## Environment Information

```bash
# instead of Paste the output of `pdm info && pdm info --env` below, manually provided:
Windows @ Github Actions runner (see above link)
pdm 2.13.1
```

**Comment by frostming** [comment]
Closed by #2749
