### ISSUE TITLE
If PDM_PYPI_URL is empty, PDM complains instead of defaulting to PyPI.org

### ISSUE THREAD

**Issue by pawamoy** [pdm-project/pdm#2742]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```bash
mkdir project
cd project
pdm init -n
PDM_PYPI_URL= pdm add setuptools
```

## Actual behavior

Output:

```
Adding packages to default dependencies: setuptools
See /home/pawamoy/.local/state/pdm/log/pdm-lock-q2_o46tn.log for detailed debug log.
[PdmUsageError]: You must specify at least one index in pyproject.toml or config.
The 'pypi.ignore_stored_index' config value is False
```

## Expected behavior

Default to pypi.org.

My use-case: I serve a local index with `pypiserver` at http://localhost:31411. It redirects to PyPI.org when it does find a project. My shell config exports `PDM_PYPI_URL=http://localhost:31411/simple`. When I don't want to pass through my local index, I use my `no-insiders` alias which is `env PDM_PYPI_URL= PIP_INDEX_URL= UV_INDEX_URL=`, like this: `no-insiders pdm install`.

I thought setting PDM_PYPI_URL to the empty string would go back to the default behavior of using PyPI.org.

## Alternative solution

I see I can define my alias like this instead: `alias no-insiders='env -u PDM_PYPI_URL -u PIP_INDEX_URL -u UV_INDEX_URL'`. Though it would be nice to be able to do a simple `PDM_PYPI_URL= pdm ...`.

## Environment Information

```bash
PDM version:
  2.13.1
Python Interpreter:
  /home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.11.5/bin/python3 (3.11)
Project Root:
  /media/data/dev/pdm-backend
Local Packages:
  /media/data/dev/pdm-backend/__pypackages__/3.11
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.5",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.8.2-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Wed, 27 Mar 2024 14:17:24 +0000",
  "python_full_version": "3.11.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
First, `'env -u PDM_PYPI_URL -u PIP_INDEX_URL -u UV_INDEX_URL'` looks more correct to me so why not?

Second, `ENV_VAR=""` means *explicit* `false` for boolean config items, treating it as unset for other env vars makes the code dirty from my point of view.

**Comment by pawamoy** [comment]
Fair enough, closing then, thanks for your answer!
