### ISSUE TITLE
Option for defining proxy environment variables (http_proxy & https_proxy) in pyproject.toml

### ISSUE THREAD

**Issue by Nomiez** [pdm-project/pdm#2752]
## Is your feature/enhancement proposal related to a problem? Please describe.
Referring to Feature Request entry: https://github.com/pdm-project/pdm/discussions/2751.

Hey, I have a small probem. I want to use PDM in my company behind a proxy. Currently I have to export the proxy environment variables http_proxy and https_proxy manually each time I want to use pdm. Therefore I am searching for a way that is equivalent to[ rye's proxy config](https://rye-up.com/guide/config/#config-file) in the .toml file for pdm:

```
[proxy]
# the proxy to use for HTTP (overridden by the http_proxy environment variable)
http = "http://127.0.0.1:4000"
# the proxy to use for HTTPS (overridden by the https_proxy environment variable)
https = "http://127.0.0.1:4000"
For pdm this could be implemented by adding the two options:
```

## Describe the solution you'd like
Support for exporting http_proxy & https_proxy environment variables out of pdm.toml before running a pdm command like pdm install.

- `proxy.http`
- `proxy.https`

The values can then be exported into the environment. If desired I can implement this by my own.

**Comment by frostming** [comment]
We are not adding this, use system environment variables instead.
