### ISSUE TITLE
Checksum file not being found - causes PDM install script error

### ISSUE THREAD

**Issue by sr-murthy** [pdm-project/pdm#2755]
- [Y ] I have searched the issue tracker and believe that this is not a duplicate.

The installation of PDM via the install script fails in a CI job using Python 3.11.8 and running on an Ubuntu runner. Here is the full output in CI:
```bash
curl -sSLO https://pdm-project.org/install-pdm.py
curl -sSL https://pdm-project.org/install-pdm.py.sha256 | shasum -a 256 -c -
...
...
shasum: standard input: no properly formatted SHA checksum lines found
Error: Process completed with exit code 1.
...
```

I've attached a screenshot of the job log from GitHub.

<img width="1037" alt="Screenshot 2024-04-01 at 11 24 46" src="https://github.com/pdm-project/pdm/assets/9358070/1fa5f091-5118-42e2-acc0-08ea4430ba42">

## Steps to reproduce

I tried to reproduce this manually on my Mac, by running the Shasum verification command:
```bash
$ curl -sSL https://pdm-project.org/install-pdm.py.sha256 | shasum -a 256 -c -
shasum: standard input: no properly formatted SHA checksum lines found
```
The target file does not appear to available from the [PDM docs site link](https://pdm-project.org/install-pdm.py.sha256 ), which would explain this:
```bash
$ curl -sSL https://pdm-project.org/install-pdm.py.sha256
Couldn't find the requested file /install-pdm.py.sha256 in pdm-project/pdm.
```
This exact command is mentioned in the [PDM docs](https://pdm-project.org/latest/#recommended-installation-method).

I haven't looked at this in much detail but has something changed? I can see the checksum file exists in the GitHub project.

## Actual behavior

As described above - SHA 256 checkum target file not found in docs.

## Expected behavior

The file to be found and verified successfully (as before).

## Environment Information

Error on Ubuntu runner happens before PDM install, so cannot get PDM info. Locally I'm running PDM 2.12.4 in a Python 3.11.2 environment.

**Comment by sr-murthy** [comment]
As a workaround I'm using the [raw checksum file](https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py.sha256) in the project, which does verify OK:
```bash
$ curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py.sha256 | shasum -a 256 -c -
install-pdm.py: OK
```
The one [linked from docs](https://pdm-project.org/install-pdm.py.sha256) still fails.

**Comment by frostming** [comment]
I've changed the domain to redirect to raw github files, check it again.

**Comment by sr-murthy** [comment]
Thanks, works now.
