### ISSUE TITLE
Install an build a project from github

### ISSUE THREAD

**Issue by ioangatop** [pdm-project/pdm#2763]
Hi! I would like to install a library from Github, but as it has some C++ dependencies, I would like to build it - basically it includes `ext_modules`

For that, I would have to pass an env variable `MMCV_WITH_OPS=1`. Specifically, with pip I'm doing the following:
```
pip install torch==2.1.0
MMCV_WITH_OPS=1 pip install git+https://github.com/open-mmlab/mmcv
```
How can I do this with `pdm`? The command `MMCV_WITH_OPS=1 pdm add git+https://github.com/open-mmlab/mmcv` does not seem to work - it installs the wheel but does not seem to build it

Thank you

**Comment by ioangatop** [comment]
It is worth to note that I tried to add in `pyproject` the following:
```
[[tool.pdm.source]]
type = "find_links"
url = "https://download.openmmlab.com/mmcv/dist/cpu/torch2.1/index.html"
name = "mmcv"
```

and i have the following logs: 
[Terminal.log](https://github.com/pdm-project/pdm/files/14844585/Terminal.log)

which seems to build smthing... however the following command does not work:
```
pdm run python -c "import mmcv; from mmcv.ops import get_compiler_version"
```

**Comment by frostming** [comment]
> it installs the wheel but does not seem to build it

There is no wheel for a git dependency and the log clearly shows it was building the package.

**Comment by ioangatop** [comment]
@frostming yes indeed, I'm also not sure what is going on... probably in the near future try to investigate more and keep you posted
