### ISSUE TITLE
Transitive local dependencies result in absolute path in the lockfile

### ISSUE THREAD

**Issue by mkhl** [pdm-project/pdm#2771]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

* Have three local projects, e.g. dep, lib, and app. The intention is that app depends on lib and lib depends on dep. (I prepared https://github.com/mkhl/pdm-nested-local to make this easier.)
* `cd lib; pdm add ../dep; cd..` (this results in the state of the main branch)
* `cd app; pdm add ../lib` (this results in the state at the "bug" branch)

## Actual behavior

The resulting lockfile of app contains the absolute path to the checkout, in my case
```
[[package]]
name = "dep"
version = "0.1.0"
requires_python = ">=3.11"
path = "/home/mkhl/src/sandbox/pdm-nested-local/lib/../dep"
summary = "Default template for PDM package"
groups = ["default"]
```

<details>
<summary>Output of <code>pdm add -v ../lib</code></summary>
<pre><code>
; pdm add -v ../lib
Adding packages to default dependencies: lib @ file:///${PROJECT_ROOT}/../lib
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   lib @ file:///${PROJECT_ROOT}/../lib
pdm.termui:   python>=3.11
pdm.termui:   Adding requirement lib @ file:///${PROJECT_ROOT}/../lib
pdm.termui:   Adding requirement python>=3.11
pdm.termui: ======== Starting round 0 ========
unearth.preparer: The file ../lib is a local directory, use it directly
STATUS: Resolving: new pin python>=3.11
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui:   Adding requirement dep @ file:///home/mkhl/src/sandbox/pdm-nested-local/lib/../dep(from lib 0.1.0)
STATUS: Resolving: new pin lib 0.1.0
pdm.termui: Pinning: lib 0.1.0
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
unearth.preparer: The file /home/mkhl/src/sandbox/pdm-nested-local/lib/../dep is a local directory, use it directly
STATUS: Resolving: new pin dep 0.1.0
pdm.termui: Pinning: dep 0.1.0
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:   python None
pdm.termui:      lib file:///${PROJECT_ROOT}/../lib
pdm.termui:      dep file:///home/mkhl/src/sandbox/pdm-nested-local/lib/../dep
STATUS: Fetching hashes for resolved packages...
🔒 Lock successful
Changes are written to pyproject.toml.
STATUS: Resolving packages from lockfile...
unearth.preparer: The file . is a local directory, use it directly
Synchronizing working set with resolved packages: 0 to add, 2 to update, 0 to 
remove

pdm.termui: Overwriting distribution lib
pdm.termui: Overwriting distribution dep
pdm.termui: Preparing environment(Isolated mode) for PEP 517 build...
pdm.termui: Preparing environment(Isolated mode) for PEP 517 build...
pdm.termui: Running PEP 517 backend to build a wheel for <Link file:///home/mkhl/src/sandbox/pdm-nested-local/dep (from None)>
pdm.termui: Running PEP 517 backend to build a wheel for <Link file:///home/mkhl/src/sandbox/pdm-nested-local/lib (from None)>
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   pdm-backend
pdm.termui:   python==3.11.8
pdm.termui:   Adding requirement pdm-backend
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   pdm-backend
pdm.termui:   python==3.11.8
pdm.termui:   Adding requirement pdm-backend
pdm.termui:   Adding requirement python==3.11.8
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui: Pinning: pdm-backend 2.1.8
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:        python None
pdm.termui:   pdm-backend 2.1.8
pdm.termui:   Adding requirement python==3.11.8
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui: Pinning: pdm-backend 2.1.8
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:        python None
pdm.termui:   pdm-backend 2.1.8
pdm.termui: Installing pdm-backend@2.1.8...
pdm.termui: Installing pdm-backend@2.1.8...
pdm.termui: Synchronization complete.
pdm.termui: Synchronization complete.
pdm.termui: /tmp/pdm-build-env-ic68tgfc-shared/lib/python3.11/site-packages/pdm/backend/wheel.py:227: PDMWarning: No license files are matched with glob patterns ['LICENSES/*', 'LICEN[CS]E*', 'COPYING*', 'NOTICE*', 'AUTHORS*'].
pdm.termui:   for file in self.find_license_files():
pdm.termui:  - Adding .pdm-build/dep-0.1.0.dist-info/METADATA -> dep-0.1.0.dist-info/METADATA
pdm.termui:  - Adding .pdm-build/dep-0.1.0.dist-info/WHEEL -> dep-0.1.0.dist-info/WHEEL
pdm.termui:  - Adding src/dep/__init__.py -> dep/__init__.py
pdm.termui:  - Adding dep-0.1.0.dist-info/RECORD -> dep-0.1.0.dist-info/RECORD
pdm.termui: /tmp/pdm-build-env-3mctof1q-shared/lib/python3.11/site-packages/pdm/backend/wheel.py:227: PDMWarning: No license files are matched with glob patterns ['LICENSES/*', 'LICEN[CS]E*', 'COPYING*', 'NOTICE*', 'AUTHORS*'].
pdm.termui:   for file in self.find_license_files():
pdm.termui:  - Adding .pdm-build/lib-0.1.0.dist-info/METADATA -> lib-0.1.0.dist-info/METADATA
pdm.termui:  - Adding .pdm-build/lib-0.1.0.dist-info/WHEEL -> lib-0.1.0.dist-info/WHEEL
pdm.termui:  - Adding src/lib/__init__.py -> lib/__init__.py
pdm.termui:  - Adding lib-0.1.0.dist-info/RECORD -> lib-0.1.0.dist-info/RECORD
  ✔ Update dep 0.1.0 -> 0.1.0 successful
  ✔ Update lib 0.1.0 -> 0.1.0 successful
Installing the project as an editable package...
pdm.termui: Overwriting distribution app
pdm.termui: Preparing environment(Isolated mode) for PEP 517 build...
pdm.termui: Running PEP 517 backend to build a wheel for <Link file:///home/mkhl/src/sandbox/pdm-nested-local/app (from None)>
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   editables
pdm.termui:   python==3.11.8
pdm.termui:   Adding requirement editables
pdm.termui:   Adding requirement python==3.11.8
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui: Pinning: editables 0.5
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:      python None
pdm.termui:   editables 0.5
pdm.termui: Installing editables@0.5...
pdm.termui: Synchronization complete.
pdm.termui: /tmp/pdm-build-env-ic68tgfc-shared/lib/python3.11/site-packages/pdm/backend/wheel.py:227: PDMWarning: No license files are matched with glob patterns ['LICENSES/*', 'LICEN[CS]E*', 'COPYING*', 'NOTICE*', 'AUTHORS*'].
pdm.termui:   for file in self.find_license_files():
pdm.termui:  - Adding .pdm-build/.gitignore -> .gitignore
pdm.termui:  - Adding .pdm-build/app-0.1.0+editable.dist-info/METADATA -> app-0.1.0+editable.dist-info/METADATA
pdm.termui:  - Adding .pdm-build/app-0.1.0+editable.dist-info/WHEEL -> app-0.1.0+editable.dist-info/WHEEL
pdm.termui:  - Adding .pdm-build/app.pth -> app.pth
pdm.termui:  - Adding app-0.1.0+editable.dist-info/RECORD -> app-0.1.0+editable.dist-info/RECORD
  ✔ Update app 0.1.0+editable -> 0.1.0 successful

🎉 All complete!
</code></pre>
</details>

## Expected behavior

The lockfile contains the relative path to the transitive dependency dep and can be used regardless of where the code is checked out.

## Environment Information

```bash
PDM version:
  2.13.2
Python Interpreter:
  /home/mkhl/src/sandbox/pdm-nested-local/app/.venv/bin/python (3.11)
Project Root:
  /home/mkhl/src/sandbox/pdm-nested-local/app
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.8",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.8.2-zen2-1-zen",
  "platform_system": "Linux",
  "platform_version": "#1 ZEN SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:20 
+0000",
  "python_full_version": "3.11.8",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
Yes, PDM loses control of the dependency(`lib`), so the path to transitive dependency(`dep`) can't be translated to PDM-aware variables, you can instead declare all local path as direct dependencies in app.
