### ISSUE TITLE
PDM doesn't find Python interpreters when PDM_IGNORE_ACTIVE_VENV is set

### ISSUE THREAD

**Issue by p-rogalski** [pdm-project/pdm#2779]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1.  Have some Python version `>=3.10` installed
2. Use following minimal `pyproject.toml`
   
   ```toml
   [project]
   name = "test"
   version = "0.0.1"
   requires-python = ">=3.10"
   ```

3. Set environment variable `PDM_IGNORE_SAVED_PYTHON` and `PDM_IGNORE_ACTIVE_VENV`.
4. Try to install the project:

   ```shell
   pdm install --verbose
   ```

## Actual behavior

PDM does not find a Python version to use and errors out:

```
PS C:\Users\progalski\git\test> pdm install --verbose
WARNING: Lockfile does not exist
Updating the lock file...
[NoPythonVersion]: No Python that satisfies >=3.10 is found on the system.
```

## Expected behavior

According to [PDM Docs: Virtualenv auto-detection](https://pdm-project.org/latest/usage/venv/#virtualenv-auto-detection) I would expect that PDM creates a new virtual environment because virtual env auto-detection fails.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PS C:\Users\progalski\git\test> pdm info && pdm info --env
[NoPythonVersion]: No Python that satisfies >=3.10 is found on the system.
```

Environment Information without the problematic environment variables set:
```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.13.2
Python Interpreter:
  C:\Users\progalski\git\test\.venv\Scripts\python.exe (3.11)
Project Root:
  C:/Users/progalski/git/test
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.11.4",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.22631",
  "python_full_version": "3.11.4",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "win32"
}
```

**Comment by p-rogalski** [comment]
I get the same error message when only `PDM_IGNORE_ACTIVE_VENV` is set. Maybe that's a lead you can follow.

**Comment by p-rogalski** [comment]
I had a look into the PDM source code, the logic of getting a valid interpreter can be found here: https://github.com/pdm-project/pdm/blob/881cd4e38d31663ae67bdae227ec1ccdfd5e2c77/src/pdm/project/core.py#L193

If `PDM_IGNORE_ACTIVE_VENV` is set, the logic which creates a new virtual environment is skipped completely. This is unexpected, because the env var explicitly states `ACTIVE` in it's name.

**Comment by noirbizarre** [comment]
I just hit the same issue.
Working on a fix
