### ISSUE TITLE
pdm sync intermittently fails when pdm manages itself and install.parallel is True

### ISSUE THREAD

**Issue by palotasb-booking** [pdm-project/pdm#2780]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

> [!IMPORTANT]  
> Update: I've uploaded a minimal reproducible example to https://github.com/palotasb-booking/pdm-sync-mcve

I don't have a minimal reproducible example I can share right now but I'll try to do so later. Until then I can only provide a high-level description of the issue, sorry!

* We have a repo with a `/pyproject.toml` of a PDM-based project.
  * It includes in it's `tool.pdm.dev-dependencies`: `pdm`, `requests`.
* We have a `/pdm.lock` file in the repo.
* In our CI, this happens:
  * A new venv is created and activated via the builtin `venv` module.
  * `pip install pdm` is run
  * `pdm sync` is run, and intermittently fails. (Usually 1 or 2 times out of 30 but this varies.)

The error all look like the following:

[log1.txt](https://github.com/pdm-project/pdm/files/14905910/log1.txt)

There is always an underlying `ImportError` during the installation step, usually one of these:

```
ImportError: cannot import name 'Session' from 'requests' (unknown location)
ImportError: cannot import name 'SKIP_HEADER' from 'urllib3.util' (unknown location)
```

The final error message is always the following:

```
[InstallationError]: Some package operations are not complete yet
WARNING: Add '-v' to see the detailed traceback
```

Usually re-running `pdm sync` fixes the issue (e.g., if we have `pdm sync || pdm sync` in the CI), but sometimes the installed packages end up in a state the 2nd call to `pdm sync` fails, and the entire output from the 2nd call to `pdm sync` is the following:

```
Traceback (most recent call last):
  File "/opt/venv/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/opt/venv/lib/python3.10/site-packages/pdm/core.py", line 288, in main
    return Core().main(args or sys.argv[1:])
  File "/opt/venv/lib/python3.10/site-packages/pdm/core.py", line 57, in __init__
    self.init_parser()
  File "/opt/venv/lib/python3.10/site-packages/pdm/core.py", line 87, in init_parser
    module = importlib.import_module(f"pdm.cli.commands.{name}", __name__)
  File "/opt/example-python/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/venv/lib/python3.10/site-packages/pdm/cli/commands/use.py", line 10, in <module>
    from pdm.models.caches import JSONFileCache
  File "/opt/venv/lib/python3.10/site-packages/pdm/models/caches.py", line 12, in <module>
    from cachecontrol.cache import SeparateBodyBaseCache
  File "/opt/venv/lib/python3.10/site-packages/cachecontrol/__init__.py", line 13, in <module>
    from cachecontrol.adapter import CacheControlAdapter
  File "/opt/venv/lib/python3.10/site-packages/cachecontrol/adapter.py", line 11, in <module>
    from requests.adapters import HTTPAdapter
  File "/opt/venv/lib/python3.10/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'
```

## Workaround

Setting `pdm config --local install.parallel False` has fixed this bug for us, or at least it has reduced the probability so much that we haven't hit it yet out of 100s of runs.

## Actual behavior

`pdm sync` fails with the errors described above.

## Expected behavior

`pdm sync` successfully installs the packages all the time.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

$ pdm info
INFO: Inside an active virtualenv /opt/venv, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
PDM version:
  2.13.3
Python Interpreter:
  /opt/venv/bin/python (3.11)
Project Root:
  /builds/example
Local Packages:

# on Python 3.11
$ pdm info --env
INFO: Inside an active virtualenv /opt/venv, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.7",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "4.18.0-544.el8.x86_64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Thu Feb 22 21:29:23 UTC 2024",
  "python_full_version": "3.11.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}

# on Python 3.10
$ pdm info --env
INFO: Inside an active virtualenv /opt/venv, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.9",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "4.18.0-544.el8.x86_64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Thu Feb 22 21:29:23 UTC 2024",
  "python_full_version": "3.10.9",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}

# on Python 3.9
$ pdm info --env
INFO: Inside an active virtualenv /opt/venv, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.18",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "4.18.0-544.el8.x86_64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Thu Feb 22 21:29:23 UTC 2024",
  "python_full_version": "3.9.18",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by huxuan** [comment]
Maybe OT, but generally, `pdm` and `pdm-backends` do not need to be included as `dev-dependencies`.

`pdm` can be installed standalone, for example, with `pipx install pdm`.
`pdm-backends` is mostly used for building package, it will be installed automatically when running something like `pdm build`.

**Comment by palotasb-booking** [comment]
It's a valid point, although I agree that it's off-topic a bit because it's a bug either way.

The reason we do it this way is two-fold:

* This is how we used to do it in the olden times with just `pip` and `venv`. The development setup was `git clone ...; cd project; python3 -m venv .venv; . .venv/bin/activate; pip install --no-deps -e '.[dev]' -r requirements.txt`. Updating requirements was `deactivate; python3 -m venv --clear .venv; . .venv/bin/activate; pip install -e '.[dev]'; pip freeze --all --exclude-editable >requirements.txt`. Note that `--all` will include `pip` itself in `requirements.txt` and it will correctly self-update.
* This way the only global requirement is `python3` (and `python3-venv` on Linuxes where that's a separate thing) and everything else can be bootstrapped from the project itself. The fewer independent tools people need to install on system (or $USER) level, the better, because that external tool can get more easily out of sync, people won't update it, etc.

**Comment by frostming** [comment]
I don't think there is any we can improve here, dependencies might have been changed between different PDM versions and it would always complain ModuleNotFound if you are downgrading itself during the PDM process run.

**Comment by palotasb-booking** [comment]
Thanks for the quick response! Would you also recommend `pipx install pdm` or `brew install pdm`? Or recommend using one of these over the other? We generally try to use official or at least community-managed installers and package repos over `curl ... | bash`-style install methods, so we would prefer `pipx` or `brew` if installing `pdm` within a PDM-managed `venv` isn't supported.

**Comment by palotasb-booking** [comment]
@frostming in case you want to look into this anyway, I've uploaded a minimal reproducible example to https://github.com/palotasb-booking/pdm-sync-mcve - The issue is reproducible with only `["requests", "pdm"]` listed as dependencies.

**Comment by frostming** [comment]
> Would you also recommend `pipx install pdm` or `brew install pdm`

`pipx` is recommended and is my favorite way to manage CLI tools
