### ISSUE TITLE
pdm outdated shows self package when project.name contains underscores

### ISSUE THREAD

**Issue by killjoy1221** [pdm-project/pdm#2785]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

In a project whose name contains underscores, run the command `pdm outdated`.

pyproject.toml
```toml
[project]
name = "package_name"
```

## Actual behavior

A table is printed which includes the self package.

```
╭──────────────┬────────────────┬────────┬────────╮
│ Package      │ Installed      │ Pinned │ Latest │
├──────────────┼────────────────┼────────┼────────┤
│ package-name │ 0.8.1+editable │        │ 0.8.1  │
╰──────────────┴────────────────┴────────┴────────╯
```

## Expected behavior

The self package should not be included in the output. It works properly after replacing underscores with dashes in `project.name`.

## Environment Information

```bash
❯ pdm info && pdm info --env
PDM version:
  2.13.3
Python Interpreter:
  /home/messingm/git/cmdb-client/.venv/bin/python (3.9)
Project Root:
  /home/messingm/git/cmdb-client
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.18",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.146.1-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Thu Jan 11 04:09:03 UTC 2024",
  "python_full_version": "3.9.18",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
@huxuan are you interested in this one?

**Comment by huxuan** [comment]
> @huxuan are you interested in this one?

Absolutely, I will take a look soon.
