### ISSUE TITLE
类似 miniconda 的 py 安装功能

### ISSUE THREAD

**Issue by 522247020** [pdm-project/pdm#2804]
我以前比较喜欢使用 miniconda 来当做虚拟环境管理。
主要原因是它能帮助我创建其他版本的 py 环境。
而不用我下载一个新的 py 安装包。
在 win 中更新 py 只能重新下载一个 py 安装包感觉这样比较麻烦。
Linux 中更新 py 也会有影响。
在看到 uv 包出来后也没有这个功能。
（我在想既然使用 rust 实现了，已经不依赖 py 了那么为什么检测不到系统中有 py 的情况下不能自己下载一个 py 呢？）
我在想 pdm 是否也能在没有 py 环境的情况下创建 py 的虚拟环境？

**Comment by huxuan** [comment]
Please try `pdm python --help`. :-)
