### ISSUE TITLE
Add a new config python.providers option for the PDM's standalone python builds

### ISSUE THREAD

**Issue by stfdxv** [pdm-project/pdm#2811]
## Is your feature/enhancement proposal related to a problem? Please describe.

I'd like PDM to search for interpreters only among the standalone python builds, installed with `pdm python install`.

## Describe the solution you'd like

Would be great to do `pdm config python.providers pdm`. Where `pdm` (or a more appropriate name) stands for the interpreters, installed by PDM.

**Comment by frostming** [comment]
Though it is not so appropriate, but we share the same installation source as `rye`. And you can notice `rye` is listed in the `python.providers` config.

**Comment by stfdxv** [comment]
@frostming But if I do `pdm config python.providers rye` and then `pdm init`, PDM still finds some non-standalone pythons: as it looks like, the first one from PATH and the one PDM was installed with. How can I prevent this?

**Comment by frostming** [comment]
no way. not all found Pythons are consolidated into providers, for minimal availability
