### ISSUE TITLE
pdm 的 配置文件 config.toml 是否可以在安装pdm 指定的PDM_HOME 一个路径？

### ISSUE THREAD

**Issue by selfeasy** [pdm-project/pdm#2814]
pdm 的 配置文件 config.toml 是否可以在安装pdm 时指定的PDM_HOME 一个路径？

**Comment by frostming** [comment]
Then the path must be stored somewhere for PDM to read from, but the config file is moved so it can't be found.

This seems to cause a recursive problem.
