### ISSUE TITLE
Why does `pdm venv create` not ask me which interpreter to use but `pdm init`/`pdm use` does?

### ISSUE THREAD

**Issue by BurningLutz** [pdm-project/pdm#2818]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

In an existing but not yet installed project, it is very weird that `pdm venv create` doesn't ask me which interpreter to use, insead it silently choose one, and the interpreter used to install pdm is preferred if it match the `requires-python` field in `pyproject.toml`. This is unexpected because I want to use manually built interpreters (by pyenv for example).

## Steps to reproduce

Type `pdm venv create` inside an existing but not yet installed project and you'll see it silently chooses one interpreter for you.

## Actual behavior

 `pdm venv create` silently chooses one interpreter for you.

## Expected behavior

`pdm venv create` should ask me which interpreter to use, like `pdm init`/`pdm use` does.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
WARNING: Project requires a python version of <3.12,>=3.11, The virtualenv is being created for you as it cannot be matched to the right version.
INFO: python.use_venv is on, creating a virtualenv for this project...
Virtualenv is created successfully at /home/lutz/Documents/foo/.venv
PDM version:
  2.14.0
Python Interpreter:
  /home/lutz/Documents/foo/.venv/bin/python (3.11)
Project Root:
  /home/lutz/Documents/foo
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.11.9",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.146.1-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Thu Jan 11 04:09:03 UTC 2024",
  "python_full_version": "3.11.9",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
This is to reduce confusion. Now `pdm use` can create a venv for you and allows selection.

**Comment by BurningLutz** [comment]
> This is to reduce confusion. Now `pdm use` can create a venv for you and allows selection.

Does it mean there is no need to use `pdm venv create` command in the future, as its functionality is repalced by `pdm use`?
