### ISSUE TITLE
Bug with new 2.14 version - install plugin in editable mode & from local path

### ISSUE THREAD

**Issue by ariadnafe** [pdm-project/pdm#2820]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

## Actual behavior

I have recently upgraded the PDM version from 2.13.2 to 2.14 and I have a bug.

Since the new 2.14 version, it is not possible to install plugins using local paths and editable mode. In the past, we could install our plugins by using our local path in editable mode. Using this syntax in our pyproject.toml files:

```bash
[tool.pdm]
plugins = ["-e /local/path/projects/plugins"]
````
And then, by doing pdm install --plugins we could easily install our plugin without having to build it. However, since the last release, we get the following error when trying to install it:

ERROR: Failed to load plugin myplugin_pdm_plugin=pdm_myplugin.plugin:main: No module named 'myplugin'

In the previous versions we could use this functionality, that now it is not working. Could you please clarify what happened with this functionality?

**Comment by noirbizarre** [comment]
According to [documentation](https://pdm-project.org/latest/dev/write/#specify-the-plugins-in-project), you miss the `file://` prefix and it should be:
```toml
[tool.pdm]
plugins = [
    "-e file:///local/path/projects/plugins",
]
```

Can you try with it ?

**Comment by ariadnafe** [comment]
Solved! Thanks :)

**Comment by prudnikov** [comment]
We've got the same errorwith pdm 2.14.0. We rolled pdm back to 2.13.2 and it works.

**Comment by ariadnafe** [comment]
Hello, thank you for your fix. However for us is still failing

**Comment by frostming** [comment]
> Hello, thank you for your fix. However for us is still failing

remove the .pdm-plugins directory and try again with the main branch

**Comment by ariadnafe** [comment]
Yes yes, of course I did it. I event created a new fresh virtual machine and did everything from scratch, and still the same error...

**Comment by frostming** [comment]
did you get a chance to check the files installed under pdm-plugins site-packages? especially check if the .pth files are installed correctly
