### ISSUE TITLE
Incorrect keyring service name when setting index username explicitly

### ISSUE THREAD

**Issue by pineapple-pokopo** [pdm-project/pdm#2822]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce
Trying to install a package from a Google Artifact Registry (GAR) PyPi mirror. Since I don't have access to the PDM environnment, I've installed `keyring` and `keyrings.google-artifactregistry-auth` globally to facilitate authentication to GAR.

`pyproject.toml`

```
[project]
name = "test"
requires-python = "==3.11.*"
dependencies = [
    "click",
]

[[tool.pdm.source]]
name = "pypi"
url = "https://europe-west4-python.pkg.dev/<PROJECT>/<REPO>/simple/"
```

Executing `pdm install -vv` then fails:

```
Synchronizing working set with resolved packages: 1 to add, 0 to update, 0 to remove

unearth.collector: Collecting links from https://europe-west4-python.pkg.dev/<PROJECT>/<REPO>/simple/click/
unearth.auth: Found index url https://europe-west4-python.pkg.dev/<PROJECT>/<REPO>/simple/
unearth.auth: Found index url https://europe-west4-python.pkg.dev/<PROJECT>/<REPO>/simple/
unearth.auth: Getting password from keyring CLI for __token__@https://europe-west4-python.pkg.dev/<PROJECT>/<REPO>/simple/
unearth.auth: Found credentials in keyring for europe-west4-python.pkg.dev
unearth.auth: 401 Error, Credentials not correct for https://europe-west4-python.pkg.dev/<PROJECT>/<REPO>/simple/click/
```

which is expected because Google Artifact Registry expects `oauth2accesstoken` as username.

So, I've updated the `[[tool.pdm.source]]` section in `pyproject.toml` to include the username:

```
[[tool.pdm.source]]
name = "pypi"
url = "https://europe-west4-python.pkg.dev/<PROJECT>/<REPO>/simple/"
username = "oauth2accesstoken"
```

Running `pdm install -vv` fails again with the following:

```
Synchronizing working set with resolved packages: 1 to add, 0 to update, 0 to remove

unearth.collector: Collecting links from https://europe-west4-python.pkg.dev/<PROJECT>/<REPO>/simple/click/
unearth.auth: Getting password from keyring CLI for oauth2accesstoken@pdm-pypi-pypi
unearth.auth: Found index url https://europe-west4-python.pkg.dev/<PROJECT>/<REPO>/simple/
unearth.auth: Getting password from keyring CLI for oauth2accesstoken@pdm-pypi-pypi
unearth.auth: Found index url https://europe-west4-python.pkg.dev/<PROJECT>/<REPO>/simple/
unearth.auth: Getting password from keyring CLI for __token__@https://europe-west4-python.pkg.dev/<PROJECT>/<REPO>/simple/
unearth.auth: Found credentials in keyring for europe-west4-python.pkg.dev
unearth.auth: 401 Error, Credentials not correct for https://europe-west4-python.pkg.dev/<PROJECT>/<REPO>/simple/click/
```

Note that keyring CLI is now queried for `oauth2accesstoken@pdm-pypi-pypi`, but the `pdm-pypi-pypi` service name is unknown to `keyrings.google-artifactregistry-auth`.

## Actual behavior

keyring CLI queried for `oauth2accesstoken@pdm-pypi-pypi`

## Expected behavior

keyring CLI queried for `oauth2accesstoken@https://europe-west4-python.pkg.dev/<PROJECT>/<REPO>/simple/`

## Environment Information

```bash
PDM version:
  2.14.0
Python Interpreter:
  /Users/<redacted>/.venv/bin/python (3.11)
Project Root:
  /Users/<redacted>
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.8",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "23.4.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 23.4.0: Fri Mar 15 00:19:22 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8112",
  "python_full_version": "3.11.8",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}
```

Related to https://github.com/frostming/unearth/issues/102, but after further investigation I think this is an issue in PDM rather than in `unearth`.

**Comment by frostming** [comment]
This should corresponds to this piece of code: 
https://github.com/frostming/unearth/blob/13609ac4e5afbe2e7e52565b69f436c17db85b0d/src/unearth/auth.py#L245-L253

First we look for credentials with `username@netloc`, if not found then `username@url`

Can you check why it doesn't show in the logs?

**Comment by frostming** [comment]
This was fixed by https://github.com/frostming/unearth/releases/tag/0.15.2

Please upgrade it and try again

**Comment by pineapple-pokopo** [comment]
Upgraded to `unearth` to v0.15.2 and tested successfully! Many thanks!
