### ISSUE TITLE
How to limit concurrency on packages installation?

### ISSUE THREAD

**Issue by stepanselyuk** [pdm-project/pdm#2823]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

```
Hello!

How to limit concurrency on package installation? If multiple packages require building/compiling then it takes too much from microcomputers like Raspberry Pi Zero 2W. I want to know if there is a way to set like --jobs=1 parameter, so PDM will install packages 1 by one. I used cgroups resources limiting for this (especially disk i/o), but still, I see multiple sub-processes competing for resources, and usually in D state.

One way of fixing I see is to deploy with empty requirements and use `pdm add ...` to install packages one by one.

![image](https://github.com/pdm-project/pdm/assets/2071269/09f7c1a3-d4e7-499c-b24f-6d7cc50c2d2c)

![image](https://github.com/pdm-project/pdm/assets/2071269/e6b6c10f-4a82-4059-916d-14ab531221cd)

**Comment by noirbizarre** [comment]
Hello 👋🏼 

You can already disable concurrency with the `install.parallel` setting or the `PDM_INSTALL_PARALLEL` environment variable cf. https://pdm-project.org/en/latest/reference/configuration/#available-configurations
