### ISSUE TITLE
Make log dir creation optional 

### ISSUE THREAD

**Issue by pgjones** [pdm-project/pdm#2825]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

In 1d370a323840a3f41288facb14af82eae52c7f45 https://github.com/pdm-project/pdm/blob/main/src/pdm/core.py#L182 was introduced which invokes `os.makedirs(self.ui.log_dir, exist_ok=True)`. I like to run pdm within a docker container as the user nobody which does not have a home directory which with PDM >= 2.13 fails with `[Errno 13] Permission denied: '/nonexistent'` as the user nobody does not have a home directory.

Pre 2.13 PDM had no need to create or use this directory, therefore could this be made optional?

**Comment by frostming** [comment]
> Pre 2.13 PDM had no need to create or use this directory

Pre 2.13 it saves logs into tmp folder. But note that with the fix #2827 you may still need to point `log_dir` config to another existing directory to make sure the log files work correctly.

**Comment by pgjones** [comment]
Thanks!

Would this likely be in 2.14.1 when released?
