### ISSUE TITLE
Installing PDM fails on windows

### ISSUE THREAD

**Issue by Badg** [pdm-project/pdm#2860]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

Related to #2153: when attempting install on windows (win10, powershell 7.4.2, within Windows Terminal 1.19.10821.0), the command fails. 

```
MethodException: Cannot convert argument "bytes", with value: "...",
for "GetString" to type "System.Byte[]": "Cannot convert value "..." to type "System.Byte[]".
Error: "Cannot convert value "..."  was not in a correct format.
```

(I may have missed some parts of the error report -- each of those ``...`` is a complete copy of the install file, printed out in the terminal, all in the same color, so it's really easy to miss which bits are error message and which bits are script).

## Steps to reproduce

All I did was open up powershell and follow the install instructions:

```
[System.Text.Encoding]::UTF8.GetString((Invoke-WebRequest -Uri https://pdm-project.org/install-pdm.py).Content) | python -
```

## Actual behavior

Parsing fails. PDM  not installed.

## Expected behavior

Parsing succeeds. PDM installed! 🎉 

Fix (I'll open up a PR in just a sec):

```
(Invoke-WebRequest -Uri https://pdm-project.org/install-pdm.py -UseBasicParsing).Content | python -
```

**Comment by Badg** [comment]
Ahhhh wait, went to update the docs and saw that the latest version of them has the ``-UseBasicParsing`` flag. **However, not everyone will have ``py`` set up to alias to ``python``** -- for example, when I try to run the version in the latest docs, I see:

```
C:\...> (Invoke-WebRequest -Uri https://pdm-project.org/install-pdm.py -UseBasicParsing).Content | py -
py: The term 'py' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

I'll open a PR to change py -> python, but... I mean, it's such a small change, dunno if it's worth it.

**Comment by frostming** [comment]
> However, not everyone will have `py` set up to alias to `python`

It's not an alias, it is a launcher installed with the official CPython installer.

If you are using pyenv you don't have it.

**Comment by pawamoy** [comment]
I'd say we could add a note in the docs to let users know that they should install the optional launcher if the command errors with 

> The term 'py' is not recognized as a name of a cmdlet, function, script file, or executable program.

**Comment by frostming** [comment]
> For what it's worth, poetry install docs specify `python`, not `py`.

No, it was actually where I copied the command from

![image](https://github.com/pdm-project/pdm/assets/16336606/6668c331-b81f-4645-afea-567516f1d2f9)

Maybe we can add the notice same as Poetry, can you adjust your PR?

**Comment by Badg** [comment]
> No, it was actually where I copied the command from

Huh. Indeed. That notice may have been enough for me.
