### ISSUE TITLE
Feature request/proposal to expose project.scripts in output of `pdm show`

### ISSUE THREAD

**Issue by adamliter** [pdm-project/pdm#2879]
## Is your feature/enhancement proposal related to a problem? Please describe.

It might be nice to expose whether (and which) `project.scripts` a Python project defines in its `pyproject.toml` via `pdm show` (e.g., `pdm show --scripts` or `pdm show --project-scripts`). This would be useful in the context of CI to be able to check that a particular package exposes a script with the expected name that can then be called later in the CI step with `pdm run my_script`.

## Describe the solution you'd like

**pyproject.toml**

```toml
[project.scripts]
my_script = my_package:my_module:main
```

**using `pdm` to check output in CI**

```sh
$ pdm show --project-scripts
["my_script"]
# or perhaps [{"my_script": "my_package.my_module:main"}]
```

Do you see utility/interest in this feature? If so, I'm happy to take a shot at it.

**Comment by frostming** [comment]
How would you implement it if user requests a pypi package like `pdm show <package> --scripts`?

**Comment by adamliter** [comment]
Hmm, good question. I guess it's not really possible since this information isn't exposed via the PyPI JSON API. So the options seem like they would be:

1. Download it to a cache in the background and then check with `importlib.metadata` from the cache ... ?
2. Just error out for packages that aren't installed locally

Maybe the second option is best, but then maybe it's worth making it a separate command or something (e.g., `pdm package-scripts` ... ?). Also understand if this is something you'd rather not add to `pdm`.
