### ISSUE TITLE
Unable to download non-py files

### ISSUE THREAD

**Issue by lin-goo** [pdm-project/pdm#2889]
When I install a private repository using the pdm add git+http://xxx method, I can't get the non-py files to download.

Please help me !!!

@frostming

**Comment by frostming** [comment]
That's a bit noisy to report an issue like this.

You don't provide the basic information like what you are trying to do, how can I help you?

**Comment by frostming** [comment]
I'll close this first so that you can understand how to report an issue properly and will reopen if it's improved.
