### ISSUE TITLE
Skip using .netrc file on errors rather than raising

### ISSUE THREAD

**Issue by ZacEllis** [pdm-project/pdm#2916]
## Is your feature/enhancement proposal related to a problem? Please describe.

I'm doing python development in a managed environment where a [netrc file](https://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-file.html) was made with incorrect permissions. This caused PDM to predictably throw an error: 
```
> pdm install -d --no-self
STATUS: Resolving packages from lockfile...
INFO: python.use_venv is on, creating a virtualenv for this project...
Virtualenv is created successfully at <path>
Synchronizing working set with resolved packages: 38 to add, 0 to update, 0 to remove

  ✖ Install setuptools 69.1.0 failed

See /root/.local/state/pdm/log/pdm-install-4esjt8u5.log for detailed debug log.
[NetrcParseError]: ~/.netrc access too permissive: access permissions must restrict access to only the owner
```
But I noticed that installs using vanilla pip succeeded, ignoring the incorrectly permissioned netrc file. 

## Describe the solution you'd like

To make adopting PDM easier, PDM should exhibit the same behaviour as pip/requests when encountering errors trying to read auto-login information from a netrc file. 
https://github.com/pypa/pip/blob/911bf995927aaf56993887225917ba7200df4e7c/src/pip/_vendor/requests/utils.py#L250 
https://github.com/psf/requests/blob/0e322af87745eff34caffe4df68456ebc20d9068/src/requests/utils.py#L250

**Comment by frostming** [comment]
Fixed on upstream `unearth`, please upgrade your dependencies.
