### ISSUE TITLE
Auto show detail when step holding

### ISSUE THREAD

**Issue by waketzheng** [pdm-project/pdm#2923]
## Is your feature/enhancement proposal related to a problem? Please describe.

<img width="920" alt="image" src="https://github.com/pdm-project/pdm/assets/35413830/5fd7ae03-461b-4b01-9438-0e96218340ff">
When executing `pdm add ultralytics` output stays resolving for a long time, it make beginner doubt that whether the process is dead or still running.

By comparison, `poetry add ultralytics` show the increasing cost time, and `pip install ultralytics` show the download progressbar, so I know that they are still running.

## Describe the solution you'd like

If one step cost too much time without any new output, print more detail to let me know what's it doing now.

Or show a progressbar to tell how long to wait.

**Comment by yngvem** [comment]
If you want more information on what PDM is doing, then you can add `-v` to the command (it's relatively common for CLIs to have a `-v` option, short for verbose).
