### ISSUE TITLE
In monorepo, sibling dependencies can result in unintended absolute paths.

### ISSUE THREAD

**Issue by sgyorkos** [pdm-project/pdm#2926]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. Set up a monorepo like so: https://github.com/sgyorkos/monorepo-example
2. Run `pdm install` in the directory `pkg-first`. If needed, delete the `pdm.lock` file first.
3. Observe that the lock file contains absolute paths even though the pyprojects for each project point at `${PROJECT_ROOT}`

## Actual behavior

The lock file contains absolute paths even though the dependencies in the pyprojects for each project point at `${PROJECT_ROOT}`

## Expected behavior

The lock file should contain relative paths that include `${PROJECT_ROOT}`. Manually updating the fields in the lock file proves that `pdm sync` will work with `${PROJECT_ROOT}` in the path.

## Environment Information

```bash
PDM version:
  2.15.4
Python Interpreter:
  C:\Users\spwmg\OneDrive\Documents\projects\pdm-example-monorepo\.venv\Scripts\python.exe (3.12)
Project Root:
  C:/Users/spwmg/OneDrive/Documents/projects/pdm-example-monorepo
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.12.1",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "11",
  "platform_system": "Windows",
  "platform_version": "10.0.22631",
  "python_full_version": "3.12.1",
  "platform_python_implementation": "CPython",
  "python_version": "3.12",
  "sys_platform": "win32"
}
```

Note: In the repo above, I've included some possible changes to fix this issue to the candidates and backends model files. It will change the path from:
"pkg-core @ file:///C:/Users/spwmg/OneDrive/Documents/projects/pdm-example-monorepo/packages/pkg-second/../pkg-core"
to:
"pkg-core @ file:///${PROJECT_ROOT}/../pkg-second/../pkg-core"
Not the cleanest but should avoid weird path edge cases. Let me know if that looks useful.

**Comment by frostming** [comment]
Due to the backend-agnostic design of PDM, now it doesn't know packages other than the current project.
The intermediate dependency `pkg-core` is parsed by the backend to a PEP 508 requirement string, and PDM doesn't know what is behind. You can notice `pkg-second` is however locked as relative path correctly because it is specified in the current project `pkg-core`, so PDM knows how to convert the path back.

This is why we need #1505 . So closing it now to keep the issue tracker not distractive.

**Comment by frostming** [comment]
> Note: In the repo above, I've included some possible changes to fix this issue to the candidates and backends model files. It will change the path from: "pkg-core @ file:///C:/Users/spwmg/OneDrive/Documents/projects/pdm-example-monorepo/packages/pkg-second/../pkg-core" to: "pkg-core @ file:///${PROJECT_ROOT}/../pkg-second/../pkg-core" Not the cleanest but should avoid weird path edge cases. Let me know if that looks useful.

Thanks for that but it is hard to read what is changed. can you include a diff file?
