### ISSUE TITLE
Settings for plugins

### ISSUE THREAD

**Issue by KalleDK** [pdm-project/pdm#2930]
## Is your feature/enhancement proposal related to a problem? Please describe.

I would like to create a plugin for unasync to pdm. Though this requires a way to have settings in pyproject.yml

Should that be under
`[tool.unasync]`
or
`[tool.pdm.unasync]`
or
`[tool.pdm.plugin_settings.unasync]`

At the moment the schema "disallows" the last two [schema](https://json.schemastore.org/partial-pdm.json)

But the last two would be the easy way to get them via `project.get_setting('unasync')` [api](https://pdm-project.org/latest/reference/api/#pdm.project.core.Project.get_setting)

## Describe the solution you'd like

I'm not really attached to either, but I would love a section in the [docs](https://pdm-project.org/latest/dev/write/#write-your-own-plugin) descibing which of the three should be best practise

**Comment by frostming** [comment]
`[tool.pdm.unasync]` is preferred due to the reason you mentioned.

Ignore the schema now, maybe someone should make a PR to loose it.
