### ISSUE TITLE
adding a "shell" command in CLI

### ISSUE THREAD

**Issue by quertenmont** [pdm-project/pdm#2936]
## Is your feature/enhancement proposal related to a problem? Please describe.

It's not really related to a problem, but it's a nice to have

## Describe the solution you'd like

I am coming from "poetry" world and I must say that I am missing a lot the "poetry shell" command,
would be nice to have a "pdm shell" equivalent command that setup the venv if it doesn't exist and activate the environment in a single command.

I know, I can achieve the same results with a couple of verbose "pdm venv" commands.... but I am a lazy python developper and I like the simplicity of "pdm shell" :-)

What do you think ?

**Comment by frostming** [comment]
This should be an enough explanation: https://pdm-project.org/en/latest/usage/venv/#activate-a-virtualenv
