### ISSUE TITLE
Does pdm have any plans to support local env, without using venv or pep582?

### ISSUE THREAD

**Issue by kebyn** [pdm-project/pdm#2939]
Use in `multi-stage-dockerfile`
Develop in `vscode dev containers`
Similar options for other software
https://python-poetry.org/docs/configuration/#virtualenvscreate
https://rye.astral.sh/guide/pyproject/#toolryevirtual

**Comment by frostming** [comment]
Did you try `pdm install --global -p .`?

**Comment by kebyn** [comment]
There are some problems with the `--global` parameter.

The `init` command still creates a global virtual environment.

The `add` command does not update pyproject.toml.

The `install` command still installs to the venv in the current directory.

**Comment by frostming** [comment]
> The `add` command does not update pyproject.toml.
> 
> The `install` command still installs to the venv in the current directory.

These are all not what it should be, please give reproduction steps

**Comment by kebyn** [comment]
Sorry, this is my problem

Projects that only use `--global` parameter are in `~/.config/pdm/global-project`
Projects that only use `--project` parameter are in the directory specified by `--project`

When both `--global` parameter and `--project` parameter, the system environment package and the directory `pyproject.toml` specified by `--project` will be used

The prompt for executing the modification may need to be clearer. This place made me look for the wrong `pyproject.toml`
![image](https://github.com/pdm-project/pdm/assets/9145323/0e6c79f9-7795-4e03-9bb9-993facfbb781)

**Comment by frostming** [comment]
Clarifications are made by #2952
