### ISSUE TITLE
Either allow users to ignore the requires-Python flag or clearify the syntax of how requires-Python works

### ISSUE THREAD

**Issue by helios1014** [pdm-project/pdm#2941]
Everytime I run PDM add “insert path to whl file here” it  tells me that all dependencies do not work on the range of the project’s requires-Python. For example, numpy lists it’s requires-Python as >=3.9 and I entered >=3.0. I am currently using version 3.12 on my work computer. If I enter >=3.8, it still tells me the dependancies are wrong. Please clarify the syntax of requires-Python so I can either tell it to ignore the Python version requirements or at the very least understand what >= means as you seem to be using it in an unintuitive manner.

**Comment by pawamoy** [comment]
If your project claims to support all Python versions above 3.0 (or 3.8) included, while Numpy claims to support only versions 3.9 included, that's a mismatch, and PDM cannot resolve Numpy. Your current Python version (3.12 here) has nothing to do with that.

Please read https://pdm-project.org/en/latest/usage/project/#set-requires-python-value. I hope this will make things more clear :slightly_smiling_face: You are not the first one having trouble with the concept, but I am myself not sure how we could make it more clear.

Anyway, nothing actionable for PDM here, closing! Feel free to comment furter.
