### ISSUE TITLE
Failed to collect links from private PyPi repository: Client Error(404): Not Found

### ISSUE THREAD

**Issue by b-morgenthaler** [pdm-project/pdm#2942]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

- Use/prepare a custom/private pypi (simple) repository where pdm is **not** available.
- Configure pdm to use the custom/private as primary pypi source
- Init a sample/empty project
- Work with pdm (e.g. adding a dependency by `pdm add requests` from custom/private repository)

## Actual behavior

The warning is printed

`Failed to collect links from https://private_repository/pypi_default/simple/pdm/: Client Error(404): Not Found`

EDIT: When building with the pdm-backend then a similar message is shown:

`unearth.collector: Failed to collect links from https://private_repository/pypi_default/simple/pdm-backend/: Client Error(404): Not Found`

## Expected behavior

No warning is printed

## Environment Information

```PowerShell
PS D:\git\python_templates\template-default> pdm info
PDM version:
  2.15.4
Python Interpreter:
  D:\git\python_templates\template-default\.venv\Scripts\python.exe (3.10)
Project Root:
  D:/git/python_templates/template-default
Local Packages:

Failed to collect links from https://private_repository/pypi_default/comlet_pypi_default/simple/pdm/: Client Error(404): Not Found
```

```PowerShell
PS D:\git\python_templates\template-default> pdm info --env
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.14",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19045",
  "python_full_version": "3.10.14",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "win32"
}
Failed to collect links from https://private_repository/pypi_default/comlet_pypi_default/simple/pdm/: Client Error(404): Not Found
```

**Comment by frostming** [comment]
Just turn off `check_update` config

**Comment by b-morgenthaler** [comment]
@frostming Unfortunately, `check_update` is not allowed in the local config which is important if you want to share this configuration with others working on the same project/repository

`[ValueError]: Config item 'check_update' is not allowed to set in project config.`
