### ISSUE TITLE
[Feature Request] Take "requires-python" into account for installing and using Python interpreter

### ISSUE THREAD

**Issue by o-moe** [pdm-project/pdm#2943]
## Motivation
- Streamline / automate the set-up process for new local virtual environments.
- Use a different Python interpreter for managing the project with pdm and developing the project.

## Use case
An existing project using pdm for dependency management is cloned/cleaned by a development team member (no .venv and .pdm-python available). The pyproject.toml already defines a (minimum Python version for the project) by the `requires-python`attribute.

## Feature request
Let `pdm python install` and `pdm use` respect the (minimum) Python version given in the pyproject.toml file (if existing) as default. Prefer cPython interpreters for downloading and using.
Additionally, add a `--automatic-install` option to `pdm use` that automatically installs the default version (from pyproject.toml) or from the user provided version.

## Expected behavior
- The user can work with `pdm python install` and `pdm use` as before if the Python version is provided.
- If a pyproject.toml is already existing that defines a (minimum) Python version, the user can automate installation and usage of this version by `pdm use --automatic-install` without any further interaction.
  - I don't mind having a `-y`option for `--automatic-install` 

### Discussed in https://github.com/pdm-project/pdm/discussions/2938

<div type='discussions-op-text'>

<sup>Originally posted by **o-moe** June 12, 2024</sup>
Hi everyone,

sorry if this is obvious but I am new to pdm and my knowledge about Python in general is limited.

Recently, I started looking into pdm to manage my project - and it look very promising. Thanks to you @frostming.
The project sources are under version control. When I follow pdm's documentation recommendation, I will commit pyproject.toml, pdm.toml and pdm.lock to have the environment reproducible across members working with my project.

But what makes me wonder is, how do I make sure that everybody uses the same Python interpreter that the project is based on (and has been initialized)? If the members just use `pdm use` after their initial checkout, they can use whatever version is available on their system. If the members use `pdm python install` prior to `pdm use`, they can choose whatever version they like.
I trust the members of my project but I would like to have the Python interpreter version controlled by the same principles like I control the dependencies and configuration with the pyproject.toml and the pdm.lock file, i.e. reproducible and failure-safe.

Am I missing something here? Is pdm supporting this use case and I just didn't realize it? Is this use case uncommon?

BTW: I also want the Python interpreter of the project being explicitly different  from the Python interpreter that pdm is using.

Thanks in advance for your thoughts.</div>

**Comment by frostming** [comment]
Sorry, can you explain how `requires-python` is not being respected?

The python selection has already been restricted by it: https://github.com/pdm-project/pdm/blob/8c9064c00098223d25ba84783836f0080baf3856/src/pdm/cli/commands/use.py#L49-L52

**Comment by o-moe** [comment]
Regarding `pdm python install`: I don't see any restrictions re-using the Python interpreters downloaded by pdm with different projects. In fact, I see this beneficial.
The point is that `pdm use` without any python version given, shall "try" to use the `requires-python` version from pyproject.toml if available and no other version has been given by the user. For this, it shall also prefer pdm installed versions in this scenario. If no version is available, it may fail. With the additional and optional `--automatic-install` option, `pdm use` may delegate to `pdm python install` to automatically install the `requires-python`version if no pdm installed version has been found to satisfy the (minimum) Python version. 
With this, one could streamline the "setting up the correct Python interpreter for a given project" process which is a source of many issues if more people work on the same project (and they set up different python versions locally and use features that they should not according to the minimum Python version required).
Additionally, I see this benefitial for a CI/CD context where the local environment gets installed every single run. Currently, the version used for `pdm python install` and `pdm use` needs to be stored elsewhere (e.g. an envrionment variable) and needs to be kept in sync with changes from pyproject.toml.

**Comment by slashtechno** [comment]
I think this would make usage with virtual environments better as well. Otherwise, I think the only solution to prevent the need for `.pdm-python` to be created after every clone would be to remove it from `.gitignore` and commit it with a relative path like `.venv/bin/python`.

**Comment by frostming** [comment]
It doesn't make any sense to share a *path* between machines, or host and containers.

**Comment by o-moe** [comment]
I agree. That’s why I think this feature request is so important. Since the needed information is already available in pyproject.toml, it would make things way easier for provisioning the Python interpreter in multi-user or CI/CD use-cases. Currently, the Python interpreter version to be installed and used by pdm during development is completely orthogonal to a project’s configuration.

**Comment by o-moe** [comment]
Another reason why this is a good idea to have: this PEP draft comes from the same motivation: https://peps.python.org/pep-0711/

**Comment by ebc-conscia** [comment]
This would be great, especially if I am to convert my colleagues to PDM.

**Comment by o-moe** [comment]
To keep things going, I created a protoyp for `pdm python install` here: https://github.com/pdm-project/pdm/compare/main...o-moe:pdm:feature/allow_pdm_py_install_to_eval_min_required_py_version_from_pyproject_toml

@frostming Can you please take a look if this is pointing into the right direction? I have a professional dev background but am not coming from Python. So, this might not be "pythonic"

**Comment by frostming** [comment]
> To keep things going, I created a protoyp for `pdm python install` here: [main...o-moe:pdm:feature/allow_pdm_py_install_to_eval_min_required_py_version_from_pyproject_toml](https://github.com/pdm-project/pdm/compare/main...o-moe:pdm:feature/allow_pdm_py_install_to_eval_min_required_py_version_from_pyproject_toml)

LGTM, just some nitpicks I can left them in the review comments

**Comment by o-moe** [comment]
@frostming I finalized the implementation in my feature branch. If you still think it fits, I will create some unit tests and create a pull request.

**Comment by frostming** [comment]
> @frostming I finalized the implementation in my feature branch. If you still think it fits, I will create some unit tests and create a pull request.

Please do.

**Comment by frostming** [comment]
but the lockfile is only effective when developing pdm(and only if you setup the dev env using pdm)

**Comment by frostming** [comment]
oh I know what you mean. could you make a PR to update the locked version and we can fix the ci failures

**Comment by o-moe** [comment]
@frostming I updated my fork with main and did a `pdm install` and with it the newest version of pbs_installer was used:

```
(.venv) bm@macbookairvonbjoern pdm % pdm install
Synchronizing working set with resolved packages: 0 to add, 1 to update, 0 to remove

  ✔ Update pbs-installer 2024.3.27 -> 2024.4.24 successful
```

this newer version is also referred to in pdm.lock (and now I also see the `build_dir` arg that you were discussing in the other issue).

According to git, the pdm lock has no changed, so it came with main. Do you want me to downgrade to the version that has been used when I implemented my PR earlier?
