### ISSUE TITLE
a way to specify dependencies that are both `build-system.requires` and `pdm.dev-dependencies`

### ISSUE THREAD

**Issue by DetachHead** [pdm-project/pdm#2947]
## Is your feature/enhancement proposal related to a problem? Please describe.

i have a bunch of dependencies in `build-system.requires` that are used in my `pdm_build.py` script. however if i don't also include them in `tool.pdm.dev-dependencies` i get type errors on the imports because those modules aren't actually installed to my main venv

this means i need to duplicate the dependencies in both sections to work around the issue:

```toml
[tool.pdm.dev-dependencies]
dev = [
    "pdm-backend>=2.3.0",
    "typing_extensions>=4.12.2",
    "docify @ git+https://github.com/DetachHead/docify@patch-1",
    "libcst>=1.4.0",
]

[build-system]
requires = [
    "pdm-backend>=2.3.0",
    "typing_extensions>=4.12.2",
    "docify @ git+https://github.com/DetachHead/docify@patch-1",
    "libcst>=1.4.0",
]
```

## Describe the solution you'd like

a way to specify `build-system.requires` dependencies that should also be installed as dev dependencies. perhaps something like this:

```toml
[tool.pdm.build-system-dev-dependencies]
dev = [
    "pdm-backend>=2.3.0",
    "typing_extensions>=4.12.2",
    "docify @ git+https://github.com/DetachHead/docify@patch-1",
    "libcst>=1.4.0",
]
```

**Comment by frostming** [comment]
Not going to support this, you can do it by using a custom build backend
