### ISSUE TITLE
option to only install dev dependencies

### ISSUE THREAD

**Issue by DetachHead** [pdm-project/pdm#2949]
## Is your feature/enhancement proposal related to a problem? Please describe.

i have a dev dependency group that does not depend on the prod dependencies being installed.

## Describe the solution you'd like

an option to only install dev dependencies:
```
pdm install --group=dev --only-dev
```

**Comment by frostming** [comment]
pdm install --no-default -G dev

**Comment by DetachHead** [comment]
thanks, i was looking through the docs for ages not sure how i missed that
