### ISSUE TITLE
Support for .pdm-python in vscode extension

### ISSUE THREAD

**Issue by KalleDK** [pdm-project/pdm#2955]
I've created a feature request under the vscode extension, but it needs upvotes within 60 days to not automaticly getting closed

https://github.com/microsoft/vscode-python/issues/23629#issuecomment-2173887823

**Comment by ebc-conscia** [comment]
Yes, it would be great for VS Code to pick up the venv location from .pdm-python :)

**Comment by frostming** [comment]
The issue has been tracked in VSCode, closing this now
