### ISSUE TITLE
A solution for `dev` dependency groups that depend *on each other*

### ISSUE THREAD

**Issue by edward-petersen-cynn** [pdm-project/pdm#2960]
## Is your feature/enhancement proposal related to a problem? Please describe.

There is no problem - this is simply an enhancement that I think could improve developer's lives with little to no change for teams that do not need this functionality

## Describe the solution you'd like

On our teams we tend to have a few default `dev` dependency groups. We love using PDM because `dev` dependencies are superior to "extras", as we do not expose our development process to the production distribution package: `pip install foobar[test]` isn't something we want end users to use and PDM solves that nicely with `dev` dependency groups.

But, as scientists, we have quite a few groups for the different experiment types. Which means the different kinds of developers often have different development environment needs. We capture those in `dev` groups such as data-sci, engineer, etc. But of course, there are dependencies we have in common and we capture those in the `dev` "parent" group. Meanwhile, our CICD pipelines have needs and we capture those in `test`, but of course some dependencies from that `dev` group are still needed.

Our solution at the moment is, of course: `pdm install --dev --groups dev,engineer` or the like. And on the build server, we have that codified, so _it_ never makes a mistake. But, every so often we have a new developer (or someone is up late and tired!) and they don't realize they need to include the `dev` group.

What I am proposing is a simple hierarchy where, in this example, the `engineer` group would "need" the `dev` group. And the installation command could be `pdm install --dev --groups engineer` and it would just know to also include the `dev` group. A bit meta, I guess.

Configuration would possibly look something like this:
```
[tool.pdm.dev-dependencies]
dev = ["important", "libs"]
engineer = [dev, "other", "important", "things"]
```
Or, if in-line would be tough to discern between groups defined and dependencies that need fetching, something like this:
```
[tool.pdm.dev-dependencies-needs]
enginner = ["dev"]
```

I am, as you might suspect, a devops engineer myself, and I would be willing to make this contribution to the code base. But I wanted to offer it up so folks could poke holes in it or tell me why it couldn't be done or would confuse things in ways I don't know because I am not intimate with the code base.

**Comment by frostming** [comment]
Just use self-referencing extra dependency

```toml
engineer = ["mypackage[dev]"]
```

but notice that you must have `distribution = true ` and a project name to refer to

**Comment by edward-petersen-cynn** [comment]
Can you point me to the documentation for `distribution`? I can't seem to find it on the documentation website. What I want to avoid is exposing our dev dependencies as traditional "extras," which this looks a lot like.

**Comment by frostming** [comment]
look at your pyproject.toml it's a config item. and the dependencies are still under dev group

**Comment by edward-petersen-cynn** [comment]
> look at your pyproject.toml it's a config item. and the dependencies are still under dev group

Yes, I know it is a configuration that goes in my `pyproject.toml` file. I was looking for the documentation on the PDM [documentation website](https://pdm-project.org/en/latest/) so I could know what effect `True` and `False` have on this configuration. And possibly what other config values interact with it. But I can't seem to find anything there.

**Comment by pawamoy** [comment]
@edward-petersen-cynn you're probably looking for https://pdm-project.org/en/latest/usage/project/#library-or-application.
