### ISSUE TITLE
`pdm python install` fails to install python3.7 even though it is listed by `pdm python install --list`

### ISSUE THREAD

**Issue by xulongwu4** [pdm-project/pdm#2970]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Ran `pdm python install --list`, and I got the following output:

```
cpython@3.12.2
cpython@3.12.1
cpython@3.12.0
cpython@3.11.8
cpython@3.11.7
cpython@3.11.6
cpython@3.11.5
cpython@3.11.4
cpython@3.11.3
cpython@3.11.1
cpython@3.10.13
cpython@3.10.12
cpython@3.10.11
cpython@3.10.9
cpython@3.10.8
cpython@3.10.7
cpython@3.10.6
cpython@3.10.5
cpython@3.10.4
cpython@3.10.3
cpython@3.10.2
cpython@3.10.0
cpython@3.9.18
cpython@3.9.17
cpython@3.9.16
cpython@3.9.15
cpython@3.9.14
cpython@3.9.13
cpython@3.9.12
cpython@3.9.11
cpython@3.9.10
cpython@3.9.7
cpython@3.9.6
cpython@3.9.5
cpython@3.9.4
cpython@3.9.3
cpython@3.9.2
cpython@3.9.1
cpython@3.9.0
cpython@3.8.18
cpython@3.8.17
cpython@3.8.16
cpython@3.8.15
cpython@3.8.14
cpython@3.8.13
cpython@3.8.12
cpython@3.8.11
cpython@3.8.10
cpython@3.8.9
cpython@3.8.8
cpython@3.8.7
cpython@3.8.6
cpython@3.8.5
cpython@3.8.3
cpython@3.8.2
cpython@3.7.9
cpython@3.7.7
cpython@3.7.6
cpython@3.7.5
cpython@3.7.4
cpython@3.7.3
cpython@3.7.1
pypy@3.10.13
pypy@3.10.12
pypy@3.9.18
pypy@3.9.17
pypy@3.9.16
pypy@3.9.15
pypy@3.9.12
pypy@3.9.10
pypy@3.8.16
pypy@3.8.15
pypy@3.8.13
pypy@3.8.12
pypy@3.7.13
pypy@3.7.12
pypy@3.7.10
pypy@3.7.9
```

cpython 3.7 is listed as availabe interpreter version to install.

However, when I tried `pdm python install 3.7.9 -v`, I got the following error:

```
Traceback (most recent call last):
  File "/home/xxx/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/xxx/.local/share/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 358, in main
    return core.main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/.local/share/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 276, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/home/xxx/.local/share/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 271, in main
    self.handle(project, options)
  File "/home/xxx/.local/share/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 207, in handle
    command.handle(project, options)
  File "/home/xxx/.local/share/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/commands/python.py", line 100, in handle
    self.install_python(project, options.version)
  File "/home/xxx/.local/share/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/commands/python.py", line 117, in install_python
    ver, python_file = get_download_link(version, implementation=implementation, arch=arch)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/.local/share/pipx/venvs/pdm/lib/python3.11/site-packages/pbs_installer/_install.py", line 66, in get_download_link
    raise ValueError(
ValueError: Could not find a version matching version='3.7.9', implementation=cpython
```

## Actual behavior

Can not install python3.7 even though `pdm python install --list` lists it as avaiable.

## Expected behavior

I expect that I can install any interpreter listed by `pdm python install --list`.

## Environment Information

Output of `pdm info`:

```
PDM version:
  2.15.1
Python Interpreter:
  /home/xxx/.local/share/pdm/python/cpython@3.12.2/bin/python3 (3.12)
Project Root:
  /home/xxx/.config/pdm/global-project
Local Packages:
```

**Comment by frostming** [comment]
there might not be a version that matches your architecture

**Comment by xulongwu4** [comment]
@frostming I am using a linux machine with an x86_64 cpu. I would assume this is a very common set up.

I looked into the source code of the `install_python()` method. It calls `get_download_link` with three arguments: version, implementation and arch. On the other hand, `get_download_link` accepts two more arguments with default values: `platform` and `build_dir`. The problem is caused by `build_dir`. Since `install_python()` does not pass in a `build_dir`, the `build_dir` is defaulted to `False`, and `get_download_link` will fail when the requested python needs to use the `build/` directory from indygrep builds.

 In my case, python 3.7.6 matches my architecture, but it requested to use the `build` directory, which means the urls looks like `('linux', 'x86_64', False): ('https://github.com/indygreg/python-build-standalone/releases/download/20200216/cpython-3.7.6-linux64-20200216T2303.tar.zst', None)`, where the `False` is supposed to match `not build_dir`. Since `build_dir` is `None`, `False` does not match `not build_dir`, and pdm reports that it can't find a matched implementation.

**Comment by o-moe** [comment]
@xulongwu4 I recently looked into this part of the source code as well, and I cannot follow your explanation as to why the installation would fail. The current version of PDM's `get_download_link` has not `build_dir`. ìnstall_python` still does not pass all arguments to `get_download_link` but the one missing is the current platform which defaults to your current platform.

I saw that you are using pdm version 2.15.1. Maybe it's worth updating to latest and see if your observation is already fixed?

**Comment by o-moe** [comment]
@frostming shouldn't the `install_python` method then also only get the download link from versions with `build_dir` set to true? Only because `pdm python install --list` doesn't show it, one could easily specify a version for `pdm python install`
