### ISSUE TITLE
Unable to install PyTorch with CUDA

### ISSUE THREAD

**Issue by lingkerio** [pdm-project/pdm#2981]
When I use `pdm add torch` to install PyTorch, it installs version 2.3.1+cpu. However, I want to install the GPU version, and I haven't found any command that helps me specify the GPU version. Is there a different command or option I should use to install PyTorch with GPU support?

![图片](https://github.com/pdm-project/pdm/assets/112792583/402edc5b-a18f-4373-9258-541c71c374b9)
![图片](https://github.com/pdm-project/pdm/assets/112792583/5e66d6d8-e813-4ec9-9a06-3575dc8d34f2)

**Comment by pawamoy** [comment]
This is not relevant to PDM, moving to Q/A :slightly_smiling_face:
