### ISSUE TITLE
Specific-dependency specific-operating system

### ISSUE THREAD

**Issue by simonprovost** [pdm-project/pdm#2987]
## Is your feature/enhancement proposal related to a problem? Please describe.
Hi folks! First thanks so much for such a great package manager.

We are ready to publish a couple of our libraries, one of which has a unique need. We forked, edited, and hosted a library on Github, however I do not understand how we may be legitimate publishing it on Pipy due to the limited changes. Nonetheless, this library's modification serves as the foundation for many of our algorithms in our main library (machine learning focused). As of now, I have the wheel for MacOS and Linux under two versions of Python CI built; however, I do not see any method through PDM or Pyproject to state that this dependent with a specific wheel link is only installable if the operating system is Linux, and another wheel only on Darwin (MacOS). (I have a link towards a wheel for each system and for each I have got two weel for the two python version we currently support (tested).

## Describe the solution you'd like

If there is a current functionality that allows so, my mistake, and I would appreciate hearing how to use it; if not, I believe this could be a significant improvement. For the time being, we are unable to publish our current primary library on Pipy because our only dependency that causes the issue is using a link that we set in a .env file using a script that sets the link to the right wheel based on the Python version and operating system identified.

**Comment by simonprovost** [comment]
Hi Pawamoy! Cheers for the prompt answer.

This is Scikit-Learn actually. When I tried to publish the deployed wheels, Twine and Hatch just told me that I could not because I could not publish into Scikit-learn, which is understandable. After trying two different methods, I assumed I could simply not publish to Pypi. Do you agree with that?

It actually is a fork of Scikit-learn to open ways to edit trees: https://github.com/neurodata/scikit-learn

Sorry I perhaps should not ask that here though! out of the scope..

**Comment by pawamoy** [comment]
> Sorry I perhaps should not ask that here though! out of the scope..

No worries :smile: But you're right, I'll close as out of scope :slightly_smiling_face: I'll let @frostming reopen if he thinks there's a feature worth implementing here.

**Comment by simonprovost** [comment]
> Kind of. You indeed cannot publish to the scikit-learn project on PyPI (you don't have the right to). But you can publish to PyPI with any other available name.

I guess I tried. Tried again since you commented, and keep having an error regarding the fact that I am publishing to Scikit-Learn despite having had changed the folder's name and everything in Setup.py. Yet the wheels built are still under scikit-learn name though.

> If you changed the distribution name in setup.py, make sure to clean your dist folder, rebuild your distributions (probably with python setup.py bdist_wheel), and upload these new distributions (bearing the new name you chose and that is available on PyPI.org) with Twine for example: twine upload -r pypi dist/*. You'll need to configure Twine (but I assume you already did that).

I am using a Github action that does the job of compiling, building the wheels, storing them as artefact and then downloading them to publish on Pypi so I presume cleaning the dist folder is done throughout the process anyway.

>  No worries 😄 But you're right, I'll close as out of scope 🙂 I'll let @frostming reopen if he thinks there's a feature worth implementing here.

I guess this is allright on my side thanks much!

I am going to seek help onto another Github repository, do not know which one yet!

Cheers so much @pawamoy !!

**Comment by pawamoy** [comment]
Yeah without seeing the code it's hard to say what goes wrong here and why the dists keep the previous name. Good luck in your investigation :smile:

**Comment by frostming** [comment]
The scikit-learn project seems using meson-build rather than setuptools and you need to edit the project name in `pyproject.toml` as well
