### ISSUE TITLE
Transient dependencies conflict resolution through nesting (similar to pnpm)

### ISSUE THREAD

**Issue by maxkoretskyi** [pdm-project/pdm#2988]
Searched the docs but can't find the information on conflict dependency resolution. Does pdm support nesting for conflicting transitient dependencies either like `npm` through copying or like `pnpm` [through simlinks](https://github.com/pdm-project/pdm/issues/new?assignees=&labels=%E2%AD%90+enhancement&projects=&template=feature_request.md&title=), i.e.:

```
node_modules
└── .pnpm
    ├── bar@1.0.0
    │   └── node_modules
    │       └── bar -> <store>/bar
    └── foo@1.0.0
        └── node_modules
            ├── foo -> <store>/foo
            └── bar -> ../../bar@1.0.0/node_modules/bar
```

**Comment by frostming** [comment]
I guess you mean making two conflicting versions of the same package co-exist in the same environment. But that's not what Python's package layout looks like. Python doesn't support that.

**Comment by maxkoretskyi** [comment]
Thanks for your answer!
> it needs the support of import system and Python doesn't support that.
That's why I probably can't find the package manager in the Python ecosystem that supports that. I saw [this discussion](https://github.com/orgs/pnpm/discussions/3164), but it didn't lead to anything.
