### ISSUE TITLE
Notify pdm update only on major version update

### ISSUE THREAD

**Issue by arition** [pdm-project/pdm#2989]
## Is your feature/enhancement proposal related to a problem? Please describe.

PDM consistently notifies about version updates at the start of my shell, likely due to shell completion, even for minor updates. While I appreciate the update notification feature, I prefer not to receive them as frequently.

## Describe the solution you'd like

Introduce a new configuration option to notify users only for major version updates.

**Comment by frostming** [comment]
This is a bit too verbose, I am not going to implement this feature.
