### ISSUE TITLE
2.16 regression: default pdm export behavior is incompatible with pip installs

### ISSUE THREAD

**Issue by sigma67** [pdm-project/pdm#2991]
- [x ] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

- `pdm export --format requirements --without-hashes --output requirements.tmp` to generate a constraints file for pip
- `pip install coverage[toml] --constraint requirements.tmp`

## Actual behavior

```
DEPRECATION: Constraints are only allowed to take the form of a package name and a version specifier. Other forms were originally permitted as an accident of the implementation, but were undocumented. The new implementation of the resolver no longer supports these forms. A possible replacement is replacing the constraint with a requirement. Discussion can be found at https://github.com/pypa/pip/issues/8210
ERROR: Constraints cannot have extras
```

## Expected behavior

This worked prior to 2.16.

If this pattern is not intended, what is the intended way to retrieve a version locked with pdm and install said version with pip?

## Environment Information

```bash
PDM version:
  2.16.1
Python Interpreter:
  project/.venv/bin/python3.10 (3.10)
Project Root:
  project
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.12",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.5.0-41-generic",
  "platform_system": "Linux",
  "platform_version": "#41~22.04.2-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun  3 11:32:55 UTC 2",
  "python_full_version": "3.10.12",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}
```

**Comment by sigma67** [comment]
The use case here is that we need only a single package from the lock file for a specific job. 

Installing everything from the lock file or even only a specific group would be wasteful and is not a solution for this case

**Comment by sigma67** [comment]
Pip source: https://github.com/pypa/pip/blame/main/src/pip/_internal/req/req_install.py#L877

**Comment by frostming** [comment]
Pass `--no-extras` to the export command
