### ISSUE TITLE
Cannot install package (backend) into global environment

### ISSUE THREAD

**Issue by sanmai-NL** [pdm-project/pdm#3000]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```
+ python3 -- /tmp/tmp.iIfGMH -v 2.16.1
Usage: pdm [-h] [-V] [-c CONFIG] [-v | -q] [--no-cache] [-I]
 [--pep582 [SHELL]]
 ...

    ____  ____  __  ___
   / __ \/ __ \/  |/  /
  / /_/ / / / / /|_/ /
 / ____/ /_/ / /  / /
/_/   /_____/_/  /_/

Options:
  -h, --help            Show this help message and exit.
  -V, --version         Show the version and exit
  -c CONFIG, --config CONFIG
                        Specify another config file path [env var:
                        PDM_CONFIG_FILE]
  -v, --verbose         Use `-v` for detailed output and `-vv` for more
                        detailed
  -q, --quiet           Suppress output
  --no-cache            Disable the cache for the current command. [env var:
                        PDM_NO_CACHE]
  -I, --ignore-python   Ignore the Python path saved in .pdm-python. [env var:
                        PDM_IGNORE_SAVED_PYTHON]
  --pep582 [SHELL]      Print the command line to be eval'd by the shell

Commands:
  add                   Add package(s) to pyproject.toml and install them
  build                 Build artifacts for distribution
  cache                 Control the caches of PDM
  completion            Generate completion scripts for the given shell
  config                Display the current configuration
  export                Export the locked packages set to other formats
  fix                   Fix the project problems according to the latest
                        version of PDM
  import                Import project metadata from other formats
  info                  Show the project information
  init                  Initialize a pyproject.toml for PDM
  install               Install dependencies from lock file
  list                  List packages installed in the current working set
  lock                  Resolve and lock dependencies
  outdated              Check for outdated packages and list the latest
                        versions on indexes.
  publish               Build and publish the project to PyPI
  python (py)           Manage installed Python interpreters
  remove                Remove packages from pyproject.toml
  run                   Run commands or scripts with local packages loaded
  search                Search for PyPI packages
  self (plugin)         Manage the PDM program itself (previously known as
                        plugin)
  show                  Show the package information
  sync                  Synchronize the current working set with lock file
  update                Update package(s) in pyproject.toml
  use                   Use the given python version or path as base
                        interpreter. If not found, PDM will try to install
                        one.
  venv                  Virtualenv management
Installing PDM (2.16.1): Creating virtual environment
Installing PDM (2.16.1): Installing PDM and dependencies
Installing PDM (2.16.1): Making binary at /home/unprivileged/.local/bin

Successfully installed: PDM (2.16.1) at /home/unprivileged/.local/bin/pdm
+ pdm add -g pdm-backend==2.3.1
Changes are written to pyproject.toml.
Adding global packages to default dependencies: pdm-backend==2.3.1
STATUS: Resolving dependencies
STATUS: Resolving: new pin python==3.12.3
STATUS: Resolving: new pin pdm-backend 2.3.1
STATUS: Resolving: new pin pip 24.1.2
STATUS: Resolving: new pin setuptools 70.2.0
STATUS: Resolving: new pin wheel 0.43.0
STATUS: Fetching hashes for resolved packages...
🔒 Lock successful
Changes are written to pyproject.toml.
STATUS: Resolving packages from lockfile...
Synchronizing working set with resolved packages: 2 to add, 2 to update, 0 to remove

  ✖ Update pip 24.0 -> 24.1.2 failed

See /home/unprivileged/.local/state/pdm/log/pdm-install-dqgp84zb.log for detailed debug log.
[PermissionError]: [Errno 13] Permission denied: '/usr/bin/pip'
WARNING: Add '-v' to see the detailed traceback
```

## Actual behavior

`PermissionError`: tries to modify `/usr/bin/pip`, I presume.

## Expected behavior

`pip` installed/updated into global environment.

## Environment Information

PDM 2.16.1 in an Alpine Linux 3.20 Docker container, with CPython 3.12.

```bash
# Paste the output of `pdm info && pdm info --env` below:
```

**Comment by frostming** [comment]
what is the problem?

modifying global environment does need proper permission doesn't it?

**Comment by sanmai-NL** [comment]
With global environment I mean the PDM global project's virtual environment. That's a different concept than system-site packages or operating system userland.

```text
+ pdm info --global
Changes are written to pyproject.toml.
PDM version:
  2.16.1
Global Python Interpreter:
  /usr/bin/python (3.12)
Global Project Root:
  /home/unprivileged/.config/pdm/global-project
Global Local Packages:

```

The global project's root directory is under an unprivileged account. PDM itself was installed as an unprivileged user. Since the build backends are no longer pre-shipped, users need a way to install them. I wonder how to install them, since when I run PDM as another (privileged user), how does it find the Global Project Root etc.?

**Comment by frostming** [comment]
>With global environment I mean the PDM global project's virtual environment.

there is no such thing.
by using global project, packages will be installed to the system sitepackages directly

if you want virtual environments just use a normal project

**Comment by sanmai-NL** [comment]
Where to install the build backends?

**Comment by sanmai-NL** [comment]
Where does PDM install itself when installed as unprivileged user?

**Comment by frostming** [comment]
> Where does PDM install itself when installed as unprivileged user?

~/.local/share/pdm for installation script

but why do you need to install the backend? it can be pulled down by the pep 517 builder

**Comment by frostming** [comment]
I feel there's some big misunderstanding and misuse 

would you like to install packages into the pdm's same environment? then you should look at `pdm self add`, that is not global project for

**Comment by sanmai-NL** [comment]
PDM isn't just the script `pdm`, it also depends on Python packages. Where does it install them?

Can you give an example of what you mean by pulling down? I need to use `pdm-backend` with `--no-isolation`?

Where is the `self` stuff documented?

**Comment by sanmai-NL** [comment]
> if you use no isolation mode, you need to add pdm-backend to every project's pyproject.toml

I know, since we've been doing that for a long time already.

> global project is not for sharing dependencies
> 
> pdm itself is also installed in its own virtual environment that is different from any project, and can't be shared either. the location has been given in my previous comments

What do you mean with sharing, here? PDM's dependencies are shared, if I understand correctly what you mean. A backend is no different, it is a required component for PDM to work in this case. The build backend we use was distributed as a ’shared’ dependency before PDM v2.16.0.

> so in short words, if you are looking for a way to share dependencies in many projects. there's no. it does not make sense either

Not sure why you think sharing, in broad sense, doesn't make sense. It makes a lot of sense in containerized app depending on heavy, machine-dependent packages and without glibc. It also makes sense to preinstall a team-wide standard build backend in base images.

Unfortunately, `pdm self` doesn't work in the latter scenario.

```console
$ pdm self list
Installed packages:
...                                                         
pdm               2.16.1    A modern Python package and dependency manager supporting the latest PEP standards                
pdm-backend       2.3.1     The build backend used by PDM that supports latest packaging standards                            
pip               24.1.2    The PyPA recommended tool for installing Python packages.                                         
...

$ pdm install --fail-fast --frozen-lockfile --no-editable --no-isolation --production --verbose
STATUS: Resolving packages from lockfile...
INFO: Inside an active virtualenv /opt/app/.venv, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
STATUS: Fetching hashes for resolved packages...
All packages are synced to date, nothing to do.
unearth.preparer: The file . is a local directory, use it directly
pdm.termui: Running PEP 517 backend to get metadata for <Link file:///Users/sanderhan/devel/gitlab.com/han-aim/aimtools (from None)>
pdm.termui: Preparing environment(Non-isolated mode) for PEP 517 build...
Traceback (most recent call last):
  File "/home/unprivileged/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/unprivileged/.local/share/pdm/venv/lib/python3.12/site-packages/pdm/core.py", line 363, in main
    return core.main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unprivileged/.local/share/pdm/venv/lib/python3.12/site-packages/pdm/core.py", line 281, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/home/unprivileged/.local/share/pdm/venv/lib/python3.12/site-packages/pdm/core.py", line 276, in main
    self.handle(project, options)
  File "/home/unprivileged/.local/share/pdm/venv/lib/python3.12/site-packages/pdm/core.py", line 212, in handle
    command.handle(project, options)
  File "/home/unprivileged/.local/share/pdm/venv/lib/python3.12/site-packages/pdm/cli/commands/install.py", line 100, in handle
    actions.do_sync(
  File "/home/unprivileged/.local/share/pdm/venv/lib/python3.12/site-packages/pdm/cli/actions.py", line 237, in do_sync
    synchronizer.synchronize()
  File "/home/unprivileged/.local/share/pdm/venv/lib/python3.12/site-packages/pdm/installers/synchronizers.py", line 469, in synchronize
    self.candidates[self_key] = self.self_candidate
                                ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/unprivileged/.local/share/pdm/venv/lib/python3.12/site-packages/pdm/installers/synchronizers.py", line 139, in self_candidate
    return self.environment.project.make_self_candidate(not self.no_editable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unprivileged/.local/share/pdm/venv/lib/python3.12/site-packages/pdm/project/core.py", line 526, in make_self_candidate
    can.prepare(self.environment).metadata
  File "/home/unprivileged/.local/share/pdm/venv/lib/python3.12/site-packages/pdm/models/candidates.py", line 612, in metadata
    result = self.prepare_metadata()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unprivileged/.local/share/pdm/venv/lib/python3.12/site-packages/pdm/models/candidates.py", line 516, in prepare_metadata
    return self._get_metadata_from_build(self._unpacked_dir, metadata_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unprivileged/.local/share/pdm/venv/lib/python3.12/site-packages/pdm/models/candidates.py", line 594, in _get_metadata_from_build
    self._metadata_dir = builder(source_dir, self.environment).prepare_metadata(metadata_parent)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unprivileged/.local/share/pdm/venv/lib/python3.12/site-packages/pdm/builders/wheel.py", line 16, in prepare_metadata
    filename = self._hook.prepare_metadata_for_build_wheel(out_dir, self.config_settings)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unprivileged/.local/share/pdm/venv/lib/python3.12/site-packages/pyproject_hooks/_impl.py", line 224, in prepare_metadata_for_build_wheel
    return self._call_hook(
           ^^^^^^^^^^^^^^^^
  File "/home/unprivileged/.local/share/pdm/venv/lib/python3.12/site-packages/pyproject_hooks/_impl.py", line 402, in _call_hook
    raise BackendUnavailable(
pyproject_hooks._impl.BackendUnavailable: Cannot import 'pdm.backend'
```

**Comment by frostming** [comment]
> What do you mean with sharing, here? PDM's dependencies are shared

PDM's dependencies are also installed in an isolated environment and can't be shared by your projects. I don't know why you think PDM's dependencies are shared. If you run `pdm run python -c "import pdm"` in your project root, it will fail.


> Not sure why you think sharing, in broad sense, doesn't make sense.

I know your use case and it does make sense, but it doesn't make sense in PDM's project management model. PDM is designed to manage multiple project with possibly different python versions, sharing dependencies between them is not realistic.

**Comment by sanmai-NL** [comment]
Thanks, it's somewhat clear (except why the blue and red venvs both exist), but I don't see why a green venv (created with `--system-site-packages`, by the way) couldn't search for build-time dependencies in the blue or red venvs (depending on their purpose). And what is least clear and most important to me now, is how to work around the breaking change to `--no-isolation` semantics. Installing a build backend manually into the venv for each project is tedious and most importantly, means elaborating the instructions to my users (data scientists) for each PDM-based project. 

If the build backend could be searched in the system site-packages, without changing anything to isolationf of PDM's internal venvs, that would help. Perhaps that works already, but there were no migration instructions so here we are now.

**Comment by sanmai-NL** [comment]
As for why I thought PDM dependencies are shared, I misremembered from https://github.com/pdm-project/pdm/issues/2944 or some other history that `pdm-backend` was distributed along with PDM in the past. And in the past, no manual install for `pdm-backend` was needed.

One question regarding `pdm self`: what's the purpose of being able to `pdm add` packages into there, if it's meant to be very isolated?

**Comment by frostming** [comment]
A basic principle is that dependencies follow the interpreter, and the environments of different interpreters are isolated from each other. The second line of each box in the above graph is the interpreter path, some of them are virtual, as in virtual environments, but the global project(red box) is a "real" interpreter, meaning the dependencies are directly installed into that interpreter.



> If the build backend could be searched in the system site-packages, without changing anything to isolation of PDM's internal venvs

There is a way, however, since virtual environments are created from a specific interpreter, it allows to inherit the dependencies from the parent interpreter. Python's `venv` allows to pass `--system-site-packages` to load the site-packages from the parent interpreter:

```
--system-site-packages
                        Give the virtual environment access to the system site-packages dir.
```

In PDM, you can either create the venv with that option yourself, or run `pdm venv create python3.11 -- --system-site-packages` to create a venv with the option enabled. Then you can install dependencies into that parent interpreter to make them shared. However, you have to make sure all projects use the same parent interpreter(one that creates the venv) to share dependencies. You can also use PDM's global project to manager that parent interpreter, if configured correctly(using `pdm use -g` to point to the correct interpreter. There is no general way to share dependencies across agnostic projects since you don't know which interpreters they are using.

> One question regarding `pdm self`: what's the purpose of being able to `pdm add` packages into there, if it's meant to be very isolated?

For managing PDM's own dependencies, there are some optional dependencies, and PDM plugins which must be installed into the PDM environment(blue box)
