### ISSUE TITLE
Cannot remove optional dependency once installed

### ISSUE THREAD

**Issue by pgarrison** [pdm-project/pdm#3002]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce
1. Set up an optional dependency [output omitted, no issue here].
```bash
pdm init
pdm add -G optional requests
```
2. Try to remove optional dependencies from working set without changing `pyproject.toml`.
```bash
pdm sync -v --prod --clean
STATUS: Resolving packages from lockfile...
All packages are synced to date, nothing to do.

🎉 All complete!
```
3. Check if `requests` was removed.
```bash
pdm run python -c "import requests"
```

## Actual behavior
`pdm run python -c "import requests"` does not error.

`requests` is not removed from the working set. Only way to do it is `rm -r .venv/lib/python3.11/site-packages/requests`.

## Expected behavior

`pdm run python -c "import requests"` should log a `ModuleNotFoundError` error.

I hoped the `--clean` flag would guarantee that the working set is exactly the requested dependencies and no others.

## Real-world use case
I use the pdm github action with the cache enabled. My github action uses `pdm sync -d --clean`. I moved a dependency X from prod dependencies to an optional dependency group. In CI, I hoped to test the code without X installed, but X was present in the cache and not removed by the `--clean` flag, so the working set included X. So every time I move a dependency from prod to the optional group, I have to manually invalidate github action cache entries.

## Environment Information

```bash
PDM version:
  2.16.1
Python Interpreter:
  /home/philip.garrison/workspace/aics/tmp/.venv/bin/python (3.11)
Project Root:
  /home/philip.garrison/workspace/aics/tmp
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.6",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "4.15.0-213-generic",
  "platform_system": "Linux",
  "platform_version": "#224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023",
  "python_full_version": "3.11.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}
```

**Comment by pgarrison** [comment]
The MWE above does not include any prod or dev dependencies, which might be a bit unnatural. The issue persists even if there are also prod and/or dev dependencies.

**Comment by frostming** [comment]
Run `pdm sync --only-keep --prod` because `--clean` won't remove packages in the lock file.

**Comment by pgarrison** [comment]
Thank you! Now that I know what to look for, the documentation seems straightforward
