### ISSUE TITLE
Regression pdm 2.16.1 with sync --no-isolation

### ISSUE THREAD

**Issue by paugier** [pdm-project/pdm#3005]
It is a regression seen with pdm 2.16.1 (and 2.16.0). The project can be installed with pdm 2.15.4.

## Steps to reproduce

I observe the issue with https://foss.heptapod.net/fluiddyn/fluidsim, where we have something like:

```
[tool.pdm.dev-dependencies]
dev = [
    "flit_core >=3.2,<4",
    # fluidsim-core needs flit_core for its build
    "-e fluidsim-core @ file:///${PROJECT_ROOT}/lib",
]

[tool.pdm.options]
sync = ["--no-isolation"]
```

## Actual behavior

With pdm 2.16, PDM tries to install fluidsim-core with no isolation before installing flit_core and we get:

```
[BackendUnavailable]: Cannot import 'flit_core.buildapi'
```

I guess before pdm 2.16.1, fluidsim-core was installed with build isolation and only the main project was installed without build isolation.

## Expected behavior

fluidsim-core should be installed after flit_core so that we have a chance to install the build dependencies.

**Comment by frostming** [comment]
that is expected 

no isolation no longer installs any build requirements and due to race condition fit-core may not be ready when installing the dependency 

does it work if you run sync again?

**Comment by paugier** [comment]
> does it work if you run sync again?

No. It fails very early and installs nothing.

> no isolation no longer installs any build requirements and due to race condition fit-core may not be ready when installing the dependency

It seems to me that it means that `--no-isolation` became incompatible with local dependencies. Is it true? Is it on purpose? Is there a workaround?

**Comment by paugier** [comment]
The lock file was already generated and I run `pdm sync`.

**Comment by frostming** [comment]
can you paste the traceback so I know where it failed?

**Comment by paugier** [comment]
Thanks @frostming. I confirm that it works after #3008.
