### ISSUE TITLE
Unable to add tar package

### ISSUE THREAD

**Issue by g-kartik** [pdm-project/pdm#3006]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
Run `pdm add https://github.com/openvinotoolkit/datumaro/archive/refs/tags/v0.1.9.tar.gz` 

## Actual behavior

Does not resolve the package and its dependencies. A error related to build tools like pip and wheel shows up

## Expected behavior

It should resolve the package and install it. I have tried to install the same via `pipenv` and `pip`. It succeeded with both of them. 

## Environment Information
```
PDM version:
  2.15.4
Python Interpreter:
  /mnt/ssd/work/mindkosh/core_tool/.venv/bin/python (3.8)
Project Root:
  /mnt/ssd/work/mindkosh/core_tool
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.8.19",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.9.7-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Fri, 28 Jun 2024 04:32:50 +0000",
  "python_full_version": "3.8.19",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
This is a problem of that tarball, not PDM

You can run `pdm add https://github.com/pallets/click/archive/refs/tags/8.1.3.tar.gz` to see if it succeeds
