### ISSUE TITLE
pdm.toml or .pdm.toml

### ISSUE THREAD

**Issue by gael-ft** [pdm-project/pdm#3023]
## Is your feature/enhancement proposal related to a problem? Please describe.

I am a bit lost regarding `pdm.toml` vs `.pdm.toml` configuration file.
I can see in my `.gitignore` generated file the line: 
```
#   pdm stores project-wide configurations in .pdm.toml, but it is recommended to not include it
#   in version control.
#   https://pdm-project.org/#use-with-ide
.pdm.toml
```

But most of the documentation is talking about a `<PROJECT_ROOT>/pdm.toml`.
See [Configuration files](https://pdm-project.org/latest/usage/config/#configuration-files) documentation page.

## Describe the solution you'd like

I started using PDM (great tool btw) recently, so I am not sure if that's a bug or not. 
But if not, I would expect a description of the difference in [Configure the project](https://pdm-project.org/latest/usage/config/#configuration-files) documentation page.

**Comment by frostming** [comment]
`pdm.toml` is the new name, you can include it ion version control or not on your choice

The generated note is not maintained by us.
