### ISSUE TITLE
`pdm build` makes wheels with snake_case for packages named with kebab-case

### ISSUE THREAD

**Issue by NickCrews** [pdm-project/pdm#3025]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

```
git clone https://github.com/NickCrews/apoc-data.git
pdm build
```

The built wheels are called `apoc_data-*`, when they should be `apoc-data-*`, since that is what is in `pyproject.toml`

Now, in another package using PDM, I am trying to install from pypi: https://pypi.org/project/apoc-data/0.1.1/

- If I try to plain old `pip install apoc-data`, then this works.
- If I add `apoc-data` as a requirement and then `pdm install` in that project, it works
- If I add `apoc-data>=0.1.1` as a requirement and then `pdm install` , I get an error when it goes to fetch the metadata:

<details>
<summary>Details</summary>

```
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   affinegap
pdm.termui:   apoc-data>=0.1.1
pdm.termui:   fire
pdm.termui:   pandas>=2
pdm.termui:   pyarrow
pdm.termui:   click>=8.1.7
pdm.termui:   ipykernel
pdm.termui:   mypy
pdm.termui:   pytest
pdm.termui:   pytest-cov
pdm.termui:   ruff
pdm.termui:   python>=3.10
pdm.termui:   Adding requirement affinegap
unearth.collector: Collecting links from https://pypi.org/simple/affinegap/
unearth.auth: Found index url https://pypi.org/simple/
unearth.collector: Fetching HTML page https://pypi.org/simple/affinegap/
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/91/97/60f37029b20b9e6ec6d88cb420d47658cdb661d90fa3424ab572a1f598e6/affinegap-1.0-py2.7-linux-x86_64.egg (from https://pypi.org/simple/affinegap/)>: Unsupported archive format: affinegap-1.0-py2.7-linux-x86_64.egg
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/9d/e2/d13e00e167f629c0dcc1d0b06b4fe0633efee58223f023c9b5ab358f68a8/affinegap-1.1-py2.7-linux-x86_64.egg (from https://pypi.org/simple/affinegap/)>: Unsupported archive format: affinegap-1.1-py2.7-linux-x86_64.egg
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/a0/5b/a7ec60976902cb7b14fb4d2233be864aec847f7801e639392a22a1e1638f/affinegap-1.2-py2.7-linux-x86_64.egg (from https://pypi.org/simple/affinegap/)>: Unsupported archive format: affinegap-1.2-py2.7-linux-x86_64.egg
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/25/2a/be1a6fec1c11fb5ad0d288ff87ee94985e07c23dc0251913a95af63a8df6/affinegap-1.3-py2.7-linux-x86_64.egg (from https://pypi.org/simple/affinegap/)>: Unsupported archive format: affinegap-1.3-py2.7-linux-x86_64.egg
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/ac/f3/5556ff8c37706fb02b70293ff291811dd97b69c75ae87b689690d6b3fe34/affinegap-1.7-py2.7-linux-x86_64.egg (from https://pypi.org/simple/affinegap/)>: Unsupported archive format: affinegap-1.7-py2.7-linux-x86_64.egg
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/fd/b4/4563e62d430ecda4fcbdd1d78ba83606ff0f0d0a18dcdf7c57e75f6a0ca1/affinegap-1.8-py2.7-linux-x86_64.egg (from https://pypi.org/simple/affinegap/)>: Unsupported archive format: affinegap-1.8-py2.7-linux-x86_64.egg
pdm.termui:   Adding requirement apoc-data>=0.1.1
unearth.collector: Collecting links from https://pypi.org/simple/apoc-data/
unearth.auth: Found index url https://pypi.org/simple/
unearth.collector: Fetching HTML page https://pypi.org/simple/apoc-data/
pdm.termui: 	Could not find any matching candidates.
pdm.termui: 	Could not find any matching candidates even when considering pre-releases.
pdm.termui: Error occurs
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pdm/2.16.1/libexec/lib/python3.12/site-packages/pdm/termui.py", line 257, in logging
    yield logger
  File "/opt/homebrew/Cellar/pdm/2.16.1/libexec/lib/python3.12/site-packages/pdm/cli/actions.py", line 124, in do_lock
    raise ResolutionImpossible("Unable to find a resolution") from None
resolvelib.resolvers.ResolutionImpossible: Unable to find a resolution
```

</details>

So PDM is barfing I think because it is finding `apoc_data` files at that package index URL, instead of `apoc-data`
If I look at [sklearns index](https://pypi.org/simple/scikit-learn/), I see the the package metadata there is in `kebab-case` format, which PDM handles fine. (EDIT: now I notice that only the very early versions of sklearn use `scikit-learn`, the later ones use `scikit_learn`, so IDK what is going on....)

So, two possible points of failure:
1. PDM is messing up the case when building a package. It should exactly mirror the package name that is in pyproject.toml.
2. PDM isn't flexible enough when resolving packages. When it goes and looks at the index URL, files of either `apoc_data` or `apoc-data` should satisfy the `apoc-data` requirement that I have.

I'm not sure what the precise specs are in this area. Fixing either one would make things work for me, but perhaps we should fix both things. But we also don't want to be more generous than the spec says :)

Thank you for work on this project, PDM is my favorite!

**Comment by dimbleby** [comment]
snake-case is correct, see https://packaging.python.org/en/latest/specifications/binary-distribution-format/#escaping-and-unicode

**Comment by NickCrews** [comment]
Thanks for the link! (assuming you mean snake_case when you say snake-case). So then I'm not sure exactly where things are falling apart then:
- The wheels built by PDM are in the correct (snake_case) format
- they are in the correct (snake_case) format on the [pypi index](https://pypi.org/simple/apoc-data/)
- PDM can seemingly install snake_case sklearn wheels from [the index](https://pypi.org/simple/scikit-learn/)

So what is the difference between sklearn and apoc-data where PDM can install one but not the other?

**Comment by frostming** [comment]
> * If I add `apoc-data>=0.1.1` as a requirement and then `pdm install` , I get an error when it goes to fetch the metadata:

Can't reproduce, everything works fine with `apoc-data>=0.1.1` as requirement. Maybe have another try?
