### ISSUE TITLE
Pdm zsh completions failure:  pdm zsh: *:: :->_subcmds: command not found...

### ISSUE THREAD

**Issue by Fury1** [pdm-project/pdm#3031]
## Steps to reproduce
PDM, version 2.17.0

Fresh install using curl as directed from [installation](https://pdm-project.org/en/latest/#installation).

Installation works as expected,  completions are generated as specified for [zsh](https://pdm-project.org/en/latest/#__tabbed_5_2). Completions also generate to file as expected .

## Actual behavior

Completions fail with attempted use: 

`
pdm zsh: *:: :->_subcmds: command not found...
`

## Expected behavior

Zsh completions should work.

## Environment Information

Fedora 40.

Zsh shell.

## Fix

Upon completion definition inspection a backslash is missing from the generated completions on the output of `pdm completion zsh > ~/.zfunc/_pdm` 

Line 54 below in `_pdm`.

```
7   _arguments -s -C -A '-*' \
  6     $arguments \
  5     {-c,--config}'[Specify another config file path\[env var: PDM_CONFIG_FILE\]]' \
  4     {-V,--version}'[Show the version and exit]' \
  3     {-I,--ignore-python}'[Ignore the Python path saved in .pdm-python]' \
  2     '--no-cache:Disable the cache for the current command. [env var: PDM_NO_CACHE]' \
  1     '--pep582:Print the command line to be eval by the shell for PEP 582:shell:(zsh bash fish tcsh csh)' \
54      {-n,--non-interactive}"[Don't show interactive prompts but use defaults. \[env var: PDM_NON_INTERACTIVE\]]"
  1     '*:: :->_subcmds' \
  2     && return 0
```

**Comment by pgarrison** [comment]
Reproduced in my environment and confirmed that adding the `\` to `_pdm` line 54 fixes the completion
