### ISSUE TITLE
pdm lock on v2.17.1 defaults to locking only for current platform

### ISSUE THREAD

**Issue by stewartadam** [pdm-project/pdm#3043]
I'm not sure if this a recent change or a something I didn't expect after peeking at the documentation but `pdm lock` appears to default to serializing the current platform information into lockfile metadata, resulting in the removal of all cross-platform whl hashes.

## Steps to reproduce

```
pdm init -n
pdm add lxml
cat pdm.lock
# it includes whl hashes for all platforms

pdm update
cat pdm.lock
# it includes whl hashes for all platforms

pdm lock
cat pdm.lock
# only current platform
```

## Actual behavior
`pdm lock` serializes the current installation information into lockfile target metadata and removes all cross-platform hashes:

```
[[metadata.targets]]
requires_python = "==3.11.9"
platform = "macos_14_0_arm64"
implementation = "cpython"
gil_disabled = false

[[package]]
name = "lxml"
version = "5.2.2"
requires_python = ">=3.6"
summary = "Powerful and Pythonic XML processing library combining libxml2/libxslt with the ElementTree API."
groups = ["default"]
marker = "python_full_version == \"3.11.9\""
files = [
    {file = "lxml-5.2.2-cp311-cp311-macosx_10_9_universal2.whl", hash = "sha256:45f9494613160d0405682f9eee781c7e6d1bf45f819654eb249f8f46a2c22545"},
    {file = "lxml-5.2.2.tar.gz", hash = "sha256:bb2dc4898180bea79863d5487e5f9c7c34297414bad54bcd0f0852aee9cfdb87"},
]
```

Once the lockfile has target metadata attached and whl hashes removed, `pdm update` won't restore it either. `pdm lock --refresh` appears to restore all whl hashes (although running a subsequent `pdm lock` operation will remove it again).

## Expected behavior

1. `pdm lock` should have clearer documentation if this is expected behavior. Users would probably want to avoid it altogether unless intending to create platform-specific lockfiles.
2. Given flags like `--platform` control the lockfile target, one would expect `pdm lock --refresh` to behave in a similar way to `pdm lock`. Both should either default to current platform, or to all platforms with CLI flags to add constraints.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.17.1
Python Interpreter:
  /Users/stewartadam/repro/.venv/bin/python (3.11)
Project Root:
  /Users/stewartadam/repro/foo
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.12.4",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "23.5.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 23.5.0: Wed May  1 20:13:18 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6030",
  "python_full_version": "3.12.4",
  "platform_python_implementation": "CPython",
  "python_version": "3.12",
  "sys_platform": "darwin"
}

```

**Comment by frostming** [comment]
Can't reproduce following your step, here is the header of lock file after each step, they are the same:

```toml
[metadata]
groups = ["default"]
strategy = ["inherit_metadata"]
lock_version = "4.5.0"
content_hash = "sha256:84ef4ff9439145cdc0fa4ccedd1c3397a385f5540283c713e54754d1cb8cb178"

[[metadata.targets]]
requires_python = "==3.12.*"
```
Note the `metadata.targets` part, it doesn't pin platform or implementation.

**Comment by stewartadam** [comment]
Huh, well this is confusing - you're right, I also can't repro this anymore with the exact same command sequence. I had a co-worker running into this issue too.

Let me take a further look tomorrow / reply back if I can repro it again.

**Comment by stewartadam** [comment]
Ah, figured this out - removing targets from the file causes it to get regenerated with the very specific build target noted in the repro instructions.

If I delete the lock file entirely, it'll get created with the targets as specified from CLI args + pyproject.toml.

**Comment by adamsxs** [comment]
You can also add back in what you know the metadata.targets should be if you want to add/update/remove dependencies without re-locking everything. Feels hacky to mess with the lockfile, but an old project of mine mine was missing its generic target like the following:
```
[[metadata.targets]]
requires_python = ">=3.10"
```  
Adding it back in caused my specific platform to stop being used for targets.
