### ISSUE TITLE
build-system.requires cannot specify the version of setuptools

### ISSUE THREAD

**Issue by mikeshi80** [pdm-project/pdm#3055]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

I set the build-system setting as belowing:
```
[build-system]
requires = ["setuptools<72.0.0", "wheel"]
build-backend = "setuptools.build_meta"
```

and run `pdm install`
## Actual behavior

pdm downloads the latest setuptools 72.0.0, not follow the settings.

## Expected behavior

pdm downloads the setuptools which version < 72.0.0, and since the 72.0.0 has remove the support for test command, the package ffmpy cannot be installed successfully if setuptools >= 72.0.0.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
```

pdm info

```plaintext
PDM version:
  2.17.1
Python Interpreter:
  C:\dev\report-analyzer\.venv\Scripts\python.exe (3.11)
Project Root:
  C:/dev/report-analyzer
Local Packages:
```

pdm info --env
```json
{
  "implementation_name": "cpython",
  "implementation_version": "3.12.2",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "11",
  "platform_system": "Windows",
  "platform_version": "10.0.22631",
  "python_full_version": "3.12.2",
  "platform_python_implementation": "CPython",
  "python_version": "3.12",
  "sys_platform": "win32"
}
```

**Comment by frostming** [comment]
The build requirements will be installed when building a source distribution, each source distribution may have its own build requirements, and the `build-system` table only changes the requirements for **the project itself**, not the dependencies.

If you are looking for a way to control the build environments for all your dependencies, use `--no-isolation` flag. #3054 
Closing it now.
