### ISSUE TITLE
`pdm py install` read  timed out

### ISSUE THREAD

**Issue by microbubble9586** [pdm-project/pdm#3070]
## Is your feature/enhancement proposal related to a problem? Please describe.

When I use pdm install some new python interpreters, I get a time out log.
```
pdm py install
[ReadTimeout]: The read operation timed out
WARNING: Add '-v' to see the detailed traceback
```
## Describe the solution you'd like

I think it would be very beneficial to have a configuration option that allows users to specify the URL for downloading the Python interpreter.

**Comment by frostming** [comment]
Set proxy with `*_PROXY` env vars should work

**Comment by microbubble9586** [comment]
Thanks,I will try it.  
Btw,I could not find these config on [PDM Cconfig](https://pdm-project.org/en/latest/reference/configuration/). 
Would it be possible to add it to the reference manual?
