### ISSUE TITLE
Feature Proposal: Concurrent Scripts

### ISSUE THREAD

**Issue by Xdynix** [pdm-project/pdm#3071]
## Is your feature/enhancement proposal related to a problem? Please describe.

I recently discovered a new requirement when I was working on my side project. My application may need to run multiple processes at the same time, such as a server and a worker. The simplest implementation is that I can open multiple terminals to execute them separately, but then I also need to stop them separately, which is annoying when there are too many processes. It would be great if there was a tool like NPM's `concurrently` but based on Python/PDM. Although PDM currently supports executing multiple scripts through composite script, they will only execute sequentially.

I have also considered [`honcho`](https://github.com/nickstenning/honcho) and [`circus`](https://github.com/circus-tent/circus). However, both libraries are not actively maintained and are relatively heavyweight for this requirement.

[`supervisor`](https://github.com/Supervisor/supervisor) is a popular option, but its configuration file-based design seems too cumbersome for a development server, and it does not support Windows.

The best I can do at the moment is still using `concurrently`, which is cross-platform, but requires adding NPM to the development environment.

```toml
[tool.pdm.scripts]
dev.cmd = [
    "npx", "concurrently", "--kill-others-on-fail",
    "pdm run python3 manage.py runserver",
    "pdm run python3 manage.py runworker",
]
```

## Describe the solution you'd like

We may have a new kind of script defined, like `concurrent`. It will be something like:

```toml
[tool.pdm.scripts]
dev.concurrent = [
    "python3 manage.py runserver",
    "python3 manage.py runworker",
]
dev.kill_others = false
dev.kill_others_on_fail = true
```

It can also have parameters like `concurrently` to determine whether to terminate the other scripts prematurely if one of the scripts terminates.

**Comment by frostming** [comment]
This might be too complex for a package manager because to run multiple subprocesses, you need an arbiter and process management, such as how to handle a subprocess crash.

I believe you can achieve this through some community tools or by writing a simple script yourself. This is beyond the scope.
