### ISSUE TITLE
Support `REQUESTS_CA_BUNDLE` (or vice versa) on non-Linux

### ISSUE THREAD

**Issue by NiklasRosenstein** [pdm-project/pdm#3076]
## Is your feature/enhancement proposal related to a problem? Please describe.

PDM uses the `truststore` package, which takes `SSL_CERT_FILE` into account only on Linux ([here](https://github.com/sethmlarson/truststore/blob/e5ba7f01a1f1bad412dd5402be257c2ab39cae31/src/truststore/_openssl.py#L34)). On OSX (and presumably other systems), the variable is ignored.

I have found https://github.com/pdm-project/pdm/issues/1240, which is from 2022, which talks about `REQUESTS_CA_BUNDLE` as being an option. I presume that the `truststore` module maybe wasn't used by PDM at this point yet.

Because PDM always uses `truststore.SSLContext()`, and because `truststore` does not support typical environment variables for injecting a custom CA bundle, PDM's CA bundle cannot be configured from environment variables.

## Describe the solution you'd like

I suspect that `truststore` not supporting `SSL_CERT_FILE` on OSX is a design decision; but PDM could add explicit support for this or another variable (like the typical `REQUESTS_CA_BUNDLE`).

**Comment by NiklasRosenstein** [comment]
Patching in `ctx.load_default_certs()` before returning the `truststore.SSLContext()` seems to work its magic for me, but I'm not sure if this gets rid of all the other opinionated/system-specific certificate loading when there's no `SSL_CERT_FILE` set.

**Comment by frostming** [comment]
> Patching in `ctx.load_default_certs()` before returning the `truststore.SSLContext()` seems to work its magic for me

Does `ctx.load_default_certs()` load env var `REQUESTS_CA_BUNDLE`?
