### ISSUE TITLE
how to use pdm install local packages，like this：!pdm add torch --find-links ./path.

### ISSUE THREAD

**Issue by lluck42** [pdm-project/pdm#3081]

**Comment by lluck42** [comment]
pdm is useful，but i can‘t find a way to search package file in local like pip. do it support this? eg: pip install --no-index --find-links=/path/to/packages -r requirements.txt

**Comment by frostming** [comment]
You are looking for `type = "find_links"` sources: https://pdm-project.org/en/latest/usage/config/#configure-the-package-indexes

**Comment by lluck42** [comment]
can you show me a example？is this toml file righ？：
![image](https://github.com/user-attachments/assets/42c4e083-1210-46cf-97ce-7f565eed9b7a)
code:
pdm add torch torchvision torchaudio

**Comment by lluck42** [comment]
![image](https://github.com/user-attachments/assets/9c114957-c4a5-4e06-b507-115fa76b415b)
thanks, it like work well.
