### ISSUE TITLE
PDM update command update all dependencies from all groups when passing a group and `--unconstrained` flag

### ISSUE THREAD

**Issue by g0di** [pdm-project/pdm#3101]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Setup a new project and install one main dependency and one dev dependency 

```bash
pdm init
# Pick default settings
pdm add "fastapi==0.100.0"
pdm add -dG lint "ruff==0.1.0"
pdm update -dG lint --unconstrained
# pdm update --unconstrained -dG lint  <- this does the same
```

## Actual behavior

When running the last update command, it updates all project dependencies (main and dev ones) even if I specified the `-dG lint` argument in the command.

```bash
$ pdm update -dG lint -u
🔒 Lock successful.
[sync-pre-commit-lock] No pre-commit config file detected at C:\Users\TBEBGOD\Developement\sandbox2\.pre-commit-config.yaml, skipping sync.
Changes are written to pyproject.toml.
Changes are written to pyproject.toml.
Synchronizing working set with resolved packages: 0 to add, 3 to update, 0 to remove

  ✔ Update starlette 0.27.0 -> 0.37.2 successful
  ✔ Update fastapi 0.100.0 -> 0.112.0 successful
  ✔ Update ruff 0.1.0 -> 0.5.7 successful
  ✔ Update sandbox2 0.1.0 -> 0.1.0 successful

  🎉 All complete! 3/3 0:00:04
```

## Expected behavior

I would expect the previous update command to only update the dependencies in the specified groups (i.e: `lint`)

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.17.3
Python Interpreter:
  C:\Users\TBEBGOD\Developement\sandbox2\.venv\Scripts\python.exe (3.10)
Project Root:
  C:/Users/TBEBGOD/Developement/sandbox2
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.11.4",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19045",
  "python_full_version": "3.10.11",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "win32"
}
```

**Comment by frostming** [comment]
The `--group/-G` option works the same as in `sync` command, where `pdm update -dGlint` selects default+lint, look at the table [here](https://pdm-project.org/en/latest/usage/dependency/#select-a-subset-of-dependency-groups-to-install)

You should add `--no-default` to exclude the default dependencies.
