### ISSUE TITLE
``pdm update`` when upgrading from lockfile v4.4.2 differs from ``pdm lock`` without existing lockfile

### ISSUE THREAD

**Issue by sigma67** [pdm-project/pdm#3105]
- [x ] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

- Have a v4.4.2 lockfile in your repo
- Have latest pdm installed
- $ pdm update

## Actual behavior

Lockfile will now contain strict [metadata.targets] with pinned Python version, which does not work on other developer's machines

prior lockfile:

```
# This file is @generated by PDM.
# It is not intended for manual editing.

[metadata]
groups = ["default", "dev"]
strategy = ["inherit_metadata"]
lock_version = "4.4.2"
content_hash = "sha256:d33278b3b6db983b32106cf56b5238f9a5e33adf341adb6af9408e06948eebe7"
```

... pdm update...

```
# This file is @generated by PDM.
# It is not intended for manual editing.

[metadata]
groups = ["default", "dev"]
strategy = ["inherit_metadata"]
lock_version = "4.5.0"
content_hash = "sha256:d33278b3b6db983b32106cf56b5238f9a5e33adf341adb6af9408e06948eebe7"

[[metadata.targets]]
requires_python = "==3.10.12"
platform = "manylinux_2_35_x86_64"
implementation = "cpython"
gil_disabled = false
```

^^ none of the auto-defaults being set here are desired.

## Expected behavior

Lockfile shall contain loose [metadata.targets] with only requires-python set to the one set in pyproject.toml. 

This is also the default behavior of latest pdm when creating a new pdm lockfile.

```
[[metadata.targets]]
requires_python = ">=3.10"
```

## Environment Information

irrelevant

**Comment by frostming** [comment]
it's because the 4.4.2 is missing the "cross_platform" strategy,which makes it a strict lock file

**Comment by frostming** [comment]
> So the root issue is this. Multiple users collaborate on a project. One uses pdm 2.16 (A), the other uses 2.17 (B).

Yes, we try to make it backward-compatible but not forward, we can't put much effort into forward-compatibility.
