### ISSUE TITLE
2.18.0: Failing tests due to missing implementation of abstract method delete_auth_info

### ISSUE THREAD

**Issue by dvzrv** [pdm-project/pdm#3110]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

When running pytest related tests (as before) with the build of 2.18.0 for the Arch Linux package (see [PKGBUILD](https://gitlab.archlinux.org/archlinux/packaging/packages/python-pdm/-/blob/ca9ea5f165658b0feb0639b1597795a7b7983a1c/PKGBUILD)) I run into issues with keyring related tests:

```
=========================== short test summary info ============================
SKIPPED [1] tests/test_utils.py:171: Windows test
ERROR tests/cli/test_config.py::test_config_password_save_into_keyring - TypeError: Can't instantiate abstract class MockKeyringProvider without an implementation for abstract method 'delete_auth_info'
ERROR tests/cli/test_config.py::test_keyring_operation_error_disables_itself - TypeError: Can't instantiate abstract class MockKeyringProvider without an implementation for abstract method 'delete_auth_info'
ERROR tests/cli/test_publish.py::test_repository_get_credentials_from_keyring - TypeError: Can't instantiate abstract class MockKeyringProvider without an implementation for abstract method 'delete_auth_info'
= 941 passed, 1 skipped, 2 deselected, 60 warnings, 3 errors in 92.05s (0:01:32) =
```

## Actual behavior

Full build and test logs:
[python-pdm-2.18.0-1-x86_64-build.log](https://github.com/user-attachments/files/16622721/python-pdm-2.18.0-1-x86_64-build.log)
[python-pdm-2.18.0-1-x86_64-check.log](https://github.com/user-attachments/files/16622720/python-pdm-2.18.0-1-x86_64-check.log)

## Expected behavior

All tests pass

## Environment Information

n/a

**Comment by frostming** [comment]
`unearth` 0.17.0 is released after PDM 2.18.0, hence the incompatibility

**Comment by dvzrv** [comment]
Ah, I see.
Please feel free to close this once there is an updated pdm released, then I can remove the deselected tests again.

**Comment by frostming** [comment]
Released
