### ISSUE TITLE
Clarify use of requires-python (no way to base resolver on specific python version is use as long as it satisfies requires-python?)

### ISSUE THREAD

**Issue by callegar** [pdm-project/pdm#3119]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. Have a requires-python specifying a wide version range
2. Try `pdm install`

## Actual behavior

See that the resolver unable to resolve because there is no single version of a dependency that is OK for the whole of the range.
This happens even if there would be a dependency version OK for some python version and another one OK for some other python version.

## Expected behavior

I would have expected pdm to see that the python interpreter in use is within the requires-python version range and then to base the resolver on the specific version in use (or at least to have a flag to trigger that behavior).

## Environment Information

pdm version 2.18.1

```
{
  "implementation_name": "cpython",
  "implementation_version": "3.12.4",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.10.5-1-MANJARO",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Wed Aug 14 17:29:44 UTC 2024",
  "python_full_version": "3.11.9",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
I think this document is enough

https://pdm-project.org/en/latest/usage/lock-targets/

**Comment by pawamoy** [comment]
> I would have expected pdm to see that the python interpreter in use is within the requires-python version range and then to base the resolver on the specific version in use (or at least to have a flag to trigger that behavior).

That wouldn't work. If you claim to support Python 3.8 through 3.12, but only lock for 3.11, then anyone else contributing to your project but not using 3.11 would be using incorrect lock data.

**The current Python interpreter has no bearing, and cannot have any bearing in the locking process.** :slightly_smiling_face:
