### ISSUE TITLE
Updating 4.5.0 lock files (PDM 2.17+) with older PDM versions makes them non-cross-platform

### ISSUE THREAD

**Issue by sh-at-cs** [pdm-project/pdm#3121]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

1. Create a new PDM project with a PDM version >= 2.17 and run `pdm lock`.
2. Downgrade PDM to a version < 2.17, e.g. 2.16, then run `pdm lock` again.
4. Bonus step: Upgrade to >= 2.17 again to see the actual consequence of a non-cross-platform lock file.

**Note** that step 2 is a stand-in for the more likely scenario where one of your colleagues happens to have an older version of PDM than you and updates the lock file with it. Of course nobody is actually going around downgrading PDM.

## Actual behavior

After step 2, you get a 4.4.2 lock file with `strategy = ["inherit_metadata"]` in its `[metadata]` section. That makes it non-cross-platform, because in lock file versions < 4.5, `strategy` must contain `"cross-platform"` to be considered as such.

So when you upgrade back to a PDM version >= 2.17 and run `pdm lock` again (bonus step 3), PDM writes a platform-specific `[[metadata.targets]]` section and your `pdm install` invocation will henceforth fail on machines with slightly differing Python installations with errors like:

```
ERROR: None of the lock targets matches the current env (==3.11.9, manylinux_2_36_x86_64, cpython):
 - (==3.11.6, manylinux_2_35_x86_64, cpython)
```

## Expected behavior

Updating lock files with older PDM versions shouldn't result in loss of the information that the lock file is meant to be cross-platform, _especially when being cross-platform is PDM's default_.

I don't know how you could fix that at this point because the lock file format has already been changed in a way that makes this inevitable.

Maybe to avoid similar issues going forward, PDM should, from now on, simply refuse to work with lock file versions that are newer than what it can handle. Perhaps the way lock file versions are chosen could reflect this, e.g. everything within a minor version must be downgrade-compatible, or something like that.

## Environment Information

As stated above.

## Related issues

- The root cause of #3105 turned out to be the same issue, as described in [this comment](https://github.com/pdm-project/pdm/issues/3105#issuecomment-2288845549).

**Comment by frostming** [comment]
> e.g. everything within a minor version must be downgrade-compatible, or something like that.


Yes, it is. The version consists of three parts: the major part indicates a breaking change, the minor part indicates a backward-compatible change, and the last part indicates a forward-compatible change. When incompatibilities arise, we attempt to reuse the lock file content as much as possible, which leads to this issue. However, I don't plan to change this because it does benefit for many cases.
