### ISSUE TITLE
Add --push-back option to command

### ISSUE THREAD

**Issue by carstencodes** [pdm-project/pdm#3124]
## Is your feature/enhancement proposal related to a problem? Please describe.

When updating my dependencies, I am able to use the latest versions and APIs from the third party dependencies, even if they are not present in the required minimum version.

In order to be able to describe this dependency better, it would be good to reflect the current version from the lockfile back to the top packages in pyproject.toml.

### Use Case

I create a library called A, which uses library Z with minimum version 1.1. After running pdm update, the version of Z in pdm.toml is 1.6.
When implementing A, I use a function / class added in version 1.5.

When I create the wheel for A, it is documented that Z in version 1.1 is minimally required.

A user of library A uses it together with library B that uses Z >= 1.2, <1.5, it will be installed in a version less than 1.5, as both libraries allow this version of the dependency Z.

As the new function used in depends on 1.5 or later, calls may (!) fail.

## Describe the solution you'd like

Run pdm update --push-back (or a similar option) to add new minimum versions of the top level packages to pyproject.toml.

This way, the newer minimum required is documented and developers may set new minimum versions of their packages automatically from the lockfiles.

**Comment by frostming** [comment]
`pdm update --unconstrained [PACKAGE]` with proper version save strategy will rewrite the version specifiers in the pyproject.toml

I feel that there might be a slight difference from your needs, but I think it's best not to make it too complicated.

**Comment by carstencodes** [comment]
This is exactly what I was searching for. Kudos to your work and thank you very much
