### ISSUE TITLE
Redundant files defined in lock file

### ISSUE THREAD

**Issue by AdamJel** [pdm-project/pdm#3127]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Description

The lock file for a given project contains this dependency:

```
[[package]]
name = "cryptography"
version = "43.0.0"
requires_python = ">=3.7"
summary = "cryptography is a package which provides cryptographic recipes and primitives to Python developers."
groups = ["default"]
marker = "python_version == \"3.12\""
dependencies = [
    "cffi>=1.12; platform_python_implementation != \"PyPy\"",
]
files = [
    {file = "cryptography-43.0.0-cp37-abi3-win_amd64.whl", hash = "sha256:31e44a986ceccec3d0498e16f3d27b2ee5fdf69ce2ab89b52eaad1d2f33d8778"},
    {file = "cryptography-43.0.0-cp39-abi3-win_amd64.whl", hash = "sha256:0663585d02f76929792470451a5ba64424acc3cd5227b03921dab0e2f27b1709"},
    {file = "cryptography-43.0.0.tar.gz", hash = "sha256:b88075ada2d51aa9f18283532c9f60e72170041bba88d7f37e49cbb10275299e"},
]
```

Which has 2 8.whl files defined - for cpython 3.7 and 3.9, but since the project has python specification for 3.12.*, I believe that only the higher version of cpython should be included.

This represents an issue in a scenario, where all the packages are downloaded for offline use. Then the .whl file with cp37 is not needed at all and must be handled manually and removed.

### pdm info

```bash
PDM version:
  2.17.3
Python Interpreter:
  C:\Users\JelinekA\repos\thu\ipc-opcua\.venv\Scripts\python.exe (3.12)
Project Root:
  C:/Users/JelinekA/repos/thu/ipc-opcua
Local Packages:
```

### pdm info --env

```
{
  "implementation_name": "cpython",
  "implementation_version": "3.12.5",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "11",
  "platform_system": "Windows",
  "platform_version": "10.0.22631",
  "python_full_version": "3.12.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.12",
  "sys_platform": "win32"
}
```

**Comment by frostming** [comment]
This however involves a cross-validation: whether a wheel should be included is not only decided by its own tags, but also tags from sibling wheels, which makes the validation more complex. I tend to not implementing this because such redundancy is totally acceptable.
