### ISSUE TITLE
PDM using PEP582 even when disabled globally

### ISSUE THREAD

**Issue by woopla** [pdm-project/pdm#3145]
I have a GitLab CI job that insists on using pep582, despite all my attempts to force it to use venvs:
- `pdm config python.use_venv true` and `pdm config -g python.use_venv true` are used in the script
- for good measure, I checked that `PYTHONPATH` does not have the relevant bits (it's empty)
- I also added this section to my `pyproject.toml`:
```toml
[tool.pdm]
use_venv = true
```

But nothing works, PDM insists on using `__pypackages__` instead of the `.venv` it itself creates when running `pdm use`.

Here's the kicker: if I login as the GitLab runner user to the machine hosting the GitLab runner and run `pdm install` myself, it works as expected.

It seems that there's another env. variable that's affecting pep582 behavior, but I can't find it. I'm using PDM v2.18.1.

**Comment by frostming** [comment]
> * I also added this section to my `pyproject.toml`:
> 
> ```toml
> [tool.pdm]
> use_venv = true
> ```

Wrong place, it should be in PDM's own config file. You can set it either per-project or globally:

```bash
pdm config python.use_venv true
```

P.S. Read the manual please

**Comment by woopla** [comment]
Sorry I should’ve mentioned that I had used `pdm config` with and without `-g` but I’m the first car that was not committed to version control for the CI - I’m gonna try again the project-specific config in the right config file.

I keep on deleting `__pypackages__` to no avail. I wish the verbose mode would say why it’s using pep582 or a venv.

**Comment by frostming** [comment]
@woopla you will also need to notice whether `PDM_PYTHON` env is set, that'll change it to PEP 582 mode if not pointing to a venv python

**Comment by woopla** [comment]
> @woopla you will also need to notice whether `PDM_PYTHON` env or `.pdm-python` is set, that'll change it to PEP 582 mode if not pointing to a venv python

Oh. *That* was my problem - I was setting `PDM_PYTHON` in the CI YAML! I renamed this to `PYTHON_EXEC` and it works as expected now, thanks!

I do not see in the docs that `PDM_PYTHON` enables PEP582, could this be clarified in https://pdm-project.org/en/latest/usage/pep582/?
