### ISSUE TITLE
太好用了, 除了速度相比poetry , uv慢点 ,其他体验都是顶级

### ISSUE THREAD

**Issue by Super1Windcloud** [pdm-project/pdm#3160]
太好用了, 除了速度相比poetry , uv慢点 ,其他体验都是顶级

**Comment by Super1Windcloud** [comment]
看了一下uv 的全局缓存, 也是用的硬链接

**Comment by 522247020** [comment]
看大佬的提交代码，9月6号还在开发用 uv 作为后端的功能。

**Comment by 522247020** [comment]
目前看 是 2.19.0 版本会发布这个功能。

## 局限性

尽管 uv 带来了显著的性能提升，但需要注意 uv 的以下局限性：

- 缓存文件存储在 uv 自己的缓存目录中，你必须使用 `uv` 命令来管理它们。
- 不支持 PEP 582 本地包布局。
- uv 不支持 `inherit_metadata` 锁定策略。 在写入锁定文件时，这将被忽略。
- 不支持除 `all` 和 `reuse` 之外的更新策略。
- 可编辑需求必须是本地路径。像 `-e git+<git_url>` 这样的需求不被支持。
- `[tool.pdm.resolution]` 下的 `overrides` 和 `excludes` 设置不被支持。

目前是代码提交的文档说明。还是要等正式版

**Comment by Super1Windcloud** [comment]
这样吗,  也就是说会使用uv的缓存全局变量吗, 可是我认为pdm的全局配置文件相比环境变量更有优势
