### ISSUE TITLE
项目初始化创建项目测试脚本

### ISSUE THREAD

**Issue by 522247020** [pdm-project/pdm#3166]
## 你的功能 / 增强提案是否与某个问题相关？请描述。

使用 PDM 创建项目时，项目目录结构如下

```
.
├── README.md
├── pdm.lock
├── pyproject.toml
├── src 
│   ├── [项目名]
│   │   ├── __init__.py  
└── tests
    ├── __init__.py
```

项目生成后，创建 scr 目录下的子目录与项目同名，我每次新建项目都不会使用他，我会把它删除。

## 描述你想要的解决方案。

我想，不如在初始化项目后，在 `src` 目录中创建一个 `main.py` ，里面添加一个 `hello world` 脚本。
然后在 `pyproject.toml` 添加一个启动项目的测试脚本。

项目结构如下：

```
.
├── README.md
├── pdm.lock
├── pyproject.toml
├── src 
│   └── main.py
└── tests
    ├── __init__.py
```

`pyproject.toml` 内添加启动脚本：

```
...
[tool.pdm.script]
dev='python src/main.py'
```

这样可以在创建项目后，执行 `pdm run dev` 快速测试项目

**Comment by frostming** [comment]
That is not what a typical python package look like.

By putting a `main.py` under `src`, the `main.py` acts as a single-file module named `main`.
