### ISSUE TITLE
关于引入 UV 问题

### ISSUE THREAD

**Issue by 522247020** [pdm-project/pdm#3167]
## 您的功能 / 增强功能提案是否与问题相关？请描述。

之前我的想法也是在 PDM 中引入 UV 来加快拉取其他库的想法。
但是我目前出现了另外一个疑惑，这样的操作会不会使核心代码库是否越来臃肿？
是否能把 UV 库的引入作为 PDM 的插件来使用？

## 描述你想要的解决方案。

我们应该优化核心代码，开放更多功能接口给插件库来使用，这样可以减轻核心代码库开发人员的一些负担。

**Comment by frostming** [comment]
By enabling plugins we need a good abstraction anyway. And that's what #3144 mainly does, just that we put uv in the main codebase as an alternative implementation of the same abstraction, and it can be opted out cleanly.
