### ISSUE TITLE
[Scripts] Pass original working directory as env variable

### ISSUE THREAD

**Issue by Bubichoo-Teitichoo** [pdm-project/pdm#3179]
## Is your feature/enhancement proposal related to a problem? Please describe.

Coming from Poetry + [Poe](https://poethepoet.natn.io/index.html) I'm missing the ability read/use the working directory of the calling shell within my scripts.
Especially with mono-repos I may need the actual working directory of the shell to properly do some scripted actions in a particular part of the repo.

## Describe the solution you'd like

The solution to the problem would be rather simple. Somewhere in [TaskRunner._run_process](https://github.com/pdm-project/pdm/blob/9bc4fd8fc508a94e1ce945204e5229f98b8937f9/src/pdm/cli/commands/run.py#L219) you would just have to create a environment variable that holds the current working directory. e.g.

```python
os.environ["PDM_PWD"] = str(Path.cwd())
```

For naming I'd propose something similar to what Poe is doing: https://poethepoet.natn.io/env_vars.html

I'm happy to make the relevant changes and create a PR if you think this proposal is good.

**Comment by frostming** [comment]
I'd suggest `PDM_RUN_CWD` but PR welcome
