### ISSUE TITLE
Ignore non-semantic differences (some whitespace etc.) with lock file hash calculation

### ISSUE THREAD

**Issue by sanmai-NL** [pdm-project/pdm#3184]
## Is your feature/enhancement proposal related to a problem? Please describe.

When running tools to format TOML files, they may disagree with PDM on layout. When these differences occur, it's annoying that the lock file hash becomes out of sync. (E.g., after a PDM update). The same with comments.

## Describe the solution you'd like

Do a TOML serialization, deserialization roundtrip before calculating the hash value.

**Comment by frostming** [comment]
Not clear what you mean, since we will serialize it to JSON before calculating hash, what non-semantic content is there?

https://github.com/pdm-project/pdm/blob/af4267b5d495bffcdbe4c1b5285a865728ac72fe/src/pdm/project/project_file.py#L86
