### ISSUE TITLE
Add virtualenv management to PDM

### ISSUE THREAD

**Issue by frostming** [pdm-project/pdm#319]
You may be surprised by the title, A PEP 582 package manager is going to manage virtualenvs? Yes, virtualenv has its own advantage, especially in the scenario of matrix testing.

The features include create, list, remove, and activate virtualenvs associated with the current project.

Most development and changes will happen in another repo which will be shipped as a plugin of PDM. It will also be included by PDM as an opt-in component via optional-dependencies.

Stay tuned and any feedbacks are welcome.

**Comment by frostming** [comment]
For activate command, Pipenv and Poetry's implementation is to invoke a subshell with PATH modified. However, this approach will lose most of the fantastic features the current shell has. For example, shell init script is not executed or even up and down arrow keys can't work.

`pdm venv activate` will, on contrast, print the activate command and users can **source** it from the current shell.

**Comment by linw1995** [comment]
Maybe do not tie them with a specific python version like 3.9, 3.8. For instead, separates them by name. By default, name them as the same as their python version. For more use cases, we may name them "linting-27", "linting-35", "testing-35"  and so on, to install different groups of packages. 

And this will need to change the pdm packages grouping mechanism for supporting that. So many packages management tools only support main and dev dependencies group in current day.

**Comment by frostming** [comment]
@linw1995 Thank you for your advice, it is the designed behavior:
```console
pdm venv create --help
Create a virtualenv

Usage: pdm venv create [-h] [-v] [-w {virtualenv,venv,conda}] [-f] [-n NAME] [python] ...

positional arguments:
  python                Specify which python should be used to create the virtualenv
  venv_args             Additional arguments that will be passed to the backend

Options:
  -h, --help            show this help message and exit
  -v, --verbose         -v for detailed output and -vv for more detailed
  -w {virtualenv,venv,conda}, --with {virtualenv,venv,conda}
                        Speicify the backend to create the virtualenv
  -f, --force           Recreate if the virtualenv already exists
  -n NAME, --name NAME  Specify the name of the virtualenv
```

**Comment by frostming** [comment]
Try it here: https://github.com/pdm-project/pdm-venv/
