### ISSUE TITLE
`[ProjectError]: tool.pdm.distribution must be `true` to be built.` which actually is in my `pyproject.toml`

### ISSUE THREAD

**Issue by galenseilis** [pdm-project/pdm#3198]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

I'm not really sure if this is a bug, or (plausibly) I have just misunderstood the available instructions.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

First, I was reminded that I need to have the token-based authentication setup:

```bash
$ pdm publish -v
Building sdist...
pdm.termui: Preparing environment(Isolated mode) for PEP 517 build...
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   Adding requirement python==3.12.3
pdm.termui:   Adding requirement pdm-backend
pdm.termui: ======== Resolution Result ========
pdm.termui:        python None
pdm.termui:   pdm-backend 2.4.1
pdm.termui: Fetching hashes for pdm-backend@2.4.1
pdm.termui: Installing pdm-backend@2.4.1...
pdm.termui: Using cached response for https://files.pythonhosted.org/packages/46/8b/.../pdm_backend-2.4.1-py3-none-any.whl
unearth.preparer: Downloading <Link https://files.pythonhosted.org/packages/46/8b/.../pdm_backend-2.4.1-py3-none-any.whl (from https://pypi.org/simple/pdm-backend/)> (107 kB)
pdm.termui: Synchronization complete.
pdm.termui:  - Adding LICENSE -> LICENSE
pdm.termui:  - Adding README.md -> README.md
pdm.termui:  - Adding .pdm-build/pyproject.toml -> pyproject.toml
pdm.termui:  - Adding src/simq/__init__.py -> src/simq/__init__.py
pdm.termui:  - Adding src/simq/simpy_ggc_network.py -> src/simq/simpy_ggc_network.py
pdm.termui:  - Adding tests/__init__.py -> tests/__init__.py
pdm.termui:  - Adding PKG-INFO -> PKG-INFO
Built sdist at /home/galen/projects/SimQ/dist/simq-0.1.0.tar.gz
Building wheel from sdist...
pdm.termui: Preparing environment(Isolated mode) for PEP 517 build...
pdm.termui:  - Adding .pdm-build/simq-0.1.0.dist-info/METADATA -> simq-0.1.0.dist-info/METADATA
pdm.termui:  - Adding .pdm-build/simq-0.1.0.dist-info/WHEEL -> simq-0.1.0.dist-info/WHEEL
pdm.termui:  - Adding .pdm-build/simq-0.1.0.dist-info/entry_points.txt -> simq-0.1.0.dist-info/entry_points.txt
pdm.termui:  - Adding .pdm-build/simq-0.1.0.dist-info/licenses/LICENSE -> simq-0.1.0.dist-info/licenses/LICENSE
pdm.termui:  - Adding src/simq/__init__.py -> simq/__init__.py
pdm.termui:  - Adding src/simq/simpy_ggc_network.py -> simq/simpy_ggc_network.py
pdm.termui:  - Adding simq-0.1.0.dist-info/RECORD -> simq-0.1.0.dist-info/RECORD
Built wheel at /home/galen/projects/SimQ/dist/simq-0.1.0-py3-none-any.whl
Username: galenseilis
Password: 
Uploading simq-0.1.0-py3-none-any.whl
[PublishError]: Client error '403 Username/Password authentication is no longer supported. Migrate to API Tokens or 
Trusted Publishers instead. See https://pypi.org/help/#apitoken and https://pypi.org/help/#trusted-publishers' for 
url 'https://upload.pypi.org/legacy/'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403
```

So I created a token, but I wasn't sure 'where' to use it. Read [this issue](https://github.com/pdm-project/pdm/issues/1891#issue-1698415961) I attempted to use `pdm publish -u <username> -p <token>`, but quickly realized that wasn't right. I got this error:

```python
[ProjectError]: tool.pdm.distribution must be `true` to be built.
```
I figure that I am getting the `ProjectError` because I am not using the password/token correctly. Although, I have noted that 
```toml
[tool.pdm]
distribution = true
```
is actually in my `pyproject.toml`.

Reviewing what I have done in the past using Twine, I realized that I already have a [`$HOME/.pypirc`](https://packaging.python.org/en/latest/specifications/pypirc/#using-a-pypi-token) so I am guessing that PDM isn't able to see it for some reason.

## Expected behavior

The expected behaviour would be successfully publishing to PyPI.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
$ pdm info && pdm info --env
PDM version:
  2.19.1
Python Interpreter:
  /home/galen/projects/SimQ/.venv/bin/python (3.12)
Project Root:
  /home/galen/projects/SimQ
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.12.3",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.8.0-45-generic",
  "platform_system": "Linux",
  "platform_version": "#45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024",
  "python_full_version": "3.12.3",
  "platform_python_implementation": "CPython",
  "python_version": "3.12",
  "sys_platform": "linux"
}

```

**Comment by frostming** [comment]
> I got this error:
> 
> ```python
> [ProjectError]: tool.pdm.distribution must be `true` to be built.
> ```

Did you change the working dir between this and previous command? Because in the previous run it was clearly built successfully.

**Comment by galenseilis** [comment]
> > I got this error:
> > ```python
> > [ProjectError]: tool.pdm.distribution must be `true` to be built.
> > ```
> 
> Did you change the working dir between this and previous command? Because in the previous run it was clearly built successfully.

Good idea. It makes sense to get such an error if I were calling from the wrong path. Unfortunately, I just confirmed that I get this behaviour when calling either of `pdm publish -v` or `pdm publish -u <username> -p <API-Token>` from the root of the project (which has the `pyproject.toml`, `.pdm-python` and `pdm.lock` files in it. Perhaps there is a path config issue in some other way?

Although the project is in an early draft state, I expect it can be published because I have put similar things up with Twine in the past. If it helps, the source is available [here](https://github.com/galenseilis/SimQ), although I would ask that you do not publish it to PyPI. Maybe it can provide sufficient information about what is wrong.

Also, this is the path to the python in my `.pdm-python`: `/home/galen/projects/SimQ/.venv/bin/python`. 

Please let me know if there is any further information I can give you, or things I should try.

**Comment by galenseilis** [comment]
> > I got this error:
> > ```python
> > [ProjectError]: tool.pdm.distribution must be `true` to be built.
> > ```
> 
> Did you change the working dir between this and previous command? Because in the previous run it was clearly built successfully.

I can also confirm that `pdm build` successfully builds the project locally.

**Comment by frostming** [comment]
> I can also confirm that `pdm build` successfully builds the project locally.

but `pdm publish` just do `pdm build` and then upload. How can i reproduce? do you have a repo for me to try?

**Comment by frostming** [comment]
> Good idea. It makes sense to get such an error if I were calling from the wrong path. Unfortunately, I just confirmed that I get this behaviour when calling either of `pdm publish -v` or `pdm publish -u <username> -p <API-Token>` from the root of the project (which has the `pyproject.toml`, `.pdm-python` and `pdm.lock` files in it

This was not the case in your first attempt:

>First, I was reminded that I need to have the token-based authentication setup:

**Comment by galenseilis** [comment]
> > I can also confirm that `pdm build` successfully builds the project locally.
> 
> but `pdm publish` just do `pdm build` and then upload. How can i reproduce? do you have a repo for me to try?

That's an interesting observation. That does suggest that the issue is occurring at the upload step.

I created a repo [pdm-foo](https://github.com/galenseilis/pdm-foo) which I have just confirmed has the same problems. You can do anything you like with it to help with troubleshooting.

However, I just made another observation worth sharing. I just created a virtual environment within the SimQ repo working directory, installed twine, and was successful at uploading (using the same build produced by PDM) by just calling `twine upload dist/*` from the root of the project. ([PyPI:SimQ](https://pypi.org/project/SimQ/)) This suggests that my `$HOME/.pypirc` file is valid.

So `pdm build` is fine, uploading with Twine is fine, just not `pdm publish`. 

I'm grasping at straws, but could there be any relevance to the fact that I used to have [Rye](https://rye.astral.sh/) installed? I believe I [uninstalled](https://rye.astral.sh/guide/commands/self/uninstall/) it correctly, but I figure I'd mention it.

**Comment by galenseilis** [comment]
Here's an idea. I have have some other systems (all Linux) that I could try publishing from. If I can reproduce the problem on them then maybe it is related to the OS. If I cannot reproduce the issue on my other systems, then it may just be an issue on the system I am currently working on.  In which case a reinstall might be in order if I cannot find the issue specifically.

**Comment by frostming** [comment]
I can't reproduce using your repo:

```
❯ pdm publish -r testpypi
Building sdist...
Built sdist at /Users/fming/wkspace/github/pdm-foo/dist/pdm_foo-0.1.0.tar.gz
Building wheel from sdist...
Built wheel at /Users/fming/wkspace/github/pdm-foo/dist/pdm_foo-0.1.0-py3-none-any.whl
Uploading pdm_foo-0.1.0-py3-none-any.whl
 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.3/16.3 kB • 00:00 • 160.7 MB/s
Uploading pdm_foo-0.1.0.tar.gz
 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 kB • 00:00 • 60.0 MB/s

View at:
https://test.pypi.org/project/pdm-foo/0.1.0/
```

And as I said, the error directly comes from [the build part](https://github.com/pdm-project/pdm/blob/28fd92888b691e6921532c8fd96ebcd1dc4db92e/src/pdm/cli/commands/build.py#L46-L47) and has nothing to do with the upload part.

**Comment by frostming** [comment]
@galenseilis hi, any updates on this issue?

**Comment by galenseilis** [comment]
> @galenseilis hi, any updates on this issue?

@frostming Hi, thanks for the follow up. I have not taken the opportunity to troubleshoot all the way through, but some of my config might be broken by Rye (even though I uninstalled it correctly).

So at the moment I am limping along with PDM + Twine on a couple of my personal projects.

Overall, I expect that this is a config issue that has nothing to do with PDM per se. I'll reopen if I find that it might be otherwise.

**Comment by galenseilis** [comment]
I made a fresh install:

```bash
pdm-foo on  main is 📦 v0.1.0 via 🐍 v3.12.3 (venv)
❯ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble
```
I set running OS updates as part of the installation. Then I used git to clone the pdm-foo repository, and installed [Starship](https://starship.rs/).

I installed`python3-pip`, which I immediately upgraded. Then I installed `python3-venv`, and started a virtual environment. Inside that virtual environment I installed pdm using pip. Then I ran `pdm build` in the working directory to confirm that the project built fine.

Next I ensured that I have a `$HOME/.pypirc` file:

```pypirc
[pypi]
username = __token__
password = <PyPI token>
```

Where `<PyPI token>` is substituted with my actual token. 

However, I am still getting an error when I call `pdm publish`:

```bash
pdm-foo on  main is 📦 v0.1.0 via 🐍 v3.12.3 (venv) took 2s 
❯ python -m pdm publish
Building sdist...
INFO: Inside an active virtualenv /home/seig/projects/pdm-foo/venv, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
Built sdist at /home/seig/projects/pdm-foo/dist/pdm_foo-0.1.0.tar.gz
Building wheel from sdist...
Built wheel at /home/seig/projects/pdm-foo/dist/pdm_foo-0.1.0-py3-none-any.whl
Username: galenseilis
Password: 
Uploading pdm_foo-0.1.0-py3-none-any.whl
 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.3/16.3 kB • 00:00 • 32.3 MB/s
See /home/seig/.local/state/pdm/log/pdm-publish-bu7vkn1m.log for detailed debug log.
[PublishError]: Client error '403 Username/Password authentication is no longer supported. Migrate to API Tokens or Trusted Publishers instead. See 
https://pypi.org/help/#apitoken and https://pypi.org/help/#trusted-publishers' for url 'https://upload.pypi.org/legacy/'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403
```

I have tried leaving the Username and Password blank, or filling in only Username and leaving Password blank, or filling in my Username and using the token itself as the password, or filling in my Username and using my PyPI password for Password. 

Weird thing is, as before, Twine still works. I installed Twine with pip, and ran `twine upload dist/*` and it worked as desired. 

I've reopened the issue because a simple reproducible fresh install should not be having these issues. Let's continue looking into this.

**Comment by frostming** [comment]
> ```shell
> Built wheel at /home/seig/projects/pdm-foo/dist/pdm_foo-0.1.0-py3-none-any.whl
> Username: galenseilis
> Password: 
> ```

You are definitely using username, the error is correct.



> Next I ensured that I have a `$HOME/.pypirc` file:

It isn't read by PDM, thanks

So afterall it turns out not a problem of PDM but misusage.

**Comment by galenseilis** [comment]
@frostming Your reading was incomplete. Please do not look only at the code example.

Here is the sentence you overlooked (bolded emphasis added).

> I have tried **leaving the Username** and Password **blank**, or filling in only Username and leaving Password blank, or filling in my Username and using the token itself as the password, or filling in my Username and using my PyPI password for Password.

Please reopen so we may resume Q&A for troubleshooting.

**Comment by galenseilis** [comment]
> > Next I ensured that I have a $HOME/.pypirc file:
> 
> It isn't read by PDM, thanks

Oh, wait... How am I supposed to configure so that PDM knows my credentials for PyPI?

**Comment by galenseilis** [comment]
> You are definitely using username, the error is correct.

In that one example, yes, however I also reported (bold emphasis added):

> I have tried **leaving the Username and Password blank**, or filling in only Username and leaving Password blank, or filling in my Username and using the token itself as the password, or filling in my Username and using my PyPI password for Password.

**Comment by galenseilis** [comment]
> So afterall it turns out not a problem of PDM but misusage.

That appears to be the case, yes. I figured it out. I was not using the literal `__token__` as the user input. 

The [documentation](https://pdm-project.org/latest/usage/publish/) says:

> PyPI requires API tokens to publish packages, you can use `__token__` as the username and API token as the password.

I did not understand what that until just now. I recall trying to put my actual token in once as the username, but gave on that.

**Comment by galenseilis** [comment]
> > > You are definitely using username, the error is correct.
> > 
> > 
> > In that one example, yes, however I also reported (bold emphasis added):
> > > I have tried **leaving the Username and Password blank**, or filling in only Username and leaving Password blank, or filling in my Username and using the token itself as the password, or filling in my Username and using my PyPI password for Password.
> 
> Then just post the reproduction steps and outputs, using a valid input.
> 
> > How am I supposed to configure so that PDM knows my credentials for PyPI? Or is that not supported altogether?
> 
> ```
> pdm config repository.pypi.username __token__
> pdm config repository.pypi.password ...
> ```

Got it. Thank you for your assistance. The issue is resolved now.
