### ISSUE TITLE
`pdm lock --check` on a lockfile generated with older PDM version has a 0 exit code when there's a change in `pyproject.toml`

### ISSUE THREAD

**Issue by chandrasekharan98** [pdm-project/pdm#3199]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

1. Generate a lock file with an older version of PDM - it should generate a different lock file version (for eg: `4.4.1` got generated with PDM version `2.12.3`)
1. Now make any change in `pyproject.toml`
1. Run this snippet to check if lockfile changes are necessary
```shell
if pdm lock --check; then
    echo "No changes required for pdm.lock in $pwd."
else
    echo "Lock file needs to be generated"
fi
```

## Actual behavior

- Used PDM version `2.12.3` to generate a lock file versioned at `4.4.1`
- Newer PDM versions such as `2.16.1` generate a lock file versioned at `4.4.2`
- In case of running `pdm lock --check` after making `pyproject.toml` changes, it only throws the below warning but the exit code is 0
`WARNING: Lockfile is generated on an older version of PDM`

![image](https://github.com/user-attachments/assets/1a1e4ab6-c2d9-48a8-845b-129b764ecc8b)

## Expected behavior

- This is not noticed if the lockfile versions are the same, i.e. if the lock file is generated with PDM version `2.16.1` for a lock_version of `4.4.2` and then we update the `pyproject.toml` - the exit code is 1 for the above snippet
![image](https://github.com/user-attachments/assets/12427a88-190a-43dd-a236-9b0b8f3f9cbc)

## Environment Information

```bash
(unstract-3.9) *[dont-merge/testing-pdm-lock-automation][~/zipstuff/unstract]$ pdm info && pdm info --env                                                                         [11:48:21] 
PDM version:
  3.16.1
Python Interpreter:
  /home/chandru/zipstuff/unstract/.venv/bin/python (3.9)
Project Root:
  /home/chandru/zipstuff/unstract
Local Packages:
  
INFO: PDM 2.16.1 is installed, while 2.19.1 is available.
Please run `pdm self update` to upgrade.
Run `pdm config check_update false` to disable the check.
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.6",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.2.6-76060206-generic",
  "platform_system": "Linux",
  "platform_version": "#202303130630~1689015125~22.04~ab2190e SMP PREEMPT_DYNAMIC Mon J",
  "python_full_version": "3.9.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
INFO: PDM 2.16.1 is installed, while 2.19.1 is available.
Please run `pdm self update` to upgrade.
Run `pdm config check_update false` to disable the check.
```

NOTE: More context can be obtained from [this Github action run](https://github.com/Zipstack/unstract/actions/runs/11174478325/job/31064233959#step:5:71)

**Comment by frostming** [comment]
It is backward-compatible so that lock file should be classified as fine, hence the 0 returncode.
