### ISSUE TITLE
pdm python list Error

### ISSUE THREAD

**Issue by LyonLeopard** [pdm-project/pdm#3200]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**
```
pdm python list -v
Traceback (most recent call last):
  File "/Users/lyonyu/Library/Python/3.12/bin/pdm", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/lyonyu/Library/Application Support/pdm/venv/lib/python3.12/site-packages/pdm/core.py", line 378, in main
    return core.main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lyonyu/Library/Application Support/pdm/venv/lib/python3.12/site-packages/pdm/core.py", line 267, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/Users/lyonyu/Library/Application Support/pdm/venv/lib/python3.12/site-packages/pdm/core.py", line 262, in main
    self.handle(project, options)
  File "/Users/lyonyu/Library/Application Support/pdm/venv/lib/python3.12/site-packages/pdm/core.py", line 194, in handle
    command.handle(project, options)
  File "/Users/lyonyu/Library/Application Support/pdm/venv/lib/python3.12/site-packages/pdm/cli/commands/python.py", line 55, in handle
    ui.echo(f"[success]{version.implementation.lower()}@{version.version}[/] ({version.executable})")
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lyonyu/Library/Application Support/pdm/venv/lib/python3.12/site-packages/findpython/python.py", line 70, in implementation
    return _run_script(str(self.executable), script).strip()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lyonyu/Library/Application Support/pdm/venv/lib/python3.12/site-packages/findpython/python.py", line 23, in _run_script
    return subprocess.run(
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/lyonyu/Library/Application Support/pdm/python/cpython@3.10.14/bin/python3', '-EsSc', 'import platform; print(platform.python_implementation())']' returned non-zero exit status 1.
```

## Steps to reproduce

enter `pdm python list` to the console

## Actual behavior

[CalledProcessError]: Command '['/Users/lyonyu/Library/Application Support/pdm/python/cpython@3.10.14/bin/python3', '-EsSc', 'import
platform; print(platform.python_implementation())']' returned non-zero exit status 1.

## Expected behavior

Should show python versions that have been already installed 

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

```
```
PDM version:
  2.19.1
Python Interpreter:
  /Users/lyonyu/Repos/python/playground/.venv/bin/python (3.12)
Project Root:
  /Users/lyonyu/Repos/python/playground
Local Packages:
```

Above are running on the M3 Macbook Pro, and the pdm is installed by the script  `curl -sSL https://pdm-project.org/install-pdm.py | python3 -`

**Comment by frostming** [comment]
You can see that the reason for the error has already been given above, so why not take a further look at what error this command output?
> ```
> subprocess.CalledProcessError: Command '['/Users/lyonyu/Library/Application Support/pdm/python/cpython@3.10.14/bin/python3', '-EsSc', 'import platform; print(platform.python_implementation())']' returned non-zero exit status 1.
> ```

**Comment by LyonLeopard** [comment]
Yes, I have listed detailed error information above. I tried to check the Python command provided in the error message. I got the following error. So I wonder if there are problems with cpy installed with pdm?
```
> '/Users/lyonyu/Library/Application Support/pdm/python/cpython@3.10.14/bin/python3'
Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
ModuleNotFoundError: No module named 'site'

Current thread 0x00000001fb223240 (most recent call first):
  <no Python frame>
 ```

**Comment by frostming** [comment]
@LyonLeopard That installation may be broken, you can remove the `/Users/lyonyu/Library/Application Support/pdm/python/cpython@3.10.14/` directory and try again.

**Comment by LyonLeopard** [comment]
Yes, this solves the problem. However, what I am worried about is whether this broken Python version is included when installing PDM, and whether it could happen to other users? If so, should this issue be addressed in the PDM source code?

**Comment by LyonLeopard** [comment]
Anyway, the problem is solved, you can close this issue anytime
