### ISSUE TITLE
a way to specify a different `requires-python` range for dev dependencies

### ISSUE THREAD

**Issue by DetachHead** [pdm-project/pdm#3206]
## Is your feature/enhancement proposal related to a problem? Please describe.

my project is a library with some dev dependencies that require `>=3.9`, but this does not mean my package should require python `>=3.9`, as these dev dependencies are not installed by users.

## Describe the solution you'd like

an option to specify a separate `requires-python` for development to the version required by the published package

**Comment by frostming** [comment]
you can separate lock files and use `--python` to specify python range
no more work needs to happen in pdm

**Comment by DetachHead** [comment]
perfect, thanks!
