### ISSUE TITLE
pdm run $SHELL doesn't give me the virtual environment's python and pip

### ISSUE THREAD

**Issue by ShaiAvr** [pdm-project/pdm#3211]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

According to the [docs](https://pdm-project.org/en/latest/usage/venv/#activate-a-virtualenv), I can mimic `pdm shell` by running `pdm run $SHELL` to create a subshell with the project's virtual environment activated. I made a sample library project using the default options of `pdm init` and ran `pdm add numpy` to add a sample dependency. When I ran `pdm run $SHELL`, I got a subshell that seemed like the venv was activated (as indicated by the shell's prompt). However, running `python` or `pip` revealed that the subshell still uses the system python and not the virtual environment (For example, running `pip list` showed all the global installed packages instead of `numpy` and the project itself).

On the other hand, activating the virtual environment using `eval $(pdm venv activate)` (no subshell) worked as expected: the environment is activated and I get the correct `python` and `pip`.

## Steps to reproduce

Create a sample project with `pdm init`, or use any existing project and run `pdm run $SHELL`.

## Actual behavior

Using `python` or `pip` inside the subshell uses the system versions and not the ones of the virtual environment. Activating the virtual environment with `eval $(pdm venv activate)` works as expected.

<img width="1680" alt="image" src="https://github.com/user-attachments/assets/f709e376-eb62-4a06-a147-e43d0290f1b3">

## Expected behavior

`python` and `pip` in the subshell should point to the versions of the virtual environment and not the system ones.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

PDM version:
  2.19.2
Python Interpreter:
  /Users/shai/dev/pdm_lib_demo/.venv/bin/python (3.12)
Project Root:
  /Users/shai/dev/pdm_lib_demo
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.12.5",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "24.0.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 24.0.0: Tue Sep 24 23:36:26 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T8103",
  "python_full_version": "3.12.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.12",
  "sys_platform": "darwin"
}

```

**Comment by frostming** [comment]
This is the downside of spawning a subshell -- **the shell init scrip will be executed at startup**, putting the pyenv path in the front of PATH. It is not able to resolve by nature. That is exactly PDM doesn't provide `pdm shell` command built in.

The second approach "shell functions" is preferred.

**Comment by ShaiAvr** [comment]
I understand. Perhaps the documentation should be updated to give a better warning about this possible issue. By reading the docs, I expected `pdm run $SHELL` to simply work, but depending on the shell init scripts, there is a chance that it wouldn't really work as intended. Maybe the docs should also mention that the "shell function" approach is preferred for that reason.
