### ISSUE TITLE
Installation Failed on Windows for Latest Version

### ISSUE THREAD

**Issue by RiwiHow** [pdm-project/pdm#3213]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

The version of Python installed on my computer is 3.13.0.

## Steps to reproduce

1. run `(Invoke-WebRequest -Uri https://pdm-project.org/install-pdm.py -UseBasicParsing).Content | python -`

## Actual behavior
The following error was encountered:
```
Building wheels for collected packages: msgpack
  Building wheel for msgpack (pyproject.toml): started
  Building wheel for msgpack (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  Building wheel for msgpack (pyproject.toml) did not run successfully.
  exit code: 1

  [11 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build\lib.win-amd64-cpython-313\msgpack
  copying msgpack\exceptions.py -> build\lib.win-amd64-cpython-313\msgpack
  copying msgpack\ext.py -> build\lib.win-amd64-cpython-313\msgpack
  copying msgpack\fallback.py -> build\lib.win-amd64-cpython-313\msgpack
  copying msgpack\__init__.py -> build\lib.win-amd64-cpython-313\msgpack
  running build_ext
  building 'msgpack._cmsgpack' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for msgpack
Failed to build msgpack
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (msgpack)
```
I tried to follow the link `https://visualstudio.microsoft.com/visual-cpp-build-tools/` to install Microsoft C++ Build Tools, but it still does not work.
## Expected behavior

The command can install PDM correctly.

**Comment by frostming** [comment]
Can you install `msgpack` will pip on Python 3.13?

**Comment by RiwiHow** [comment]
Thank you for your reply. There is no issue when installing with pip.
```
PS C:\Users\User> pip install msgpack
Collecting msgpack
  Using cached msgpack-1.1.0-cp313-cp313-win_amd64.whl.metadata (8.6 kB)
Downloading msgpack-1.1.0-cp313-cp313-win_amd64.whl (75 kB)
Installing collected packages: msgpack
Successfully installed msgpack-1.1.0
```

**Comment by frostming** [comment]
@RiwiHow can you also try if you can pip install `msgpack==1.0.8` since that's the version the script installs

Anyway now you can run `(Invoke-WebRequest -Uri https://pdm-project.org/install-pdm.py -UseBasicParsing).Content | python - --no-frozen-deps` to work it around.

**Comment by RiwiHow** [comment]
Thank you! I tried installing version 1.0.8 of msgpack, and it indeed results in an error：
```
Building wheels for collected packages: msgpack
  Building wheel for msgpack (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for msgpack (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-313\msgpack
      copying msgpack\exceptions.py -> build\lib.win-amd64-cpython-313\msgpack
      copying msgpack\ext.py -> build\lib.win-amd64-cpython-313\msgpack
      copying msgpack\fallback.py -> build\lib.win-amd64-cpython-313\msgpack
      copying msgpack\__init__.py -> build\lib.win-amd64-cpython-313\msgpack
      running build_ext
      building 'msgpack._cmsgpack' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for msgpack
Failed to build msgpack
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (msgpack)
```


Additionally, I noticed that the recommended installation method for Windows differs between the Chinese and English versions of the documentation. Was this intentional?
**Chinese**:
`(Invoke-WebRequest -Uri https://pdm-project.org/install-pdm.py -UseBasicParsing).Content | py -`

![image](https://github.com/user-attachments/assets/5e01066e-da1f-4e2c-87a9-50f5214f894c)
**English**:
`powershell -ExecutionPolicy ByPass -c "irm https://pdm-project.org/install-pdm.py | py -"`

![image](https://github.com/user-attachments/assets/c7bdb520-0c40-434e-82c9-702b3542ea12)

**Comment by frostming** [comment]
The Chinese version is maintained by community and may not be up-to-date.

**Comment by RiwiHow** [comment]
Okay, thank you. 🫡
