### ISSUE TITLE
Allow `pdm search` to search within multiple repositories

### ISSUE THREAD

**Issue by o-moe** [pdm-project/pdm#3217]
## Is your feature/enhancement proposal related to a problem? Please describe.

I am working with several private repositories besides pypi.org where packages are published to: for example one as a pypi.org proxy, one for development versions and one for (internal) released versions. For resolving dependencies this is not an issue because I added those as additional indexes to pyproject.toml.

`pdm search`, however,  only takes exactly one repository to seek package details, either the [publish repository from options, from PDM_PUBLISH_REPO or (as default) pypi](https://github.com/pdm-project/pdm/blob/d85760a525a80693bb9e4005632f01a377d9858c/src/pdm/cli/commands/publish/__init__.py#L140).

## Describe the solution you'd like

I would like to configure `pdm search` to look into multiple repositories at once - either by separate configuration (like multiple publish repositories that can also be configured local - not only global) or using the additional project specific indexes.

**Comment by frostming** [comment]
`pdm search` consults a non-standard HTML endpoint https://pypi.org/search/?q=xxx that most registries doesn't support. I don't see much value supporting multiple repositories.

**Comment by o-moe** [comment]
I respect that you do not plan on changing this, imho this would fit very well into the current user experience with other commands: you allow configuring multiple indexes from which the resolver resolves dependencies from. you allow multiple repositories to publish to (by configuration and by cli). you already allow for at least one alternative (to pypi) source for searching by the environment variables (as seen in the source code). To me, it would be only consequent to also allow searching in this context. And working with multiple (private) repositories is at least in a corporate environment not very uncommon. 

Additionally, I  don't think it should not be pdm's problem, if the repository does not allow the needed endpoint for searching. some may support it - some may not.

Unfortunately, I don't think I will find enough time to look into this and understand enough details to propose a PR.

**Comment by frostming** [comment]
Not only that this endpoint is not generic at all, but the parsing is also highly implementation-specific, I can't imagine it would still work if you change the default index.
