### ISSUE TITLE
Running Jupyter Notebook with PDP does not load other dependencies

### ISSUE THREAD

**Issue by ksinkar** [pdm-project/pdm#3222]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
PDM is installed with ASDF.
OS is GNU/Linux
Distro is Fedora 40
Python is system python which is installed along with Fedora
PEP 582 NOT enabled.

``` bash
pdm add jupyter 
pdm add astropy
pdm run jupyter notebook
```

## Actual behavior

In jupyter notebook running 

``` python
import astropy
```

gives the following error

``` ipynb
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 import astropy

ModuleNotFoundError: No module named 'astropy'
```

## Expected behavior

Importing astropy in jupyter notebook should not give an error.

When I simply run 

``` bash 
pdm run

``` 

I get a python REPL where when I do

``` python
import astropy
```

there is no problem

### pdm info

```bash
PDM version:
  2.19.2
Python Interpreter:
  $HOME/Documents/$PROJECTDIR/.venv/bin/python (3.12)
Project Root:
  $HOME/Documents/$PROJECTDIR/
Local Packages:
```

### pdm info --env
``` bash
{
  "implementation_name": "cpython",
  "implementation_version": "3.12.6",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.11.3-200.fc40.x86_64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Thu Oct 10 22:31:19 UTC 2024",
  "python_full_version": "3.12.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.12",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
make sure the core is selected correctly and why not check the sys.path / sys.executable in the notebook
