### ISSUE TITLE
Support for target option for `pdm install`

### ISSUE THREAD

**Issue by Levelleor** [pdm-project/pdm#3257]
## Is your feature/enhancement proposal related to a problem? Please describe.

I couldn't find any info at all for anything AWS Lambda related using with PDM. AWS lambda requires us to provide a .zip archive for lambda apps that contains all dependencies at root of the archive. Basically what we've been doing is installing packages into a custom target location once preparing the artifact for production with: `pip install --target ./`. 

I also found a relevant [thread for Poetry](https://github.com/python-poetry/poetry/issues/1937) which mentions at the very end that there will be no support for this functionality. However it seems like PDM is doing a lot to be somewhat similar to NPM in specific keypoints and one of the benefits of NPM here is that packages are installed locally in the projects which allows them to be easily uploaded onto lambda if desired. 

Is there support for installing packages into specified directories? Is anything like that planned at all? How do I prepare lambda for deploy to AWS Lambda otherwise?

## Describe the solution you'd like

`pdm install --target ./` (can also use "--output" or "-directory" instead)

> Installs packages directly into specified path, which allows to have them on the same level as application and allows AWS finding packages properly.

**Comment by frostming** [comment]
Try https://github.com/frostming/pdm-packer

**Comment by Levelleor** [comment]
Hey, @frostming , thanks. I will be trying this out but there's this comment out there which I am concerned about:
>If the result zipapp contains binaries, it can only be deployed to the platforms with the same abi, any cross-abi usage of that app might expect a failure.

I am not 100% sure what this means. Does this mean that when I download packages I have to rely on them being platform-specific to work on AWS Lambda? Is it going to be any different than just downloading packages regularly and packing them into .zip manually?

**Comment by frostming** [comment]
@Levelleor It is no worse than `install --target`, which only installs packages for the current platform as well.

I guess you need to make a zipball yourself after installing to a target directory, and that is exactly what `pdm-packer` does.

**Comment by Levelleor** [comment]
Sorry, took me a while to loop back in. 

So this means `pdm-packer` doesn't support platform installations at all right now. If there are platform-specific binaries in some packages it will install them for the current system and wont work on other environments. In my case we're using the `--platform` flag on some applications so this might be a big issue for us.

I am assuming the only other option for my use-case would be to export packages into requirements.txt. From what the documentation says it will not include platform markers on export:
https://pdm-project.org/en/latest/reference/cli/#export

So this should work:
```
pdm export -o requirements.txt
pipx install pip
pip install -r requirements.txt -t /path/to/project
```

Could you please shine some light on the above, @frostming?

**Comment by Levelleor** [comment]
In fact it seems like there is another package that could potentially replace all 3 commands with one:
https://github.com/pdm-project/pdm-download - allows installing packages into a target directory. And has support for platform and implementation flags.

**Comment by frostming** [comment]
> https://github.com/pdm-project/pdm-download - allows installing packages into a target directory

It doesn't "install" but "download", with only `.whl` and `.tar.gz` files

**Comment by Levelleor** [comment]
Oh, that makes sense. Got you.
