### ISSUE TITLE
Limit log file size

### ISSUE THREAD

**Issue by aeisenbarth** [pdm-project/pdm#3262]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

I found a 23GB log file in $HOME/.local/state/pdm/log/pdm-lock-v1caevh9.log

## Steps to reproduce

Use PDM occasionally to install a PDM project with many dependencies (env ca. 6GB).

## Actual behavior

Under whatever circumstances, the log file was able to grow to an unusual size that can impact the performance of the system (e.g. out of space, other applications crash). It was the largest single file on the system, larger than a hand full of VMs.

It was easy to delete, but only after having discovered it by chance. I still think there is something wrong that this could occur.

## Expected behavior

Log files should be negligible, just like those of other software, so that PDM does not require extra maintenance effort.

- The log file could be stored in `~/.cache` (instead of `~/.config`) which falls under regular clean up routines. `$XDG_CACHE_HOME` is for "user specific non-essential data files". Config contains essential files and requires significant effort to clean it without breaking things.

- The log file size could be limited (rotating, dropping older entries), unless the user explicitly declares the intention to preserve full logs e.g. by enabling a non-default log level.

## Environment Information

```bash
PDM version:
  2.17.1
Python Interpreter:
  $HOME/software/miniconda3/envs/my-project-3.10/bin/python (3.10)
Project Root:
  $HOME/git/my-project
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.13",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.0-117-generic",
  "platform_system": "Linux",
  "platform_version": "#127-Ubuntu SMP Fri Jul 5 20:13:28 UTC 2024",
  "python_full_version": "3.10.13",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
1. The log file will be deleted if the command succeeds
2. We do clean older log files when a new log is to be created
3. The default log path is `~/.local/state/pdm/log`(Linux) or `~/Library/Logs/pdm` and you can change it via config or `PDM_LOG_DIR` env.

That's all, I don't think there is any work to do.
