### ISSUE TITLE
Proposal: output similar command when the input command is not correct

### ISSUE THREAD

**Issue by Zheaoli** [pdm-project/pdm#3270]
## Is your feature/enhancement proposal related to a problem? Please describe.

For now, some other package manager will output a similar command when the input command is not correct.

For example

```text
╰─ poetry en

The command "en" does not exist.

Did you mean one of these?
    env use
    env info
    env list
    env remove
```

I think we can add this feature to help people use PDM more friendly

The basic code will be simple, like following below:

```python
distance = SequenceMatcher(None, actual_name, name).ratio()
```

We can calculate the distance by using `SequenceMatcher` in stdlib, and output the ratio >= 0.5

If this proposal has been accepted, I would like to send a PR for this

**Comment by frostming** [comment]
SGTM
