### ISSUE TITLE
More detailed info for 'saved Python interpreter doesn't match the project's requirement'

### ISSUE THREAD

**Issue by jasonhemann** [pdm-project/pdm#3276]
### Feature Description

There seem to be a lot of possible causes that would trigger the following info and warning message:

```
INFO: The saved Python interpreter doesn't match the project's requirement. Trying to find another one.
WARNING: Project requires a python version of >=3.13, The virtualenv is being created for you as it cannot be matched to the right version.
```

It would be nice to tell what facet of the current configuration causes that message to appear---missing ./.venv? only earlier python versions?

I could understand not wanting this information for every user all the time, but maybe at least under the `-v` flag it would be nice to see.

### Problem and Solution

Some info message that would output what's being attempted re: the saved interpreter, so that a user can make better sense of the subsequent output. 

### Are you willing to contribute to the development of this feature?

- [ ] Yes, I am willing to contribute to the development of this feature.

**Comment by frostming** [comment]
PR welcome
