### ISSUE TITLE
OrderedSet `__contains__` is O(N)

### ISSUE THREAD

**Issue by eltoder** [pdm-project/pdm#3280]
### Feature Description

The `OrderedSet` class, used in src/pdm/resolver/graph.py, stores data as a plain list. This means that `__contains__` method runs in O(N) instead of O(1) like in regular sets. This can be quite inefficient if the set contains more than a few items.

### Problem and Solution

The easiest is to store data as keys of a dict.

### Are you willing to contribute to the development of this feature?

- [X] Yes, I am willing to contribute to the development of this feature.

**Comment by frostming** [comment]
PR welcome.
