### ISSUE TITLE
The install cache is invalid and the package cannot be installed through the cache.

### ISSUE THREAD

**Issue by AboutDark** [pdm-project/pdm#3310]
### Describe the bug

Using the pdm add command will re-download the installed package. The cache does not work properly.

### To reproduce

pdm add requests

### Expected Behavior

The corresponding version of the requests package is installed through the cache instead of re-downloading.

### Environment Information

PDM version:
  2.20.1
Python Interpreter:
  venv\Scripts\python.exe (3.12)
Project Root:
 pdmtest
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.12.0",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "11",
  "platform_system": "Windows",
  "platform_version": "10.0.22631",
  "python_full_version": "3.12.0",
  "platform_python_implementation": "CPython",
  "python_version": "3.12",
  "sys_platform": "win32"
}

### pdm -v output

PDM, version 2.20.1

### Are you willing to submit a PR to fix this bug?

- [ ] Yes, I would like to submit a PR.

**Comment by frostming** [comment]
all downloadings are also cached, I don't see what is not working.

**Comment by AboutDark** [comment]
The installed packages are indeed cached. When I use the add command again, these cached packages are not read. They will still be downloaded and installed again through the network. This will cause a lot of network overhead.

**Comment by frostming** [comment]
> They will still be downloaded and installed again through the network. This will cause a lot of network overhead.

Can you confirm that? The HTTP responses are cached so it won't consult the internet even it appears so.

**Comment by AboutDark** [comment]
The http response cache doesn't seem to be working properly. Can you help me check if there is a problem with my configuration?

**Comment by AboutDark** [comment]
I modified the code in my local environment and the package cache has been restored to work. However, the http response is not working properly yet.

**Comment by frostming** [comment]
> The http response cache doesn't seem to be working properly

How did you observe that?

**Comment by AboutDark** [comment]
When I was installing ms-swift, I had to keep installing new packages because the ms-swift dependency package was incomplete. During the installation, it was unusually slow. Through the task manager, I found that the pdm network bandwidth was very large.

**Comment by AboutDark** [comment]
When installing ms-swift, I noticed that due to incomplete dependencies of ms-swift, I had to keep installing new packages. The installation process was exceptionally slow, and through the Task Manager, I found that the network bandwidth usage of PDM was very high.

**Comment by frostming** [comment]
Here is what I tried:

```
pdm config -l install.cache on
pdm add ms-swift
pdm venv create -f 3.11   # recreate a clean virtualenv
```
(Cut off the network)
```
pdm sync
```
All packages are installed successfully offline, proving that no HTTP requests are sent to the internet.

**Comment by AboutDark** [comment]
After installing ms-swift, try installing other packages. Because I installed it multiple times, VPN traffic did consume a lot.

**Comment by AboutDark** [comment]
I'll debug it tonight. Thank you for reproducing this problem.

**Comment by frostming** [comment]
```
pdm add marko
```

Here are the HTTP requests recorded:

```
  GET https://pypi.org/simple/marko/
  GET https://files.pythonhosted.org/packages/ef/9b/3dbfbe6ee255b1c37a37e2a6046adb2e77763a020591dae63e5005a2c8d7/marko-2.1.2-py3-none-any.whl.metadata
  GET https://files.pythonhosted.org/packages/ef/9b/3dbfbe6ee255b1c37a37e2a6046adb2e77763a020591dae63e5005a2c8d7/marko-2.1.2-py3-none-any.whl
```

All seem normal
