### ISSUE TITLE
Support caret and tilde operators for constraining versions

### ISSUE THREAD

**Issue by bayshann-matt-chamberlain** [pdm-project/pdm#3311]
### Feature Description

To be able to constrain dependency versions using the `^` and `~` operators.

Example:
```yaml
[project]

dependencies = [
    "fastapi^0.115.5",
    "pytest~8.3.3",
]
``` 

### Problem and Solution

Current approach is more verbose and less readable than being able to use `~` and `^`. More time consuming to type and maintain.

### Additional Context

Mimic how Poetry and other package managers like NPM work 
  - https://python-poetry.org/docs/dependency-specification/#version-constraints 
  - https://docs.npmjs.com/about-semantic-versioning

### Are you willing to contribute to the development of this feature?

- [ ] Yes, I am willing to contribute to the development of this feature.

**Comment by frostming** [comment]
We are not going to support dependency specifications beyond PEP 508, thanks.

**Comment by bayshann-matt-chamberlain** [comment]
Got it, thanks for clarifying 🙏
