### ISSUE TITLE
Task verbosity change introduce in 2.21 breaks some scripts

### ISSUE THREAD

**Issue by noirbizarre** [pdm-project/pdm#3313]
### Describe the bug

In 2.21, in https://github.com/pdm-project/pdm/pull/3278 more precisely, default scripts verbosity has been changed, and it breaks some existing scripts relying on output:
- all scripts that are output-dependants now needs to run with `-q` (can represent some volume to migrate)
- script called using `pdm <command>` have to migrate to `pdm run -q <command>` to preserve output, `-q` not being available on the shortcut form
- script full command is outputted in addition to the task title, resulting in lots of line lost and broken terminal output when relying on some multiline scripts
- it makes the `-v` flag do nothing more
- It kind of break verbosity consistency as everywhere else command echo/feedback is only available with detailed verbosity (ex: https://github.com/pdm-project/pdm/blob/main/src/pdm/cli/commands/venv/backends.py#L72-L75)

### To reproduce

- create a script outputting some formatted data (JSON, CSV, ...) > not parsable anymore without `-q`
- create a script spanning on multiple lines > same amount of lines is prepended in addition to the title
- create a composite script, with optionally pre or post hooks > output is now having 2 extra lines by task hook (assuming they are single line scripts)

### Expected Behavior

One of:
1. default script behavior just run the script without decoration, echoing script name and command line being by definition verbosity
2. this behavior is opt-in, aka. no output as default, a user setting allows enabling this when not verbose, but remain whatever the setting value in verbose mode
3. this behavior is opt-in and progressive, aka. no output as default, a user setting allows disabling the task name only in normal, and the full output remain in verbose mode whatever the setting value

(The third one is having my preference)

### Environment Information

PDM version:
  2.21.0
Python Interpreter:
  <redacted workdir>/.venv/bin/python (3.11)
Project Root:
  <redacted workdir>
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.12.7",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.11.9-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Sun, 17 Nov 2024 16:06:17 +0000",
  "python_full_version": "3.11.9",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}

### Additional Context

Given I also understand some people like having tasks feedback by default, this PR is to start discussing what should be the solution, choose a setting name (`scripts.echo` ? `scripts.display_name` ? `scripts.always_show_name` ?) if a setting-based solution is accepted.

### Are you willing to submit a PR to fix this bug?

- [X] Yes, I would like to submit a PR.

**Comment by frostming** [comment]
Yes, I should have discussed it clearly with the author in the PR, but out of some laziness, I didn't.

I tend to think the five points posted here makes more sense to me. @guru-desh You should read it to understand how other users are using this feature. And I would like to know what you think of it

**Comment by guru-desh** [comment]
These 5 points make sense to me as well. I like the idea of having a user-setting control. I think that using `[tool.pdm.options]` could solve this issue. For users that want to have the task name and command outputted by default, users could simply add the following to `pyproject.toml`:

```toml
[tool.pdm.options]
run = ["--verbose"]
```

Else, users that do not want verbosity by default don't need to add this section in `pyproject.toml`

I think the easiest way to resolve this is by doing the following:
1. Reverting PR #3278 
2. Adding a section in the [scripts documentation](https://pdm-project.org/en/latest/usage/scripts/) about how users can default verbosity when running scripts.

Thoughts?

**Comment by frostming** [comment]
> I think the easiest way to resolve this is by doing the following:

I have no objections, either you or @noirbizarre PR welcome.

**Comment by guru-desh** [comment]
I don't mind making the PR. @noirbizarre does the proposed solution work for you?

**Comment by noirbizarre** [comment]
I thought about it and I don't think options are a good approach, here's my reasoning:
- choosing whether you want to display task heading or not is in my opinion a personal preference, while anything in a `pyproject.toml` is shared by all contributors
- display related settings like theme are already defined in the [configuration](https://pdm-project.org/en/latest/reference/configuration/)
- config scales better because you can define your settings once and for all globally of by project (cf. https://pdm-project.org/en/latest/usage/config/#configuration-files)

So I made a proposal PR in #3315 (which includes a suggestion of a colleague preferring to display the help instead of task title)
