### ISSUE TITLE
Repositories configurable in pyproject.toml

### ISSUE THREAD

**Issue by farndt** [pdm-project/pdm#3335]
### Feature Description

Repositories can be configured in pyproject.toml. The credentials are read from the OS credential stores via keyring.

### Problem and Solution

Problem:
According to https://pdm-project.org/en/latest/usage/config/#configure-the-repositories-for-upload repositories are only configurable via config.toml or environment variables. If developers are working on different python projects that all need to upload to different repositories, all developers must configure the repos individually. With the option of configuring this within pyproject.toml for **pdm**, it would be possible to share the configuration. Use case in company.

Solution:
```toml
[[tool.pdm.repo]]
name = "company"
url = "https://artifactory.company.com/artifactory/api/pypi/remote"
```

`pdm publish --repository company` to start publishing.

**Keyring** will read pdm-repository-company from Credential Store to receive _username_ and _password_

### Are you willing to contribute to the development of this feature?

- [X] Yes, I am willing to contribute to the development of this feature.

**Comment by lorenzosciarra** [comment]
Hi @frostming, can you make an example of how this allows to include repository configuration into pyproject.toml files? I can't figure it out other than putting it into a pdm.toml file, which I would like to use only for the credentials. Thank you in advance.
