### ISSUE TITLE
Cache dependency lists of resolved packages.

### ISSUE THREAD

**Issue by zerosignal0101** [pdm-project/pdm#3340]
### Feature Description

Resolve the dependency requirements of already resolved packages using the cached list of dependencies, instead of downloading the full package from PyPI or other package distribution sites.

### Problem and Solution

When add or remove packages in the project, pdm will resolve all packages from PyPI or pytorch website and fully download these packages. For example "nvidia-cudnn-cu12" or "torch==2.5.1", these big packages will take up some time (normally 5mins) and large bandwidth to resolve, which is quite laggy for dependency management as well as demanding for CDNs. 

```
Removing packages from default dependencies: fairseq
Changes are written to pyproject.toml.
0:02:00 Resolve for environment (==3.11.*) 2 resolved, 50 to resolve
Resolving nvidia-cudnn-cu12 9.1.0.70
```

I searched the doc of pdm and only found `install.cache` which use cached wheel installation, but for resolve process, cache will not be used. So I think it might be much quicker to extract dependency lists for resolved packages ,store the lists to cache directory and resolve the dependencies from cached dependency lists. 

Since I am not very familiar with package dependency resolution, I would like to ask if this enhancement is appropriate or if I have overlooked any configuration related to caching.

### Are you willing to contribute to the development of this feature?

- [ ] Yes, I am willing to contribute to the development of this feature.

**Comment by frostming** [comment]
We do cache package metadata, read the code https://github.com/pdm-project/pdm/blob/21375cd65753f03f4d8ba18d7ddde88f3e77873b/src/pdm/models/repositories/base.py#L38-L48

You can also see the cache stats by `pdm cache info`

**Comment by zerosignal0101** [comment]
I use pdm with conda virtual env. Maybe the integration with conda has some defects in cache function. I will try to figure out the cause.

Thanks for your reply.
