### ISSUE TITLE
PDM misdetects platform tag, leading to version selection that breaks resolution

### ISSUE THREAD

**Issue by sanmai-NL** [pdm-project/pdm#3341]
### Describe the bug

```
DEBUG Searching for a compatible version of torch (>=2.2.2, <3.0.0)
DEBUG Selecting: torch==2.5.1 [preference] (torch-2.5.1-cp312-cp312-manylinux1_x86_64.whl)
```

This happens on macOS x86_64, the latest torch version that's available for this platform is 2.2.2.

### To reproduce

```
pdm install
```

### Expected Behavior

Selection of compatible `torch` version (2.2.2).

### Environment Information

```
PDM version:
  2.21.0
Python Interpreter:
  /Users/myuser/app/.venv/bin/python (3.12)
Project Root:
  /Users/myuser/app
Local Packages:
```
  
 ```json
{
  "implementation_name": "cpython",
  "implementation_version": "3.13.0",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "23.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:00 PDT 2024; root:xnu-10063.141.2~1/RELEASE_X86_64",
  "python_full_version": "3.12.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.12",
  "sys_platform": "darwin"
}
```
  

### Additional Context

Full repository at https://gitlab.com/han-aim/research/knowledgeplatform/app/-/tree/ea2d531552edb9f8832d83a564203d92274186b6

### Are you willing to submit a PR to fix this bug?

- [X] Yes, I would like to submit a PR.

**Comment by sanmai-NL** [comment]
Possibly related: https://github.com/pdm-project/pdm/issues/3234

**Comment by frostming** [comment]
You didn't mention but apparently you are using `uv` mode.

**Comment by sanmai-NL** [comment]
Yes that is true, I don't think it has to do with unearth (but I suppose the problem is in the lockfile, and I don't know the exact interaction between PDM and uv in generating that).

**Comment by sanmai-NL** [comment]
Is this related? https://github.com/pdm-project/pdm/issues/2696

**Comment by frostming** [comment]
I can't reproduce using the main branch, can you confirm?

**Comment by sanmai-NL** [comment]
I would like to, do you have instructions on how to run it for my colleague?

**Comment by frostming** [comment]
> @frostming I would like to, do you have instructions on how to run it for my colleague?

Instructions on run what?

**Comment by sanmai-NL** [comment]
How to install PDM from the main branch, on macOS.

**Comment by sanmai-NL** [comment]
She uses PDM from Homebrew.

**Comment by frostming** [comment]
> She uses PDM from Homebrew.

```
brew install --HEAD pdm
```

**Comment by sanmai-NL** [comment]
@frostming The fault persists on her system. I'm still trying to get hold of the log. The new uv resolution overrides functionality did provide a workaround, by the way.

**Comment by sanmai-NL** [comment]
@frostming 
[bugreport.log](https://github.com/user-attachments/files/18064078/bugreport.log)

**Comment by frostming** [comment]
The issue exists in the lock file, and there is no torch version compatible with MacOS 14 x86_64.

In fact, I forgot to mention in the docs that cross-platform lock targets are unavailable in UV mode. You may need to remove the MacOS x86_64 target, turn off uv mode, and run `pdm lock --append --platform macos_14_0_x86_64` to fix the lock file.

**Comment by sanmai-NL** [comment]
@frostming Thanks. There does exist a compatible `torch` version: v2.2.2. When the lockfile is deleted an regenerated on the system, the fault pops up too.

**Comment by sanmai-NL** [comment]
Context for the interested reader: https://github.com/astral-sh/uv/issues/3347
