### ISSUE TITLE
Publish wheel without tarball

### ISSUE THREAD

**Issue by khasrusn** [pdm-project/pdm#3347]
### Feature Description

Hello everyone! Thanks for the great project management tool. I have a question about publishing packages: how can I publish only the wheel (without building the tarball)? I know that I can build only the wheel with the following command:

`pdm build --no-sdist`

But for publishing I can't use this keyword.

### Problem and Solution

`pdm publish --no-sdist`

### Are you willing to contribute to the development of this feature?

- [ ] Yes, I am willing to contribute to the development of this feature.

**Comment by frostming** [comment]
```
pdm build --no-sdist && pdm publish --no-build
```
