### ISSUE TITLE
Pack CI job failed in forked project's Actions

### ISSUE THREAD

**Issue by Georgehu716** [pdm-project/pdm#3349]
I forked the PDM project and enabled GitHub Actions in my fork, using the same CI workflow as the original project. While the Testing job passed successfully, the Pack job failed.

Here is the error message: https://github.com/Georgehu716/pdm/actions/runs/12251619247/job/34176598451

```
Run pdm pack
  pdm pack
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.1[2](https://github.com/Georgehu716/pdm/actions/runs/12251619247/job/34176598451#step:5:2).7/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/[3](https://github.com/Georgehu716/pdm/actions/runs/12251619247/job/34176598451#step:5:3).12.7/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.7/x6[4](https://github.com/Georgehu716/pdm/actions/runs/12251619247/job/34176598451#step:5:4)
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.7/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.7/x[6](https://github.com/Georgehu716/pdm/actions/runs/12251619247/job/34176598451#step:5:6)4
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.7/x64/lib
WARNING: Project requires a python version of >=3.9, The virtualenv is being created for you as it cannot be matched to the right version.
INFO: python.use_venv is on, creating a virtualenv for this project...
Virtualenv is created successfully at /home/runner/work/pdm/pdm/.venv
Packing packages...
STATUS: Resolving packages from lockfile...
[AttributeError]: 'Core' object has no attribute 'synchronizer_class'
WARNING: Add '-v' to see the detailed traceback
Error: Process completed with exit code 1.
```

It seems the issue is due to the installed PDM version being less than 2.19, as indicated here: https://github.com/frostming/pdm-packer/blob/1d050b88c40ff407b9e8ed9c20b93d879e01cf12/src/pdm_packer/env.py#L56. 

In my CI environment, the installed PDM version appears to be `PDM, version 0.1.dev2981+g07a402d`. However, I am not sure how this version was determined or calculated. Could someone help me understand how to resolve this issue and successfully pass the Pack job in my project's CI workflow?

**Comment by frostming** [comment]
The version is calculated from the last git tag of the repo so the tags need to be kept when forking the repo.
However, your repo doesn't contain any tags.
