### ISSUE TITLE
Should strategy config cover strategy in lockfile?

### ISSUE THREAD

**Issue by monchin** [pdm-project/pdm#3363]
### Describe the bug

Currently, when `pdm config strategy.inherit_metadata` is true, while `"inherit_metadata"` not in "metadata" of pdm.lock, groups info would not be added in the lockfile, and vice versa, when `pdm config strategy.inherit_metadata` is false, while `"inherit_metadata"` in "metadata" of pdm.lock, groups info would be added in the lockfile. To be honest, it confuses me in the past.

### To reproduce

set `pdm config use_uv false`, and set `pdm config strategy.inherit_metadata true`, init a project and `pdm add numpy`, then delete "inherit_metadata" in "strategy" in `pdm.lock`, and run `pdm lock`

### Expected Behavior

"groups" info appears in the lockfile

### Environment Information

pdm 2.22.1
python 3.10.12

### Additional Context

I'm not sure whether it is designed to be so deliberately or it is just a bug, but IMHO, config level should be higher than the lockfile, and when the two contradict, config should prevail.

If it is a feature, I think we should add some hints or warning when pdm finds the contradiction. Or we should fix it.

### Are you willing to submit a PR to fix this bug?

- [X] Yes, I would like to submit a PR.

**Comment by frostming** [comment]
This is intentional, lockfile metadata to "remember" the config when you generate the lock file and keep consistent between runs. While pdm config only controls how to generate a "new" lock file.
