### ISSUE TITLE
Running `pdm install` results in `AttributeError` on nonexistent `PosixPath.filepath`.

### ISSUE THREAD

**Issue by rduplain** [pdm-project/pdm#355]
## Issue

Running `pdm install` on various projects (haven't found one that works) results in :

```
[AttributeError]: 'PosixPath' object has no attribute 'filepath'
```

## Resolution

Cut a release, as it appears that you've fixed this in f6aa9c6c6ad4109a9336c73c94c7d8afe95c638b.

In pdm/project/metadata.py:

```diff
-            return Metadata._read_pyproject(filepath)
+            return super()._read_pyproject()
```

Footnote: The underlying issue is that `Metadata._read_pyproject(self)` needs a `Metadata` object as `self`, which has a `filepath` attribute, and the code was previously passing the `filepath` as `self`. Naturally, the call to `super()` fixes this.

## Environment Information

Reproduced the bug on macOS as well.

```bash
$ pdm info && pdm info --env
PDM version:        1.4.4                                     
Python Interpreter: .../.pyenv/shims/python (3.9.2)
Project Root:       .../src/pdm                    
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.2",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.8.0-45-generic",
  "platform_system": "Linux",
  "platform_version": "#51~20.04.1-Ubuntu SMP Tue Feb 23 13:46:31 UTC 2021",
  "python_full_version": "3.9.2",
  "platform_python_implementaiton": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

:warning: While we are here, there's a typo in `platform_python_implementaiton`.

**Comment by rduplain** [comment]
Workaround:

```
pip install pdm==1.4.2
```

**Comment by frostming** [comment]
I thought downgrading `pdm-pep517<0.6.0` would do the trick.

**Comment by knowsuchagency** [comment]
Can confirm the regression was introduced in `1.4.3`

**Comment by frostming** [comment]
It was fixed in https://github.com/pdm-project/pdm/releases/tag/1.4.5
