### ISSUE TITLE
Version is set to 0.0.0 in local build

### ISSUE THREAD

**Issue by rmsc** [pdm-project/pdm#386]
I'm creating a package for Archlinux based on release v1.4.5. Given that this is for the system package manager, I need to build it locally.

Since there are no build instructions in the README, I've tried two approaches:
- using a `setuptools` workflow
- using `build` for building and `pip` for installing

In both approaches the package builds without errors, but the package version is set to `0.0.0`.

### setuptools (EDIT: + dephell)
In the `setuptools` + `dephell` workflow I'm doing the following:
```bash
$ dephell deps convert --from pyproject.toml --to setup.py
$ python setup.py build
$ python setup.py install --root="$pkgdir" --optimize=1 --skip-build
```
Not only is the package version set to `0.0.0`, but  the `pdm` script isn't even installed.

### build + pip
In the `build`+ `pip` I'm doing the following:
```bash
$ python -m build --skip-dependencies --sdist .
$ pip install (...) dist/pdm-1.4.5.tar.gz
```
In this case `pip install`fails because the version is `0.0.0` so the `pdm-1.4.5.tar.gz` file isn't even there.

However if I do `$ pip install (...) dist/pdm-0.0.0.tar.gz` then the `pdm` tool does get installed, but with the wrong version.

**Comment by frostming** [comment]
The first approach shouldn't have even worked because there is no `setup.py`, how did you get that file?

And for the second approach, `git` should be available on the `PATH`

**Comment by rmsc** [comment]
> The first approach shouldn't have even worked because there is no `setup.py`, how did you get that file?

Sorry, I was also using `dephell`. It was way past bedtime.. I've edited original description.

> And for the second approach, `git` should be available on the `PATH`

But it is:
```bash
$ which git
/usr/bin/git
```

**Comment by rmsc** [comment]
I think I figured it out, I'm building from the release package, which doesn't have a `.git`directory!

Perhaps in the release tarball `version` should be hardcoded? Now I think this is actually a bug.

**Comment by frostming** [comment]
Oh, are you getting tarball from the GitHub releases? You should get a standard source distribution which can be found at PyPI: https://pypi.org/project/pdm/#files

**Comment by rmsc** [comment]
I am, good catch! I've avoided using those because the `tests` are stripped from them. I thought it made sense to run the tests when creating the package. That said, I had trouble running some of those tests, so I'm skipping them for now.

Would it make sense to do the same version hardcoding for the github release?

**Comment by frostming** [comment]
This may require some change of the CI workflow, at this point, you can manually amend the `pyproject.toml` file.

**Comment by rmsc** [comment]
Sure, I've worked around this by using `sed`. The question was more towards the next release.

In any case thanks for the help!

**Comment by frostming** [comment]
I have included `tests` directory in the latest uploaded source distribution: https://pypi.org/project/pdm/1.5.0/#files

Close this issue now
