### ISSUE TITLE
Install for production

### ISSUE THREAD

**Issue by thernstig** [pdm-project/pdm#391]
## Is your feature request related to a problem? Please describe.

Most dependency managers have a `--production` (or similar) flag to only install for production. A normal `install` without that flag install all dependencies (production + development).

Looking at https://pdm.fming.dev/usage/dependency/#install-the-packages-pinned-in-lock-file this is confusing.

## Describe the solution you'd like

I would like it to mimic how other tools does this and believe this tool incorrectly took the approach of pipenv. See https://github.com/pypa/pipenv/issues/3093#issuecomment-432718562 for more reference of tools (the entire thread is interesting).

The reason is that developers are bound to want to install all (production + dev) dependencies in their daily work. A `pdm install`  is thus quicker to write. It also mimics most (all?) other package managers out there.

**Comment by frostming** [comment]
This might be worth considering, any thoughts? @pohlt @pawamoy @linw1995

**Comment by pohlt** [comment]
Unless there are good reasons for not doing so, pdm should try to resemble the behavior of most other package managers, so +1 for the suggestion.

But I don't have a good overview of the other package managers.

**Comment by linw1995** [comment]
pypa/pipenv#3093 is interesting and gives me some thoughts about this feature request. We should take more care of these CLI API changes. We don't want this feature request to break the current APIs due to compatibility. And they are hard to co-exist. I  prefer the current CLI APIs because of being more precise and neat for usage.

Maybe make it optional for users to choose what CLI API patterns for usage. Pro mode for the users like me who want the dependencies' installation more precisely. And a common mode for the users who love to use PDM easily because of having common APIs which are similar to the other tools.

Therefore, this feature request will be able to co-exist with the old APIs instead of removing them or making confusion.

And below are features of the common APIs. (This part needs further discussion)

* `pdm run` will sync packages
* `pdm install` and `pdm sync` will install dev default and default packages (maybe including all optional packages)
* `pdm install --deploy` and `pdm sync --deploy` for installing default packages.

**Comment by frostming** [comment]
Thanks for the advice

> `pdm run` will sync packages

I am against this approach, as it would require adding options and flags of `install/sync` to `run` command, too.

> `pdm install` and `pdm sync` will install dev default and default packages (maybe including all optional packages)

Extra dependencies must be given explicitly since they are not required at the most time.

None of the mentioned package manager has so many dependency groups as PDM has, so the commands to install dependencies can be relative simple, only `--production` or not. `run` command can also imply installing all packages. But it is not the case in PDM. we have `--dev`, optional-dependency groups and dev dependency groups. Every time user runs `install`, he /she should specify which groups are desired to install.

As we are at the stage of beta testing of a big release with already-have behavior changes. So it is not so surprising that `pdm install` changes the default dependency set to install. We will emit a warning to users that the `pdm install` equals to `pdm install -d` before and you have to use `--deploy` to achieve the same behavior before.

Another point: when `--deploy` is passed, should we demand strict matching between pyproject.toml and pdm.lock and abort if they don't match? This is what `pipenv install --deploy` does

**Comment by thernstig** [comment]
In addition, I cannot see the install options mentioning the word `production` anywhere. I believe this is super-important to be clear when `production` packages are installed. Are they what you call `default`? And then you call development dependencies `dev default`?

The reason for being explicit about production is that many companies (such as mine) require you to go through a process to record all the FOSS packages used in production, due to legal reasons. So there should be no ambiguitiy to what packages are production packages in the .toml file containing the packages (with a flag or something). So if I do a `pdm install --production` I will know I only install those.

**Comment by pohlt** [comment]
In general, PDM should not worry to much about backward compatibility _now_. It's a relatively young project in its beta phase. Once we get to 1.x and broader adoption, we will all be glad that we did the breaking changes back in 2021 and can enjoy a consistent and efficient user experience for the years to come.

**Comment by frostming** [comment]
In fact, it is likely that I would switch to CalVer at some point 🤣 https://hynek.me/articles/semver-will-not-save-you/

**Comment by frostming** [comment]
BTW, can `--production` be used with `-d`? @thernstig

**Comment by thernstig** [comment]
I'd say it installs both production and development deps in the first case, and also the optional `doc` in the second. The first case would be the same as `pdm install`.

Note that e.g. npm v7 has these options https://docs.npmjs.com/cli/v7/commands/npm-install:
`--omit=<type>`

(But this project cannot compare 1-to-1 to that since you have a separate command to actually add packages).

**Comment by pawamoy** [comment]
command |  what it does
--- | ---
1- pdm install | installs prod and dev deps (not optional prod deps)
2- pdm install -s hello | installs prod and dev deps, as well as hello optional prod group
3- pdm install -d | installs prod and dev deps (not optional deps), redundant with °1
4- pdm install -ds hello | installs prod deps and hello group of dev deps
5- pdm install --production | installs only prod deps
6- pdm install --production -s hello | installs prod deps and hello optional prod group
7- pdm install --production -d | does not make sense
8- pdm install --production -ds hello | does not make sense

Seeing these, I feel like if we go for a `--production` flag, the `-d` flag should be removed.
Sections should have different names between prod groups and dev groups, allowing `-s` to match prod groups and/or dev groups.

Lets shorten `--production` to `-p` in this example. This would give us this:

command |  what it does
--- | ---
1- pdm install | installs prod and dev deps (no prod groups)
2- pdm install -s prodgroup1 | installs prod deps, dev deps, and "prodgroup1" prod group
2- pdm install -s devgroup1 | installs prod deps and only "devgroup1" dev group
2- pdm install -s prodgroup1 -s devgroup1 | installs prod deps, "prodgroup1" prod group and "devgroup1" dev group
5- pdm install -p | installs only prod deps
6- pdm install -p -s hello | installs prod deps and "hello" prod group. if "hello" is a dev group, fails

**Comment by pawamoy** [comment]
It all revolves around production and/or development dependencies. Default should be both, they flags are introduced to (un)select one or the other.

**Comment by thernstig** [comment]
@pawamoy I do not understand item 2 above. The only difference between that and 1. is that you want to install the optional group, so why is it not installing both dev AND prod in that instance?

**Comment by thernstig** [comment]
@pawamoy regarding the "unselect" part would it then not be better to have `--omit=<type>` as npm? That does not pollute everything with a ton of flags, and is quite clear what it does, and extensible with more than just the three initial "omit" flags you propopsed.

**Comment by frostming** [comment]
@thernstig
> then not be better to have `--omit=<type>` as npm

No, npm only has 3 types of deps: prod, dev and optional, which are all selected by default. But PDM unselects optional prod deps, and selects dev optional deps(with this proposal) by default, and users want to select only a few of them the most of time.

CLI flags should be a supplement to the default behavior.

Now we have `--section` to select groups(positive), `--dev` to select dev groups(positive) and `--no-default` to unselect prod deps(negative), `--production` seems to be negative(or `--no-dev`?)

**Comment by thernstig** [comment]
As we are into the topic of `npm install`, I must ask why `-s/--section` was chosen, when you call it `groups` in the docs: https://pdm.fming.dev/usage/dependency/ - I do not think terminology used to describe something not matching CLI semantics is great, unless there is a strong reason to not match them. Why not just make it `-g/--group` to be consistent what is is referred to as in the docs?

**Comment by frostming** [comment]
> I must ask why -s/--section was chosen, when you call it groups in the docs:

Makes sense, I will update doc to use "sections"

**Comment by frostming** [comment]
This is what I wrote in #394 to describe the behavior change, paste it here to clarify:

| Command                         | What it does                                                        | Comments                    |
| ------------------------------- | ------------------------------------------------------------------- | --------------------------- |
| `pdm install`                   | install prod and dev deps(no optional)                              |                             |
| `pdm install -s extra1`         | install prod deps, dev deps, and "extra1" optional section          |                             |
| `pdm install -s dev1`           | install prod deps and only "dev1" dev section                       | redundant `-d` can be given |
| `pdm install -s:all`            | install prod deps and "extra1", "extra2" optional section           |                             |
| `pdm install -ds:all`           | install prod deps and "dev1", "dev2" dev section                    | `-d` can't be omitted       |
| `pdm install -s extra1 -s dev1` | install prod deps, "extra1" optional section and "dev1" dev section |                             |
| `pdm install --prod`            | install prod only                                                   |                             |
| `pdm install --prod -s extra1`  | installs prod deps and "extra1" optional                            |                             |
| `pdm install --prod -s dev1`    | Fail, `--prod` can't be given with dev dependencies                 | Leave the `--prod` option   |

**Comment by thernstig** [comment]
> > I must ask why -s/--section was chosen, when you call it groups in the docs:
> 
> Makes sense, I will update doc to use "sections"

Are you opposed to calling it groups and making it `-g/--group` ? It feels like a more natural term for what it is. Just an idea.

**Comment by frostming** [comment]
`-s/--section` is a thing from the birth of this project, when each group of dependencies have its own table in `pyproject.toml`, like this:

```toml
[tool.pdm.doc-dependencies]
mkdocs = "*"

[tool.pdm.test-dependencies]
pytest = "*"
```

They are actual "sections" in the project file.

**Comment by thernstig** [comment]
I do understand that. Still I ponder if groups would not make more sense? See how you even said "each group of dependencies" - it is an instinct to use "group" for it 😆 It might be very subjective of course.

**Comment by frostming** [comment]
Unfortunately, the short option `-g` is occupied by `--global`, so switching to `--group` doesn't benefit. Maybe we can change the full name of `-s` to `--select`, sounds intuitive yeh?

**Comment by thernstig** [comment]
@frostming that might work. But if you keep calliing it sections then `--section` makes most sense of course 😃
