### ISSUE TITLE
Generic question: Pipenv vs pdm

### ISSUE THREAD

**Issue by thernstig** [pdm-project/pdm#392]
This is a generic question but I suppose it is interesting for the community. As one who has used Pipenv as well as Poetry during the past years, I've seen the "controversy" between these tools and how they evolved.

It has also been obvious that @frostming as the main author of PDM also worked on Pipenv for the longest of time (and still is looking at the latest commits).

So my question is:

How come pipenv was not "fixed" instead and what are the reasons for you to work on both projects?

Note: I am no way critizing this decision to start a new package! I think it is good and this one seems very promising, especially with the performance gains and the PEP 582 support!

**Comment by frostming** [comment]
It is an interesting topic I would like to leave some comments on.

I think the most important reason that motivates me to build a new package manager is the decision made by Pipenv that can hardly change after adopted by so many projects -- the core components are all run in a subprocess approach. Specifically, the installer is `pip`, and the resolver is `piptool`. It means you can only build a relative THIN wrapper around the component without big changes. On the contrary, Poetry builds these components on its won making it a large monolithic project that has a lot of things to keep track of. Poetry also comes with a `pyproject.toml` spec which is not so consistent to me( `python` as a dependency and optional dependencies syntax). While PDM takes the core functionalities from `pip` and `resolvelib` and combines them to form the installer/builder and resolver respectively. It has much more flexibility and less maintenance burden.

Another pain point about Pipenv is the test suite. If you take a look at Pipenv's CI you can find it takes ~50min to run 230 test cases only. Why are they so slow? Most of the cases are integration tests that should be run from a real shell process and the initialization of Pipenv costs much. This also makes it impossible to collect the coverage of the tested code. I am just tired to change a single line of code and wait for up to 1 hour to see the testing result.

The last point is I want to do some pioneer experiments of the Python packaging system, such as PEP 582 and PEP 621. Future proposals such as installation backend and editable installation protocol will also be expected to land in PDM after the PEP is finalized.

Hope you can have more sight of why PDM exists and take a chance to try it!

**Comment by thernstig** [comment]
Sounds good @frostming thanks for the answer. Maybe this would make a good chapter at the end of the readme or in the docs.

What are the reasons you continue working on pipenv? I'd guess your energy is best left for this great tool instead. Obviously I a in no place to tell you what to do, but it is out of curiosity.

**Comment by frostming** [comment]
Out of the responsibility, given the large user base of Pipenv,  but only critical issues will be handled.

**Comment by thernstig** [comment]
That is a valiant approach, kudos to you. Hopefully PDM takes of like a rocket leaving you with more time here.

Aside: The only concern I have with pep 582 right now is that everyone have to run a "pdm run" instead of just a "path/to/python/file" which users are used to when having an activated environment. But hopefully in due to time Python recognizes `__pypackages__` by default, making it a moot point.

**Comment by frostming** [comment]
Why not try enabling PEP 582 globally, you can find the instruction in the [README](https://github.com/pdm-project/pdm#quickstart)

**Comment by thernstig** [comment]
I see, it is about setting `eval $(pdm --pep582)`. Didn't find it clear that was the issue solved first time I read it, but now I see. Anyhow I will close this thread. Maybe it serves a good purpose for future readers to have your answers here. At least you can link to it if someone asks :)
