### ISSUE TITLE
Switch to Calendar Versioning

### ISSUE THREAD

**Issue by frostming** [pdm-project/pdm#395]
## Rationale

Currently, many projects related to Python packaging are CalVer'd. Among them, there are `pip`, `virtualenv`. `pipenv`.

Also, there are some articles explaining why SemVer isn't so good:

- https://bernat.tech/posts/version-numbers/
- https://hynek.me/articles/semver-will-not-save-you/
- https://snarky.ca/why-i-dont-like-semver/

## Specification

PDM is also a heavy CLI app that has no guarantee of backward compatibility. Commands and options may change from time to time. So, PDM would also likely follow this pattern. We choose a three-part CalVer: `<year>.<month>.<seq>`, where:

- `year` is a two-digit number representing the year.
- `month` is a number without leading zeros
- `seq` is a 0-indexed number representing the sequence of release in this month

**Example**

`21.5.0` The first release of May 2021
`21.5.1` The second release of May 2021.

## Downsides?

The dramatic jump of version number may scare people.

## When will it be changed.

The final decision isn't made yet. It may happen at around mid-2021.

**Comment by pawamoy** [comment]
These posts were very interesting, thank you. Particularly in Brett's post, the note about Elm being able to tell if the API changed at compile time. It gave me the idea of bringing such verifications to Python packages. For example if you autogenerate your API docs with Sphinx+autodoc or MkDocs+mkdocstrings, you could tell that if something was renamed or removed, it would need a major bump (semver). Maybe we could write a new dedicated tool for this: list all the public modules, classes, functions and methods and their signatures, hash it, and compare with previous release hash.

**Comment by pohlt** [comment]
While I agree with the general reservations against SemVer, CalVer makes live more difficult for people (like me) developing software in a regulated environment (healthcare). You have to go through a release process for each package you are using (PDM is "only" a dev tool, but still) and typically, you have to repeat this process for each major release.

I'm wondering if there is not some middle ground: If a new version does not change the API, has no new functionality, but only fixes bugs, safety or installation issues for certain packages, you could just increase the sequence number.

Anyway, I can see that this is only a niche application and that SemVer just does not live up to its promises. I just wanted to give you some context why some people might advocate for SemVer.

**Comment by abersheeran** [comment]
> These posts were very interesting, thank you. Particularly in Brett's post, the note about Elm being able to tell if the API changed at compile time. It gave me the idea of bringing such verifications to Python packages. For example if you autogenerate your API docs with Sphinx+autodoc or MkDocs+mkdocstrings, you could tell that if something was renamed or removed, it would need a major bump (semver). Maybe we could write a new dedicated tool for this: list all the public modules, classes, functions and methods and their signatures, hash it, and compare with previous release hash.

That's cool! In a code I wrote for the company, I used git to achieve a similar function. I never thought that this could also be applied to open source projects. This is really a great idea.

**Comment by andrewebdev** [comment]
I personally prefer calendar versioning, I use that for my own projects these days. I really like that fact that you can extrapolate the date something was published from the version number and much prefer that.

**Comment by frostming** [comment]
The next release 1.6.0 will be around the first week of June, which is a coincidence that it fits with the calendar. 🎉

**Comment by clarfonthey** [comment]
Even though it'd be longer, I'd highly recommend going with the full year as the first year to make it clear that it's a year and not just rapid-churn semver.
