### ISSUE TITLE
Little typo - at a prominent place ;-)

### ISSUE THREAD

**Issue by AXGKl** [pdm-project/pdm#396]
Hey, 

a million thanks for PDM  - I'm blown away by this!

You want to fix this one, first impression is very important:

----

![2021-04-16_1020x337_scrot](https://user-images.githubusercontent.com/9989548/115029211-0f292500-9ec6-11eb-8fb4-089d2c1d6730.png)

----

Also, minor, this one:

![2021-04-16_1172x463_scrot](https://user-images.githubusercontent.com/9989548/115029860-b5752a80-9ec6-11eb-8f7b-b7b6293ec55f.png)

(and maybe note there that grouped dev dependencies are not yet supported in the pipx installed pdm version - until they are. That led to a bit frustration, until I found out that I need the git version of pdm, so that `pdm install -d -s <dev dependency>` works)

**Comment by frostming** [comment]
Fixed, thanks for the reminder. The fresh features are live in the beta releases. Get it with `--pre` flag(for pipx, use `--pip-args='--pre'`.

Look forward to the 1.5.0 release which will likely be out next week.

**Comment by AXGKl** [comment]
Thanks for the `--pre` hint, did not know.

PS: Your productivity is crazy, but take my advice: Try to not overdo it - this will be a marathon, not a sprint, and I see you are actively involved in pipenv as well...
