### ISSUE TITLE
Packages exported result keeps changing order randomly.

### ISSUE THREAD

**Issue by linw1995** [pdm-project/pdm#401]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

After upgrading 1.5.0 from 1.5.0b1, I discover the exported requirements.txt file keep changing every time. 
(I use pre-commit to automatically generate requirements.txt while the `pdm.lock` file changing)

I look into the codes about packages exporting. 
And I find out the `translate_sections` function added recently that returns the result sections in random order every time.

https://github.com/pdm-project/pdm/blob/f7650b0d4f8fa1f190d42dfaf4825a5fae8f4467/pdm/cli/utils.py#L464-L485

Replacing `return list(sections)` with `return sorted(sections)` maybe the easiest way to fix this problem.
And I'd be happy to help.

Sorts the result sections in ascending order to ensure the incoming steps like packages installation will be performed in order instead of in random order. And **the same command of PDM will take the same effect.**

## Steps to reproduce

1. initialize a dummy project via PDM
2. randomly add some packages with different sections
3. run "pdm export -f requirements -s ..." twice times to export two requirements.txt files
4. compare two requirements.txt files

## Actual behavior

Got two different files.

## Expected behavior

Two files are identical.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.5.0
Python Interpreter: /nix/store/7pjbbmnrch7frgyp7gz19ay0z1173c7y-python3-3.9.2/bin/python (3.9)
Project Root:       /Users/linw1995/Documents/opensources/pdm
Project Packages:   /Users/linw1995/Documents/opensources/pdm/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.2",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "20.3.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64",
  "python_full_version": "3.9.2",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
Sure thing. Thank you.
