### ISSUE TITLE
Using pdm.lock.toml instead of pdm.lock

### ISSUE THREAD

**Issue by xareelee** [pdm-project/pdm#431]
## Is your feature request related to a problem? Please describe.

A feature request: Using **pdm.lock.toml** instead of **pdm.lock**

PDM generates `.toml` files (`.pdm.toml` and `pyproject.toml`), but not for `.lock` file. This would make `.lock` file not highlighten in IDE. I knew using `.lock` is convention; just propose my idea.

I'm using VSCode, and there is a plugin **Better TOML** which can highlight code for `.toml` files. Using file extension `.toml` for lockfile would make code be easier to read with highlighten code, and be comment-out-able by IDE using shortcut (e.g. `cmd + /` on Mac).

You can make this feature to be optional; set up this config in `pyproject.toml`:

```toml
[tool.pdm]
lockfile="pdm.lock.toml"
```

**Comment by frostming** [comment]
It is a thing of editor support, `Pipfile.lock`(JSON) and `poetry.lock` don't have correct suffix either but they can be highlighted rightly.

We are not going to change this.
