### ISSUE TITLE
statically-typed Requirement class

### ISSUE THREAD

**Issue by danieleades** [pdm-project/pdm#433]
would be nice if the `pdm.models.requirements.Requirement` class was statically typed. That is, defined *without* the use of `setattr`. This allows static type checkers such as mypy to lint code which uses this class.

in order to do this, i need to know the types of each of the attributes.

```python
class Requirement:
    """Base class of a package requirement.
    A requirement is a (virtual) specification of a package which contains
    some constraints of version, python version, or other marker.
    """

    attributes = (
        "vcs",
        "editable",
        "name",
        "specifier",
        "specs",
        "marker",
        "extras",
        "key",
        "project_name",
        "url",
        "path",
        "ref",
        "revision",
        "index",
        "version",
        "allow_prereleases",
        "from_section",
    )

    def __init__(self, **kwargs: Any) -> None:
        self._marker = None
        self.from_section = "default"
        self.marker_no_python: Optional[Marker] = None
        self.requires_python = PySpecSet()
        for k, v in kwargs.items():
            if k == "specifier":
                v = get_specifier(v)
            setattr(self, k, v)
        if self.name and not self.project_name:
            self.project_name = safe_name(self.name)
            self.key = self.project_name.lower()
```

judging from the usage, i'm guessing the majority of these will be `Optional[...]=None`, correct?

The trick will be to do this in a way that doesn't involve copying and pasting a massive parameter list in every subclass...
Possibly by using a `dataclass`

looking at this a little further, it seems that `Requirement` is a base class, but it contains the *superset* of parameters of its subclasses. for example the `vcs` parameter- surely this only belongs in the `VcsRequirement` subclass?

**Comment by danieleades** [comment]
The trick will be to do this in a way that doesn't involve copying and pasting a massive parameter list in every subclass...
Possibly by using a `dataclass`

**Comment by frostming** [comment]
> i'm guessing the majority of these will be Optional[...]=None, correct?

Correct.

> Possibly by using a dataclass

Yes, dataclass is a good approach

> for example the vcs parameter- surely this only belongs in the VcsRequirement subclass?

Yes, but we put them in the base class so that accessing the attribute won't raise errors for all requirements.

**Comment by danieleades** [comment]
> Yes, but we put them in the base class so that accessing the attribute won't raise errors for all requirements.

That seems like a real abuse of polymorphism. Are there examples of where derived class attributes need to be accessed from the baseclass, or from different derived classes? Can this be refactored to use a different approach?

**Comment by frostming** [comment]
> > Yes, but we put them in the base class so that accessing the attribute won't raise errors for all requirements.
> 
> That seems like a real abuse of polymorphism. Are there examples of where derived class attributes need to be accessed from the baseclass, or from different derived classes? Can this be refactored to use a different approach?

You can start refactoring with dataclass and we will see what usage is left accessing the missing attributes.
