### ISSUE TITLE
Configure cache directory with an environment variable

### ISSUE THREAD

**Issue by pawamoy** [pdm-project/pdm#435]
## Is your feature request related to a problem? Please describe.

In CI, my scripts run without a proper user set (no HOME), so the cache directory end up being `/.cache`, which triggers PermissionDenied errors. Looking at [this table](https://pdm.fming.dev/configuration/#available-configurations) (which is absolutely fantastic to have, thanks), it seems that the cache directory, contrary to other settings, cannot be configured using an environment variable. Is there a reason for this? Maybe the docs simply don't state it while it exists?

Currently the only option is to run `pdm config cache_dir /my/cache/directory` in each CI job.

## Describe the solution you'd like

Instead of having to run the pdm config command, I'd prefer configuring this with an environment variable, once and for all jobs.

**Comment by pawamoy** [comment]
I need this even more now, because it turns out I can't even run `pdm config cache_dir /my/cache/directory` since PDM then tries to write the config in `/.pdm`, for which I also get a PermissionDenied error :confused:

**Comment by pawamoy** [comment]
I was able to work around this:

```bash
export HOME=/tmp/home
mkdir -p $HOME
pdm config cache_dir /tmp/.pdm_cache
```

It would definitely be easier to be able to do `PDM_CACHE_DIR=/tmp/.pdm_cache` 😄 
I guess more users could face the same issue in CI.

By the way, you should probably try to respect the XDG config instead of using `Path.home() / ".pdm"` for PDM config directory, but that's another issue.

**Comment by frostming** [comment]
I guess this single line would do the trick:

```bash
export HOME=/tmp/home
```

**Comment by pawamoy** [comment]
Oh, I see. Setting the HOME variable will actually allow PDM to create the `$HOME/.pdm` and `$HOME/.cache/pdm` directories without a permission error. I'll try that, thank you @frostming 🙂

**Comment by frostming** [comment]
Close this since a workaround is provided. `PDM_CACHE_DIR=xxx pdm install` looks not so good to me. It breaks the centralized cache assumption and `pdm cache` commands can't manage them correctly.
