### ISSUE TITLE
Extract name and version from egg info

### ISSUE THREAD

**Issue by frostming** [pdm-project/pdm#441]
An egg info is a filename with the pattern `<name>-<version>`

**Comment by linw1995** [comment]
For this case https://github.com/pdm-project/pdm/pull/429#discussion_r624702158, it would be better if we implement it by accessing the PKG-INFO file in source distribution file?

**Comment by frostming** [comment]
> For this case [#429 (comment)](https://github.com/pdm-project/pdm/pull/429#discussion_r624702158), it would be better if we implement it by accessing the PKG-INFO file in source distribution file?

Yes it would be better

**Comment by frostming** [comment]
There is a problem with reading PKG-INFO, it requires to download that file.
