### ISSUE TITLE
PyPy

### ISSUE THREAD

**Issue by fjbardelli** [pdm-project/pdm#481]
Is it possible to use pdm to publish a package in pypy?

**Comment by frostming** [comment]
I guess so, although I don't use pypy myself and the support is not guaranteed by CI. You can just try it.

**Comment by fjbardelli** [comment]
in de command list, there is no command to publish, the generated package

**Comment by frostming** [comment]
There isn't. But it is easy to do with twine upload, why bother adding a command

**Comment by blueyed** [comment]
Note: this appears to be about PyPI, not PyPy.

**Comment by frostming** [comment]
> Note: this appears to be about PyPI, not PyPy.

lol, maybe you are right. I think I've also answered that. Close it now
