### ISSUE TITLE
Manage Python version

### ISSUE THREAD

**Issue by bolinocroustibat** [pdm-project/pdm#483]
I am conscious that it is a very utopian and broad feature request, but it would be great if PDM could also manage different Python versions, a bit like Pyenv does except using the official `requires-python` metadata from `pyproject.toml`, as defined in [this section of PEP621](https://www.python.org/dev/peps/pep-0621/#requires-python).

**Comment by frostming** [comment]
It is not in the scope of PDM. We would like to give users the freedom how to install Python, and PDM can work perfectly with pyenv.
