### ISSUE TITLE
Allow specification of "trusted host" in pyproject.toml

### ISSUE THREAD

**Issue by ArminGruner** [pdm-project/pdm#488]
Hi, I need to add some project dependencies from our gitlabs installation, which uses a self-signed certificate.

I can instruct 'pip' with --trusted-host so does it not abort with a SSL verify error.
Of course I also can add it to the pip.conf file.
So, as PDM also (always?) uses PIP to retrieve/install the dependencies, I can make "pdm add" work for sites with a broken/expired/self-signed SSL certificate.

Though, on a fresh checkout of a project I'd prefer that this is self-contained, i.e. if I add a dependency with PDM to pyproject.toml, check it out on another machine later, it should work as well, even without manually modifying/creating a PIP config file.

Is there already a way to e.g. specify "trusted-host" like in pip.conf?
Or a generic way to specify project specific pip parameters in pyproject.toml?
Does PDM always use PIP to download/install dependencies?
Or may SSL verify be disabled by other means?

**Comment by frostming** [comment]
Check this: https://pdm.fming.dev/pyproject/tool-pdm/#specify-other-sources-for-finding-packages

**Comment by ArminGruner** [comment]
Awww.. thanks for the pointer! I was sure that you already solved this somehow ;-)  Thanks for creating PDM!

**Comment by ArminGruner** [comment]
Hm, I think I need a bit more hints on how to use it in my context:

As a dependency, I use

`pypackage @ git+https://gitlab.internal.int/pypackage.git @ git-hash
`

So, how do I translate this into a dependency which can be resolved ignoring any SSL verify errors?

Obviously, the package is constructed "on the fly", and gitlab does not provide some kind of a PyPI package index.. 
so i cannot list it as a package repository as an [[tool.pdm.source]] array element..

Greetings, Armin

**Comment by frostming** [comment]
We don't support trust-host in arbitrary URLs. You have to configure your tools locally:

```bash
git config --type=bool --get-urlmatch http.sslverify https://gitlab.local/pypackage.git false
```
