### ISSUE TITLE
Confusing/duplicated wording?  "Adding packages to dev dev-dependencies"

### ISSUE THREAD

**Issue by blueyed** [pdm-project/pdm#496]
Using `pdm add -d …` says: "Adding packages to dev dev-dependencies".

I think it should say "main dev-dependecies" there probably, but am not sure.

Code ref: https://github.com/pdm-project/pdm/blob/d6c12142d05034898a07d90c293f9f5aaded658b/pdm/cli/actions.py#L185-L198

pdm, version 1.6.3.dev4+gd6c1214

**Comment by frostming** [comment]
It would go to the "dev" group under "dev-dependencies", so what would you suggest?

**Comment by blueyed** [comment]
Yeah, it is documented like this: https://pdm.fming.dev/usage/dependency/#add-development-only-dependencies

I've thought that it would be redundant, but is also clear/explicit in the end then.

It might be clearer if it was also named "default" there (with the message).

Closing for now though.
