### ISSUE TITLE
Documentation on how best to "deploy" a pdm project using e.g. Docker

### ISSUE THREAD

**Issue by steve-marmalade** [pdm-project/pdm#498]
## Is your feature request related to a problem? Please describe.

I have been using PDM to manage dependencies for my recent python projects and have been really enjoying it! It's way faster than Pipenv and I like that it doesn't require creating/sourcing virtualenvs for everything. 

I am now looking to deploy my project in a Docker container, and have created this Github Issue for advice on the recommended way to do this.

My current strategy:
```Dockerfile
# Install system-wide dependencies
SHELL ["/bin/bash", "-c"]
RUN pip install pdm && pdm --pep582 >> ~/.bashrc
ENV PYTHONPATH=/usr/local/lib/python3.9/site-packages/pdm/pep582

# Install project-specific dependencies
COPY pyproject.toml pyproject.toml
COPY pdm.lock pdm.lock
RUN pdm sync --production
```

## Describe the solution you'd like

Two requests:

1. Is the way I am doing it above even the best way? Maybe I should be using `pdm install` ? Would it make sense to add a section to the docs for Docker best practices?
2. I definitely do not want end-users of this container to need to be aware of PDM at all. As a result, you can see I am making an effort to ensure that e.g. the PYTHONPATH is updated, so that folks don't get any surprising "ModuleNotFound" errors. **Perhaps `pdm` could add a `deploy` sub-command, which would install all dependencies into the global python environment (i.e. not using `__pypackages__`) ?**

**Comment by steve-marmalade** [comment]
Maybe one recommendation would be to export a requirements file before building the container, that way the Dockerfile can completely remove the dependency on PDM?

```bash
pdm export --prod --format requirements --pyproject > requirements.txt

# Dockerfile copies the requirements file and pip installs it globally
docker build .
```

**Comment by frostming** [comment]
For the 1st request, it is OK, using `pdm install` may update pdm.lock without awareness during build. So `pdm sync` is preferred on deployment that only honors the lock file.

> Would it make sense to add a section to the docs for Docker best practices?

That is great, there is already some existing in https://github.com/pdm-project/pdm/blob/main/docs/docs/usage/advanced.md I think you can reorganize that part of doc.

For the 2nd request, any of the following one is OK for deployment:

1. Install into `__pypackages__` and enable PEP 582
2. Install into the global site-packages by `pdm sync --global`
3. export a requirements.txt and use it in docker build.

**Comment by frostming** [comment]
Since there is no more follow-up for this issue, I'm closing it now
