### ISSUE TITLE
`pdm add 'pdm[doesnotexist]'` warns (ExtrasError), but adds dependency

### ISSUE THREAD

**Issue by blueyed** [pdm-project/pdm#499]
After the following `"pdm[doesnotexist]~=1.6"` gets added to dependencies in pyproject.toml, while I think it could/should abort before creating/updating the lock file:
```
% pdm add 'pdm[doesnotexist]'
Adding packages to default dependencies: pdm[doesnotexist]
Updating the whole lock file as it is not compatible with PDM
⠹ Resolving dependencies
…/.venv/lib/python3.9/site-packages/pdm/models/requirements.py:416: ExtrasError: Extras not found: ('doesnotexist',)
✔ 🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 21 to add, 0 to update, 0 to remove

  ✔ Install pip 21.1.2 successful
…
  ✔ Install toml 0.10.2 successful

🎉 All complete!
pdm add 'pdm[doesnotexist]'  11.33s user 0.97s system 47% cpu 25.885 total
```

Note that the warning (ExtrasError) does not show up anymore on a second run (also with a clean project), since it apparently gets cached.

**Comment by frostming** [comment]
PDM treats non-existing extras as soft errors(warnings) that don't abort.

**Comment by blueyed** [comment]
Ok, fair enough.  What's the reasoning behind it though?  (And could it be done always, regardless of caching - mostly for consistency / to avoid confusion?)

In my specific/actual use case I've used `django-storages[django]` instead of `django-storages[google]` accidentally, and ran into an error/bug when trying to also add the correct one then.  (The bug likely being due to having the same package twice with different extras or similar - I can try to reproduce it, and create a separate issue then.)

**Comment by frostming** [comment]
No special reason, I just found it no-harm if one installs `package[non-exist]` and finally gets `package` installed only.
