### ISSUE TITLE
[feat] Consider adding get-pdm.py or install-pdm.py to make installation simpler for users

### ISSUE THREAD

**Issue by yihong0618** [pdm-project/pdm#508]
Like poetry.

![image](https://user-images.githubusercontent.com/15976103/122493091-a8d19780-d019-11eb-9ff2-b1714f037e7b.png)

**Comment by frostming** [comment]
In fact, we can publish a single file `.pyz` so that people can download and run without installing any dependencies, except a Python must be present.
