### ISSUE TITLE
Extract package name and version

### ISSUE THREAD

**Issue by iocentos** [pdm-project/pdm#527]
**Problem**

I am trying to integrate pdm with our CI server. Currently, for every pip package that we want to publish we have a flow where we dynamically extract the package name and version and use those to make few different checks.

We do that we the following commands
`python ./setup.py --version`
`pyrhon ./setup.py --name`

As we are now migrating to pyproject.toml with pdm, I am trying to find a way to dynamically get that info. I see that pdm has the `show` flag but this one requires a package name. Ideally we would like to get that dynamically.

**Proposal**

Change the behavior of the `show` flag to show the current package by default (if no package name is specified). On top of that allow for different options to be used to extract specific info of a given package (for example `--version`, `--name` etc).

All the following would be valid commands
`pdm show --version`
`pdm show --name`
`pdm show my-package --version`
`pdm show`
`pdm show my-package`

**Comment by frostming** [comment]
Sounds good to me.
