### ISSUE TITLE
Error installing odmantic 

### ISSUE THREAD

**Issue by frepond** [pdm-project/pdm#529]
## Steps to reproduce

`pdm add odmantic`

## Actual behavior

KeyError: "There is no item named 'ODMantic-0.3.5.dist-info/WHEEL' in the archive

## Expected behavior

Package odmantic installed

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.6.4
Python Interpreter: /Users/frepond/.asdf/installs/python/3.9.4/bin/python3 (3.9)
Project Root:       /private/tmp/test
Project Packages:   /private/tmp/test/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.4",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "20.5.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64",
  "python_full_version": "3.9.4",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
odmantic's wheel name is ODMantic-0.3.5 while dist-info name is `odmantic-0.3.5.dist-info`, but `distlib` expects them to be the same. I would categorize this issue as an upstream issue.

**Comment by frepond** [comment]
Hi @frostming is there any workaround for this? Thanks.

**Comment by SwiftWinds** [comment]
I'm getting the same issue with the package `PyFunctional`. Would a workaround be possible?
