### ISSUE TITLE
pdm init -- python interpreter option doesn't display all installed version

### ISSUE THREAD

**Issue by jamestansx** [pdm-project/pdm#539]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. initialize pdm
2. Try to select python interpreter version 3.9.0
![image](https://user-images.githubusercontent.com/45304579/125448309-4cd81acb-cec2-40dc-96bd-7eafa0e9e708.png)

## Actual behavior

No path ```C:/Users/jamestansx/.pyenv/pyenv-win/versions/3.9.0/python.exe``` to be selected for python 3.9.0.

## Expected behavior

There should be an option for python 3.9.0

## Environment Information

```pdm is not initialized``` 
```bash
# Paste the output of `pdm info && pdm info --env` below:

```

**Comment by jamestansx** [comment]
Now I have initialized pdm and manually update ```.pdm.toml```.  

pdm info:
````
PDM version:        1.6.4                                                             
Python Interpreter: C:/Users/jamestansx/.pyenv/pyenv-win/versions/3.9.0/python.exe (3.9)
Project Root:       D:/Projects/pycal-gui                                             
Project Packages:   D:\Projects\pycal-gui\__pypackages__\3.9  
````

pdm info --env:
````{
  "implementation_name": "cpython",
  "implementation_version": "3.9.0",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19041",
  "python_full_version": "3.9.0",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "win32"
}
````

**Comment by frostming** [comment]
> Now I have initialized pdm and manually update `.pdm.toml`.

You don't have to do this way, you can use `pdm use <path_to_python>` to set the interpreter path.

For the original problem, just need to know the interpreter must be exposed somewhere for `pythonfinder` to find. On Windows, it may come from two sources:

1. Exposed in `PATH` env var.
2. Findable on winreg

I haven't used `pyenv-win` before and I don't know how it install pythons, it is likely they are not exposed in either of the above.

**Comment by jamestansx** [comment]
[pyenv-win](https://github.com/pyenv-win/pyenv-win) is just a pyenv that is ported to Windows, so after searching, 

> Exposed in PATH env var.

I found that ```pythonfinder``` will look for ```PYENV_ROOT``` that I didn't set up. So after I added ```PYENV_ROOT``` to env, now the result looks like this:

![image](https://user-images.githubusercontent.com/45304579/125548374-f2db9019-19ee-464a-b88e-4e9f927a57e9.png)

which looks quite like #406

**Comment by frostming** [comment]
AFAICT pythonfinder don't support pyenv-win yet. Care to report an issue there?

**Comment by jamestansx** [comment]
Ok, will report this issue at there.

**Comment by jamestansx** [comment]
In ```pyenv-win install```, there is an option ```-r``` to add python to the registry.  Hence, by disabling ```python.use_pyenv``` every python installed with ```pyenv-win``` can be found. 

Closing this issue 
Thanks
