### ISSUE TITLE
Can this be used with devcontainers?

### ISSUE THREAD

**Issue by mr-rodgers** [pdm-project/pdm#542]
I can't seem to find a valid way to use this tool within a devcontainer (VS Code).

The main issue seems to be that the tool locks down the `pyproject.toml` and `pdm.lock` files to the executing user with `rw-/---/---` permissions. If you mount the project directory inside a docker container and then run `pdm add *` from inside the container, this means that the files will be locked so that they can only be read by `root` on the host. This then causes any subsequent rebuild of the container to fail, as these files are copied empty by the docker daemon, which in turn causes the tool to fail in installation.

I contrast this to `poetry`, which respects the umask (doesn't force the permissions to `rw-/---/---`) on pyproject and doesn't suffer from this same issue.

**Comment by frostming** [comment]
Thanks for catching this, a fix is on the way
