### ISSUE TITLE
Author name is not reflected correctly

### ISSUE THREAD

**Issue by carstencodes** [pdm-project/pdm#545]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

Wheel and setuptools both set different fields for the name and the email of the author. 

When running pdm, name and email are both crunched to the email field while the name field is left untouched

## Steps to reproduce

Here's a simple pyproject.toml:

```toml
[project]
name = "author-issue"
version = "0.1.0"
description = ""
authors = [
    {name = "John Doe", email = "john.doe@foo.bar" },
]
dependencies = []
requires-python = ">=3.8"
dynamic = ["classifiers"]
license = {text = "MIT"}

[project.urls]
homepage = ""

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
```

Running pdm build and pdm export -f setuppy leaves the name field empty:

### pdm export -f setuppy

```py

# -*- coding: utf-8 -*-
from setuptools import setup

long_description = None

setup_kwargs = {
    'name': 'author-issue',
    'version': '0.1.0',
    'description': '',
    'long_description': long_description,
    'license': 'MIT',
    'author': '',
    'author_email': 'John Doe <john.doe@foo.bar>',
    'maintainer': None,
    'maintainer_email': None,
    'url': '',
    'package_data': {'': ['*']},
    'classifiers': [
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
    ],
    'python_requires': '>=3.8',

}


setup(**setup_kwargs)
```
### pdm build

Here's the METADATA of the resulting wheel

 Metadata-Version: 2.1
 Name: author-issue
 Version: 0.1.0
 Summary: UNKNOWN
 License: MIT
 Author-email: John Doe <john.doe@foo.bar>
 Requires-Python: >=3.8
 Classifier: License :: OSI Approved :: MIT License
 Classifier: Programming Language :: Python :: 3
 Classifier: Programming Language :: Python :: 3.8
 Classifier: Programming Language :: Python :: 3.9
 Project-URL: homepage,

### pdm export -f setuppy

```py

# -*- coding: utf-8 -*-
from setuptools import setup

long_description = None

setup_kwargs = {
    'name': 'author-issue',
    'version': '0.1.0',
    'description': '',
    'long_description': long_description,
    'license': 'MIT',
    'author': 'John Doe',
    'author_email': 'john.doe@foo.bar',
    'maintainer': None,
    'maintainer_email': None,
    'url': '',
    'package_data': {'': ['*']},
    'classifiers': [
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
    ],
    'python_requires': '>=3.8',

}


setup(**setup_kwargs)
```

### pdm build

Here's the METADATA of the resulting wheel according to https://packaging.python.org/specifications/core-metadata/

 Metadata-Version: 2.1
 Name: author-issue
 Version: 0.1.0
 Summary: UNKNOWN
 License: MIT
 Author: John Doe
 Author-email: john.doe@foo.bar
 Requires-Python: >=3.8
 Classifier: License :: OSI Approved :: MIT License
 Classifier: Programming Language :: Python :: 3
 Classifier: Programming Language :: Python :: 3.8
 Classifier: Programming Language :: Python :: 3.9
 Project-URL: homepage,

## Environment Information

```bash
PDM version:        1.6.4                                                     
Python Interpreter: /usr/bin/python3.8 (3.8)                                  
Project Root:       /home/user/dev/test/pdm/author-issue                   
Project Packages:   /home/user/dev/test/pdm/author-issue/__pypackages__/3.8

{
  "implementation_name": "cpython",
  "implementation_version": "3.8.10",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.4.0-77-generic",
  "platform_system": "Linux",
  "platform_version": "#86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021",
  "python_full_version": "3.8.10",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}

```

**Comment by pawamoy** [comment]
Unfortunately I think it matches the spec: https://www.python.org/dev/peps/pep-0621/#authors-maintainers

**Comment by carstencodes** [comment]
Ok, I didn't notice that. Thanks for clarification.
