### ISSUE TITLE
ModuleNotFoundError: No module named 'toml'

### ISSUE THREAD

**Issue by cblessing24** [pdm-project/pdm#546]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

Create the following `Dockerfile`:
```Dockerfile
FROM ubuntu:20.04

# Fix for https://github.com/actions/virtual-environments/issues/2803
ENV LD_PRELOAD=/lib/x86_64-linux-gnu/libgcc_s.so.1
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y \
    curl \
    build-essential \
    python3.9 \
    python3.9-distutil \
    python3.9-dev
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py \
    && python3.9 get-pip.py \
    && rm get-pip.py \
    && python3.9 -m pip install --upgrade pip
RUN python3.9 -m pip install pdm==1.6.4
RUN pdm sync -v
```

Build the image using `docker build .`

## Actual behavior

`ModuleNotFoundError` is raised because `toml` module can not be imported.

## Expected behavior

No error is raised.

## Environment Information

The environment should be fully specified by the `Dockerfile`.

**Comment by frostming** [comment]
Fixed on release 1.7.0
