### ISSUE TITLE
PDM_PYTHON_PATH not working as expected

### ISSUE THREAD

**Issue by dongkeren** [pdm-project/pdm#576]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

PDM_PYTHON_PATH=/some/path/to/python pdm install -v

## Actual behavior

PDM_PYTHON_PATH was ignored by pdm. You can search "PDM_PYTHON_PATH" in the source code and it turns out it only appears in configuration.md but none in code.

## Expected behavior

Should use PDM_PYTHON_PATH as python intepreter when specified.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

```
PDM version:        1.7.2
Python Interpreter: /Users/dkr/Code/kungfu/extensions/sim/../../framework/core/dist/kfc/kfc (3.7)
Project Root:       /Users/dkr/Code/kungfu/extensions/sim
Project Packages:   /Users/dkr/Code/kungfu/extensions/sim/__pypackages__/3.7
{
  "implementation_name": "cpython",
  "implementation_version": "3.7.10",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "20.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64",
  "python_full_version": "3.7.10",
  "platform_python_implementation": "CPython",
  "python_version": "3.7",
  "sys_platform": "darwin"
}

**Comment by frostming** [comment]
It is named `PDM_PYTHON`, the doc should be fixed, thanks

**Comment by dongkeren** [comment]
True, thanks
