### ISSUE TITLE
Unsupported shell: sh in alpine linux (busybox shell)

### ISSUE THREAD

**Issue by Bruceforce** [pdm-project/pdm#597]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

Hi,

first let me thank you for this great project. I stumbled across this because of your article in <https://dev.to/frostming/a-review-pipenv-vs-poetry-vs-pdm-39b4> and the performance and ease of use is just great. However after trying to perform the `pdm --pep582` command in an alpine linux container I stumbled across the following issue.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```sh
docker run --rm -it python:3.8-alpine /bin/sh
apk add curl && curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python - && export PATH=/root/.local/bin:$PATH && pdm --pep582
```

## Actual behavior

```
Traceback (most recent call last):
  File "/root/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/root/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 194, in main
    return Core().main(args)
  File "/root/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 134, in main
    print_pep582_command(self.ui, options.pep582)
  File "/root/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/cli/actions.py", line 657, in print_pep582_command
    raise PdmUsageError(
pdm.exceptions.PdmUsageError: Unsupported shell: sh, please specify another shell via `--pep582 <SHELL>`
```

## Expected behavior

Shell should be detected I guess.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.7.2
Python Interpreter: /usr/local/bin/python (3.8)
Project Root:       /
Project Packages:   /__pypackages__/3.8
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.11",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "4.19.0-16-amd64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Debian 4.19.181-1 (2021-03-19)",
  "python_full_version": "3.8.11",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}

```

**Comment by frostming** [comment]
`pdm --pep582` only supports a limited set of shells and it is not worth supporting more than that. You can anyway manually manipulate `PYTHONPATH` env var by adding `/path/to/lib/pdm/pep582` to the front.

**Comment by Bruceforce** [comment]
Thanks for the fast reply. Just wanted to bring this up since I found nothing by googling.

Feel free to close this (I just didn't close this because I don't know how you prefer to handle "Won't fix" stuff).
