### ISSUE TITLE
Support build extensions

### ISSUE THREAD

**Issue by abersheeran** [pdm-project/pdm#632]
## Is your feature request related to a problem? Please describe.

Sometime, python project need use C/Cython/MyPyC or other tools to build package.

After reading pdm's document, I don't found config about this.

## Describe the solution you'd like

Just like `poetry`:

```toml
[tool.poetry]
build = "speedup.py"
```

```python
# speedup.py
def build(setup_kwargs):
    setup_kwargs.update(..........)
```

**Comment by frostming** [comment]
Similar: https://pdm.fming.dev/pyproject/tool-pdm/#build-c-extensions

**Comment by abersheeran** [comment]
I apologize for my eyes. Thank you for your reply.

**Comment by sanmai-NL** [comment]
@frostming That webpage is now gone. Where to look nowadays?

**Comment by frostming** [comment]
@sanmai-NL https://pdm-backend.fming.dev/build_config/#run-setuptools
