### ISSUE TITLE
Cannot specify --no-binary

### ISSUE THREAD

**Issue by frafra** [pdm-project/pdm#637]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

`pdm add psycopg2`

## Actual behavior

`psycopg2-binary` is added usually.

## Expected behavior

It would be nice to be able to install `psycopg2` as non-binary. `pip` has a flag for that: https://www.psycopg.org/docs/install.html#change-in-binary-packages-between-psycopg-2-7-and-2-8

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.8.2                  
Python Interpreter: /usr/bin/python3 (3.8) 
Project Root:       /app                   
Project Packages:   /app/__pypackages__/3.8
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.6",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "4.15.0-147-generic",
  "platform_system": "Linux",
  "platform_version": "#151-Ubuntu SMP Fri Jun 18 19:21:19 UTC 2021",
  "python_full_version": "3.8.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
Since PDM is using pip under the hood, so setting env var `PIP_NO_BINARY='psycopg2'` would do the trick.
