### ISSUE TITLE
Reuse/Cache the library files

### ISSUE THREAD

**Issue by yingbo** [pdm-project/pdm#638]
## Is your feature request related to a problem? Please describe.

If I have many projects (e.g. 20 project), they all use the same version of python(e.g. 3.8.6), and they all use a same library (e.g pandas). Each of the project has it's own copy of pandas, so the pandas is being duplicated multiple times.

I hope there is a much less copy of the same library under a same python version. 

## Describe the solution you'd like

Just a thought: can we have a global cache: e.g. /foo/bar/Cache/3.8/pandas/1.3.2/, and whenever a project is using the same pandas, we just symbol link the cache to the project's lib position. In the java eco, the maven or gradel has the similar cache idea.

**Comment by frostming** [comment]
if you read the changelog, you will find it's already supported.

**Comment by yingbo** [comment]
Is it #589? I haven't tried PDM but sounds so exciting! This is the major pain point on poetry.

**Comment by frostming** [comment]
Yes, why not give it a try now?

I am going to close this feature request now.

**Comment by yingbo** [comment]
Hi @frostming , I tried the cache  with py3.9 and tensorflow 2.6, got an error. I guess it's a similar problem as #623. Must be some libraries problem.
