### ISSUE TITLE
Provide a way to update content_hash in pdm.lock without updating

### ISSUE THREAD

**Issue by blueyed** [pdm-project/pdm#642]
In case of merge conflicts you might have to update the `content_hash` based on the merged result (if not taking one alternative completely).

There appears to be no command to update/verify/rewrite the lock file without updating it, is there?

I've tried `pdm lock`, which does not have `--no-update` like e.g. poetry.  I think this could be a good option here also?

(I've also tried `pdm update --update-reuse`, but it would still update versions.)

As far as I can see it gets done currently implicitly with `pdm install`:

> Lock file hash doesn't match pyproject.toml, regenerating...

**Comment by blueyed** [comment]
I think it would be useful if this would also update the hashes, e.g. when you've added/changed sources.
(I can create a new issue / feature request if needed, but thought it is very much related to this issue here already)

**Comment by frostming** [comment]
#1019
