### ISSUE TITLE
`python -m venv .venv` not installing setuptools into virtualenv if installed in `__pypackages__` already

### ISSUE THREAD

**Issue by blueyed** [pdm-project/pdm#661]
Creating a virtualenv while having set `PYTHONPATH=/home/user/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/pep582` does only install pip into it, which results in errors when using pip later:
```
% rm -rf .venv; python -m venv .venv; ls .venv/lib/python3.9/site-packages 
pip/  pip-21.2.3.dist-info/
```

It works when not setting PYTHONPATH:
```
% rm -rf .venv; env -u PYTHONPATH python -m venv .venv; ls .venv/lib/python3.9/site-packages
_distutils_hack/  distutils-precedence.pth  pip/  pip-21.2.3.dist-info/  pkg_resources/  setuptools/  setuptools-57.4.0.dist-info/
```

This appears to be triggered by setuptools being installed in `__pypackages__`:
```
% python -c 'import setuptools; print(setuptools)'
<module 'setuptools' from '/home/user/Vcs/pdm/test-editable/__pypackages__/3.9/lib/setuptools/__init__.py'>
```

This happened for me in a project, and also in a smaller test project (test-editable above), but for some yet unknown reason not within the working tree of pdm itself (which also has setuptools being installed in `__pypackages__`).

## Environment Information

```bash
% pdm info
PDM version:        1.8.5
Python Interpreter: /usr/bin/python3 (3.9)
Project Root:       …/Vcs/pdm/test-editable
Project Packages:   …/Vcs/pdm/test-editable/__pypackages__/3.9
% pdm info --env
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.7",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.13.13-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT Thu, 26 Aug 2021 19:14:36 +0000",
  "python_full_version": "3.9.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
venv shouldn't co-exist with `__pypackages__`

**Comment by blueyed** [comment]
Is this a hard limitation?

FWIW, the change in behavior is triggered by updating setuptools 56.2.0 -> 58.1.0.  The former is currently used by pdm.  I could try to bisect it, but makes no sense if you think this should not work anyway.

From what I can tell a `.venv` in a project is a good way to install additionally packages, without going through pdm itself (i.e. only for local tinkering, e.g. using pdb++).

**Comment by blueyed** [comment]
The problem with pip in the venv then is this:
```
% .venv/bin/pip install wmctrl                                                                                                                                 (csd@3.9.7)
Collecting wmctrl
  Using cached wmctrl-0.4.tar.gz (5.4 kB)
    ERROR: Command errored out with exit status 1:
     command: …/project/.venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bz4513ag/wmctrl_c5b21330242a4c37818784cb57433818/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bz4513ag/wmctrl_c5b21330242a4c37818784cb57433818/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-nbhq9bg1
         cwd: /tmp/pip-install-bz4513ag/wmctrl_c5b21330242a4c37818784cb57433818/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a5/48/bd9b5c4c0d865e5d143f91020600f921c37f9755c8101336d292e1de1252/wmctrl-0.4.tar.gz#sha256=66cbff72b0ca06a22ec3883ac3a4d7c41078bdae4fb7310f52951769b10e14e0 (from https://pypi.org/simple/wmctrl/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached wmctrl-0.3.tar.gz (2.5 kB)
    …
ERROR: Could not find a version that satisfies the requirement wmctrl (from versions: 0.1, 0.2, 0.3, 0.4)
ERROR: No matching distribution found for wmctrl
```

From what I guess it is related to this running in an isolated tmp dir, where `__pypackages__` is not available anymore then.

**Comment by frostming** [comment]
Because You probably want `__pypackages__` to be loaded even when venv python is used. This benefits in many ways such as debugging and REPL tools installed within an *isolated* env(pipx) can be used cross-project.

**Comment by blueyed** [comment]
Sure, I want the `.venv/bin/python` to use it also, that's my idea.

It should just not be used when creating the venv I guess, so `env -u PYTHONPATH python -m venv .venv` is a good enough workaround for now.

However, I think the behavior change due to a setuptools upgrade is suspicious, and maybe even not wanted (i.e. a bug/regression).

I also assume that the `venv` module could become more aware of this, and/or the PEP being refined in this regard to address/improve this.

**Comment by blueyed** [comment]
It looks like setuptools 57.3.0 is good/old, and 57.4.0 is bad/new.  Compare view: https://github.com/pypa/setuptools/compare/v57.3.0..v57.4.0
This does not really look suspicious to me though.

**Comment by blueyed** [comment]
The change in behavior is due to the requirement of `pip` being 57.4.0 with Python 3.9.7..
I.e. it is not setuptools really being involved here, but only `ensurepip` not installing it if it is already, and therefore the issue only being not triggered when using an older setuptools within `__pypackages__`, and `ensurepip --upgrade` adding it then (which apparently gets skipped when the other one is newer already).

**Comment by frostming** [comment]
@blueyed Thanks for the investigation, it makes much sense. But I don't know how PDM can improve the situation.

**Comment by blueyed** [comment]
@frostming you're welcome, glad to hear that it makes sense.. :)

I do not know how `pdm.pep582` is involved there really (and could mess with paths/setup if it detects this situation), but apparently it boils down to the venv not being created independently really (with regard to having its own pip).

Likely a good fix might be to use a more isolated pip run (similar to pip's isolated builds, in a temporary directory), or use `--force-reinstall` as an arg to pip-install in ensurepip.
After all the issue appears to be that "setuptools" is recognized to be installed, but not within the venv's site-packages itself - this however could then also be an issue with `pdm.pep582` adding `__pypackages__` (around) there (maybe).

Code ref: https://github.com/python/cpython/blob/cc60f415bac8078b8026f8868fefee61fc03be25/Lib/ensurepip/__init__.py#L80-L93

**Comment by frostming** [comment]
> Likely a good fix might be to use a more isolated pip run (similar to pip's isolated builds, in a temporary directory), or use --force-reinstall as an arg to pip-install in ensurepip.

But `ensurepip` is called by `venv`, not `pdm`. The problem is triggered because `ensurepip` is called with site enabled while `venv/bin/pip` builds package with site disabled(`python -I`), so the former sees `setuptools` but the latter does not. Yes, it is PDM that adds additional packages into the `sys.path` in `site` loading period, but to fix it you can't tell PDM not to do that, since it is how PEP 582 works. You should take the responsibility to fix your environment, fortunately, there are workarounds, either should work:

1. Chdir to another directory and create the venv.
2. If venv is already created, you can install `setuptools` yourself by `venv/bin/pip install -I setuptools`.

**Comment by blueyed** [comment]
@frostming 
Thanks for the info.  I've not meant that pdm is at fault here really, but just posted my investigations.  I've meant that `ensurepip` should be changed in this regard, as you've also mentioned.  Do you think a bug report there is feasible?

FWIW, I've created a wrapper script, which also installs `wheel` then automatically:
```sh
#!/bin/sh
# Create a Python virtualenv in the current directory.

test -z "$@"

# Unset PYTHONPATH to work around ensurepip re-using packages from __pypackages__ (PEP581).
# Ref: https://github.com/pdm-project/pdm/issues/661
set -x
unset PYTHONPATH
python -m venv .venv
.venv/bin/pip install wheel
```
