### ISSUE TITLE
Can't choose 3.10.0rc2 with `pdm use`

### ISSUE THREAD

**Issue by laike9m** [pdm-project/pdm#666]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. Install Python 3.10.0rc2 with pyenv
2. `pdm use 3.10.0` or `pdm use 3.10.0rc2`

## Actual behavior

![image](https://user-images.githubusercontent.com/2592205/135704723-7c23d90c-a1f9-46d9-8c9d-49048fc0c15a.png)
## Expected behavior

What I did is manually setting the interpreter's path in `.pdm.toml`, which works fine.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

PDM version:        1.8.5
Python Interpreter: /Users/laike9m/.pyenv/versions/3.10.0rc2/bin/python (3.10)
Project Root:       /Users/laike9m/Dev/Python/Cyberbrain
Project Packages:   /Users/laike9m/Dev/Python/Cyberbrain/__pypackages__/3.10
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.0c2",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "19.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 19.6.0: Tue Aug 24 20:28:00 PDT 2021; root:xnu-6153.141.40~1/RELEASE_X86_64",
  "python_full_version": "3.10.0rc2",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}
```

**Comment by pawamoy** [comment]
Try `pdm use -f python3.10` instead.

**Comment by laike9m** [comment]
`pdm use -f python3.10` does work. Is this expected behavior?

**Comment by pawamoy** [comment]
I think it just comes down to the fact that PDM searches an executable using its name rather than its version. Since version 3.10.0rc2 is available as `python3.10` on your PATH, PDM finds it. On the contrary, it does not know how to handle `3.10.0rc2` (maybe there's something to improve here). @frostming could probably tell us more about this (or correct me if what I said is non-sense ^^)

**Comment by frostming** [comment]
Update the version of `pythonfinder` within the PDM's **installation** env fixes the problem.
