### ISSUE TITLE
Updating editable package showed multiple times

### ISSUE THREAD

**Issue by laike9m** [pdm-project/pdm#677]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Every time I ran `pdm update`, `Updating cyberbrain` shows up multiple times:

![image](https://user-images.githubusercontent.com/2592205/136869334-c9f8f47a-08da-40ec-9550-4a039140642a.png)

See [tmp.txt](https://github.com/pdm-project/pdm/files/7325904/tmp.txt) for the full output of `pdm update -v`.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.8.5
Python Interpreter: /Users/laike9m/.pyenv/versions/3.10.0/bin/python3 (3.10)
Project Root:       /Users/laike9m/Dev/Python/Cyberbrain
Project Packages:   /Users/laike9m/Dev/Python/Cyberbrain/__pypackages__/3.10
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.0",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "19.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 19.6.0: Thu Sep 16 20:58:47 PDT 2021; root:xnu-6153.141.40.1~1/RELEASE_X86_64",
  "python_full_version": "3.10.0",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}
```

**Comment by warsaw** [comment]
I should note that I'm seeing this same issue with two other packages I'm converting to PDM, [atpublic](https://gitlab.com/warsaw/public/-/merge_requests/16) and [flufl.lock](https://gitlab.com/warsaw/flufl.lock/-/tree/main).

**Comment by frostming** [comment]
Please test if it still occurs on [`2.0.0a1`](https://github.com/pdm-project/pdm/releases/tag/2.0.0a1)
