### ISSUE TITLE
feat: symlink to save storage and time

### ISSUE THREAD

**Issue by jjangga0214** [pdm-project/pdm#690]
## Is your feature request related to a problem? Please describe.

Everytime I use pdm for a new project, it creates "heavy" `__pypackages__`.
`pdm` copies and paste packages from cache to the project.

## Describe the solution you'd like

The problem is similar from what nodejs's package managers face (or once faced).

![W2P0Ul6](https://user-images.githubusercontent.com/28584151/138243390-3c3ab4dd-5577-4346-ba07-19a24636d65c.jpg)

[`pnpm`](https://github.com/pnpm/pnpm) (not npm) resolved this by symlink.

![Screenshot from 2021-10-21 17-48-04](https://user-images.githubusercontent.com/28584151/138243947-ffab4279-28fd-499d-83a2-873db79e774c.png)

(from [the official article](https://medium.com/pnpm/why-should-we-use-pnpm-75ca4bfe7d93))

For yarn, from v2(berry), it also uses a similar method. It does not copy-paste the content of the packages, but it just marks every packages' paths, so that (special) nodejs runtime can find the packages.

This is similar to how other package managers do (e.g. maven(java), pub(dart)).

I think pdm is already good(better) alternative to pipenv and poetry, etc, especially for projects using comparatively lightweight dependencies, like web development. 

But packages in datascience and artificial intelligence are quite heavy(e.g. pytorch, tensorflow).
And it seems people do not want to create a virtualenv, which is coupled with an interpreter.
anaconda has been good for these points. 

However, pdm is already detached from interpreter and virtualenv, so if it resolves this issue, than 
I think pdm becomes more attractive, providing more reproducibility than alternatives(e.g. anaconda).  

How do you think?

Thanks

**Comment by frostming** [comment]
Guess what? it is already there: https://pdm.fming.dev/usage/dependency/#save-disk-space-by-enabling-the-install-cache

But that `.pth` files are more platform-agnostic than symlink

**Comment by frostming** [comment]
ICYMI PDM now prefers symlink approach if it is supported by the filesystem, and falls back to .pth files otherwise.
