### ISSUE TITLE
how to install with version annotation and wheel? (e.g. pytorch cpu version)

### ISSUE THREAD

**Issue by jjangga0214** [pdm-project/pdm#694]
![Screenshot from 2021-10-22 03-00-13](https://user-images.githubusercontent.com/28584151/138332063-667b61a0-15d7-451d-84ce-473dc28c3201.png)

[Pytorch's official page](https://pytorch.org/get-started/locally/) guides user to install the cpu-only mode of package by the following.

```shell
pip3 install torch==1.10.0+cpu \ 
  torchvision==0.11.0+cpu \ 
  torchaudio==0.10.0+cpu \
  -f https://download.pytorch.org/whl/cpu/torch_stable.html
```

If I run 

```shell
pdm add torch~=1.10.0+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
```
then an error occurs.
```shell
Usage: pdm [OPTIONS] [COMMANDS] ...
pdm: error: unrecognized arguments: -f https://download.pytorch.org/whl/cpu/torch_stable.html
```

If I run
```shell
pdm add torch~=1.10.0+cpu
```
then another error occurs.
```shell
[RequirementError]: The local path torch=1.10.0+cpu does not exist.
Add '-v' to see the detailed traceback
```

How can I do?

Thanks.
## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
➜  pdm (☸ |k3d-ateam:local) pdm info && pdm info --env
PDM version:        1.9.0                                                 
Python Interpreter: /home/jjangga/.pyenv/versions/3.9.7/bin/python3 (3.9) 
Project Root:       /media/jjangga/SHARE/experiment/pdm                   
Project Packages:   /media/jjangga/SHARE/experiment/pdm/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.7",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.11.0-37-generic",
  "platform_system": "Linux",
  "platform_version": "#41~20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021",
  "python_full_version": "3.9.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}

```

**Comment by lsmith77** [comment]
I am using `PDM, version 2.4.8` on OSX and I am trying to get the CPU verson of PyTorch installed.

I am trying

```
pdm add "torch>=2.0.0+cpu"
Adding packages to default dependencies: file:///${PROJECT_ROOT}/torch%3E%3D2.0.0%2Bcpu
See /var/folders/61/02k_wd1j7f57mhzbflsv1s2m0000gn/T/pdm-lock-hn01l8j6.log for detailed debug log.
[FileNotFoundError]: [Errno 2] No such file or directory: '/Users/lsmith/htdocs/nlp_api-flexible/torch>=2.0.0+cpu'
Add '-v' to see the detailed traceback
```

Without the `+cpu` it manages to install torch but then I don't have the CPU version, which means it tries to load CUDA related libraries.

**Comment by lsmith77** [comment]
the following seems to have done the trick

```
dependencies = [
    "torch>=2.0.0",
]

[[tool.pdm.source]]
type = "find_links"
url = "https://download.pytorch.org/whl/cpu/torch_stable.html"
name = "torch"
```

my pdm.lock looks like this:
```
[[package]]
name = "torch"
version = "2.0.0+cpu"
requires_python = ">=3.8.0"
summary = "Tensors and Dynamic neural networks in Python with strong GPU acceleration"
dependencies = [
    "filelock",
    "jinja2",
    "networkx",
    "sympy",
    "typing-extensions",
]
```

**Comment by frostming** [comment]
> Without the +cpu it manages to install torch 

You are making a mistake: you thought >= works similarly to == and should work when combined with 2.0.0+cpu. However this is wrong, +cpu local version can't be used with comparison operators but can be used with equality and  inequality operators.

**Comment by lingkerio** [comment]
我安装的是torch2.2.1（之前安装了2.2.0 ，用pdm update更新了）
![图片](https://github.com/pdm-project/pdm/assets/112792583/a329e2e7-c22a-40b6-a937-453cc1617400)
但是当我运行python查看却发现torch版本还是2.2.0
![图片](https://github.com/pdm-project/pdm/assets/112792583/69fde641-b2f5-4f53-9417-b6301c9924d2)
而且安装的还是cpu版本（我是用pdm add torch torchaudio torchvision命令安装的），我又该如何安装GPU版本呢？

**Comment by zagorulkinde** [comment]
> the following seems to have done the trick
> 
> ```
> dependencies = [
>     "torch>=2.0.0",
> ]
> 
> [[tool.pdm.source]]
> type = "find_links"
> url = "https://download.pytorch.org/whl/cpu/torch_stable.html"
> name = "torch"
> ```
> 
> my pdm.lock looks like this:
> 
> ```
> [[package]]
> name = "torch"
> version = "2.0.0+cpu"
> requires_python = ">=3.8.0"
> summary = "Tensors and Dynamic neural networks in Python with strong GPU acceleration"
> dependencies = [
>     "filelock",
>     "jinja2",
>     "networkx",
>     "sympy",
>     "typing-extensions",
> ]
> ```

Thanks, works like a charm!

**Comment by pofl** [comment]
For anyone who came here via Google looking for how to install CPU-torch via PDM like me, the following works for me at the time of writing (PDM v2.25.4):

```toml
dependencies = [
    "torch>=2.7.1",
]

[[tool.pdm.source]]
type = "index"
url = "https://download.pytorch.org/whl/cpu/"
name = "torch"
```
