### ISSUE TITLE
Support `pdm shell`

### ISSUE THREAD

**Issue by abersheeran** [pdm-project/pdm#715]
## Is your feature request related to a problem? Please describe.

Execute `pdm shell` in the shell to set environment variables for the current shell.

Some examples：

In Bash

```bash
export PATH=$(pdm info --packages)/bin:$PATH
export PYTHONPATH=$(pdm info --packages)/lib:$PYTHONPATH
```

In PowerShell

```python
split = ";" if os.name == "nt" else ":"
bin_dir = "Scripts" if os.name == "nt" else "bin"
```

```powershell
$env:PATH = Join-Path $(pdm info --packages) '{bin_dir}' '{split}' $env:PATH
$env:PYTHONPATH = Join-Path $(pdm info --packages) 'lib' '{split}' $env:PYTHONPATH
```

A incomplete python example:

```python
import shellingham

shell, executeable = shellingham.detect_shell()
shell = shell.lower()

if shell in ("bash", "zsh"):
    call("export PATH=$(pdm info --packages)/bin:$PATH")
elif shell == "fish":
    call("set -x PATH (pdm info --packages)/bin $PATH")
elif shell in ("csh", "tcsh"):
    call("setenv PATH $(pdm info --packages)/bin:$PATH")
elif shell == "pwsh":
    split = ";" if os.name == "nt" else ":"
    bin_dir = "Scripts" if os.name == "nt" else "bin"
    call(
        f"$env:PATH = Join-Path $(pdm info --packages) '{bin_dir}' '{split}' $env:PATH"
    )
else:
    raise NotImplementedError(f"Shell {shell} is not supported")
```

## Describe the solution you'd like

This provides a way close to a virtual environment, which can make pdm easier to use in the shell.

**Comment by leosannlsn** [comment]
What's the status of this? This looks like a really helpful enhancement but doesn't look like it's implemented.
I also tried installing the `pdm-shell` plugin but it looks like it's outdated, it downgrades my pdm version from 2.2.1 to 1.15.5 and it messes up other plugins.

**Comment by abersheeran** [comment]
Please use pdm-shell 1.1.0
