### ISSUE TITLE
Interest in supporting PEP 665?

### ISSUE THREAD

**Issue by brettcannon** [pdm-project/pdm#718]
## Is your feature request related to a problem? Please describe.

Coming up with a standard file format to replace `pdm.lock` files.

## Describe the solution you'd like

If this project would support PEP 665 being selected, could you either let me know here or at https://discuss.python.org/t/pep-665-take-2-a-file-format-to-list-python-dependencies-for-reproducibility-of-an-application/11736 so I can list this project as supportive of the PEP?

**Comment by frostming** [comment]
Sure, that is in plan

**Comment by brettcannon** [comment]
Thanks! I listed PDM as favourable in the PEP.
