### ISSUE TITLE
install package without summary will fail

### ISSUE THREAD

**Issue by exherb** [pdm-project/pdm#719]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

https://github.com/pdm-project/pdm/blob/fee04e5ece3493139458ac4939d3352807769afe/pdm/cli/utils.py#L439 v.summary is possible None

## Steps to reproduce

pdm add selenium~=4.0 -v

## Actual behavior

install fail

## Expected behavior

install success

## Environment Information

```bash
PDM version:        1.10.0
Python Interpreter: /usr/local/opt/python@3.9/bin/python3.9 (3.9)
Project Root:       /Users/Herb/Git/adtalos/xapi/python
Project Packages:   /Users/Herb/Git/adtalos/xapi/python/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.7",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "21.2.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 21.2.0: Wed Oct 20 00:23:27 PDT 2021; root:xnu-8019.60.40.0.1~26/RELEASE_X86_64",
  "python_full_version": "3.9.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "darwin"
}
```

**Comment by exherb** [comment]
will today release a new version for this?

**Comment by frostming** [comment]
I don't think so, for `selenium` it still fails to install because of an incorrect wheel:

```
AssertionError: In /private/var/folders/4d/r05n15jx1yv7yd4z7qrtmdm00000gn/T/pip-unpack-7ji5dfll/selenium-4.0.0-py3-none-any.whl, selenium/__init__.py is not mentioned in RECORD
```

Consider reporting it to the selenium packager.

**Comment by exherb** [comment]
ok, thanks

**Comment by jjangga0214** [comment]
@exherb Have you reported it to the selenium packagers? Or have you solved the issue?

**Comment by exherb** [comment]
both no, I just use selenium~=3.0

**Comment by jjangga0214** [comment]
@exherb Just reported. Consider adding some comments if you'd like to.
