### ISSUE TITLE
Hide pkg_resources warning about invalid versions

### ISSUE THREAD

**Issue by pawamoy** [pdm-project/pdm#720]
```
/media/data/dev/griffe/__pypackages__/3.9/lib/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning:
0.3.2.linux-x86_64 is an invalid version and will not be supported in a future release
```

I recently started getting a lot of these warnings when resolving dependencies. Would be nice if PDM would discard/ignore them itself, as this is non-actionable by the user anyway.

Also, the warning says "will not be supported in a future release". Do you know what this means concretely? Will future versions stop working with how PDM resolves dependencies?

**Comment by frostming** [comment]
The warning comes from https://github.com/pypa/setuptools/blob/8af23a41194ae747faf3e60f9cc19141b5e7ad24/pkg_resources/__init__.py#L112-L121

It seems some of your dependencies are using legacy version strings.

**Comment by pawamoy** [comment]
Patched my local version of PDM with the diff: it seems it's not enough, I still get the warnings.

**Comment by pawamoy** [comment]
I also changed the import in `models/repositories.py` and it seems to do the trick :slightly_smiling_face:

**Comment by frostming** [comment]
> I also changed the import in `models/repositories.py` and it seems to do the trick 🙂
Do you mean the newest release is working? then this issue can be closed.

**Comment by pawamoy** [comment]
If this last change is effective in the new version, then the first changes completes the fix, yes. Thanks a lot!
