### ISSUE TITLE
Running files from `bin` directory doesn't work

### ISSUE THREAD

**Issue by DUOLabs333** [pdm-project/pdm#727]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
Make a pdm folder, install any package that provides an executable in the `bin` folder. Run ` eval "$(pdm --pep582)"` and try to run that script.

## Actual behavior
Nothing happens 

## Expected behavior
The script to run

## Environment Information

```
PDM version:        1.10.0
Python Interpreter: /usr/bin/python (3.9)
Project Root:       /home/system/Downloads/pywb
Project Packages:   /home/system/Downloads/pywb/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.7",
  "os_name": "posix",
  "platform_machine": "aarch64",
  "platform_release": "5.14.14-1-ARCH",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Thu Oct 21 19:35:13 MDT 2021",
  "python_full_version": "3.9.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by DUOLabs333** [comment]
It seems you have to run `pdm run $SCRIPT`. It would be nice if you could run it without having to do that (for example, python scripts that expect it to be in the path).

**Comment by pawamoy** [comment]
You could do this:

```
PATH=./__pypackages__/3.8/bin:$PATH
```

...but not sure this is good-practice. Maybe wildcards would work as well:

```
PATH=./__pypackages__/*/bin:$PATH
```

**Comment by pawamoy** [comment]
For packages that provide a `__main__` module, you can also call them with `python -m package`. This will let you choose the Python version, contrary to the PATH hack above.

**Comment by frostming** [comment]
PEP 582 doesn't add bin to the `PATH` env var, this is consistent with `npm`/`pnpm`. Prefix with `pdm run` please.
