### ISSUE TITLE
Implement --force-reinstall flag

### ISSUE THREAD

**Issue by dshtrikul** [pdm-project/pdm#732]
Are there plans to duplicate pip's --force-reinstall option ? 

thx in advance

**Comment by frostming** [comment]
`pdm sync -r/--reinstall`

**Comment by dshtrikul** [comment]
thank you ! didnt see it somehow

best wishes to the project !

**Comment by DUOLabs333** [comment]
Is it possible to do this for only one package (I edited it, and now I want to reinstall it).
