### ISSUE TITLE
Small documentation improvement suggestion

### ISSUE THREAD

**Issue by jeverling** [pdm-project/pdm#736]
Small documentation improvement suggestion: I copied the code for `.vscode/settings.json`, the file didn't exist in my project. The copied code included the ellipsis for other settings.

```json
{
  ...
  "python.autoComplete.extraPaths": ["__pypackages__/<major.minor>/lib"],
  "python.analysis.extraPaths": ["__pypackages__/<major.minor>/lib"]
}
```

I think it's better to not include the ellipsis in the code and rephrase, so it's clear it should be added to existing configuration.

**Comment by jeverling** [comment]
I also have a problem / question. Resolving dependencies in vscode does not work, even when `.vscode/settings.json` is updated.
It does work when I use `pdm run code . `, but not when I use `code .`. 

I do have the `pdm --pep582 ` output appended to `~/.zshrc` and

```json
{
  "python.autoComplete.extraPaths": ["__pypackages__/<major.minor>/lib"],
  "python.analysis.extraPaths": ["__pypackages__/<major.minor>/lib"]
}
```

in `.vscode/settings.json`.

I would have expected vscode being able to resolve the dependencies, without being run through `pdm run`. Or is that the expected behavior?

**Comment by pawamoy** [comment]
My intuition is that VSCode uses bash on your machine to run things, and you only configured zsh to support PEP582. Try telling VSCode to use zsh instead, or add the output of `pdm --pep582` to your `.bashrc` as well.

**Comment by jeverling** [comment]
Thanks for your answer. You were right, the default terminal on VSCode was bash. Both suggestions (changing to zsh and adding to `~/.bashrc`) didn't help though. Probably some peculiarity on my system.
