### ISSUE TITLE
series of issues when converting from poetry in a complex, multiplatform project

### ISSUE THREAD

**Issue by earonesty** [pdm-project/pdm#745]
VERSION: pdm, version 1.10.3

Each number represents some sort of bug/issue:

*ISSUE 1 (MINOR)*. using pyenv-windows, outside of a virtualenv, pdm was not installed to scripts directory.   other things install properly.  inside of a venv, pdm also installs correctly.

solution: `python -mdm`

*ISSUE 2*. import poetry doesn't work with platform specifiers

`python -mpdm import -vf poetry ./pyproject.toml`
Error: `TypeError: __init__() got an unexpected keyword argument 'platform'`

Reason: `pywin32 = {version = ">=228", platform = "win32"}`

solution: removed all platform specifiers (hoping to put them back later)

*ISSUE 3 (SEVERE)*. pdm uses an odd/broken package called `pythonfinder`, which is incompatible with pyenv-win32, and results in it simply not working because `C:/Users/erik/.pyenv/pyenv-win/shims/python` is not a binary executable

hardcoded things in the path until it wasn't broken.   todo: maybe patch pdm to not use pythonfinder or patch pythonfinder to work with pyenv-win (it calls popen on the result... what if it's a bash script...  fails)

*ISSUE 4*. git@dependencies don't work with platform specifiers: `"vidarelay @ git+ssh://git@gitlab.com/atakama/ccserver.git; sys_platform=='win32'"` didn't work, i got: `pip._vendor.pkg_resources.RequirementParseError: Parse error at "'sys_plat'": Expected stringEnd`

removing those specifiers (which is bad, but i wanted to see what happend) finally worked!

*ISSUE 5 (WORKAROUND)*. solver got stuck in an infinite loop : see https://pastebin.com/1NU3HvHp

Solution:  remove flake8 (hoping it would help) ... it did!

Finally...solving took a bit longer than poetry... but it worked!

ISSUE 6 (PIP INI, NO GOOD WORKAROUND): installation failures when extra-index-url is required to resolve.   the bug seems to be that it is using the SAME --extra-index-url and the --index-url (even thought they are different in my pip.ini)  example of pip.ini

```
[global]
index-url = https://erik:XXXXX@artifacts.XXX.io/repository/vida-pi/simple
extra-index-url = https://pypi.org/simple
```

output of failure

```add quickxorhash failed:
Traceback (most recent call last):
...
  File "C:\venvs\465ba029bf6c0fbcb108914b9e956119.3a0542912274a141\lib\site-packages\pdm\builders\base.py", line 86, in log_subprocessor
    raise BuildError(
pdm.exceptions.BuildError: Call command ['C:/venvs/465ba029bf6c0fbcb108914b9e956119.3a0542912274a141/Scripts/python.EXE', '-Esm', 'pip', 'install', '--isolated', '--ignore-installed', '--pre
fix', 'C:\\Users\\erik\\AppData\\Local\\Temp\\pdm-build-env-hyq3qnvo-shared', '--index-url', 'https://erik:xxxx@artifacts.xxxxx.io/repository/vida-pi/simple', '--extra-inde
x-url', 'https://erik:xxxxx@artifacts.xxxx.io/repository/vida-pi/simple/', '-r', 'C:\\Users\\erik\\AppData\\Local\\Temp\\pdm-build-reqs-pv9bgtkg.txt'] return non-zero statu
s(1).
```

Giving up for now :( will revisit later.

**Comment by frostming** [comment]
ISSUE 2: I didn't see poetry support keyword `platform` from the [docs](https://python-poetry.org/docs/dependency-specification/#using-environment-markers), change to environment markers would be fine.

ISSUE 4: You need to put a space between the URL and semicolon like `vidarelay @ git+ssh://git@gitlab.com/atakama/ccserver.git ; sys_platform=='win32'`, otherwise it will be parsed as part of the URL

ISSUE 5: might be solved in the main branch, care to have a test?

Other issues might be potential bugs, I will look into them soon. Thanks!

**Comment by frostming** [comment]
ISSUE 6: Do you have any `source` in your project.toml? Only `index_url` from `pip.ini` will be read by PDM.

**Comment by earonesty** [comment]
yes we have a source:
```
name = "nexus"
url = "https://artifacts.xxxxx.io/repository/vida-pi/simple/"
```

**Comment by frostming** [comment]
It is trying to set up an ISOLATED environment for PEP 517 build, `pip` and `build` are also doing this way.

Can you show the `source` table in `pyprojec.toml` and `pip.ini` content?
