### ISSUE TITLE
Wrongly formed pyproject.tml project authors when converted from Poetry pyproject.toml

### ISSUE THREAD

**Issue by bolinocroustibat** [pdm-project/pdm#747]
I have PDM 1.10.0 running on MacOS 11.6
On an existing project with an existing `pyproject.toml` from Poetry, I did a `pdm init` to update the `pyproject.toml` file to PDM and use PDM for now.
Then for every PDM command I get the error `atoml.exceptions.UnexpectedCharError: Unexpected character: 'n' at line 45 col 0`.

It seems the `pyproject.toml` is malformed in [project] -> authors:

```
[tool.poetry]
name = "foo-bar-project"
version = "1.0.0"
description = ""
authors = ["Foo Bar <foo@bar.com>"]

[tool.poetry.dependencies]
python = "^3.8"
country-list = "^1.0.0"

[tool.poetry.dev-dependencies]
black = "^21.10b0"
ipython = "^7.29.0"


[tool.pdm]
includes = []
[tool.pdm.dev-dependencies]
dev = [
    "black<22.0,>=21.10b0",
    "ipython<8.0.0,>=7.29.0",
]
[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Foo Bar", email = "foo@bar.com"},
name = "Foo Bar"
email = "foo@bar.com"
]
dependencies = ["country-list<2.0.0,>=1.0.0", "Django<4.0.0,>=3.2.9"]
requires-python = ">=3.8"
dynamic = ["classifiers", "classifiers"]
license = {text = "MIT"}

[project.urls]
homepage = ""

```

**Comment by frostming** [comment]
Use the latest version of PDM please, it should be fixed.

**Comment by bolinocroustibat** [comment]
@frostming Thanks. I installed PDM today, it is the latest version provided by `brew`. It means `brew` is not installing the latest version of PDM? Should we create another ticket for that?

**Comment by frostming** [comment]
> @frostming Thanks. I installed PDM today, it is the latest version provided by `brew`. It means `brew` is not installing the latest version of PDM? Should we create another ticket for that?

It's not true, the latest version is [1.10.3](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pdm.rb), you might need to `brew update` first.

**Comment by bolinocroustibat** [comment]
@frostming Oh sorry that makes sense, thanks!
