### ISSUE TITLE
Incompatibility with PEP 621

### ISSUE THREAD

**Issue by abravalheri** [pdm-project/pdm#748]
Hi guys I am under the impression that `pdm` is not compatible with PEP 621 (I have been working in a `pyproject.toml` validator and this problem showed up when running it against some projects created using `pdm`).

In particular the problems lie in the following parts of the spec:

1. [**version** - Format: string](https://www.python.org/dev/peps/pep-0621/#version)
2. [Build back-ends MUST raise an error if the metadata specifies a field statically as well as being listed in dynamic.](https://www.python.org/dev/peps/pep-0621/#dynamic)

PDM documentation indicate that users can do `version = {use_scm = true}` or `version = {from = "pdm/__init__.py"}`, which violates the spec in (1).

Regarding item (2), I understand that passing `version = {use_scm = true}` or `version = {from = "pdm/__init__.py"}` doesn't really is specifying a field statically, but this is still a very controversial usage/interpretation of the standard.

- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. Check a PDM's powered project that uses dynamic versions for its `pyproject.toml`
2. Validate the `pyproject.toml` file against PEP 621

## Actual behavior

PDM accepts a inline-table ``version``.

## Expected behavior

PDM should error when ``version`` is not a string.
Additional tool-specific information needed for dynamic version discovery, should be stored in `tool.pdm`

**Comment by pawamoy** [comment]
I guess there's an issue with classifiers as well then. Too bad, it means we cannot specify some classifiers statically and let the build backend add some more dynamically...

**Comment by abravalheri** [comment]
Yeap, the 2 things cannot exist at the same time unless using a `tool`-specific table.

The PEP goes even further and says:

> If the metadata does not list a field in dynamic, then a build back-end CANNOT fill in the requisite metadata on behalf of the user (i.e. dynamic is the only way to allow a tool to fill in metadata and the user must opt into the filling in).

So it is "not allowed" to implicitly add classifiers to the user-given list (i.e. add extra classifiers to PKG-INFO/METADATA without the field being listed in `dynamic` which in turn requires the user to leave the field completely unspecified).

**Comment by frostming** [comment]
Thanks, I've also noticed that and planned to change someday. `version` will be moved to `tool` table automatically, but `classifiers`, I think it is not intuitive to defined it in `tool.pdm` just for auto filling, so maybe it is time to remove it from dynamic fields keep it pure static... too bad, the same feeling as @pawamoy

**Comment by abravalheri** [comment]
Should we start a discussion on discord about this, at least for the classifiers? It is a very handy feature...

I don't know how the community would feel about creating another PEP to amend this one, though... It might be difficult to get people on board.

**Comment by frostming** [comment]
Sure, join the PDM discord channel which can be found in the README

**Comment by abravalheri** [comment]
Sorry, I mean a discussion with the packaging community about amending the PEP...

**Comment by frostming** [comment]
Okay, then https://discuss.python.org/c/packaging/14 should be the correct place, would you like to create a topic there?

**Comment by frostming** [comment]
But IMO according to the spirit of `dynamic` of PEP 665: dynamic fields shouldn't be listed as a static field at the same time, there is no space for the autofilling classifiers, unless users are okay to have them written in the `tool` table. Or do you have better approach?

**Comment by abravalheri** [comment]
I understande @frostming, and I don't have a better approach. Maybe the best is to align with the PEP.

**Comment by oprypin** [comment]
So the ability to automatically specify Python version classifiers has been fully removed:

* https://github.com/pdm-project/pdm/pull/759
* https://github.com/pdm-project/pdm-pep517/pull/53

I feel like that was a huge overreaction. Surely there are ways to keep this functionality under a different config key. And I wasn't specifying any extra static classifiers anyway.

I'm once again in a situation where I'm lacking features compared to Poetry
https://python-poetry.org/docs/pyproject/#classifiers

This, along with the fact that features are being removed like this just on a whim, is again a showstopper for me.

**Comment by pawamoy** [comment]
You mean for example specifying classifiers in `[tool.pdm]`, so that PDM can also add dynamic ones?

**Comment by pawamoy** [comment]
Well in the end, I like declaring my classifiers as static, because it forces me to actually add some meaningful ones :grin:
