### ISSUE TITLE
Colorizing fails [win10]

### ISSUE THREAD

**Issue by dshtrikul** [pdm-project/pdm#753]
Seems like an coloring issue on Windows

c:\>pdm -V
←[1mpdm←[0m, version 1.10.3

c:\>pdm
←[33m←[1mUsage: ←[0mpdm [OPTIONS] [COMMANDS] ...

PDM - Python Development Master

←[33m←[1mCommands←[0m:
←[36m  {add,build,cache,completion,config,export,import,info,init,install,list,lock,plugin,remove,run,search,show,sync,update,use}
←[0m←[36m    add                 ←[0mAdd package(s) to pyproject.toml and install them
←[36m    build               ←[0mBuild artifacts for distribution
←[36m    cache               ←[0mControl the caches of PDM
←[36m    completion          ←[0mGenerate completion scripts for the given shell
←[36m    config              ←[0mDisplay the current configuration
←[36m    export              ←[0mExport the locked packages set to other formats
←[36m    import              ←[0mImport project metadata from other formats
←[36m    info                ←[0mShow the project information
←[36m    init                ←[0mInitialize a pyproject.toml for PDM
←[36m    install             ←[0mInstall dependencies from lock file
←[36m    list                ←[0mList packages installed in the current working set
←[36m    lock                ←[0mResolve and lock dependencies
←[36m    plugin              ←[0mManage the PDM plugins
←[36m    remove              ←[0mRemove packages from pyproject.toml
←[36m    run                 ←[0mRun commands or scripts with local packages loaded
←[36m    search              ←[0mSearch for PyPI packages
←[36m    show                ←[0mShow the package information
←[36m    sync                ←[0mSynchronize the current working set with lock file
←[36m    update              ←[0mUpdate package(s) in pyproject.toml
←[36m    use                 ←[0mUse the given python version or path as base interpreter

←[33m←[1mOptions←[0m:
←[36m  -h, --help            ←[0mshow this help message and exit
←[36m  -V, --version         ←[0mshow the version and exit
←[36m  -v, --verbose         ←[0m-v for detailed output and -vv for more detailed
←[36m  -I, --ignore-python   ←[0mIgnore the Python path saved in the pdm.toml config
←[36m  --pep582 [SHELL]      ←[0mPrint the command line to be eval'd by the shell

c:\>systeminfo
...
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19042 N/A Build 19042
...

**Comment by pawamoy** [comment]
What graphical console are you using? Terminal coloring is a mess on Windows (speaking from experience). Generally I had a better experience with Terminal (from Microsoft), though it happened to break as well (not interpreting ANSI sequences anymore for some reason).

**Comment by dshtrikul** [comment]
Same behaviour with cmd and powershell
