### ISSUE TITLE
PDM importing project authors from pyproject.toml's Poetry, and also asking for them in CLI when `pdm init`

### ISSUE THREAD

**Issue by bolinocroustibat** [pdm-project/pdm#757]
I have PDM 1.10.3 running on MacOS 11.6 installed with brew.
I'm using `pdm init` on existing projects with existing `pyproject.toml` generated from Poetry, to update it.

Since I already have author(s) in [tool.poetry] -> authors, which PDM seems to successfully import, and since PDM is also asking for the author in the CLI when doing `pdm init` (to which the user will often answer with the same), the resulting `pyproject.toml` often has repeated authors, i.e:
```
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Foo Bar", email = "foo@bar.com"},
    {name = "Foo Bar", email = "foo@bar.com"},
]
```
Absolutely not a major issue, but would be nice to find a way to manage this case.

And thanks for the great work, the tool is amazing.

**Comment by frostming** [comment]
Yes, it repeats but I think it is not an issue. we simply do the merging, but no deduplication.
