### ISSUE TITLE
Way to delegate calls to setuptools `cmdclass` commands

### ISSUE THREAD

**Issue by defined-user** [pdm-project/pdm#758]
Hey!

This isn't really an issue, it's closer to a question. I know that right now building C extensions hardly relies on `setuptools` package, so I followed all steps from your documentation and it works just great - custom commands from `cmdclass` argument for `setup` function are getting called, the package gets built and packaged correctly and installed, if needed.

Nevertheless, I encountered a small problem with project local usage. The project structure is pretty simple and follows general recommendations for Python packages:
```
- system_folder
- - python_package_with_sources
- - build_c_extensions_with_build_function.py
- - pyproject.toml
- - pdm.lock
- - README.md
- - etc.
```

During development, after the build, I usually need to run a few test (including tests for built Cython files) like usual with `unittest` package: `python -m unittest`. The problem is that built package name matches sources directory name (which makes sense in terms of packaging), so Python performs all imports from the source directory, not the built package (as local files come before any others in `PYTHONPATH`), thus a few errors appear.

I didn't find a way to build all files inplace (without packaging them, creating new files directly in sources folder. instead of a future package) with `pdm`, so wanted to delegate it to `setuptools` package and simply call a few commands from the `cmdclass`, as I used to do without `pdm` like so `python setup.py build_py`, but the problem is that they are not regular functions, rather `Command` objects from `setuptools`, so can't do it with the help of regular scripts.

Right now I solved this problem by renaming the sources folder, but wanted to know if I missed anything.

**Comment by defined-user** [comment]
I think I could create a regular function for the `pdm` script, which would wrap a complete call to `setup` function, but then I'd have to have project configs listed in two places: in `pyproject.toml` and that specific place with a direct call to `setup`.

**Comment by pawamoy** [comment]
This is a common issue (testing the dist, not the sources) that can be alleviated by putting your Python sources under another folder, typically `src`. Of course the `src` folder must not appear in the PYTHONPATH when testing. Plenty of resources on this matter on the internet 🙂 (pytest, tox, ionelmc's cookiecutter and blog posts, github issues, etc.)

**Comment by defined-user** [comment]
Got it, thanks! I searched the web before creating the issue, but didn't manage to find anything useful. Will try again, now that I have more information on this.
