### ISSUE TITLE
Namespace package (PEP 420)

### ISSUE THREAD

**Issue by nihilox** [pdm-project/pdm#761]
`lev/ts/demo/__init__.py`
...

`setup.py`
```python
from setuptools import setup


setup(
    name = 'lev.ts.demo',
    packages = ['lev.ts.demo'],
)
```

How to use PDM to manage this project?

**Comment by pawamoy** [comment]
Did you find a solution? Could you post it here so it can help others with the same question?

**Comment by ItsAleph** [comment]
Sorry for bumping an old thread, but for here's an option in case anyone else comes across this issue.
If you only need to *manage* project with PDM, and you don't care about build backend, you can use PDM but specify (manually, as `pdm init` doesn't provide this option) build backend to poetry's masonry:
```toml
# pyproject.toml

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
Unfortunately, at the time of writing pdm-backend fails to install namespace packages in some cases (see the referenced issue above), so you'd need to use masonry or setuptools (which seems to handle namespace packages nicely as well), though i personally prefer more modern-ish solutions.
