### ISSUE TITLE
`pdm/pep582/sitecustomize.py` not honoring Python version for `__pypackages__` load

### ISSUE THREAD

**Issue by emcd** [pdm-project/pdm#766]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

### Baseline Configuration
```bash
$ echo $PATH | tr ':' '\n' | head -4
/home/me/bin
/home/me/.local/bin
/home/me/.asdf/shims
/home/me/.asdf/bin
$ echo $PYTHONPATH

$ echo $PEP582_PACKAGES

$ which python
/home/me/.asdf/shims/python
$ python --version
Python 3.6.15
```

### Reproduction: Use system Python rather than project Python.

```bash
$ pdm run bash --login -i
$ echo $PYTHONPATH
/home/me/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/pep582
$ echo $PEP582_PACKAGES
/home/me/src/python-lockup/__pypackages__/3.6
$ /usr/bin/python3 --version
Python 3.8.10
$ /usr/bin/python3 -c 'import lockup; print( lockup.__file__ )'
/home/me/src/python-lockup/sources/python3/lockup/__init__.py
$ ls __pypackages__
3.6
```

## Actual behavior

A Python 3.8 interpreter was able to load a package which is only supposed to be available for Python 3.6.

## Expected behavior

Import error for `lockup`.

## Environment Information

```bash
$ pdm info && pdm info --env
PDM version:        1.10.3
Python Interpreter: /home/me/.asdf/installs/python/3.6.15/bin/python (3.6)
Project Root:       /home/me/src/python-lockup
Project Packages:   /home/me/src/python-lockup/__pypackages__/3.6
{
  "implementation_name": "cpython",
  "implementation_version": "3.6.15",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.10.16.3-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Fri Apr 2 22:23:49 UTC 2021",
  "python_full_version": "3.6.15",
  "platform_python_implementation": "CPython",
  "python_version": "3.6",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
it's not a bug, the packages path is frozen when doing `pdm run` by populating the `PEP582_PACKAGES` env var. You either don't `pdm run` or  unset the env var in the shell.

**Comment by emcd** [comment]
@frostming: I respectfully disagree. Here is some more context on why I think it is undesirable behavior:
*  I have a habit of typing `python3` rather than `python` - it's a habit that I developed during the transition from `python2` to `python3`. I had subshell running under `pdm` and accidentally typed `python3` outside of the project directory. The system Python was in my `PATH` ahead of any shimmed Python in this case.
* One could see a similar problem with accidentally using a different version Python in a different directory that is also managed by a tool version manager, such as `asdf` or `pyenv`. That is the more generalized case which I would be concerned about, as lots of people are likely using these.

People, such as myself, will want to run subshells off of `pdm` because that mimics the convenience of an activated virtual environment. Accidents like the above will happen. Failure to properly catch them may result in weird behaviors due to opcode mismatches in the `.pyc` files.

But, it's your project, so I respect your judgment.

**Comment by pawamoy** [comment]
Note that when PDM's `sitecustomize.py` is in your PYTHONPATH, you don't need `pdm run` to run Python modules installed in your `__pypackages__`.

```bash
cd your_project
python3.8 -m pytest  # finds __pypackages__/3.8/lib/pytest/__main__.py
python3.9 -m pytest  # finds __pypackages__/3.9/lib/pytest/__main__.py
# etc.
```

You can of course import modules the same way

```console
$ python3.8 -c "import pytest; print(pytest.__file__)"
/path/to/your_project/__pypackages__/3.8/lib/pytest/__init__.py
$ python3.9 -c "import pytest; print(pytest.__file__)"
/path/to/your_project/__pypackages__/3.9/lib/pytest/__init__.py
```

I'd recommend users to take advantage of that rather that simulating virtualenv activation through various means. But I understand that it takes some time to accommodate :slightly_smiling_face: Virtualenvs are quite ingrained in us!

**Comment by frostming** [comment]
PDM doesn't encourage using a subshell. `pdm run` is for one-off tasks and PDM recommends [enabling PEP 582](https://pdm.fming.dev/#enable-pep-582-globally) for shells to be aware of the `__pypackages__`. Tell me if that doesn't fit in your case.

**Comment by emcd** [comment]
Hi @pawamoy , thanks for your response.

> Note that when PDM's `sitecustomize.py` is in your PYTHONPATH, you don't need `pdm run` to run Python modules installed in your `__pypackages__`.
> 
> ```shell
> cd your_project
> python3.8 -m pytest  # finds __pypackages__/3.8/lib/pytest/__main__.py
> python3.9 -m pytest  # finds __pypackages__/3.9/lib/pytest/__main__.py
> # etc.
> ```

Right, but that work style is inconvenient. Using a subshell eliminates the need to prefix everything with `python -m`. Telling people that they always need to write `python -m coverage` instead of `coverage` or `python -m invoke` instead of `invoke` is a user experience regression from what virtual environments provide.

> I'd recommend users to take advantage of that rather that simulating virtualenv activation through various means. But I understand that it takes some time to accommodate 🙂 Virtualenvs are quite ingrained in us!

They are indeed quite ingrained in us! But, possibly for good reasons? :) 
As a developer, I want a path of low resistance, and I want that path to be low resistance for anyone else who works on my projects. If a tool or a project says that I have to expend more energy and take on a higher cognitive load because it either becomes confused by a common use case or for philosophical reasons, then that is a negative.

My interest in PDM is
* faster (and possibly better) dependency resolution (compared to Pipenv),
* dependency resolution across multiple Python versions (compared to Pipenv),
* PEP 621 project metadata support (compared to Setuptools),
* maybe a better story around working with compiled code (compared to Poetry): https://pdm.fming.dev/pyproject/tool-pdm/#build-c-extensions  (more interested in Rust extensions than C extensions at this point, but same story) 

If I have to significantly change my workflow and do things in a less convenient manner, then it dampens my enthusiasm for PDM somewhat. (I still think it is a nice project with some good ideas!) However, I strongly suspect that I am not the only one who is going to want to use a subshell with it and not the only one who is going to be using a tool version manager (like `asdf` or `pyenv`) with it.

**Comment by pawamoy** [comment]
I guess it's a matter of preference. For me, *virtualenvs* are the higher cognitive load. There are many cases where having to activate/deactivate virtualenvs leads to errors and confusion. When I was still using Poetry, I almost never used `poetry shell`, and sticked to `poetry run`, because: is my env activated? Am I in a subshell? *Which* env is activated? Should I type deactivate or exit? With PDM, it feels more explicit, even though yes, I have to type `python -m`. But you can easily make wrappers around that (makefiles and task runners). Just my own experience of course :slightly_smiling_face: 

By the way, I'm using both pyenv and PDM and have no issues, not sure to understand what you mean in your last sentence.

**Comment by emcd** [comment]
> PDM doesn't encourage using a subshell. `pdm run` is for one-off tasks and PDM recommends [enabling PEP 582](https://pdm.fming.dev/#enable-pep-582-globally) for the _current_ shell to be aware of the `__pypackages__`. Tell me if that doesn't fit in your case.

I think it can be helpful, but it is quite intrusive and potentially adds an extra step for someone wanting to develop on a PDM-based project.

Currently, the steps to setup for development with one of my projects look like [this](https://emcd.github.io/python-lockup/contribution.html#development):
1. Ensure that `asdf` is installed (to provide isolation from the system Python and to support the multiple Python environments that will used for a complete set of tests).
2. Ensure that `pipenv` is installed (to provide an environment with the specific packages and commands needed for development on the project and to provide a shell in which to work with those packages and commands).
3. `pipenv sync --dev`

By contrast, the setup instructions with PDM would look like:
1. Ensure that `asdf` is installed.
2. Ensure that `pdm` is installed (either via `pipx` or else as part of an `asdf`-managed Python site packages).
3. `pdm install`
4. Modify `PYTHONPATH` via your shell profile so that Python interpreters can gain general awareness of `__pypackages__`.
That's an extra step and a global one that can affect the user's experience outside of work on my project. It also does not address the issue that a user would be expected to prefix every environment-specific command with `python -m`.

Given that part of the stated spirit of PEP 582 is to make environment setup easier, I am not sure that the extra step meets that criterion.

**Comment by emcd** [comment]
> I guess it's a matter of preference. For me, _virtualenvs_ are the higher cognitive load. There are many cases where having to activate/deactivate virtualenvs leads to errors and confusion. When I was still using Poetry, I almost never used `poetry shell`, and sticked to `poetry run`, because: is my env activated? Am I in a subshell? _Which_ env is activated? Should I type deactivate or exit?

I completely agree that there are problems with virtual environments and I'm not actually advocating for them in their current form. That said, both Pipenv and Poetry paper over some of those problems by handling automatic activation in a subshell and by modifying the shell prompt.

> With PDM, it feels more explicit, even though yes, I have to type `python -m`. But you can easily make wrappers around that (makefiles and task runners). Just my own experience of course 🙂

 👍 
True, people can make shell aliases, but that is an extra investment to achieve a comfortable working environment.

As far as Makefiles and task runners go, yes, you can do that. But, GNU Make is not universally available and other flavors of Make, such as Microsoft's Nmake, are not completely compatible with it. For task runners, I have settled on Pyinvoke (`invoke`) as that lets me provide a portable, 100% pure Python solution so that people don't have to remember more languages when they work on one of my projects. (Full rationale is [here](https://github.com/emcd/python-lockup/blob/v1.0.5/tasks/__init__.py#L1-L39).) However, the problem is that `invoke` is not available everywhere, so I ensure that it is installed as part of `pipenv sync --dev`. Which leads us back to the earlier problem statement, unfortunately. ☹️ 

> By the way, I'm using both pyenv and PDM and have no issues, not sure to understand what you mean in your last sentence.

Sorry that I wasn't clear. It is a reference to the fact that if you wander outside the project, `pyenv` may use a different Python per `.python-version` or fallback to the system Python. And, if `PEP582_PACKAGES` is set (as it would be in a subshell started from `pdm run`), then the Python version check in the PEP 582 site packages customization is bypassed and you may get `__pypackages__` for the wrong version of Python. (Hence the origin of this bug report.)

Anyway, thanks for the discussion. I don't want to be some random Joe off the Internet vociferously arguing a point. Just trying to share some of my own experience and rationale in this particular case. I do think there are a lot of things which PDM is getting right and am happy that the project exists. Maybe some day, we'll actually solve the headache-inducing mess known as "Python packaging".

**Comment by pawamoy** [comment]
OK I see the issue with pyenv now, thanks :slightly_smiling_face: 

I'm using something similar to pyinvoke, that I wrote ([duty](https://github.com/pawamoy/duty)). I also install it as a dev-dep. And I also want to provide a smooth UX for my "users" or contributors, so I had trouble as well figuring out what would be their entrypoint to run commands in a cross-platform setup :sweat_smile:  I eventually went with a Makefile as it's generally available on Linux distributions, and still installable on Windows through Conda or other package managers. If make is not available, it's either `pdm run duty TASK` or `python -m duty TASK` (or a Bash alias/function that allows to run `duty` directly). It's all templated here: https://github.com/pawamoy/copier-pdm. So in the end, I totally understand the motivation behind this issue :smile:

**Comment by emcd** [comment]
Duty looks quite interesting - thanks for sharing the link, @pawamoy! (I like your use of context managers. Seems more powerful than Invoke's - it has one for working in a changed directory, but this is significantly richer.)

About Makefiles. Yes, I've done a lot with them over the years, especially during my time as a C and C++ developer, including generation of complex ones using the GNU autotools. But, I don't really want to force potential ~users~ contributors to learn the syntax, simple though the basic syntax is. And, I try to treat Windows as a first-class citizen - adding an extra step or two (installing Conda to install `make`) raises the barrier to entry on that platform. But, everyone is going to draw the line differently in terms of acceptable user experience. I can respect your decision.
