### ISSUE TITLE
Use wheel-like naming scheme for `__pypackages__/<version>` rather than just Python version.

### ISSUE THREAD

**Issue by emcd** [pdm-project/pdm#767]
## Is your feature request related to a problem? Please describe.

During the discussion over PEP 582 on discussion.python.org, it was pointed out that incompatibilities when `__pypackages__` is being used across multiple operating systems sharing a project in a common file system mean that the major and minor version of Python alone may not be enough. One suggestion was to use a wheel-like naming convention: https://discuss.python.org/t/pep-582-python-local-packages-directory/963/82. Given that PEP 582 has not been approved (and seems to be quite controversial), have you considered deviating from its current wording and following the suggestion made by Tzu-ping Chung?

(One of the specific motivators for that arc in the thread was people developing using WSL2, where you may have a project shared between Linux and Windows.)

## Describe the solution you'd like

Use a `__pypackages__` directory structure that discriminates on ABI and platform compatibility rather than Python version alone.

**Comment by frostming** [comment]
Yes, I think that part is still under discussion and PDM isn't going to change unless the PEP is updated. Thanks for your suggestion and the Python community is willing to listen to more voices. You can participate in the discussion to push the iteration of PEP 582.
