### ISSUE TITLE
`pdm --help` does not perform TTY detection and sends ANSI SGR escape sequences to pipelined process.

### ISSUE THREAD

**Issue by emcd** [pdm-project/pdm#768]
- [X ] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

```bash
pdm --help | less
```

## Actual behavior

```
ESC[33mESC[1mUsage: ESC[0mpdm [OPTIONS] [COMMANDS] ...

PDM - Python Development Master

ESC[33mESC[1mCommandsESC[0m:
ESC[36m  {add,build,cache,completion,config,export,import,info,init,install,list,lock,plugin,remove,run,search,show,sync,update,use}
ESC[0mESC[36m    add                 ESC[0mAdd package(s) to pyproject.toml and install them
ESC[36m    build               ESC[0mBuild artifacts for distribution
```
...

## Expected behavior

```
Usage: pdm [OPTIONS] [COMMANDS] ...

PDM - Python Development Master

Commands:
  {add,build,cache,completion,config,export,import,info,init,install,list,lock,plugin,remove,run,search,show,sync,update,use}
    add                 Add package(s) to pyproject.toml and install them
    build               Build artifacts for distribution
```
...

## Environment Information

```bash
$ pdm info && pdm info --env
PDM version:        1.10.3
Python Interpreter: /home/me/.asdf/installs/python/3.6.15/bin/python (3.6)
Project Root:       /home/me/src/python-lockup
Project Packages:   /home/me/src/python-lockup/__pypackages__/3.6
{
  "implementation_name": "cpython",
  "implementation_version": "3.6.15",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.10.16.3-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Fri Apr 2 22:23:49 UTC 2021",
  "python_full_version": "3.6.15",
  "platform_python_implementation": "CPython",
  "python_version": "3.6",
  "sys_platform": "linux"
}
```

**Comment by emcd** [comment]
It should be noted that `pdm list` does detect when it is attached to a TTY or not and behaves correctly. So, this is an inconsistency with how different parts of the `pdm` CLI work.

**Comment by frostming** [comment]
Can't reproduce here, can you try the main branch?

**Comment by emcd** [comment]
Ah, yes, it seems to be fixed on the main branch. Sorry - I didn't see any bug report around this and so I didn't bother to check against the latest code.

```bash
$ python -m pdm --version
pdm, version 1.10.4.dev13+geec4112
```

**Comment by emcd** [comment]
As a side note, it might help to add something like the following to the instructions at https://pdm.fming.dev/contributing/#local-development:
> Please ensure that your `setuptools` version is recent if you see ```ERROR: File "setup.py" not found.``` when you try `pip install -e .`. `pip install --upgrade setuptools wheel pip` is recommended.

**Comment by frostming** [comment]
> As a side note, it might help to add something like the following to the instructions at https://pdm.fming.dev/contributing/#local-development:
> 
> > Please ensure that your `setuptools` version is recent if you see `ERROR: File "setup.py" not found.` when you try `pip install -e .`. `pip install --upgrade setuptools wheel pip` is recommended.

I tried with a clean virtualenv and uninstall `setup.py` manually, it runs and succeeds smoothly. The only requirement to run this command is `pip >=21.3`

**Comment by emcd** [comment]
Ah, I see. My system `pip` is also out-of-date and the venv that I made to build `pdm` was based off that. I remembered something about a minimum `setuptools` version being needed for `setup.cfg`-only operation and thought that was the problem. But, it seems to be the minimum `pip` version is the problem in this case. Forget that I said anything. :)
