### ISSUE TITLE
Package pin on Git commit hash being ignored.

### ISSUE THREAD

**Issue by emcd** [pdm-project/pdm#769]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

Given the following dependencies:
```toml
[tool.pdm.dev-dependencies]
documentation = [
  'furo',
  'sphinx',
  'sphinx-copybutton',
  # NOTE: Locked because of Python >= 3.8 requirement.
  'sphinx-inline-tabs==2021.3.28b7',
]
lint = [
  'bandit',
  'mypy',
  'pyenchant',
  'pylint',
  'semgrep',
]
miscellany = [
  'bump2version',
  'invoke',
  'pre-commit',
  'tomli',
  'twine',
  # QUESTION: Do we need this explicitly?
  'wheel',
  # NOTE: Locked because of missing diff tool.
  'yapf @ git+https://github.com/google/yapf.git@9d6808a3d9b9a0ea40efea0c7cc3247464dbc291',
]
test = [
  # NOTE: Locked because of automatic .gitignore overwriting.
  'coverage[toml]<6.1',
  'hypothesis',
  'pytest',
  'tox',
  'tox-asdf',
]
```
and its equivalent Pipfile dev dependencies and `requires-python = "== 3.6"` in `pyproject.toml` and the equivalent Python version in the Pipfile, the following commands were used to extract lists of resolved dependency versions:
```bash
pdm list | tail +3 | awk '{print $1,$2}' | egrep -v '(editables|lockup|setuptools|wheel)' >pdm-packages.txt
pipenv run pip freeze | tr '=' ' ' | sed 's| @ | |g' | awk '{print tolower($1),$2}' >pipenv-packages.txt
```
A diff was taken of these two files, which showed at least one major version difference between packages as well as some minor version differences, even though both locks had been recently regenerated before the experiment. However, the most interesting find was that `pdm` chose to ignore the Git commit hash pin on `yapf` and instead install a buggy release of `yapf` that I was deliberately trying to avoid.

## Actual behavior

Note that `pdm` chose `yapf 0.31.0` rather than the explicitly pinned Git commit hash.

```bash
$ diff pdm-packages.txt pipenv-packages.txt
13c13
< cfgv 3.0.0
---
> cfgv 3.3.1
25c25
< gitpython 3.1.20
---
> gitpython 3.1.18
27c27
< identify 1.6.2
---
> identify 2.4.0
34c34
< isort 5.8.0
---
> isort 5.10.1
51c51
< pre-commit 2.1.1
---
> pre-commit 2.15.0
56c56
< pylint 2.12.0
---
> pylint 2.12.1
75c75
< sphinx 4.3.0
---
> sphinx 4.3.1
77c77
< sphinx-inline-tabs 2021.3.28b7
---
> sphinx_inline_tabs 2021.3.28b7
92c92
< typing-extensions 4.0.0
---
> typing_extensions 4.0.0
98c98
< yapf 0.31.0
---
> yapf git+https://github.com/google/yapf.git@9d6808a3d9b9a0ea40efea0c7cc3247464dbc291
```

## Expected behavior

`pdm` would honor the pinned commit hash for `yapf`.

## Environment Information

```bash
$ pdm info && pdm info --env
PDM version:        1.10.3
Python Interpreter: /home/me/.asdf/installs/python/3.6.15/bin/python (3.6)
Project Root:       /home/me/src/python-lockup
Project Packages:   /home/me/src/python-lockup/__pypackages__/3.6
{
  "implementation_name": "cpython",
  "implementation_version": "3.6.15",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.10.16.3-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Fri Apr 2 22:23:49 UTC 2021",
  "python_full_version": "3.6.15",
  "platform_python_implementation": "CPython",
  "python_version": "3.6",
  "sys_platform": "linux"
}
```

**Comment by emcd** [comment]
As noted in the above diff output, there are some other curious issues as well:

* `pdm` chose a much lower version of `identify`, in spite of the platform and acceptable Python versions being the same between the `Pipfile` and `pyproject.toml`.
* `pdm` does not preserve case in the package name (e.g., `GitPython`) and so I had to lowercase package names to make a good comparison.
* `pip` chooses underscores rather than hyphens for some packages, even though they appear with hyphens on PyPI. The behavior of `pdm` seems better in this case, but it would be nice to understand why `pip` chooses underscores in some cases (`sphinx-inline-tabs` and `typing-extensions`) but hyphens in other cases (`pre-commit`).

I can file separate bugs for the above if desired.

**Comment by frostming** [comment]
First you are using different output method for comparison, if you change the command to list pdm dependencies to `pip freeze --path __pypackages__/X.Y/lib` you will find the case inconsistency is gone and `yapf` git version is correct.

Second, for package version selection, in fact `identify>1.6.2` requires [python >= 3.6.1](https://github.com/pre-commit/identify/blob/89d9e7500e59c7eb62ca8eef2cccde8e0f825375/setup.cfg#L25) and is considered not eligible with all python versions specified by project's `requires-python = "== 3.6"`(Note that `==3.6` is equivalent to `==3.6.0`). So PDM rejects that version.

Pipenv's resolver doesn't promise that kind of compatibility, you can easily generate a lock file that can't work on other Python versions you demand.

**Comment by emcd** [comment]
> First you are using different output method for comparison, if you change the command to list pdm dependencies to `pip freeze --path __pypackages__/X.Y/lib` you will find the case inconsistency is gone and `yapf` git version is correct.

OK, I was trying to use the "native" method provided by `pdm`. Is there is a reason why `pdm list` would show something different than `pip freeze --path __pypackages__/3.6/lib`? I think that is a bit confusing and can mislead people into thinking that it is not working correctly.

> Second, for package version selection, in fact `identify>1.6.2` requires [python >= 3.6.1](https://github.com/pre-commit/identify/blob/89d9e7500e59c7eb62ca8eef2cccde8e0f825375/setup.cfg#L25) and thus it isn't considered eligible with all python versions specified by project's `requires-python = "== 3.6"`(Note that `==3.6` is equivalent to `==3.6.0`).

OK, fair point. For some reason, I thought PEP 440 said something different, but you are correct.

> Pipenv's resolver doesn't promise that kind of compatibility, you should better assume the lock file only works on the python version within the virtualenv and can't work on other Python versions you demand.

Yes, and that is why I limited the test to Python 3.6. I wanted to do as close of a comparison as possible between Pipenv and PDM before deciding to switch from one to the other. I will rerun the test with `requires-python = "==3.6.15"`. Thanks for catching that oversight.

**Comment by frostming** [comment]
> Is there is a reason why pdm list would show something different than pip freeze --path __pypackages__/3.6/lib

That is a choice of UI. PDM also provides `pdm list --freeze` to produce the exact same result as `pip freeze`
