### ISSUE TITLE
Displays version number 0.0.0

### ISSUE THREAD

**Issue by bolinocroustibat** [pdm-project/pdm#772]
PDM displays 0.0.0 as a version number instead of 1.11.0.

<img width="270" alt="Screen Shot 2021-12-01 at 14 50 44" src="https://user-images.githubusercontent.com/4353767/144179474-922ce99a-8e02-439a-9b1f-541b732905f3.png">

It seems it is the case since it was upgraded from 1.10.3 to. 1.11.0  (upgraded via Brew, on MacOS 11.6).

**Comment by frostming** [comment]
Thanks, that is due to the wrongly built tarball. It will be fixed in the next patch release.
