### ISSUE TITLE
Support per-package `--prerelease` option

### ISSUE THREAD

**Issue by agoose77** [pdm-project/pdm#774]
## Is your feature request related to a problem? Please describe.

Poetry provides the user with the ability to specify `--prerelease` on a per `poetry add` basis. This is likely more useful than a per-project setting, because (in my experience) most of the time it's only certain packages that should be pre-releases.

## Describe the solution you'd like

A  `--prerelease` option for `pdm add` which allows the user to install pre-releases for the given dependencies. This would require an entry in `tool.pdm`, e.g. `tool.pdm.pre-dependences` to store this for future resolutions.

**Comment by frostming** [comment]
> This would require an entry in tool.pdm, e.g. `tool.pdm.pre-dependences` to store this for future resolutions.

I have a different idea to implement this. We may need not any extra table, `--prerelease` can be a one-off flag only applicable in `pdm add` that controls which version is to be pinned in the `pyproject.toml`.

```
pdm add foo
# results in:
dependencies = ["foo~=1.0"]
pdm add --prerelease foo
# results in:
dependencies = ["foo>=1.1.0b1,<2.0"]
```
Because in PEP 440, `~=1.0` doesn't allow prereleases while `>=1.1.0b1,<2.0` does. The prerelease flag is indeed saved in the version specifier, we don't need to save it elsewhere.

**Comment by agoose77** [comment]
@frostming this would work!

Maybe there would also be an option for `--prerelease` with `pdm update` as well?

**Comment by prudnikov** [comment]
Is there any way to make it work with 
```
[tool.pdm.resolution]
allow-prereleases = false
```
I mean, in the prod environment, I don't want to install pre-releases of 3rd party packages. But I have a dependency from `apache-airflow`, which in turn depend `opentelemetry-semantic-conventions==0.48b0` through other intermediate dependencies. And this package can't be resolved. I can add it to 
```
[tool.pdm.resolution.overrides]
opentelemetry-semantic-conventions = "==0.48b0"
```
but still can't be resolved.
