### ISSUE TITLE
pip import in install-pdm.py

### ISSUE THREAD

**Issue by u1138** [pdm-project/pdm#780]
install-pdm.py requires pre-installed pip:
https://github.com/pdm-project/pdm/blob/99612031451b41534a0e61fa4356cf0a07262bd3/install-pdm.py#L19
It appears that pre-installed pip is used only to install virtualenv package, however this step is not needed in many or most cases. Maybe it would be better to move the import from the top of the script inside the function, or even to use alternative virtualenv install method [via zipapp](https://virtualenv.pypa.io/en/latest/installation.html#via-zipapp) just like in [install-poetry.py](https://github.com/python-poetry/poetry/blob/6a35cc41e950d4ff0f1efad649c1d15d689a9ce2/install-poetry.py#L294)?

**Comment by frostming** [comment]
Thanks, will do

**Comment by frostming** [comment]
Fixed in 8b3ebd36
