### ISSUE TITLE
Cannot import pywintypes

### ISSUE THREAD

**Issue by fqwl** [pdm-project/pdm#784]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Initialize and then add xlwings
```bash
pdm init
pdm add xlwings
```
`import xlwings as xw` in py file

## Actual behavior

Get the error that pywintypes could not be found after`import xlwings`
```python
Traceback (most recent call last):
  File "e:\Code\pdm-test\test.py", line 1, in <module>
    import xlwings as xw
  File "e:\Code\pdm-test\__pypackages__\3.9\lib\xlwings\__init__.py", line 9, in <module>
    from . import _xlwindows as xlplatform
  File "e:\Code\pdm-test\__pypackages__\3.9\lib\xlwings\_xlwindows.py", line 14, in <module>
    import pywintypes
  File "e:\Code\pdm-test\__pypackages__\3.9\lib\win32\lib\pywintypes.py", line 117, in <module>
    __import_pywin32_system_module__("pywintypes", globals())
  File "e:\Code\pdm-test\__pypackages__\3.9\lib\win32\lib\pywintypes.py", line 98, in __import_pywin32_system_module__
    raise ImportError("No system module '%s' (%s)" % (modname, filename))
ImportError: No system module 'pywintypes' (pywintypes39.dll)
```

## Expected behavior

After installing `xlwings`, can find `pywintypes39.dll` in `__pypackages__\3.9\lib\pywin32_system32\`, it should be imported correctly

## Environment Information

```powershell
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.11.0
Python Interpreter: C:/Python39/python.EXE (3.9)
Project Root:       E:/Code/pdm-test
Project Packages:   E:\Code\pdm-test\__pypackages__\3.9
```

**Comment by frostming** [comment]
This is because `pywin32` doesn't support PEP 582 scheme. Although I can patch PDM to update the functions in `sysconfig`, I consider this would be a breaking change since it will change where`pip` installs packages to.

So IMHO you can report this to the maintainers of `pywin32` to make it support PEP582?
