### ISSUE TITLE
Main website blocked in India

### ISSUE THREAD

**Issue by freakynit** [pdm-project/pdm#786]
The main website (https://pdm.fming.dev/) is blocked by India's `Ministry of Electronics and Information Technology` (https://www.meity.gov.in/).... I don't see a reason as to why this should be blocked.

Can you folks get it unblocked by getting in touch with them? Do ping them on social media. Else, I personally don't think you'll ever get a response back. 

<img width="816" alt="Screenshot 2021-12-10 at 8 48 43 AM" src="https://user-images.githubusercontent.com/745352/145511671-302d1a3e-9465-4bbc-bd40-8bb1f33f355d.png">

**Comment by abelcheung** [comment]
@freakynit Suspect this is more like a political decision. Even complaining won't get you anywhere...

**Comment by abelcheung** [comment]
Indeed, especially when it is open source software related. But apparently we alone can do nothing about those political stuff *shrug*

**Comment by freakynit** [comment]
This is now unblocked... I suspect some kind of automated system flagging website initially. 
The issue can be closed I believe 🤷‍♂️

**Comment by frostming** [comment]
Thanks 😄
