### ISSUE TITLE
Support prepare script after pdm install

### ISSUE THREAD

**Issue by yinzixie** [pdm-project/pdm#789]
## Describe the solution you'd like
I can configure to automatically run a command after the command `pdm install`.
Just like script "prepare" in npm.
This would be useful for new users init project, for example, I don't need to worry about them forgetting to init pre-commit.

**Comment by frostming** [comment]
SGTM, would you like to help implement?

**Comment by frostming** [comment]
npm support more special scripts than `prepare`, as well as `pre` and `post` prefixes.

**Comment by yinzixie** [comment]
Haha. That's just a user case, I wish I could help but I don't know how to do it.
