### ISSUE TITLE
SyntaxError during curl installation on Mac

### ISSUE THREAD

**Issue by peemblis** [pdm-project/pdm#792]
- [x ] I have searched the issue tracker and believe that this is not a duplicate.

Running curl command below to install pdm results in syntax error. I'm on a Mac.

## Steps to reproduce

```
❯ curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python -
  File "<stdin>", line 39
    def _call_subprocess(args: list[str]) -> int:

                             ^
SyntaxError: invalid syntax
```

## Actual behavior

`SyntaxError` above

## Expected behavior

Expected pdm to be installed.

**Comment by pawamoy** [comment]
Hi! What your Python version?

**Comment by peemblis** [comment]
3.7

**Comment by frostming** [comment]
try replacing the last python to python3.7 or python3
