### ISSUE TITLE
The path to the python interpreter of the project is added to the end of PATH when using `pdm run`

### ISSUE THREAD

**Issue by dominik-schwabe** [pdm-project/pdm#797]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**
I am not sure if this is a bug but for me it is an inconvenience.
When i run `bash -c 'echo $PATH'` i get the following output:
```bash
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
```
When i run `pdm run bash -c 'echo $PATH'` i get the following output:
```bash
/home/myname/test/__pypackages__/3.9/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/home/myname/.asdf/installs/python/3.9.7/bin
```
In my opinion there is no reason to add `/home/myname/.asdf/installs/python/3.9.7/bin` to the end of PATH, because the `python` executable inside will not be used, because there is a `python` executable in `/bin`, which occurs before `/home/myname/.asdf/installs/python/3.9.7/bin` and is therefore preferred when calling `python`. I think the path (in my case `/home/myname/.asdf/installs/python/3.9.7/bin`) should be added after `/home/myname/test/__pypackages__/3.9/bin` instead, because the python interpreter inside it would be used instead of the system interpreter when spawning a shell whit `pdm run bash` and executing `python` in this spawned shell.
e.g. the preferred PATH would be:
```bash
/home/myname/test/__pypackages__/3.9/bin:/home/myname/.asdf/installs/python/3.9.7/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
```

The content of my `.pdm.toml` is:
```toml
[python]
path = "/home/myname/.asdf/installs/python/3.9.7/bin/python"
```
I am aware that this is no perfect solution, because this will fail when there are multiple different interpreters in the same path, but it will work when the interpreters are isolated e.g. when using `pyenv` or `asdf`.

## Steps to reproduce
Initialize some project with `pdm init` and run `pdm run bash -c 'echo $PATH'`

## Actual behavior
The path to the locally configured python interpreter is added to the end of PATH.

## Expected behavior
The path to the locally configured python interpreter should be added to the beginning of PATH, but after `*/__pypackages__/*/bin`.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.11.2
Python Interpreter: /home/myname/.asdf/installs/python/3.9.7/bin/python (3.9)
Project Root:       /home/myname/test
Project Packages:   /home/myname/test/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.7",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.4.0-89-generic",
  "platform_system": "Linux",
  "platform_version": "#100~18.04.1-Ubuntu SMP Wed Sep 29 10:59:42 UTC 2021",
  "python_full_version": "3.9.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by xulongwu4** [comment]
@dominik-schwabe, I think it might also cause issues if the path to the configured python is added to the beginning of the `PATH` right after `__pypackages__/3.x/bin`. For example, if I am using the system python for my project, the path to the configured python interpreter can be something like `/usr/bin`. The point is, this path could contain a lot of executable. Making this path appear early in the `PATH` environment variable basically raised the priority of all executable in the same folder as the configured python executable.

I might prefer some executable in places in `$HOME/.local/bin`, and to do that, I make sure `$HOME/.local/bin` appears before `/usr/bin` in my `PATH`. However, if `pdm run` is going to make `/usr/bin` appear early in the `PATH` variable, that would beat the purpose of picking executable in `$HOME/.local/bin` first.

**Comment by dominik-schwabe** [comment]
@xulongwu4 I see the point. When someone uses a interpreter from `/usr/bin` it has indeed a lot of unwanted side effects. Let me elaborate a bit on my workflow. When I develop on a project, I usually use `pipenv run nvim` or in this case `pdm run nvim`, so that i can spawn a repl with e.g. [vim-slime](https://github.com/jpalardy/vim-slime) to which i then send python code. When i have ipython installed, this will work with pdm without issues, since ipython is aware of the python version that was used to install it. But when i use the pure python interpreter it will choose the global one. I see this is a problem that is hard to solve. I have two ideas to tackle this problem:
- create a `python` symlink in `__pypackages__/3.x/bin` to the configured python version (I am absolutely unaware of the side effects with this approach.)
- add an option to `pdm run` like `pdm run --expose` that would give this behavior (This would make pdm more bloated.)

For me this is not a big issue. As described, pdm with ipython works perfectly fine and i usually install ipython when i work on a project.

**Comment by frostming** [comment]
In fact, `pdm run` was designed for one-off tasks and I never expect it should spawn long-running processes like `bash` or `vim`. But if you are comfortable with this approach that is on you. Apparently, appending the host python's bin to the end is not for python discovery, but for any third-party console scripts installed with it, just as a fallback so it wouldn't appear earlier.

For more rationales behind this, `pdm run` means you want to use the libraries in `__pypackages__` not elsewhere. In this case, the python interpreters don't make any difference as long as it has the same major.minor version, i.e. `/usr/bin/python3.9` works the same as `~/.local/asdf/python/3.9/bin/python`. Yes, the `site-packages` are different but `pdm run` shouldn't care about this, per the previous statement. So if you are preferring this usage of `pdm run` that enters a subshell, you are responsible to use the correct Python interpreter in order to find `__pypackages__/X.Y` correctly.

**Comment by dominik-schwabe** [comment]
Ok, i understand and close the issue.
