### ISSUE TITLE
Document how to configure Neovim/Vim to work with PDM

### ISSUE THREAD

**Issue by lyz-code** [pdm-project/pdm#804]
## Is your feature request related to a problem? Please describe.

I'm willing to give the jump from Poetry to PDM, but I don't see how to configure my IDE (neovim) to work with PDM. I still need to read your articles on why you don't use virtualenvs (which I think is awesome), which would make me understand better what would I have to do to make it work.

## Describe the solution you'd like

Clear instructions on how to make pdm work within a vim environment are added to the documentation

**Comment by frostming** [comment]
I am using vim myself, but you can refer to [Emacs Config](https://pdm.fming.dev/usage/advanced/#work-with-lsp-python-ms-in-emacs). It should work by adding `__pypackages__` to `PATH` and `PYTHONPATH`. The packages path can be returned by `pdm info --packages`

Welcome to contribute if you find out a working example

**Comment by lyz-code** [comment]
Thank you for your quick answer. I still need to understand how do the linters and fixers understand that when you open a file, it's able to run them using only the project's packages. Once I finish all the reading I've still got on your (awesome) package, I'll surely contribute to the docs.

**Comment by wizard-28** [comment]
@frostming, I couldn't get it to work, I'm on fish and I ran:
```bash
pdm --pep582 | source
set -x PATH (pdm info --packages):$PATH
set -x PYTHONPATH (pdm info --packages):$PYTHONPATH
```

Still neovim `pyright` LSP complains that it could not find the imports could not be resolved

My code:
```py
from rich import print
```

My packages:
```py
Package            Version Location
------------------ ------- --------
colorama           0.4.4
commonmark         0.9.1
pygments           2.10.0
rich               10.16.1
```

**Comment by frostming** [comment]
The path is wrong:
```fish
set -x PATH (pdm info --packages)/bin:$PATH
set -x PYTHONPATH (pdm info --packages)/lib:$PYTHONPATH
```

**Comment by frostming** [comment]
@lyz-code Can you confirm if the above solves your problem?

**Comment by lyz-code** [comment]
Hey @frostming these are busy days for me, I hope to squeeze some time next week for this.

If you want to close the issue, it's fine, I'll reopen it if I encounter any problem. I'll still make the PR once I make it work

**Comment by BbsonLin** [comment]
Hello guys, I'm also setting my NeoVim config these days. I've checked Pyright repo's [issue 2767](https://github.com/microsoft/pyright/issues/2767#issuecomment-1002212686)

```
[tool.pyright]
extraPaths = ["__pypackages__/3.8/lib/"]
```
Putting these lines in pyproject.toml seams to work. FYI

**Comment by lyz-code** [comment]
Until `mypy` supports `__pypackages__` I'm not going to dive yet into dropping virtualenvs, so I'll make the PR when I fight with it then

**Comment by Andrew15-5** [comment]
The Emacs link is broken, but I found https://pdm-project.org/en/latest/usage/pep582/#neovim. I tried setting

```toml
[tool.pyright]
extraPaths = ["__pypackages__/3.10/lib/"]
```

and same thing but with many other ways with no luck. I almost gave up on this, but then found and tried https://stackoverflow.com/a/75509259:

```toml
[tool.pyright]
venvPath = "."
venv = ".venv"
```

Which did work out. But strangely setting this in Lua config does nothing.
