### ISSUE TITLE
Shimming like pnpm for npm

### ISSUE THREAD

**Issue by NoelJacob** [pdm-project/pdm#805]
SImply one copy for everything

**Comment by frostming** [comment]
Is there any documentation link for reference?

**Comment by frostming** [comment]
Do you mean https://pdm.fming.dev/usage/project/#cache-the-installation-of-wheels ?

**Comment by NoelJacob** [comment]
Oh, yes thank you! <3

**Comment by NoelJacob** [comment]
Oh, yes thank you! <3
