### ISSUE TITLE
pipenv install --deploy / poetry lock --check equivalent?

### ISSUE THREAD

**Issue by gitpushdashf** [pdm-project/pdm#810]
It's really nice in CI to require that the lock file is up to date. So I like to use `pipenv install --deploy` or `poetry lock --check` (Poetry v1.2). I can't find an equivalent in `pdm`. Is there one?

If pyproject.toml has been updated, I want to require that the lockfile is current and there's no disparity.

Thank you!

**Comment by pawamoy** [comment]
`pdm install --no-lock`? I think it'll fail if there's a hash mismatch.

**Comment by gitpushdashf** [comment]
Ah, that is it. Thank you!

I think I saw that, but I thought `--no-lock` meant to ignore the lockfile.

**Comment by frostming** [comment]
I think it is worth adding, `--no-lock` is just a side-effect, if the package exists in the lock file it won't crash.

**Comment by gitpushdashf** [comment]
Wow, thank you so much!
