### ISSUE TITLE
reportMissingImports from Pylance in VS Code

### ISSUE THREAD

**Issue by Xemnas0** [pdm-project/pdm#815]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

- Install PDM
- pdm init
- pdm add numpy (or any other package)
- Write a main.py that imports numpy
- Add `{
    "python.autoComplete.extraPaths": ["__pypackages__/<major.minor>/lib"],
    "python.analysis.extraPaths": ["__pypackages__/<major.minor>/lib"]
}` to .vscode/settings.json

## Actual behavior

VS Code does not detect the installed package.

## Expected behavior

VS Code should detect the installed package.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

PDM version:        1.11.3
Python Interpreter: C:/Users/msi/AppData/Local/Programs/Python/Python39/python.exe (3.9)
Project Root:       D:/other_projects/pdm_folder
Project Packages:   D:\other_projects\pdm_folder\__pypackages__\3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.9",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19042",
  "python_full_version": "3.9.9",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "win32"
}

```

**Comment by Xemnas0** [comment]
Problem solved by replacing "<major.minor>" with "3.9".
Thanks @frostming

**Comment by edouard-lopez** [comment]
For me it was the following who did the trick

```
  "python.autoComplete.extraPaths": [".venv/lib/*/"],
  "python.analysis.extraPaths": [".venv/lib/*/"]
```
