### ISSUE TITLE
distutils hack

### ISSUE THREAD

**Issue by pawamoy** [pdm-project/pdm#821]
Related to #623

Not a bug nor a feature request. Just a question and possible enhancement.

Since a few days, I'm getting this `distutils-precedence.pth` file installed, which triggers error messages just like in #623.

```console
% cat __pypackages__/3.9/lib/distutils-precedence.pth 
import os; var = 'SETUPTOOLS_USE_DISTUTILS'; enabled = os.environ.get(var, 'local') == 'local'; enabled and __import__('_distutils_hack').ensure_shim();
```

```
Error processing line 1 of /media/data/dev/mkdocstrings/__pypackages__/3.9/lib/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.9.9/lib/python3.9/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
```

I guess it comes from setuptools:
- https://stackoverflow.com/questions/69038398/python-module-distutilis-hack
- https://github.com/pypa/setuptools/blob/main/_distutils_hack/__init__.py

Not sure why the `_distutils_hack` module cannot be found. Not sure if it's completely useless when using PDM, though everything works fine even when I delete this `distutils-precedence.pth` file.

**Comment by frostming** [comment]
Are you using a `.pth` based install cache?

**Comment by pawamoy** [comment]
Yes, symlinks didnt work yet so I stayed on version 1.11.3 and pth based cache.

**Comment by frostming** [comment]
That is simply because `distutils-precedence.pth` is executed before `setuptools.pth`, which loads the path of `_distutils_hack`

**Comment by pawamoy** [comment]
Hmmm. Should I raise an issue on setuptools tracker then? Not sure if this actionable at all in PDM. Feel free to close.

**Comment by frostming** [comment]
No, it is not setuptools' fault. It is the nature of .pth file loading, they are looked one by one. Prefixing the pdm generated pth file with `aaaaa_` can fix this, but that looks ugly.

**Comment by warsaw** [comment]
I landed here when I ran into the same problem both locally and in [my CI](https://gitlab.com/warsaw/flufl.lock/-/jobs/1950193258).  I can see that @frostming had some suggested workaround in #623 but that does not seem to help when testing locally because:

* The error is comming from setuptools
* `pdm config --local feature.install_cache` already returns `False`
* I'm running from a clean git checkout (i.e. after `git clean -dxffi`)

I'm running under tox with multiple versions of Python, from 3.7 to 3.10.

```
py37 run-test-pre: PYTHONHASHSEED='2171121435'
py37 run-test: commands[0] | pdm config --local use_venv True
py37 run-test: commands[1] | pdm config --local feature.install_cache False
py37 run-test: commands[2] | pdm install -G testing
⠋ Resolving packages from lockfile...
⠙ Resolving packages from lockfile...
⠹ Resolving packages from lockfile...
⠸ Resolving packages from lockfile...
Synchronizing working set with lock file: 14 to add, 2 to update, 0 to remove

  ⠋ Updating setuptools 60.1.1 -> 60.3.1...
  ⠙ Updating setuptools 60.1.1 -> 60.3.1...
  ⠹ Updating setuptools 60.1.1 -> 60.3.1...
  ⠸ Updating setuptools 60.1.1 -> 60.3.1...
Error processing line 1 of /Users/barry/projects/flufl/lock/.tox/py37/lib/python3.7/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
Error processing line 1 of /Users/barry/projects/flufl/lock/.tox/py37/lib/python3.7/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
  ⠼ Updating setuptools 60.1.1 -> 60.3.1...
Error processing line 1 of /Users/barry/projects/flufl/lock/.tox/py37/lib/python3.7/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
Error processing line 1 of /Users/barry/projects/flufl/lock/.tox/py37/lib/python3.7/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
Error processing line 1 of /Users/barry/projects/flufl/lock/.tox/py37/lib/python3.7/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
Error processing line 1 of /Users/barry/projects/flufl/lock/.tox/py37/lib/python3.7/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
  ⠴ Updating setuptools 60.1.1 -> 60.3.1...
Error processing line 1 of /Users/barry/projects/flufl/lock/.tox/py37/lib/python3.7/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
Error processing line 1 of /Users/barry/projects/flufl/lock/.tox/py37/lib/python3.7/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
Error processing line 1 of /Users/barry/projects/flufl/lock/.tox/py37/lib/python3.7/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
  ⠦ Updating setuptools 60.1.1 -> 60.3.1...
 processing line 1 of /Users/barry/projects/flufl/lock/.tox/py37/lib/python3.7/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
  ⠧ Updating setuptools 60.1.1 -> 60.3.1...
  ⠇ Updating setuptools 60.1.1 -> 60.3.1...
  ⠏ Updating setuptools 60.1.1 -> 60.3.1...
  ⠋ Updating setuptools 60.1.1 -> 60.3.1...
  ⠙ Updating setuptools 60.1.1 -> 60.3.1...
  ⠹ Updating setuptools 60.1.1 -> 60.3.1...
  ⠸ Updating setuptools 60.1.1 -> 60.3.1...
  ✔ Update setuptools 60.1.1 -> 60.3.1 successful
```

I see this issue was closed, but I don't know if that's available in pdm 1.12.2, which is I think the latest version on PyPI and in brew.

**Comment by frostming** [comment]
How can I reproduce it locally? Does it fail on all python versions from 3.7 to 3.10? I am using PDM 1.12.3 and Python 3.10 but can't reproduce.

**Comment by agoose77** [comment]
I ran into this error too. In my case, I noticed that my package cache has an empty `$HOME/.cache/pdm/packages/setuptools-62.3.3-py3-none-any/lib/_distutils_hack/`

**Comment by frostming** [comment]
Is there any periodic clean strategy against the cache folder on your machine?

**Comment by agoose77** [comment]
Not that I have employed. I wonder whether the cache was corrupted by an interrupted install. Also I noticed that the `pdm cache clean` didn't remove any of the contents of `$HOME/.cache/pdm/packages/`, I had to remove it manually.

I cleaned the package cache, but the installation with `pdm sync` still failed (using the old lockfile) with the same complaint:
```
Synchronizing working set with lock file: 191 to add, 2 to update, 0 to remove

  ⠧ Updating setuptools 62.3.3 -> 62.3.3...
Error processing line 1 of /home/angus/.mambaforge/envs/phd-thesis/lib/python3.10/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/home/angus/.mambaforge/envs/phd-thesis/lib/python3.10/site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

  ✔ Update setuptools 62.3.3 -> 62.3.3 successful
  ✖ Update wheel 0.37.1 -> 0.37.1 failed
  See /tmp/pdm-install-5590pvcx.log for detailed debug log.
  [IsADirectoryError]: [Errno 21] Is a directory: '/home/angus/.mambaforge/envs/phd-thesis/lib/python3.10/site-packages/wheel'
  Add '-v' to see the detailed traceback
```

So, I then recreated the lockfile with `pdm lock`, and `pdm sync` just worked™

**Comment by frostming** [comment]
> didn't remove any of the contents of $HOME/.cache/pdm/packages/

The packages won't be removed unless they are not referred by any project.

**Comment by agoose77** [comment]
@frostming I can reproduce this now with a virtual env and the following lock/projectfiles:
[pdm.lock.txt](https://github.com/pdm-project/pdm/files/8910405/pdm.lock.txt)
[pyproject.toml.txt](https://github.com/pdm-project/pdm/files/8910406/pyproject.toml.txt)

Steps to reproduce:
1. Switch to temp dir `cd $(mktemp -d)`
1. Create a virtualenv  `python3 -m venv .venv && source .venv/bin/activate`
1. Run `pdm sync -vvv`

**Comment by frostming** [comment]
@vvanglro that looks weird, you are not using install cache, and the `_disutils_hack` package looks existing. Can you check the content of the package to see if it is empty?

**Comment by vvanglro** [comment]
> @vvanglro that looks weird, you are not using install cache, and the `_disutils_hack` package looks existing. Can you check the content of the package to see if it is empty?

This is package content:
![image](https://github.com/pdm-project/pdm/assets/43594924/3d895481-ef95-4fbf-ad69-dcd68b9cb927)

**Comment by frostming** [comment]
Ok, I think it is a temporary state since you are uninstalling and installing `setuptools`. Does the error persist after that?

**Comment by vvanglro** [comment]
> Ok, I think it is a temporary state since you are uninstalling and installing `setuptools`. Does the error persist after that?

Yes, This is still the case when executing `pdm update` again.

![image](https://github.com/pdm-project/pdm/assets/43594924/c16dbf61-8942-40e4-8fb5-5f7f155719b3)

**Comment by frostming** [comment]
I mean it only occurs when you update `setuptools`.

**Comment by vvanglro** [comment]
> I mean it only occurs when you update `setuptools`, not every time.

Oh, I understand, but every time `pdm update` is executed, it will be displayed in the upgrade setuptools 67.7.2 -> 68.0.0.

**Comment by vvanglro** [comment]
> @vvanglro It may be related to the incomplete uninstall #2075

Wow, That's right now.

> Ok, I think it is a temporary state since you are uninstalling and installing `setuptools`. Does the error persist after that?

 I first used pip to uninstall setuptools, and then when I executed `pdm update`, an error would be reported as you said, but when I executed it again, setuptools would not be updated repeatedly.
