### ISSUE TITLE
UnicodeDecodeError while compiling c-extension

### ISSUE THREAD

**Issue by I-love-study** [pdm-project/pdm#823]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

```bash
Exception in thread Thread-18:
Traceback (most recent call last):
  File "D:\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\I_Love_Study\AppData\Roaming\pdm\venv\lib\site-packages\pdm\builders\base.py", line 55, in run
    for line in self.reader:
UnicodeDecodeError: 'gbk' codec can't decode byte 0x9d in position 56: illegal multibyte sequence
```

## Steps to reproduce
compile package with c-extension(like pyyaml)

## Actual behavior
raise UnicodeDecodeError and install failed

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.12.1
Python Interpreter: D:/Python310/python.EXE (3.10)
Project Root:       E:/xxx
Project Packages:   E:\xxx\__pypackages__\3.10
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.1",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.22000",
  "python_full_version": "3.10.1",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "win32"
}
```

**Comment by pawamoy** [comment]
Try exporting the `PYTHONUTF8=1` environment variable.

**Comment by I-love-study** [comment]
exporting `PYTHONUTF-8=1` not working
I add `encoding` param in here and it's working
https://github.com/pdm-project/pdm/blob/0f224898d6ff7d37bcb1c77c9507ccac325100c1/pdm/builders/base.py#L42
```python
self.reader = os.fdopen(self.fd_read, encoding="UTF-8")
```

**Comment by pawamoy** [comment]
The variable name is `PYTHONUTF8` without a dash. Not sure what you've tested.

**Comment by I-love-study** [comment]
> The variable name is `PYTHONUTF8` without a dash. Not sure what you've tested.

Oops, I just write wrong with a dash in it. Sorry about it.
Adding `PYTHONUTF8=1` can work too.
