### ISSUE TITLE
strategy.save also affects "pdm update --unconstrained"

### ISSUE THREAD

**Issue by blueyed** [pdm-project/pdm#834]
I am using `pdm update --no-sync --update-eager --unconstrained` to upgrade dependencies, and noticed that the change of the default for "strategy.save" in pdm 1.11.3 (via 87595dc) changed the resulting `pyproject.toml`, e.g.:

```diff
 dependencies = [
-    "django~=4.0",
+    "django",
 ]
```

Note that this changed in 1.12.0 (via 21cbbca) then to `"django>=4.0"`, when the typo ("mininum" => "minimum") was fixed.

While the change itself is good, I think that the `strategy.save` should either not get used here (the package is not being added), or the documentation being extended.

Currently it says (https://pdm.fming.dev/configuration/):

> Specify how to save versions when a package is added

Likely this is due to the package being removed internally for unconstrained upgraded, and then added, which then uses this setting.

**Comment by frostming** [comment]
On the contrary, I think the strategy should be used here. It is used whenever a package needs to be saved in the pyproject.toml but is not constrained. `--unconstrained` is for the dependency solver to find a proper solution ignoring the *current* constraints, but when a solution is found, the packages should be saved with version constraints, unless the strategy is "wildcard".

**Comment by blueyed** [comment]
I've liked the upper bounds to distinguish between "update" (`pdm update --update-eager`) and "upgrade" (`pdm update --update-eager --unconstrained`).
With the changed (default) setting "update" and "upgrade" will behave the same now.

I can see that I could change `strategy.save`, but a) I still think that it is not adding packages in the first place, and should not use this setting, and b) it is not possible to configure this for the project, but only locally (with `.pdm.toml`, which is not meant to be shared/committed).

If you still think this should be closed / works as intended I think the doc for this setting should get updated at least.

And as for b) above: I've updated my update/upgrade Makefile targets to use `pdm update --save-compatible …`, which also causes the bounds to be updated (i.e. not keeping the existing ones), so this is feasible as a workaround for me.

(While I agree that upper bounds are problematic in general, it makes sense to me for controlled updates/upgrades in an app though)

**Comment by blueyed** [comment]
What about if the `strategy.save` option would not be used for the default of `pdm update` (as it appears to be), but it (`pdm update`) defaulting to keeping the existing style ("compatible", "wildcard", "exact", or "minimum") when `--unconstrained` is used?
