### ISSUE TITLE
pdm update: --dry-run does not display changes

### ISSUE THREAD

**Issue by blueyed** [pdm-project/pdm#837]
While investigating into #836 I've found that `pdm update --no-sync --update-eager --dry-run` ~~actually writes `pdm.lock`~~ does not display the differences, despite the help saying:

>   --dry-run, --outdated
>      Show the difference only without modifying the lockfile content

pdm 1.12.2 (current main).

**Comment by blueyed** [comment]
Sorry, must have confused something: it says "Lock successful", but does not write it (and does not say "Changes are written to pdm.lock."), but also does not display the differences either - at least not the change for `name = "pygments"` (as described in #836).

**Comment by frostming** [comment]
The changes are actually displayed by the `sync` action, you just leave the `--no-sync` option and it should work.

**Comment by blueyed** [comment]
I see.
So it appears to display the differences to the synced packages, which is different to what would be updated/changed in the lock file.
I.e. if you have not run `pdm install` yet, it would not only display packages to be updated, but all the unchanged (to be installed) ones also.

I can see that this might be intended, and it is easy to diff the lock file yourself before/after.

But it should probably display a warning, or even better display it also when `--no-sync` is used (but just not sync actually then).

**Comment by frostming** [comment]
I fixed the behavior so that `--dry-run` will show the difference even if `no-sync` is passed.
