### ISSUE TITLE
Access global/user python modules

### ISSUE THREAD

**Issue by DUOLabs333** [pdm-project/pdm#838]
## Is your feature request related to a problem? Please describe.

I have some python modules globally installed. Before, any script I run with `pdm run` allowed me to access those modules. The newest update removed the ability to use those modules.

## Describe the solution you'd like
Allow any script run with `pdm run` to access the modules outside the current directory.

**Comment by DUOLabs333** [comment]
Fixed with `-s/--site-packages`. This actually makes a lot of sense why isolation is the default (I would like it that way), but the package in question is a pain to build for the pdm directory.

**Comment by DUOLabs333** [comment]
However, it should probably be renamed to `--global`.

**Comment by frostming** [comment]
Thanks, but `--global` is used by another option with a different meaning.
