### ISSUE TITLE
Website blocked (again) in India

### ISSUE THREAD

**Issue by icy-comet** [pdm-project/pdm#844]
This was mentioned earlier in #786. And although the site was unblocked then, it has been blocked again as of today.

It is very unlikely that the block is a political decision. Some small technical detail could be flagging the site.

Just wanted to bring this to attention.

**Comment by mkniewallner** [comment]
Possibly related to https://github.com/captn3m0/hello-cloudflare/blob/main/README.md.
If this is the case, 2 different solutions are suggested [here](https://github.com/captn3m0/hello-cloudflare/blob/main/README.md#help-my-website-is-blocked).

**Comment by icy-comet** [comment]
@mkniewallner could be. But I am not using Airtel as my ISP. So the issue must extend to other networks as well.

**Comment by mkniewallner** [comment]
Airtel is used as a peering partner by Cloudflare, so even if your ISP is not Airtel, you could be affected.
A PR updated the wording, to make that clearer https://github.com/captn3m0/hello-cloudflare/pull/5.

**Comment by frostming** [comment]
Hi, I've changed to the HTTPS in Github pages, can anyone check if it is back to normal?

**Comment by icy-comet** [comment]
> Airtel is used as a peering partner by Cloudflare, so even if your ISP is not Airtel, you could be affected.

@mkniewallner I wasn't aware.

> Hi, I've changed to the HTTPS in Github pages, can anyone check if it is back to normal?

@frostming  The site is indeed accessible now without any _blocking_ notices. I am closing the issue.
