### ISSUE TITLE
Support configuring Python interpreter paths for different Python versions in `.pdm.toml`

### ISSUE THREAD

**Issue by laike9m** [pdm-project/pdm#846]
## Is your feature request related to a problem? Please describe.

`pdm use` requires users to manually select the interpreter path. When users need to switch between different Python versions often, this operation quickly becomes tedious.

## Describe the solution you'd like

IMHO, it makes sense to let users configure the interpreter path for different versions of Python. Reasons are
- Saving human effort
- The interpreter paths seldom change, so prompting the selection every time is not so necessary. We can prompt only if the path is not configured.
- `.pdm.toml` already supports setting `python.path`, but only to the current interpreter being used. This proposal is about enhancing the existing feature to make it more useful.

**Comment by frostming** [comment]
I've received another similar FR about this, but it proposed a different solution: Add a configuration item specifying the location to find Python interpreters, say you configure it as the pyenv home so that only pyenv pythons are listed. Because pyenv usually has only one Python for a given version, it should solve your problem?

**Comment by pawamoy** [comment]
Maybe pyenv is not the right example though, because you can already configure it to expose only one version of each minor version (`pyenv global 3.6.8 3.7.8 3.8.8 3.9.6 3.10.0`), so pointing PDM to its shims seems redundant.

**Comment by laike9m** [comment]
> I've received another similar FR about this privately, but it proposed a different solution: Add a configuration item specifying the location to find Python interpreters, say you configure it as the pyenv home so that only pyenv pythons are listed. Because pyenv usually has only one Python for a given version, it should solve your problem?

Not exactly. 

First, even if we limited the search scope to pyenv's directory, there are still multiple binaries to choose from
![image](https://user-images.githubusercontent.com/2592205/148506752-a2635435-d4f5-4ddc-be22-a93bcd2ef1bd.png)

Second, the solution we picked should be generic enough to support all ways Python are installed. The format of condiguration doesn't have to be `version -> path_to_binary`, but at least this is one way to make it work no matter how Python is installed (but TBH I can't think of other better ways that can do the  same, maybe you can).

**Comment by frostming** [comment]
Configuring the `version -> path_to_binary` is a big effort which I wouldn't like to do. What I can suggest is to cache the last choice in `pdm use <python>` with the key `<python>`.

**Comment by laike9m** [comment]
Honestly, I don't think only memorizing `pdm use` is very useful, at least it doesn't solve the pain points I have.

> Configuring the version -> path_to_binary is a big effort which I wouldn't like to do
I bet there are some reasons behind this. Mind explain?

**Comment by frostming** [comment]
Let me understand, the key point that makes you prefer configuration rather than memorizing is, em, transparency. Is it true?
Because the only difference is the memorizing method doesn't need extra user input but loses some transparency. Or am I missing other concerns on this?

**Comment by laike9m** [comment]
> Configuring the version -> path_to_binary is a big effort which I wouldn't like to do. What I can suggest is to remember the last choice in pdm use <python> with the key <python>. And of course, offer an option to pdm use to ignore the caches.

Sorry for the confusion, seems my previous understanding was wrong. To make sure I understand, in your proposal, pdm can remember the mapping from `version -> path`, but the mapping implicit instead of explicit. And this is the only difference from my proposal. Is that correct? If so, I'm fine with it.
