### ISSUE TITLE
A more convenient `pdm run`

### ISSUE THREAD

**Issue by warsaw** [pdm-project/pdm#856]
## Is your feature request related to a problem? Please describe.

I often find myself wanting to just fire up a Python interactive prompt using pdm's `__pypackages__` in `sys.path`.  I believe the way to do that is with `pdm run python` (at least, that works for me.  But maybe we can be a little more convenient or discoverable.  I admit this is a pretty minor convenience, so I don't mind if you close as Won't Fix.

## Describe the solution you'd like

What if `pdm run` with no command were equivalent to running interactively the Python specified by `pdm use`?  If you wanted to do anything more clever (e.g. `pdm run python -c "whatever"`) you'd have to do that explicitly of course.

**Comment by pawamoy** [comment]
If you enabled PEP 582 in your shell, you can just run `python -m some_package_installed_in_pypackages some args`. Or `python -c "import some_package; etc"`.

**Comment by warsaw** [comment]
Yep.  I just don't generally enable this in my shell.

**Comment by pawamoy** [comment]
Oh, OK :blush: Out of complete curiosity, why is that?

**Comment by warsaw** [comment]
A couple of reasons.  My shell configs are a bit weird, having accumulated a lot of cruft over the decades.  I also like to keep my shell environment tightly controlled.  While I like the idea of PEP 582, I'm still a bit leery as to the security implications of it, especially with `bin` enabled.  For now, I prefer to explicitly opt in when necessary.

**Comment by pawamoy** [comment]
I see, thanks!

**Comment by quique** [comment]
> I often find myself wanting to just fire up a Python interactive prompt using pdm's __pypackages__ in sys.path. 

How about `source .venv/bin/activate`?

**Comment by pawamoy** [comment]
The question was about `__pypackages__`, not venvs :slightly_smiling_face:
