### ISSUE TITLE
PDM on Mac OS 12.1 with Homebrew Python 3.10 "BuildError" on first add numpy

### ISSUE THREAD

**Issue by scandey** [pdm-project/pdm#871]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

- Create new folder, run `pdm init`, selecting existing Homebrew Python 3.10 installation.
- Run `pdm add numpy`
- Get BuildError (full log with -v attached below)

Full trace from running `pdm add numpy -v`
[numpy_pdm.txt](https://github.com/pdm-project/pdm/files/7955857/numpy_pdm.txt)

After it failed, I tried again with the verbose flag to produce the trace above. Both times, PDM tried to install numpy 1.12.1. After that, I tried re-initializing the project and selected the "default" Python 3.9 installation (also from Homebrew) and added numpy, and that time it just worked, pulling numpy 1.22.1. Even weirder: after that worked, I tried re-re-initializing back to Python 3.10, and this time adding numpy just worked, also pulling the correct numpy ~~1.12.1~~ 1.22.1. All packages since then have also just worked. 

## Actual behavior

```
Adding packages to default dependencies: numpy
✔ 🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 1 to add, 0 to update, 0 to remove

  ✖ Install numpy 1.12.1 failed
  Retry failed jobs
  ✖ Install numpy 1.12.1 failed

ERRORS:
add numpy failed:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/Cellar/pdm/1.12.6/libexec/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 190, in install_candidate
    self.manager.install(can)
  File "/usr/local/Cellar/pdm/1.12.6/libexec/lib/python3.10/site-packages/pdm/installers/manager.py", line 38, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/usr/local/Cellar/pdm/1.12.6/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 309, in build
    self.wheel = builder.build(build_dir, metadata_directory=self._metadata_dir)
  File "/usr/local/Cellar/pdm/1.12.6/libexec/lib/python3.10/site-packages/pdm/builders/wheel.py", line 28, in build
    filename = self._hook.build_wheel(out_dir, config_settings, metadata_directory)
  File "/usr/local/Cellar/pdm/1.12.6/libexec/lib/python3.10/site-packages/pep517/wrappers.py", line 208, in build_wheel
    return self._call_hook('build_wheel', {
  File "/usr/local/Cellar/pdm/1.12.6/libexec/lib/python3.10/site-packages/pep517/wrappers.py", line 322, in _call_hook
    self._subprocess_runner(
  File "/usr/local/Cellar/pdm/1.12.6/libexec/lib/python3.10/site-packages/pdm/builders/base.py", line 238, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/usr/local/Cellar/pdm/1.12.6/libexec/lib/python3.10/site-packages/pdm/builders/base.py", line 86, in log_subprocessor
    raise BuildError(
pdm.exceptions.BuildError: Call command ['/usr/local/opt/python@3.10/bin/python3.10', '/usr/local/Cellar/pdm/1.12.6/libexec/lib/python3.10/site-packages/pep517/in_process/_in_process.py', 'build_wheel', '/var/folders/sf/pcjlsp7573ldj0z34qn2bw7r0000gn/T/tmp6sr7vs8a'] return non-zero status(1).
```

## Expected behavior

Numpy should be found and installed.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

```
PDM version:        1.12.6
Python Interpreter: /usr/local/opt/python@3.10/bin/python3.10 (3.10)
Project Root:       /Users/scottcandey/Documents/ESCAPADE/hvps-controller
Project Packages:   /Users/scottcandey/Documents/ESCAPADE/hvps-controller/__pypackages__/3.10
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.1",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "21.2.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64",
  "python_full_version": "3.10.1",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}

**Comment by frostming** [comment]
> also pulling the correct numpy 1.12.1

It confuses me, `numpy 1.22.1` should be the correct one.

Did you change the `requires-python` setting between the two attempts?

**Comment by scandey** [comment]
Oops! Typo, that third numpy version should have also been 1.22.1. I got 1.12.1, then 1.22.1, and 1.22.1 again.

I didn't intentionally change the requires-python setting between attempts, but it is possible! Tomorrow I'll try a new project folder and see if I can recreate this while saving out each step.

**Comment by frostming** [comment]
BTW you can change the python version by `pdm use`, no need to initialize again.

**Comment by scandey** [comment]
Aha, I can consistently cause the error by using either Python 3.9 or Python 3.10 and then setting `python-requires` to `*`. If I use the default of `>=3.9`, there is no issue. 

This makes some sense, I assume numpy 1.12.1 was the latest that supports Python 2 or something. However, I'd expect PDM to provide a "gentle" failure with an explanation that there is no way to solve for all versions of python, rather than an inscrutable "build error". I've attached a zipped copy of the project I was just testing on, though I don't know how much useful it will be.

[test-pdm.zip](https://github.com/pdm-project/pdm/files/7962951/test-pdm.zip)

**Comment by frostming** [comment]
>However, I'd expect PDM to provide a "gentle" failure with an explanation that there is no way to solve for all versions of python

It is not true, it is SOLVED, but can't be BUILT. If you are on a linux machine and have all build-essentials installed, the build would succeed. So PDM can't throw an error like that.

I think this issue has been solved. I would like to close it now.
