### ISSUE TITLE
Python interpreter of pdm doesn't have the python built-in module tkinter

### ISSUE THREAD

**Issue by dev590t** [pdm-project/pdm#873]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

I'm trying to use matplotlib, and matplotlib depends of module `tkinter`.

It seem tkinter is a built-in module of Python interpreter
https://docs.python.org/3.8/library/tk.html

However, It seems Python of pdm don't have this module.

## Steps to reproduce and Actual behavior

```
(base) export PYTHONPATH=/home/dev_1/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/pep582
(base) pdm run -v python -c "import _tkinter;print(_tkinter)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named '_tkinter'
```
## Expected result
should success import like my system Python interpreter
```
(base) echo $PYTHONPATH 
/home/dev_1/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/pep582:/home/dev_1/.local/lib/python3.8/site-packages:/home/dev_1/.guix-profile/lib/python3.8/site-packages
(base) python -c "import _tkinter;print(_tkinter)"
<module '_tkinter' from '/home/dev_1/.guix-profile/lib/python3.8/site-packages/_tkinter.cpython-38-x86_64-linux-gnu.so'>
```
## Environment Information

```bash
(base) pdm info && pdm info --env
PDM version:        1.12.6
Python Interpreter: /home/dev_1/.local/share/pdm/venv/bin/python (3.8)
Project Root:       /tmp/test
Project Packages:   /tmp/test/__pypackages__/3.8
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.2",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.9.3-gnu",
  "platform_system": "Linux",
  "platform_version": "#1 SMP 1",
  "python_full_version": "3.8.2",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform":

```

**Comment by dev590t** [comment]
After install few python tk lib, and retry, that still fails
```
$ history
  587  pdm add tk-tools
  589  pdm add tkinter-page
  591  pdm add tk
  593  pdm add pytk
$ pdm run -v python -c "import _tkinter;print(_tkinter)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named '_tkinter'
```

**Comment by pawamoy** [comment]
I don't think this is related to PDM. Such modules need some system libraries to be present when compiling Python. You should probably search on the internet what libraries are needed, and reinstall/recompile your Python interpreter. Are you using pyenv?

**Comment by dev590t** [comment]
@pawamoy 
The [documentation](https://docs.python.org/3.8/library/tk.html) says tkinter is a built-in module of Python:
> Tk/Tcl has long been an integral part of Python.

> reinstall/recompile your Python interpreter

I use the python interpreter of pdm : `/home/dev_1/.local/share/pdm/venv/bin/python`. So I guess tkinter should also be built-in.

**Comment by dev590t** [comment]
A workaround I have use to bypass the issue:
```
(base) ls /gnu/store/5s4z41ajz1i6zyvfhp9dl2vvv7rn6i2a-python-3.8.2-tk/lib/python3.8/site-packages/
_tkinter.cpython-38-x86_64-linux-gnu.so
(base) PYTHONPATH=$PYTHONPATH:/gnu/store/5s4z41ajz1i6zyvfhp9dl2vvv7rn6i2a-python-3.8.2-tk/lib/python3.8/site-packages/
(base) pdm run -v python -c "import _tkinter;print(_tkinter)"
<module '_tkinter' from '/gnu/store/5s4z41ajz1i6zyvfhp9dl2vvv7rn6i2a-python-3.8.2-tk/lib/python3.8/site-packages/_tkinter.cpython-38-x86_64-linux-gnu.so'>
```

**Comment by pawamoy** [comment]
The "interpreter of PDM" is just the interpreter you used to install PDM. It seems that this particular interpreter was not compiled with tkinter support. Since `/gnu/store/5s4z41ajz1i6zyvfhp9dl2vvv7rn6i2a-python-3.8.2-tk/bin/python` seems to have tkinter support, you could try to reinstall PDM using this interpreter instead (but not sure where it comes from or if this is a good idea).

**Comment by dev590t** [comment]
@pawamoy Thank you, if the problem doesn't from PDM, I close the issue
