### ISSUE TITLE
Resolver prefers solve which introduces `alpha` release over stable.

### ISSUE THREAD

**Issue by agoose77** [pdm-project/pdm#879]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

`pdm add ipython jupyterlab~=3.2`

## Actual behavior

PDM seems to find `ipython==8.0.1` and then finds the alpha release of JupyterLab that supports IPython 8. Currently, no stable releases JupyterLab 3.x support IPython 8.  

## Expected behavior

The resolver uses an IPython<8 such that JupyterLab >=3.2,<4.0 can be installed.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.12.7
Python Interpreter: /tmp/tmp.f9Hqu8V5t4/bin/python (3.9)
Project Root:       /tmp/tmp.f9Hqu8V5t4
Project Packages:   None
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.4",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.11.0-17-generic",
  "platform_system": "Linux",
  "platform_version": "#18-Ubuntu SMP Thu May 6 20:10:11 UTC 2021",
  "python_full_version": "3.9.4",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
It will definitely make the resolving more complicated if we (softly) reject prereleases unless no solution is found after all versions are looked at. 

On the other hand, it is easier to solve on the user-side: try excluding the prereleases explicitly by specifying `jupyterlab>=3.2,<4.0.0a0`
