### ISSUE TITLE
Issue when building Calibre -- "-c: Unable to find file 'QtWidgets/QtWidgetsmod.sip'"

### ISSUE THREAD

**Issue by DUOLabs333** [pdm-project/pdm#880]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
Start a new project, install pyqt5, sip, and pyqt-builder. Clone the calibre source code and run `pdm run python setup.py build`
## Actual behavior
Failure with `-c: Unable to find file 'QtWidgets/QtWidgetsmod.sip'`
## Expected behavior
Succeeding

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.12.6
Python Interpreter: /usr/bin/python (3.9)
Project Root:       /home/system/Downloads/calibre
Project Packages:   /home/system/Downloads/calibre/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.9",
  "os_name": "posix",
  "platform_machine": "aarch64",
  "platform_release": "5.15.5-1-ARCH",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Wed Dec 1 01:26:36 UTC 2021",
  "python_full_version": "3.9.9",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}

```

**Comment by DUOLabs333** [comment]
The file does exist -- it's probably a PATH issue.

**Comment by pawamoy** [comment]
What's the exact relative path to this file?

**Comment by pawamoy** [comment]
(@frostming same suggestion as in #881, to me it does not look like a bug in PDM, so I could move this to Discussions/Q&A instead)

**Comment by DUOLabs333** [comment]
@pawamoy `../__pypackages__/3.9/lib/PyQt5/bindings/QtWidgets/QtWidgetsmod.sip`

**Comment by pawamoy** [comment]
Could you post a full traceback if you have one?

**Comment by DUOLabs333** [comment]
```

*
* Running build
*

Building 25 extensions
SIPing 3 files...
/usr/bin/python -c from sipbuild.tools.build import main; main(); --verbose --no-make --qmake /usr/bin/qmake-qt5
Querying qmake about your Qt installation...
/usr/bin/qmake-qt5 -query
These bindings will be built: pictureflow.
Generating the pictureflow bindings...
-c: Unable to find file "QtWidgets/QtWidgetsmod.sip"
```

**Comment by pawamoy** [comment]
Thanks. That's still not enough though :thinking: 
Would you happen to know which Python module is trying to access this file, or which tool?

**Comment by DUOLabs333** [comment]
Probably `sipbuild`

**Comment by pawamoy** [comment]
Well, I can't find the source code of `sip` nor `pyat-builder`, but I suspect they search this file in a way that is not compatible with PEP 582. Do you know if they have a GitHub repository or something?

**Comment by DUOLabs333** [comment]
No, but they just put out a new source code package [here](https://pypi.org/project/sip/#files).

**Comment by pawamoy** [comment]
You could try to somehow pass `-DSIP_INCLUDE_DIR` to the cmake command. https://github.com/Ultimaker/libArcus/issues/79

I have to ask though: why doing that with PDM? Does it not work with a simple venv?

**Comment by DUOLabs333** [comment]
I just do everything with PDM now :)

**Comment by pawamoy** [comment]
Great answer :smile:

**Comment by DUOLabs333** [comment]
I'm not sure how to pass it in though.

**Comment by pawamoy** [comment]
Try exporting the SIP_INCLUDE_DIR env var.

**Comment by DUOLabs333** [comment]
It didn't work.

**Comment by frostming** [comment]
> `/usr/bin/qmake-qt5 -query`

That is the problem: you are using a system-level builder which doesn't support PEP 582 paths.
PDM only supports PEP 517 builds which means all build dependencies, if there are any, must be installed in the same environment as where the build is run. Pre-installed build tools are not PEP 517 style. Or you shouldn't use PDM to build.

**Comment by DUOLabs333** [comment]
Shame -- guess I'll make a virtual env.

**Comment by frostming** [comment]
Never mind, it is rather a matter of design choice. And PEP 517 just isn't your friend for this project.
