### ISSUE TITLE
ModuleNotFoundError tensorflow

### ISSUE THREAD

**Issue by extremety1989** [pdm-project/pdm#881]
windows 10
installed with Invoke-WebRequest
python version 3.9.10
pdm init -> pdm add tensorflow  

import tensorflow as tf
i got error that says       ModuleNotFoundError: No module named 'tensorflow'

**Comment by pawamoy** [comment]
How do you run your program?

**Comment by extremety1989** [comment]
@pawamoy py .\main.py

**Comment by pawamoy** [comment]
@extremety1989 did you [enable PEP582](https://pdm.fming.dev/#enable-pep-582-globally)?
Does it work if you run `pdm run python main.py` instead?

**Comment by extremety1989** [comment]
@pawamoy yes i did, thanks now it runs !  with  only python main.py
