### ISSUE TITLE
Allow specifying other config then global/home and local/project

### ISSUE THREAD

**Issue by canatella** [pdm-project/pdm#883]
## Is your feature request related to a problem? Please describe.

We use PDM for all our packages. We have some common config like `pypi.url` that we'd like to share between project but avoid defining at the global level to not interfere with the user configuration. We are currently using environment variable but not all config items are available as such.

## Describe the solution you'd like

Either an environment variable to pass an alternative path to the global config, or having PDM lookup each project parent directory for a `.pdm.toml` for example.

**Comment by frostming** [comment]
While this idea is generally good, it creates extra levels for configuration: global -> parent -> parent -> ... -> cwd and each level can override the configuration of last level. Or do you want override at all?

A better alternative may be like `gitconfig`. it has an `includeIf` directive in the home config, This is more explicit.

```ini
[includeIf "gitdir:/my/project/"]
        path = /my/project/.gitconfig
```

**Comment by canatella** [comment]
Would work for me, but might be simpler to just have a `PDM_HOME` env variable.  It would indeed be less flexible though. I also tried hooking today into PDM via a plugin to change this, I have something working but its ugly; in the plugin `__init__.py`: 
```python
def main(core: Core) -> None:
    Project.GLOBAL_PROJECT = Workspace.for_path().root / "config.toml"
```
Providing a clean API to do that could also be a solution.

**Comment by canatella** [comment]
And thinking about it, the IncludeIf solution is annoying because then my environment is not independent from the system, a new user configuring its environment would have to edit its system configuration to specify the path of the development environment. With an environment variable or the parent solution, it is all self contained which is nice.

Btw, I did not reply on the parent solution, but I think its the best one, the user has still some control by modifying the global config. Its also the way some formatting tools and linters works these days.

**Comment by canatella** [comment]
Thanks!
