### ISSUE TITLE
Update pyproject.toml dependency constrains

### ISSUE THREAD

**Issue by lyz-code** [pdm-project/pdm#884]
## Is your feature request related to a problem? Please describe.
For most open sourced projects maintained by few people, the only maintained version is the latest one, so you can only be sure that the program works with the version of the libraries that are in the `pdm.lock`.

`pdm update` doesn't update the constrains in `pyproject.toml`, so you can end up with a user installing dependencies on a lower version than the one specified in `pdm.lock` thus seeing a different behaviour than the expected. 

## Describe the solution you'd like
`pdm` could have a configuration or  `update` a flag that if it's activated, whenever the dependencies are updated, the constrains in the `pyproject.toml` are updated too.

**Comment by frostming** [comment]
How do you want the constraints to be updated?

The dependencies in `pyproject.toml` are for a library, where it is not likely to have pinned versions, while the dependencies in `pdm.lock` are for reproducible installations, where the versions are pinned. So if you ship your project as an application. You should tell the users to install from `pdm.lock`, not `pyproject.toml`. So I don't see why it is a problem.

Anyway, if you want to update the constraints in `pyproject.toml`, add `--unconstrained` flag to `pdm update`.

**Comment by lyz-code** [comment]
Maybe I've understood something wrong, in `pyproject.toml` I don't pin versions but set constrains like `>=0.1.0`, for example when using `pdm add`. I guess that when a user uses `pdm add {{ my_package }}` it will use the content of `pdm.lock`, but if the user uses `pip install my_package` will it also install the versions of the dependencies specified in the lock file? or will pip try to use it's resolver with the constrains set in the `pyproject.toml`?

**Comment by frostming** [comment]
You are right, `pdm.lock` can only be read by `pdm` and `pip` reads `pyproject.toml`. The problem is you shouldn't use `pip install package` for deterministic installation since it doesn't guarantee that. You should either use `pdm install` or generate a `requirements.txt` with `pdm export` and use `pip install -r` with the file.

**Comment by lyz-code** [comment]
I don't think that asking all users to use pdm install or clonning and then doing a pip install -r is realistic, that was why I thought that keeping the pyproject.toml constrains as close as possible to the pdm.lock pins was desired to avoid unexpected bugs.

Using `--unconstrained` did change the constrains but with the side effect that it doesn't respect the pins of the downstream libraries, which may be inconvenient in some cases. I see though that understanding the constrains of pyproject.toml and changing them on each update may  not be easy, for example when some version is excluded a range is allowed and another isn't, so I'd  understand if you felt this is a corner case and don't want to support it. I'm fine with closing the issue if it's the case

**Comment by pawamoy** [comment]
I think there's a bit of misunderstanding here.

> I guess that when a user uses pdm add {{ my_package }} it will use the content of pdm.lock

It does not. Running `pdm add` or `pip install` goes through the same standardized process without involving any lock file at all. They both get dependencies from what is written in the wheel records. You don't have to ship, or even version lock files for libraries projects.

**Comment by lyz-code** [comment]
It's funny, yesterday I browsed through your repos @pawamoy to see how did you manage your dependencies and it surprised me that you didn't pack the `pdm.lock`, now I know why :)

**Comment by frostming** [comment]
> I don't think that asking all users to use pdm install or clonning and then doing a pip install -r is realistic

Neither is `pip install <package_name>`. IIUC you are shipping an **application** which should have all dependencies **pinned** to the private index right? Though that is not recommended PDM can do it by setting `pdm config strategy.save exact`.

>Using `--unconstrained` did change the constrains but with the side effect that it doesn't respect the pins of the downstream libraries, which may be inconvenient in some cases.

It does respect as long as the update strategy is `reuse`and update packages like:
```
pdm update <specific_package_name> --unconstrained
# or to update all top dependencies
pdm update --unconstrained --top
```

**Comment by lyz-code** [comment]
>  IIUC you are shipping an **application** which should have all dependencies **pinned** to the private index right? Though that is not recommended PDM can do it by setting `pdm config strategy.save exact`.

Not exactly, I want all dependencies pinned to the highest version available that is compatible all between themselves but with the `>=` constrain, in case the update process fails, I don't do upper version capping.

> It does respect as long as the update strategy is `reuse`and update packages like:
> 
> ```
> pdm update <specific_package_name> --unconstrained
> # or to update all top dependencies
> pdm update --unconstrained --top
> ```

Looks good, will introduce this into my workflow, if I encounter any error I'll report back.

Thanks for the help :)
