### ISSUE TITLE
Add option for `~/.local` directory

### ISSUE THREAD

**Issue by DUOLabs333** [pdm-project/pdm#885]
## Is your feature request related to a problem? Please describe.
`pdm` has a `-g` option, to edit the "global" Python environment, eg. the one in `/usr`. However, there's no option for the local python environment, the one in `~/.local`

## Describe the solution you'd like
Maybe an option like `--local` or `--user` to act on that directory?

**Comment by frostming** [comment]
> How does `-g` even work? `~/.pdm/global-project` doesn't have anything that would point to `/usr`.

`~/.pdm/global-project/.pdm.toml` also stores the Python path, and the packages will be installed into the `site-packages` of the selected Python interpreter

**Comment by DUOLabs333** [comment]
Is `global-project` special? Like can I make my own folder that will point to another `site-packages`?

**Comment by frostming** [comment]
No you can point to another project dir by `-gp <project_path>`, where `global-project` is a default location when `-p` isn't given.

**Comment by DUOLabs333** [comment]
How would I remove/add packages? Since they're not in the `pyproject.toml` it fails with `does not exist in default dependencies.`

**Comment by frostming** [comment]
> How would I remove/add packages? Since they're not in the `pyproject.toml` it fails with `does not exist in default dependencies.`

If you agree the env should be kept in sync with `pyproject.toml`, then `pdm sync -g --clean` will remove all packages not needed.

**Comment by DUOLabs333** [comment]
Doing `pdm sync -g` gives me `Lock file does not exist, nothing to install`.

**Comment by frostming** [comment]
> So you are saying that `pdm sync` will just add all the packages in `site-packages` to `global-project/pyproject.toml`?

Sync is from `pyproject.toml` to `site-packages` and not reverse.

> Doing pdm sync -g gives me Lock file does not exist, nothing to install.

Did you generate a lock file in the first place? Use `pdm install -g` to generate.

You seems to be taking `-g` as some kind of black magic, but it is just like a normal project, except that the packages are installed into global `site-packages`, instead of project level `__pypackages__`. All packages must be listed in `pdm.lock`, which is generated from `pyproject.toml`, and adding and removing must be via PDM. So that the global `site-packages` are fully tracked and can be easily rebuilt from scratch, with a pair of `pyproject.toml` and `pdm.lock` files.

**Comment by DUOLabs333** [comment]
Ok, so you are saying the point of `--global` is to add new packages to `site-packages`, not to manage old packages already there.

**Comment by frostming** [comment]
Yeah, you need to add them to `pyproject.toml` yourself if you want to manage the old packages

**Comment by DUOLabs333** [comment]
Is there any way to import them in or do I really have to add them one by one? Maybe offer a `pyproject.toml` format?

**Comment by frostming** [comment]
You only need to add top-level dependencies, run `pdm list -g --graph` to show the dependency tree, and add root nodes to `pyproject.toml`'s `dependencies` array, each item is a [PEP 508](https://peps.python.org/pep-0508/) requirement string. Take the example of `pdm/pyproject.toml`.

Answering such question unpaid kills a lot of time, you may consider [Sponsor this project](https://github.com/sponsors/pdm-project), or just READ THE MANUAL please.
