### ISSUE TITLE
New html parser

### ISSUE THREAD

**Issue by q0w** [pdm-project/pdm#888]
## Is your feature request related to a problem? Please describe.
As I [mentioned earlier](https://github.com/pdm-project/pdm/pull/887), html5lib will be removed from pip (it already [does not switch to html5lib by default](https://github.com/pypa/pip/pull/10869)). So maybe rewrite to `html.parser` or add 3th-party lib parser, like html5lib. 
Or use a faster parser, like [selectolax](https://github.com/rushter/selectolax) to improve performance.
## Describe the solution you'd like

I think, html.parser is slow, as html5lib too. So adding selectolax can be a solution.

**Comment by frostming** [comment]
IMO html parser shouldn't be the performance bottleneck unless you can provide some proof.

**Comment by frostming** [comment]
At present, PDM is reusing the ability of `pip` for index parsing so there isn't room for customizing the parser. But we are in the process of [dropping `pip`](https://github.com/pdm-project/pdm/issues/743) and third-party HTML parsers may be worth considering.

**Comment by q0w** [comment]
Do you think dropping pip in pdm will be earlier than pip will fully remove html5lib from vendors?

**Comment by abersheeran** [comment]
https://peps.python.org/pep-0691/

Maybe don’t need new html parser

**Comment by q0w** [comment]
But existing api would not be deprecated soon

**Comment by frostming** [comment]
On PDM 2.0 we switched from pip to [unearth](https://pypi.org/project/unearth), which uses `html.parser`.

**Comment by frostming** [comment]
Please test it on [`2.0.0a1`](https://github.com/pdm-project/pdm/releases/tag/2.0.0a1)
