### ISSUE TITLE
How do I uninstall?

### ISSUE THREAD

**Issue by robml** [pdm-project/pdm#890]
## Is your feature request related to a problem? Please describe.

I can't find how to uninstall PDM (for linux)

## Describe the solution you'd like

Preferably a guide how to uninstall PDM on Linux.

Truth be told, this is all still very new and overwhelming to me. The fact that I can't access my local apps without running "pdm run" feels strange, I think I need to understand package managers better first. Until then, how do I bloody uninstall?

**Comment by thiagola92** [comment]
There is a way to uninstall?

**Comment by frostming** [comment]
> There is a way to uninstall?
> 
> Removing the file from `$HOME/.local/bin` is enough?

```bash
curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 - --remove
```

**Comment by thiagola92** [comment]
Thank you!
