### ISSUE TITLE
Pdm based package doesn't include stubs

### ISSUE THREAD

**Issue by JaviFuentes94** [pdm-project/pdm#916]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

After typing and publishing a package using pdm, the types are gone. 
So both 
```
pip install package
pip install -e package
```
Leads to ` Cannot find implementation or library stub for module named package` when running mypy from other packages. 

## Expected behavior
Pdm should package the stubs together with the module. This is achieved as follows in the traditional `setup.py` way:
```
package_data={
        'package': ['py.typed'],
    },
    data_files=[],
    include_package_data=True,
```
As far as I understand this is not possible with pdm. 

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.10.2
Python Interpreter: /home/harry/.pyenv/versions/3.7.5/bin/python3 (3.7)
Project Root:       /home/harry/uizard/code/pip-package-uizard-nolybab
Project Packages:   /home/harry/uizard/code/pip-package-uizard-nolybab/__pypackages__/3.7

PDM 1.10.2 is installed, while 1.12.8 is available.
Please run $ /home/harry/.pyenv/versions/3.7.5/bin/python3.7 -m pip install -U pdm to upgrade.
Run $ pdm config check_update false to disable the check.
{
  "implementation_name": "cpython",
  "implementation_version": "3.7.5",
  "os_name": "posix",
  "platform_machine": "aarch64",
  "platform_release": "5.10.47-linuxkit",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT Sat Jul 3 21:50:16 UTC 2021",
  "python_full_version": "3.7.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.7",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
There may be some problem with the packaging settings.

Including data files work well, see this project: https://pypi.org/project/atoml#files

**Comment by JaviFuentes94** [comment]
I am not sure what happened but when I ran the project again the problem seems to be solved 🤷 In any case, thanks for the help, appreciated!
