### ISSUE TITLE
[doc] Add some description on add wheel files

### ISSUE THREAD

**Issue by jerrylususu** [pdm-project/pdm#927]
## Is your feature request related to a problem? Please describe.

I am just trying out PDM, and found it unclear how to install wheel files. 

Initially I assumed that it uses the same idea as `pip`, so I tried `pdm add [path_to_whl]`, which didn't work. Later after digging in the issues list and the document, I realized that URLs are required for installing wheel files, even for local files. Therefore I tried again with `pdm add file:///[absolute_path_to_whl]` as well as `pdm add file:///${PROJECT_ROOT}/[relative_path_to_whl]`, and both of them worked. 

## Describe the solution you'd like

Installing prebuilt wheel files is probably a common usage for Python development, so there should probably exist a section in PDM's documentation on how to add wheel files. Currently there is no such instructions, and `${PROJECT_ROOT}` is only mentioned until the Environment variables expansion section.

Perhaps something like the following may help:

---

### Add prebuilt wheels
Use `pdm add [url_to_whl]` to add wheel files. For local wheel files, to keep the project portable and self-contained, it is recommended to put them somewhere in the project folder, then use `pdm add file:///${PROJECT_ROOT}/[relative_path_to_whl]` to add them. For more information on expanding environment variables, see [Environment variables expansion](https://pdm.fming.dev/usage/dependency/#environment-variables-expansion).

**Comment by frostming** [comment]
>  so I tried pdm add [path_to_whl], which didn't work

It does work, only that relative path must start with `.`.

**Comment by frostming** [comment]
https://pdm.fming.dev/usage/dependency/#add-local-dependencies covers that usage. Closing it now.
