### ISSUE TITLE
Add feature to ignore conflicts

### ISSUE THREAD

**Issue by DUOLabs333** [pdm-project/pdm#929]
## Is your feature request related to a problem? Please describe.
I have a package `Mathics` that I'm pulling from git then building. However, it is of version `4.1.0.dev0`. However, `mathicsscript` 4.0.0 wants `Mathics` between 4.0.0 and 4.1.0 exclusive. So, I want to force pdm to install the newer version and keep `mathicsscript` 4.0.0 (right now, it downgrades it to 1.1.2, where the dependencies are `"Mathics3>=1.1.1"`

## Describe the solution you'd like
Maybe something like `pdm add -f <package>`?

**Comment by frostming** [comment]
Override the resolution result:

https://pdm.fming.dev/usage/dependency/#solve-the-locking-failure
