### ISSUE TITLE
Can't resolve in GitHub CI

### ISSUE THREAD

**Issue by pawamoy** [pdm-project/pdm#934]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

Not really sure what's happening here, any idea @frostming?

## Steps to reproduce

Run `pdm lock` in GitHub CI.

## Actual behavior

https://github.com/mkdocstrings/griffe/runs/5308743695?check_suite_focus=true
PDM is able to resolve locally (v12 and v13, latest).

## Expected behavior

PDM should be able to resolve dependencies?

## Environment Information

See GitHub CI, and locally:

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.13.2
Python Interpreter: /home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.10.0/bin/python3.10 (3.10)
Project Root:       /media/data/dev/griffe
Project Packages:   /media/data/dev/griffe/__pypackages__/3.10
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.0",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.16.10-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT Wed, 16 Feb 2022 19:35:18 +0000",
  "python_full_version": "3.10.0",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
It seems to be fixed on the main branch: https://github.com/frostming/griffe/runs/5312944609?check_suite_focus=true

**Comment by frostming** [comment]
Please check if the new release solves the problem

**Comment by pawamoy** [comment]
Yup, seems to work fine, thanks :slightly_smiling_face:
