### ISSUE TITLE
Not all help output is formatted based on terminal width

### ISSUE THREAD

**Issue by julie777** [pdm-project/pdm#938]
- [x ] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
run git-bash on Windows 10
run `pdm -h`

## Actual behavior
Some output doesn't get formatted based on number of columns.
(Pasting output didn't keep the formatting so I am using a screen clipping.)
![image](https://user-images.githubusercontent.com/5090005/155860081-544088b8-1a95-4207-820c-4387ef2ada46.png)

You can see that commands just keep going past the term width and don't get formatted based on COLUMNS. However looking at `export` and `add` you can see proper wrapping.

## Expected behavior

I would expect all formatted output to use terminal COLUMNS to format.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
 pdm info
[ProjectError]: The pyproject.toml has not been initialized yet. Y
ou can do this by running 'pdm init'.
```
I had to create a directory and run `pdm init` to run the command you specified.
```bash
$ pdm info && pdm info --env
PDM version:        1.13.3
Python Interpreter: C:\Users\julie\AppData\Local\Programs\Python\P
ython310\python.EXE (3.10)
Project Root:       C:/tmp/sssssss
Project Packages:   C:\tmp\sssssss\__pypackages__\3.10
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.2",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19043",
  "python_full_version": "3.10.2",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "win32"
}

```

**Comment by frostming** [comment]
It's an issue lying in `argparse` rather than in PDM.

**Comment by julie777** [comment]
I wasn't sure about that given that pdm uses a custom formatter for argparse.
I didn't try to debug it, but just reported what I saw.

**Comment by frostming** [comment]
Yeah, I can confirm that issue still exists using the default formatter
