### ISSUE TITLE
Add editor selection options when using pdm init

### ISSUE THREAD

**Issue by kai648846760** [pdm-project/pdm#947]
When using pdm init, add editor options, and automatically generate the corresponding configuration, such as:

Please select the editor you use [0.vscode 1.pycharm....]

In order to generate the corresponding configuration file in the project directory.

For example: after selecting vscode, automatically generate .vscode/setting.json in the current directory
and write the corresponding configuration
![image](https://user-images.githubusercontent.com/53172671/156327333-9ed9a63b-1fcb-45a3-a000-93c55840a7f2.png)

Thanks for developing such a good project, it is very pleasant to use, and I hope PDM is getting better and better.

**Comment by frostming** [comment]
It seems to be only useful for vscode, what about PyCharm, or vim, emacs? Is it going to be a no-op for these editors? Then I think it isn't worth implementing.

**Comment by kai648846760** [comment]
Thanks for the reply, indeed, is it possible to make a vscode plugin with similar functionality to better adapt to vscode? The previous pdm plugin was really difficult to use.

**Comment by dexterlemmer** [comment]
> It seems to be only useful for vscode, what about PyCharm, or vim, emacs? Is it going to be a no-op for these editors? Then I think it isn't worth implementing. -- @frostming

I'm not a PyCharm user myself, but IIRC I did recently discover a website showing how to setup Pycharm to work with `__pypackages__`. And what isn't possible for emacs ;-) (I'm not an emacs user either. I just happen to see folks doing everything with emacs.)

**Comment by frostming** [comment]
> Thanks for the reply, indeed, is it possible to make a vscode plugin with similar functionality to better adapt to vscode? The previous pdm plugin was really difficult to use.

I made one [pdm-vscode](https://github.com/frostming/pdm-vscode) that can generate `settings.json` for you.

**Comment by dexterlemmer** [comment]
> > Thanks for the reply, indeed, is it possible to make a vscode plugin with similar functionality to better adapt to vscode? The previous pdm plugin was really difficult to use.
> 
> I made one [pdm-vscode](https://github.com/frostming/pdm-vscode) that can generate `settings.json` for you.

Thanks. I assume this is only for PEP582. Since if you use a venv, VSCode (and other IDEs) should automatically detect PDM, right? (VSCode does for me any way.)
