### ISSUE TITLE
Add an option to skip hook scripts

### ISSUE THREAD

**Issue by xanterx** [pdm-project/pdm#948]
## Is your feature request related to a problem? Please describe.

I want start from hooks scripts and pre post scripts are great addition to pdm. Like using `post_install` to setup `pre-commit` (#789). But sometime this could lead to unwanted result during production builds, where `pre-commit` setup is not desirable.

Example: While running `pdm sync --prod --global --no-editable` during docker build. It also runs `post_install` script.

## Describe the solution you'd like

If a flag option exists like `--skip-hook` or something similar. This can used to skip all hooks during production build.

Now, it is also quite possible that during prod build some hook scripts are desirable and some not. So, extending the same option to skip specific hook would work great. Like `--skip-hook "post_install pre_install"`.

**Comment by frostming** [comment]
As a workaround, you can examine an env var like `$skip_hook` at the beginning of your script and set it when necessary:

```
skip_hook=true pdm sync --prod --no-editable
```
