### ISSUE TITLE
PDM stopped working with Pyenv out of the blue

### ISSUE THREAD

**Issue by robml** [pdm-project/pdm#952]
### Discussed in https://github.com/pdm-project/pdm/discussions/951

<div type='discussions-op-text'>

<sup>Originally posted by **robml** March  3, 2022</sup>
After a lot of troubleshooting to properly work with PDM I thought I had a good workflow going. However recently (with no changes except an update to PDM itself) the entire package stopped working. How? Well I suspect it has to do with PyEnv. For context I am developing using WSL2 (Ubuntu on Windows) and it has served me well so far. As you know Ubuntu comes with a default Python of 3.8, however for development and production purposes I use 3.9.10 and 3.10.2, for which Pyenv seemed like a good solution.

So I initialized my projects with either version and that was that. Now however coming back, I can no longer seem to work with any of my former projects, even typing something as simple as `pdm info` brings the following message

`[InvalidPyVersion]: Invalid Python interpreter: /home/robmel/.pyenv/shims/python`

I want to know if anyone else has faced this and how they've dealt with it, I don't want to report as a bug if there isn't one.</div>

Full Traceback Below:

```
Traceback (most recent call last):
  File "/home/robmel/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/robmel/.local/lib/python3.8/site-packages/pdm/core.py", line 233, in main
    return Core().main(args)
  File "/home/robmel/.local/lib/python3.8/site-packages/pdm/core.py", line 168, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/robmel/.local/lib/python3.8/site-packages/pdm/core.py", line 163, in main
    f(options.project, options)
  File "/home/robmel/.local/lib/python3.8/site-packages/pdm/cli/commands/info.py", line 35, in handle
    interpreter = project.python
  File "/home/robmel/.local/lib/python3.8/site-packages/pdm/project/core.py", line 157, in python
    self._python = self.resolve_interpreter()
  File "/home/robmel/.local/lib/python3.8/site-packages/pdm/project/core.py", line 195, in resolve_interpreter
    for py_version in self.find_interpreters():
  File "/home/robmel/.local/lib/python3.8/site-packages/pdm/project/core.py", line 595, in find_interpreters
    yield PythonInfo.from_path(python)
  File "/home/robmel/.local/lib/python3.8/site-packages/pdm/models/python.py", line 27, in from_path
    raise InvalidPyVersion(f"Invalid Python interpreter: {path}")
pdm.exceptions.InvalidPyVersion: Invalid Python interpreter: /home/robmel/.pyenv/shims/python
```

**Comment by frostming** [comment]
Can't reproduce, can you make sure the shim python works rightly?
```
/home/robmel/.pyenv/shims/python -c "import platform; print(platform.python_version())"
```

**Comment by robml** [comment]
> I seem to have the same problem with pyenv installed 3.11-dev.
> 
> `~/.pyenv/shims/python -c "import platform; print(platform.python_version())"`
> 
> > > 3.11.0a6+

I am not entirely sure what it is in your situation, however I suspect it may be because of the Python version itself. My issue previously turned out to be an entire mess in my core files (like '.bashrc') so reinstalling WSL2 solved my problem as I didn't have any critical files and looked after those files much better. Have you checked your `.bashrc` or `.profile` files?

**Comment by frostming** [comment]
> I seem to have the same problem with pyenv installed 3.11-dev.
> 
> `~/.pyenv/shims/python -c "import platform; print(platform.python_version())"`
> 
> > > 3.11.0a6+

Dev versions with modifiers `+` are not supported
