### ISSUE TITLE
"pdm add xgboost" on Windows leads to a "pdm.exceptions.InstallationError"

### ISSUE THREAD

**Issue by alexclarence** [pdm-project/pdm#962]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

 

**Make sure you run commands with `-v` flag before pasting the output.**

 

## Steps to reproduce

 

On a windows machine, trying to install xgboost package with pdm:

```bash

pdm venv create 3.9

pdm use 3.9

pdm add xgboost -v

```

 

*Note: the same error happens without creating a virtual environment as well*

 

## Actual behavior

 

The code above produces an error

> pdm.exceptions.InstallationError: Some package operations are not complete yet

 

The error mentions this:

> vcomp140.dll is not mentioned in RECORD

 

The full output of the command can be seen at the very end below in the **Full error log** section

 

## Expected behavior

 

When you install xgboost with `pdm run pip install xgboost`, it installs without any errors.

It seems like it's creating a directory with ***vcomp140.dll*** file inside it, directly in the environment folder.

E.g. if your environment path is `C:\Users\username\AppData\Local\pdm\pdm\venvs\pdm_xgboost_test-f8q741ma-3.9`, pip installation will create a folder `xgboost` inside of it, with the `.dll` file in it:

```bash

C:\Users\username\AppData\Local\pdm\pdm\venvs\pdm_xgboost_test-f8q741ma-3.9\xgboost\vcomp140.dll

```

The rest of the package files are installed by pip normally into the `Lib\site-packages` directory:

```bash

C:\Users\username\AppData\Local\pdm\pdm\venvs\pdm_xgboost_test-f8q741ma-3.9\Lib\site-packages\xgboost

C:\Users\username\AppData\Local\pdm\pdm\venvs\pdm_xgboost_test-f8q741ma-3.9\Lib\site-packages\xgboost-1.5.2.dist-info

```

 

## Environment Information

 

```bash

# Paste the output of `pdm info && pdm info --env` below:

```

> PDM version:        1.13.3

> Python Interpreter: C:\Users\username\AppData\Local\pdm\pdm\venvs\pdm_xgboost_test-f8q741ma-3.9\Scripts\python.exe (3.9)

> Project Root:       C:/Users/username/PycharmProjects/pdm_xgboost_test

> Project Packages:   None

> {

>   "implementation_name": "cpython",

>   "implementation_version": "3.9.9",

>   "os_name": "nt",

>   "platform_machine": "AMD64",

>   "platform_release": "10",

>   "platform_system": "Windows",

>   "platform_version": "10.0.19042",

>   "python_full_version": "3.9.9",

>   "platform_python_implementation": "CPython",

>   "python_version": "3.9",

>   "sys_platform": "win32"

> }

 

## Full error log

> Adding packages to default dependencies: xgboost

> ======== Start resolving requirements ========

>   xgboost

>   python>=3.9

>   Adding requirement xgboost

> [present-diagnostic] <MissingHTMLDoctypeDeclaration: missing-index-doctype>

>         Found matching candidates:

>           <Candidate xgboost 1.5.2 from <company_pypi>/repository/pypi-all/simple/xgboost/>

>           <Candidate xgboost 1.5.1 from <company_pypi>/repository/pypi-all/simple/xgboost/>

>           <Candidate xgboost 1.5.0 from <company_pypi>/repository/pypi-all/simple/xgboost/>

>           <Candidate xgboost 1.4.2 from <company_pypi>/repository/pypi-all/simple/xgboost/>

>           <Candidate xgboost 1.4.1 from <company_pypi>/repository/pypi-all/simple/xgboost/>

>           <Candidate xgboost 1.4.0 from <company_pypi>/repository/pypi-all/simple/xgboost/>

>           <Candidate xgboost 1.3.3 from <company_pypi>/repository/pypi-all/simple/xgboost/>

>           <Candidate xgboost 1.3.2 from <company_pypi>/repository/pypi-all/simple/xgboost/>

>           <Candidate xgboost 1.3.1 from <company_pypi>/repository/pypi-all/simple/xgboost/>

>           <Candidate xgboost 1.3.0.post0 from <company_pypi>/repository/pypi-all/simple/xgboost/>

>           ... [83 more candidate(s)]

>   Adding requirement python>=3.9

> ======== Starting round 0 ========

> Resolving: new pin python >=3.9

> ======== Ending round 0 ========

> ======== Starting round 1 ========

>   Adding requirement numpy(from xgboost 1.5.2)

> [present-diagnostic] <MissingHTMLDoctypeDeclaration: missing-index-doctype>

>         Found matching candidates:

>           <Candidate numpy 1.22.2 from <company_pypi>/repository/pypi-all/simple/numpy/>

>           <Candidate numpy 1.22.1 from <company_pypi>/repository/pypi-all/simple/numpy/>

>           <Candidate numpy 1.22.0 from <company_pypi>/repository/pypi-all/simple/numpy/>

>           <Candidate numpy 1.21.1 from <company_pypi>/repository/pypi-all/simple/numpy/>

>           <Candidate numpy 1.21.0 from <company_pypi>/repository/pypi-all/simple/numpy/>

>           <Candidate numpy 1.20.3 from <company_pypi>/repository/pypi-all/simple/numpy/>

>           <Candidate numpy 1.20.2 from <company_pypi>/repository/pypi-all/simple/numpy/>

>           <Candidate numpy 1.20.1 from <company_pypi>/repository/pypi-all/simple/numpy/>

>           <Candidate numpy 1.20.0 from <company_pypi>/repository/pypi-all/simple/numpy/>

>           <Candidate numpy 1.19.5 from <company_pypi>/repository/pypi-all/simple/numpy/>

>           ... [1478 more candidate(s)]

>   Adding requirement scipy(from xgboost 1.5.2)

> [present-diagnostic] <MissingHTMLDoctypeDeclaration: missing-index-doctype>

>         Found matching candidates:

>           <Candidate scipy 1.6.1 from <company_pypi>/repository/pypi-all/simple/scipy/>

>           <Candidate scipy 1.6.0 from <company_pypi>/repository/pypi-all/simple/scipy/>

>           <Candidate scipy 1.5.4 from <company_pypi>/repository/pypi-all/simple/scipy/>

>           <Candidate scipy 1.5.3 from <company_pypi>/repository/pypi-all/simple/scipy/>

>           <Candidate scipy 1.5.2 from <company_pypi>/repository/pypi-all/simple/scipy/>

>           <Candidate scipy 1.5.1 from <company_pypi>/repository/pypi-all/simple/scipy/>

>           <Candidate scipy 1.5.0 from <company_pypi>/repository/pypi-all/simple/scipy/>

>           <Candidate scipy 1.4.1 from <company_pypi>/repository/pypi-all/simple/scipy/>

>           <Candidate scipy 1.4.0 from <company_pypi>/repository/pypi-all/simple/scipy/>

>           <Candidate scipy 1.3.3 from <company_pypi>/repository/pypi-all/simple/scipy/>

>           ... [644 more candidate(s)]

> Resolving: new pin xgboost 1.5.2

> ======== Ending round 1 ========

> ======== Starting round 2 ========

> Resolving: new pin numpy 1.22.2

> ======== Ending round 2 ========

> ======== Starting round 3 ========

>   Adding requirement numpy>=1.16.5(from scipy 1.6.1)

> [present-diagnostic] <MissingHTMLDoctypeDeclaration: missing-index-doctype>

>         Found matching candidates:

>           <Candidate numpy 1.22.2 from <company_pypi>/repository/pypi-all/simple/numpy/>

>           <Candidate numpy 1.22.1 from <company_pypi>/repository/pypi-all/simple/numpy/>

>           <Candidate numpy 1.22.0 from <company_pypi>/repository/pypi-all/simple/numpy/>

>           <Candidate numpy 1.21.1 from <company_pypi>/repository/pypi-all/simple/numpy/>

>           <Candidate numpy 1.21.0 from <company_pypi>/repository/pypi-all/simple/numpy/>

>           <Candidate numpy 1.20.3 from <company_pypi>/repository/pypi-all/simple/numpy/>

>           <Candidate numpy 1.20.2 from <company_pypi>/repository/pypi-all/simple/numpy/>

>           <Candidate numpy 1.20.1 from <company_pypi>/repository/pypi-all/simple/numpy/>

>           <Candidate numpy 1.20.0 from <company_pypi>/repository/pypi-all/simple/numpy/>

>           <Candidate numpy 1.19.5 from <company_pypi>/repository/pypi-all/simple/numpy/>

>           ... [668 more candidate(s)]

> Resolving: new pin scipy 1.6.1

> ======== Ending round 3 ========

> ======== Starting round 4 ========

> ======== Resolution Result ========

> Stable pins:

>    python None

>   xgboost 1.5.2

>     numpy 1.22.2

>     scipy 1.6.1

> [present-diagnostic] <MissingHTMLDoctypeDeclaration: missing-index-doctype>

>         Found matching candidates:

>           <Candidate xgboost 1.5.2 from <company_pypi>/repository/pypi-all/simple/xgboost/>

> [present-diagnostic] <MissingHTMLDoctypeDeclaration: missing-index-doctype>

>         Found matching candidates:

>           <Candidate numpy 1.22.2 from <company_pypi>/repository/pypi-all/simple/numpy/>

> [present-diagnostic] <MissingHTMLDoctypeDeclaration: missing-index-doctype>

>         Found matching candidates:

>           <Candidate scipy 1.6.1 from <company_pypi>/repository/pypi-all/simple/scipy/>

> 🔒 Lock successful

> Changes are written to pdm.lock.

> Changes are written to pyproject.toml.

> Synchronizing working set with lock file: 3 to add, 0 to update, 0 to remove

>

> [present-diagnostic] <MissingHTMLDoctypeDeclaration: missing-index-doctype>

> [present-diagnostic] <MissingHTMLDoctypeDeclaration: missing-index-doctype>

> [present-diagnostic] <MissingHTMLDoctypeDeclaration: missing-index-doctype>

> Install xgboost 1.5.2 failed

> Error occurs:

> Traceback (most recent call last):

>   File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 58, in run

>     result = self.fn(*self.args, **self.kwargs)

>   File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\pdm\installers\synchronizers.py", line 185, in install_candidate

>     self.manager.install(can)

>   File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\pdm\installers\manager.py", line 39, in install

>     installer(prepared.build(), self.environment, prepared.direct_url())

>   File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\pdm\installers\installers.py", line 176, in install_wheel

>     _install_wheel(

>   File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\pdm\installers\installers.py", line 280, in _install_wheel

>     for record_elements, stream in source.get_contents():

>   File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\site-packages\installer\sources.py", line 170, in get_contents

>     assert record is not None, "In {}, {} is not mentioned in RECORD".format(

> AssertionError: In C:\Users\username\AppData\Local\Temp\pip-unpack-1_rv_b2f\xgboost-1.5.2-py3-none-win_amd64.whl, xgboost-1.5.2+742c19f3ecf2135b4e008a4f4a10b59add8b1045.data/data/xgboost/vcomp140.dll is not mentioned in RECORD

> Install numpy 1.22.2 successful

> Install scipy 1.6.1 successful

>   Retry failed jobs

> Install xgboost 1.5.2 failed

> Error occurs:

> Traceback (most recent call last):

>   File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 58, in run

>     result = self.fn(*self.args, **self.kwargs)

>   File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\pdm\installers\synchronizers.py", line 185, in install_candidate

>     self.manager.install(can)

>   File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\pdm\installers\manager.py", line 39, in install

>     installer(prepared.build(), self.environment, prepared.direct_url())

>   File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\pdm\installers\installers.py", line 176, in install_wheel

>     _install_wheel(

>   File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\pdm\installers\installers.py", line 280, in _install_wheel

>     for record_elements, stream in source.get_contents():

>   File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\site-packages\installer\sources.py", line 170, in get_contents

>     assert record is not None, "In {}, {} is not mentioned in RECORD".format(

> AssertionError: In C:\Users\username\AppData\Local\Temp\pip-unpack-1_rv_b2f\xgboost-1.5.2-py3-none-win_amd64.whl, xgboost-1.5.2+742c19f3ecf2135b4e008a4f4a10b59add8b1045.data/data/xgboost/vcomp140.dll is not mentioned in RECORD

>

> ERRORS:

> add xgboost failed:

> Traceback (most recent call last):

>   File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 58, in run

>     result = self.fn(*self.args, **self.kwargs)

>   File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\pdm\installers\synchronizers.py", line 185, in install_candidate

>     self.manager.install(can)

>   File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\pdm\installers\manager.py", line 39, in install

>     installer(prepared.build(), self.environment, prepared.direct_url())

>   File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\pdm\installers\installers.py", line 176, in install_wheel

>     _install_wheel(

>   File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\pdm\installers\installers.py", line 280, in _install_wheel

>     for record_elements, stream in source.get_contents():

>   File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\site-packages\installer\sources.py", line 170, in get_contents

>     assert record is not None, "In {}, {} is not mentioned in RECORD".format(

> AssertionError: In C:\Users\username\AppData\Local\Temp\pip-unpack-1_rv_b2f\xgboost-1.5.2-py3-none-win_amd64.whl, xgboost-1.5.2+742c19f3ecf2135b4e008a4f4a10b59add8b1045.data/data/xgboost/vcomp140.dll is not mentioned in RECORD

>

> Traceback (most recent call last):

>   File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main

>     return _run_code(code, main_globals, None,

>   File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code

>     exec(code, run_globals)

>   File "C:\Users\username\AppData\Local\Programs\Python\Python39\Scripts\pdm.exe\__main__.py", line 7, in <module>

>   File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\pdm\core.py", line 233, in main

>     return Core().main(args)

>   File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\pdm\core.py", line 168, in main

>     raise cast(Exception, err).with_traceback(traceback)

>   File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\pdm\core.py", line 163, in main

>     f(options.project, options)

>   File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\pdm\cli\commands\add.py", line 53, in handle

>     actions.do_add(

>   File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\pdm\cli\actions.py", line 245, in do_add

>     do_sync(

>   File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\pdm\cli\actions.py", line 190, in do_sync

>     handler.synchronize()

>   File "C:\Users\username\AppData\Roaming\Python\Python39\site-packages\pdm\installers\synchronizers.py", line 352, in synchronize

>     raise InstallationError("Some package operations are not complete yet")

> pdm.exceptions.InstallationError: Some package operations are not complete yet

**Comment by frostming** [comment]
Duplicate with #728
