### ISSUE TITLE
Improve usability for library development

### ISSUE THREAD

**Issue by AnOctopus** [pdm-project/pdm#972]
## Is your feature request related to a problem? Please describe.

I work on an [open source framework](https://github.com/streamlit/streamlit) and would like to be able to switch us to pdm, but the interaction of several features and design decisions makes it currently not work well for our use case. I can see many potential ways this could be improved, so it seems better to describe the situation rather than jump to any particular change.

1. We are a library, and so do not commit lock files for python dependencies, since our code needs to be able to work with any versions of dependencies allowed by our version bounds anyway.
2. We have several dev dependencies for testing integrations with third party libraries, including libraries like older tensorflow versions that aren't available on python 3.10, or M1 macbooks, and so those tests and dependencies are optional for some devs.
3. We bound the python version for our package as the minimum version needed for the language features we use. There is no good reason to set an upper bound.
4. The `requires-python` field in the pyproject file is used by pdm for both the package version (so we want it to just have a lower bound), and for requiring that resolved dependencies work on all python versions permitted by the field.
5. I have seen it explained that the second behavior from 4 is to ensure the lock file is always valid. But as noted in 1, this isn't useful to us.
6. The second behavior of 4 leads to unusably long resolution times if the version range in `requires-python` doesn't have a strict upper bound, which conflicts with the version range the package should have.

## Describe the solution you'd like

A few possibilities:
- Split `requires-python` into two fields, one for the versions in the package metadata, and one for resolving dependencies for local development.
- Add a way to have version resolution ignore python upper bounds in dependencies. There are a few legitimate uses for having them, but so many libraries add them unnecessarily in ways that break dependency tools and I'd rather deal with the legitimate cases manually.
- Add a way to relax the requirement that a lock file be valid for all versions allowed by `requires-python`, so the python version could be treated like other dependencies and work nicely for developing libraries that don't commit and share lock files.

**Comment by frostming** [comment]
IMO what you should do is to restrict the env marker of the specific dependencies that do not work on all python versions specified by `requires-python`.

```toml
[too.pdm.dev-dependencies]
test = [
    "tensorflow; python_version < '3.10' and platform_machine != 'arm64'"
    ...
]
```
In this way the resolver will correctly resolve `tensorflow` and skip the package on installation if the env doesn't match. I suppose you don't know this trick. Have a try and let's see what is left.

**Comment by AnOctopus** [comment]
I tried that previously and it worked for a few dependencies, but ran into some issues and assumed it didn't work or that I didn't understand how it was supposed to work. Trying again just now, it works fine initially, but I ran into weird behavior with markers for tensorflow and scipy. With restricting scipy and tensorflow to python < 3.10 and not ARM, it resolves after a bit, but when I relax the bound on scipy to < 3.11, which should be satisfied by 1.7.3 which was previously selected, pdm starts rejecting `tensorflow-io-gcs-filesystem 0.24.0` due to python version conflicts, even though the version bound on tensorflow wasn't changed and it worked previously.

**Comment by frostming** [comment]
> I tried that previously and it worked for a few dependencies, but ran into some issues and assumed it didn't work or that I didn't understand how it was supposed to work. Trying again just now, it works fine initially, but I ran into weird behavior with markers for tensorflow and scipy. With restricting scipy and tensorflow to python < 3.10 and not ARM, it resolves after a bit, but when I relax the bound on scipy to < 3.11, which should be satisfied by 1.7.3 which was previously selected, pdm starts rejecting `tensorflow-io-gcs-filesystem 0.24.0` due to python version conflicts, even though the version bound on tensorflow wasn't changed and it worked previously.

If any sub-dependency has a narrower `requires-python` than the project's, you also need to restrict it with markers in `dependencies` array.

**Comment by frostming** [comment]
But be aware, using the method makes the dependencies OPTIONAL. For a library, you must guarantee it works on all python versions promised in `requires-python`. Otherwise, when people install it on, for instance, Python 3.11, some dependency may be missing and the library becomes broken.

**Comment by AnOctopus** [comment]
Somehow, even though I don't recall changing anything about my dependency configuration, attempting to install went from having the issue [described here](https://github.com/pdm-project/pdm/issues/972#issuecomment-1068177745) to resolving. There's still some issue with not being able to run the installed editable package that I'll have to look into, but this is promising for being able to use pdm for our project.
