### ISSUE TITLE
Add pdm parse to dependabot

### ISSUE THREAD

**Issue by abersheeran** [pdm-project/pdm#978]
## Describe the solution you'd like

https://github.com/dependabot/dependabot-core/tree/main/python/lib/dependabot/python/file_parser

**Comment by frostming** [comment]
Unfortunately dependabot [has stopped accepting new ecosystems](https://github.com/dependabot/dependabot-core/blob/main/CONTRIBUTING.md#contributing-new-ecosystems).

But we can make a dedicated github action from a fork of dependabot-core, like [dependabot-lein-runner](https://github.com/CGA1123/dependabot-lein-runner).

Thanks for the info

**Comment by Secrus** [comment]
I recently stumbled upon this article: https://www.oddbird.net/2022/06/01/dependabot-single-pull-request/. Maybe this is something to consider for PDM? I would be glad to try myself in implementing that. What do you think @frostming?

**Comment by frostming** [comment]
> I recently stumbled upon this article: https://www.oddbird.net/2022/06/01/dependabot-single-pull-request/. Maybe this is something to consider for PDM? I would be glad to try myself in implementing that. What do you think @frostming?

Thank you, just go for it.

**Comment by madkinsz** [comment]
Hm, they do say

> If you are an ecosystem maintainer and are interested in integrating with Dependabot, and are willing to help provide the expertise necessary to build and support it, please open an issue and let us know.

You may be able to get them interested if you have the time to coordinate with them.

**Comment by sanmai-NL** [comment]
It'd to good to take into account other platforms than GitHub. For example, GitLab integrates with dependabot in its own way and I know a lot of Python products are hosted on GitLab instances, for one because of their Package Registry. If coordinating with the Dependabot dev team helps with that, over building some alternative integration, then I'm all for it.

**Comment by ivarnakken** [comment]
@frostming Do you have plans on coordinating with the dependabot team any time soon? Having dependabot is important at our end, and is a bottleneck in our transition to PDM ❤️

**Comment by sanmai-NL** [comment]
I use [Renovate](https://docs.renovatebot.com/modules/datasource/) instead. But that supports PDM neither.

**Comment by sanmai-NL** [comment]
Their [contribution guidelines](https://github.com/renovatebot/renovate/blob/main/.github/contributing.md#code).

**Comment by frostming** [comment]
> @frostming Do you have plans on coordinating with the dependabot team any time soon? Having dependabot is important at our end, and is a bottleneck in our transition to PDM ❤️

I have no such plan myself. Volunteers can take on this task. If you need an auto-updater we have https://github.com/pdm-project/update-deps-action

**Comment by carstencodes** [comment]
According to latest documentations, renovatebot has support for PEP621 managers and PDM is one of them..
