### ISSUE TITLE
PDM-installed streamlit fails to launch a server

### ISSUE THREAD

**Issue by baggiponte** [pdm-project/pdm#989]
## Steps to reproduce

Add `streamlit` and `watchdog` to a pdm-managed python project. PDM will install the latest version, which as of today is 1.7. Then execute `pdm run streamlit hello` to view the demo.

## Actual behavior

<details>
  <summary> pmd-streamlit hello log </summary>

```
❯ pdm run streamlit hello
2022-03-23 12:03:44.653 WARNING streamlit.config:
Warning: the config option 'server.enableCORS=false' is not compatible with 'server.enableXsrfProtection=true'.
As a result, 'server.enableCORS' is being overridden to 'true'.

More information:
In order to protect against CSRF attacks, we send a cookie with each request.
To do so, we must specify allowable origins, which places a restriction on
cross-origin resource sharing.

If cross origin resource sharing is required, please disable server.enableXsrfProtection.

2022-03-23 12:03:44.658 DEBUG   streamlit.logger: Initialized tornado logs
2022-03-23 12:03:44.661 DEBUG   matplotlib.pyplot: Loaded backend agg version unknown.
2022-03-23 12:03:44.662 DEBUG   streamlit.bootstrap: Setting up signal handler
2022-03-23 12:03:44.662 DEBUG   asyncio: Using selector: KqueueSelector
2022-03-23 12:03:44.676 DEBUG   streamlit.server.server: Starting server...
2022-03-23 12:03:44.676 DEBUG   streamlit.server.server: Serving static content from the Node dev server
2022-03-23 12:03:44.686 DEBUG   streamlit.server.server: Server started on port 8501
2022-03-23 12:03:44.687 DEBUG   streamlit.server.server: Server state: State.INITIAL -> State.WAITING_FOR_FIRST_BROWSER
2022-03-23 12:03:44.848 DEBUG   git.cmd: Popen(['git', 'version'], cwd=/Users/luca/Documents/dev/oai/k2, universal_newlines=False, shell=None, istream=None)
2022-03-23 12:03:44.862 DEBUG   git.cmd: Popen(['git', 'version'], cwd=/Users/luca/Documents/dev/oai/k2, universal_newlines=False, shell=None, istream=None)
2022-03-23 12:03:44.882 DEBUG   git.cmd: Popen(['git', 'version'], cwd=/Users/luca/Documents/dev/oai/k2, universal_newlines=False, shell=None, istream=None)
2022-03-23 12:03:44.895 DEBUG   git.cmd: Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/luca/Documents/dev/oai/k2, universal_newlines=False, shell=None, istream=None)

  Welcome to Streamlit. Check out our demo in your browser.

  Local URL: http://localhost:3000
  Network URL: http://192.168.1.117:3000

  Ready to create your own Python apps super quickly?
  Head over to https://docs.streamlit.io

  May you create awesome apps!


2022-03-23 12:03:44.910 DEBUG   streamlit.version: Skipping PyPI version check
```

</details>

Then, when I connect to `localhost:3000` the connection fails. From my poor server/httpd knowledge, I believe the server does not launch.

## Other attempts

I installed `streamlit` again using `pipx` and when I launch the same command the prompt is much more concise:

<details>
  <summary>pipx-streamlit hello log</summary>

```
❯ streamlit hello

  Welcome to Streamlit. Check out our demo in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.1.117:8501

  Ready to create your own Python apps super quickly?
  Head over to https://docs.streamlit.io

  May you create awesome apps!
```

</details>

**Notably, a different port is chosen: 8501 instead of 3000.**

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.13.5
Python Interpreter: /Users/luca/.pyenv/versions/3.9.9/bin/python (3.9)
Project Root:       /Users/luca/Documents/dev/oai/k2
Project Packages:   /Users/luca/Documents/dev/oai/k2/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.9",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "21.4.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64",
  "python_full_version": "3.9.9",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "darwin"
}
```

**Comment by cye18** [comment]
Looks like streamlit is aware of this issue: https://github.com/streamlit/streamlit/issues/3132. According to their [document](https://docs.streamlit.io/library/get-started/installation#set-up-your-virtual-environment), they don't officially support PDM at this point, which is a shame. Hopefully when PDM gets more popular it won't be a problem anymore.

**Comment by cye18** [comment]
I just successfully launched the streamlit app with PDM on my machine. Hope it works for you as well.

Use a `--server.port` option in the command, i.e. `pdm run streamlit run app.py --server.port 8501`

I got an error saying `server.port does not work when global.developmentMode is true.` but it's solved by adding `--global.developmentMode false` in the end.

So the whole command that works for me is `pdm run streamlit run app.py --server.port 8501 --global.developmentMode false`.

Hope it's a legit solution :D

**Comment by baggiponte** [comment]
thank you everyone for the prompt answers!

> I don't have enough energy to find out. As a maintainer of package manager I can't look into the problems of every particular package that complains not working.

@frostming sure - I did not mean to sound demanding. Thank you for taking the time. If you have any hints or gut feelings about where the problem resides I might try to have a look at that. 

@cye18 thank you for the answer! I noticed that the port (3000) was not the default one (8501). I modified the settings in `~/.streamlit/.config.toml` and subsequently got the error message `server.port does not work when global.developmentMode is true`. I was stuck because I could not find any reference to `global.developmentMode` in [streamlit docs](https://docs.streamlit.io/library/advanced-features/configuration#view-all-configuration-options).

I confirm that the solution works. You can also create a local `$CWD/.streamlit/config.toml` file inside your pdm-managed projects.
